### ISSUE TITLE
Write a user-defined function to propagate DELETE commands to all shards

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#10]
Write a user-defined function that extends and propagates DELETE commands to all the shards. This function doesn't need to be as safe as functionality that's built into Citus and should help in removing the need for customers to write their own scripts.

**Comment by ozgune** [comment]
@aamederen -- two quick clarification notes.

* We need this feature in the following scenario: The user hash partitions their data, for example say on the ``app_id`` column. They would then like to delete (expire) old rows based on time, say ``created_at``. This would translate into a ``DELETE`` statement that runs across all shards.
* The tricky part here is failure semantics. For example, let's say that we have four shards A, B, C, and D. What happens when we delete old rows from shard A, and B, and then fail to delete rows from C? I know @samay-sharma thought about this in the context of ``ALTER TABLE``. It's also worth surveying other parts of our codebase to decide on the failure semantics.

**Comment by aamederen** [comment]
The following are the technical e-mails for this issue:

@aamederen:
> I looked into the code for the options for this issue. 
> 
> When Murat was talking about the planner, he stated that distributed modify queries were allowed to hit only one shard because of difficulties in handling the failure cases. I think, if we provide support for modify queries within a distributed transaction, we can develop a more comprehensive solution for this issue. Metin told me that Marco is working on distributed transaction within the copy-for-hash-partitioning branch and I think that feature can be used in this issue. 
> 
> So, the possible options that came to my mind for this issue are:
> - Extend the functionality of master_apply_delete_command
> - Create multiple delete tasks in modify_planner (instead of one) for each shard and show a warning for failed modifications
> - Create multiple delete tasks, within a distributed transaction so that if the modification in any of the shards fail, we can roll everything up
> 
> As I side note, I think you have sent the last mail by mistake and Metin and I could not find Matt's requests from the e-mails and docs that we have. 

@marcocitus:
> Just some notes/context:
> 
> COPY opens up BEGIN; COPY ..; transactions on all the placements and
> if there is a failure it aborts all transactions. The only exception
> is a connection to an individual shard placement failing, in that case
> the placement is marked as inactive if the transaction completes. To
> deal with failures after the first transaction has committed, the user
> can set citus.copy_transaction_manager to '2pc' and set
> max_prepared_transactions to 100 or so on the worker nodes (needs to
> be at least the number of placements on the node). Failed commits can
> then be committed later.
> 
> Having multi-shard DELETE would be very useful as we shift more from
> append-partitioned to hash-partitioned tables. We are also going to
> start sending BEGIN; DELETE ... as part of Jason's UPDATE/DELETE
> improvements. So we should have a lot of the necessary infrastructure.
> 
> There is an obvious issue with not having global snapshot isolation.
> While the delete is being committed across the shards, other queries
> will see intermediate states where data has been deleted from some
> shards, but not others. I think this is more acceptable for
> multi-shard SELECT, COPY and DELETE than it is for multi-shard UPDATE.
> 
> A question is whether we need 2PC for delete. Many delete commands are
> idempotent, so simply re-running the delete might be a simpler path to
> recovery.

@ozgune:
> From a failure handling standpoint, this change has similarities with "COPY for hash" and "ALTER TABLE". We modify more than (potentially all) one shard in each case, and we'd ideally want this to be an all-or-nothing operation.
> 
> "COPY for hash" uses a configurable transaction manager. "ALTER TABLE" makes a best effort -- Samay, do we have the final logic captured in a document? Samay considered using 2PC here, but decided to check this in a future iteration. Some open questions with 2PC were the user setting max_prepared_transactions and failure handling at some stages in the algorithm.
> 
> * Could you schedule a call with Marco / Metin, pick one approach, and communicate the meeting notes to the team? Since this logic is contained in a udf, if need be, we could quickly change it later.
> * Could you capture this email thread in the Github issue (#10) as well?
> * Could you open a (lower priority) issue that evaluates "unifying our multi-node modify logic"? This way, we'd use the same logic across our changes in the future.

@aamederen:
> I have been investigating the codebase for possible approaches to DELETE on multiple shards.
> 
> In the handler of ALTER TABLE command lies the ExecuteCommandOnWorkerShards function, which calls the ExecuteRemoteQuery for each placement of each shard, which opens a connection to the related worker, issues the query and fetches the result. 
> 
> In Copy on Hash, as far as I understood, we send the rows one by one to the relevant shard and its replicas (asynchronously?), in a transaction.
> 
> Notice that both of these features are outside of our main planner/executor logic. For DELETE, we need to stay inside this data flow.
> 
> I have been getting my hands dirty and saw that modify planner is easy to change to allow multi-line modifications. However, the executor part is a little bit more challenging:
> Normally, modify operations go through the ROUTER EXECUTOR, which assumes that the query hits only one shard. However, we need a more comprehensive solution for this, which would open the necessary connections to multiple workers, issues the queries to shards and their replicas and mark the failed replicas.
> 
> When I think about it, this behavior is similar to what REAL TIME EXECUTOR or TASK TRACKER do. However, they are developed with SELECT queries in mind (COPY the result list to STDOUT, create a master table, prepare a SELECT query on the master table, send the query only to single replica, etc) and may require some significant changes. 
> 
> So, the possible ideas are:
> Dive into REAL TIME EXECUTOR or TASK TRACKER (or both) to make them work with modify queries.
> Create a new executor type and name it MODIFY EXECUTOR (or George*) which would open a distributed transaction, open connections to the relevant workers, issue the MODIFY queries, mark the failed shards and close the query as apropriate.
> Don't touch the planner/executor data flow and modify the existing master_apply_delete_command UDF.
> Ozgun, I understood from your e-mail that you are suggesting the UDF approach. We will meet with Metin and Marco early next week to decide in a solid plan.
> 
> * "I will name him George" is one of my favorite quotes :)

@ozgune:
> When prioritizing #10, our intent was to have a well-defined and scoped issue resolved. We could later look into extending on this approach -- for now, could we scope this feature as it's defined in Github (as a user-defined function)?
> 
> When we go with the user-defined function approach, failure handling semantics is still an open question. I'm in favor of the simpler approach primarily because it keeps the scope limited for #10. That said, I'm perfectly happy with the decision you guys reach.

@aamederen:
> We have discussed how should we approach the Delete on Multiple Shards issue and here is the notes from our meeting:
> Handling this in a UDF seems like the most suitable choice now.
> Writing an executor for the modify queries would be more complex and time consuming but beneficial for providing a structure for future modify features.
> We will left the existing master_apply_delete_command, since many of our customers rely on it; and create a new UDF. It would be nice to have the name for the new UDF though. We will probably name this new UDF something like master_push_delete_command.
> For consistency, we will reuse the two-phase transaction (multi_transaction and CopyTransactionManager) used by COPY on hash. For that, we should change the name of CopyTransactionManager to something like ShardTransactionManager before 5.1.

**Comment by aamederen** [comment]
@ozgune suggested that, after we merge the master_delete_from_shards UDF, during a DELETE query on modify planner, we can 

- call this UDF behind the covers or
- give some information about master_delete_from_shards UDF
