### ISSUE TITLE
When staging to a foreign table, if we put a semi-colon at the end, this gets detected as an 'option', thus giving the error: "options not supported for foreign tables". We should distinguish between a trailing semi-colon and actual options like 'with delimiter'

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#100]
When staging to a foreign table, if we put a semi-colon at the end, this gets detected as an 'option', thus giving the error: "options not supported for foreign tables". We should distinguish between a trailing semi-colon and actual options like 'with delimiter'

**Comment by metdos** [comment]
Fixed with #416, #445 and #468.
