### ISSUE TITLE
Prevent co-location of MX and non-MX Tables

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#1009]
Colocation of MX and nonMX tables may have some challenges, mainly because metadata and distributed tables of only MX tables are propagated to workers.

One of the main deal-breakers are foreign keys. If an MX table refers to a non-mx table, then the propagation would fail, since the non-mx table metadata will not exist in the workers.

Disabling specific features is another option but it is safer to prevent colocation of mx and non-mx tables for now.

**Comment by metdos** [comment]
@aamederen, I think I fixed this issue with this commit: https://github.com/citusdata/citus/commit/e2d0bd38f2ba924dc8a1f825b32b2786a3b2a775

Could you verify that? And if yes, could you close this issue?

**Comment by aamederen** [comment]
@metdos, I have tested this and indeed your commit seems to fix this issue.

One thing I notice is that, `colocate_with` option does not allow colocation with an mx table:

```
SET citus.shard_replication_factor TO 2;
SET citus.shard_count = 8;
CREATE TABLE nonmx_table_temp (a int);
SELECT create_distributed_table('nonmx_table_temp', 'a', colocate_with=>'mx_table');
ERROR:  cannot colocate tables mx_table and nonmx_table_temp
DETAIL:  Replication models don't match for mx_table and nonmx_table_temp.
```

There, I would expect `nonmx_table_temp` to a streamed replicated table colocated with `mx_table`.

@marcocitus @ozgune what do you think? Is it worth fixing that?

**Comment by metdos** [comment]
> @marcocitus @ozgune what do you think? Is it worth fixing that?

This happens because currently, 'c' is the hard coded replication model. We can fix this by getting `repmodel` of the table to colocate with and passing it through other functions. Overall, this a quick fix if we want to add this feature.

**Comment by marcocitus** [comment]
> There, I would expect nonmx_table_temp to a streamed replicated table colocated with mx_table.

We can't have streaming replication tables with replication factor > 1, so one way or another this should error out.

**Comment by ozgune** [comment]
@metdos -- This looks like a separate issue. Could we open a new issue with this description and close this one?

**Comment by metdos** [comment]
@aamederen, looking into your PR #1045, we can say that if replication count is 1, we will use 's', otherwise, we will use 'c'. Therefore, I think we're good here and I'm not opening a new issue.
