### ISSUE TITLE
Release quality: Packaging simplification - Investigate

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1014]
We currently have a number of distribution/deployment methods for Citus.

* Tutorials (custom single node binaries)
* Redhat based packages (single and multiple node)
* Ubuntu based packages (single and multiple node)
* Docker
* Homebrew packages
* CloudFormation templates
* Citus Cloud (managed cloud)
* Build from source

We need to evaluate how effective each method is and investigate if we could reduce the number of distribution methods available for Citus -- with the intent to provide a better experience overall.

**Comment by metdos** [comment]
The use of Snappy(see http://snapcraft.io/) is mentioned on the Slack channel (https://citus-public.slack.com/archives/general/p1481032742000019)

**Comment by ozgune** [comment]
We had an internal conversation on this.

We decided to stop officially supporting our Homebrew packages. In particular, we're going to stop updating Homebrew packages with each release and we're going to remove installation steps for Homebrew from our website.

For users looking to evaluate Citus on OS X, we're going to guide them to using Docker.

**Comment by jasonmp85** [comment]
Had to laugh at this…
<img width="207" alt="screen shot 2017-02-26 at 11 54 37 pm" src="https://cloud.githubusercontent.com/assets/50673/23351522/f5edbcec-fc7e-11e6-881a-a061312950a8.png">

**Comment by jasonmp85** [comment]
By now, I think also the tutorial is guided toward Docker, no? Have we simplified enough, or does this issue have further tasks?
