### ISSUE TITLE
Comprehensive cstore integration with Citus.

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus#1015]
There is no specific(comprehensive) model which describew on how to integrate cstore in a distributed setup. The below are some of the necessary items to enable this:

1. Add/update/review features to cstore_fdw/citus in the context of a distributed setup.
2. Come up with suitable data modeling approaches(similar to how we have tenant based and entity based sharding approaches) on how cstore could be used with Citus.
3. Come up with documentation to complement all the above.

The topic of data compression comes up in many prospect engagements. Recently it came up in 2 specific discussions in which each prospect were expecting over 100s of TB of data and data compression was an important factor.

(The above description could be changed in the future, but just wanted to create an issue for documentation purposes)

**Comment by marcocitus** [comment]
Fixed by #4311
