### ISSUE TITLE
After a co-located join, the resulting table could be said to be partitioned on multiple columns, but we only chose one. This could lead to unnecessary repartitioned joins and performance degradations

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#102]
Join-order planning bug: After a local-join, the resulting table could be said to be partitioned on multiple columns, but we only chose one. e.g. o_orderkey = l_orderkey and l_orderkey = c_orderkey. In this case, if we pick o_orderkey as the partition-column after the first local-join, join-order planning decides to re-partition the data.

**Comment by marcocitus** [comment]
I believe this is fixed.
