### ISSUE TITLE
Replicate global objects to new and existing workers

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1026]
We currently have hacky workarounds for propagating schemas and sequences that are used in distributed tables on shard creation, which require yet more hacky workarounds to prevent deadlock, drop tables, and deal with new nodes. Other relevant objects are not replicated at all (roles, types, functions, extensions, ...), which may make adding new workers rather tedious (e.g. when using a composite type). 

Ideally, we would automatically replicate objects to workers when the object is created or first used, or when a new worker joins the cluster. Alternatively, we could ask the user to explicitly call a function to replicate certain objects, e.g. `SELECT distribute_type('my_composite_type')`. This function could recursively replicate dependent types. It may be necessary to keep track of which objects are replicated to replicate all marked objects when a new node joins.

A more generic way of doing this would be to specify a "start-up" command that gets immediately run on all existing workers, and on new workers when they join `SELECT add_worker_command($$CREATE TYPE ...$$)`. This could also be an extension of citus-tools where we store the command in something like `pg_dist_startup_command` and execute all commands on a new node when `master_add_node` is called. We could also consider calling this function automatically for any object that is created on the master/coordinator after the Citus extension is created.

Given that we now have infrastructure for performing transactions across workers for MX, it should now be relatively straight-forward to propagate commands to all workers in a transactional way. For reference tables, we'll need to add infrastructure to replicate a table to a new node (#971) when it joins. We could use the same infrastructure for creating other global objects.

**Comment by mtuncer** [comment]
My understanding of ```global objects```  are types and schemas. 
Following are excluded
- functions
- aggregates
- triggers
- sequences
- prepared statements
- tables and views

If we limit this to just types and schemas, we can tap into type/schema creation and keep those inside a table, (possibly with dependencies).  We should also tap into alter/drop type/schema to update the table as needed.

**Comment by jasonmp85** [comment]
Having recently used `pg_upgrade`, I think its code (and `pg_dump` and `pg_restore`) provides good guidance for what needs to be recreated to mirror a database. Maybe someone could walk through that (it's somewhat highly abstracted, but the log messages it emits should help a reader figure out what each section does) to get a full list of objects we might want to consider.

**Comment by ozgune** [comment]
I'm also noting #376 as a related issue.

**Comment by marcocitus** [comment]
We have more objects to cover, but the infrastructure for this is in place and many object types are supported.
