### ISSUE TITLE
Transaction recovery must not run during prepare phase of other transactions

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1030]
We currently don't prevent `SELECT recover_prepared_transactions()` from running while other backends might be sending `PREPARE TRANSACTION..` commands. This means that `recover_prepared_transactions` might see prepared transactions on a worker without (visible) records in `pg_dist_transaction`. In that case, the transaction recovery logic will conclude that the transactions in question must have been aborted and try to roll them back, even though they might have to be committed. 

In MX this was addressed by taking a lock at the start of a distributed transaction, but we missed this change during MX integration:
https://github.com/citusdata/citus-mx/blob/masterless/main/src/backend/distributed/transaction/commit_protocol.c#L53

It may also be better to take the lock just before the first `PREPARE TRANSACTION..` command is sent.

The impact of this is currently low as transaction recovery is only enabled for metadata syncing, but will be high once we implement #1023 as it could cause data loss.

**Comment by marcocitus** [comment]
This doesn't seem to be an issue anymore since `RecoverPreparedTransactions` blocks `LogTransactionRecord` and `LogTransactionRecord` is called prior to sending `PREPARE TRANSACTION ...`.

**Comment by ChenHuajun** [comment]
when `SELECT recover_prepared_transactions()` was called before some workers had execute "PREPARE TRANSACTON ..." and others are not in a concurrent transaction, data loss would occurs.

I have reproduced this scene with gdb.

1. set breakpoint in StartRemoteTransactionPrepare()
2. update a reference table
3. continue when enter StartRemoteTransactionPrepare() for worker1
4. execute `SELECT recover_prepared_transactions()`

        [postgres@sndsdevsdd03 ~]$ psql testdb -p9700 -c "select recover_prepared_transactions()"
        NOTICE:  recovered a prepared transaction on localhost:9701
         recover_prepared_transactions 
        -------------------------------
                                     1
        (1 row)
5. continue when enter StartRemoteTransactionPrepare() for worker2

        testdb=# insert into ref_tb values(1,'c');
        WARNING:  prepared transaction with identifier "citus_0_8250_8" does not exist
        WARNING:  failed to commit transaction on localhost:9701
        WARNING:  failed to roll back prepared transaction 'citus_0_8250_8'
        HINT:  Run "COMMIT PREPARED 'citus_0_8250_8'" on localhost:9701
        INSERT 0 1

insert successed in worker2

    [postgres@sndsdevsdd03 ~]$ psql testdb -p9702 -c "select count(*) from ref_tb_102026"
     count 
    -------
         1
    (1 row)

insert failed in worker1, ang can not execute 2pc recovery.

    [postgres@sndsdevsdd03 ~]$ psql testdb -p9701 -c "select count(*) from ref_tb_102026"
     count 
    -------
         0
    (1 row)

    [postgres@sndsdevsdd03 ~]$ psql testdb -p9701 -c "select pg_prepared_xact()"
     pg_prepared_xact 
    ------------------
    (0 rows)

**Comment by marcocitus** [comment]
@ChenHuajun is this on the master branch or an older version of Citus?

**Comment by ChenHuajun** [comment]
i tested on citus 6.2.1

**Comment by ChenHuajun** [comment]
I had tried the master master branch again, and the result is same.

**Comment by marcocitus** [comment]
> This doesn't seem to be an issue anymore since RecoverPreparedTransactions blocks LogTransactionRecord 

It seems `LogTransactionRecord` releases the lock immediately, which is a bug.

**Comment by marcocitus** [comment]
Fixed by 3d7f7912
