### ISSUE TITLE
Citus Cloud upgrade issue across Citus and Postgres versions

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1036]
I'm copy/pasting @fdr's internal email on this below. I'm also noting #907 as a related issue.

---

The current situation: someone using Citus Packages is liable to break their cluster if they run a system update, e.g. via `yum upgrade` or `apt-get upgrade`.

It also makes it impossible to have a single machine image (e.g. AWS AMI) capable of servicing an operation running multiple major versions (e.g. 5, 6) of Citus at the same time.

Citus Cloud uses `yum` and lightly modified `PGDG` packaging programs, and so it suffers these problems, much as an end-user would.

This is because Citus 5.X catalogs and operations are not compatible with Citus 6.X, but as-is Citus 6.X will silently overwrite 5.X.  Two ways to prevent this issue are discussed later.

## How Citus Cloud Installs Citus

A maintainer of Citus Cloud will create new AMI snapshots that are used as the basis for deployment.  New servers then use this AMI. This includes newly created servers for failover, even on existing
formations.

This image includes Linux version and all user versions. It is a disk image of the entire root file system.

During this AMI build process, `yum` is run somewhat like this:

<pre>
    yum install -y \
      autoconf \
      citus_95 \
      citus_95-debuginfo \
      citus_96 \
      citus_96-debuginfo \
      daemonize \
      dnsmasq \
      dstat \
      emacs-nox \
      gdal-debuginfo \
      gdb \
      geos-debuginfo \
      git \
      hll_95 \
      hll_95-debuginfo \
      hll_96 \
      hll_96-debuginfo
</pre>
 
The problem is, what version of Citus should be contained in `citus_95` and `citus_96`?  Should these be 5.2, or 6.0?

To best cope with the current situation, I have chosen that `citus_95` will be 5.X and `citus_96` will contain 6.X.  PGDG has chosen to upgrade `citus_95` directly from 5.2 to 6.0, (perhaps out of
ignorance?) and thus anyone running a system `yum upgrade` or prepares a new system running the same `yum install` will break a cluster or get a new behavior likely without being aware of it.

In general, the problem is that we need to be able to control when an upgrade takes place and take action for it, as well as give control and adjustment warning tot he user, rather than changing
behavior/upgrading implicitly.

## Ways to Solve It

There are two ways to solve this:

A root problem here is that a package name like `citus_95` should be two packages, akin to `citus5_95` and `citus6_95`.  In this way, if one has `citus5_95` installed and runs `yum upgrade`, one gets a
backwards compatible binary that requires no user action.  Both solutions have adding a major version to the package name in common.

The question then becomes: what happens when one installs `citus6_95`?

As-is, this would present a problem: packages cannot have conflicting files.  If a hypothetical `citus5_95` and `citus6_95` were to be installed at the same time, as-is they'd conflict on both installing a file like `/usr/lib/pgsql-9.5/lib/citus.so`.  Note that there is no Citus version on `citus.so`.

## Solution: Full Dual-Install Compatability

One solution is encoding the version name into the `.so` as well, such as `citus5.so` and `citus6.so`, which requires modification of the Citus extension control files.  All else being equal, this would be
preferred.

## Solution: Declare Conflict and Replace

A second option is to use the `Conflict` feature seen in most package managers, such that `citus5_95` is marked as incompatible with `citus6_95`, and installing one will replace the other.  Because `yum
upgrade` and `yum install` would no longer change behaviors silently (as `citus5_95` would always contain a 5.X release), this solves the silent-upgrade problem.

However, it comes at a cost when one is ready to perform an upgrade: one cannot install both packages ahead of time, but one must install the new package at the time of upgrade and not before.

However, using this approach spares one having distinct `.so` file names.

## Conclusion

At a minimum, we'll need multiple package names, one per release branch that is maintained.

You might notice that this is effectively what Citus Cloud does by co-opting the existing name and path mangling applied to each extension package to handle multiple Postgres versions at the same
time (e.g. the suffix `_95` and `_96` seen in package names, and their disparate paths in `/usr/pgsql-9.5` and `/usr/pgsql-9.6`)

A key question to answer is how worthwhile it is to *also* make multiple Citus versions installable at the same time.  This is preferred.

**Comment by ozgune** [comment]
@fdr / @jasonmp85 -- I know that we're making changes to our packaging policy. Does this issue reflect a dated understanding? What's a good description of how we're planning to move forward?

**Comment by fdr** [comment]
It'd be better to use @sumedhpathak's recounting of the issue after our meeting. I think this thing I wrote is only useful for archival.

**Comment by serprex** [comment]
@ozgune with the state of Citus Cloud can this issue be closed?

**Comment by marcocitus** [comment]
We follow the "Declare Conflict and Replace" approach in package cloud.
