### ISSUE TITLE
How to install citus as a pure extension?

### ISSUE THREAD

**Issue by minimok** [citusdata/citus#1037]
I have a requirement to use plv8. This means that your combined postgres-citus server will not work - it's simply not possible to build the plv8 library against it. So I need to:
1. download a vanilla postgres e.g. postgres-server-dev
2. build the plv8 against that and install
3. install citus as a simple extension

Is there an idiot's guide on how to just get citus as a pure extension and build/install it?

Apropos - it really should be possible in 2016 to have a single postgres build-file where we declare all the extensions we want in one place and the whole process just 'works'...

**Comment by lithp** [comment]
Our [CONTRIBUTING.md](https://github.com/citusdata/citus/blob/master/CONTRIBUTING.md) file has instructions on building and installing citus from source. It's pretty straightforward, just make sure that pg_config points to the postgres installation you wish to use.
