### ISSUE TITLE
Implement distributed (VACUUM|ANALYZE) VERBOSE

### ISSUE THREAD

**Issue by jasonmp85** [citusdata/citus#1050]
In #1013, we implemented all options of `VACUUM` and `ANALYZE`, except `VERBOSE`.

Adding the `VERBOSE` option would require routing and displaying output from all worker nodes during `VACUUM`/`ANALYZE` execution: the implementation we chose was relatively straightforward and non-intrusive and the added code complexity of `VERBOSE` didn't seem worth it in a first pass at the `VACUUM` feature.

When a use case presents itself, this ticket will be waiting.

**Comment by mtuncer** [comment]
@ozgune This feature is requested by a user.
