### ISSUE TITLE
ALTER TABLE commands display notice about Citus' transaction commit protocol

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1059]
When the user runs an ``ALTER TABLE`` command for the first time, we display a notice message about the distributed commit protocol Citus is using. We also hint to the user to enable 2PC for extra safety.

<pre>
postgres=# ALTER TABLE products ADD short_id text NULL;
NOTICE:  using one-phase commit for distributed DDL commands
HINT:  You can enable two-phase commit for extra safety with: SET citus.multi_shard_commit_protocol TO '2pc'
ALTER TABLE
</pre>

We heard questions about ALTER TABLE and its commit protocol on Slack and over email. Ideally, the user wouldn't need to know about these details -- particularly during early stages of development.

Two options:

1. Reword this notice and hint message
2. Citus now enables 2PC without the user having to change their postgresql.conf settings. We could therefore default to 2PC.

If we go with the second option, we also want to be careful that we don't exhaust system resources. At a minimum, we should check that the number of shards we're going to touch is less than ``max_prepared_transactions``.

I'm also noting #709 and #710 as semi-related issues on checking if we have adequate resources to complete an operation.

**Comment by anarazel** [comment]
I vote for 2).  I don't think ```max_prepared_transactions``` is that much of an issue, because we'll usually run out of connections first.  I.e. the fix is to reduce the number of connections needed, not to use less 2PC.
