### ISSUE TITLE
We get this warning when compiling on a Mac: worker_merge_protocol.c:171:49: warning: format specifies type 'unsigned long long' but the argument has type 'uint64' [-Wformat]. A similar warning is thrown in worker_partition_protocol

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#106]
We get this specific warning when compiling on a Mac:worker_merge_protocol.c:171:49: warning: format specifies type 'unsigned long long' but the argument has type 'uint64' (aka 'unsigned long') [-Wformat]. A similar warning is thrown in worker_partition_protocol. There was a reason to set it up that way, rather than using UINT64_FORMAT, but we don't currently know why. Logging this as a low-priority to-do.

**Comment by serprex** [comment]
@onderkalaci do you have this warning? Pinging you since you're the person using a mac off the top of my head. If not, this can be closed

**Comment by onderkalaci** [comment]
> @onderkalaci do you have this warning? Pinging you since you're the person using a mac off the top of my head. If not, this can be closed


No, I don't see such warning
