### ISSUE TITLE
Difference between part_replica_count and shard_replication_factor

### ISSUE THREAD

**Issue by HackerMD** [citusdata/citus#1064]
```sql
SET citus.shard_replication_factor = 1;
CREATE TABLE foo ...
CREATE TABLE bar ...  # FOREIGN KEY constraint referencing foo.id
SELECT master_create_distributed_table('foo');
SELECT master_create_distributed_table('bar');
```

```sql
select * from master_get_table_metadata('foo');
```

```
 logical_relid | part_storage_type | part_method | part_key | part_replica_count | part_max_size | part_placement_policy
---------------+-------------------+-------------+----------+--------------------+---------------+-----------------------
      14961915 | t                 | h           | id       |                  2 |    1073741824 |                     2
```

```sql
select * from master_get_table_metadata('bar');
```

```
 logical_relid | part_storage_type | part_method |   part_key   | part_replica_count | part_max_size | part_placement_policy
---------------+-------------------+-------------+--------------+--------------------+---------------+-----------------------
      14961926 | t                 | h           | foo_id       |                  2 |    1073741824 |                     2
```

What's the difference between `shard_replication_factor` and `part_replica_count`?

The docs say

> part_replica_count: Current shard replication count.

But is this correct? I'm sure that I set `shard_replication_factor` to 1, because the distribution with foreign keys would not have worked. Is my data now being replicated or not?

**Comment by HackerMD** [comment]
I realized this only happens when I log out from `psql` in between. When I set the `shard_replication_factor` again upon login:

```sql
set citus.shard_replication_factor = 1;
select * from master_get_table_metadata('foo');
```

I get `part_replica_count` of 1.

```
 logical_relid | part_storage_type | part_method | part_key | part_replica_count | part_max_size | part_placement_policy
---------------+-------------------+-------------+----------+--------------------+---------------+-----------------------
      14961915 | t                 | h           | id       |                  1 |    1073741824 |                     2
```

How is the `shard_replication_factor` used? Do I need to set it upon every connection or is the display of  `master_get_table_metadata` incorrect?

**Comment by marcocitus** [comment]
The `part_replica_count` simply reflects the current value of `shard_replication_factor`. The `master_get_table_metadata` function was previously used to communicate the properties of new shards in append-distributed tables to clients, including the current value of `shard_replication_factor`. We have since moved on to other ways of creating shards, either upfront when creating a hash-distributed table through `create_distributed_table` or using `master_create_empty_shard` for append-distributed tables. Both functions use the value of `shard_replication_factor` when they are called.
