### ISSUE TITLE
Evaluate making the concept of replication models explicit

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1065]
We're planning to reduce Citus' default replication factor to 1. We're talking about this change and our motivations for making it in #998.

@marcocitus talks about Citus' replication models and its implications for the default replication factor in [this comment](https://github.com/citusdata/citus/issues/998#issuecomment-263838050) in that issue talks about Citus' replication models.

>> One option I've discussed with @aamederen and @metdos is to introduce a new GUC along the lines of default_replication_model which could either be 'coordinator' or 'streaming'. If it is set to 'streaming', then then table will be synced to workers, but the replication factor cannot be increased.

>> Another option is to treat all tables with replication factor 1 as 'streaming' tables and sync them with MX (this is the current approach in MX). This means you can never increase the replication factor later on, which might be ok.

We need to evaluate and resolve this decision before our v6.1 release. Between these two options, having another config setting that indicates the replication model sounds like the correct approach. That said, it also introduces the following questions:

* Does the ``default_replication_model`` default to 'coordinator' or 'streaming'?
* When can you change it this setting? Are there any restrictions on changing this setting?

I also wanted to capture the following points in this issue.

1. Citus Cloud has a check that disables increasing the replication factor. AFAIK, that's the only Citus related change the Cloud team has. @fdr / @lfittl -- if we introduce the ``replication_model`` setting, could you remove that change?
2. We have an extra column in metadata for ``part_replica_count``. This may cause some confusion (#1064). Do you want to remove this column?
3. When the replication factor is set to 1, we mark a table's replication model to 'streaming' in the [master branch](https://github.com/citusdata/citus/issues/1009#issuecomment-268042595). Do we keep this behavior?
4. We also have a flag for ``all_modifications_commutative``. Do we bypass that flag when the replication factor is set to 1?

Also, the following upgrade related questions are both relevant for #998 and this issue.

1. If a customer who has append distributed tables wants to upgrade, should we just default to 2 for them?
2. What happens when a customer with hash distributed tables (and uses statement based replication) upgrades? What's our behavior for their existing tables?
3. What happens when Citus Cloud customers upgrade?

**Comment by metdos** [comment]
> When the replication factor is set to 1, we mark a table's replication model to 'streaming' in the master branch. Do we keep this behavior?

Just a note: If we change this, we need to make sure that we don't allow 'streaming' and 'coordinator' tables to be colocated.

**Comment by onderkalaci** [comment]
We also added `2pc` replication model for reference tables. That replication model is the same with `coordinator` replication model except for that executor chooses to use `2pc` for modification queries.

**Comment by marcocitus** [comment]
We had a meeting on this issue today with @ozgune @lfittl @anarazel @onderkalaci .

We've decided to introduce a GUC that defaults to 'coordinator' and leave upgrading to 'streaming' to specific deployments such as cloud. Marking a distributed table as 'streaming' enforces a replication factor of 1. Right now, the main advantage is that it enables MX for hash-distributed tables after calling `start_metadata_sync_to_node`. In the future, we may tie additional logic to the 'streaming' replication model such as the ability to query shard placements on secondaries (provided that those are known to Citus).

Upgrading a Citus deployment involves setting the GUC to 'streaming' and updating the repmodel column for existing tables with replication factor 1 to 's'. This can be done at any time after upgrading to 6.1.

Additional notes:
- It seems like `citus.replication_model` would be an appropriate name for the GUC.
- This GUC should only be settable by an administrator.
- When replication model is 'streaming', this should apply to append- and range-distributed tables as well.
- There is an open question about whether 'coordinator' appropriately captures the current replication model.
- Reference tables always have the 't' replication model and are not affected by the GUC.

**Comment by ozgune** [comment]
@jasonmp85, I'm dropping a note from @umurc in this thread.

In an internal email thread on our [replication model blog post](https://www.citusdata.com/blog/2016/12/15/citus-replication-model-today-and-tomorrow/) (re: Blog post outline -- Re: Citus' replication model and reducing the default replication factor to 1 in v6.1), we decided to refer to these two replication models as 'streaming' and 'statement'. In GUC settings, we probably want to keep using this terminology.

This may introduce a discrepancy with the enum fields we use in our metadata tables ('c' and 's'). Since we don't document metadata tables, this discrepancy might be find.
