### ISSUE TITLE
Distinguish workers with and without metadata

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#1072]
Currently, distinguish between workers and the schema node is done via `pg_dist_local_group` entry, in which `groupid=0` means the current node is the schema node and `groupid>0` means a worker with metadata. This means that workers without metadata also have `groupid=0`, which could be a problem with temporary pauses to metadata syncs and also reliance on `pg_dist_local_group` entry. Most of the time, the workaround is setting `citus.enable_ddl_propagation` to off.

A solution could be:

- Distinguish between
    - coordinator node (`localGroupId = 0`)
    - worker with metadata (`localGroupId > 0`)
    - worker without metadata (`localGroupId = -1`)
- Set localGroupId of the added worker to -1 on master_add_node;

**Comment by marcocitus** [comment]
I think this distinction might be useful at some point, though I don't see an immediate need for it right now. Outside MX we don't have any restrictions on workers vs. the Master,. Workers could in fact act as master for other distributed tables. You could even turn shards into distributed tables and get (clunky) multi-level sharding. The non-restrictiveness is quite powerful.

**Comment by marcocitus** [comment]
It seems we've done this by adding a `hasmetadata` column to `pg_dist_node`.
