### ISSUE TITLE
Disallow CREATE/DROP SCHEMA from workers

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#1076]
In MX usage, allowing schemas to be dropped from the workers may cause harm.

If a distributed table exists within a schema, dropping that schema would cause shard and metadata loss, therefore this should be prohibited on the workers.

@onderkalaci suggests that, since users may want to create citus-unrelated stuff on a separate schema, disallowing to drop a schema would not be user friendly.

My take is that, on workers, `CREATE SCHEMA` as well as `DROP SCHEMA` (or even other commands like `CREATE TABLE`) should be disallowed, since the main purpose of connecting to workers are issuing queries to existing distributed tables.

@marcocitus what do you think?

**Comment by anarazel** [comment]
> > I can't see that being acceptable - people (like @samay-sharma ;)) do a lot of things on workers to import data. We can't prohibit that. If we want to prevent something like that we should use dependencies to prevent things we're interested in from being dropped.
>
> Yes, that makes a lot of sense. The question is, how can we do that?
> Is it possible to revoke permissions for things like `DROP SCHEMA` and
> `DROP TABLE` for citus-related objects?

> For example, it would be nice if we could revoke `DROP TABLE` for shard tables.

We could create dependencies from the citus extension to the shards.

I am however quite doubtful that this is a good idea. What are we
protecting against here?  It's e.g. not that unexpected to have to
delete shards manually if a node is unavailable. Or what if you're
looking at a restored backup/replica?

**Comment by aamederen** [comment]
> I am however quite doubtful that this is a good idea. What are we
protecting against here?  It's e.g. not that unexpected to have to
delete shards manually if a node is unavailable. Or what if you're
looking at a restored backup/replica?

My main idea is to put a barrier for accidental deletes. In MX, people will login to workers for MX queries, but it is very dangerous do allow them to drop anything, both for integrity and user experience. We error out on `DROP TABLE` to distributed tables but we have no control over shards/sequences/schemas/etc.

Maybe a GUC for `GOD MODE` changes or requiring superuser privilages can provide a safer experience.

**Comment by marcocitus** [comment]
I think it goes into a broader UX discussion, e.g. should shards be in a separate schema? For the moment there are scenarios in which the user has to be able to drop shards and schemas might contain non-Citus objects so we shouldn't interfere with either.

**Comment by marcocitus** [comment]
Dropping schemas with distributed tables on workers is no longer allowed.

We'll continue to support creating schemas on workers for now.
