### ISSUE TITLE
Mark RF=1 tables as streaming replicated upon upgrade

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#1077]
@marcocitus suggests that we mark MX eligible tables (hash replicated, RF=1) as streaming replicated (thus as MX tables) so that they are ready to be used as mx tables. 

Note that this won't propagate the metadata until `start_metadata_sync_to_node` is called.

**Comment by metdos** [comment]
I think this is also tied to the decision in #1065. @aamederen, could you correct me if I'm wrong.

**Comment by ozgune** [comment]
@aamederen, we talked about this issue in a meeting this week and added our comments [in here](https://github.com/citusdata/citus/issues/1065#issuecomment-271383150).

I'm planning to close this issue in favor of #1065. If that doesn't work, could you add your notes to this issue?

**Comment by aamederen** [comment]
@ozgune sure, I couldn't track the latest updates was just waiting for your official decision :) Feel free to close this up
