### ISSUE TITLE
failed install citus_96-devel

### ISSUE THREAD

**Issue by forkeer** [citusdata/citus#1078]
Hi
We need install citus_96-devel in centos 7
but show error :
```
--> Running transaction check
---> Package citus_96-devel.x86_64 0:6.0.1-1.rhel7 will be installed
--> Processing Dependency: citus_96(x86-64) = 6.0.1-1.rhel7 for package: citus_96-devel-6.0.1-1.rhel7.x86_64
--> Finished Dependency Resolution
Error: Package: citus_96-devel-6.0.1-1.rhel7.x86_64 (pgdg96)
           Requires: citus_96(x86-64) = 6.0.1-1.rhel7
           Installed: citus_96-6.0.1.citus-1.el7.centos.x86_64 (@citusdata_community)
               citus_96(x86-64) = 6.0.1.citus-1.el7.centos
           Available: citus_96-6.0.0-1.rhel7.x86_64 (pgdg96)
               citus_96(x86-64) = 6.0.0-1.rhel7
           Available: citus_96-6.0.0.citus-1.el7.centos.x86_64 (citusdata_community)
               citus_96(x86-64) = 6.0.0.citus-1.el7.centos
           Available: citus_96-6.0.1-1.rhel7.x86_64 (pgdg96)
               citus_96(x86-64) = 6.0.1-1.rhel7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
```
yum --showduplicates list citus_96-devel | expand
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.hosteurope.de
 * extras: ftp.hosteurope.de
 * updates: ftp.hosteurope.de
Available Packages
citus_96-devel.x86_64                    6.0.0-1.rhel7                    pgdg96
citus_96-devel.x86_64                    6.0.1-1.rhel7                    pgdg96

```
```
yum --showduplicates list citus_96 | expand
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.hosteurope.de
 * extras: ftp.hosteurope.de
 * updates: ftp.hosteurope.de
Installed Packages
citus_96.x86_64          6.0.1.citus-1.el7.centos           @citusdata_community
Available Packages
citus_96.x86_64          6.0.0-1.rhel7                      pgdg96
citus_96.x86_64          6.0.0.citus-1.el7.centos           citusdata_community
citus_96.x86_64          6.0.1-1.rhel7                      pgdg96
citus_96.x86_64          6.0.1.citus-1.el7.centos           citusdata_community

```
where ? citus_96-devel-6.0.1-1.el7.centos.x86_64?
can any one help me for this ?

**Comment by forkeer** [comment]
Hi
when install citus from yum with your taturial 
`curl https://install.citusdata.com/community/rpm.sh | sudo bash`
this script add citusdata_community.repo in yum.rep
when run yum --showduplicates list citus_96 , can see install citus_96.x86_64 from @citusdata_community but not have citus_96-devel in @citusdata_community and try install from pgdg96
i remove 
`rm /etc/yum.repos.d/citusdata_community.repo`
and install citus_96 and citus_96-devel from pgdg96 source problem solve
but please add citus_96-devel in @citusdata_community

Thanks

**Comment by onderkalaci** [comment]
Hi @forkeer,

We try to answer those questions on our [users-group](https://groups.google.com/forum/#!forum/citus-users) and [slack channel](https://slack.citusdata.com/).

I moved this discussion to our [user group](https://groups.google.com/forum/#!topic/citus-users/W7IW6s2x-PI).

Thanks!

**Comment by ozgune** [comment]
@forkeer -- @onderkalaci reported this problem in our user's list and @jasonmp85 replied in that thread.

Could you continue the conversation in that email thread? (Are you looking to compile a particular extension against Citus?) https://groups.google.com/forum/#!topic/citus-users/W7IW6s2x-PI

**Comment by jasonmp85** [comment]
Hey @forkeer, I answered your question in the [Google Group](https://groups.google.com/d/msg/citus-users/W7IW6s2x-PI/Fqg5FTFmDwAJ), but here's a copy-paste for convenience…

>> We need install citus_96-devel in centos 7
> 
> Can you share some more information about why you need access to Citus headers? We mostly use them for building certain Enterprise features, but have not yet publicly supported their use.
> 
>> when run yum --showduplicates list citus_96 , can see install citus_96.x86_64 from @citusdata_community but not have citus_96-devel in @citusdata_community and try install from pgdg96
> 
> Before your email, I was actually unaware there was a citus_96-devel in PGDG. It appears the PGDG RPM maintainers separated the headers out into their own package, something we don’t do in our own distributions.
> 
> Your problem arises because you’ve installed the Citus-repository version of the Citus package and are trying to install the PGDG-repository version of the headers.
> 
>> but please add citus_96-devel in @citusdata_community
> 
> We don’t have any plans to add a specific devel package; however, if you install a Citus-repository distribution of Citus, you already have the headers on your system; we just include everything in one package rather than separate them out (though rpmlint isn’t particularly happy about this).
> 
> It is possible the headers may not be present in subsequent releases, as they were essentially a holdover from previous Enterprise/Community integration points. Can you share more about what you’re looking to accomplish?

I'd be happy to continue discussion in the Google Group, as this appears to be a usage question and not a feature request or bug report.
