### ISSUE TITLE
Support DISABLE/ENABLE TRIGGER ALL on distributed tables

### ISSUE THREAD

**Issue by lfittl** [citusdata/citus#1080]
This is a missing feature for those using Citus together with Ruby on Rails, and using a framework like [database_cleaner](https://github.com/DatabaseCleaner/database_cleaner/blob/master/lib/database_cleaner/active_record/truncation.rb#L235) to truncate their tables after test suite runs. In particular, Rails has a method called [disable_referential_integrity](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activerecord/lib/active_record/connection_adapters/postgresql/referential_integrity.rb#L15) that runs the following SQL on each table known to Rails:

```sql
ALTER TABLE ... DISABLE TRIGGER ALL
-- other SQL here
ALTER TABLE ... ENABLE TRIGGER ALL
```

This happens after a test run to remove the test run's data without executing triggers.

Even though we don't support triggers (https://github.com/citusdata/citus/issues/906) this causes errors when running the tests for a Rails app, since its always being called, including for tables that have no triggers.

It would be helpful if we supported this as a no-op for now, and push it down once https://github.com/citusdata/citus/issues/906 is implemented.

**Comment by metdos** [comment]
@lfittl, as long as I see from your message, catching this commands on distributed tables and ignoring them will be enough. I'm thinking to add a warning or notice message instead of an error message. Would it be okay for Rails?

**Comment by lfittl** [comment]
@metdos Yes, I think having a WARNING/NOTICE for now would be an improvement.

If its not too much effort to push down, since we support foreign keys already (and triggers when adding them manually), this would be good to have fully implemented too.

Do you have an estimate how much additional effort it would be to add push-down support for this?

**Comment by metdos** [comment]
> If its not too much effort to push down, since we support foreign keys already (and triggers when adding them manually), this would be good to have fully implemented too.
> 
> Do you have an estimate how much additional effort it would be to add push-down support for this?

@lfittl actually it was pretty easy because we are already able to push down "disable/enable trigger all", adding regression tests was harder #1299 :)

I was also planning to test it with database_cleaner, but it seems that it will take some time to warm up with Ruby :)

**Comment by lfittl** [comment]
@metdos Nice - no worries re: testing, I think that should all work fine :)
