### ISSUE TITLE
Put shards in separate schema

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1082]
When a user connects to an MX worker for make queries on a distributed table, the shards on that worker are visible when using `\d` and it is easy to make a mistake (see also: #1076). Consider putting shards into a separate schema to hide them from the user and provide a more homogeneous user experience when connecting to a worker via a load-balanced data URL.

**Comment by onderkalaci** [comment]
Can we consider this issue resolved with #2323 ?

**Comment by marcocitus** [comment]
Yes
