### ISSUE TITLE
Subqueries other than in from-clause are currently unsupported

### ISSUE THREAD

**Issue by forkeer** [citusdata/citus#1086]
Hi
we used many Subqueries  in where clause and i see this error , we cant change query 
any one can help me for using sharding citus ?

ERROR:
 ```
 cannot perform distributed planning on this query
DETAIL:  Subqueries other than in from-clause are currently unsupported
```

**Comment by onderkalaci** [comment]
Hi @forkeer, 

We try to answer those questions on our [users-group](https://groups.google.com/forum/#!forum/citus-users) and [slack channel](https://slack.citusdata.com/).

Currently, I'm closing the issues on github. Could you post your question to the above channels?

Thanks!

**Comment by forkeer** [comment]
why not answer in this post ?
i not work with slack and google
please answer in this post 
Thanks

**Comment by lithp** [comment]
An update for any future readers of this ticket: For Citus 6.2 a lot of work was put into subquery support, certain subqueries are now allowed in the WHERE clauses. If the subquery only touches rows which are on the same node as the rows the clause is filtering it will be allowed and pushed down to that node.
