### ISSUE TITLE
cannot plan queries that include both regular and partitioned relations

### ISSUE THREAD

**Issue by forkeer** [citusdata/citus#1088]
hi
can any one explain whats means this error ?

ERROR: 
 `cannot plan queries that include both regular and partitioned relations`

**Comment by onderkalaci** [comment]
Hi @forkeer, 

We try to answer those questions on our [users-group](https://groups.google.com/forum/#!forum/citus-users) and [slack channel](https://slack.citusdata.com/).

Currently, I'm closing the the issues on github. Could you post your question to the above channels?

Thanks!

**Comment by forkeer** [comment]
why not answer in this post ?
i not work with slack and google
please answer in this post 
Thanks

**Comment by jmunsch** [comment]
@forkeer i felt the same way and opened a pull request : 

https://github.com/citusdata/citus/pull/1431

did you get to an answer on what the confusing error meant?

**Comment by forkeer** [comment]
@jmunsch  we have many problem with citus , we research and find pgxl ✓ https://github.com/forkeer/PostgresXL

**Comment by lithp** [comment]
@forkeer I'm interested to hear what caused you to decide to use postgresXL. Are there any features you feel were missing from Citus? Is there somewhere you think the Citus documentation could be more clear?

**Comment by forkeer** [comment]
@lithp 
check this issue 
https://github.com/citusdata/citus/issues/1086
https://github.com/citusdata/citus/issues/1087
https://github.com/citusdata/citus/issues/1088
https://github.com/citusdata/citus/issues/1089

now we work in pgxl without any problem
