### ISSUE TITLE
Unify schema creation logic

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1097]
We currently create schemas for distributed tables by adding a `CREATE SCHEMA IF NOT EXISTS ...` command to the list of DDL commands that we send when creating a placement or distributed table on a worker. This means that we currently have several ways in which a schema can get created on a worker:

1. Reference table is copied to a new node by `master_add_node` (as table owner)
2. Shard rebalancer moves or copies a shard placement to a new node (as table owner) 
3. Create a shard placement on a node (as table owner)
4. Distributed tables are created on a node using `start_metadata_sync_to_node` (as superuser)
5. Creating an streaming replication table when there are workers with metadata (as superuser) 

Because we set `AUTHORIZATION` when generating the `CREATE SCHEMA` statement, the schema will have the correct owner even in cases 4-5. However, in cases 1-3 the table owner might not have permission to create the schema on the worker as the schema could have a different owner than the table.

We can also run into to problems when making more operations transactional. If there are multiple connections to a worker trying to create the same schema from separate transactions then they would deadlock.

The current schema creation logic also complicates distributing other objects like functions and types, since their schema might not exist yet.

Consider implementing a more unified approach to creating schemas. For example, we could ensure all existing schemas are created on a new worker on `master_add_node` (see also: #1026) and propagate `CREATE SCHEMA` statements to all existing workers. We should create schemas on workers in subtransactions that are performed as superuser to avoid ownership and deadlock/visibility issues.

**Comment by ozgune** [comment]
We captured our thinking on unifying our DDL propagation in #354 and #376. I'm noting them here as semi-related issues.

**Comment by marcocitus** [comment]
Fixed by #2777 and #2882.
