### ISSUE TITLE
Implement master_aggregate_table_shards(source table, destination table, aggregation_query)

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#11]
Our documentation refers to the user-defined function `master_aggregate_table_shards` to help users create distributed materialized views. We need to implement this function or remove the reference to it from our documentation.

https://www.citusdata.com/documentation/citusdb-documentation/examples/id_querying_aggregated_data.html

The mechanism through which we implement this function could potentially be similar to #10

**Comment by ozgune** [comment]
@onderkalaci -- Now that we implemented ``INSERT INTO (SELECT ...)`` with #508, what do you think about closing this issue?

**Comment by onderkalaci** [comment]
> https://www.citusdata.com/documentation/citusdb-documentation/examples/id_querying_aggregated_data.html

The link is dead, so I cannot see what the UDF is intended for. If it only intends to make `co-located` roll-ups, `INSERT INTO .. SELECT` already does that with a wide SQL coverage. But, if it intends to run arbitrary multi-shard roll-ups, it might make sense to keep the issue open.

**Comment by ozgune** [comment]
Good point. The intent with this user-defined function was to roll-up data from a source distributed table to a target colocated table. I'm therefore closing this issue.
