### ISSUE TITLE
Reference table modifications are missing "set of active connections" expansion check

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#1102]
In contrast to GetConnectionForPlacement() GetPlacementConnectionsReadyForTwoPhaseCommit() doesn't have
```
		ereport(ERROR, (errcode(ERRCODE_CONNECTION_DOES_NOT_EXIST),
						errmsg("no transaction participant matches %s:%d",
							   placement->nodeName, placement->nodePort),
						errdetail("Transactions which modify distributed tables may only "
								  "target nodes affected by the modification command "
```
That doesn't seem entirely right to me.  @onderkalaci Was that intentional? If so, why exactly?

**Comment by onderkalaci** [comment]
It doesn't do it explicitly. But, the connections opened (and marked as critical) by `GetPlacementConnectionsReadyForTwoPhaseCommit ()`  always goes through `GetConnectionForPlacement ()` and so passes through the participant check. Is that approach not accurate?

Also, have a regression test for [it](https://github.com/citusdata/citus/blob/master/src/test/regress/expected/multi_modifying_xacts.out#L744).

**Comment by anarazel** [comment]
Ladidadi - I blame jetlag. Sorry for the noise.

**Comment by anarazel** [comment]
FWIW, that's correct, but it's really quite ugly to start connections first in GetPlacementConnectionsReadyForTwoPhaseCommit() and then rely on a second lookup to trigger the error.

**Comment by onderkalaci** [comment]
> FWIW, that's correct, but it's really quite ugly to start connections first in GetPlacementConnectionsReadyForTwoPhaseCommit() and then rely on a second lookup to trigger the error.

Since your new PR (#1079) fixes it, I'm not going to do anything on that?
