### ISSUE TITLE
Hash Pruning does not work with Composite types

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#112]
Hash Pruning does not work with Composite types. Our current behaviour is to not prune any shards even if the condition is on the partition column. The reason for this is that there does not seem to be a default hash function for the equality operator for composite types. We should either error out if we aren't able to find hash functions, or notify the user that hash pruning does not work with composite types.

**Comment by samay-sharma** [comment]
@onderkalaci @sumedhpathak : I think this should already be addressed. We have a [regression test](https://github.com/citusdata/citus/blob/master/src/test/regress/sql/multi_data_types.sql#L51) which tests for this too.

If so, should I close this issue?

**Comment by onderkalaci** [comment]
@samay-sharma Yes, we can close the issue, Citus supports all functionality with composite types. @sumedhpathak has wrote even more extensive example [here](https://gist.github.com/sumedhpathak/b8d4d46a656dbc58f364), noting here for reference.
