### ISSUE TITLE
UPDATE ... FROM support for queries that touch a single machine

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1127]
We have two customers who asked if we could support the ``UPDATE ... FROM (SELECT ...)`` construct for queries that modify data in a single machine. For example:

<pre>
UPDATE foobar
SET
       distinct_viewers = metrics.viewers
FROM
       (SELECT contactable_id foobar_id,
        count(DISTINCT (CASE WHEN event_type='View' then visitor_token end)) as viewers
        FROM events
        WHERE account_id=12 group by contactable_id) metrics
WHERE
   id=metrics.foobar_id AND
   account_id=12;
</pre>

**Comment by samay-sharma** [comment]
+1; Ran into it during a customer engagement.

**Comment by lithp** [comment]
Weird, I would have thought we already support this! Router executor supposedly checks to make sure the query only hits one machine and then pushes down.

**Comment by marcocitus** [comment]
Only for SELECT, not for DML. DML is trickier because we can't guarantee that the subquery will return the same result on every replica without very aggressive locks, though I think it's worth allowing this when the replication factor is 1.

**Comment by marcocitus** [comment]
From hacking router planner a bit, it seems reasonably straight-forward to start planning UPDATEs and DELETEs with RouterSelectQuery. 

RouterSelectQuery will need to be refactored a bit, e.g. for UPDATE/DELETE we need to call `deparse_shard_query`  instead of `pg_get_query_def`.  We'll also need to set the relationShardList as we do for INSERT..SELECT to make sure we lock tables from which we are selecting for replication factor > 1. Finally, we'll need to remove some error checks and add a lot of regression tests (might expose deparsing bugs). Overall, seems like a 1-2 week task.

**Comment by lithp** [comment]
If this existed I would have been able to provide an easy answer for #1313

**Comment by saicitus** [comment]
+3, came up in 3 prospect engagements.

**Comment by ozgune** [comment]
@saicitus -- Could you update the SE <> product sheet with specific prospect names where this came up? I suspect there may be some overlap between the engagements @samay-sharma, you, and I mentioned in this thread.

**Comment by ozgune** [comment]
I'm posting a similar query that recently came up below for completeness:

<pre>
UPDATE objects SET x = 123
  WHERE id IN (SELECT object_id FROM other_table ... WHERE tenant_id = 12) AND tenant_id = 12;
</pre>

**Comment by metdos** [comment]
> RouterSelectQuery will need to be refactored a bit, e.g. for UPDATE/DELETE we need to call deparse_shard_query instead of pg_get_query_def

@marcocitus, `deparse_shard_query` works on a single shard/table, but for an `update ... from`, we need to update multiple shards/tables. Are you proposing extending `deparse_shard_query` or am I missing something?

**Comment by marcocitus** [comment]
I think I switched `pg_get_query_def` and `deparse_shard_query`.
