### ISSUE TITLE
Propagate views to workers

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1129]
We added support for creating views in #1024. To provide a consistent user experience in MX, it would be nice if we would also propagate views to workers with metadata.

**Comment by onderkalaci** [comment]
One very simple -- but not working-- idea I tried was to call `GetViewCreationCommandsOfTable()` in `MetadataCreateCommands()`, emulating as if the views are part of the metadata creation.

However, that has many drawbacks, such as schemas that the views depend on are not automatically propagated:
```SQL
create schema sc10;
create view sc10.v_type_3 as SELECT * FROM users_table;
SELECT start_metadata_sync_to_node('localhost', 9700);
ERROR:  schema "sc10" does not exist
CONTEXT:  while executing command on localhost:9700
Time: 98.945 ms
```

We'd have all sorts of cases like these. So, the best approach could be let the object propagation framework to handle this. I can think of two approaches:

1) [preferred approach]: The object propagation infrastructure automatically adds views that are dependent to the distributed relations. This sounds controversial to how dependency resolution works as the system works in the other direction.

2) [less preferred approach] Invent a new UDF like `create_distributed_view` which marks the view as an distributed object and does all the resolution.

**Comment by onderkalaci** [comment]
A prototype: https://github.com/citusdata/citus/compare/create_distributed_views?expand=1  with a similar idea to https://github.com/citusdata/citus/pull/5061

**Comment by onderkalaci** [comment]
Implemented via https://github.com/citusdata/citus/pull/5889, https://github.com/citusdata/citus/pull/5914   , https://github.com/citusdata/citus/pull/5923.

Remaining PR is https://github.com/citusdata/citus/pull/5950, we can close this issue after that.
