### ISSUE TITLE
Subquery bug related with resjunk, if a function is applied on group by column.

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#113]
Assume we run this query on CitusDB without any subqueries.

``` sql
select
round(l_orderkey),
count(*)
from
lineitem
group by
l_orderkey;
```

Then worker query becomes something like;

``` sql
select
round(l_orderkey) as intermediate_column_0,
count(*) as intermediate_column_1,
l_orderkey as intermediate_column_2
from
lineitem_xxx
group by
l_orderkey;
```

and master query becomes something like;

``` sql
select
intermediate_column_0 -- this is round(l_orderkey)
sum(intermediate_column_1)
from
master_merged_table
group by
intermediate_column_2; -- this is l_orderkey
```

If you run this master query on our temporarily created table on the master, you should get an error saying that `"ERROR: column "intermediate_column_0"` must appear in the GROUP BY clause or be used in an aggregate function". We don't see this error in CitusDB, because this check is run in the parser. We create and run master query directly, and it doesn't go through the parser. For this use-case we give correct results. And the time being I couldn't think a use case which would not.

Now the subquery part

For subqueries, we use same worker and master query creation logic. If the query above is in a subquery, then master query(reduce query for subqueries) goes to worker and pass through also the parser logic. Then we get the error above in the worker node.

Possible Fixes:

i. Modify worker and master query creation logic. Run round() function not in worker query but in the master query (I think this is correct way to do this).
ii. Error out in worker and master query creation logic.
iii. Error out in task creation while creating reduce tasks in mapmergejob creation.

**Comment by marcocitus** [comment]
this seems to no longer be an issue with custom scans
