### ISSUE TITLE
Expand failure tests for distributed copy 

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#1153]
While reviewing #1133 I noticed that our current coverage is pretty crappy. We miss at least:
- tests verifying we handle a removed host correctly
- tests verifying that we mark shards properly as invalid after failures (i.e. RF > 1, with some placements failing, not all)
- tests verifying we handle failing connections properly

**Comment by mtuncer** [comment]
Some parts of this is already addressed by #1168 . Adding any remaining tests to that PR.

**Comment by mtuncer** [comment]
fixed by #1168
