### ISSUE TITLE
Router executor does not immediately mark placement as inactive

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1161]
When a DML command fails on a node, we wait until the end of the transaction with marking placements as inactive. This means that subsequent queries and functions in the same transaction will still see the placement as healthy, which seems a bit dangerous and leads to subsequent commands showing warnings.

It seem that after executing a statement in the router executor we should do: `CheckForFailedPlacements(true, CoordinatedTransactionUses2PC);`, to update the shardstates or error out.

(we observed a similar problem with master_append_table_to_shard in #1149)

**Comment by metdos** [comment]
@lithp, assigned to you, because we expect #1169 to fix this.
