### ISSUE TITLE
Undo the change in #1149 which made CoordinatedTransactionUses2PC a global

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#1166]
The PR: https://github.com/citusdata/citus/pull/1149

It was made because we want external callers to call `CheckForFailedPlacements`, but that can be better achieved by creating a new method.

**Comment by marcocitus** [comment]
Can't we just use remove the `using2PC` parameter from `CheckForFailedPlacements`? It's just confusing and always has `CoordinatedTransactionUses2PC` as a value.

**Comment by lithp** [comment]
Because `CoordinatedTransactionUses2PC` is (rightly?) a static of `transaction_management.c`, while `CheckForFailedPlacements` is in `placement_connection.c`
