### ISSUE TITLE
Deadlock happens on a buggy branch - May require further investigation

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#1176]
As the title mentions, this is not a bug that we could observe on the master branch (or any releases). This only happens on a buggy branch. However,  I'm opening this issue for further investigation in case a similar deadlock could happen on the master branch. Note that I couldn't re-produce the bug on any stable branch with any potential other steps.

1. Checkout to [fix_insert_select](https://github.com/citusdata/citus/tree/fix_insert_select) branch.
2. Create a cluster with the exact same steps:
```SQL
-- to reproduce it simply, use two workers
SELECT master_add_node('localhost', 9700);
SELECT master_add_node('localhost', 9701);

-- again, for simplicity use the same shard/replication configs
SET citus.shard_count = 4;
SET citus.shard_replication_factor = 2;

CREATE TABLE raw_events_first (user_id int, time timestamp, value_1 int, value_2 int, value_3 float, value_4 bigint, UNIQUE(user_id, value_1));
SELECT create_distributed_table('raw_events_first', 'user_id');

CREATE TABLE raw_events_second (user_id int, time timestamp, value_1 int, value_2 int, value_3 float, value_4 bigint, UNIQUE(user_id, value_1));
SELECT create_distributed_table('raw_events_second', 'user_id');


BEGIN;
ALTER TABLE raw_events_second DROP COLUMN value_4;
INSERT INTO raw_events_first SELECT * FROM raw_events_second WHERE user_id = 10; 
COMMIT;
```
3. Or, simply run `check-multi`. But, debugging that is more complicated.

This issue might be a complete false alarm.

**Comment by marcocitus** [comment]
Should we close this?

**Comment by onderkalaci** [comment]
Ah, I removed the branch recently. So, the issue seems less useful now 😢 

But, I think we should keep this issue. Here, I'm suspecting a bug related to the connection manager, which is not triggered normally. But, in some cases, we pick the wrong connection and lead to the deadlock.

**Comment by onderkalaci** [comment]
This is not relevant anymore
