### ISSUE TITLE
Validate distribute-by clause column to make sure it belongs to the table.

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#118]
Sending this out for documentation purposes:

I was testing 9.4.4 integration, along with pg_shard and cstore_fdw.

I accidentally created the table using: 
`DISTRIBUTE BY APPEND('customer_id')` instead of
`DISTRIBUTE BY APPEND(customer_id);`

This saved the partition-column type in pg_dist_partition as a `CONST` type instead of a `VAR` type.
We didn't error out anywhere in the Citus code.

Since pg_shard was also in shared_preload_libraries, when I ran a query against a Citus table, it errored in pg_shard (since it first loads the pg_shard planner/executor and tries to load pg_shard metadata). The error was an assertion failure in pg_shard which expects the partition column to be a VAR type always.

Even a simple "select \* from pgs_distribution_metadata.partition" would fail with that assertion.

I am noting this in Trello, but seems like a particularly noxious bug and one that's hard to debug.
We need better validation during insert into pg_dist_partition.

Sumedh

**Comment by marcocitus** [comment]
This code path is long gone.
