### ISSUE TITLE
Create indexes during shard copies after creating the data

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1180]
When we copy a shard from one node to another (e.g. shard repair, shard rebalancer) we first copy out the data from the worker in to a file, then create the (shard) table and the indexes, and then copy the data into the table. A faster implementation would be to create the indexes *after* copying in the data. This should make shard rebalancing substantially faster for users that make heavy use of indexes.

**Comment by samay-sharma** [comment]
One of our larger customers has also asked about it a few times to make their rebalance faster. So, +1

**Comment by ozgune** [comment]
Is this issue related to #1232? If so, do we now have it resolved?

**Comment by metdos** [comment]
> Is this issue related to #1232? If so, do we now have it resolved?

I think so. @byucesoy, @marcocitus can we close this issue?
