### ISSUE TITLE
Workaround VACUUM/ANALYSE limitations

### ISSUE THREAD

**Issue by HackerMD** [citusdata/citus#1186]
I just realized through #719  that `VACUUM ANALYSE table_name` has been silently ignored on the master for distributed tables. It's great that this will be supported with the upcoming release.

Until there is a stable 6.1 release, how can I workaround this issue? Would I need to vacuum each shard manually?

**Comment by anarazel** [comment]
On 2017-01-31 23:18:03 -0800, Markus D. Herrmann wrote:
> Until there is a stable 6.1 release, how can I workaround this issue? Would I need to vacuum each shard manually?

In many cases postgres' autovacuum will automatically take care of
this. By tuning autovacuum you can trigger more or less aggressive
vacuuming.  Otherwise you can also trigger all tables on the workers by
doing database wide vacuums on them.

**Comment by ozgune** [comment]
@HackerMD -- Does @anarazel's reply help with your question? If you have further questions on workarounds, could you reach out to us on the citus-users mailing list or our Slack channel?

Now that we have ``VACUUM`` / ``ANALYZE`` on distributed tables implemented, I'm planning to close this issue. If that doesn't work, please let us know.

**Comment by HackerMD** [comment]
@anarazel -- thank you for your feedback!

I would like to specifically target selected tables, where I have extremely high `INSERT` rates. Tuning autovacuum would be a reasonable option. Since these tables already exist, are `ALTER TABLE` statements modifying autovacuum settings pushed down to the workers?

**Comment by lithp** [comment]
@HackerMD unfortunately, that's not supported:

```
ec2-user=# ALTER TABLE example SET (autovacuum_vacuum_threshold = 50);
ERROR:  alter table command is currently unsupported
DETAIL:  Only ADD|DROP COLUMN, SET|DROP NOT NULL, SET|DROP DEFAULT, ADD|DROP CONSTRAINT FOREIGN KEY and TYPE subcommands are supported.
```

**Comment by HackerMD** [comment]
Alright, seems I'll have to change this on shards manually for now. Thank you for your support!
