### ISSUE TITLE
Ctrl-C with master_append_table_to_shard causes data inconsistency

### ISSUE THREAD

**Issue by byucesoy** [citusdata/citus#1187]
If copying is started to a node, it continues in the background even after Ctrl-C is pressed. It causes copying unwanted data and worse if copy is started at one node but not the other, one node will get the data and other will not. We are not marking any nodes as INVALID.

**Comment by marcocitus** [comment]
Seems we forgot to add a RemoteTransactionBeginIfNecessary after getting the connection, which prevents it from rolling back.
