### ISSUE TITLE
If a node fails during shard creation, Citus does not re-create the shards at working nodes

### ISSUE THREAD

**Issue by byucesoy** [citusdata/citus#1192]
If a node fails during during create_distributed_table(..., hash); or master_create_worker_shards shard Citus does not re-create the shards created at stopped worker. Only remaining shards are created at running workers. None of the shards are marked as inactive.

```sql
-- set shard_count to something big so that we have time to stop the node
SET citus.shard_count to 512;

CREATE TABLE hash_table(column1 int);
SELECT create_distributed_table('hash_table', 'column1', 'hash');

-- stop a node here, create_distributed_table prints warning messages

-- we do not mark already created shards as INACTIVE or delete them or create them at healthy worker
SELECT * FROM pg_dist_shard_placement
shardid | shardstate | shardlength | nodename  | nodeport | placementid 
---------+------------+-------------+-----------+----------+-------------
  102328 |          1 |           0 | localhost |     9700 |         321
  102329 |          1 |           0 | localhost |     9701 |         322
  102330 |          1 |           0 | localhost |     9702 |         323
  102331 |          1 |           0 | localhost |     9700 |         324
  102332 |          1 |           0 | localhost |     9701 |         325
...
```

**Comment by marcocitus** [comment]
Is this a bug? If the node comes back, we can still use the shards that were already created and their contents will be correct (empty), so there's no reason to mark them as inactive yet.

**Comment by metdos** [comment]
> Is this a bug? If the node comes back, we can still use the shards that were already created and their contents will be correct (empty), so there's no reason to mark them as inactive yet.

I think you are technically right. Just, I'm not sure if this is user-friendly or not. The user gets a distributed table (with some warnings on the way), but then he will not be able to use that table (unless the other node comes back).

Saying that I don't have any strong preference, we may close this issue.

**Comment by marcocitus** [comment]
Well, if the table was created 2 seconds earlier, the user also wouldn't be able to use the table after the failure, so it seems like a rather insignificant difference.

**Comment by metdos** [comment]
> Well, if the table was created 2 seconds earlier, the user also wouldn't be able to use the table after the failure, so it seems like a rather insignificant difference.

Fair enough.

**Comment by byucesoy** [comment]
Well I think it depends on what is the expected behavior of create_distributed_table and master_create_worker_shards.

Slightly more confusing result of this issue is this;

- Create a cluster with this problem
- INSERT some values which will go to only shards at healthy nodes. (This will work as expected)
- SELECT all rows. (This will error out because we cannot reach some shards, we cannot read the data we inserted in previous step)

I do not have strong position about this is a bug or not either but we should decide what is the expected behavior. Because according to test document, we expect that shards will be re-created at healthy nodes.

**Comment by metdos** [comment]
For documentation purposes: We decided that this was a known behavior and we deliberately choose this behavior.
