### ISSUE TITLE
master_create_worker_shards permits streaming tables with RF>1

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#1194]
`master_create_worker_shards` does not check the compatibility of given replication factor with the `citus.replication_model` parameter. This allows us to create streaming replicated distributed tables with RF>1.

```
set citus.replication_model to 'streaming';
set citus.shard_replication_factor to 1; -- will be ignored
create table test(id integer);
select master_create_distributed_table('test', 'id', 'hash');

-- check that replication model is streaming
select repmodel from pg_dist_partition where logicalrelid='test'::regclass;

select master_create_worker_shards('test', 8, 2);

-- check that the shards have two placements
SELECT count(*) FROM pg_dist_shard_placement WHERE shardid IN (select shardid from pg_dist_shard where logicalrelid='test'::regclass LIMIT 1);
```

**Comment by lithp** [comment]
What's wrong with this behavior? If you want to double-replicate, maybe we should let you double-replicate!

**Comment by aamederen** [comment]
@lithp The purpose of this issue is to provide consistency with the behavior of `create_distributed_table`, since it does't allow streaming replication with RF>1.

For the general reason of this decision, I am not exactly sure. One drawback of RF>1 could be with MX: queries from different workers may go to the placements in a different order, causing inconsistent behavior (I am not sure if it is unnavoidable). I am sure @ozgune @anarazel @marcocitus @fdr have better explanations for this.
