### ISSUE TITLE
Improve concurrent start_metadata_sync_to_node and other metadata changes

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#1199]
Running concurrent metadata changes and `start_metadata_sync_to_node()` may lead to failures / unexpected metadata.

Things to consider:
* `start_metadata_sync_to_node()` / `ALTER TABLE`
* `start_metadata_sync_to_node()` / `DROP TABLE`
* `start_metadata_sync_to_node()` / `CREATE FKEY`
* `start_metadata_sync_to_node()` / `create_dist_table()` / `create_reference_table()` 
* `start_metadata_sync_to_node()` / `upgrade_to_reference_table` [ignore]
* `start_metadata_sync_to_node()` / `mark_tables_colocated` [ignore]
* Note that the above may not be the full list, the owner of the task should consider other UDFs/operations as well.

One example:
Session 1:
```SQL
SELECT start_metadata_sync_to_node('localhost', 9700);
```

Session 2:
```SQL
ALTER TABLE t1 add column x int;
NOTICE:  using one-phase commit for distributed DDL commands
HINT:  You can enable two-phase commit for extra safety with: SET citus.multi_shard_commit_protocol TO '2pc'
WARNING:  connection error: localhost:9700
DETAIL:  no connection to the server
ERROR:  failure on connection marked as essential: localhost:9700
```

A comment from @marcocitus from the test doc: 
```
pg_get_tableschemadef_string, which generates the CREATE TABLE command, does acquire an AccessShareLock on the table, which blocks ALTER TABLE, but it also releases it at the end of the function.
```

**Comment by onderkalaci** [comment]
In my point of view, this issue is not a blocker for 6.1 The reason is that I would expect users to enable metadata syncing just before operating the cluster. It does not seem something a user would do on an operating cluster at an arbitrary time. 

I guess @marcocitus might have ideas on this as well.

**Comment by marcocitus** [comment]
I agree that it's not a blocker.

**Comment by velioglu** [comment]
We have the same problem with current Citus version as well. Do we still think that it's not a blocker/problem to solve? If yes, should we close this issue?

**Comment by mtuncer** [comment]
It might not be blocker, but it is a serious enough. We should fix this.

**Comment by onderkalaci** [comment]
could be related to https://github.com/citusdata/citus/issues/3190

**Comment by onderkalaci** [comment]
- ALTER TABLE .. ATTACH/DROP partition vs metadata sync

**Comment by hanefi** [comment]
#5480 fixes the majority of our concurrency issues with metadata syncing. We started to lock all the dependencies with an exclusive lock in this PR.

I did some more manual testing today. I disabled metadata syncing to a worker running on port 9701.

Session 1:
```sql
BEGIN;
SELECT start_metadata_sync_to_node('localhost',9701);
```

Session 2:
```sql
BEGIN;
ALTER TABLE ... # or some other concurrent operation.
```

The following operations are fine. They get blocked when there is a concurrent `start_metadata_sync` operation
- `ALTER TABLE`
- `DROP TABLE`
- `create_distributed_table()`
- `create_reference_table()`
- `ATTACH PARTITION`
- `DETACH PARTITION`

The following operation does not get blocked. However, it appears that all the shards have correct foreign keys. I will test this one out more.
- `CREATE FKEY`

ignored:
`upgrade_to_reference_table`
`mark_tables_colocated`

**Comment by onderkalaci** [comment]
1) What about `CREATE/DROP TYPE` vs `start_metadata_sync_to_node `? 

The tricky part is that when inside tx block ` `CREATE/DROP TYPE` ` are not propagated immediately. So, not easy to test / add isolation test. Do you have any thoughts on how can we add test for this?

2) What about `CREATE PARTITION OF ..`, this is common as well. Can you maybe add test for this as well?
