### ISSUE TITLE
`ALTER TABLE [table] SET (storage_parameter = [value])` is not supported

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#1202]
This came up [in the context of autovacuum](https://github.com/citusdata/citus/issues/1186) where it's currently a little painful to set per-table autovacuum settings, but I can also imagine pushing down per-table `fillfactor`s being useful.

**Comment by lfittl** [comment]
Just to add a +1 here - table autovacuum settings have come up with a few customers.

I've also just run into index storage settings not being pushed down on ALTER INDEX - we push them down on CREATE INDEX, but e.g. when turning off fastupdate for a GIN index you need to do that for every index separately:

Coordinator:
```
citus=> CREATE INDEX test2 ON companies USING gin(name);
CREATE INDEX
citus=> ALTER INDEX test2 SET (fastupdate = off);
ALTER INDEX
citus=> \d+ test2
         Index "public.test2"
 Column | Type | Definition | Storage  
--------+------+------------+----------
 name   | text | name       | extended
gin, for table "public.companies"
Options: fastupdate=off
```

worker:
```
citus=> \d+ test2_102038
      Index "public.test2_102038"
 Column | Type | Definition | Storage  
--------+------+------------+----------
 name   | text | name       | extended
gin, for table "public.companies_102038"
```

Happy to create a separate issue, but sounds like it'd be related and similar to fix.

**Comment by lfittl** [comment]
Another +1 for supporting this, as it has come up with one more customer.

In the meantime one can workaround by running `run_command_on_shards` to manually apply it to shards.
