### ISSUE TITLE
Submit patch upstream making additional explain.c functions public

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#1212]
Right now we copy:
- ExplainOpenGroup
- ExplainCloseGroup
- ExplainXMLTag
- ExplainJSONLineEnding
- ExplainYAMLLineStarting
- various X_* flags (like X_OPENING)

it should be fairly simple, and I hope uncontroversial, to make these public.

**Comment by pykello** [comment]
Sent a patch to pgsql-hackers to make ExplainOpenGroup/ExplainCloseGroup public. Rest of functions and defines weren't referenced directly by Citus code, so we don't need Postgres to make them public.

There is also ExplainOneQuery() which I thought might be a bit more difficult to convince to make public, so I am keeping it for a separate patch after thinking a bit more to see if we have another option.

**Comment by pykello** [comment]
Commitfest link: https://commitfest.postgresql.org/14/1209/. Waiting to be reviewed.

**Comment by sumedhpathak** [comment]
👍

**Comment by jasonmp85** [comment]
Oh, heh. I had to deal with this change as part of the PostgreSQL 11 changes. I didn't realize we submitted it :-P
