### ISSUE TITLE
Citus coordinator node doesn't propagate psql's -v option (\set command) to worker nodes

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1218]
The Citus coordinator node doesn't propagate psql's \set commands to worker nodes.

This issue recently came up in a conversation where one of our users was running psql with `-v ON_ERROR_STOP=1` flag. If the particular command failed on the worker nodes, psql wouldn't respect this flag and continue to execute. For example:

<pre>
psql -v ON_ERROR_STOP=1 -X -a -b -d `cat /home/ubuntu/CITUS_PROD` -c "BEGIN" -c "SET maintenance_work_mem = '128MB'" -c "SET citus.multi_shard_commit_protocol = '2pc'" -c "DROP INDEX IF EXISTS index_logs_on_company_id" -c "CREATE INDEX index_logs_on_company_id ON logs (company_id)" -c "END" -c "\di index_logs_on_company_id"
</pre>

[psql's documentation](https://www.postgresql.org/docs/9.6/static/app-psql.html) notes that `-v assignment` performs a variable assignment, like the `\set` meta-command. The Citus coordinator node doesn't propagate these meta-commands to worker nodes. As a result, the psql run doesn't provide the expected behavior on error.

**Comment by anarazel** [comment]
I don't quite understand the issue here - \set and ON_ERROR_STOP are client-side commands? They can't be propagated, because there's no psql elsewhere.

**Comment by lithp** [comment]
Uh, related to [this ticket](https://github.com/citusdata/citus/issues/462) but what does it mean for us to propagate psql configuration to the worker nodes, since we don't use psql when talking to the worker nodes?   I suppose we could add code to do templating but, how would we know what variables were sent? They're never sent to the server from psql.

**Comment by anarazel** [comment]
@ozgune Could you clarify what it'd take to fix this bug, because it's not clear to me?

**Comment by lithp** [comment]
@ozgune friendly ping
