### ISSUE TITLE
Split shard

### ISSUE THREAD

**Issue by xbogdan** [citusdata/citus#1222]
Hello,

Is there a way to split a shard in multiple smaller shards ?

For example I distributed a table and created 1 shard and 3 replicas across 3 workers.
Is there a way I can split that shard in 8 smaller shards ?

Also, what would be an optimal amount of shards for each table ?
I have tables with 500 000 000 rows.

Thanks.

**Comment by mtuncer** [comment]
Hey @xbogdan 

Thanks for contacting us, moving this discussion to [citus-users group](https://groups.google.com/forum/#!topic/citus-users/IaiRRW9SOIY) and closing this issue.
