### ISSUE TITLE
Evaluate docker install instructions in the README

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus#1227]
I believe that docker-machine and the docker toolbox are deprecated in favor of native installs on mac. 
Noting it in this issue so we can discuss the best installation instructions. A broader question is do we want to point people to docker at all or another method?

Here are some changes to accommodate the docker toolbox deprecation:

```diff
--- a/README.md
+++ b/README.md
@@ -47,10 +47,6 @@ Citus Cloud runs on top of AWS as a fully managed database as a service and has
 If you're looking to get started locally, you can follow the following steps to get up and running.

 * Install docker-compose: [Mac][mac_install] | [Linux][linux_install]
-* (Mac only) connect to Docker VM
-  ```bash
-  eval $(docker-machine env default)
-  ```

 * Pull and start the docker images
   ```bash
@@ -152,5 +148,5 @@ Copyright © 2012–2017 Citus Data, Inc.

 [faq]: https://www.citusdata.com/frequently-asked-questions
 [linux_install]: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-14-04
-[mac_install]: https://www.docker.com/products/docker-toolbox
+[mac_install]: https://www.docker.com/products/docker#/mac
 [tutorial]: https://docs.citusdata.com/en/v6.0/tutorials/tut-hash-distribution.html
```

**Comment by begriffs** [comment]
A related change in the docs repo - https://github.com/citusdata/citus_docs/commit/f6b7d57d5fba72152dc782f5e367caa7aca0c1b1

**Comment by jasonmp85** [comment]
+1 for getting rid of all the `docker-machine` stuff in favor of Docker Mac.

-1 for removing Docker entirely, as it's certainly the quickest way to get a simple cluster running IMO (even though the cluster obviously won't show performance, as it's on one machine, not many).
