### ISSUE TITLE
INSERT INTO SELECT with bytea as partition column errors out

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus#1228]
Citus version: Latest Citus 6.0 release and  6.1 master.
```
CREATE TABLE test_var(i int, h bytea);
CREATE TABLE test_var1(i int, h bytea);
SELECT create_distributed_table('test_var','h');
SELECT create_distributed_table('test_var1','h');
INSERT INTO test_var1 (SELECT * from test_var);
ERROR:  function pg_catalog.hashvarlena(bytea) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
CONTEXT:  while executing command on localhost:9701
```
Quoting @anarazel for the reason : "hashvarlena() is a wrapper taking an internal parameter (and internal taking functions aren't called via sql)."

Workaround: We can create a wrapper that direcly accepts byteas.
```
CREATE FUNCTION pg_catalog.hashvarlena(bytea) RETURNS INT IMMUTABLE LANGUAGE internal AS $$hashvarlena$$;
```
Create the above function on all nodes(theoretically only workers) and the INSERT INTO SELECT works.

**Comment by metdos** [comment]
Closing in favor of #1279 because it is more general and proposes a fix for the general case.
