### ISSUE TITLE
SELECT ... FOR UPDATE is not supported for router-plannable queries

### ISSUE THREAD

**Issue by lfittl** [citusdata/citus#1236]
## Test case

```
SELECT "projects".* FROM "projects" WHERE "projects"."account_id" = 20 AND "projects"."id" = 12 LIMIT 1 FOR UPDATE;
```

returns

```
ERROR:  could not run distributed query with FOR UPDATE/SHARE commands
HINT:  Consider using an equality filter on the distributed table's partition column.
```

Expected behavior is for this to be sent down to the single worker using the router executor. Note that this typically runs within a transaction, with an UPDATE on that same record to follow a bit later.

## Use case

One source of this SQL is `with_lock` in ActiveRecord, which lead me to encounter the problem. Its likely customers using Rails and doing atomic operations on rows will run into this issue. `with_lock` is a common approach to perform complex atomic changes on records in Rails.

## Test schema

```
postgres=# \d projects
                                Table "public.projects"
   Column   |       Type        |                       Modifiers                       
------------+-------------------+-------------------------------------------------------
 id         | integer           | not null default nextval('projects_id_seq'::regclass)
 name       | character varying | 
 account_id | integer           | not null
Indexes:
    "projects_pkey" PRIMARY KEY, btree (id, account_id)
```

```
postgres=# SELECT * from master_get_table_metadata('projects');
 logical_relid | part_storage_type | part_method |  part_key  | part_replica_count | part_max_size | part_placement_policy 
---------------+-------------------+-------------+------------+--------------------+---------------+-----------------------
         23901 | t                 | h           | account_id |                  1 |    1073741824 |                     2
(1 row)
```

---

In chat @marcocitus mentioned that this seems to be due to MultiRouterPlannableQuery returning false for hasForUpdate queries.

**Comment by anarazel** [comment]
There was some discussion about this on slack: The reason this isn't allowed is that the locking required for FOR SHARE/UPDATE/... makes things a bit more complicated than plain SELECTs. We need to

1. Start remote transactions when FOR SHARE/UPDATE is present
2. Lock the relevant shards if RF > 1, to avoid issues with differing ordering between concurrently run queries

It's still not hard, but it's not just making MultiRouterPlannableQuery() return true for the case.

**Comment by marcocitus** [comment]
> Start remote transactions when FOR SHARE/UPDATE is present

Do we need this even if the SELECT .. FOR UPDATE is not wrapped in a transaction block?

**Comment by anarazel** [comment]
> > Start remote transactions when FOR SHARE/UPDATE is present
>
> Do we need this even if the SELECT .. FOR UPDATE is not wrapped in a transaction block?

We definitely have to do it if in an explicit transaction block, but
even if not, it'd probably be a good idea. Without the transaction you
can't be sure there's a single moment where all the rows are locked at
once, rather than shard by shard.  I don't think this hugely pessimizes
anything, given that there's few uses of FOR UPDATE/SHARE outside of a
transaction.

Wonder if there's an argument to be made that we should do this on all
placements rather than just the one a SELECT would be run upon?

**Comment by marcocitus** [comment]
>  Without the transaction you can't be sure there's a single moment where all the rows are locked at once, rather than shard by shard.  

There is, it just happens more than once, which seems fine to me.

> Wonder if there's an argument to be made that we should do this on all placements rather than just the one a SELECT would be run upon?

Running it on all placements is mandatory. Otherwise, a concurrent UPDATE (assuming all_modifications_commutative is enabled) might fail and skip a placement and then proceed despite the locks. In general, SELECT..FOR UPDATE should be executed as an UPDATE, except we should not modify shardstate and should mark all connections as critical.

**Comment by lfittl** [comment]
To add to this - whilst we can currently use a no-op UPDATE to workaround a simple `FOR UPDATE`, this isn't true for a `FOR UPDATE NOWAIT` query.

I noticed this hasn't been prioritized for 6.2, and just wanted to point out that the NOWAIT use case might warrant looking into this earlier rather than later since customers are running into this as they port their (multi-tenant) applications to Citus.

**Comment by habibc** [comment]
Plus one for this feature. We need vanilla `Select for update` for processing data in our current workflow. We need it because we write a row to a table and later we pick it by "select for update" for processing. Since the signal to pick the row is sent by a distributed message queue that does not guarantee exactly once delivery we do this to avoid deadlocks between competing workers.

**Comment by ozgune** [comment]
@lfittl -- We're looking at this issue now. We had two clarification questions.

1. Does `SELECT ... FOR UPDATE` hit a single tenant?
2. Does `SELECT ... FOR UPDATE` touch reference tables?

**Comment by lfittl** [comment]
@ozgune  All depends on the application of course. In the simplest case I think we should support `SELECT ... FOR UPDATE` on a transaction for a single tenant, without support for reference tables.

**Comment by qeternity** [comment]
Any update on this? We're in the process of updating to a newer version of Django which now makes extensive use of SELECT ... FOR UPDATE within its ORM when doing get_or_create/update_or_create operations. These currently fail even when being done across a single partition.

**Comment by ozgune** [comment]
Hey @habibc, @qeternity, @jyunis, @bpatridge, @lfittl, we're working on this feature as part of our Citus 7.5 release.

We're now gathering requirements for this feature. Could you share with us example queries (and table distribution columns) where you needed this functionality?

**Comment by jyunis** [comment]
@ozgune - That's great! I haven't set up Citus yet but using the Django ORM (1.10+) does a `SELECT FOR UPDATE` as the first step in the transaction when using the `update_or_create()` method to create a record, e.g.:

`SELECT <fields> FROM <table> WHERE (<filter fields>) FOR UPDATE`

Followed by either an INSERT or UPDATE depending on the result of the SELECT.

**Comment by qeternity** [comment]
As @jyunis says, the Django ORM as of 1.10 as updated its internal calls to avoid race conditions. We’ve had to monkey patch the Postgres driver so that we can use it with Citus, but it means we lose the race condition protection.
