### ISSUE TITLE
master_get_local_first_candidate_nodes is unused, untested, and undocumented

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#1238]
Maybe we should remove it?

**Comment by jasonmp85** [comment]
Yes.

**Comment by jasonmp85** [comment]
(I've known this for some time)

**Comment by lithp** [comment]
Well, I'm glad someone knew about it, and we weren't just unintentionally leaving unused code lying around ;)

**Comment by sumedhpathak** [comment]
Seems like this was used in `STAGE`. Looking back at the PR, I noticed this comment:
https://github.com/citusdata/citus/pull/737#issuecomment-240174856. 

@lithp Have we removed the other referenced functions?
- master_get_local_first_candidate_nodes
- master_get_round_robin_candidate_nodes
- master_stage_shard_row
- master_stage_shard_placement_row

Looks like Marco's question remained open, as does Andres's. @samay-sharma @ozgune Any reason we can think of for keeping the functions around?

**Comment by lithp** [comment]
All of these have been removed as of #1255
