### ISSUE TITLE
Add support for Alter Table Add/Drop Constraint

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1239]
We currently don't propagate Alter Table Add/Drop Constraint commands to related shards. This feature request came up in a customer conversation; and I'm opening this issue to track it.

<pre>
ALTER TABLE triggers DROP CONSTRAINT IF EXISTS triggers_pkey;
ERROR: alter table command is currently supported
DETAIL: Only ADD|DROP COLUMN, SET|DROP NOT NULL, SET|DROP DEFAULT and TYPE subcommands are supported.
</pre>

**Comment by lithp** [comment]
Hehe, I thought we had fixed this:

> ERROR: alter table command is currently supported

That's uniquely terrible.

**Comment by velioglu** [comment]
I have started coding this issue today. I think, it will take 6 days to implement it.

**Comment by saicitus** [comment]
+1, recently came up in a customer conversation.
ALTER TABLE ADD UNIQUE CONSTRAINT

**Comment by velioglu** [comment]
@saicitus. After the PR will be merged, user can add unique constraint with ALTER TABLE table_name ADD CONSTRAINT constraint_name UNIQUE(column_name(s)). Note that column_name(s) must include the distribution column.
