### ISSUE TITLE
Add support for renaming Distributed Tables

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#1249]
E.g.

```SQL
ALTER TABLE distributors RENAME TO suppliers;
```

**Comment by lfittl** [comment]
Just to add a quick note that this came up with a current customer, as a maintenance operation they wanted to run.

The motivations for this was/is that their Rails application changed, and they adjusted the model name in the ORM, and would like to have the underlying table name match the new model name.

**Comment by Altonymous** [comment]
This is also very helpful when you need to change the distribution key on a table and want to do an inline replace of the table..

As an example:
`BEGIN TRANSACTION;

CREATE TABLE web_logs_new (
...
);

SELECT create_distributed_table('web_logs_new', 'ip');

ALTER TABLE web_logs RENAME TO web_logs_domain_dist;
ALTER TABLE web_logs_new RENAME TO web_logs;

END TRANSACTION;`

**Comment by marcocitus** [comment]
Fixed by #1939
