### ISSUE TITLE
Avoid replicating sequence defaults to shards

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#1251]
Currently the dependency added by replicating the ```nextval('seqname'::regclass)``` default value causes locking issues while making additional parts of the system transactional. 

We e.g. want to use multiple connections, one for each placement, to create the placements on workers, to allow that table to be the target of a COPY inside the same transaction (which requires one connection per placement).  But the replicated sequence makes doing so in a transactional manner hard, because all the connections have to see that sequence - which isn't the case if it's created in a separate connection & transaction.  Additionally creating a table/column with a sequence default locks the sequence.

A similar issue exist when dropping placements using parallel over multiple connections and also dropping a sequence.  The sequence cannot be dropped until all transactions that drop the shards having a dependency on the shard are dropped, otherwise the DROP SEQUENCE will just block.

Hence @marcocitus and I came to the conclusion/agreement that the best way forward is to remove the sequence default on placements.  I.e. when replicating a table, we'll have GetTableDDLEvents()/pg_get_tableschemadef_string() not output the DEFAULT for nextval() dependencies.

There's still a couple open-ish questions:
- do we continue to replicate sequences when creating placements? Marco is against, I'm slightly in favor, because that seems quite useful for later pushing down INSERT ... SELECT with sequences present.
- if we don't, we continue to replicate DROP SEQUENCE commands? For now  it seems like it'd be better to do so, given that we have previously replicated sequences and they already exist. On the other hand, an orphan sequence on workers wouldn't necessarily hurt us much

This relates to #1229 and #1201 because the sequence dependency causes locking issues for these.

**Comment by mtuncer** [comment]
I am close to be done with basic implementation. I am removing default clause altogether if it contains a call to nextval.  @marcocitus do you see any issues with that ?

One known issue is **"missing default value"** when replicating the table on a different MX node. It needs to contain full definition. I am aware of it and will take care of it before submitting PR.
