### ISSUE TITLE
Consider removing data fetches during distributed joins

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1260]
This may be a duplicate since we discussed this before, but I couldn't find the issue.

We currently have some logic to fetch shards during a distributed join and perpetually cache them, which assumes that shards are read-only. However, this logic may lead to incorrect (stale) join results, especially when creating a single-shard distributed table (see #1258). The router executor also doesn't have any data fetching logic.
 
With `create_reference_table` and explicit co-location support we now have a better alternative for joining a distributed table with a single-shard table and co-located joins. We may want to consider removing the data fetch code, which would significantly simplify the real-time executor and might allow us to unify it with the multi-shard router executor for INSERT..SELECT/DDL. 

There might be some users relying on this logic (and master_expire_table_cache), so this would be a major version change.

**Comment by onderkalaci** [comment]
Though not a solution for this, for the short term we could consider warning users in case they create distributed tables with less than large table shard count and suggest using reference tables.

**Comment by marcocitus** [comment]
> Though not a solution for this, for the short term we could consider warning users in case they create distributed tables with less than large table shard count and suggest using reference tables.

See #1259 ;)

**Comment by ozgune** [comment]
I'm noting this issue as part of the reference table's parent issue (#879). I'm also adding #638, #292, #253, and #56 as semi-related issues.

**Comment by ozgune** [comment]
I'm noting https://github.com/citusdata/citus_docs/issues/238 as a related issue.

We introduced new APIs for reference tables and colocated joins. We have a few old references to broadcast join related config in our docs. Once we implement this feature, we should also remove them from our docs.

**Comment by onderkalaci** [comment]
> There might be some users relying on this logic (and master_expire_table_cache), so this would be a major version change.

Well, I agree with that 😄  But, @velioglu told me that you're not OK with it now? We've bunch of PRs that would resolve #1787, so, we should probably discuss that again whether we'd want a major version upgrade or not (CC: @ozgune)

**Comment by velioglu** [comment]
Fixed by #1980
