### ISSUE TITLE
result of master_get_table_metadata() changes from time to time

### ISSUE THREAD

**Issue by ictlyh** [citusdata/citus#1262]
From the source of function [master_get_table_metadata()](https://github.com/citusdata/citus/blob/master/src/backend/distributed/master/master_node_protocol.c#L92), we know that it returns the current value of config options "citus.shard_replication_factor", "citus.shard_max_size" and "citus.shard_placement_policy" as the value of replication factor, shard max size and shard placement policy, respectively. How ever, all there three config options are changeable via the command "SET", therefore the result of master_get_table_metadata() changes from time to time.

Test result as below:

<pre>
luoyuanhao=# select * from master_get_table_metadata('tb1');
 logical_relid | part_storage_type | part_method | part_key | part_replica_count | part_max_size | part_placement_policy 
---------------+-------------------+-------------+----------+--------------------+---------------+-----------------------
         16618 | t                 | h           | id       |                  1 |       1024000 |                     2
(1 row)

luoyuanhao=# set citus.shard_replication_factor =1;
SET
luoyuanhao=# select * from master_get_table_metadata('tb1');
 logical_relid | part_storage_type | part_method | part_key | part_replica_count | part_max_size | part_placement_policy 
---------------+-------------------+-------------+----------+--------------------+---------------+-----------------------
         16618 | t                 | h           | id       |                  1 |       1024000 |                     2
(1 row)

luoyuanhao=# set citus.shard_replication_factor =3;
SET
luoyuanhao=# select * from master_get_table_metadata('tb1');
 logical_relid | part_storage_type | part_method | part_key | part_replica_count | part_max_size | part_placement_policy 
---------------+-------------------+-------------+----------+--------------------+---------------+-----------------------
         16618 | t                 | h           | id       |                  3 |       1024000 |                     2
(1 row)

luoyuanhao=# set citus.shard_max_size =10000;
SET
luoyuanhao=# select * from master_get_table_metadata('tb1');
 logical_relid | part_storage_type | part_method | part_key | part_replica_count | part_max_size | part_placement_policy 
---------------+-------------------+-------------+----------+--------------------+---------------+-----------------------
         16618 | t                 | h           | id       |                  3 |      10240000 |                     2
(1 row)

luoyuanhao=# 
</pre>`

Besides, the config option 'citus.shard_replication_factor' takes effects while calling "[master_create_emtpy_shard()](https://github.com/citusdata/citus/blob/master/src/backend/distributed/master/master_stage_protocol.c#L70)" for append-distributed table, the replication factor of the shard of the append-distributed table maybe different from time to time, does it matter? What about the other config options?

I suggest that we should add "replication_factor", "shard_number" and just like attributes to struct [DistTableCacheEntry](https://github.com/citusdata/citus/blob/master/src/include/distributed/metadata_cache.h#L25), and maybe use these values but not the value of current config options in "master_create_emtpy_shard()".

**Comment by marcocitus** [comment]
master_get_table_metadata has been deprecated
