### ISSUE TITLE
DROP SEQUENCE deadlocks when using master as worker

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1269]
Whenever you drop a sequence (inc. a table with a serial column), master_drop_sequences is called via the SQL_DROP trigger and sends DROP SEQUENCE IF EXISTS commands to workers *even if the sequence is not used for a distributed table*. This creates self-deadlocks when a node is its own worker.

```
SELECT master_add_node('localhost', 5432);
CREATE SEQUENCE foo;
DROP SEQUENCE foo;
... deadlock ...
```

The only resolution is to remove the node from pg_dist_node:

```
SELECT master_remove_node('localhost', 5432);
DROP SEQUENCE foo;
... no deadlock ...
```

**Comment by anarazel** [comment]
> Whenever you drop a sequence, master_drop_sequences is called via the SQL_DROP trigger and sends DROP SEQUENCE IF EXISTS commands to workers *even if the sequence is not used for a distributed table*. This creates self-deadlocks when a node is its own worker.

Wondered before if we should remotely disable ddl propagation while propagating...

**Comment by marcocitus** [comment]
Wouldn't matter, the problem is that the master has already dropped the sequence and then connects to self and tries to drop it again.

**Comment by jasonmp85** [comment]
> master_drop_sequences is called via the SQL_DROP trigger and sends DROP SEQUENCE IF EXISTS commands to workers even if the sequence is not used for a distributed table

Wait, what? Repro, plz?

**Comment by jasonmp85** [comment]
Hm… just re-read the code and it looks like maybe that's how it does things? I seem to remember there being a problem determining whether a sequence actually belongs to a distributed table in the drop trigger. Digging up the PR, since this probably got discussed there.

**Comment by jasonmp85** [comment]
Yeah, I documented this problem [here](https://github.com/citusdata/citus/pull/673#issuecomment-235177827)

> Using the utility hook does _not_ seem to capture the sequence drop portion when dropping a sequence-owning table. The event trigger seems natural, though by the time the loop informs me a sequence is being dropped, I can no longer figure out what relation it was associated with (its information in `pg_depend` is gone). And since the `EVENT TRIGGER` drops the table (and shards) before processing the sequence drop, even the placement rows are already gone (so finding the affected nodes isn't possible at that point in time). I'll fix this early in the morning.

**Comment by jasonmp85** [comment]
@anarazel replied [here](https://github.com/citusdata/citus/pull/673#issuecomment-235341613):

> For simplicity a reasonable approach is to simply always replay drop sequence commands on workers.  ISTM that before long we'll unconditionally replicate CREATE FUNCTION/OPERATOR/TYPE/SEQUENCE, because things are just too painful to use without that.

And I replied back clarifying the behavior I ended up going with:

> This elides the fact that there is no canonical set of "workers". Just the list of to-be-workers-when-shards-are-next-created in `pg_worker_list.conf` and the list of _de facto_ workers specified by the hostnames and ports in `pg_dist_shard_placement`. Seems safest to actually record where the shards are being dropped, and send sequence commands there (which is what I've done).

So I think that behavior is what we have to go with, but we need to make sure it works correctly with master-as-worker configurations (which weren't really a thing when this was first merged).

**Comment by marcocitus** [comment]
I think one approach would be to stop dropping sequences and always create/reset them in an idempotent way.

**Comment by marcocitus** [comment]
I think we can just change `master_drop_sequences` to only send the `DROP SEQUENCE` command to workers with metadata. We currently only create sequences for MX tables.

Older users might still have some sequences that were created as part of shard placement creation. Nowadays we strip the default expression from shards and only use the sequence in the coordinator or MX tables.
