### ISSUE TITLE
Invalidate cached plans for PREPARE statements. 

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#127]
When metadata changes, we need to invalidate the cached plans. The reason is that when metadata changes, we need to build new MultiPlan according to the updated metadata. For instance, currenltly if we add new shards, prepared statements would not be able to get data from those shards.

**Comment by ozgune** [comment]
@anarazel mentions that we ended up doing most of the work associated with this issue. However, we need to check if we're missing pieces related to invalidating cached plans in our codebase.

I'm assigning this issue to Andres so that we document the remaining work involved.

**Comment by anarazel** [comment]
We have invalidation support for pg_dist_shard (i.e. new shard creation), and pg_dist_partition (i.e. new distributed tables), and ALTERing tables/indexes. I think what's primarily missing is that we add invalidation for pg_dist_shard_placement, which should be easy.
There's also some ad-hoc caches in various places, without invalidation support; those will need to be evaluated as well.

**Comment by anarazel** [comment]
@sumedhpathak, @ozgune Lookes like we need to schedule this work.

**Comment by marcocitus** [comment]
What @anarazel said :)

**Comment by sumedhpathak** [comment]
@anarazel noted a quick fix which reduces the probability of this occuring. We marked it as a 6.0 release item. @anarazel could you update the issue after discussion with @marcocitus

**Comment by ozgune** [comment]
We merged in #914 and #916 to address the probability of this issue occurring. I'm therefore removing the v6.0 milestone (part) from the issue.
