### ISSUE TITLE
Concurrent DDL might deadlock in the presence of foreign keys

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1276]
I haven't tried to reproduce this yet, but it seems that concurrent DDL commands on tables with a foreign key between them might deadlock since we do not take locks on other tables in the coordinator prior to issuing DDL commands on the workers, where the DDL commands would try to obtain conflicting locks in different orders.

A possible solution is to implement #357.

**Comment by jasonmp85** [comment]
FWIW we're implementing #357 :-D

**Comment by marcocitus** [comment]
Fixed by #1278
