### ISSUE TITLE
Standardize our terminology on master / coordinator node

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1285]
Citus started out with the notion of a single node that served the following purposes in the context of complex analytical workloads: (a) keeps distributed metadata, (b) serves as endpoint for clients to connect to, (c) managed other nodes in the cluster, and (d) perform maintenance operations such as DDL changes. We therefore referred to this node as the "master node".

Three changes happened since. Citus expanded on the set of use cases it addresses, Citus Cloud started managing the nodes in the cluster, and the Citus MX (#744) project enabled distributing metadata to all nodes in the cluster. We therefore started referring to this node as the "coordinator node" in our website.

Our mixed use of terminology is now confusing our users (#207). We therefore decided to consistently use one name, the coordinator node. This requires that we make a few changes in our docs and udf names. In particular:

1. We change our documentation to consistently use the term "coordinator node". This involves changing references to master with coordinator and updating our architectural diagrams.
2. Our Docker images starts up one citus_master and citus_worker. We should revise the term citus_master to citus_coordinator.
3. Some of our external and internal UDFs use the prefix "master". We should start by adding aliases that use the prefix "coordinator" instead (#1286).

An orthogonal dimension to this issue is to decide on what specifically we'd like the coordinator node's responsibilities to be. Do users connect to the coordinator to perform DDL changes? With on-prem deployments, is the coordinator also responsible for tracking other nodes' healths?

**Comment by marcocitus** [comment]
We mostly moved away from master and effectively deprecated UDFs starting with master.
