### ISSUE TITLE
Citus <-> pg_shard hash partitioning isn't compatible.

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#129]
Currently we can't do a re-partition join between a pg_shard hash-partitioned table and a CitusDB range partitioned table.
(Single-repartition of a range-partitioned table to join with a hash-partitioned table).

The reason is that the hash-partitioning method between the two don't match.

pg_shard creates a range of hash-tokens, and each partition owns a range (e.g. partition 0 owns 0 -> 10).

However, CitusDB does a 'mod' based partitioning. So value 0 will go to partition 0, value 1 will go to partition 1 etc.

We need to modify CitusDB's partitioning to match pg_shard (possibly by providing a range similar to current range partitioning).

**Comment by anarazel** [comment]
@jasonmp85 I think we should close this issue?

**Comment by jasonmp85** [comment]
Sure, let's close.
