### ISSUE TITLE
Simpler single node install (Docker image) and/or OS X install

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#13]
Most new users start with trying out unofficial Citus Docker images. We also currently don't have an install story except from source for OS X. We need to have simpler single node install (Docker image) and/or OS X install instructions.

**Comment by sumedhpathak** [comment]
@ozgune Mark this item as done?

**Comment by jasonmp85** [comment]
@sumedhpathak let's wait to see about Homebrew/homebrew#50392. The turnaround on new formula looks to be around two days.

**Comment by sumedhpathak** [comment]
Marking this as done now that we have homebrew. @jasonmp85 let me know if something here remains.
