### ISSUE TITLE
Timestamp column with default causes JDBC error

### ISSUE THREAD

**Issue by trasa** [citusdata/citus#1304]
If I have a sharded table that looks like this:

    create table uuidsample (id uuid,
                         other_id bigint,
                         name varchar(50) not null,
                         namespace varchar(50) not null,
                         create_date timestamptz not null default now());

And some JDBI code like this:

```
// line breaks added for readability
@SqlUpdate("insert into uuidsample(id, other_id, name, namespace) 
         values (:id, :other_id, :name, :namespace) on conflict do nothing")
int createUUID(@Bind("id") UUID id, @Bind("other_id") long otherId, 
        @Bind("name") String name, @Bind("namespace") String namespace);
```

Attempting to insert a row gives me this error:

```
    org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: org.postgresql.util.PSQLException: 
ERROR: no value found for parameter 3 [statement:"insert into uuidsample(id, other_id, name, namespace) values (:id, :other_id, :name, :namespace) on conflict do nothing", 
located:"insert into uuidsample(id, other_id, name, namespace) values (:id, :other_id, :name, :namespace) on conflict do nothing", 
rewritten:"insert into uuidsample(id, other_id, name, namespace) values (?, ?, ?, ?) on conflict do nothing", 
arguments:{ positional:{}, named:{name:'asdf',namespace:'ns',id:4ac7d33f-a963-4fcc-b20c-17ad143524a6,other_id:1}, finder:[]}]
```

But getting rid of the create_date column causes the error to go away. This code works fine with plain old unsharded postgres table of same construction.

Thoughts? I have uploaded the code used to repro this to https://github.com/trasa/citus_default_date_bug/

**Comment by byucesoy** [comment]
Thank you for reporting this bug. I also tried it without JDBI and it worked. It seems Citus cannot process some queries generated by JDBI, this is likely to be related with PREPARED statements.

**Comment by trasa** [comment]
FYI I tried the code using the Fluent API of JDBI and get the same exception.

**Comment by trasa** [comment]
One more update: can reproduce problem using JDBC prepared statements; agreeing that this is related to #983 and #306
