### ISSUE TITLE
Support for DISTINCT ON clause on citus

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus#1307]
<pre>
SELECT DISTINCT ON (part_col) col1,col2,col3
FROM TABLE;
ERROR:  could not run distributed query with DISTINCT clause
HINT:  Consider using an equality filter on the distributed table's partition column.
</pre>

This is push-downable, but still it throws an error.
Came up in 2 user conversations. In one of these conversations, **this is the only / major blocker.**

**Comment by ozgune** [comment]
@saicitus -- I have a clarification question and a note.

* Could you describe a bit more how the ``DISTINCT ON`` clause is different than ``DISTINCT``? When do users run ``DISTINCT ON`` clauses?
* We have ongoing work for Citus 6.2 to notably expand our SQL coverage. Do the improvements in #1204 resolve this issue?

**Comment by ozgune** [comment]
@saicitus / @onderkalaci -- Are we resolving this issue with our upcoming improvements in #1204? If we are, I'm planning to close this issue.

**Comment by onderkalaci** [comment]
#1204 only deals with subqueries, so the answer is that no we're not resolving this in 6.2.


But, there is a workaround for doing that both in 6.1 and 6.2 using subqueries. Basically, wrap the query into another query:

```SQL
SELECT user_id, value_2, value_3
FROM
(
    SELECT DISTINCT ON (user_id) user_id, value_2, value_3
     FROM users_table
     WHERE (value_1 > 3)
     ORDER BY 1,2,3
) subquery;

```
(Note that in some cases -- not this one, PostgreSQL pulls up subqueries and Citus fails to recognize the subqueries. In such cases, adding a volatile function prevents postgres from pulling up the subqueries such as):

```SQL
SELECT user_id, value_2, value_3
FROM
(
SELECT DISTINCT ON (user_id) user_id, value_2, value_3, random()
     FROM users_table
     WHERE (value_1 > 3)
     ORDER BY 1,2,3 
) subquery;
```

> Came up in 2 user conversations. In one of these conversations, this is the only / major blocker.

@saicitus Does the above help?

> Could you describe a bit more how the DISTINCT ON clause is different than DISTINCT? When do users run DISTINCT ON clauses?

Also, for the details of `DISTINCT ON`, I think the official PostgreSQL [documentation](https://www.postgresql.org/docs/9.5/static/sql-select.html#SQL-DISTINCT) seems concise.

**Comment by saicitus** [comment]
@onderkalaci Above makes sense but one clarification, could you give an example case in which postgres pulls up subqueries(with DISTINCT ON). I tested very simple queries like **SELECT * FROM (SELECT DISTINCT ON(tenant_id) id from test_table)a;**(with citus.subquery_pushdown on) and postgres still keeps it as a subquery.
