### ISSUE TITLE
Add session-level GUC to log all cross-shard queries

### ISSUE THREAD

**Issue by lfittl** [citusdata/citus#1308]
One of the issues that frequently comes up in customers migrating to Citus, especially in a multi-tenant model, is understanding if there are any cross-shard (i.e. realtime/task-tracker executor) queries in a particular part of the customer's application code.

Right now one has to manually check all executed SQL and verify that the tenant_id is present on the queries.

Ideally we'd have a GUC (e.g. `citus.log_dist_statement`, defaulting to `off`) on the coordinator that can be set on a per-session basis to something like `cross_shard` or `multi-shard`.

When enabled all cross-shard queries should be output to the logfile, similar to how `log_statement` is output:

```
2014-11-24 22:17:15 CET LOG:  statement: SELECT * FROM objects WHERE id = 123;
```

---

**Stretch goal:**

We could consider including the duration in the output as well, or even naming this `citus.log_min_duration_multi_shard_statement` and make it work similarly to `log_min_duration_statement` (i.e. `-1` is the default and logs nothing, `0` logs everything, `500` logs every cross-shard/multi-shard query that is slower than 500ms).

This is not required however, since the customer mostly cares whether they missed any cross-shard queries in their app migration work (i.e. forgot to add tenant_id to queries), and would only use this in development.

**Comment by lithp** [comment]
It's probably faster to add a GUC which disables cross-shard queries and makes them error out. How much do you prefer logging them instead?

Also, I think we already emit `DEBUG` output saying which executor was used, why can't clients use that?

**Comment by metdos** [comment]
> Also, I think we already emit DEBUG output saying which executor was used, why can't clients use that?

I suppose this is to debug why system/some queries get slower. We don't want to log all of the queries. This is just for a couple queries which is supposed to be router executable.

**Comment by byucesoy** [comment]
> > Also, I think we already emit DEBUG output saying which executor was used, why can't clients use that?
> 
> I suppose this is to debug why system/some queries get slower. We don't want to log all of the queries. This is just for a couple queries which is supposed to be router executable.

I guess this GUC will only be used for short time, before going to production to check whether every query has tenant_id. If that is the case @lithp's both suggestions make sense.

**Comment by lfittl** [comment]
@lithp On the erroring out, this was my initial thought as well - but after some discussion with Craig and asking customers, it seems that having an explicit log of cross-shard queries is preferred.

Why we can't use the existing DEBUG output: It would be way too verbose. This is specifically for multi-tenant apps, where 95% of queries should be single-shard, router executor queries.

If we ask customers to use the DEBUG output they have to write their own log filtering and probably work with logfiles of significant size. Having an explicit setting makes this much simpler, since they can just read the (ideally small) logfile.

Hope that makes sense, happy to jump into a call to discuss further :)

**Comment by anarazel** [comment]
In an earlier conversation I suggested that the GUC for this can be set to one of the existing log-levels.  If e.g. set to WARNING it'll log message at WARNING level, if set to ERROR it'll error out. (we'd obviously have to disallow at least PANIC).  That'll allow to tune things so that e.g. during testing it can be set to ERROR, and live it can be set to LOG.

**Comment by metdos** [comment]
Hey @lfittl, we are planning to have `multi_task_query_log_level` guc variable with "off", "debug", "log", "notice",  "warning", "error" options. Does this work?

**Comment by lfittl** [comment]
@metdos That seems good - just to confirm, if you set `citus.multi_task_query_log_level = error` it would essentially prevent an application from running any cross-shard queries, correct?

Also, how would this interact with a transaction - could I disable the setting for parts of a transaction (e.g. for initial setup in a unit test), and then enable `citus.multi_task_query_log_level = error` whilst still being inside that same transaction?

Thanks!

**Comment by anarazel** [comment]
On 2017-04-19 11:01:44 -0700, Lukas Fittl wrote:
> Also, how would this interact with a transaction - could I disable the setting for parts of a transaction (e.g. for initial setup in a unit test), and then enable `citus.multi_task_query_log_level = error` whilst still being inside that same transaction?

Yes.

**Comment by velioglu** [comment]
> if you set citus.multi_task_query_log_level = error it would essentially prevent an application from running any cross-shard queries, correct?

Yes, it will error out.
