### ISSUE TITLE
Allow joins between a distributed table and jsonb_array_elements(jsonb) 

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus#1310]
This occurs when a user tries to join each row of a table with a jsonb entry which is a part (either a jsonb column or an jsonb typed attribute of a jsonb column) etc. of that row itself.
Example:
```
select a.id, b.* from distributed_table a, 
jsonb_array_elements(a.jsonb-> 'children') 
b where b.value -> 'name' != 'null'::jsonb limit 10;
```

**Comment by metdos** [comment]
@velioglu, could you research about the reason of this problem and update the issue with this information? Then, we can decide how we want to fix this issue.

**Comment by marcocitus** [comment]
The reason is that we haven't implemented joins with functions. The fix would be to implement it :).

Joins with functions are a bit complex to reason about in general.

As a workaround, you can do something like:
```
SET citus.subquery_pushdown TO on;
SELECT * FROM (SELECT a.id, jsonb_array_elements(a.jsonb->'children') AS value FROM distributed_table a) a WHERE value->'name' != 'null'::jsonb LIMIT 10;
```

**Comment by marcocitus** [comment]
This seems to work now.
