### ISSUE TITLE
Expand transaction coverage for queries that touch reference and distributed tables

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1328]
We recently had a few requests around expanding transaction coverage for queries that touch reference and distributed tables. For example:

<pre>
BEGIN
SELECT nextval(org_table)
INSERT INTO org_table ... RETURNING id
SELECT DISTINCT ... FROM campaign_table INNER JOIN ads_table ....
SELECT users FROM users ...
INSERT INTO users ...
ROLLBACK
</pre>

In this example, the `users` table is a reference table, and all other tables are distributed tables sharded on `tenant_id`. Also, @lfittl shared an internal email (re: Issue with reference tables in transactions) that have more examples.

One question here is related to distributed deadlock detection. Citus can push these queries by setting ` citus.enable_deadlock_prevention = off`.

**Comment by ozgune** [comment]
I'm also noting the issue on SAVEPOINTs (#1493) as slightly related to this one.

**Comment by onderkalaci** [comment]
This seems to be fixed by #1529. Any reason not to close the issue?
