### ISSUE TITLE
EXPLAIN ANALYZE with DML executes write twice

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1344]
I think this used to just throw an error:

```
CREATE TABLE test (x int, y int);
SELECT create_distributed_table('test', 'x');
EXPLAIN ANALYZE INSERT INTO test (x) VALUES (5);
                                                   QUERY PLAN                                                   
----------------------------------------------------------------------------------------------------------------
 Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0) (actual time=5.292..5.292 rows=0 loops=1)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Insert on test_102951  (cost=0.00..0.01 rows=1 width=8) (actual time=0.058..0.058 rows=0 loops=1)
               ->  Result  (cost=0.00..0.01 rows=1 width=8) (actual time=0.001..0.002 rows=1 loops=1)
             Planning time: 0.321 ms
             Execution time: 0.099 ms
 Planning time: 0.177 ms
 Execution time: 5.357 ms
(11 rows)

postgres=# SELECT * FROM test;
 x | y 
---+---
 5 |  
 5 |  
(2 rows)
```

**Comment by sumedhpathak** [comment]
Ok, this isn't good :). Is this related to recent changes in 6.2, or custom-scan changes? @metdos could you investigate this? Thanks!

**Comment by anarazel** [comment]
On 2017-04-21 10:18:31 -0700, Sumedh Pathak wrote:
> Ok, this isn't good :). Is this related to recent changes in 6.2, or custom-scan changes? @metdos could you investigate this? Thanks!

It's custom scan.  I wonder if the better fix wouldn't be to always
execute the EXPLAIN (...) on the workers inside a savepoint that's
rolled back?  You can have fairly nasty sideeffects with functions and
such too, and just erroring out for DML doesn't address that.

- Andres

**Comment by metdos** [comment]
> It's custom scan.  I wonder if the better fix wouldn't be to always
> execute the EXPLAIN (...) on the workers inside a savepoint that's
> rolled back?  You can have fairly nasty sideeffects with functions and
> such too, and just erroring out for DML doesn't address that.

I did a dirty prototype for this (savepoint approach) by changing how we send explain queries to workers nodes in `RemoteExplain()` (I needed to replace `ExecuteRemoteQuery` with transactional remote calls). After cleaning the branch, I will open the PR.
