### ISSUE TITLE
Cannot change sharding key

### ISSUE THREAD

**Issue by stevorobs3** [citusdata/citus#1352]
I have created a distributed table and would like to change the sharding key. It doesn't seem to be possible to do this. You can drop the distributed table (and then could recreate it with a different key), but that drop also drops the original table. Is there a work around for this or am I missing something?

**Comment by lithp** [comment]
Hello there, sorry it took so long for this ticket to get noticed!

Unfortunately there's no easier way to change the sharding key than dropping and recreating the table. Usually your data model has been designed with a specific use-case in mind and changing the axis around which your data is distributed is an exceptionally rare operation, you'd only do that if you're now using your database quite differently than when you first started using it.
