### ISSUE TITLE
Join of a router plannable subquery with another query error out

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#1371]
Create a hash partitioned table
```SQL
CREATE TABLE hp(a int, b int);
SELECT create_distributed_table(‘hp’, ‘a’);
```
Run query
```sql
SELECT * FROM 
    (SELECT a, b FROM hp WHERE a = 5 group by 1, 2) u1,
    (SELECT a, b FROM hp WHERE a = 18 group by 1, 2) u2
WHERE u1.a = u2.a;
```
Result:
```
ERROR:  not implemented
```

It still returns and error when you join a single-shard subquery with a multi-shard subquery
```sql
SELECT * FROM 
    (SELECT a, b FROM hp WHERE a = 5 group by 1, 2) u1,
    (SELECT a, b FROM hp WHERE a > 18 group by 1, 2) u2
WHERE u1.a = u2.a;
```

**Comment by onderkalaci** [comment]
Please see #1372, we had some weird merge issue. Also, as far as I can see, the issue has nothing to do with router planning given that setting router execution to false prevents this error. 

It's basically a bug that was introduced during subquery pushdown work but unfortunately not checked-in to the master as explained in #1372.

The issue should have been fixed there with the [commit](https://github.com/citusdata/citus/pull/1372/commits/640d5baa8cf30a4c6796c3e7935c6b93d8a892a8) on the master as well.

@mtuncer  Could you ensure that it is fixed on the master branch now?

**Comment by mtuncer** [comment]
verified the fix is in. closing this one.
