### ISSUE TITLE
Add Progress Tracking Infrastructure

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#1375]
For getting progress information about long running jobs (CREATE INDEX, COPY, rebalance, etc.) we should add a reusable infrastructure.

One way to add this is to create DSM segments in the beginning of the operation, store the dsm segment handle, progress id and process type in `pg_stat_get_progress_info` output by calling `pgstat_progress_start_command` and fetch the info when the progress info is requested.

**Comment by lithp** [comment]
What is a DSM segment?

**Comment by anarazel** [comment]
On 2017-05-03 14:14:06 -0700, Brian Cloutier wrote:
> What is a DSM segment?

dynamic-shared-memory segment.  See dsm.c/h in postgres.

**Comment by marcocitus** [comment]
This has been implemented in `multi_progress.c`
