### ISSUE TITLE
Truncate fails if shards are dropped concurrently

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#1381]
Looks like truncate command pre-fetches shards to be dropped before it was blocked by concurrent transaction.  Shards are already dropped and committed by the time the first worker receives truncate command. The command fails and returns shard does not exist error.

## Steps
- 2 concurrent connections are opened. 
- connection 1 starts a transaction and issues drop all shards command
- before connection 1 commits, connection 2 issues truncate table command.

### Connection 1
```sql
begin;
select master_drop_all_shards('drop_test'::regclass, 'public', 'drop_test');
commit;
```

### Connection 2
```sql
truncate table drop_test;
```

Expected
- connection 2 to be blocked until connection 1 commits
- truncate command to complete silently since there is nothing left to truncate

Result
- connection 2 to be blocked until connection 1 commits ✅ 
- truncate command returned error stating some shard cannot be found ❌ 
```
ERROR:  relation "public.drop_test_102040" does not exist
CONTEXT:  while executing command on localhost:9700
```

**Comment by marcocitus** [comment]
Related to #727 and #761.
