### ISSUE TITLE
Concurrent creation of a distributed table from non-empty table and copy into a same table result in empty table

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#1398]
### Setup:
- A local table with some data in it
- An external file to load data from

### Connection 1:
- Starts a transaction,
- issues copy to local table
- does not commit

### Connection 2:
- Starts a transaction
- Issues create distributed table table (blocked)
---
When Connection 1 commits, connection2 gets unblocked and creates a distributed table.

However the distributed table does not contain any data. Expect it to contain both old, and recently copied in data.

Removed the row in pg_dist_partition to make the table local again, verified copied data is still there.

It is somewhat related to #1392

**Comment by onderkalaci** [comment]
> It is somewhat related to #1392

I think it is exactly the same.
