### ISSUE TITLE
Concurrent calls to master_remove_node fails with “tuple concurrently updated” error

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#1400]
### Steps
- Connection 1
  - Starts transaction
  - Calls master_remove_node
  - Does not commit;
- Connection 2
  - Starts transaction
  - Calls master_remove_node
  - Blocked
- Connection 1 commits
- Connection 2 gets unblocked fails with “Error: tuple concurrently updated”

Same behavior is observed when master_activate_node and master_remove_node is called concurrently where activate is called first.

**Comment by mtuncer** [comment]
Clarification : functions are called for the same node

**Comment by sumedhpathak** [comment]
@mtuncer Isn't this expected behavior? Or are we expecting something different to happen? Thanks.

**Comment by marcocitus** [comment]
Definitely not the expected error message. 

The table locking in `node_metadata.c` needs work.
