### ISSUE TITLE
master_add_node fails when a different user have created a reference table in a different schema

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#1411]
Steps to reproduce:
1. Setup two node cluster
2. Create the following reference table in a schema as a regular user:
 ```CREATE SCHEMA tutorial;

CREATE TABLE tutorial.users (
  user_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email text NOT NULL UNIQUE,
  encrypted_password text NOT NULL ,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id)
);
```
3. Call master_add_node

Error on coordinator:
```
ERROR:  must be member of role "postgres"
CONTEXT:  while executing command on ec2-35-166-240-133.us-west-2.compute.amazonaws.com:5432
STATEMENT:  SELECT master_add_node('ec2-35-166-240-133.us-west-2.compute.amazonaws.com', 5432)
```

Error on worker:
```
ERROR:  must be member of role "postgres"
STATEMENT:  SELECT worker_apply_shard_ddl_command (102008, 'CREATE SCHEMA IF NOT EXISTS tutorial AUTHORIZATION postgres')
``` 

 ```citus=> \dn
   List of schemas
   Name   |  Owner   
----------+----------
 citus    | postgres
 public   | postgres
 tutorial | citus
(3 rows)
```
note that the schema is owned by citus user, not postgres user - but we incorrectly try to create it with the postgres user as owner

**Comment by byucesoy** [comment]
@aamederen @lfittl 

I could not reproduce this problem. Could you add more detailed steps? How did you create users? Did you use Citus Cloud or local citus cluster?

I do not think this is a complex bug. We can probably fix it with a small patch, but we completed release testing and plan to start packaging this Monday. If you can provide more details to reproduce this issue, I can create a quick PR then we can evaluate whether we want to add it to this release or backport it later.

**Comment by lfittl** [comment]
@byucesoy Did you try to reproduce this on enterprise master or community?

I can reproduce this just now on current enterprise master on Citus Cloud. Note that Citus Cloud calls master_add_node(...) automatically, and eagerly (i.e. sometimes when the node is not up yet) but that shouldn't generate the wrong authorization. It seems to be that we are missing some logic to correctly determine schema owners in this case.
