### ISSUE TITLE
We don't allow local-joins between RANGE partitioned and APPEND partitioned tables. Should we? Alternately, how do we give customers means to indicate two tables are co-located.

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#142]
We don't allow local-joins between RANGE partitioned and APPEND partitioned tables. Should we? Alternately, how do we give customers means to indicate two tables are co-located.

**Comment by ozgune** [comment]
Citus added logic for table colocation in #695. I'm therefore closing this issue.

**Comment by anarazel** [comment]
On 2017-02-18 12:40:55 -0800, Ozgun Erdogan wrote:
> Citus added logic for table colocation in #695. I'm therefore closing this issue.

But neither append nor range partitioned tables can be marked colocated currently?

**Comment by jasonmp85** [comment]
Yeah, I feel that issue answers the second question, but not the first.
