### ISSUE TITLE
DROP EXTENSION citus fails in SQL_DROP trigger

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1421]
Set up some dummy SQL_DROP trigger that with a statement that goes through the planner hook:
```
CREATE TABLE public.unrelated_table (x int, y int);

CREATE OR REPLACE FUNCTION cleanup()
 RETURNS event_trigger
 LANGUAGE plpgsql
AS $function$                         
BEGIN
    /* go into citus planner hook */
   DELETE FROM public.unrelated_table;
END;                      
$function$;        
CREATE EVENT TRIGGER cleanup_trigger ON SQL_DROP
EXECUTE PROCEDURE cleanup();
```

Then in new session, `DROP EXTENSION citus` attempts to access `pg_dist_partition` (OID 51219) after it was dropped:
```
DROP EXTENSION citus; 
ERROR:  could not open relation with OID 51219
CONTEXT:  SQL statement "DELETE FROM public.unrelated_table"
PL/pgSQL function cleanup() line 3 at SQL statement
```

However, it succeeds the second time:
```
# DROP EXTENSION citus;
DROP EXTENSION
#
```

**Comment by anarazel** [comment]
On 2017-05-17 03:32:25 -0700, Marco Slot wrote:
> Set up some dummy SQL_DROP trigger that with a statement that goes through the planner hook:

While a bug, I don't think it's particularly severe/blocking. Agreed?

**Comment by marcocitus** [comment]
Yep, just something I randomly ran into.
