### ISSUE TITLE
pg_dist_node changes for 7.0

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#1423]
**Proposal**

```
                            Table "pg_catalog.pg_dist_node"
   Column    |  Type   |                           Modifiers                           
-------------+---------+---------------------------------------------------------------
 nodeid      | integer  | not null default nextval('pg_dist_groupid_seq'::regclass)
 groupid     | integer  | not null default nextval('pg_dist_node_nodeid_seq'::regclass)
 nodename    | text     | not null
 nodeport    | integer  | not null default 5432
 noderack    | text     | not null default 'default'::text
 hasmetadata | boolean  | not null default false
 isactive    | boolean  | not null default true
 connopts    | text     |
 regionid    | text     | not null default 'home'
 noderole    | noderole | not null default 'primary'::noderole
Indexes:
    "pg_dist_node_pkey" PRIMARY KEY, btree (nodeid)
    "pg_dist_node_nodename_nodeport_key" UNIQUE CONSTRAINT, btree (nodename, nodeport)
Triggers:
    dist_node_cache_invalidate AFTER INSERT OR DELETE OR UPDATE ON pg_dist_node FOR EACH ROW EXECUTE PROCEDURE master_dist_node_cache_invalidate()
```

Changes:
- Add `connopts` for #947, the connection string we use to connect to workers will be
  `"host=$nodename port=$nodeport $connopts"`
- Add a `regionid` for cross-region support.
- Add a `noderole` field, specifying the node's role within its group

---

This assumes two additional GUCs:
- `citus.current_region`: the coordinator will only send queries to nodes which have the same regionid as this GUC.
- `citus.send_queries_to_secondaries`: This can be one of `when-possible` or `never`. In the cross-region case all the nodes in the other region will look like `regionid=us-west noderole='secondary'`, so this GUC must be set to true in order for queries to succeed. `when-possible` means the coordinator will try to send as many queries to the the secondary as it can however some queries, such as SELECT queries which invoke `vextval()`, modify state and must be routed to the primary.

Some notes:
- `CREATE TYPE noderole AS ENUM ('primary', 'unavailable', 'secondary')`
- `CREATE UNIQUE INDEX ON pg_dist_node (groupid, noderole) WHERE noderole = 'primary'::noderole`
- Writes are only ever sent to nodes with the "primary" noderole.
- If `citus.send_queries_to_secondaries` is to "when-possible" there are still plenty of cases where queries could still be sent to the primary, such as if you're inside a transaction or sending an INSERT. Maybe we want to add an `always` option instead and have it error out when the query isn't allowed to be run on a secondary.
- Some functions don't make sense when called on secondaries, they should either error out when called on a secondary or have their signatures changed to accept a groupid rather than nodename and nodeport. And, I think they should error out on `unavailable` nodes as well? The functions are: `{start,stop}_metadata_sync_to_node()`, `master_activate_node()`, and `master_disable_node()`.
- `master_add_node` should include optional parameters specifying which `groupid/role/region it` should be in.

(I've updated this description to incorporate everything from the discussion up to [this comment](https://github.com/citusdata/citus/issues/1423#issuecomment-306319845))

**Comment by marcocitus** [comment]
> Drop noderack, which is completely unused

Not completely. If you `set citus.shard_placement_policy to 'random'` then `master_create_empty_shard` tries to put different placements on different racks. It's rather obscure, for sure.

**Comment by lithp** [comment]
Oof, you're right. I grepped for `nodeRack` and didn't notice we assign it to a field called `workerRack`... Okay, I suppose `workerRack` stays then.

**Comment by marcocitus** [comment]
> If citus.send_queries_to_secondaries is set, reads will only be sent to secondaries and writes will not be allowed.

I think what we do with secondaries might evolve over time. It might make sense to allow multiple values (e.g. at some point we might have '`always`', '`never`', `'load_balance'`, `'primary_failover'`).

**Comment by marcocitus** [comment]
> CREATE TYPE noderole AS ENUM ('primary', 'failing-over', 'secondary')

Behaviour-wise, what is the effect of setting the role to each of these roles?

**Comment by lithp** [comment]
> I think what we do with secondaries might evolve over time. It might make sense to allow multiple values (e.g. at some point we might have 'always', 'never', 'load_balance', 'primary_failover').

Yes, this is a much better idea! Updated the ticket.

**Comment by lithp** [comment]
Recording what we talked about on the call: I'm not sure if `noderole` is the right name because it's kind of simplifying to think about the column in terms of which queries are allowed to be run on the node.

I think it makes sense to go with: `primary`, `secondary`, and `unavailable`. Nodes for which `primary` is set (there only exists one at any given time per group) accept both reads and writes. All queries which happen within a transaction are sent to the `primary` node. SELECT queries which include volatile functions need to hit the `primary` node. [pqmasg](https://github.com/citusdata/pgmasq/blob/master/src/pgmasq.c#L217) had some of this logic. `secondary` nodes are used if the setting for querying secondaries allows it. `unavailable` nodes are either initializing or catching up or failing, it doesn't quite matter but no queries are allowed to be sent to them.

This is different than the `isactive` flag on `pg_dist_node`. If a node is not active then writes to reference tables are allowed, and simply not propagated to the inactive node. If a group has no node which is `primary` then writes to reference tables are disallowed, because it's assumed that the node will come back up soon.

When deciding whether a follower should be in the `secondary` or the `unavailable` state, we use the existing logic in the monitor node for deciding whether a node in asynchronous replication is caught up enough to the primary to fail over. There's probably no reason to have different thresholds? In the case of synchronous replication, the follower is only marked `secondary` if it's entirely caught up and `remote_apply` has been set.

**Comment by lithp** [comment]
Just realized, this also involves changing some of our UDFs. There are some UDFs which don't make sense when called with a secondary:

- `{start,stop}_metadata_sync_to_node()`
- `master_activate_node()`
- `master_disable_node()`

They should either error out when called on a secondary, or have their signatures changed. Rather than accept `(nodename, nodeport)` it'd be cleaner for them to accept `(groupid)`.

Should `master_add_node()` include parameters saying which group/role it has?

**Comment by metdos** [comment]
> I think it makes sense to go with: primary, secondary, and unavailable. Nodes for which primary is set (there only exists one at any given time per group) accept both reads and writes. All queries which happen within a transaction are sent to the primary node. SELECT queries which include volatile functions need to hit the primary node. pqmasg had some of this logic. secondary nodes are used if the setting for querying secondaries allows it. unavailable nodes are either initializing or catching up or failing, it doesn't quite matter but no queries are allowed to be sent to them.
> 
> 
> When deciding whether a follower should be in the secondary or the unavailable state, we use the existing logic in the monitor node for deciding whether a node in asynchronous replication is caught up enough to the primary to fail over. There's probably no reason to have different thresholds? In the case of synchronous replication, the follower is only marked secondary if it's entirely caught up and remote_apply has been set.

I'm curious about what @fdr thinks about having secondaries explicitly on pg_dist_node. @fdr, do you see any problem on the Cloud side? As long as I know, this is a different approach to fail-over than you have.

**Comment by fdr** [comment]
It's more duplication for sure. We freely add and remove standbys and their host names are not stable. As-is, everything works well. It'd be a shame if I had to do careful bookkeeping to make everything work well in the future.

**Comment by anarazel** [comment]
> Add connopts for #947, the connection string we use to connect to workers will be
> "host=$nodename port=$nodeport $connopts"

What exactly are you proposing here? Parse the `$connopts` string with `PQconninfoParse()`, and then overwrite host/port?  Or are you just thinking of of just setting the `options=...` parameter?

This doesn't really give you the power of specifying a full connection string, because these days you can specify things like:
```
postgresql://host1:123,host2:456/somedb
```
i.e. multiple options.   Nor is the options= parameter powerful enough (as it doesn't allow configuring SSL and such).

**Comment by ozgune** [comment]
@lithp / @metdos -- This issue starts with a specific proposal for extending our metadata tables. Before we reach a conclusion, could we explicitly write down **why** we need to add these columns? In particular, what new functionality are we looking to enable with these changes and how do these columns fit into that picture?

In particular, I can think of four reasons:

1. Auto-HA using streaming replication: We already have Citus Cloud in production and our Postgres HA extension. These technologies don't require some of these additional columns. What would these columns by us in this case?
2. Using secondary nodes for read queries
3. Isolating OLTP/OLAP workloads by creating follower nodes
4. Cross-region replication of Citus cluster for low latency reads

**Comment by lithp** [comment]
@ozgune 

Going down them in order of priority

A. Adding `noderole`, this isn't strictly necessary for auto-HA (1) but makes the job easier. Instead of removing nodes when they're down the monitor can just update the `noderole`. It's necessary in a future where we want to read from secondaries (2).

B. Adding `regionid`, pretty self-explanatory, this is motivated by cross-region. In order to route queries to a specific region we need to know which region each node is in.

C. Adding some GUC like `read_from_secondaries` makes it easy for users to do (4).

D. Adding `connopts`, this is a feature Cloud requested and will make it easier for them to configure citus. It will let them do things like require ssl and pin certs on connections between the master and workers. It's not strictly necessary though, they also want a `pg_dist_user` which will allow the same things, just in a slightly more clunky way.

**Comment by marcocitus** [comment]
Apart from `connopts` these have been merged.
