### ISSUE TITLE
In CONTRIBUTING we state cla.citusdata.com will explain why we want a CLA, but it doesn't!

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#1433]
[In CONTRIBUTING.md](https://github.com/citusdata/citus/blob/cd60c8942139b29cab19fe39aaea083a1bc27ce5/CONTRIBUTING.md) we say:

> Before accepting any code contributions we ask that Citus contributors sign a Contributor License Agreement (CLA). For an explanation of why we ask this as well as instructions for how to proceed, see the Citus CLA.

But cla.citusdata.com doesn't have any explanation. And doesn't even show you the CLA! The only way to see the CLA is to click the link which sends you to Github, then authorize, then type more information, then check your email.

Surely this is causing some friction for contributors. Some things we could do:
- Include an explanation of why we ask contributors to sign the CLA in cla.citusdata.com
- Include a link to the CLA from cla.citusdata.com, so it can be reviewed without going through an auth flow

**Comment by lithp** [comment]
@lfittl Tagging you because I believe you were the one who setup our CLA box but feel free to reassign if you're not the right person to talk to.

**Comment by lfittl** [comment]
@lithp This will probably require some internal review on what makes sense - lets discuss by email instead. I'll close this for now.
