### ISSUE TITLE
Foreign keys lead to deadlocks while rebalancing

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#1437]
When rebalancing a table with foreign keys we'll frequently get into unprincipled deadlocks, i.e. deadlocks that aren't due to user logic, but due to our code.

Steps to reproduce:

schema:
```
DROP TABLE IF EXISTS test_table CASCADE;
CREATE TABLE test_table (test_id integer primary key, data text, data2 text);
SELECT create_distributed_table('test_table', 'test_id', 'hash');

DROP TABLE IF EXISTS test_table2 CASCADE;
CREATE TABLE test_table2 (test_id integer NOT NULL references test_table , data text, data2 text);
SELECT create_distributed_table('test_table2', 'test_id', 'hash');
postgres[32630][1]=# SELECT get_shard_id_for_distribution_column('test_table', 8);
┌──────────────────────────────────────┐
│ get_shard_id_for_distribution_column │
├──────────────────────────────────────┤
│                               102144 │
└──────────────────────────────────────┘
(1 row)

postgres[28742][1]=# SELECT * FROM pg_dist_shard WHERE shardid = 102144;
┌──────────────┬─────────┬──────────────┬───────────────┬───────────────┐
│ logicalrelid │ shardid │ shardstorage │ shardminvalue │ shardmaxvalue │
├──────────────┼─────────┼──────────────┼───────────────┼───────────────┤
│ test_table   │  102144 │ t            │ -2147483648   │ -2013265921   │
└──────────────┴─────────┴──────────────┴───────────────┴───────────────┘
(1 row)
```

To reproduce the issue easily I currently use gdb. In one session I set a breakpoint like:
```
(gdb) b LockAcquire if lockmode == RowExclusiveLock
Breakpoint 1 at 0x7ca30a: file /home/andres/src/postgresql-9.5/src/backend/storage/lmgr/lock.c, line 672.
```
and then run 
```
INSERT INTO test_table VALUES(8, 1, 2);
```
once that breakpoint hits, I let it acquire just that lock, by making the function return:
```
Breakpoint 1, LockAcquire (locktag=0x7ffee5ce7100, lockmode=3, sessionLock=0 '\000', dontWait=0 '\000')
    at /home/andres/src/postgresql-9.5/src/backend/storage/lmgr/lock.c:672
672             return LockAcquireExtended(locktag, lockmode, sessionLock, dontWait, true);
(gdb) fin
Run till exit from #0  LockAcquire (locktag=0x7ffee5ce7100, lockmode=3, sessionLock=0 '\000', dontWait=0 '\000')
    at /home/andres/src/postgresql-9.5/src/backend/storage/lmgr/lock.c:672
0x00000000007c88dc in LockRelationOid (relid=16652, lockmode=3) at /home/andres/src/postgresql-9.5/src/backend/storage/lmgr/lmgr.c:112
112             res = LockAcquire(&tag, lockmode, false, false);
Value returned is $1 = LOCKACQUIRE_OK
```

then in another session I start a rebalance:
```
postgres[28628][1]=# BEGIN ;
BEGIN
postgres[28628][1]*=# SELECT master_move_shard_placement(102144,'localhost',57638,'localhost',57637);
```
letting execution in the first session continue, triggers a deadlock:
```
ERROR:  40P01: deadlock detected
DETAIL:  Process 28927 waits for ShareLock on advisory lock [12385,0,102144,4]; blocked by process 28628.
Process 28628 waits for ShareRowExclusiveLock on relation 16652 of database 12385; blocked by process 28927.
HINT:  See server log for query details.
LOCATION:  DeadLockReport, deadlock.c:956
```

The problem here is that we're quite uncareful about which locks we acquire in which order.  There's several problems imo, but the one triggering the issue in this case is that `master_move_shard_placement()->CopyColocatedShardPlacement()->CopyShardForeignConstraintCommandList()->ForeignConstraintGetReferencedTableId()` does:
```
		Constraint *constraint = (Constraint *) command->def;
		if (constraint->contype == CONSTR_FOREIGN)
		{
			RangeVar *referencedTable = constraint->pktable;
			LOCKMODE lockmode = AlterTableGetLockLevel(foreignConstraintStmt->cmds);

			return RangeVarGetRelid(referencedTable, lockmode,
									foreignConstraintStmt->missing_ok);
		}
```

In other words, when building the DDL to recreate the fkeys on the new shards, we acquire a ShareRowExclusiveLock on the table.

This triggers a deadlock, because the INSERT first acquires a `RowExclusiveLock` on the table, and *then* acquires a shard metadata lock (via `LockShardDistributionMetadata()`) on the target shard,  and `master_move_shard_placement()` first acquires a metadata lock on the target shards, and then tries to get a `ShareRowExclusiveLock` the tables with fkeys from within `ForeignConstraintGetReferencedTableId`.   If those happen interspersed deadlocks ensue.

I think it's fairly confusing that a function named `ForeignConstraintGetReferencedTableId()` acquires a quite "heavy" lock, and it does so without any sort of documentation about the intent. Even if it were intended, it's currently only used in some `GetTableForeignConstraintCommands` callsites, without being consistent about afaict.

I think this kind of lock is actually not required while rebalancing/moving placements - we've blocked modifications to the relevant colocated shards, so there cannot be any fkey affecting commands.  Acquiring `ShareRowExclusiveLock` on entire relations doesn't allow any modifications, which surely isn't what we want during rebalancing.  I think we should just move the lock acquisition to the callers that appears to need it, and remove it from the current location.

Comments?

There's further issues here (like not locking the underlying table at all, not even an `AccessShare`), but it seems better to keep those to separate tickets.

**Comment by anarazel** [comment]
@saicitus @samay-sharma @sumedhpathak ^

**Comment by marcocitus** [comment]
Agreed, we shouldn't need an additional table lock in `ForeignConstraintGetReferencedTableId`, this should just be `NoLock`. The call to `RangeVarGetRelid` could also be avoided here, but that's a bigger change.

**Comment by anarazel** [comment]
This has since been fixed and backpatched.
