### ISSUE TITLE
Limit worker task count for analyze

### ISSUE THREAD

**Issue by krburkhart** [citusdata/citus#1444]
The 'analyze <tablename>' command can exceed the number of max_connections configured on worker nodes, even if the task-tracker executor type is configured.  If there are a large number of shards and max_connections is also large, it is possible for an analyze command to make a worker node unresponsive due to large load average.

I would like a way to configure the master (in task-tracker and in real-time mode) to limit the number of concurrent queries sent to any one worker. 

I was asked to post this issue in this citus-users thread: https://groups.google.com/forum/#!topic/citus-users/IYdui9zyOi0

-Kelly

**Comment by krburkhart** [comment]
On reflection I think this issue should be in two parts:

1.  Create setting to limit max number of concurrent commands sent to any worker, regardless of task_executor_type.
2.  Make analyze respect that.

I believe that even when real-time executor is selected, it should not be possible for the master to bury worker nodes.

**Comment by marcocitus** [comment]
This would be addressed by the proposal in #1273.
