### ISSUE TITLE
Handle clauses without columns: like potentially now() > constDate, or where 3 < 5. We can't push them down, but could evaluate them at the top-level worker.

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#145]
Handle clauses without columns: like potentially now() > constDate, or where 3 < 5. We can't push them down, but could evaluate them at the top-level worker.

**Comment by ozgune** [comment]
@marcocitus / @onderkalaci -- Is this issue related to #751?

Also, what do you think of adding a small regression test that captures @onderkalaci's test scenario in #751?

**Comment by marcocitus** [comment]
Not quite sure if I understand this issue (why we can't push them down), but it seems like we can in we do, so we can close this. I think adding regression tests would be a good.

**Comment by marcocitus** [comment]
This seems fixed and there are various regression tests for it.
