### ISSUE TITLE
Support declarative partitioning on distributed tables

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#1459]
Postgres 10 will come with declarative partitioning [support](https://www.postgresql.org/docs/10/static/ddl-partitioning.html#ddl-partitioning-declarative).

To achieve #573, one of the alternatives is to support declarative partitioning on distributed tables. (See the other alternative [here](https://github.com/citusdata/citus/issues/573?_pjax=%23js-repo-pjax-container#issuecomment-303075836).) Note that this will build the infrastructure to fulfill the requirements of #573.

We've had some internal discussions and design notes on this [document](https://docs.google.com/document/d/11TsIbS60oUiPKKt6mj3JWxwyjPW_S9iF_Rj1778LhRc/edit). Here, I'll move the necessary parts:

- [x] Add utility functions that the other parts of the implementation will benefit
- [x]  Creating partitioned distributed tables:
    - [x]  Creating the partitioning hierarchy before distributing the relations and then distributing the relations
   - [x] Creating partitions of already distributed relations
   - [x] Creating regular PostgreSQL tables and ATTACHING to a distributed table
   - [x] Creating distributed tables and ATTACHING to another distributed table
   - [x] DETACHING partitions from a distributed table
   - [x] Erroring out on unsupported operations
- [x] Metadata: Make sure that each partition is a distributed table and the partitioning hierarchy is formed on the shards as well

- [x] Locking on the coordinator: Given that both partitions and parent table is accessible by the users, it makes sense to elaborate lock acquisitions on the master to make sure that we’re good. See below for the discussion:

    - [x]  Shard metadata locks: Make sure that parent and children are co-located. Then, co-location logic would handle the rest for us.

    - [x]  Shard resource locks: Whenever a child's lock is acquired, make sure that the parent's corresponding shard resource lock is also acquired.

    - [x]  Relation Lock on query execution: This is tricky. Whenever a modification happens on a parent table, Postgres acquires relation lock (i.e., AccessShareLock) on both the parent and all children. However, that is happening during the standard_executor(), which Citus skips. The relevant locks are already held on the shards by Postgres. However, the question is that do we actually need to acquire the relation locks on the coordinator?

    - [x]  Relation Locks on DDLs: Since Citus first executes the DDLs on the coordinator, all the necessary locks are acquired. Thus, we don't need to implement anything.

- [x] Shard rebalancer considers the partitioning hierarchy. 
- [x] Tenant isolation considers the partitioning hierarchy.
- [x] MX sends the necessary metadata
- [ ] Distributed table size
- [x] Adding regression tests: i.e., 'Querying tables', `DDL/Constraint`s, `multi-column partitioning`, `concurrency`, `transactions`, `COPY`, different executors, `partition key == distribution key` etc
-----

Note that we are not planning to support multi-level partitioning in this release.

**Comment by marcocitus** [comment]
> Creating the partitioning hierarchy before distributing the relations and then distributing the relations

Does this include data loading?

**Comment by onderkalaci** [comment]
> Does this include data loading?

Yes, that's the plan. We'll likely to skip data loading from the parent table to resemble the solution to shard rebalancer / tenant isolation solutions. Otherwise, we'd end-up with loading the data twice.

**Comment by marcocitus** [comment]
> Yes, that's the plan. We'll likely to skip data loading from the parent table to resemble the solution to shard rebalancer / tenant isolation solutions. Otherwise, we'd end-up with loading the data twice.

This might require some changes since the current implementation reads straight from the heap. You'd probably want to use a Portal and `standard_planner`.

**Comment by onderkalaci** [comment]
> This might require some changes since the current implementation reads straight from the heap, and does not consider partitions. You'd probably want to use a Portal and standard_planner.

Hmm, I see it now. What about if we change the `CopyLocalDataIntoShards()` function to
`CopyLocalDataIntoShards(Oid destinationDistributedRelationId, List *sourceLocalTableList)
` and read from the list of source tables? Such as this [commit](https://github.com/citusdata/citus/pull/1467/commits/e36e3efa8dda588d50ee5fad5f589b92f41563c6)?  Should I go ahead and make it a proper commit  @marcocitus ?

**Comment by onderkalaci** [comment]
> Hmm, I see it now. What about if we change the CopyLocalDataIntoShards() function to
CopyLocalDataIntoShards(Oid destinationDistributedRelationId, List *sourceLocalTableList) and read from the list of source tables? Such as this commit? Should I go ahead and make it a proper commit @marcocitus ?

We should probably check that tuple descriptors are the same

**Comment by marcocitus** [comment]
>  What about if we change the CopyLocalDataIntoShards() function to CopyLocalDataIntoShards(Oid destinationDistributedRelationId, List *sourceLocalTableList) and read from the list of source tables? 

Well, going through standard_planner would be nicer since that would also support cstore_fdw, but it could work.

**Comment by ozgune** [comment]
@onderkalaci -- We seem to have three remaining items in this issue. Could you estimate how long it would take to implement these three items?

**Comment by jilongs** [comment]
Hi, is there an update on this? I'm seeing 
```
distributing partitioned tables with replication factor greater than 1 is not supported
```
We want to use citus with distributing partitioned tables in productin, so use replication factor as 1 is not ideal.

Thanks,

Jacky

**Comment by ozgune** [comment]
Hi @jilongs -- Thank you for participating in this issue. When partitioning is involved, we currently recommend our customers to use streaming replication. Is that an option for you?

Are you currently using Citus on production?

**Comment by marcocitus** [comment]
Seems sufficiently well-addressed.
