### ISSUE TITLE
create_distributed_table does not delete local data

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#1479]
`create_distributed_table()` copies local data to the newly created distributed table but does not delete the local data on the coordinator note.

This came up in a Citus user discussion.

**Comment by marcocitus** [comment]
This is intentional to allow you to revert.

To remove the old data, you can do:

```
BEGIN;
SET LOCAL citus.enable_ddl_propagation TO off;
TRUNCATE distributed_table;
COMMIT;
```

**Comment by metdos** [comment]
Thanks @marcocitus, I'm closing this issue.
