### ISSUE TITLE
auto-HA: Block writes to nodes while they're failing over

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#1480]
In order to confidently promote secondaries there needs to be a way of knowing that the primary is definitely receiving no more writes.

The API for this hasn't been fully decided yet, it might look something like:

    sync_node_states([list-of-node-records]);

When this function returns we should know for sure that no more writes are being sent, and simply updating pg_dist_node isn't enough to make that guarantee because when the function returns there could be concurrent processes which are still using the outdated pg_dist_node table. In order to guarantee exclusion all threads which open a connection to a remote node should, before opening the connection:

1. Take out a ShareLock on an advisory lock keyed on the nodeid (and not release it until it will not open any more connections)
2. AcceptInvalidationMessages
3. Check that the noderole is still "primary"

`sync_node_states`, on the other hand, should take out an ExclusiveLock on the advisory lock for the relevant nodes before updating them.

Processes which write to remote nodes should be careful to release the lock after they're opened all their connections and not after they've closed the connections. `sync_node_states` is called when the remote node has failed due to things like timeouts. It would be bad if `sync_node_states` had to wait for every currently open connection to timeout before finally applying the change.

**Comment by lithp** [comment]
There are three things we want to do:
- Ensure that any existing sessions do not write on their next command
- Ensure that any new sessions do not write to the node which is no longer `primary`
- Ensure that any writes which are currently in progress finish before `sync_node_states` returns

**Comment by marcocitus** [comment]
This behaviour is implemented by `master_udpate_node`
