### ISSUE TITLE
Wrong column names when using row_to_json on distributed table

### ISSUE THREAD

**Issue by mrijkeboer** [citusdata/citus#1485]
When I use `row_to_json` on a distributed table the column names are replaced with `f1`, `f2`, ... Below and example:

```sql
-- Normal table
CREATE TABLE example_normal(
	key text PRIMARY KEY,
	val text NOT NULL
);

INSERT INTO example_normal (key, val) VALUES ('key1', 'val1');
INSERT INTO example_normal (key, val) VALUES ('key2', 'val2');

-- Distributed table
CREATE TABLE example_dist(
	key text PRIMARY KEY,
	val text NOT NULL
);

SELECT create_distributed_table('example_dist', 'key');

INSERT INTO example_dist (key, val) VALUES ('key1', 'val1');
INSERT INTO example_dist (key, val) VALUES ('key2', 'val2');
```

When I query the normal table with the following query:

```sql
SELECT row_to_json(tmp)
FROM (SELECT * FROM example_normal) tmp;
```

I get the following correct output:

```
{"key":"key1","val":"val1"}
{"key":"key2","val":"val2"}
```

However, when I query the distributed table with the following query:

```sql
SELECT row_to_json(tmp)
FROM (SELECT * FROM example_dist) tmp;
```

I get the following output with all the column names replaced by `f1`,` f2`, ...:

```
{"f1":"key1","f2":"val1"}
{"f1":"key2","f2":"val2"}
```

How can I query a distributed table and get the correct column names?

System info:
- PostgreSQL: 9.6.3
- Citus: 6.2.2

**Comment by anarazel** [comment]
> I get the following output with all the column names replaced by f1,f2, ...:

> ```
> {"f1":"key1","f2":"val1"}
> {"f1":"key2","f2":"val2"}
> ```

That's indeed not great.


> How can I query a distributed table and get the correct column names?

I'm not sure if that actually solves your problem, I assume you've simplified it, but for your example you have you should be able to get away with:
```
SELECT *
FROM (SELECT row_to_json(d) FROM example_dist d) tmp;
┌─────────────────────────────┐
│         row_to_json         │
├─────────────────────────────┤
│ {"key":"key1","val":"val1"} │
│ {"key":"key2","val":"val2"} │
└─────────────────────────────┘
(2 rows)
```

Which'll also have the advantage that the conversion will be done on the worker(s), rather than the coordinator.

**Comment by mrijkeboer** [comment]
@anarazel: I indeed simplified it. I need to be able to select some of the columns and with your solution I get all columns of the table.

**Comment by mrijkeboer** [comment]
The strange thing is that if I add an `ORDER BY` clause I _do_ get column names, i.e.:

```SQL
SELECT row_to_json(tmp)
FROM (SELECT * FROM example_dist ORDER BY key) tmp;
```

Returns the correct column names:

```
{"key":"key1","val":"val1"}
{"key":"key2","val":"val2"}
```

So this seems like a bug.

**Comment by marcocitus** [comment]
Seems to no longer be an issue
