### ISSUE TITLE
Shards with aliases no longer work for broadcast joins. We generate fetch tasks in cases where we didn't use to and then later prune them

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#151]
Shard aliases are now broken - we generate fetch tasks in cases where we didn't use to and then later prune them. As a result many queries (eg. select count(*) from dist_table) fail when they should work as ShardFetchQueryString is called and signals an error even though the task would have been later pruned.

**Comment by robin900** [comment]
#739 removed shardalias usage entirely; issue can be closed.
