### ISSUE TITLE
Check for proper collation support in CitusDB. For eg. currently, the collation information is not pushed down to the worker nodes when supplied inside an aggregate.

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#152]
Check for proper collation support in CitusDB. For eg. currently, the collation information is not pushed down to the worker nodes when supplied inside an aggregate.

**Comment by marcocitus** [comment]
Citus has reasonably comprehensive collation support. The specific example is described in more detail in #4010.
