### ISSUE TITLE
multi_view regression test may fail on OS X

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1520]
I'm running our regression tests on OS X 10.10.5, and I'm getting a repeatable regression test failure in the multi_view test.

I'm including the regression test diff below. PostgreSQL seems to be choosing a different plan on worker nodes than the one we anticipate in the test plan.

@mtuncer -- What's our goal with this regression test plan? If we disable certain planner options (such as `enable_bitmapscan` or `enable_indexscan`), does that help us get a more reproducible output?

<pre>
--- /workplace/mainline/citus/src/test/regress/expected/multi_view.out	2017-07-26 14:53:06.000000000 -0700
+++ /workplace/mainline/citus/src/test/regress/results/multi_view.out	2017-07-26 15:13:04.000000000 -0700
@@ -793,81 +793,87 @@
       61 | Tue Jan 21 05:25:27.452065 2014 |        392 |     472 |     925 |        
       19 | Tue Jan 21 05:23:09.26298 2014  |        202 |     888 |     640 |        
       65 | Tue Jan 21 05:22:56.725329 2014 |        519 |     457 |     259 |        
       27 | Tue Jan 21 05:19:14.38026 2014  |         19 |      19 |     205 |        
       11 | Tue Jan 21 05:15:14.879531 2014 |        459 |     545 |      80 |        
 (10 rows)
 
 RESET citus.subquery_pushdown;
 -- explain tests
 EXPLAIN (COSTS FALSE) SELECT user_id FROM recent_selected_users GROUP BY 1 ORDER BY 1;
-                                                                       QUERY PLAN                                                                        
----------------------------------------------------------------------------------------------------------------------------------------------------------
+                                                                    QUERY PLAN                                                                     
+---------------------------------------------------------------------------------------------------------------------------------------------------
  Sort
    Sort Key: remote_scan.user_id
    ->  HashAggregate
          Group Key: remote_scan.user_id
          ->  Custom Scan (Citus Real-Time)
                Task Count: 4
                Tasks Shown: One of 4
                ->  Task
                      Node: host=localhost port=57637 dbname=regression
-                     ->  HashAggregate
+                     ->  Group
                            Group Key: users_table.user_id
-                           ->  Hash Join
-                                 Hash Cond: (users_table.user_id = ru.user_id)
-                                 ->  Bitmap Heap Scan on users_table_1400000 users_table
-                                       Recheck Cond: ((value_1 >= 120) AND (value_1 < 150))
-                                       ->  Bitmap Index Scan on is_index3_1400000
-                                             Index Cond: ((value_1 >= 120) AND (value_1 < 150))
-                                 ->  Hash
-                                       ->  Subquery Scan on ru
-                                             ->  Sort
-                                                   Sort Key: (max(users_table_1."time")) DESC
-                                                   ->  HashAggregate
-                                                         Group Key: users_table_1.user_id
-                                                         Filter: (max(users_table_1."time") > '2014-01-21 05:45:49.978738'::timestamp without time zone)
-                                                         ->  Seq Scan on users_table_1400000 users_table_1
-(25 rows)
+                           ->  Sort
+                                 Sort Key: users_table.user_id
+                                 ->  Hash Join
+                                       Hash Cond: (users_table_1.user_id = users_table.user_id)
+                                       ->  Sort
+                                             Sort Key: (max(users_table_1."time")) DESC
+                                             ->  HashAggregate
+                                                   Group Key: users_table_1.user_id
+                                                   Filter: (max(users_table_1."time") > '2014-01-21 05:45:49.978738'::timestamp without time zone)
+                                                   ->  Seq Scan on users_table_1400000 users_table_1
+                                       ->  Hash
+                                             ->  Bitmap Heap Scan on users_table_1400000 users_table
+                                                   Recheck Cond: ((value_1 >= 120) AND (value_1 < 150))
+                                                   ->  Bitmap Index Scan on is_index3_1400000
+                                                         Index Cond: ((value_1 >= 120) AND (value_1 < 150))
+(26 rows)
 
 EXPLAIN (COSTS FALSE) SELECT *
 	FROM (
 		(SELECT user_id FROM recent_users) 
 		UNION
 		(SELECT user_id FROM selected_users) ) u
 	WHERE user_id < 15 AND user_id > 10
 	ORDER BY user_id;
-                                                                   QUERY PLAN                                                                    
--------------------------------------------------------------------------------------------------------------------------------------------------
+                                                                QUERY PLAN                                                                 
+-------------------------------------------------------------------------------------------------------------------------------------------
  Sort
    Sort Key: remote_scan.user_id
    ->  Custom Scan (Citus Real-Time)
          Task Count: 4
          Tasks Shown: One of 4
          ->  Task
                Node: host=localhost port=57637 dbname=regression
-               ->  Unique
-                     ->  Sort
-                           Sort Key: recent_users.user_id
-                           ->  Append
-                                 ->  Subquery Scan on recent_users
-                                       ->  Sort
-                                             Sort Key: (max(users_table."time")) DESC
-                                             ->  GroupAggregate
-                                                   Group Key: users_table.user_id
-                                                   Filter: (max(users_table."time") > '2014-01-21 05:45:49.978738'::timestamp without time zone)
-                                                   ->  Index Scan using is_index1_1400000 on users_table_1400000 users_table
+               ->  HashAggregate
+                     Group Key: recent_users.user_id
+                     ->  Append
+                           ->  Subquery Scan on recent_users
+                                 ->  Sort
+                                       Sort Key: (max(users_table."time")) DESC
+                                       ->  HashAggregate
+                                             Group Key: users_table.user_id
+                                             Filter: (max(users_table."time") > '2014-01-21 05:45:49.978738'::timestamp without time zone)
+                                             ->  Bitmap Heap Scan on users_table_1400000 users_table
+                                                   Recheck Cond: ((user_id < 15) AND (user_id > 10))
+                                                   ->  Bitmap Index Scan on is_index1_1400000
                                                          Index Cond: ((user_id < 15) AND (user_id > 10))
-                                 ->  Index Scan using is_index1_1400000 on users_table_1400000 users_table_1
-                                       Index Cond: ((user_id < 15) AND (user_id > 10))
-                                       Filter: ((value_1 >= 120) AND (value_1 < 150))
-(22 rows)
+                           ->  Bitmap Heap Scan on users_table_1400000 users_table_1
+                                 Recheck Cond: ((value_1 >= 120) AND (value_1 < 150) AND (user_id < 15) AND (user_id > 10))
+                                 ->  BitmapAnd
+                                       ->  Bitmap Index Scan on is_index3_1400000
+                                             Index Cond: ((value_1 >= 120) AND (value_1 < 150))
+                                       ->  Bitmap Index Scan on is_index1_1400000
+                                             Index Cond: ((user_id < 15) AND (user_id > 10))
+(27 rows)
 
 EXPLAIN (COSTS FALSE) SELECT et.* FROM recent_10_users JOIN events_table et USING(user_id) ORDER BY et.time DESC LIMIT 10;
 ERROR:  cannot push down this subquery
 DETAIL:  Limit in subquery is currently unsupported
 SET citus.subquery_pushdown to ON;
 EXPLAIN (COSTS FALSE) SELECT et.* FROM recent_10_users JOIN events_table et USING(user_id) ORDER BY et.time DESC LIMIT 10;
                                                      QUERY PLAN                                                      
 ---------------------------------------------------------------------------------------------------------------------
  Limit
    ->  Sort

======================================================================
</pre>

**Comment by ozgune** [comment]
I'm noting #1395 as a semi-related issue to this one.

**Comment by mtuncer** [comment]
I too see it from time to time. Purpose of this test is to make sure queries involving views could be explained. Explanation details are not very relevant.

forcing certain type of scan could be an option here.

**Comment by mtuncer** [comment]
@ozgune can you check if [view_test](https://github.com/citusdata/citus/tree/view_test) branch fixes your issue ?

**Comment by onderkalaci** [comment]
Having `VACUUM ANALYZE` on the table just before the tests helps most of the time such as [here](https://github.com/citusdata/citus/blob/45957e568896cf2f963b13e4fc82e2914efc85cf/src/test/regress/sql/multi_mx_explain.sql#L131)
