### ISSUE TITLE
As we are partitioning data, we may also want to "check for interrupts" through the standard PostgreSQL macros. This gives user the ability to cancel their long queries.

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#154]
As we are partitioning data, we may also want to "check for interrupts" through the standard PostgreSQL macros. This gives user the ability to cancel their long queries.

**Comment by anarazel** [comment]
This is largely done due to the replacement of \stage with COPY. There's some remaining issues in other parts of the code, but separate issues track those #1100 #1121).
