### ISSUE TITLE
MetadataCreateCommands calls ActivePrimaryNodeList()

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#1541]
This means when syncing metadata to a node we only sync the primary nodes in the current cluster to it. This could cause issues in a future where we want MX nodes to be able to read from secondaries in our cluster.

**Comment by marcocitus** [comment]
how would we sync secondaries? don't they just get their metadata from primaries?

**Comment by lithp** [comment]
It makes sense that we're not trying to send commands to the secondary nodes, but we're also not sending commands which include the secondary nodes to the other primary nodes.
