### ISSUE TITLE
Distributed deadlock detection crashes when upgrading from old version

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1557]
When upgrading from an older version of Citus to 7.0, then the first user-issued command will activate the maintenance daemon, which as part of distributed deadlock detection calls `ReadWorkerNodes`, which then tries to read a non-existent column from `pg_dist_node`, which causes a segmentation fault.

The maintenance daemon should not run if the catalog is behind.

**Comment by onderkalaci** [comment]
Is that to add `CheckCitusVersion(ERROR);` to the deamon?

**Comment by marcocitus** [comment]
We don't really want to throw errors in the background daemon. We could create a different version of `CheckCitusVersion` that only returns true or false and if the version is behind deadlock detection is skipped.

**Comment by onderkalaci** [comment]
Luckily that function already does that. I'll test & open PR today.

**Comment by marcocitus** [comment]
Yeh, but it might also throw an error.
