### ISSUE TITLE
Replace jobId sequence with something non-persistent

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#156]
We use a sequence on the master to generate unique jobIds.

There exist several reasons for trying to get away from using a sequence for Job IDs:
- On standbys we can't use a sequence, as they're read-only
- This is one of the blockers preventing us from supporting pg_dump (which breaks pg_dump/COPY cf. #348)
- For MX jobIds should probably be meaningful across the whole cluster (@marcoslot details?)
- The need for reproducible job ids requires tests to reset the job sequence. Which in turn requires only one test to run concurrently

**Comment by anarazel** [comment]
I think a good identifier here would be something like (nodeId, backendId, localJobId) with localJobId just being a per-backend counter that increases.

**Comment by lfittl** [comment]
Just adding a note that we can close this once #1208 is merged.
