### ISSUE TITLE
Enable DML transactions from secondary coordinator

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1583]
For the purpose of availability, it would be useful if secondary coordinators (hot standby) could perform DML operations, such that when the primary coordinator fails, clients can continue to write to the distributed table via the secondary.

Currently, most write operations error out in the postgres executor, e.g.:
```
INSERT INTO test VALUES (1,2);
ERROR:  cannot execute INSERT in a read-only transaction
```

To enable write operations, we may need to bring back the executor hooks to avoid the condition in `ExecutorStart` which triggers this error.

Distribute deadlock detection currently uses group ID to identify which node started a distributed transaction. The database on the secondary is identical, so the deadlock detector would not be able to distinguish which distributed transactions were started by the primary and which were started by the secondaries. We should instead use a unique node ID that is assigned to a GUC using `ALTER SYSTEM`. 

To support 2PC recovery, the secondary would have to write transaction recovery records to one of the workers instead of its own `pg_dist_transaction` table, which is not writable.

Replication factor >1 would not be supported since the secondary cannot update `shardstate` in `pg_dist_placement`.

**Comment by lfittl** [comment]
Just adding a note that this could also be seen as a way to increase connection limits - right now, unless using MX, you are bound by the connection limit of the single coordinator node (and its pgbouncer if on Cloud).

With this, assuming no coordinator tables, you could have multiple coordinators running for both queries and DML to get a higher overall connection limit for the typical OLTP type application. You'd still be bound by the individual worker node connection limits of course, but there you can scale out more easily.
