### ISSUE TITLE
If we somehow create our resource identifiers (input data identifiers) based on the operation we are executing and the base data, then we can greatly benefit from performance improvements (future improvement)

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#159]
If we somehow create our resource identifiers (input data identifiers) based on the operation we are executing and the base data, then we can greatly benefit from performance improvements (future improvement)

**Comment by marcocitus** [comment]
I have no idea what this means. Feel free to reopen if you do. :)
