### ISSUE TITLE
Select query on empty append distributed tables with where dist_col < or > crashes

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus#1593]
My Setup;
* PostgreSQL REL_10_STABLE
* Citus Community 7.0-14

When I just create a basic table as;
```
CREATE TABLE test(id INT, uname TEXT);
```

and append distribute it on a column which I can use basic comparison operators (<, <=, >=, >). For example
```
SELECT create_distributed_table('test', 'id', 'append');
```
and run a select query which has a where clause at the end of the distribution column such as;
```
SELECT * FROM test WHERE id < 6;
```
Postgres server just crashes.

When I debug it I see that the exception is thrown on the line 1059 of the class shard_pruning.c
```
Assert(shardCount != 0);
```
Here the shardCount is 0 as expected since there is no data and the query hits no shard.

**Comment by metdos** [comment]
This bug also exists on 6.2.
