### ISSUE TITLE
\copy shouldn't succeed in READ ONLY transaction.

### ISSUE THREAD

**Issue by pykello** [citusdata/citus#1594]
The following query succeeded for a distributed table:

```sql
BEGIN READ ONLY;
\copy companies from program 'curl https://examples.citusdata.com/tutorial/companies.csv' with csv;
COMMIT;
```
But it shouldn’t. For regular postgres tables, it results in the following error:
```ERROR:  cannot execute COPY FROM in a read-only transaction```

**Comment by anarazel** [comment]
I'm hesitant addressing this. We do want to be able to issue writes from standbys where transactions are readonly.

**Comment by pykello** [comment]
@anarazel to add more context, INSERTs fail in READ ONLY transactions:

```sql
BEGIN READ ONLY;
INSERT INTO companies VALUES (-1, 'A', '', LOCALTIMESTAMP, LOCALTIMESTAMP);
COMMIT;
```

```ERROR:  cannot execute INSERT in a read-only transaction```

Isn't inconsistency between INSERT and \copy confusing?

**Comment by anarazel** [comment]
Yea, but look at #1583 - we're more going in the *opposite* direction.

**Comment by marcocitus** [comment]
We may want to introduce a GUC to control this behaviour. Some charting applications rely on `READ ONLY` to give users read-only SQL access.

**Comment by marcocitus** [comment]
This seems to fail as expected now.
