### ISSUE TITLE
drop table with sequence locked

### ISSUE THREAD

**Issue by tqyq** [citusdata/citus#1601]
steps:

1. create table ts (id serial);
2. drop table ts cascade;

the client locked.

version:

citus 6.1, 6.2

**Comment by mtuncer** [comment]
Hey @tqyq 

Thanks for the report. These steps does not include a distributed table.  It is creation and drop of a regular table. Citus should not be involved on those operations.

Can you confirm that they are all needed to reproduce the issue ?

thanks

**Comment by marcocitus** [comment]
May be a duplicate of https://github.com/citusdata/citus/issues/1269

**Comment by ozgune** [comment]
@tqyq - I ran these two steps on Citus 7.0-15 and couldn't reproduce the issue.

Were these the only two commands you ran? Could you provide us more info?

**Comment by marcocitus** [comment]
This is an issue when the coordinator is added as a node.

**Comment by ozgune** [comment]
Got it. Should we then close this issue as a duplicate of #1269?

**Comment by jasonmp85** [comment]
@ozgune I believe so. Closing as we couldn't reproduce, don't have further info, and believe this is a duplicate.
