### ISSUE TITLE
Multi-row INSERT statements have poor performance

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1604]
Citus 7.0 enables multi-row INSERT statements (#455). Our current implementation (#1517) relies on the multi-shard update executor.

The multi-shard update executor isn't designed for performance. In particular, if we have a multi-row INSERT statement that touches multiple shards, then we're going to open a new connection to each shard. For example, a multi-row INSERT statement that inserts 100 values and touches 32 shards, will open a total of 32 connections. This behavior results in poor performance for multi-row INSERT statements.

We should change our multi-row INSERT logic to re-use cached connections. I'm including an email thread from @marcocitus below.

---

Multi-row INSERTs currently use the same infrastructure as DDL and DML commands. For INSERTs that span multiple shards, that means we open a new connection for every shard placement and use aggressive locks to prevent deadlocks and connection explosions.

I performed 100-row INSERTs using pgbench over a varying number of shards by tweaking partition column values.

1 shard: 1900 tps = 190,000 rows/sec (17ms avg)
2 shards: 246 tps = 24,600 rows/sec  (131ms avg)
4 shards: 175 tps = 17,500 rows/sec (182ms avg)
8 shards: 132 tps = 13,200 rows/sec (240ms avg)
16 shards: 92 tps = 9,200 rows/sec (351ms avg)
32 shards: 58 tps = 5,800 rows/sec  (555ms avg)

Measured using 32 clients/threads over a 30 second period on a cluster with 2+1 r3.large nodes.

While the multi-shard locks are no longer necessary for avoiding deadlocks now that we have deadlock detection, removing the locks does not substantially improve throughput and causes connection errors due to the number of connections. The bottleneck is the number of connections.

To address throughput at high shard counts, we'll need to write a new executor that can reuse connections for multiple tasks within the same statement, e.g.: https://github.com/citusdata/citus/issues/1273

---

Hey @marcocitus, @jasonmp85,

These performance numbers are quite informative -- thanks! I had a question.

When you're doing an INSERT into Citus, we can re-use open connections and send INSERTs to shards that way. When we receive a multi-row INSERT, could we leverage the same infrastructure?

That is, can we take a multi-row INSERT and turn that into multiple single-row INSERT statements?

---

Yep, we could write code that does that. I'd expect it to perform better in most cases.

**Comment by marcocitus** [comment]
It appears sequential execution (see #1608) gives substantially better throughput and latency, and is only a minimal code change:

1 shard: 1698 tps = 169,800 rows/sec (20ms avg)
2 shards: 1455 tps = 145,500 rows/sec (22ms avg)
4 shards: 1148 tps = 114,800 rows/sec (28ms avg)
8 shards: 784 tps = 78,400 rows/sec (41ms avg)
16 shards: 482 tps = 48,200 rows/sec (66ms avg)
32 shards: 271 tps = 27,100 rows/sec (119ms avg)

**Comment by anarazel** [comment]
@marcocitus Hm. So I think there's two aspects affecting performance here. Wonder if that's just my intuition, or whether you think that's right:

1) The sequential connection establishment allows to use cached connections. Based on a quick look we are allowed to use a pre-existing cached connection in the multi-shard case, but we won't establish one. Is that right? If so, it might be worthwhile to benchmark after "warming" each connection to establish one connection.
2) `OpenTransactionsForAllTasks()` uses `FinishConnectionListEstablishment()` - which is implemented in a terminally stupid manner - especially when openssl is in use it'll basically block on each connection in turn.   I don't immediately see how we could reuse fca986f214a2ae58c6536cd8477e855cd6e6590d infrastructure for this unfortunately, but an open coded variant, or an adapted `WaitForOneConnection()` seems like it should easily do the trick.

**Comment by marcocitus** [comment]
> The sequential connection establishment allows to use cached connections. Based on a quick look we are allowed to use a pre-existing cached connection in the multi-shard case, but we won't establish one. Is that right? 

Yes.

> If so, it might be worthwhile to benchmark after "warming" each connection to establish one connection.

Seems unnecessary, the connection is cached after the first insert.

> OpenTransactionsForAllTasks() uses FinishConnectionListEstablishment() - which is implemented in a terminally stupid manner - especially when openssl is in use it'll basically block on each connection in turn. 

As far as I'm aware there is no SSL between postgres and pgbouncer. I think pgbouncer is probably a bigger bottleneck.

**Comment by anarazel** [comment]
On 2017-08-22 15:20:46 +0000, Marco Slot wrote:
> > The sequential connection establishment allows to use cached connections. Based on a quick look we are allowed to use a pre-existing cached connection in the multi-shard case, but we won't establish one. Is that right? 
> 
> Yes.
> 
> > If so, it might be worthwhile to benchmark after "warming" each connection to establish one connection.
> 
> Seems unnecessary, the connection is cached after the first insert.

I don't think it its, with the current multi-row setup?
ExecuteModifyTask() executes OpenTransactionsForAllTasks() with
connectionFlags FOR_DML (or DDL), which then adds
CONNECTION_PER_PLACEMENT.  I've not yet had any coffee *and* I'm
jetlagged, so I'm not going to bet anything on this, but afaicts that'll
mean all connections get closed at EOX.


> > OpenTransactionsForAllTasks() uses FinishConnectionListEstablishment() - which is implemented in a terminally stupid manner - especially when openssl is in use it'll basically block on each connection in turn. 
> 
> As far as I'm aware there is no SSL between postgres and pgbouncer. I think pgbouncer is probably a bigger bottleneck.

Well, pgbouncer outgoing will have SSL. And given the high number of
connections here it'll probably constantly reestablish at least some of
them. So it might still help, given it IIRC won't start establishing the
backend connection until auth has succeeded.

Greetings,

Andres Freund

**Comment by marcocitus** [comment]
> I don't think it its, with the current multi-row setup?

The results for sequential execution shown above are based on #1608.

>  And given the high number of connections here it'll probably constantly reestablish at least some of them. So it might still help, given it IIRC won't start establishing the backend connection until auth has succeeded.

Not sure what you mean. What would help?

**Comment by anarazel** [comment]
> >I don't think it its, with the current multi-row setup?
>  The results for sequential execution shown above are based on #1608.

Sure, but I was talking about the parallel execution case - and there's no caching going on there IIUC. Which makes the comparison not particularly meaningful, no?

**Comment by marcocitus** [comment]
> Which makes the comparison not particularly meaningful, no?

I don't see why not. Caching one out of 16 connections per worker doesn't seem particularly meaningful and why would a connection be cached in practice? The client might just be doing multi-row inserts.

**Comment by anarazel** [comment]
> I don't see why not. Caching one out of 16 connections per worker doesn't seem particularly meaningful and why would that connection be cached in practice? The client might just be doing multi-row inserts.

Well, that depends on how the rows are distributed. I'd assume that in a lot of cases it'll not be entirely random, but that there'll be some locality and/or limit to the number of shards touched. In which case caching / not caching will be a major performance factor.

**Comment by anarazel** [comment]
FWIW, I think it's ok to go for sequential for now (in fact I'd argued for that during the 7.0 release planning meeting, some people disagreed on performance grounds...), I just don't think the practical performance difference is necessarily as large as presented here.

**Comment by marcocitus** [comment]
> I just don't think the practical performance difference is necessarily as large as presented here.

I think the performance benefit is actually going to be a lot bigger in practice if there is a combination of real-time queries an multi-row inserts.

**Comment by marcocitus** [comment]
We've merged the sequential execution changes. There is more we can do to improve multi-row INSERT performance (parallelise across workers, batch statements going to the same worker), but closing this issue.
