### ISSUE TITLE
pg_dist_transaction records are not removed automatically

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1614]
When we perform a 2PC we right recovery records for each prepared transaction to `pg_dist_transaction`. The presence of a recovery record indicates that the coordinator committed in case of a failure to fully commit/abort the 2PC.

The recovery records are kept even if the transaction successfully completed, because we can no longer modify the `pg_dist_transaction` table after commit/abort. They are removed when the user runs `SELECT recover_prepared_transactions()`, which also rolls any pending prepared transactions forward based on whether or not there is a corresponding recovery record. 

Recovery records were introduced when 2PCs were rare (MX metadata sync, DDL) and a 2PC failure would be exceptional, but there are now many commands that can use 2PC.

In all cases:
- Write to reference table
- MX metadata sync

If `citus.multi_shard_commit_protocol = '2pc'`:
- `master_modify_multiple_shards`
- `INSERT...SELECT`
- DDL  (incl. DROP TABLE, TRUNCATE)
- create_distributed_table
- multi-row INSERT
- multi-statement transactions across multiple nodes

Especially the last 2 can occur in high volumes, and for each transaction one or more transaction recovery records are written to `pg_dist_transaction`, which can become very large as a result. Moreover, actual failures could occur that need to be resolved by running `recover_prepared_transactions`. Since this is cumbersome, we've not yet enabled 2PC by default.

To avoid requiring the user to periodically run `SELECT recover_prepared_transactions()`, we should periodically call `recover_prepared_transactions` from the maintenance daemon. That way, we can enable 2PC by default.

**Comment by anarazel** [comment]
Wonder if we should add a hacky version of `heap_transactionless_delete()` like there's `heap_inplace_update()`.  In theory that should be doable with existing WAL records - but it'd be something on the more complicated side, so I'm not super comfortable with the idea.
