### ISSUE TITLE
master_drop_all_shards should error out for reference tables

### ISSUE THREAD

**Issue by byucesoy** [citusdata/citus#1624]
We should error out if master_drop_all_shards is used with reference tables. Currently, we drop reference table's shards which puts us in a weird situation.

Example test case to reproduce the issue;
```sql
CREATE TABLE t(c int);
SELECT create_reference_table('t');
SELECT master_drop_all_shards('t', 'public', 't');
```

Above command succeeds. Then we end up in a weird situation;

```sql
INSERT INTO t VALUES(1);

ERROR:  could not find any shards
DETAIL:  No shards exist for distributed table "t".
HINT:  Run master_create_worker_shards to create shards and try again.
```

Which is not possible as expected.

**Comment by marcocitus** [comment]
You'd get the same error for hash-distributed tables. `master_drop_all_shards` is not meant to be called by users.

**Comment by ozgune** [comment]
@marcocitus / @byucesoy -- If the behavior above is the expected one, should we then close this issue?

**Comment by byucesoy** [comment]
Well, I think it is not expected, however as @marcocitus said this UDF is not supposed to called by user. I guess, it is OK to close.
