### ISSUE TITLE
Maintenance daemon may skip cache invalidations

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#1636]
To start with, this issue does not lead to any critical issues except for generating many `WARNINGs` on the coordinator's log file. Once the coordinator is restarted, the `WARNINGs` go away. But seems worthwhile to backport to 7.0.

Steps:
1. Connect to the coordinator and remove a node
```
SELECT master_remove_node('localhost', 9702);
```

2. Check the coordinator's log file, you'll see lots of these warnings:
```
CONTEXT:  Citus maintenance daemon for database 12669 user 10
WARNING:  no connection to the server
CONTEXT:  while executing command on localhost:9702
	Citus maintenance daemon for database 12669 user 10
WARNING:  connection error: localhost:9702
DETAIL:  no connection to the server
```

The reason: 

With #1584 we've added a logic to reset the metadata OID caches on each iteration of deadlock detection. (See the reason and long discussions for that in the PR.)

That seems to lead this weird behavior. Once a node is deleted from `pg_dist_node`, the maintenance daemon gets a cache invalidation message, however, it might skip the invalidation since the OID for `pg_dist_node` might be `InvalidOid` at the time the invalidation happens. See the gdb output for better understanding (add break point to `InvalidateNodeRelationCacheCallback` and later remove a node while gdb attached to the daemon):

```
Breakpoint 1, InvalidateNodeRelationCacheCallback (argument=0, relationId=16494) at utils/metadata_cache.c:2766
2766		if (relationId == InvalidOid || relationId == MetadataCache.distNodeRelationId)
(gdb) p relationId
$1 = 16494
Current language:  auto; currently minimal
(gdb) p MetadataCache.distNodeRelationId
$2 = 0
```
(Node that `16494` is `pg_dist_node`'s `OID`)

(Thanks @furkansahin for reporting this)

**Comment by anarazel** [comment]
Two possibilities:
- replace ClearMetadataOIDCache() with InvalidateSystemCaches()
- move workerNodeHashValid, LocalGroupId into the MetadataCache struct
