### ISSUE TITLE
Exception "ERROR: unrecognized node type:" with citus 7.0.0 & JDBC

### ISSUE THREAD

**Issue by btnguyen2k** [citusdata/citus#1640]
Citus version: 7.0.0
PostgresSQL JDBC version: 42.1.4
Java version: 64 bit Linux 1.8

The following code throws exception "org.postgresql.util.PSQLException: ERROR: unrecognized node type: 32" after around ~10 rows have been inserted:

```java
        try (Connection conn = DriverManager.getConnection(url, user, password)) {
            final String SQL = "INSERT INTO tableName (col1, col2) VALUES (?,?) ON CONFLICT DO NOTHING";
            Random RAND = new Random(System.currentTimeMillis());
            for (int i = 0; i < 1000; i++) {
                try (PreparedStatement pstm = conn.prepareStatement(SQL)) {
                    String col1Value = String.valueOf(RAND.nextLong());
                    long col2Value = RAND.nextLong();
                    String data = "{\"_" + col1Value + "\":" + col2Value + "}";
                    pstm.setString(1, col1Value);
                    pstm.setLong(2, col2Value);
                    pstm.executeUpdate();
                    System.out.println(soData);
                }
            }
        }
```

The code above did work ok with Citus version 6.2.2 and 6.2.3.

Regards,
Thanh Nguyen

**Comment by velioglu** [comment]
@btnguyen2k I have tried to reproduce the error but couldn't achieve. Could you share your PG version and details of how you created the Citus stack ?

**Comment by btnguyen2k** [comment]
Hi @velioglu,
I simply use docker version of citus (v7.0.0) via docker-compose (scale worker=2) and still got the same error.
The docker image is citus official image from docker hub

**Comment by sumedhpathak** [comment]
This is fixed in master, and we'll be releasing a patched version soon.

**Comment by btnguyen2k** [comment]
Thanks,
I am looking forward to the new release.

Best regards,

**Comment by jasonmp85** [comment]
7.0.1 is available now and a new Docker image has been built. Can you try `citusdata/citus:7.0.1` and tell us whether the issue is resolved? If so, feel free to close this ticket; thanks!

**Comment by jasonmp85** [comment]
Hm, I believe the `docker-compose` file is still in flux to address some issues with the `scale` support. I don't think it will be usable until we merge some changes in another repo (scheduled to wrap up tomorrow). @btnguyen2k… I'll ping you tomorrow after that's wrapped up and we can see whether this issue has been solved.

**Comment by btnguyen2k** [comment]
Thank @jasonmp85, I tested v7.0.1 (installed via yum) and the error has gone.

Cheers,

**Comment by winstontantan** [comment]
This bug fixes very timely. I just found this BUG yesterday, almost gave up CITUS the. Thank you very much for developers. You saved me ~!
