### ISSUE TITLE
coordinator node crashes while creating distributed table when there is an older worker node

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#1659]
Hit this when investigating something else
- build citus version 7.0-2 from label 04fe3f0 (git checkout 04fe3f0)
- prepare a worker node, and install citus
- build up to date citus version  7.0-15  from label c6ec493 (git checkout c6ec493)
- prepare a master node, and install citus
- create a table (create table t1(a int, b int))
- distribute t1 on a (select create_distributed_table('t1', 'a'))

coordinator first gives following error then, crashes with assert
```
ERROR:  function assign_distributed_transaction_id(integer, integer, unknown) does not exist at character 57
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
STATEMENT:  BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;SELECT assign_distributed_transaction_id(0, 2, '2017-09-18 14:10:06.160085-07');


TRAP: FailedAssertion("!(PQtransactionStatus(connection->pgConn) == PQTRANS_INTRANS)", File: "transaction/remote_transaction.c", Line: 140)
```

Same steps result in just assert when coordinator and worker are placed on different nodes.
assert is thrown  [here](https://github.com/citusdata/citus/blob/master/src/backend/distributed/transaction/remote_transaction.c#L140)

It looks like we are sending two commands there and only checking success state of the first command.

**Comment by mtuncer** [comment]
Proposed fix is

implement a logic in ```FinishRemoteTransactionBegin()``` similar to ```ForgetResults()```. 
i.e. keep looping on ```GetRemoteCommandResult()``` until results from all commands previously sent in ```StartRemoteTransactionBegin()```  are consumed.

something like
```c
while (true)
{
    PGresult *result = GetRemoteCommandResult(connection, raiseErrors);

    if (result == NULL)
    {
        break;
    }

    if (!IsResponseOK(result))
    {
        ReportResultError(connection, result, WARNING);
        MarkRemoteTransactionFailed(connection, raiseErrors);
    }
    else if (transaction->transactionState == REMOTE_TRANS_STARTING)
    {
        transaction->transactionState = REMOTE_TRANS_STARTED;
        transaction->lastSuccessfulSubXact = transaction->lastQueuedSubXact;
    }
    PQclear(result);
}
```

**Comment by ozgune** [comment]
@mtuncer / @onderkalaci -- We seem to have two issues here.

1. When the user upgrades their coordinator node, but not worker nodes, then we crash. We should clearly document that we'd like the user to upgrade all nodes in their cluster. We're currently tracking this issue in https://github.com/citusdata/citus_docs/issues/422.
  * Can we also check for this mismatch in the product itself? We have users who only upgrade their coordinator node. What upgrade story do we offer to them?

2. We send multiple commands over a connection. One of the commands return an error message. Citus crashes.

Let's focus on fixing the second issue in here. @onderkalaci -- this isn't related to #1660, is it?

**Comment by linxd** [comment]
in 15，citus 13， also got this error.
