### ISSUE TITLE
An idea for metadata changes: If we're moving shard placement 102 from node A to node C, first change placement on node A to "sending" and insert a row to signal that the placement on node C is "receiving." Once the transfer is complete, we delete the "sending" placement and change the "receiving" shard to finalized

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#166]
2/ Another idea for metadata changes in the future. If we're moving shard placement 102 from node A to node C, first change placement on node A to "sending" and insert a row to signal that the placement on node C is "receiving." Once the transfer is complete, we delete the "sending" placement and change the "receiving" shard to finalized. For our current use-case, this doesn't buy us much. It may become helpful in the context of real-time inserts -- particularly if the inserts are commutative.

**Comment by marcocitus** [comment]
Shard moves are implementing using logical replication.
