### ISSUE TITLE
Procedure for changed IP on worker

### ISSUE THREAD

**Issue by taybin** [citusdata/citus#1666]
Situation: Citus cluster with master and workers is shutdown.  Backups for cluster nodes (including master) are restored on a different set of machines.  At this point, pg_dist_node is incorrect because the IPs are different.  Also the citus background task is detecting that it can't communicate with the other nodes and restarting the process because the connection is null.

I was able to fix pg_dist_node by UPDATEing the rows with the new IPs, but I had to make several attempts for each change because my client would get disconnected after each change by the background task.

Is there a better procedure I can use for this scenario?  Perhaps by calling `master_disable_node()` on each worker first?  The documentation wasn't clear on what would happen to shards existing on a disabled node.

Running 7.0.1

**Comment by taybin** [comment]
I was able to work around this by using /etc/hosts to maintain a mapping to the IP.  I am still curious about the behavior of `master_disable_node()` though.

**Comment by ozgune** [comment]
Hey @taybin -- we may prioritize a user-defined function that enables users to update their pg_dist_node metadata.

I had a clarification question on your original comment.

>> At this point, pg_dist_node is incorrect because the IPs are different. Also the citus background task is detecting that it can't communicate with the other nodes and restarting the process because the connection is null.

Could you elaborate a bit more on the behavior you observed here? When you change the IP address, does the coordinator node shut down and restart?

**Comment by taybin** [comment]
Yes.  That is exactly what would happen.

I'm actually seeing something very similar to #1636 after doing a backup restore, where the coordinator node claims that it can't communicate with the workers, although queries go through successfully.  This causes it to fill the logs with "no connection to server", "connection error: worker1".

Restarting the coordinator postgres instance doesn't resolve the issue and neither does restarting the worker nodes.

I tried disabling the nodes via `master_disable_node()`, but that didn't fix the issue and then citus wouldn't let me reactivate the nodes, complaining about "could not find any healthy placement for shard 102008".

At the moment, I'm guessing this is happening because I didn't run `master_add_node()`, the `pg_dist_node` table was populated by the backup restore and `master_add_node()` does something special that short circuited by the table already being populated.  So I'm looking for something that will preserve the data, but still allow me to give the maintenance daemon a kick to get it working again.

**Comment by taybin** [comment]
I figured out the issue.  Part configuration error, but maybe also a problem with the maintenance daemon.

I have the worker nodes locked down with so that you need to a special user and password to log into them.  This is communicated to the controller node via a .pgpass file, and this appears to work.  However, the maintenance daemon didn't stop complaining about not being able to communicate with the workers until I added 
```
# Trusted hosts
host  all  all  10.2.0.0/8  trust
```
to the workers' pg_hba.conf files.  So could it be that the maintenance daemon is ignoring the .pgpass file?  It seems likely to me that it is using libpg, but I'm at a loss for other theories.

**Comment by marcocitus** [comment]
> I'm actually seeing something very similar to #1636 after doing a backup restore, where the coordinator node claims that it can't communicate with the workers, although queries go through successfully. This causes it to fill the logs with "no connection to server", "connection error: worker1".

Yep, this looks exactly like #1636. We have a fix that we plan to include in an upcoming patch release https://github.com/citusdata/citus/pull/1681 .

>  So could it be that the maintenance daemon is ignoring the .pgpass file? 

It doesn't, but this change may have triggered a maintenance daemon restart, which would make it reload the metadata. You can also manually restart the maintenance daemon by running: `SELECT pg_cancel_backend(pid) FROM pg_stat_activity WHERE application_name = 'Citus Maintenance Daemon';`

**Comment by sumedhpathak** [comment]
@lithp Could you look into this one? Thanks!

**Comment by lithp** [comment]
@taybin Can you clarify, when you said you figured out the issue, do you mean your client is no longer getting disconnects? If you're still getting disconnects, I'm at kind of a loss for what could be causing it. I'd like to give you instructions for running a debug build of Citus and sending us a stacktrace, Citus should never crash!

**Comment by metdos** [comment]
@marcocitus, can we close this given that we merged #1691, #1636 and #1660. Referring https://github.com/citusdata/citus/pull/1691#issuecomment-336970164

**Comment by taybin** [comment]
Yes, my client is no longer getting disconnected.  I haven't upgraded to 7.0.3 yet, but I hope to soon and will test out the `master_update_node()`.  Thank you for your help!

**Comment by marcocitus** [comment]
Thanks @taybin !
