### ISSUE TITLE
Citus adds extra filter on INSERT / SELECT queries which messes PG planner estimates

### ISSUE THREAD

**Issue by samay-sharma** [citusdata/citus#1671]
While running INSERT / SELECT queries, Citus adds filters on worker node queries like:

```
((worker_hash(distribution column) >= '-2147483648'::integer) AND (worker_hash(distribution column) <= '-2013265921'::integer) 
```

This leads to the planner having very wrong estimates. An example is below.

```
->  Seq Scan on table  (cost=0.00..2742400.71 rows=1430 width=66) (actual
 time=43751.529..119194.216 rows=16207353 loops=1)
                                       Filter: ((worker_hash(column) >= '-2147483648'::integer) AND
 (worker_hash(column) <= '-2013265921'::integer) AND (to_timestamp(("timestamp")::double precision)
 >= '2017-09-19 00:00:00+00'::timestamp with time zone) AND (to_timestamp(("timestamp")::double
 precision) < '2017-09-20 00:00:00+00'::timestamp with time zone))
```

This can lead to worse query plans on each worker node shard and hence worse query performance.

**Comment by onderkalaci** [comment]
As far as I remember, we had to add `worker_hash` filters because the way we detect unsupported outer joins was failing to detect all cases when reference  tables involved (it was the initial implementation of INSERT .. SELECT pushdown, we've fixed that already). That's why, for  certain types of `OUTER JOIN`s, it was possible to INSERT `NULL` values to distribution key on the target table. To filter out those, we added `worker_hash ` calls.

We should spend a little more time to see if there are any such issues, otherwise we should be able to remove it.

**Comment by onderkalaci** [comment]
To be more clear, that is to prevent ingesting `NULL` values via outer joins:

```SQL
CREATE TABLE t1 (a int);
CREATE TABLE t2 (a int);
SELECT create_distributed_table('t1', 'a');
SELECT create_distributed_table('t2', 'a');

INSERT INTO t1 VALUES (1);
INSERT INTO t2 VALUES (2);

-- this query can generate NULL values
SELECT t1.a, t2.a FROM t1 FULL JOIN t2 USING (a);
 a | a 
---+---
 1 |  
   | 2
(2 rows)


-- now, if we don't add the worker_hash filter, we could insert NULL to the distributed table
-- instead the planner adds worker_hash filter to the query  to filter out NULL values
-- this is actually not quite correct, we implicitly filter out rows without the user knowing
INSERT INTO t1 SELECT t1.a FROM t1 FULL JOIN t2 USING (a) RETURNING * ;
 a 
---
 1
(1 row)

INSERT 0 1
-- but, INSERT .. SELECT via repartition prevents it
INSERT INTO t1 SELECT t1.a FROM t1 FULL JOIN t2 USING (a) OFFSET 0;
ERROR:  the partition column value cannot be NULL
CONTEXT:  while executing command on localhost:9700

```

To  keep the current behaviour, we  could replace `worker_hash` calls  with `dist_key IS NOT NULL` which should yield a lot more  accurate plans.


To do the more accurate/expected thing  as INSERT .. SELECT via  repartitioning, we should replace `worker_hash` in the query to something like `throw_error_if_null(dist_key)`,  though this might break some existing users who used to filter out NULLs. Plus, it might perform really bad as well.

One other more complex item could be to replace `dist_key` in the select part with `coalesce(t1.dist_key, t2.dist_key)` which we already know that the tables are joined on distributed keys. Though, this seems pretty complex as we should include all the tables in the JOIN.

We can also be a little smart, and only add filters if  we have at least one outer join in the query.

**Comment by onderkalaci** [comment]
As a note that Sai mentioned, if we  could allow NULL values in distribution keys, we could get rid of this at all.
