### ISSUE TITLE
Need install from source documentation

### ISSUE THREAD

**Issue by kbaegis** [citusdata/citus#1679]
I use gentoo based containers. I need a way to install Citus from source, and I'm finding absolutely no information on how to do this. If someone is not limiting their installs to apt or premade rpms, how is this supposed to be accomplished?

**Comment by lfittl** [comment]
@kbaegis Thanks for reaching out!

Citus works the same as most other Postgres extensions in that regard - assuming you have the necessary build environment (Postgres headers, compiler, etc) it should be a simple matter of `./configure` (which will need pg_config to be available, which provides installation paths, etc), `make` and then `sudo make install` to place them into the correct paths.

You should be able to use the tarballs from https://github.com/citusdata/citus/releases I believe.

Does that help / anything particular you ran into?

**Comment by kbaegis** [comment]
So I was able to get everything working rolling my own docker container- everything. except the worker discovery. I have to manually add my workers with SELECT * from master_add_node('citus_worker_1', 5432); rather than relying on the built-in functionality with docker-compose scaling. How is this implemented?

**Comment by kbaegis** [comment]
Got it. I wasn't using citusdata/membership-manager:0.1.0 :)
