### ISSUE TITLE
Support for multiple databases

### ISSUE THREAD

**Issue by kbaegis** [citusdata/citus#1680]
Can we add support for multiple databases on the same citus nodes? 

Rather than having the entrypoint read the .sql files sequentially under a monolithic DB, if we do it by directory then we could do something like this:

ADD sql/* /docker-entrypoint-initdb.d/

and the entrypoint reads sql/bob/000-create-citus-extension.sql and creates it for the bob database and so on. It seems cleaner to me. I'm not sure how this extends to the manager code which appears to be hardcoded to the postgres user and only reads a single POSTGRES_DB env on init at present.

**Comment by marcocitus** [comment]
Citus (mostly) supports using multiple databases, I moved your issue to the docker repo:
https://github.com/citusdata/docker/issues/41
