### ISSUE TITLE
Make with --without-libcurl fails if you don't have curl

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#1693]
```
utils/statistics_collection.c:13:23: fatal error: curl/curl.h: No such file or directory
```

If you don't have the curl library installed it should be possible to build, by adding the `--without-libcurl` flag.

**Comment by jasonmp85** [comment]
This also broke the nightly packaging jobs… https://travis-ci.org/citusdata/packaging/jobs/286691668#L609-L612
