### ISSUE TITLE
citus_total_relation_size error message is too verbose

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#1694]
It emits `ERROR:  could not open relation with OID 23227`. This has 2 problems:
- Nobody cares about OIDs, it's not user-friendly
- It makes our regression tests brittle

The table size functions should instead accept a table name (this changes the signature of those functions but not their usage, so I think it's a safe change) and then emit an error message if that table disappears before we call `relation_open`.

**Comment by jasonmp85** [comment]
> The table size functions should instead accept a table name

I'm of the strong opinion that we should use correct types when possible. `text` does not describe what this function expects.

**Comment by marcocitus** [comment]
+1 on keeping regclass.

**Comment by jasonmp85** [comment]
@lithp hasn't this been entirely addressed now? Can we close this?
