### ISSUE TITLE
Remove master node (masterless)

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#17]
Citus currently has a master node that holds authoritative metadata. This issue is to remove the master node from the Citus architecture and make sure that all nodes can ingest data and hold metadata.

The subtasks for this project are:
- Requirements and design document (#18)
- Propagate metadata changes to all nodes (2PC or pg_paxos) (#19)
- Replication group automated fail-over (Requirements document: review existing solutions) (#20)
- Replication group fail-over (#21)
- Replication group initialization logic (#22)
- Educating users on PostgreSQL's streaming replication (#23)
- Answer compatibility questions with existing Citus deployments (#24)

**Comment by ozgune** [comment]
We're currently tracking this project (MX) and its sub-tasks in #744.

@marcocitus -- What do you think about closing any issues between #17-#24 that are duplicates?

**Comment by anarazel** [comment]
@marcocitus @ozgune I think we can mark this as closed/fixed?

**Comment by ozgune** [comment]
Sounds good to me. Now that we have MX integrated to Citus in #744, I'm closing #17-#24 in favor of that issue.

@marcocitus -- if you don't agree, please feel free to reopen any of the issues.
