### ISSUE TITLE
Extend pg_dump to include our syntax changes.

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#170]
Extend pg_dump to include our syntax changes.

**Comment by anarazel** [comment]
@sumedhpathak @ozgune I'd like to close this issue, as the current description isn't meaningful. How about opening a new issue about preserving citus-specific knowledge in pg_dump?

**Comment by sumedhpathak** [comment]
I am OK to close it. Does #348 capture adding pg_dump support in Citus?

**Comment by lithp** [comment]
@sumedhpathak Yes, #348 is now about pg_dump not erroring out.
