### ISSUE TITLE
Implement `ALTER TABLE % REPLICA IDENTITY` for distributed tables

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#1714]
As we're considering using logical replication, being able to set replica identity should provide a better user experience.

Also, I couldn't find a way to run it with `run_command_on_placements()` for the following since we need to pass two strings, which is not supported now:

```SQL
 SELECT run_command_on_placements('rep_test', 'unique_index_name',  'ALTER TABLE %s REPLICA IDENTITY  USING INDEX %s');

```

**Comment by furkansahin** [comment]
fixed #1731
