### ISSUE TITLE
Address PostgreSQL 11 VACUUM Changes

### ISSUE THREAD

**Issue by jasonmp85** [citusdata/citus#1715]
The PostgreSQL 11 build has been failing in Travis for a while, so gave it a quick look. Decided to open up this issue to avoid forgetting what to fix down the line.

Appears that postgres/postgres@11d8d72c27a64ea4e30adce11cf6c4f3dd3e60db added the ability to specify multiple relations in a single `VACUUM` command, which required changing the fields of `VacuumStmt`.

This issue has two tasks:

  * **Fix compilation and restore the distributed `VACUUM` feature** — I threw up a quick sketch in 54f104458922, which doesn't appear to be correct, but something like that could work. Basically don't allow distributed `VACUUM`s over multiple relations (preserve old behavior)
  * **Implement multi–distributed-relation `VACUUM`** — Maybe a little harder than it sounds at first, since users could specify a mix of local and remote relations

**Comment by marcocitus** [comment]
Seems to have been fixed.
