### ISSUE TITLE
table cache lookup failure when there are multiple pg+citus+cstore installations

### ISSUE THREAD

**Issue by kethineni1** [citusdata/citus#1730]
CREATE FOREIGN TABLE LINEITEM (
                L_ORDERKEY              BIGINT NOT NULL, -- references O_ORDERKEY
                L_PARTKEY               BIGINT NOT NULL, -- references P_PARTKEY (compound fk to PARTSUPP)
                L_SUPPKEY               BIGINT NOT NULL, -- references S_SUPPKEY (compound fk to PARTSUPP)
                L_LINENUMBER    INTEGER,
                L_QUANTITY              DECIMAL,
                L_EXTENDEDPRICE DECIMAL,
                L_DISCOUNT              DECIMAL,
                L_TAX                   DECIMAL,
                L_RETURNFLAG    CHAR(1),
                L_LINESTATUS    CHAR(1),
                L_SHIPDATE              DATE,
                L_COMMITDATE    DATE,
                L_RECEIPTDATE   DATE,
                L_SHIPINSTRUCT  CHAR(25),
                L_SHIPMODE              CHAR(10), 
                L_COMMENT               VARCHAR(44) 
        ) SERVER cstore_server
OPTIONS(compression 'pglz');

SELECT create_distributed_table(table_name:='LINEITEM',distribution_column:='l_orderkey');

SQL Error [XX000]: ERROR: cache lookup failed for foreign table 0¶  Where: SQL statement "SELECT EXISTS (SELECT 1 FROM public.lineitem)"

**Comment by mtuncer** [comment]
hey @kethineni1 
Thanks for reporting the issue. I have looked at it but can not reproduce it at our end.

Could you provide more context ?
1 - can you run the same scenario with regular tables ?
2 - have you installed cstore_fdw to all workers ?
3 - do you have cstore_fdw in ```shared_preload_libraries``` ? in both coordinator and workers. (note it should be set to```'citus, cstore_fdw'```)

Another thing that took my attention is the failing query ```SELECT EXISTS (SELECT 1 FROM public.lineitem)```. This query is not supported by citus, and should fail with another error. Could you go over your setup again ?

thanks

**Comment by kethineni1** [comment]
1. regular non foreign table works fine
2. verified cstore exists
3. cstore is in shared libs
4. verified each node can create cstore table
5. SELECT EXISTS (SELECT 1 FROM public.lineitem) is not from our code base.

$ sudo -i -u postgres  psql -U postgres -h localhost -p 1111 -c "CREATE
FOREIGN TABLE  LINEITEM3( L_ORDERKEY BIGINT NOT NULL) SERVER cstore_server;"
CREATE FOREIGN TABLE
$ sudo -i -u postgres  psql -U postgres -h localhost -p 1111 -c "SELECT
create_distributed_table(table_name:='LINEITEM3',distribution_column:='l_orderkey');"
ERROR:  cache lookup failed for foreign table 0
CONTEXT:  SQL statement "SELECT EXISTS (SELECT 1 FROM public.lineitem3)"

**Comment by mtuncer** [comment]
I tracked down where that query might be failing.  It is an SPI query to check whether the table being distributed already has some rows.

But still can't reproduce it.
Could you describe the environment i.e. PG version, OS version, citus setup (version, coordinator/workers)

**Comment by mtuncer** [comment]
confirmed that @kethineni1 no longer have the problem. It might have caused by having multiple versions of pg+citus+cstore_fdw on the same server.

**Comment by mtuncer** [comment]
@ozgune @jasonmp85 it seems like we may have problems when multiple versions are installed via packages. Shall we keep this issue open to investigate that ?

**Comment by ozgune** [comment]
@mtuncer -- Sounds good. Could you update this issue's title accordingly?
