### ISSUE TITLE
Push down CLUSTER command on distributed tables

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#1752]
Citus' behavior with `CLUSTER` command is confusing. We don't error out but don't push it down, which is confusing since `CLUSTER` is meaningful if there is data on the node.

It appears that we [have the logic](https://github.com/citusdata/citus/blob/master/src/backend/distributed/relay/relay_event_utility.c#L140) for pushing it down .

**Comment by aamederen** [comment]
I want to note that propagating `CLUSTER` on worker nodes is a user request.

**Comment by metdos** [comment]
Note: We have added a warning message, I'm updating the issue description.

**Comment by ssavkovic** [comment]
Supporting this request as clustering of tables can significantly improve query performance. I got almost order of magnitude improvement on my spatial queries that use postal code index or Post GIS spatial index. After sorting my rows on primary key (makes sure that rows that are close to each other on the map are also close to each other in the table). Had to manually cluster each shard table on each node to do it.
