### ISSUE TITLE
Co-locates with a distributed table without a colocation group

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus#1755]
When we create a table with `master_create_distributed_table`, shards are not created yet and it should error out if we try to colocate a table with this one but it doesn't.
To reproduce,
```SQL
ec2-user=# create table t1(i int);
CREATE TABLE
ec2-user=# create table t2(i int);
CREATE TABLE
ec2-user=# SELECT master_create_distributed_table('t1', 'i', 'hash');
 master_create_distributed_table
---------------------------------

(1 row)

ec2-user=# SELECT create_distributed_table('t2', 'i', colocate_with=> 't1');
 create_distributed_table
--------------------------

(1 row)

ec2-user=# select logicalrelid, colocationid from pg_dist_partition where logicalrelid = ANY (array['t1'::regclass,'t2'::regclass]);
 logicalrelid | colocationid
--------------+--------------
 t1           |            0
 t2           |            0
(2 rows)
```

**Comment by onderkalaci** [comment]
I don't think that's an important issue. `master_create_distributed_table` is deprecated and we have `mark_tables_colocated()` UDF which can be used to fix this situation.

**Comment by ozgune** [comment]
@onderkalaci -- I agree. We deprecated `master_create_distributed_table` and we don't refer to this function in our docs.

@furkansahin, what do you think about closing this issue as "will not fix"?

**Comment by furkansahin** [comment]
@ozgune sure.

This will not be fixed.
