### ISSUE TITLE
Distributing a partitioned table errors out

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1758]
Citus MX currently doesn't support table partitioning. We disabled partitioning for MX because of the complexity associated with running `DROP TABLE` on distributed and partitioned tables.

However, the error check that we put in for Citus MX also kicks in when we use the streaming replication. So this error check forbids partitioning a distributed table on Cloud.

```
SELECT create_distributed_table('measurement', 'city_id');
ERROR:  distributing partitioned tables which uses streaming replication is not supported
```

Should we quickly fix this for 7.1?

(also, typo in the error message)

**Comment by lfittl** [comment]
@marcocitus @sumedhpathak FWIW, if possible fixing this in 7.1 would be nice, given that this means right now nobody could use Postgres partitioning + distributed tables on Cloud.
