### ISSUE TITLE
Support WITH OIDS

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1760]
We're now using logical replication to rebalance data in Citus Cloud. To support UPDATE / DELETE commands during a rebalance, we need a replica identity on shards.

For tables WITH OIDS, you can use the oid column as a replica identity.

```
postgres=# CREATE TABLE test (x int, y int);
CREATE TABLE
Time: 12.222 ms
postgres=# CREATE PUBLICATION test_pub FOR TABLE test ;
CREATE PUBLICATION
Time: 4.246 ms
postgres=# UPDATE test SET y = 3 WHERE x = 1;
ERROR:  cannot update table "test" because it does not have a replica identity and publishes updates
HINT:  To enable updating the table, set REPLICA IDENTITY using ALTER TABLE.
Time: 0.590 ms
postgres=# ALTER TABLE test SET WITH OIDS ;
ALTER TABLE
postgres=# CREATE UNIQUE INDEX CONCURRENTLY test_oid_idx ON test (oid);
CREATE INDEX
postgres=# ALTER TABLE test REPLICA IDENTITY USING INDEX test_oid_idx;
ALTER TABLE
postgres=# UPDATE test SET y = 3 WHERE x = 1;
UPDATE 0
```

Main drawback of using WITH OIDS is that OIDS are 4 byte integers that may wrap around, which would cause failures in the unique index. An alternative, though much more elaborate implementation that does not have this limitation is https://github.com/citusdata/citus/issues/1729 

We may want to consider setting WITH OIDS by default on shards, since adding it later causes downtime. We could even consider adding the unique index and replica identity by default on reference tables, such that we can seamlessly replicate reference tables to new nodes.

**Comment by pykello** [comment]
@marcocitus "WITH OIDS" was removed few months ago: https://github.com/postgres/postgres/commit/578b229718e8f15fa779e20f086c4b6bb3776106

So should we close this issue?

**Comment by marcocitus** [comment]
Yep.
