### ISSUE TITLE
Coordinator crashes during multi shard update when a worker node fails

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#1763]
This is a crash due to assert.
- run a long update or insert into select query  (tested with a 32 shard table with 12M rows)
- kill one of the workers 
- coordinator crashes with and assert
```
TRAP: FailedAssertion("!(queryOK)", File: "executor/multi_router_executor.c", Line: 1145)
```

**Comment by mtuncer** [comment]
Note : update takes very little time. My test included a table``` t1(a int, b int, c int)``` with 32 shards.

Created a UDF at coordinator and workers
```sql
create or replace function return_one(b int)
returns int language plpgsql immutable as $$ 
begin 
    perform pg_sleep(1);
    return 1;
end; 
$$;
```

and used following query
```sql
update t1 set c to return_one(b) where b = 100
```

Issue is also present when run on a single shard
```sql
update t1 set c to return_one(b) where a = 100
```

**Comment by marcocitus** [comment]
Where does it crash in the single shard case?

**Comment by mtuncer** [comment]
my mistake, I killed the wrong process (coordinator) and saw the coordinator crashed.

Killing worker in single shard update does not crash coordinator. It fails with a proper error message.

**Comment by marcocitus** [comment]
Good find. I guess the code assumes setting `failOnError` to true means ConsumeQueryResult/StoreQueryResult throw an error if the connection is down, but they only error out if the query returns an error.

Maybe in `ExecuteModifyTasks` do:

```
if (!queryOK)
{
    ReportConnectionError(connection, ERROR);
}
```

or in `ConsumeQueryResult` and `StoreQueryResult` do:

```
if (result == NULL)
{
    if (failOnError)
    {
        ReportConnectionError(connection, ERROR);
    }

    break;
}
```

**Comment by mtuncer** [comment]
Observed the same crash with index creation (create index concurrently)
