### ISSUE TITLE
Upgrade_to_reference_table leaves shards on the workers after failure

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#1767]
Steps to reproduce

- create a distributed table with single shard
- call upgrade_to_reference table, kill a worker process
- pg_dist_shard_placement contains only one row for this shard
- However workers (except the one that is killed) have copies of the single shard

**Comment by mtuncer** [comment]
I used following event trigger to slow down table creation on worker node. This allowed me to kill the worker process.

```sql
create or replace function create_event() returns event_trigger  language plpgsql as $$
begin
 if (TG_TAG = 'CREATE TABLE'::text) THEN
   raise notice 'sleep a bit';
   perform pg_sleep(30);
 END IF;
 return; 
 end; 
$$;



create event trigger create_event on ddl_command_start execute procedure create_event();
```

**Comment by onderkalaci** [comment]
> However workers (except the one that is killed) have copies of the single shard

Isn't this the expected behavior? We always create the shards first and update the metadata once everything is OK?

**Comment by mtuncer** [comment]
at least I did not expect that.  The transaction has failed, so we should revert any uncommitted changes.
