### ISSUE TITLE
create_distributed_table fails with wrong error message

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#1778]
This could be considered as a user error.

I was testing colocation with range tables, so I had 2 entries in pg_dist_partition with colocationid set to 1 and 2 respectively. ( I set the values myself)

Then I attempted to create a new hash distributed table.
```sql
select create_distributed_table('s1' ,'id');
ERROR:  unsupported table partition type: r
```
notice that pg_dist_colocation had a single entry at this time, probably due to an earlier create distributed table.

```sql
select *  from pg_dist_colocation;
 colocationid | shardcount | replicationfactor | distributioncolumntype 
--------------+------------+-------------------+------------------------
            1 |         32 |                 1 |                     23

```

It worked fine after I reset colocationid of offending tables to -1.

**Comment by metdos** [comment]
You shouldn't modify `pg_dist_partition` yourself, I think we can close this.
