### ISSUE TITLE
Remove broadcast join related logic

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#1787]
Citus 5.x and earlier had the notion of "broadcast joins". In Citus 6.x and after, we replaced that logic with reference tables (#879). However, we still have logic in the distributed planner and executor for broadcast joins. (edited)

@velioglu and I walked over our code base and decided to remove this logic in three or four steps. I'm including those steps below.

PR-1a
----
1. Remove all data and code segments that execute broadcast join logic (see [comment here](https://github.com/citusdata/citus/issues/1787#issuecomment-353874206) for detailed list). The only exception here is `citus.large_table_shard_count`
2. Fix related regression tests
3. Check that the enterprise and shard rebalancer repos work as expected

PR-1b
----
4. Change `LocalJoin()` in the join order planner. This function will now check if two tables are colocated. If not, we won't execute a local join. We expect this change to impact two large append distributed tables that are joined on the distribution column, or two hash / range distributed tables that are joined on different types
5. Fix related regression tests

PR-2
----
6. Refactor `BroadcastJoin` function into a `ReferenceTableJoin` function. We no longer have to check for number of shards in a table in this function. Remove `candidateShardList` argument from all join evaluation functions
7. In `FixedJoinOrderPlanner`, we emit the following error message: `Cannot perform outer joins with broadcast joins of more than 1 shard`. Check if this error message is accurate. If so, remove the related `if / else if` block.
8. Clean up `TODOs` marked in @velioglu's local branch.

PR-3
----
9. Change `citus.large_table_shard_count` to emit an error message when set
10. Fix related regression tests
8. Update documentation. Check that we have documentation to upgrade from broadcast tables to reference tables (#1075)

PR-4
---
12. Read over task tracker executor design document and/or fix
13. Read over issue #458 and check if it has now been resolved

Once we make these changes, we're also going to resolve the following issues:
* #2027
* #1789
* #1260 
* #527 
* #638 
* #292 (only third item in the list)
* #458 (if we get to PR-4)
* #253 
* #56

**Comment by jasonmp85** [comment]
Our [code coverage for that file](https://codecov.io/gh/citusdata/citus/src/master/src/backend/distributed/executor/multi_real_time_executor.c) still shows these lines being hit during testing…

We do still rely on this logic, right? So the proposal would be to entirely remove broadcast joins in favor of user-initiated reference tables for anything that might need to be on all nodes?

**Comment by ozgune** [comment]
I don't think we rely on broadcast logic anymore.

We have old regression tests that exercise this code path, but I don't think it's intentional.

**Comment by ozgune** [comment]
(Copy / pasted from the original issue description)

Citus 5.x and earlier had the notion of "broadcast joins". In Citus 6.x and after, we replaced that logic with reference tables (#879). However, we still have logic in the real-time and task-tracker executors to execute broadcast joins.

For example, `multi_real_time_executor.c`'s `ManageTaskExecution()` function has the following code:

<pre>
static ConnectAction
ManageTaskExecution(Task *task, TaskExecution *taskExecution,
		    TaskExecutionStatus *executionStatus)
{
...
  		case EXEC_FETCH_TASK_LOOP:
		{
			List *dataFetchTaskList = task->dependedTaskList;
			int32 dataFetchTaskCount = list_length(dataFetchTaskList);

			/* move to the next data fetch task */
			taskExecution->dataFetchTaskIndex++;
...
		case EXEC_FETCH_TASK_START:
...
		case EXEC_FETCH_TASK_RUNNING:
...
}
</pre>

Since we no longer rely on this logic, we should remove state and logic related to broadcast joins from our executors.

**Comment by ozgune** [comment]
We're removing broadcast join related logic from our codebase. This comment describes the data and code segments that we're removing.

Planner
----

* JoinOrderPlanner : Delete large_table_shard_count related code in BroadcastJoin
* PhysicalPlanner:
    * Delete ShardFetchTask type and all code paths that reference it
    * Delete ShardFetchQueryString()
    * Delete Task->shardId and all code paths that reference it
    * Delete ShardStorageRelay and all code paths that reference it
    * Check where we use ShardStorageForeign(Table and Columnar)
    * Delete FOREIGN_FETCH_COMMAND and TABLE_FETCH_COMMAND and all code paths that reference it
    * Check where we get the fragment reference in CITUS_RTE_RELATION

Executor
----

* Real Time Executor: Delete EXEC_FETCH_TASK_LOOP, EXEC_FETCH_TASK_START, EXEC_FETCH_TASK_RUNNING and all related code paths
* Task Tracker Executor: Delete Shard_Fetch_Task and ShardFetchTaskList functions

UDF
----
* Delete FetchTableCommon, LocalTableSize, FetchRegularTable, FetchForeignTable, RemoteTableOwner, ForeignFilePath, and all static function definitions that result from these functions
* Delete master_expire_table_cache file (Also check if this function has any other use that expiring cached shards)

GUC
----
* Delete ExpiredCacheShards config flag and related variable definition

**Comment by ozgune** [comment]
@velioglu / @metdos -- Could you provide a quick update on this issue?

If we merged in changes that remove broadcast joins, could we review issues listed in the first comment? (#2027, #1789, #1260, #527, #638, #253, #56) Could we then close issues that are no longer relevant?

**Comment by metdos** [comment]
> If we merged in changes that remove broadcast joins, could we review issues listed in the first comment? (#2027, #1789, #1260, #527, #638, #253, #56) Could we then close issues that are no longer relevant?

@velioglu ^^^

**Comment by ozgune** [comment]
@velioglu / @metdos -- I wanted to send a quick ping on this thread.

**Comment by velioglu** [comment]
@ozgune @metdos All the issues related to this one have been closed except #458 (I have added a note on that issue). This issue can be closed after solving the #458 and updating the task-tracker design document.

**Comment by marcocitus** [comment]
I'm going to close this issue as I don't think we're planning to take any more action on it.
