### ISSUE TITLE
Function worker_fetch_regular_table causes a lot of lock waiting events

### ISSUE THREAD

**Issue by yglh-gq** [citusdata/citus#1789]
Function worker_fetch_regular_table causes a lot of lock waiting events
# Environment
- PostgreSQL9.6.2
- citus_ 6.1.0
# Reproduce steps

1. DDL
```
set citus.shard_count = 16;
set citus.shard_replication_factor = 1;
create table tb1(c1 int,c2 int);
create table tb2(c1 int,c2 int);
select create_distributed_table('tb1','c1');
select create_distributed_table('tb2','c1');
```

2. insert data

```
insert into tb1 values(1,1);
insert into tb1 values(2,2);
insert into tb1 values(3,3);
insert into tb2 values(1,1);
insert into tb2 values(2,2);
insert into tb2 values(3,3);
``` 

3. call function `worker_fetch_regular_table` on a worker,do not commit

```
postgres=# begin;
postgres=# SELECT worker_fetch_regular_table  ('tb2_102026', 0, '{localhost}', '{9701}');
 worker_fetch_regular_table 
----------------------------
 
(1 row)
```

4. execute a join on master
```
select * from tb1,tb2 where tb1.c1 = tb2.c1;
```
then this query will be blocked until the query in step 3 commit .

# Source info
After we check the src,function `worker_fetch_regular_table` calls `FetchTableCommon` to perform the actual table fetching.We find that  `FetchTableCommon` will acquire a `AccessExclusiveLock` on shardID.
However,function `worker_fetch_regular_table` is used to broadcast append distributed tables.For hash distributed tables,the `remoteTableSize` will always be zero,and then this function will do nothing,just return.
With this in mind,for hash distributed tables whether this function call should be removed?
```
static void
FetchTableCommon(text *tableNameText, uint64 remoteTableSize,
				 ArrayType *nodeNameObject, ArrayType *nodePortObject,
				 bool (*FetchTableFunction)(const char *, uint32, const char *))
{
	...
	shardId = ExtractShardId(tableName);
	LockShardResource(shardId, AccessExclusiveLock);
        ...
	/* check if we already fetched the table */
	if (relationId != InvalidOid)
	{
		uint64 localTableSize = 0;

		if (!ExpireCachedShards)
		{
			return;
		}
               ...
		localTableSize = LocalTableSize(relationId);

		if (remoteTableSize > localTableSize)
		{
			/* table is not up to date, drop the table */
			ObjectAddress tableObject = { InvalidOid, InvalidOid, 0 };

			tableObject.classId = RelationRelationId;
			tableObject.objectId = relationId;
			tableObject.objectSubId = 0;

			performDeletion(&tableObject, DROP_RESTRICT, PERFORM_DELETION_INTERNAL);
		}
		else
		{
			/* table is up to date */
			return;
		}
	}
	...
}
```

**Comment by metdos** [comment]
Related to #1787

**Comment by ozgune** [comment]
Hi @yglh-gq, thank you for reporting this issue.

Could you describe your use case a bit more? Do you observe these performance issues in production?

Citus 5.2 and earlier versions implemented broadcast joins / reference tables by calling  `worker_fetch_regular_table()` behind the covers. Starting with Citus 6.0, we added proper support for reference tables, and our customers no longer need to call `worker_fetch_regular_table()`.

We're planning to deprecate `worker_fetch_regular_table()` and related broadcast join logic in the upcoming Citus release. #879 and #1260 discuss this issue further.

**Comment by yglh-gq** [comment]
Hi@ozgune ，yes，we observe these performance issues in production.
We received a warning which means there are too many waiting connections in a worker.It's a little bit strange because most sql in worker is select.
Then we caught some snapshots of pg_locks in production.Most locks in snapshots are added by calling `worker_fetch_regular_table()`.
In our later test,as long as we execute a join select with distributed table ,`worker_fetch_regular_table()` will be called.

**Comment by ozgune** [comment]
Hi @yglh-gq - We're planning to remove broadcast join related logic (and `worker_fetch_regular_table()`) in Citus 7.3. Citus 6+ supports colocated tables and reference tables; and these APIs are the recommended ways to join tables.

If you're seeing `worker_fetch_regular_table()` calls in production, you might be using deprecated functionality. Could you drop us a note in our Slack channel and describe when you see `worker_fetch_regular_table()`?

We're tracking the removal of `worker_fetch_regular_table()` in #1787.

**Comment by velioglu** [comment]
`worker_fetch_regular_table()` has been deprecated by #1915
