### ISSUE TITLE
Parser currently checks that table names are at most 64 characters. Reduce that limit to 50 characters, as we internally append shardIds to table names.

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#179]
Parser currently checks that table names are at most 64 characters. Reduce that limit to 50-55 characters, as we internally append shardIds to table names.

**Comment by ozgune** [comment]
@robin900 / @marcocitus -- do you think we can close this issue now?

**Comment by robin900** [comment]
@ozgune Yes, the PR #783 specifically mentions "Fixes #179".
