### ISSUE TITLE
start_metadata_sync_to_node causes deadlock when the coordinator added as mx node

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#1792]
hit this when testing #1746 to see previous behavior

following causes a deadlock when adding coordinator as an MX target.
```sql
set citus.replication_model to 'streaming';
select master_add_node('localhost', 5432);
select start_metadata_sync_to_node('localhost', 5432);
```

dump_local_wait_edges() does not report anything.

**Comment by onderkalaci** [comment]
As of some old release(s), we ask the administers to add the coordinator to the metadata with `groupid:=0` field.


```SQL
select master_add_node('localhost', 5432, groupid:=0);
NOTICE:  localhost:5432 is the coordinator and already contains metadata, skipping syncing the metadata
 start_metadata_sync_to_node 
-----------------------------
 
(1 row)

Time: 0.437 ms 
```

So, in that sense I think this is a low priority issue. Still, would be nice to throw an error instead of an undetected self-deadlock.

**Comment by onderkalaci** [comment]
Users do not need to call `start_metadata_sync` anymore. The problem with `add_node` is resolved via https://github.com/citusdata/citus/pull/5758
