### ISSUE TITLE
I can run create_distributed_table but failed when i drop that table.

### ISSUE THREAD

**Issue by chaintng** [citusdata/citus#1822]
I used CentOS 7 for master and 2 workers.
I create user with password for database in 3 nodes.
i put that authentication in `.pgpass` file under `/var/lib/pgsql`

Then, i create table and run
`SELECT create_distributed_table('ads', 'id');`

Everything work fine,

After that, i run `DROP TABLE ads`
but it failed with following error

```
WARNING:  connection error: 10.140.0.3:5432
DETAIL:  no connection to the server
WARNING:  could not connect to shard "ads_102104" on node "10.140.0.3:5432"
DETAIL:  Marking this shard placement for deletion
WARNING:  connection error: 10.140.0.4:5432
DETAIL:  no connection to the server
WARNING:  could not connect to shard "ads_102105" on node "10.140.0.4:5432"
DETAIL:  Marking this shard placement for deletion
WARNING:  could not connect to shard "ads_102106" on node "10.140.0.3:5432"
DETAIL:  Marking this shard placement for deletion
```

I set `pg_hba.conf` like this
```
host    all             all             10.0.0.1/8              md5
```

if i changed `md5` to `trust`, the DROP table went successfully...

It's really strange that it can create distributed table but cannot drop table under `md5` authentication

anyone has the same issue here?

**Comment by velioglu** [comment]
I have reproduced the problem with the community version. Enterprise version works flawlessly.

**Comment by marcocitus** [comment]
This seems to describe a configuration issue.
