### ISSUE TITLE
Should we error out in LocalJoin() if we have two columns that can join, but have different column types?

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#186]
Should we error out in LocalJoin() if we have two columns that can join, but have different column types?

**Comment by ozgune** [comment]
I'm looking at resources available on the internet. It would be nice to have this. That said, a good number of distributed databases out there don't seem to support it. For example, excerpt from a related source:

**Joining on different data types**: Even though join columns in two tables may contain the same numeric value and distribution keys, if they have different data types, the records are hashed to different shards -- as these are mathematically different columns. This operation must go through the same processing steps as single table redistribution.

**Comment by marcocitus** [comment]
These queries error out now.
