### ISSUE TITLE
Transactional INSERT SELECT via coordinator after normal INSERT SELECT

### ISSUE THREAD

**Issue by mattnaides** [citusdata/citus#1865]
Would it be possible to do an INSERT SELECT via coordinator after doing a normal INSERT SELECT in the same transaction?  Let's say I have two sets of tables, one set sharded on anon_id and the other set sharded on external_id.  I can currently do something like this
```
BEGIN;
insert into (external_id) from (select * from anon_id);  --Query 1 via coordinator
insert into (anon_id) from (select * from anon_id); --Query 2
insert into (external_id) from (select * from external_id); -- Query 3
COMMIT;
```
but switching the query order
```
BEGIN;
insert into (anon_id) from (select * from anon_id); --Query 2
insert into (external_id) from (select * from anon_id);  --Query 1 via coordinator
insert into (external_id) from (select * from external_id); -- Query 3
COMMIT;
```
results in `ERROR:  cannot open new connections after the first modification command within a transaction`

**Comment by marcocitus** [comment]
Yep, this is supported on the master branch, and will be part of the next release.
