### ISSUE TITLE
Trigger Issue

### ISSUE THREAD

**Issue by sm2017** [citusdata/citus#1868]
Consider the following schema

```sql
CREATE TABLE IF NOT EXISTS "test" (
  "one" BIGINT       NOT NULL,
  "two" BIGINT       NOT NULL
);
ALTER TABLE "test"
  ADD PRIMARY KEY ("one","two");
```

I want to distribute `test` table with two column `one` and `two` , As citus don't support this , I create a materialized view using trigger

```sql
CREATE TABLE IF NOT EXISTS "test2" (
  "two" BIGINT       NOT NULL,
  "one" BIGINT       NOT NULL
);
ALTER TABLE "test"
  ADD PRIMARY KEY ("two","one");

CREATE FUNCTION test_insert()
  RETURNS TRIGGER
  SECURITY DEFINER
  LANGUAGE plpgsql
AS $$
  BEGIN
      INSERT INTO "test2" ("two", "one") VALUES (NEW."two", NEW."one");
    RETURN NEW;
  END;
$$;

CREATE TRIGGER test_insert AFTER INSERT ON test
    FOR EACH ROW EXECUTE PROCEDURE test_insert();
```

So I can distribute `test` by column `one` and `test2` by `two`

I must add trigger to coordinator as there is many many table in workers and citus must handle it , and I know trigger in workers is executed if defined but they cannot distrubute new record to table `test2` , **But why citus don't execute trigger in coordinator** ? 

How can I create a materialized view ?

**Comment by marcocitus** [comment]
Triggers on distributed tables are not really supported right now, though some users do set up triggers directly on the shards on the workers.

**Comment by marcocitus** [comment]
an example of setting up triggers on the shards is given in:
https://docs.citusdata.com/en/v7.1/extra/query_propagation.html

**Comment by sm2017** [comment]
What about replication?? Assume I have 3 replied shard . why I must have 3 trigger execution for 1 insert?? Update and delete?

The solution creates many other issue like dead lock

**Comment by marcocitus** [comment]
It's recommended to set up streaming replication on the workers for such workloads and use replication factor of 1.

**Comment by sm2017** [comment]
If I do this . How can I access replications?? As citus coordinator don't detect them . How can I have high availability ??

**Comment by marcocitus** [comment]
You can use any auto failover tool for Postgres. If you prefer not to manage it yourself, you can use Citus Cloud, which can set up auto-failover for all nodes.

**Comment by sm2017** [comment]
According to FAQ

> 
> How does Citus handle failure of a worker node?
> If a worker node fails during e.g. a SELECT query, jobs involving shards from that server will automatically fail over to replica shards located on healthy hosts. This means intermittent failures will not require restarting potentially long-running analytical queries, so long as the shards involved can be reached on other healthy hosts. You can find more information about Citus’ failure handling logic in Dealing With Node Failures

If I use replication factor of 1and set up streaming replication on the workers . How coordinator can automatically fail over to replica shards??

**Comment by sm2017** [comment]
@marcocitus How can I chat you?? (WhatsApp, Twitter ,...)

**Comment by sm2017** [comment]
@marcocitus please help

**Comment by metdos** [comment]
> If I use replication factor of 1and set up streaming replication on the workers . How coordinator can automatically fail over to replica shards??

You need to update metadata on the coordinator by yourself or set up some logic around it. As noted above, you can use Citus Cloud, which can set up auto-failover for all nodes.

**Comment by metdos** [comment]
We already have an issue for triggers, #906. I'm closing this in favor that.
