### ISSUE TITLE
SELECT FOR UPDATE in subqueries quietly allowed

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1870]
Citus incorrectly allows you to execute some SELECT ... FOR UPDATE commands by wrapping the FOR UPDATE in a subquery. 

```
CREATE TABLE test (x int, y int);
SELECT create_distributed_table('test','x');

SELECT * FROM test WHERE x = 1 FOR UPDATE;
ERROR:  could not run distributed query with FOR UPDATE/SHARE commands
HINT:  Consider using an equality filter on the distributed table's partition column.

SELECT * FROM (SELECT * FROM test FOR UPDATE) foo WHERE x = 1;
 x | y 
---+---
 1 | 1
(1 row)

```

While FOR UPDATE is useful, Citus currently *does not execute FOR UPDATE commands correctly*. As long as we don't support it these commands should error out.

**Comment by onderkalaci** [comment]
> SELECT * FROM test WHERE x = 1 FOR UPDATE;
ERROR:  could not run distributed query with FOR UPDATE/SHARE commands
HINT:  Consider using an equality filter on the distributed table's partition column.


Note that the error message is misleading, given that it's also a router query.

**Comment by marcocitus** [comment]
SELECT..FOR UPDATE is allowed in router queries, and this seems to error out correctly for multi-shard queries.
