### ISSUE TITLE
JSONB concatenation leads to error

### ISSUE THREAD

**Issue by samay-sharma** [citusdata/citus#1880]
Coordinator query:

```
STATEMENT: select (src->'properties')::jsonb || '{"key":"value"}'::jsonb from table where column < 49850
 order by column desc limit 1;
```

Worker query: 
```
STATEMENT: COPY (SELECT ((src -> 'properties'::text) || '{"key": "value"}'::jsonb), column AS 
worker_column_2 FROM table WHERE (column < 49850) ORDER BY column DESC LIMIT '1'::bigint) TO
 STDOUT WITH (FORMAT binary)
```
So, Citus casts the jsonb to text which leads to user getting error on the worker nodes:
`WARNING:  invalid concatenation of jsonb objects`

Same query works on non-distributed table.

**Comment by marcocitus** [comment]
The `::text` is fine, it just cast `'properties'`to text., see also:

```sql
SELECT pg_typeof(('{"key":"value"}')::jsonb->'key'::text);
 pg_typeof 
-----------
 jsonb
(1 row)
```

Maybe you're concatenating a JSONB value and an object?

**Comment by saicitus** [comment]
As @marcocitus explained both postgres and citus allow to concatenate jsonbs only if they are objects or arrays. The type-casting the key to text makes sense as the key is in **text** format. Hence closing the issue.
