### ISSUE TITLE
CREATE INDEX CONCURRENTLY blocks inserts for shard_replication_factor = 2

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#1891]
Here is how to replicate;

```sql
CREATE TABLE test_table (id int, value numeric);

SET citus.shard_replication_factor = 2;
SELECT create_distributed_table('test_table', 'id');

-- insert enough data
INSERT INTO test_table SELECT generate_series(1,10000000), random();
```

```sql
-- run these concurrently from different psql clients
CREATE INDEX CONCURRENTLY myindex ON test_table(id);

INSERT INTO test_table VALUES (1, 1);
```

**Comment by metdos** [comment]
Here is the call stack for replication factor = 2. Basically, we get `ShareUpdateExclusiveLock` lock if the replication factor is =1, and `ExclusiveLock` if >1 on the anchor shards.

```
AcquireExecutorMultiShardLocks() at multi_router_executor.c:298 0x10ece3920	
ExecuteModifyTasks() at multi_router_executor.c:1,058 0x10ece26f8	
ExecuteModifyTasksWithoutResults() at multi_router_executor.c:989 0x10ece260e	
ExecuteTasksSequentiallyWithoutResults() at multi_router_executor.c:1,009 0x10ece2c44	
ExecuteDistributedDDLJob() at multi_utility.c:2,943 0x10ecebb7e	
multi_ProcessUtility() at multi_utility.c:557 0x10ece97ac
```

We need to differentiate `CREATE INDEX CONCURRENTLY`. Some alternatives;
i. Adding another boolean flag/ or lock type parameter to Task struct
ii. Adding lock type parameter to ExecuteTasksSequentiallyWithoutResults, ExecuteModifyTasksWithoutResults, ExecuteModifyTasks, AcquireExecutorMultiShardLocks functions
iii. Parsing `queryString` inside `task` and check for `CONCURRENTLY`.

@marcocitus any other ideas?

**Comment by marcocitus** [comment]
Maybe just skip the shard resource locks altogether for DDL commands.
