### ISSUE TITLE
Misleading error in create_distributed_table / when transaction switches role

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#1898]
When a transaction changes the role with which it connects to workers, either because it calls a `security definer` function or because of (buggy?) Citus internals, we may give a misleading error.

In particular, `create_distributed_table` creates shards as the relation owner, but may then attempt to copy data as the current user (e.g. superuser). This gives an error message like the following:
```
SELECT create_distributed_table('test','x');
ERROR:  cannot establish a new connection for placement 122, since DDL has been executed on a connection that is in use" while running
```

**Comment by samay-sharma** [comment]
Ran into this with a couple customers over the last few weeks.

**Comment by byucesoy** [comment]
Similar issue is also come up in public slack channel, but with `create_reference_table`

**Comment by rayrapetyan** [comment]
I'm getting this error all over the app, in different places (e.g. in CREATE TABLE \ COPY \ DROP TABLE sequence - getting it on DROP, also got it on create_distributed_table once).

**Comment by mtuncer** [comment]
Apparently this does not go away even if connection is closed an a new backend is opened.
by scenario was
- begin transaction
- bunch of ddl/dml/select queries
- abort transaction
- create a reference table --> error

**Comment by mtuncer** [comment]
when this happened, pg_ctl was unable to shutdown postgres.

**Comment by johnzw89** [comment]
Hi,
Is there a work-around for this? I am trying to run citus locally for tests and am running into this issue as well:

`-- execute("SELECT create_distributed_table($$item_watcher_iw_updates$$, $$user_id$$)")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::ActiveSqlTransaction: ERROR:  cannot establish a new connection for placement 67, since DDL has been executed on a connection that is in use
: SELECT create_distributed_table($$item_watcher_iw_updates$$, $$user_id$$)
`
I am using Rails and running migrations.

**Comment by marcocitus** [comment]
@johnzw89 you should run `create_distributed_table` through the same database user that created the table.

**Comment by johnzw89** [comment]
@marcocitus I have a bunch of Rails migrations which generate the sql statements, and I'm not sure which user is running create_distributed_table. Would the role just be "citus" ?

**Comment by cyxgun** [comment]
We see this infrequently, but regularly in our unit tests and are tracking it (internal issue 3010); we haven't seen it reproduce in the same test twice, yet.  Our tests are currently running with 16 processes in parallel, so it seems like a race condition in our case, as we see it maybe every hundredth time or so.  Each test stands up it's own database, so maybe enough of them have to be issuing the create_distributed_table call at the same time?  Perhaps I'll create a focused unit test that attempts to provoke it.

**Comment by cyxgun** [comment]
I was able to reproduce this on 7.5.3...

**Comment by cyxgun** [comment]
I reproduced this with Postgres log level "debug5" and have the trimmed logs with the error and context, about 3.5MB compressed.  Attached (zip file with tar-gz  file within).
[logs.zip](https://github.com/citusdata/citus/files/2699675/logs.zip)

**Comment by mtuncer** [comment]
I can't reproduce with current master branch.

**Comment by marcocitus** [comment]
Fixed by https://github.com/citusdata/citus/pull/2486
