### ISSUE TITLE
Masterless: Propagate metadata changes to all nodes

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#19]
We need to propagate metadata changes to all nodes. That is, when the user creates a distributed table or creates new shards for that distributed table, we need to propagate these changes to all nodes in the cluster. For this, we could use the 2PC protocol built-into Postgres or pg_paxos.

**Comment by sumedhpathak** [comment]
@ozgune Should we close this issue in this repo?

**Comment by sumedhpathak** [comment]
Removing 5.2 release tag from this issue. Keeping issue as open however to validate we've captured content in the other repo.

**Comment by ozgune** [comment]
Now that we have #744 integrated, I'm closing this issue.
