### ISSUE TITLE
Implement function that prints a stack trace when a Postgres process segmentation faults

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#191]
Implement function that prints a stack trace when a Postgres process segmentation faults. This function will aid in debugging and can be specific to a particular platform (Linux). We can also solve this problem by integrating Google's crash reporting library (google-breakpad) to PostgreSQL.

**Comment by ozgune** [comment]
I think this issue and #3979 are duplicates. The issue description in #3979 is more comprehensive, so I'm closing this issue in favor of the other one.
