### ISSUE TITLE
Pushdown CTEs

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#1914]
Citus 7.2 supports CTEs by recursively planning each CTE, pulling&pushing the results back to the workers.

In some cases, the CTE can be pushdownable and we could enable CTE pushdown via query pushdown (#1706) which might be much more efficient than pulling the results to the coordinator and pushing it back.

An example query:
```SQL
WITH cte AS
(
    SELECT users_table.value_1
    FROM users_table, events_table
    WHERE users_table.user_id = events_table.user_id
    AND event_type = 5

)

SELECT * FROM cte LIMIT 5;

DEBUG:  generating subplan 15_1 for CTE cte: SELECT users_table.value_1 FROM public.users_table, public.events_table WHERE ((users_table.user_id = events_table.user_id) AND (events_table.event_type = 5))
DEBUG:  Plan 15 query after replacing subqueries and CTEs: SELECT value_1 FROM (SELECT intermediate_result.value_1 FROM read_intermediate_result('15_1'::text, 'binary'::citus_copy_format) intermediate_result(value_1 integer)) cte LIMIT 5
```

The above query is safe to pushdown, so should be pushdownable by Citus.

**Comment by marcocitus** [comment]
This is implemented by inlining the CTE as a subquery when possible.
