### ISSUE TITLE
Need a warning for distributing a table when there is an invalid worker

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus#1922]
It seems like there is a problem related to cache invalidation.
Let's assume we are connected to psql and have a working cluster with 2 workers and a master. Such as;

```SQL
postgres=# select * from master_get_active_worker_nodes();
 node_name | node_port
-----------+-----------
 localhost |      9701
 localhost |      9702
```

It is trivial to just distribute a table in this step. So let's do it.
```SQL
postgres=# create table a (i int);
CREATE TABLE
Time: 7.164 ms
postgres=# select create_distributed_table('a', 'i');
 create_distributed_table
--------------------------

(1 row)
```

And let's add another worker node with an invalid name or port such as
```SQL
postgres=# select master_add_node('node-name', 5432);
                 master_add_node
--------------------------------------------------
 (4,4,node-name,5432,default,f,t,primary,default)
(1 row)

postgres=# select * from master_get_active_worker_nodes();
 node_name | node_port
-----------+-----------
 localhost |      9701
 localhost |      9702
 node-name |      5432
(3 rows)
```

Here, the nodes in localhost are available but not the `node-name`. If we create and distribut a table, it is automatically created in the other workers (if there is any) without giving any warnings about the availability of the invalid node.

```SQL
postgres=# create table b (i int);
CREATE TABLE
Time: 4.041 ms
postgres=# select create_distributed_table('b', 'i');
 create_distributed_table
--------------------------

(1 row)

Time: 28.186 ms
postgres=# select * from pg_dist_shard_placement ;
 shardid | shardstate | shardlength | nodename  | nodeport | placementid
---------+------------+-------------+-----------+----------+-------------
  102052 |          1 |           0 | localhost |     9701 |          45
  102054 |          1 |           0 | localhost |     9701 |          47
  102056 |          1 |           0 | localhost |     9701 |          49
  102058 |          1 |           0 | localhost |     9701 |          51
  102053 |          1 |           0 | localhost |     9702 |          46
  102055 |          1 |           0 | localhost |     9702 |          48
  102057 |          1 |           0 | localhost |     9702 |          50
  102059 |          1 |           0 | localhost |     9702 |          52
(8 rows)

``` 

It seems like the problem is related to cache invalidation because a restart of psql after adding the invalid node caused the warning.
  
The behavior is the same for 7.1 and later. We had a crash problem in 7.0 in the same scenario but it is already resolved.

**Comment by onderkalaci** [comment]
>  If we create and distribut a table, it is automatically created in the other workers (if there is any) without giving any warnings about the availability of the invalid node.

Well, that's kind of expected. We're creating co-located tables automatically with the existing nodes. If you create the table in a different co-location group, you'd see errors such as:
```SQL
 create table c (i int);

-- force different colocation group
 set citus.shard_count TO 15;

 select create_distributed_table('c', 'i');
WARNING:  connection error: node-name:5432
DETAIL:  could not translate host name "node-name" to address: nodename nor servname provided, or not known
ERROR:  connection error: node-name:5432
DETAIL:  could not translate host name "node-name" to address: nodename nor servname provided, or not known
```

> It seems like the problem is related to cache invalidation because a restart of psql after adding the invalid node caused the warning.

How is that happening? I don't see such behaviour. I consistently get the behaviour that I posted here.

**Comment by furkansahin** [comment]
>Well, that's kind of expected. We're creating co-located tables automatically with the existing tables on the nodes that are used previously. If you create the table in a different co-location group, you'd see errors such as:

Agreed, I missed the co-location point and just assumed that we have to use the added node.

>How is that happening? I don't see such behaviour. I consistently get the behaviour that I posted here.
This was diagnosed by @metdos but obviously there was some build related issue or such. Maybe he can clarify if he can reproduce the same behavior. I get the same behavior with you too. If not, can you please close this issue @metdos

**Comment by metdos** [comment]
Ohh, I also forget about the colocation. Most likely, I also changed my shard count in the existing psql connection, so the second time I connected, it tried to create a new table in a different colocation group. It seems like this is not a problem.
