### ISSUE TITLE
Tutorial Issue

### ISSUE THREAD

**Issue by syukur91** [citusdata/citus#1924]
I've followed the tutorial and there are some question when I run the tutorial with docker image ```citusdata/citus:7.1.1```

1.  When I run ```SELECT create_distributed_table('companies', 'id');```
the master said there are no worker node in the cluster so I have to add it manually with this 
```SELECT * from master_add_node('10.10.100.158', 5441);```
with that, I can do create_distributed_table to all of my worker, do I have to do that manually? 

2. When I tried to execute the script which my own schema and there is database on top of it
and then I tried to distribute the table as well, but it said there's no ```create_distributed_table function```, what should I do?

3. I tried to rebalance the new node with this ```SELECT rebalance_table_shards('companies');``` but it return ```ERROR:  function rebalance_table_shards(unknown) does not exist``` is it only exist in citus enterprise?

**Comment by syukur91** [comment]
Here's my own script that I talked about 
[backup.sql.zip](https://github.com/citusdata/citus/files/1599395/backup.sql.zip)

**Comment by metdos** [comment]
@syukur91 we use issues to track core features and bugs, I see you also already commented on the Slack channel which is a better place for this kind of questions.

1. Probably there is a problem with Docker membership
2. It seems Citus extension is not installed
3. It only exists in citus enterprise and Citus Cloud

Best
