### ISSUE TITLE
Help for query

### ISSUE THREAD

**Issue by sm2017** [citusdata/citus#1927]
If I run the following query 

```sql
SELECT "room_member"."roomId"  FROM "room_member"
LEFT JOIN "room" ON ("room_member"."roomId" = "room"."id")
LEFT JOIN "room_message" ON ("room_message"."roomId" = "room"."id")
WHERE 
(
	"room"."type" = 0 OR "room_member"."leftAt" IS NULL
	OR
	"room_message"."id" < (EXTRACT(EPOCH FROM "leftAt") * 10000000 + 9999999)
)
AND
"userId"='3' AND "display"=1
GROUP BY "room_member"."roomId","room_member"."pinVersion"
ORDER BY "room_member"."pinVersion" DESC , MAX("room_message"."id") DESC  LIMIT 40
```

The following error occured

```
[2018-01-03 20:48:28] [0A000] ERROR: cannot perform distributed planning on this query
[2018-01-03 20:48:28] Detail: Shards of relations in outer join queries must have 1-to-1 shard partitioning
```

But the following works 

```sql
SELECT "room_member"."roomId"  FROM "room_member"
LEFT JOIN "room" ON ("room_member"."roomId" = "room"."id")
LEFT JOIN "room_message" ON ("room_message"."roomId" = "room"."id")
WHERE 
"room_message"."roomId" = "room"."id"
AND
(
	"room"."type" = 0 OR "room_member"."leftAt" IS NULL
	OR
	"room_message"."id" < (EXTRACT(EPOCH FROM "leftAt") * 10000000 + 9999999)
)
AND
"userId"='3' AND "display"=1
GROUP BY "room_member"."roomId","room_member"."pinVersion"
ORDER BY "room_member"."pinVersion" DESC , MAX("room_message"."id") DESC  LIMIT 40
```

The issue is , when I explain query `Task Count` is 128

`shard_count` for `room_member` (by `roomId`) and `room` (by `id`) is 16 and for `room_message` (by `roomId`) is 128 , I need to optimize query to set `Task Count` 16 (or minimium count)

How can I do this ?

The query has 3 part , One is get all record for ` "userId" = '3'` from `room_member` that is in 16 shard , but when we solve it we have `"room_member"."roomId"` and it is not needed to scan all 128 shards of `room_message` because it is sharded by  "room_message"."roomId" and it is equal to  "room_member"."roomId"  and  "room"."id"

**Comment by onderkalaci** [comment]
Hey @sm2017,

We reply these kinds of questions on our Slack channel or Citus users group as mentioned on our github [repo](https://github.com/citusdata/citus#talk-to-contributors-and-learn-more). We use github more for bug reports and feature requests.


Thanks!
