### ISSUE TITLE
Citus returns incorrect results if you kill a worker while it's running a router-executor query

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#1942]
I have a table with a bunch of rows in it:

```
brian=# SELECT min(b), pg_sleep(5) FROM copy_perf WHERE a = 1;
              min               | pg_sleep 
--------------------------------+----------
 randomdatarandomdatarandomdata | 
(1 row)
```

If, midway through running the above query, I kill the relevant worker:

`bin/pg_ctl -D data/worker2 stop -m immediate`

I instead get this incredibly wrong output:

```
brian=# SELECT min(b), pg_sleep(5) FROM copy_perf WHERE a = 1;
 min | pg_sleep 
-----+----------
(0 rows)
```

We don't throw any kind of error or even a warning!

**Comment by pykello** [comment]
Maybe related to https://github.com/citusdata/citus/issues/1926?

**Comment by lithp** [comment]
Yep, this appears to be the same bug as found in #1926.
