### ISSUE TITLE
Build problem on FreeBSD

### ISSUE THREAD

**Issue by infracaninophile** [citusdata/citus#1958]
FreeBSD needs to include <sys/stat.h> for the S_IRUSR and S_IWUSR #defines:
```
--- src/backend/distributed/executor/multi_real_time_executor.c.orig    2018-01-17 22:05:28 UTC
+++ src/backend/distributed/executor/multi_real_time_executor.c
@@ -20,6 +20,7 @@
 #include "miscadmin.h"

 #include <unistd.h>
+#include <sys/stat.h>

 #include "access/xact.h"
 #include "commands/dbcommands.h"
```

**Comment by ozgune** [comment]
@pykello / @lithp -- I know you're working on portability to other platforms. How easy is it to incorporate this change?

**Comment by pykello** [comment]
@ozgune PostgreSQL includes `<sys/stat.h>` in many files, so this is safe to include and shouldn't create any portability problems. Also, these constants are actually from the `<sys/stat.h>` header, so we should include them here.

I'll create a PR for this.

**Comment by pykello** [comment]
... and we have included it in other places where we used `S_IRUSR` or `S_IWUSR`. This was the only exception.

**Comment by jasonmp85** [comment]
Yeah, we've had the exact same issue elsewhere before, IIRC (leading to a previous FreeBSD problem). I'll review this real quick.
