### ISSUE TITLE
In terms of partitioning pruning, the MRA paper introduces the logical QSL operator. This QSL operator is not distributive with MJN. However, if we distribute QSL and then apply it (Theorem 10), we are fine

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#196]
In terms of partitioning pruning, the MRA paper introduces the logical QSL operator. This QSL operator is not distributive with MJN. However, if we distribute QSL and then apply it (Theorem 10), we are fine. Do we foresee a problem with partition and join pruning here? If we do, does it apply to inner joins as well?

**Comment by ozgune** [comment]
I think our distributed planning logic changed quite a bit since this issue was opened. I'm closing it for that reason
