### ISSUE TITLE
Query become slow when COPYING data into Citus

### ISSUE THREAD

**Issue by PatrickYung** [citusdata/citus#1987]
Citus Version: 7.2.0
PG Version: 9.6.2
master nodes: 10 physical cores and 192G RAM, HDD
data nodes: 8 physical cores and 192G RAM, HDD

We have a cluster with 1 master node and 8 work nodes. Usually the query is round trip is 2~3 seconds. And we have a spark program to import data using COPY function. We noticed that when Spark is inserting data into the cluster, the query would be stuck! 

According to https://docs.citusdata.com/en/v7.2/performance/scaling_data_ingestion.html

> Note
To avoid opening too many connections to worker nodes, we recommend running only **two** COPY commands on a distributed table at a time. In practice, running more than four at a time rarely results in performance benefits. An exception is when all the data in the ingested file has a specific partition key value, which goes into a single shard. COPY will only open connections to shards when necessary.

We reduce the number of connection to two on each Spark program, and the query would not be stuck while still spending more then 1 min to finish. After COPY finished, the query would be finished in seconds again.

We have check the master and data node's cpu/vm/io stat, nothing abnormal found.

**Comment by metdos** [comment]
What types of queries are you running? And could you check pg_locks if they are blocked on the COPY command?

**Comment by PatrickYung** [comment]
I am running some simple select query without joining. In pg_locks, only below records found for the tables being copied.
![image](https://user-images.githubusercontent.com/21700237/35625290-c41b3e48-06cc-11e8-92c1-ae96f926efa9.png)

**Comment by metdos** [comment]
Are you sure that you're not bottlenecked on the IO?

**Comment by PatrickYung** [comment]
Hi metdos,

Here are some iostat of the nodes when query slow.  

Master Node:
```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.17    0.00    0.06    0.13    0.00   99.64

Device:            tps    MB_read/s    MB_wrtn/s    MB_read    MB_wrtn
sdb              48.13         3.25         3.14   24756936   23958444
```

One of the workers:

```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.15    0.00    0.05    0.04    0.00   99.77

Device:            tps    MB_read/s    MB_wrtn/s    MB_read    MB_wrtn
sdb              24.94         1.12         1.44    4866732    6278877
```

Here are some action we took today but didn't help:
1. set the share_buffer to 1/4 of total RAM, saying 64G.
2. setup another master node for select query only.

**Comment by PatrickYung** [comment]
Problem fixed by setting shared_buffer as 1/4 of physical RAM.
Before setting: RAM usage of checkpoint process is 77% (as captured below)
After : RAM usage of checkpoint process is 20%.
![image](https://user-images.githubusercontent.com/21700237/35725529-9ea9d824-083c-11e8-816a-1e383f85b17b.png)
