### ISSUE TITLE
could not run distributed query because the window function that is used cannot be pushed down

### ISSUE THREAD

**Issue by kxjhlele** [citusdata/citus#1992]
ERROR: could not run distributed query because the window function that is used cannot be pushed down HINT: Window functions are supported in two ways. Either add an equality filter on the distributed tables' partition column or use the window functions inside a subquery with a PARTITION BY clause containing the distribution column

citus: 7.2
SELECT create_distributed_table('info', 'id');

select sdate, id
lead(e_id) over(PARTITION BY id ORDER BY btime) n_msisdn,
lead(btime) over(PARTITION BY id ORDER BY btime) n_time
from info
where sdate >= '2018-1-10' and sdate <= '2018-1-17' and roam = 0

**Comment by metdos** [comment]
Related to #52, closing this.

**Comment by furkansahin** [comment]
Hey @kxjhlele! Thanks for the issue.
We are aware of the problem and currently working to support window functions fully. However, as I can see, your query is also supportable, if you can rewrite it as following;
```SQL
SELECT * FROM (
select sdate, id,
lead(e_id) over(PARTITION BY id ORDER BY btime) n_msisdn,
lead(btime) over(PARTITION BY id ORDER BY btime) n_time
from info
where sdate >= '2018-1-10' and sdate <= '2018-1-17' and roam = 0) a;
```

Here, I assume your table `info` is distributed on `id`. You can also make this query work without subquery if you are interested in a specific id such as;
``` SQL
select sdate, id,
lead(e_id) over(PARTITION BY id ORDER BY btime) n_msisdn,
lead(btime) over(PARTITION BY id ORDER BY btime) n_time
from info
where sdate >= '2018-1-10' and sdate <= '2018-1-17' and roam = 0 and id = 5;
```
Note that I added a new filter to the where clause as **``` and id = 5 ```**

**Comment by kxjhlele** [comment]
thx, 

Note that window functions are supported for SELECT queries that, based on filter conditions, hit a single shard, co-located shards, and/or reference tables, but not for SELECT queries that hit multiple shards.
