### ISSUE TITLE
Table size functions open a new connection on every call

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#2004]
Users with a lot of distributed tables may experience issues when running a query like `SELECT logicalrelid, pg_size_pretty(citus_total_relation_size(logicalrelid)) FROM pg_dist_partition` because the size functions open up a new connection on every call.

`DistributedTableSize` uses a FORCE_NEW_CONNECTION flag, meaning it always opens a new connection. We probably just need to remove that flag.

**Comment by saicitus** [comment]
+1, saw it with another customer.

**Comment by ozgune** [comment]
@metdos -- How long do you think this issue would take?
