### ISSUE TITLE
documentation for run_command_on_shards() doesn't match example

### ISSUE THREAD

**Issue by taybin** [citusdata/citus#2014]
https://docs.citusdata.com/en/v7.2/extra/query_propagation.html#running-on-all-shards

The documentation says:
> Notice the %I which will be replaced with each shard’s name.

but the example code uses `%s`

This also makes the documentation for `run_command_on_colocated_placements()` confusing because it uses both `%s` and `%I` and doesn't explain which is for which table.

**Comment by ozgune** [comment]
Hey @taybin -- Thank you for reporting this issue. I opened up a sister issue in our [Citus documentation repo](https://github.com/citusdata/citus_docs/issues/617).

I'm planning to close the issue in the Citus repo and track the issue in the Citus documentation repo. If that doesn't work, could you let us know?
