### ISSUE TITLE
When disable worker node,  failed create distributed table by column of text type

### ISSUE THREAD

**Issue by zxs** [citusdata/citus#2025]
postgres=# select * from  master_get_active_worker_nodes();
 node_name | node_port 
-----------+-----------
 jy3x137   |     54200
 jy3x136   |     54200
 jy3x135   |     54200
 jy3x134   |     54200
(4 rows)

postgres=# CREATE TABLE companies (
postgres(#     id bigint NOT NULL,
postgres(#     name text NOT NULL,
postgres(#     image_url text,
postgres(#     created_at timestamp without time zone NOT NULL,
postgres(#     updated_at timestamp without time zone NOT NULL
postgres(# );
CREATE TABLE

postgres=# SELECT create_distributed_table('companies', 'id');
 create_distributed_table 
+--------------------------
(1 row)

postgres=# drop table companies;
DROP TABLE

postgres=# CREATE TABLE companies (
postgres(#     id bigint NOT NULL,
postgres(#     name text NOT NULL,
postgres(#     image_url text,
postgres(#     created_at timestamp without time zone NOT NULL,
postgres(#     updated_at timestamp without time zone NOT NULL
postgres(# , primary key(id, name));
CREATE TABLE
postgres=# SELECT create_distributed_table('companies', 'name');
WARNING:  connection error: jy3x138:54200
DETAIL:  could not send data to server: No route to host
could not send SSL negotiation packet: No route to host
ERROR:  connection error: jy3x138:54200
DETAIL:  could not send data to server: No route to host
could not send SSL negotiation packet: No route to host
postgres=# SELECT create_distributed_table('companies', 'id');
 create_distributed_table 
+--------------------------
 
(1 row)

**Comment by ozgune** [comment]
Hey @zxs, thank you for reporting this issue.

I have a quick question. After dropping the distributed table (and before creating the table again), could you try disconnecting from the psql prompt and reconnecting? Does that resolve the problem?

@metdos -- Could we try the steps above and see if we can reproduce this issue on our side?

**Comment by zxs** [comment]
I can reproduce this issue , when i disconnecting from the psql prompt and reconnecting :(

**Comment by metdos** [comment]
Hi @zxs, how did you disable the node? I couldn't the related command on your log.

Could you also run this query before calling the failing `create_distributed_table`, and paste results to here?
```sql
select * from pg_dist_node;
```

**Comment by ozgune** [comment]
@metdos -- Can we reproduce this issue on our end?

**Comment by metdos** [comment]
@ozgune, no I can't. @zxs, I'm closing the issue, feel free to open it if you come back with the data I asked.
