### ISSUE TITLE
Remove multi_index_statements_0.out

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#2029]
We needed to add this regression file temporarily. The output of regression tests is changed to due to a change in REL_10_STABLE. On Travis, we use PostgreSQL source files for push build and the Debian packages for PR builds which causes different regression results until Debian packages catch-up with the latest changes on the stable branch.

Here is the PR: #2028 and the related commit: https://github.com/citusdata/citus/pull/2028/commits/91165c41407b4828237941a1623106853f817c5f

**Comment by hanefi** [comment]
@serprex removed said file with
74cb168205efbfdf03b8ba71b1de92154855a7f1
