### ISSUE TITLE
Wrong timezone casting when retrieve data from distributed node.

### ISSUE THREAD

**Issue by chaintng** [citusdata/citus#2040]
![image](https://user-images.githubusercontent.com/2979072/37088379-b9e50d36-222f-11e8-9e63-6212bd0702b6.png)

All node are in Japan timezone (Both server timezone and postgres config)

When casting `::timestamptz`, i expect database to add timezone without changing time.

However, in citus, look like it's transforming the date time.

I feel like it's a bug. So i reported here.

**Comment by onderkalaci** [comment]
There is one thing in the issue description that I couldn't follow. Are the coordinator and the worker nodes have the same timezone settings in Postgresql?

So, when you do the following on both servers, do you see the same timezone?
```
 show timezone;
```

**Comment by chaintng** [comment]
@onderkalaci Yes, all servers in this experiment (postgres, citus coordinator and citus workers) are in same timezone (Japan)

`show timezone;` also show `Japan` in every node.

**Comment by onderkalaci** [comment]
I see, I'm guessing that the data type of `created_at` is `timestamp` not `timestamptz`?

Could you maybe use the following pattern for now?

```SQL
SELECT timezone('Japan', created_at) FROM messages WHERE id = 47 and tenant_id = 2; 
```

**Comment by chaintng** [comment]
The query above is actually come from the library. Changing library query is quite hard.
Anyway, i will try to find the work around. 
I just want to make sure that it would fix in upcoming release.

**Comment by onderkalaci** [comment]
> Yes, the data type is timestamp, no timezone specified.

Hi @chaintng, generally it is recommended** to use `timestamptz` over `timestamp`. Just to understand better your use-case, do you have any special reasons to use `timestamp`?

**[[1]](http://www.craigkerstiens.com/2017/06/08/working-with-time-in-postgres/), [[2]](http://phili.pe/posts/timestamps-and-time-zones-in-postgresql/#why-two-types-of-timestamps)

**Comment by chaintng** [comment]
It's actually default rails data type https://github.com/rails/rails/blob/v4.2.6/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L79..L114

However, don't you think giving difference result between Postgres and Citus is unexpected behavior?

**Comment by mtuncer** [comment]
Hello @chaintng 

We are not able to reproduce the problem with the current information. I suspect that timezone setting in coordinator, and workers might be different in the session.

Could you run following commands in the same session to check the timezone.
```sql
show timezone;
select * from run_command_on_workers('show timezone');
```

**Comment by jasonmp85** [comment]
I've also been looking into this and am completely unable to reproduce if the servers have the same `TimeZone` setting. I don't even really see the same sort of behavior when they don't.

Can you do a quick search of your Rails codebase and tell me what timezone-related settings are configured there?

Additionally, I'd like to know a bit more about your server config. `SHOW TimeZone` will only show the active value for the connection. The following query will help us a bit more:

```sql
SELECT * FROM run_command_on_workers($$SELECT format('boot: %s, reset: %s, value: %s', boot_val, reset_val, setting) FROM pg_settings WHERE name = 'TimeZone'$$);
```

Thanks!

**Comment by jasonmp85** [comment]
Finally, @trickpeeraze and @kaikuchn: I noticed you both :+1:'d this issue. Do you have similar problems? Maybe a repro case we can use?

**Comment by jasonmp85** [comment]
What we're looking for:

  * **CREATE TABLE** statement showing table being created
  * **create_distributed_table** command showing distribution
  * **INSERT** command showing exactly how data was ingested
  * **pg_settings** values for debugging time zone config
  * **SELECT** statement that triggers problem

So far things we've tried on our own (starting workers and coordinator in different time zones, changing time zones for sessions, etc.) haven't turned up much.

**Comment by chaintng** [comment]
I have destroyed that database
And reinstall citus from the same ansible script
However, i cannot reproduce it anymore...

strange. But i think this issue can be closed.

**Comment by onderkalaci** [comment]
> However, i cannot reproduce it anymore...

Seems like a wrong configuration for `timezone` in the workers.

**Comment by trickpeeraze** [comment]
Yes @jasonmp85, but I'm on the same team with @chaintng, So don't worry, I just 'd like to support that this issue need to be investigated more.

And thanks for your help.
