### ISSUE TITLE
Not able to understand NodeRole

### ISSUE THREAD

**Issue by nitishxp** [citusdata/citus#2053]
node_role: Whether it is ‘primary’ or ‘secondary’. Default ‘primary’

what does noderole define in master_add_node() does it means we can add a worker with
primary and secondary to have same shard ? or does it means same thing ?

and can we configure a worker to have its replication mapped to another server?

**Comment by metdos** [comment]
It’s for read-only clusters, and I think this question is answered in the slack channel. Closing this. We use GitHub issues to track bugs and features.
