### ISSUE TITLE
Update of all distributed table column values takes forever

### ISSUE THREAD

**Issue by ssavkovic** [citusdata/citus#2054]
We are evaluating Citus extension for our data analytics load. However, when loading data bumped into an issue.
I have a distributed table with over 980 million rows and over 70 columns. Running update statement like this:
UPDATE common_kpi_stgk SET mgrspoint = ST_SetSRID(ST_MakePoint(lon, lat),4326)
Is taking over 24 hours. The import of the whole table using CSV took less than 12 hours (with COPY command). There is no index on mgrspoint column (removed it before update).
The configuration is one coordinator node and two worker nodes running on Cent OS. The machines use RAID 0 and each has 128 GB of RAM. I can see heavy IO on both worker nodes  (postgres on top) as well as CPU use (postgres on top as well). It looks like this update is very inefficient as there are too many threads hammering different partitions on the same DB and trying to update at the same time. Auto-vacuum running at the same time on the same table likely makes things worse.
From our experience we had similar issue  in our code when we were populating another DB and trying to do it similarly by hammering different tables from multiple threads - the slowdown was terrible. Doing partition by partition in order was way more efficient (less IO).
Please find attached the statistics from one the worker nodes.
![image](https://user-images.githubusercontent.com/14916521/37361101-750c3bce-26c8-11e8-93a2-02c31c97dca0.png)

**Comment by onderkalaci** [comment]
You could try setting the following GUC: `SET citus.multi_shard_modify_mode TO 'sequential';`

**Comment by ssavkovic** [comment]
Thanks, that help to alleviate the problem with worker nodes being overwhelmed. Now, they are responsive while writing the data. However, the performance issue is still there - still over a day to update (not done yet). The problem is that it is not doing it in parallel between nodes, it goes node by node now.
What is even worse the original update attempt silently failed without reporting errors. It claimed that it has finished, but when I checked the data nothing was updated.
BTW What is the original value of citus.multi_shard_modify_mode so I can set it back?

**Comment by lithp** [comment]
@ssavkovic in general you can return postgres GUCs to their default value by running `SET configuration_parameter TO DEFAULT;`.

So you can run `SET citus.multi_shard_modify_mode TO DEFAULT`. 

But, to answer your question, the default is `'parallel'`.

**Comment by onderkalaci** [comment]
> What is even worse the original update attempt silently failed without reporting errors. It claimed that it has finished, but when I checked the data nothing was updated.

@ssavkovic That sounds odd. Could it be a connection timeout such that the transaction `ROLLBACK`ed instead of being `COMMIT`ed? For instance, did you see `UPDATE N` (where `N` is the updated row count) after the transaction finishes?

**Comment by ssavkovic** [comment]
Thanks for all the info!
I've gave up on updating from the coordinator node as the second attempt took more than a day and failed. Updating each worker node separately now (directly, partitioned table by table).

**Comment by onderkalaci** [comment]
> I've gave up on updating from the coordinator node as the second attempt took more than a day and failed. 

What kind of failure is that?

>  Updating each worker node separately now (directly, partitioned table by table).

That seems hard to maintain. How are you going to handle failures on the workers (if happens)?
