### ISSUE TITLE
unsupported aggregate function: mode()

### ISSUE THREAD

**Issue by l-we** [citusdata/citus#2066]
citus 7.3
mode() WITHIN GROUP (ORDER BY sort_expression)
unsupported aggregate function mode

Partition tenant_id 

select sdate, tenant_id, mode() WITHIN GROUP (ORDER BY sort_expression) sort
from table_name
group by sdate, tenant_id

**Comment by ozgune** [comment]
@kxjhlele -- Thank you for reporting this issue.

We currently don't have distributing mode() queries in our roadmap. We will keep this issue open and keep you posted when we prioritize this feature. If you have any questions for us in the meantime, please let us know.

**Comment by serprex** [comment]
#3324 will address this, but suboptimally. We should be supporting aggregate push down when the partition key is being grouped by

**Comment by marcocitus** [comment]
Fixed by #3324
