### ISSUE TITLE
Missing shard min-max values are not supported with single-partition join

### ISSUE THREAD

**Issue by velioglu** [citusdata/citus#2082]
We added co-partition check on local join with [1974](https://github.com/citusdata/citus/pull/1974). So, while planning a join with append tables without min or max value we can not use local join anymore. Since single-partition join logic is the next option in our join order planner code,  it is expected to use that logic if we have a table without min or max value. However, single repartition join does not support shards without min or max value. 

As a solution we may add min-max checks on single-partition logic to use dual-partition join logic instead. 

Note that, in order to preserve out test quality we have changed WHERE clause of [some tests](https://github.com/citusdata/citus/pull/1974/files#diff-e24782f5e9a21c3ac747afe61c6cc415) to use dual-partition logic instead of single partition logic.

**Comment by marcocitus** [comment]
Closed by #5359
