### ISSUE TITLE
2PC recovery might be interfering with active distributed transactions in Citus MX (?)

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#2095]
While working on a large test cluster, we've occasionally observed the following errors on the different worker log files at different times:

The cluster had Citus MX with many worker nodes doing highly concurrent multi-shard commands on 8-9 different distributed tables.

```

ERROR:  prepared transaction with identifier "citus_24_71104_2654_8" does not exist


WARNING:  failed to commit transaction on XXXXX:5432
WARNING:  failed to roll back prepared transaction 'citus_24_65309_836_37'
 HINT:  Run "COMMIT PREPARED 'citus_24_65309_836_37'" on XXXXX:5432



 ERROR:  prepared transaction with identifier "citus_21_63757_589_20" does not exist
[app=citus] STATEMENT:  ROLLBACK PREPARED 'citus_21_63757_589_20'



prepared transaction with identifier "citus_24_21561_24021_24" is busy
STATEMENT:  ROLLBACK PREPARED '

```

Our workaround was just to increase the `citus.recover_2pc_interval` to `30` minutes. After that, all the errors went away. (This obviously cannot be a solution, but mitigate the source of the bug.)

We seem to have a very similar issue in the previous implementation of `recover_prepared_transactions` (e.g., before #1696) and that was fixed with a commit in #1030.

Note: The issue might not be specific to Citus MX, that needs more investigation.

**Comment by onderkalaci** [comment]
I reproduced the issue on 1+12 c5.9xlarge cluster while running tpcb-like pgbench. I had seperate 3 driver nodes during the tests. pgbench options:  `-c 128 -j 64 -b tpcb-like`


```
2018-08-17 08:03:10.844 UTC [10128][18/219] : [3-1] [app=citus] ERROR:  prepared transaction with identifier "citus_11_11544_2633_113" is busy
2018-08-17 08:03:10.844 UTC [10128][18/219] : [4-1] [app=citus] STATEMENT:  COMMIT PREPARED 'citus_11_11544_2633_113'
2018-08-17 08:03:10.845 UTC [10103][5/120] : [5-1] LOG:  recovered a prepared transaction on ec2-18-215-0-141.compute-1.amazonaws.com:5432
2018-08-17 08:03:10.845 UTC [10103][5/120] : [6-1] CONTEXT:  ROLLBACK PREPARED 'citus_11_11544_2633_113'

 [3-1] WARNING:  prepared transaction with identifier "citus_12_10324_639492_203" does not exist

```

Note that all nodes have different local group id such that there is no conflict:
```
 psql postgres://citus:OQLl5lyVVB9PwSkFZJBG-A@c.fxelbk2jq2jhlfh5f5mch26bray.db.citusdata.com:5432/citus?sslmode=require -c "SELECT run_command_on_workers(\$\$SELECT * FROM pg_dist_local_group\$\$)"
                 run_command_on_workers                 
--------------------------------------------------------
 (ec2-18-213-227-244.compute-1.amazonaws.com,5432,t,6)
 (ec2-18-214-218-219.compute-1.amazonaws.com,5432,t,12)
 (ec2-18-214-222-142.compute-1.amazonaws.com,5432,t,9)
 (ec2-18-214-224-134.compute-1.amazonaws.com,5432,t,7)
 (ec2-18-215-0-141.compute-1.amazonaws.com,5432,t,1)
 (ec2-18-215-0-224.compute-1.amazonaws.com,5432,t,3)
 (ec2-18-233-240-132.compute-1.amazonaws.com,5432,t,2)
 (ec2-34-224-109-166.compute-1.amazonaws.com,5432,t,8)
 (ec2-34-225-208-137.compute-1.amazonaws.com,5432,t,11)
 (ec2-34-239-216-65.compute-1.amazonaws.com,5432,t,5)
 (ec2-35-153-125-198.compute-1.amazonaws.com,5432,t,4)
 (ec2-52-72-58-84.compute-1.amazonaws.com,5432,t,10)
(12 rows)
```

**Comment by marcocitus** [comment]
I wonder whether it's due to a race condition where pgbouncer sends the PREPAR over one connection and the COMMIT PREPARED over another, but somehow it cannot see the 2PC identifier yet.

**Comment by onderkalaci** [comment]
I think `prepared transaction with identifier "citus_24_21561_24021_24" is busy` means that the same prepared transaction is being `COMMIT`ed or `ROLLBACK`ed concurrently. To repro it, simple create a prepared transaction `t1`. Later, try to commit it concurrently via pgbench:
```
/usr/local/pgsql/bin/pgbench -j 4 -c 4 -f /tmp/f.sql postgres
client 1 aborted in command 0 of script 0; ERROR:  prepared transaction with identifier "t1" is busy

client 2 aborted in command 0 of script 0; ERROR:  prepared transaction with identifier "t1" is busy

client 3 aborted in command 0 of script 0; ERROR:  prepared transaction with identifier "t1" is busy

client 0 aborted in command 0 of script 0; ERROR:  prepared transaction with identifier "t1" does not exist
```

where f.sql is `'COMMIT PREPARED 't1';'

So, that makes me feel that there is a bug in our 2PC recovery code where we're tryting to `ROLLBACK` or `COMMIT` a transaction at the same time the coordinated transaction is trying to commit/rollback it ?

**Comment by marcocitus** [comment]
I think this query is broken: https://github.com/citusdata/citus/blob/master/src/backend/distributed/transaction/transaction_recovery.c#L423

The underscore has special meaning in the LIKE syntax, so it's matching more than it should:
https://www.postgresql.org/docs/current/static/functions-matching.html

**Comment by marcocitus** [comment]
We should prefix the underscores with backslashes

**Comment by onderkalaci** [comment]
Great catch! I was deep inside in the 2pc recovery code, and couldn't have found any bugs with hours of code reading!

And, that makes it clear why we observe this bug with 10+ worker node 😄 

```SQL
SELECT gid FROM pg_prepared_xacts WHERE gid LIKE 'citus_1_%%';
         gid         
---------------------
 citus_1_29129_2_35
 citus_10_29129_2_35
 citus_11_29129_2_35
(3 rows)
```
