### ISSUE TITLE
Incomplete instruction manual Postgres 10.3 Centos

### ISSUE THREAD

**Issue by Extarys** [citusdata/citus#2110]
I followed those instructions (https://docs.citusdata.com/en/v7.3/installation/single_machine_rhel.html) to the letter but when I log in as postgres and type `psql` I got:

```
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

But port 5432 is not in use since we are using 9700, 9701 and 9702.

Also, creating 2 workers on the same machine, can I eventually split them up to their dedicated machines without too much hassles?

Thanks!

**Comment by onderkalaci** [comment]
Hi @Extarys,

> Also, creating 2 workers on the same machine, can I eventually split them up to their dedicated machines without too much hassles?

[Citus enterprise](https://www.citusdata.com/product/enterprise) and [Citus Cloud](https://www.citusdata.com/product/cloud) has the rebalancing tools (e.g., [`Shard Rebalancer`](https://www.citusdata.com/blog/2017/04/11/rebalancing-your-database-with-citus/)) that could make it easy to move shards around the cluster.

You could potentially implement your tools on top of the community edition as well.

We mostly prefer to discuss these kinds of support issues on the [Slack](https://slack.citusdata.com/) channel. I'm closing the issue, feel free to move the discussion over there!

Thanks
