### ISSUE TITLE
Provide Citus Cloud with "Azure Database for PostgreSQL"

### ISSUE THREAD

**Issue by mkurz** [citusdata/citus#2114]
As of today ["Azure Database for PostgreSQL"](https://azure.microsoft.com/en-us/services/postgresql/) is officially [general available](https://azure.microsoft.com/en-us/updates/azure-database-for-postgresql/). (Another blog post can be found [here](https://azure.microsoft.com/en-us/blog/announcing-general-availability-of-azure-database-services-for-mysql-and-postgresql/).)

Citus Cloud is running on top of AWS right now. Wouldn't it be nice to also provide Azure as a backend (One of our customers uses Azure, that's why I am proposing this.)?

Are there any plans?

**Comment by mkurz** [comment]
@mtuncer thanks for you reply. Right now I don't have the need to talk to your product leadership, however if the need arises I am happy to contact you again, thanks!

However:
Do you actually plan to work with Microsoft and/or Amazon to provide Citus as an official extension? See ["Extensions supported by Azure Database for PostgreSQL"](https://docs.microsoft.com/en-us/azure/postgresql/concepts-extensions#extensions-supported-by-azure-database-for-postgresql) (plus [this UserVoice ticket](https://feedback.azure.com/forums/597976-azure-database-for-postgresql/suggestions/19324003-citus-columnar-datastore)) and ["PostgreSQL Version 10.x Extensions and Modules Supported on Amazon RDS"](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.FeatureSupport.Extensions.101x). If Citus would become an official extension in either Azure or AWS (with or without your help), wouldn't that undermine your efforts of making money by providing your own Citus cloud solution?

**Comment by mtuncer** [comment]
thanks for the comments, I will make sure our product leadership will receive them.

**Comment by ozgune** [comment]
Hey @mkurz -- Thanks for opening up this issue. We'd be happy to have a fifteen minute conversation with you.

Could you send us a message using the link below and mention this issue in your request?

https://www.citusdata.com/about/contact_us

**Comment by canbarisjones** [comment]
Now that citus is part of Microsoft, is there a release date or plans on making it easy to use on Azure, in cunjunction with Azure Database for PostgreSQL?

**Comment by wujysh** [comment]
It will be available soon. https://www.citusdata.com/azure-interest/

**Comment by mkurz** [comment]
Finally, Citus is available as a managed service on Azure:
* https://www.citusdata.com/blog/2019/05/06/introducing-hyperscale-citus-on-azure-database-for-postgres/
* https://azure.microsoft.com/de-de/blog/get-high-performance-scaling-for-your-azure-database-workloads-with-hyperscale/
