### ISSUE TITLE
Propagate ALTER TABLE ... ENABLE ROW LEVEL SECURITY to workers

### ISSUE THREAD

**Issue by mkurz** [citusdata/citus#2125]
The title says it all.
You even published [a blog post](https://www.citusdata.com/blog/2018/04/04/raw-sql-access-with-row-level-security/) a couple of weeks ago focusing on row level security in which you published a workaround:
```sql
SET citus.enable_ddl_propagation to off;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
SET citus.enable_ddl_propagation to on;
SELECT run_command_on_shards('events','ALTER TABLE %s ENABLE ROW LEVEL SECURITY;');
```

Seems like some of the `ALTER TABLE...` subcommands are already supported:
https://github.com/citusdata/citus/blob/v7.3.0/src/test/regress/expected/multi_reference_table.out#L1387-L1388

**Comment by thanodnl** [comment]
The `ALTER TABLE ... ENABLE ROW LEVEL SECURITY` are supported on citus enterprise and citus cloud as part of Fine-grained access controls.

**Comment by mkurz** [comment]
OK. Why this isn't supported in the Community Edition?
Using the Community Edition people can just use
```
SELECT run_command_on_shards('events','ALTER TABLE %s ENABLE ROW LEVEL SECURITY;');
```
instead anway. You even published a [blog post](https://www.citusdata.com/blog/2018/04/04/raw-sql-access-with-row-level-security/) using this approach.

What I don't understand is what is the point of not letting people use the prober command in community edtion, but let them workaround it any?

Another problem I see is if we download Community Edition (lets say the docker images) for local development then we would have to use the `run_command_on_shards` workaround, but when deploying on Citus Cloud we would have to change our scripts (or better: can change our scripts)?

**Comment by mkurz** [comment]
The same with `GRANT`/`REVOKE`, see #2129.
I just don't get why you make it hard for people in the Community edtion to use the prober commands if they can use `run_command_on_xxx` as a workaround anyway?

What do you gain by supporting those commands only in the Cloud/Enterprise version? Like things work now, they are not a explict feature in those Citus offerings if people can still work around it in the Community Edition.

**Comment by marcocitus** [comment]
You are of course free to use the `run_command_on_*` functions or to work around the limitation. We never prevent you from doing things directly in Postgres and anything that works in the open source version will work in Cloud/Enterprise.

Features like user management and access controls give added value to Cloud/Enterprise customers without restricting the functionality of the open source edition. Supporting the DDL commands directly gives better integration with tools like pgAdmin, but more importantly preserves the settings if you run the shard rebalancer in cloud/enterprise. 

We appreciate your feedback on adding these feature to the open source repo. We'll continue to re-evaluate which features should be in enterprise vs. open source and may reconsider in the future.

**Comment by mkurz** [comment]
@marcocitus Thanks for you reply! Having spent some time trying out citus via the provided docker images and reading most of the docs for me it just seems kind of weird to use `run_command_on_*` in order to run `GRANT`/`REVOKE`/`ENABLE ROW LEVEL SECURITY`/... when you already have that implemented in your Cloud and Enterprise offerings anyway.

Look at it this way:
I am not going to buy your Cloud or Enterprise offering thinking "cool now I can use that commands!" but rather think why do you even hold them back? You don't offer anything new I already can achieve via the `run_command_on_*` commands anyway. (I am rather buying your commercial offerings because of HA, rebalancing, etc.).

And again, I want to emphasize that I think by holding those commands back you just make it harder for people to migrate to your Cloud or Enterprise offerings since most of the time people start by downloading the Community Edition (most likely the docker images) and start implementing/migrating their schemas on their machines before even buying your Citus cloud "dev" plan for 99 USD. If, after working on migrating my schema to Citus community edtion locally offline, figure out that after buying one of your commercial offerings have to/can use those commands and have to/can change my SQL scripts I am really start to think: wtf, why now???

My personal conclusion:
**I think in your commercial offerings you should focus on things like HA, rebalancing, tenant isolation, etc. - THAT is what the people really want to pay for - not to just have some commands available they can work around anyway.
Just support the same set of SQL commands across all versions to make it easy for people to migrate to your commercial offerings!** (Except of course the functions for rebalancing, etc. you explicitly offer in your commerical versions)

Just my 2 cents :smile:
