### ISSUE TITLE
Propagate GRANT/REVOKE in Citus Community edition

### ISSUE THREAD

**Issue by mkurz** [citusdata/citus#2129]
Hi!

If I run simple `GRANT` or `REVOKE` commands on distributed or reference tables these commands won't be propagated to the workers. Instead I have to use `run_command_on_shards` and/or `run_command_on_placements` to propagate my `GRANT` or `REVOKE` commands.

However it seems that in Citus cloud and your enterprise offering you do propagate these commands.
E.g. in [this docs](https://docs.citusdata.com/en/v7.3/cloud/security.html#granting-privileges-in-bulk), which apply to Citus cloud, you write:
> Citus propagates single-table GRANT statements through the entire cluster, making them apply on all worker nodes.

I also found [this commit](https://github.com/citusdata/citus/commit/2cb34406d1581ba623fcab2188d624686865a275) where you "turn off propagation to avoid Enterprise processing a section" - which also leads me to the assumption that you do offer this feature for your Citus cloud and enterprise customers.

Why? What's the point of not letting people propagate `GRANT`/`REVOKE` in the open source edition even when you can simply workaround that limitation by just using `run_command_on_xxx`?

**Comment by ozgune** [comment]
Hi @mkurz -- Thank you for your feedback.

I also read over your comments in #2125. We understand that not supporting these commands in Citus Community Edition makes migrating harder, particularly for customers who start by testing the open source version. That said, Citus Data customers have diverse profiles. Some of them start by testing directly on our Cloud and Enterprise offerings.

We earlier made a decision to natively provide fine-grained access controls as part of our Cloud and Enterprise solutions. So I'm closing this issue.

Thank you again for providing your feedback. If you have other comments / questions, happy to chat more about them over Slack or email.
