### ISSUE TITLE
run_command_on_xxx is not transaction aware

### ISSUE THREAD

**Issue by mkurz** [citusdata/citus#2131]
Run this script step for step on the coordinator:
```sql
BEGIN; -- start transaction

CREATE TABLE my_table (
    my_col INT
);

SELECT create_reference_table('my_table'); -- waits for COMMIT before sending to workers
-- after the above query there are no my_table shards on the workers yet, perfect!

SELECT run_command_on_placements('my_table', $cmd$ -- immediately fails :-(
    CREATE FUNCTION foo_func () RETURNS INT AS $$
        SELECT my_col FROM %s;
    $$ LANGUAGE sql;
$cmd$);

COMMIT; -- end transaction
-- now the my_table shards on the workers got created, perfect!

```
When you run the `run_command_on_placements(...)` command you will get following error:
```
                              run_command_on_placements                               
--------------------------------------------------------------------------------------
 (citus_worker_1,5432,102009,f,"ERROR:  relation ""my_table_102009"" does not exist")
 (citus_worker_2,5432,102009,f,"ERROR:  relation ""my_table_102009"" does not exist")
 (citus_worker_3,5432,102009,f,"ERROR:  relation ""my_table_102009"" does not exist")
(3 rows)
```
That's because `CREATE FUNCTION` will be send to the workers immediately and not when the transaction gets commited, meaning at the time the `CREATE FUNCTION` stmt is executed on the workers the `my_table_xxx` shards have not been created yet (because `create_reference_table` works fine and postpones its execution after the `COMMIT`).
`create_reference_table` however works fine, on the workers the table shards will be created after the `COMMIT`.
I didn't test with the other `run_command_on_xxx` methods, however I would guess they have the same problem.

**Comment by mtuncer** [comment]
@mkurz that is correct. They were not transaction aware, and they won't be.

**Comment by mkurz** [comment]
@mtuncer Alright, so this is by design? So I would have to commit after
```
SELECT create_reference_table('my_table');
```
Or is there another approach/workaround?

**Comment by mtuncer** [comment]
correct, in order for them to see the worker shards, transaction that created them must be committed first.

**Comment by mtuncer** [comment]
Please remember the comment in [docs](https://docs.citusdata.com/en/v7.3/develop/reference_propagation.html). When you deal with ```run_command_on_xxx``` commands.

> Manual query propagation bypasses coordinator logic, locking, and any other consistency checks. These functions are available as a last resort to allow statements which Citus otherwise does not run natively. Use them carefully to avoid data inconsistency and deadlocks.

**Comment by mkurz** [comment]
Alright, I understand. I will close this issue.
Thanks!

**Comment by mkurz** [comment]
@mtuncer Just one question left:

I tested and it is actually possible to run multiple commands inside one `run_command_on_xxx` query:
```
SELECT run_command_on_workers($cmd$
    CREATE FUNCTION foo ()...; -- first
    CREATE FUNCTION var ()...; -- second
    CREATE FUNCTION xyz ()...; -- third statement
$cmd$);
```
Can I trust this behaviour because I think this isn't documented and also the commands are called `run_command_xxx` and not `run_commands_` (see the "s").
Or is it ok to use it like this?

**Comment by mtuncer** [comment]
that's my bad. it is ```run_command_``` without ```s```

we do not support sending multiple statements within a single ```run_command``` call, however, we did not prevent it either.

Please exercise caution when you are using this commands. You can easily get your cluster in to a bad state.

**Comment by mkurz** [comment]
> we do not support sending multiple statements within a single `run_command` call, however, we did not prevent it either.

OK, but it works, so I will use it ;) I will test everything on a test setup anyway.

**Comment by mkurz** [comment]
How about introducing `run_commands_xxx` which officially supports multiple statements? :smile:
