### ISSUE TITLE
Consider removing deprecated UDFs/GUCs when planning for a major version upgrade

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#2146]
There are a good number of deprecated UDFs and GUCs that we should consider removing:

Some of the ones that I can remember:

* `master_create_distributed_table()` - `master_create_worker_shards()`
* `master_modify_multiple_shards()`
* `citus.expire_cached_shards`
* `citus.large_table_shard_count`
* `worker_hash_partition_table(bigint, integer, text, text, oid, integer)` (old api)

I bet there should be more. Anything to add?

**Comment by mtuncer** [comment]
While we are on that we can also get a baseline for ```citus--8.0.sql``` and get rid of re-declarations of functions. That means getting rid of ```citus--8.0.sql``` and the files depend on it.

**Comment by velioglu** [comment]
We may also remove `mark_tables_colocated()`

**Comment by onderkalaci** [comment]
Not forget the too old UDF: `create_insert_proxy_for_table `

**Comment by marcocitus** [comment]
citus.enable_deadlock_prevention is not deprecated, it is used to relax the locking on multi-shard DML.

**Comment by metdos** [comment]
@agedemenli anything remained for Citus 10? If not shall we close the issue, or remove the milestone to keep track of removing them in the future?

**Comment by agedemenli** [comment]
`worker_hash_partition_table` still exists. I don't know if we should consider remove it. Maybe we can discuss it.

**Comment by metdos** [comment]
We're done with changes here, we will open new issues if required.
