### ISSUE TITLE
create extension error

### ISSUE THREAD

**Issue by qianxiansheng90** [citusdata/citus#2174]
env:
PostgreSQL-10.1
CentOS7.1
citus-7.4
compile citus-7.4.tar.gz,not rpm.

[local]:54333 postgres@postgres=# \dn+ pg_catalog
List of schemas
-[ RECORD 1 ]-----+----------------------
Name              | pg_catalog
Owner             | postgres
Access privileges | postgres=UC/postgres +
                  | =U/postgres
Description       | system catalog schema

when I install citus,but I got error;

CREATE EXTENSION citus with schema public ;
ERROR:  extension "citus" must be installed in schema "pg_catalog"
Time: 2.928 ms

create extension citus with schema pg_catalog;
ERROR:  no schema has been selected to create in
Time: 497.119 ms

**Comment by onderkalaci** [comment]
That seems like a minor bug. 

You should simply be able to create the extension with `CREATE EXTENSION citus;` which creates the extension in `pg_catalog` by default.

**Comment by qianfangyuan** [comment]
thanks
