### ISSUE TITLE
Marking reference table shard as unhealthy

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus#2179]
We got reported that in a mysterious case, we mark a shard of a reference table as unhealthy. Normally, we do use 2pc for DDL/DML operations around reference table and we use a flag called `stopOnFailure` to not mark a specific connection failed so that we wouldn't mark the shard unhealthy in the metadata. In a very rare occasion this is not true.

See the mail with `Shard of a reference table marked inactive` header.

In case we hit such a problem. It should be fixed in either one of these two ways;
1- using upgrade_to_reference_table('TABLE_NAME');
This solution requires superuser access and we will a little mess around the metadata. 
Note: The moment upgrade_to_reference_table is called, all of the updates are going to be blocked but select may continue.
```
begin;
update pg_dist_shard set shardmaxvalue = 2147483647, shardminvalue=-2147483648 where logicalrelid='TABLE_NAME'::regclass;
update pg_dist_partition set partmethod='h', partkey='{VAR :varno 1 :varattno 1 :vartype 23 :vartypmod -1 :varcollid 0 :varlevelsup 0 :varnoold 1 :varoattno 1 :location -1}' where logicalrelid='TABLE_NAME'::regclass;
select upgrade_to_reference_table('TABLE_NAME');
commit;
```

2- create local table and distribute as a reference table.

The advantage of this solution is that the user him/herself can directly apply but requires data fetching to the coordinator and broadcasting back. On the other side, the moment DROP TABLE is called, all of the queries are going to be blocked on this table until commit.

```
begin;
CREATE TABLE table2 AS SELECT * FROM table_name;
DROP TABLE table_name;
ALTER TABLE table2 RENAME TO table_name;
SELECT create_reference_table('table_name');
commit;
```

**Comment by marcocitus** [comment]
This may be triggered by rolling back to a savepoint after a failure (e.g. exception handler in a function call) and then continuing with other commands.

```sql
BEGIN;                                            
SAVEPOINT start;
INSERT INTO ref VALUES (1001,2);
-- stop worker 2

SELECT * FROM ref;
ROLLBACK TO SAVEPOINT start;
SELECT * FROM ref;
END;
SELECT logicalrelid, shardid FROM pg_dist_shard JOIN pg_dist_placement USING (shardid) WHERE shardstate = 3;
┌──────────────┬─────────┐
│ logicalrelid │ shardid │
├──────────────┼─────────┤
│ ref          │  102040 │
└──────────────┴─────────┘
(1 row)
```

**Comment by onderkalaci** [comment]
One way to fix it, which may require some more thought: https://github.com/citusdata/citus/compare/fix_ref_table?expand=1#diff-d876ba5a2a127211fd1758f470621e5cL1035

Some comments:
```
>  Maybe let's think a little bit more, because I'm not  very confident yet if this the right fix -- though it fixes the steps you've shared

[1/6 2:53 PM] Marco Slot
    is the connection failed+critical?
​[1/6 2:53 PM] Marco Slot
    perhaps we should error out pre-commit if such a connection exists?
​[1/6 2:54 PM] Marco Slot
    not sure if the notion of "critical" still means what I think it means
​[1/6 2:59 PM] Onder Kalaci
    
On the failed node,  `MultiConnection *connection = primaryConnection->connection;`  is `NULL` in `CheckShardPlacements()`

hmm Adaptive executor closes that at the end  of  the execution: https://github.com/citusdata/citus/blob/master/src/backend/distributed/executor/adaptive_executor.c#L1505-L1521
because the state is `MULTI_CONNECTION_FAILED`

On the failed node,  `MultiConnection *connection = primaryConnection->connection;`  is `NULL` in `CheckShardPlacements()`
[1/6 3:12 PM] Marco Slot
    hmz, I remember some bugs related to CloseConnection vs. ShutdownConnection 
​[1/6 3:13 PM] Marco Slot
    I guess we do want to remember this connection, though we need to make sure we don't reuse it
```

**Comment by serprex** [comment]
Trying to read through this code to get a handle on things, there's some confusion around FinishDistributedExecution

https://github.com/citusdata/citus/blob/f6d4df6da917b28ea14112ec4f2cbc59aa1be7ee/src/backend/distributed/executor/adaptive_executor.c#L2635-L2637

So I'd think in FinishDistributedExecution we dispose the connections, & indeed it claims to do so

https://github.com/citusdata/citus/blob/f6d4df6da917b28ea14112ec4f2cbc59aa1be7ee/src/backend/distributed/executor/adaptive_executor.c#L1462-L1464

But then only resets notice level & modification level
