### ISSUE TITLE
Speedup Travis tests

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus#2213]
Hey all,

We spend enormous amount of time in travis tests. This is written by @jasonmp85 in our #code channel
> What’s happened to our build time in Travis? It’s insane…
> Just had a 23m build
> like, this is well into “affecting my ability to ship code” territory

I believe, this really affects our development speed. I generally cannot spend my time on some other tasks while waiting for travis since the context switch feels like more costly. When we quickly check the community edition's travis tests in the last week, we had around 200 builds and each takes around 12 mins in average. (Just checked quickly by eye) The numbers are insane because this makes that we spent 40 hrs by waiting travis results.

When I look at our tests in travis, I see a parallelization chance. First of all currently, each PR is built in parallel for PG9.6 and PG10 (soon 11 will be added). However, under each PG version build, we run 7 different test suites (multi, isolation, mx, etc..). I think we can parallelize this. 

If we can group them under 5 different travis builds and run for 2 major Postgres versions, this gives us 10 sub tasks and Travis has a subscription for 10 concurrent job. I believe, this would drastically decrease the wasted time.

**Comment by marcocitus** [comment]
Can we also remove the `check-multi-task-tracker-extra` schedule and maybe just introduce some new regression tests that run a few regular queries over task-tracker? Should save at least a minute or two.

**Comment by jasonmp85** [comment]
When I chatted with some Travis folks a while back, they asked whether we were using [build stages](https://docs.travis-ci.com/user/build-stages). I think that could make things even faster, as we could have a "compile" stage that fans out into many "test" stages, removing the need for each member of this proposed matrix to do its own compilation.

**Comment by onderkalaci** [comment]
And, we're about to introduce automated failure tests, which should also take quite a bit of time to finish.

**Comment by onderkalaci** [comment]
I guess this is safe to close as of now @jasonmp85?

**Comment by jasonmp85** [comment]
> I guess this is safe to close as of now @jasonmp85?

Yup. Closing.
