### ISSUE TITLE
Insert into referenced table takes forever (could be deadlock?)

### ISSUE THREAD

**Issue by btnguyen2k** [citusdata/citus#2223]
I have the following referenced table:

```
CREATE TABLE ghnmcshr_employee (
    eid                         INT,
    echecksum                   BIGINT,
    edata                       JSONB,
    etime                       TIMESTAMP,
    PRIMARY KEY (eid)
);
SELECT create_reference_table('ghnmcshr_employee');
```

A simple INSERT statement tool forever to run:
`INSERT INTO ghnmcshr_employee(eid,echecksum,edata) VALUES (1,1,'{}'::JSON)`

I noticed that the table already had a row with eid=1, so I tried the following statement, but it also took forever to run:
`INSERT INTO ghnmcshr_employee(eid,echecksum,edata) VALUES (1,1,'{}'::JSON)
ON CONFLICT (eid) DO UPDATE SET echecksum=EXCLUDED.echecksum,edata=EXCLUDED.edata`.

I have  no such problem with distributed table.

My Citus version: `citus70_96-7.0.3.citus-1.el7.centos.x86_64`

**Comment by btnguyen2k** [comment]
I found that there was something wrong with the table on one of the worker node.
I tried:
`DELETE  FROM the-table`
`DROP TABLE the-table`
`DROP  DATABASE the-database`

But none worked! DROP DATABASE showed a message: `database "dbname" is being accessed by other users. There is 1 prepared transaction using the database.`

I tried:
`DROP EXTENSION citus;` on that node
also `REVOKE CONNECT ON DATABASE`
also terminate exiting connection with `SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = 'dbname';`

But I am still not able to `DELETE  FROM the-table`, or drop the table,  or drop the database.

**Comment by marcocitus** [comment]
If you run `SELECT recover_prepared_transactions()` first, do the commands start working again?

**Comment by btnguyen2k** [comment]
`SELECT recover_prepared_transactions()` returns:
```
 recover_prepared_transactions
-------------------------------
                             0
(1 row)
```

Then drop database returns:
```
dropdb: database removal failed: ERROR:  database "dbname" is being accessed by other users
DETAIL:  There are 1 other session(s) and 1 prepared transaction(s) using the database.
```

It does not solve the problem I assume.

**Comment by marcocitus** [comment]
That's odd. Did you run `recover_prepared_transactions` on the coordinator? 

On the worker that has the prepared transaction, can you run `SELECT * FROM pg_prepared_xacts ;`?

**Comment by btnguyen2k** [comment]
I ran `SELECT recover_prepared_transactions()` on worker node. The database was dropped on  coordinator so `SELECT recover_prepared_transactions()` on coordinator node returns error `No function matches the given name and argument types`.

`SELECT * FROM pg_prepared_xacts` on the worker node returns:

postgres=# SELECT * FROM pg_prepared_xacts ;
 transaction |           gid           |           prepared            | owner | database
-------------+-------------------------+-------------------------------+-------+----------
   949257931 | citus_0_30286_57051_375 | 2018-06-15 13:44:46.735916+07 | <user> | <dbname>
(1 row)

Odd things:
- The database was dropped on coordinator node successfully  (and other worker nodes, except for  the error one).
- All nodes (coordinator and workers) have been rebooted several times.
- I tried to restart pgsql service and immediate followed by dropdb but it didn't work.

As of now, I still can not drop the database on the error worker node.

**Comment by marcocitus** [comment]
Ah, you'd normally run `recover_prepared_transactions` on the coordinator.

You can do `ROLLBACK PREPARED citus_0_30286_57051_375` on the worker to release the locks held by the 2PC.

**Comment by btnguyen2k** [comment]
`ROLLBACK PREPARED 'citus_0_30286_57051_375'` was successful and `SELECT * FROM pg_prepared_xacts;` returned empty rows.
Dropping database returned with error:
```
ERROR:  database "dbname" is being accessed by other users
DETAIL:  There is 1 other session using the database.
```
However,  I am now able to DELETE  FROM table  and also DROP TABLE.

I think it's good to me for now. Thanks for your help.
