### ISSUE TITLE
Build error on Solaris 11.3 SPARC

### ISSUE THREAD

**Issue by clauzio** [citusdata/citus#2225]
With developerstudio12.6:
$ ./configure                                                                                                                                                                              
checking for a sed that does not truncate output... /usr/bin/gsed
checking for gawk... gawk
checking for flex... /opt/csw/bin/flex
configure: building against PostgreSQL 10
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... no
checking whether /opt/developerstudio12.6/bin/cc accepts -g... yes
checking for /opt/developerstudio12.6/bin/cc option to accept ISO C89... none needed
checking how to run the C preprocessor... /opt/developerstudio12.6/bin/cc -E
checking for grep that handles long lines and -e... /usr/bin/ggrep
checking for egrep... /usr/bin/ggrep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking size of void *... 4
checking whether /opt/developerstudio12.6/bin/cc supports -Wall... yes
checking whether /opt/developerstudio12.6/bin/cc supports -Wextra... yes
checking whether /opt/developerstudio12.6/bin/cc supports -Wno-unused-parameter... yes
checking whether /opt/developerstudio12.6/bin/cc supports -Wno-sign-compare... yes
checking whether /opt/developerstudio12.6/bin/cc supports -Wno-missing-field-initializers... yes
checking whether /opt/developerstudio12.6/bin/cc supports -Wno-clobbered... yes
checking whether /opt/developerstudio12.6/bin/cc supports -Wdeclaration-after-statement... yes
checking whether /opt/developerstudio12.6/bin/cc supports -Wendif-labels... yes
checking whether /opt/developerstudio12.6/bin/cc supports -Wmissing-format-attribute... yes
checking whether /opt/developerstudio12.6/bin/cc supports -Wmissing-declarations... yes
checking whether /opt/developerstudio12.6/bin/cc supports -Wmissing-prototypes... yes
checking whether /opt/developerstudio12.6/bin/cc supports -Werror=vla... ./configure[4009]: citusac_cv_prog_cc_cflags__Werror_vla=yes: not found [No such file or directory]

checking for curl_global_init in -lcurl... yes
checking curl/curl.h usability... yes
checking curl/curl.h presence... yes
checking for curl/curl.h... yes
configure: creating ./config.status
config.status: creating Makefile.global
config.status: creating src/include/citus_config.h
config.status: src/include/citus_config.h is unchanged
config.status: creating src/include/citus_version.h
config.status: src/include/citus_version.h is unchanged

$ gmake                                                                                                                                                                                    
gmake -C src/backend/distributed/ all
gmake[1]: Entering directory `/home/80126197/citus/src/backend/distributed'
/opt/developerstudio12.6/bin/cc -v -O -KPIC -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wno-clobbered -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/home/80126197/citus/src/include' -I'../../../src/include' -I. -I./ -I/opt/postgresql/include/server -I/opt/postgresql/include/internal   -I/opt/postgresql/include  -c -o commands/create_distributed_table.o commands/create_distributed_table.c
"/opt/postgresql/include/server/catalog/pg_index.h", line 48: warning: type of struct member "indkey" can not be derived from structure with flexible array member
"/opt/postgresql/include/server/catalog/pg_trigger.h", line 57: warning: type of struct member "tgattr" can not be derived from structure with flexible array member
"/home/80126197/citus/src/include/distributed/version_compat.h", line 92: void function cannot return value
"commands/create_distributed_table.c", line 456: warning: statement not reached
cc: acomp failed for commands/create_distributed_table.c
gmake[1]: *** [commands/create_distributed_table.o] Error 2
gmake[1]: Leaving directory `/home/80126197/citus/src/backend/distributed'
gmake: *** [extension] Error 2

With gcc (GCC) 4.8.2:
$ ./configure                                                                                                                                                                              
checking for a sed that does not truncate output... /usr/bin/gsed
checking for gawk... gawk
checking for flex... /opt/csw/bin/flex
configure: building against PostgreSQL 10
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/gcc accepts -g... yes
checking for /usr/bin/gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... /usr/bin/gcc -E
checking for grep that handles long lines and -e... /usr/bin/ggrep
checking for egrep... /usr/bin/ggrep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking size of void *... 4
checking whether /usr/bin/gcc supports -Wall... yes
checking whether /usr/bin/gcc supports -Wextra... yes
checking whether /usr/bin/gcc supports -Wno-unused-parameter... yes
checking whether /usr/bin/gcc supports -Wno-sign-compare... yes
checking whether /usr/bin/gcc supports -Wno-missing-field-initializers... yes
checking whether /usr/bin/gcc supports -Wno-clobbered... yes
checking whether /usr/bin/gcc supports -Wdeclaration-after-statement... yes
checking whether /usr/bin/gcc supports -Wendif-labels... yes
checking whether /usr/bin/gcc supports -Wmissing-format-attribute... yes
checking whether /usr/bin/gcc supports -Wmissing-declarations... yes
checking whether /usr/bin/gcc supports -Wmissing-prototypes... yes
checking whether /usr/bin/gcc supports -Werror=vla... ./configure[4009]: citusac_cv_prog_cc_cflags__Werror_vla=yes: not found [No such file or directory]

checking for curl_global_init in -lcurl... yes
checking curl/curl.h usability... yes
checking curl/curl.h presence... yes
checking for curl/curl.h... yes
configure: creating ./config.status
config.status: creating Makefile.global
config.status: creating src/include/citus_config.h
config.status: creating src/include/citus_version.h

$ gmake                                                                                                                                                                                    
gmake -C src/backend/distributed/ all
gmake[1]: Entering directory `/home/80126197/citus/src/backend/distributed'
/usr/bin/gcc -v -O -KPIC -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wno-clobbered -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/home/80126197/citus/src/include' -I'../../../src/include' -I. -I./ -I/opt/postgresql/include/server -I/opt/postgresql/include/internal   -I/opt/postgresql/include  -c -o shared_library_init.o shared_library_init.c
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
gcc: error: unrecognized command line option ‘-KPIC’
Target: sparc-sun-solaris2.11
Configured with: /export/home/hudson/workspace/nightly-update/build/sparc/components/gcc48/gcc-4.8.2/configure CC=/usr/gcc/4.7/bin/gcc CXX=/usr/gcc/4.7/bin/g++ --prefix=/usr/gcc/4.8 --mandir=/usr/gcc/4.8/share/man --bindir=/usr/gcc/4.8/bin --libdir=/usr/gcc/4.8/lib --sbindir=/usr/gcc/4.8/sbin --infodir=/usr/gcc/4.8/share/info --libexecdir=/usr/gcc/4.8/lib --enable-languages=c,c++,fortran,objc --enable-shared --with-gmp-include=/usr/include/gmp --with-mpfr-include=/usr/include/mpfr --without-gnu-ld --with-ld=/usr/bin/ld --without-gnu-as --with-as=/usr/bin/as CFLAGS='-g -O2  -mtune=ultrasparc -mcpu=ultrasparc -mno-unaligned-doubles' CXXFLAGS='-g -O2 -mtune=ultrasparc -mcpu=ultrasparc -mno-unaligned-doubles'
Thread model: posix
gcc version 4.8.2 (GCC) 
gmake[1]: *** [shared_library_init.o] Error 1
gmake[1]: Leaving directory `/home/80126197/citus/src/backend/distributed'
gmake: *** [extension] Error 2
80126197@sac0983:~/citus$ gcc --version                                                                                                                                                                            
gcc (GCC) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Thx

**Comment by ozgune** [comment]
Hi @clauzio -- Thanks for reporting this.

We currently don't support building on Solaris 11.3. Looking at the build output, we're using a gcc command line option that's unsupported on your platform.

Could you elaborate a bit more on how you're planning to use Citus (your use case, etc.)?

**Comment by ozgune** [comment]
I'm closing this issue because we currently don't support Citus on Solaris 11.3.

If you have a specific question, please feel free to re-open and comment.
