### ISSUE TITLE
create_distributed_table issues `CREATE SCHEMA IF NOT EXISTS` twice

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus#2283]
We were discussing this in [here](https://github.com/citusdata/citus/pull/2280#discussion_r202224101) that a `create_distributed_table` call actually tries to create the schema twice per shard; one in [`CreateHashDistributedTableShards`](https://github.com/citusdata/citus/blob/master/src/backend/distributed/commands/create_distributed_table.c#L489) and the other command is run in [`CreateShardsOnWorkers`](https://github.com/citusdata/citus/blob/master/src/backend/distributed/master/master_stage_protocol.c#L492) through `GetTableDDLEvents`. It seems like a harmless bug but it also causes some strange behavior, such as;
If we cancel the query in the middle of the execution after the first `CREATE SCHEMA` is executed, there is no way we rollback that even when the connection is broken or cancelled. The schema gets created in workers because we sent it through a different connection which also solves a problem we had earlier, see #1637 and #1652.

**Comment by marcocitus** [comment]
Related to https://github.com/citusdata/citus/issues/1097

**Comment by hanefi** [comment]
fixed by #2777
