### ISSUE TITLE
Cancellation may leave behind prepared transactions

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#2287]
Cancellation might cause prepared transactions to be left behind even if there are no connection failures:
https://github.com/citusdata/citus/pull/2272/files#r202020794

The reason is that `ForgetResults`/`GetRemoteCommandResults` returns early when `QueryCancelPending` is true in the abort handler:
https://github.com/citusdata/citus/blob/88f64d22db7a0afd31c9670bda3944281e49916c/src/backend/distributed/connection/remote_commands.c#L741

That means that `ROLLBACK PREPARED ...` is sent without the result of the `PREPARE TRANSACTION` being fully consumed:
https://github.com/citusdata/citus/blob/88f64d22db7a0afd31c9670bda3944281e49916c/src/backend/distributed/transaction/remote_transaction.c#L371

and that leads to an "another command is already in progress" error:
```
LOG:  issuing ROLLBACK PREPARED 'citus_0_23234_85_15'
DETAIL:  on server localhost:57640
WARNING:  connection error: localhost:57640
DETAIL:  another command is already in progress
WARNING:  failed to roll back prepared transaction 'citus_0_23234_85_15'
HINT:  Run "ROLLBACK PREPARED 'citus_0_23234_85_15'" on localhost:57640
```

**Comment by marcocitus** [comment]
What's not entirely clear to me is why `QueryCancelPending` is true at abort time, whereas it should become false as soon as we hit `CHECK_FOR_INTERRUPTS()` and throw the `"canceling statement due to user request"` error. This suggests that there are multiple cancellations, in which case this is expected behaviour.

**Comment by marcocitus** [comment]
It seems that there are actually 2 cancellations in the automated failure test because there are 2 `PREPARE TRANSACTION` commands being intercepted. In that case interrupting the `ROLLBACK PREPARED` is expected and desirable behaviour.

**Comment by onderkalaci** [comment]
This came up again, it was confusing while understanding the issue. We should probably consider sending a single `cancel()` even if multiple commands are sent over a single connection.
