### ISSUE TITLE
INSERT...SELECT...ON CONFLICT... allows modifying partition column

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#2288]
We don't apply the usual ON CONFLICT checks to distributed INSERT...SELECT queries.
```sql
CREATE TABLE test (x int primary key, y int);                                                                                                                           
CREATE TABLE test2 (x int, y int);
SELECT create_distributed_table('test', 'x');
SELECT create_distributed_table('test2', 'x');                                                                                                                          
INSERT INTO test2 VALUES (1,2);

-- First insert, no conflict
INSERT INTO test SELECT * FROM test2 ON CONFLICT (x) DO UPDATE SET x = 3 RETURNING *;

SELECT * FROM test WHERE x = 1;
 x │ y 
───┼───
 1 │ 2
(1 row)

-- Conflicts on the primary key, so update x to 3
INSERT INTO test SELECT * FROM test2 ON CONFLICT (x) DO UPDATE SET x = 3;

-- Row is still there
SELECT * FROM test;
 x │ y 
───┼───
 3 │ 2
(1 row)

-- but it's in the wrong shard
SELECT * FROM test WHERE x = 3;
 x │ y 
───┼───
(0 rows)

```

**Comment by thanodnl** [comment]
@marcocitus What is the expected behaviour here?

My assumption is that such a query is not possible since updating the value in the distribution column would cause the item to be inserted in on a different partition. This seems to be not possible when such a query gets executed on the shards.

**Comment by marcocitus** [comment]
We should throw an error as we do with regular upserts:

```
postgres=# INSERT INTO test VALUES (1,2) ON CONFLICT (x, y) DO UPDATE SET x = 3;
ERROR:  modifying the partition value of rows is not allowed
```

**Comment by thanodnl** [comment]
I have a working patch in [fix/insert-select-onconflict](https://github.com/citusdata/citus/tree/fix/insert-select-onconflict).

It might conflict slightly with [insert_select_onconflict](https://github.com/citusdata/citus/tree/insert_select_onconflict) as I needed to extract `ErrorIfOnConflictNotSupported` which is now extracted in both. I tried to have the exact same patch to minimise the conflicts.
