### ISSUE TITLE
`ALTER TABLE %s ADD COLUMN` constraint check is missing

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus#2289]
I realized this bug while working on #2286
We do not support some of the constraints on distributed table and we check them while `ALTER TABLE %s ADD CONSTRAINT` or `create_distributed_table`. However, some of the constraints can also be added via `ALTER TABLE %s ADD COLUMN %s`, in which case, we do not check anything. Thus, user is able to create some of the constraints which s/he shouldn't. For example,
```
postgres=# CREATE TABLE t(i int);
CREATE TABLE
Time: 5.067 ms
postgres=# SELECT create_distributed_table('t', 'i');
 create_distributed_table
--------------------------

(1 row)

Time: 83.607 ms
postgres=# -- we do not support UNIQUE constraints on non-distribution columns
postgres=# ALTER TABLE t ADD COLUMN j int UNIQUE;
ALTER TABLE
Time: 152.560 ms
postgres=# \d+ t;
                                     Table "public.t"
 Column |  Type   | Collation | Nullable | Default | Storage | Stats target | Description
--------+---------+-----------+----------+---------+---------+--------------+-------------
 i      | integer |           |          |         | plain   |              |
 j      | integer |           |          |         | plain   |              |
Indexes:
    "t_j_key" UNIQUE CONSTRAINT, btree (j)
```

**Comment by mtuncer** [comment]
Let's keep this issue open for a while until we fix this for good

**Comment by mtuncer** [comment]
alter  <reference_table> add column <colname> <coltype> default  nextval(<sequence>) passes our checks and fail at worker level.
We should 1 - allow this command on coordinator, 2 - strip default ... part from worker command such that to match existing behavior when adding the same column during table creation time.

**Comment by furkansahin** [comment]
re-opening since we cannot catch the use case @mtuncer mentions

**Comment by marcocitus** [comment]
seems to have been fixed a while ago
