### ISSUE TITLE
foreign_key_restriction_enforcement test consistently fails on CentOS

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#2293]
The `foreign_key_restriction_enforcement` test always fails on my laptop because there are `EventTriggerTableRewrite` debug messages, e.g.:

```
ALTER TABLE on_update_fkey_table ALTER COLUMN value_1 SET DATA TYPE bigint;
+DEBUG:  EventTriggerTableRewrite(23187)
```

**Comment by thanodnl** [comment]
I think I have witnessed the same issue on OSX, so might not be isolated to CentOS

**Comment by thanodnl** [comment]
This was a line present in postgres before April 20th. It got removed in: https://github.com/postgres/postgres/commit/b1b71f16581fb5385fa9f9a663ffee271cdfaba5#diff-381097b27cbaf2d023ce5e63eaf524b8L939

**Comment by onderkalaci** [comment]
So, that's no longer an issue @thanodnl ?

**Comment by thanodnl** [comment]
Nope, if you make a new build of postgres with a version after above patches (eg. REL_10_STABLE) the tests pass.

**Comment by onderkalaci** [comment]
> Nope, if you make a new build of postgres with a version after above patches (eg. REL_10_STABLE) the tests pass.

I'm a bit confused because the issue is closed 😄  So, shall I re-open the issue and fix it?

**Comment by marcocitus** [comment]
It's fixed, it was a postgres issue that existed in older patch releases.
