### ISSUE TITLE
Fast COPY distributed_table TO STDOUT

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#2306]
We currently implement `COPY distributed_table TO STDOUT` by replacing the table name with `SELECT * FROM distributed_table` and running the query through the regular distributed planner and (real-time) executor. A much faster method would be to run commands like `COPY distributed_table_102008 TO STDOUT` against the shards and writing the rows returned by the commands directly to the client. We could do something similar for COPY commands with queries that don't require any aggregation.

A benefit is that it would make `pg_dump` on Citus much more usable, since the data doesn't have to be written to the coordinator to return it.

**Comment by seamusabshere** [comment]
very important for many reasons

often the most important tables in the database are the distributed ones and pg_dump is currently basically broken for them unless your coordinator is huge

**Comment by seamusabshere** [comment]
@marcocitus any plans for this?

**Comment by marcocitus** [comment]
@seamusabshere I took a shot at it: https://github.com/citusdata/citus/pull/2623

There are some limitations mentioned in the PR, do you think those would be acceptable?

**Comment by colton-citus** [comment]
Can we revisit this issue? We had a 2TB coordinator fill up when dumping a 1.2TB table due to the behavior this fixes.
