### ISSUE TITLE
can not create cstore_fdw table in MX

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#2312]
Hit this problem when investigating another user issue

steps to reproduce
```sql
set citus.replication_model to 'streaming';
select start_metadata_sync_to_node('localhost', 9700);
create foreign table cs (a int, b int) server cstore_server;
select create_distributed_table('cs', 'a');
```

Result:
```
ERROR:  "cs" is a foreign table
DETAIL:  Foreign tables cannot have TRUNCATE triggers.
CONTEXT:  while executing command on localhost:9700
```

Failing command at worker is
```sql
 SELECT worker_create_truncate_trigger('public.cs')
```

When creating distributed table in coordinator we check [whether the table is a regular table](https://github.com/citusdata/citus/blob/master/src/backend/distributed/commands/create_distributed_table.c#L348)

We fail to perform the same check in [worker_create_truncate_trigger](https://github.com/citusdata/citus/blob/master/src/backend/distributed/worker/worker_truncate_trigger_protocol.c#L36) function.

Fix should be straightforward.

**Comment by mtuncer** [comment]
Fix turned out to be not so trivial.

**Comment by surprisetalk** [comment]
Has there been any progress on this?

I'm willing to tackle the issue myself, but it would be helpful if somebody could point me in the right direction...
