### ISSUE TITLE
pg_dist_local_group warning after upgrade to postgresql-10 and 7.5.0

### ISSUE THREAD

**Issue by taybin** [citusdata/citus#2329]
I noticed this after upgrading to both postgresql-10 and citus-7.5.0 so I'm not sure what triggered it.

Queries run successfully, but I see the logs filling up with
```
2018-08-06 17:40:40.599 UTC,,,725,,5b64621a.2d5,399518,,2018-08-03 14:09:30 UTC,4/137606,0,WARNING,XX000,"could not find any entries in pg_dist_local_group",,,,,"while executing command on worker3:5432
```
every second for each worker node.

On master, the table has a single row with the value `0`, and on the workers the table is empty.

**Comment by marcocitus** [comment]
You can do `INSERT INTO pg_dist_local_group VALUES (0)` to make the error stop.

**Comment by marcocitus** [comment]
We are probably missing a step upgrading the workers on http://citus-docs.readthedocs.io/en/v7.5/admin_guide/upgrading_citus.html . Sorry for the inconvenience.

**Comment by taybin** [comment]
The `INSERT` fixed it.  Thank you.  Should I close this?

**Comment by marcocitus** [comment]
I've opened an issue in our docs repo to add the missing step. Making pg_upgrade less involved is tracked in #987. Closing this one.
