### ISSUE TITLE
cannot run UPDATE command which targets multiple shards

### ISSUE THREAD

**Issue by eliteacc** [citusdata/citus#2349]
how fix it ?

`1=# UPDATE 2 SET email = replace(email, '''', '') where email like '''%?%';`
ERROR:  cannot run UPDATE command which targets multiple shards
HINT:  Consider using an equality filter on partition column "id" to target a single shard. If you'd like to run a multi-shard operation, use master_modify_multiple_shards().
`1=# select master_modify_multiple_shards('UPDATE 2 SET email = replace(email, '''', '') where email like '''%'');`
ERROR:  function master_modify_multiple_shards(boolean) does not exist
LINE 1: select master_modify_multiple_shards('UPDATE leaked_sources ...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.`

**Comment by marcocitus** [comment]
This works as of Citus 7.1. You may need to upgrade.
