### ISSUE TITLE
documentation example for colocated trigger is incorrect

### ISSUE THREAD

**Issue by taybin** [citusdata/citus#2354]
Using citus-7.5 and postgresql-10.4:

The documentation suggests
```
SELECT run_command_on_colocated_placements(
  'little_vals',
  'big_vals',
  $cmd$
    CREATE TRIGGER after_insert AFTER INSERT ON %s
      FOR EACH ROW EXECUTE PROCEDURE embiggen(%s)
  $cmd$
);
```
as the way to have a distributed trigger on two tables, but this is a change from the previous documentation which used suggested:
```
SELECT run_command_on_colocated_placements(
  'little_vals',
  'big_vals',
  $cmd$
    CREATE TRIGGER after_insert AFTER INSERT ON %s
      FOR EACH ROW EXECUTE PROCEDURE embiggen(%I)
  $cmd$
);
```
Please note the use of `%I` in `embiggen()`.  This is what we used previously for colocated triggers, and we had to use `%I` for a new trigger, ignoring the latest documentation.  I couldn't find the old documentation page, but the current page disappears at version 7.2, so it was probably renamed then.

**Comment by marcocitus** [comment]
Shouldn't it be `embiggen(%L)`?

**Comment by taybin** [comment]
We think the `%L` worked.  We do use schemas, both for tables and functions, and `%I` was working for our case, but we switched to `%L` and that seems to work as well.

**Comment by serprex** [comment]
I've created an issue on citus_docs to track this issue
