### ISSUE TITLE
7.5.1 build error against PostgreSQL 11

### ISSUE THREAD

**Issue by devrimgunduz** [citusdata/citus#2355]
Hi,

As of v11, pg_constraint_fn.h is renamed to pg_constraint_d.h, so a patch is required for v11:

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wno-clobbered -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -Werror=vla -I '/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/citus/master/citus-7.5.1/src/include' -I'../../../src/include' -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -I/usr/pgsql-11/include  -c -o executor/multi_task_tracker_executor.o executor/multi_task_tracker_executor.c
ddl/foreign_constraint.c:18:10: fatal error: catalog/pg_constraint_fn.h: No such file or directory
 #include "catalog/pg_constraint_fn.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [<builtin>: ddl/foreign_constraint.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by jasonmp85** [comment]
@devrimgunduz because 11 isn't at RC yet (and won't be for a week or two, I believe, if that), it's likely that Citus 8.0 will be the first version with PostgreSQL 11 support; obviously we relaxed the constraints used in our configure script to aid in ongoing development, but I don't think we plan on backporting 11 compatibility to 7.5 unless something changes.

**Comment by l-we** [comment]
PostgreSQL 11 Bate3

/home/soft/citus-7.5.1/src/backend/distributed/ddl/foreign_constraint.c
18：#include "catalog/pg_constraint_d.h"
643：char *colName = get_attname(relationId, attrNo, false);

/home/soft/citus-7.5.1/src/backend/distributed/transaction/transaction_management.c
144：CommitContext = AllocSetContextCreateExtended(TopMemoryContext,

**Comment by devrimgunduz** [comment]
Hi Jason,

Packagers do not use a branch to fetch the source -- we just use released versions.

Regards, Devrim

**Comment by jasonmp85** [comment]
@devrimgunduz I was mostly responding to @l-we, though their comment is largely indecipherable to me.

Are you saying that Citus 7.5's incompatibility with PostgreSQL 11 is causing some sort of problem, or…?

**Comment by ozgune** [comment]
We released Citus 8 with PG 11 support last month. So, I'm closing this issue.
