### ISSUE TITLE
can not rollback a transaction within procedure

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#2371]
You 
```sql
CREATE TABLE test_table(id integer , org_id integer);
SELECT create_distributed_table('test_table', 'id');
CREATE PROCEDURE test_procedure_rollback(tt_id int, tt_org_id int) LANGUAGE PLPGSQL AS $$
BEGIN
	DELETE FROM test_table;
	COMMIT;
	INSERT INTO test_table VALUES (tt_id, tt_org_id);
	ROLLBACK;
END;
$$;

INSERT INTO test_table VALUES (2,3);

CALL test_procedure_rollback(2,5);
SELECT * FROM test_table ORDER BY 1, 2;
```

Expect:
nothing since delete is commited and insert is rolled back.

Result:
```
 id | org_id 
----+--------
  2 |      5
(1 row)
```

When you run this test on regular (not distributed) tables. insert is rolled back with no problem

Note : It works as expected on reference tables.

**Comment by mtuncer** [comment]
Additional notes :
When a DDL is executed, it could be rolled back

**Comment by marcocitus** [comment]
Nice find. I'm assuming it's because Citus does not consider the INSERT to be in a transaction block and therefore sends it to the worker without a transaction block. The DDL and DELETE are multi-shard commands and therefore always in a transaction block

**Comment by pykello** [comment]
On Fri, Sep 7, 2018 at 10:33 AM Marco Slot <notifications@github.com> wrote:

> Nice find. I'm assuming it's because Citus does not consider the INSERT to
> be in a transaction block and therefore sends it to the worker without a
> transaction block. The DDL and DELETE are multi-shard commands and
> therefore always in a transaction block
>
> Just for my understanding, how is the INSERT inside the procedure
definition different from the following:

BEGIN;
INSERT INTO test_table VALUES (4, 5);
ROLLBACK;

I assume we are not getting any callback calls for the "BEGIN". So how do
we send a transaction to the worker nodes in this case but not in the
procedure definition?

I always look at the code to understand this, but later I forget again :) I
figured I can ask this time, and hopefully it will stick this time.

Thanks,
Hadi

**Comment by marcocitus** [comment]
@pykello we check for `IsTransactionBlock()` in `multi_router_executor.c`

It's kind of hard to detect whether we are in a procedure. As far as I can tell, there isn't any indication in the query plan. I think we should do something like `if (IsA(parsetree, CallStmt)) BeginOrContinueCoordinatedTransaction()` in the utility hook.

**Comment by marcocitus** [comment]
Given that this is a major release, we should also consider always opening transaction blocks for single-shard writes called from PL/pgSQL. For that we could look at `whereToSendOutput`  (it would be `DestSPI` when called from a function).

**Comment by sumedhpathak** [comment]
@marcocitus @pykello @mtuncer  Do we have an estimate for the fix? Should we prioritize for 8.0?

**Comment by marcocitus** [comment]
If the CallStmt thing works: at most 1 day.

**Comment by jasonmp85** [comment]
Didn't we have some behavior around functions (not procedures) and decided _not_ to detect and auto-start a transaction for them because it would break existing users who depended on certain things in a function that wouldn't be the same with a transaction?

Did we ever resolve that issue/decision? Doesn't it affect this?

**Comment by mtuncer** [comment]
I haven't given it a try but I am not convinced it would work. Because we can do multiple commit/rollbacks within a procedure.
