### ISSUE TITLE
TRUNCATE on multiple tables may fail if there is a foreign key to reference table

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#2382]
We could probably improve this behaviour by looking at all the tables that are truncated as opposed to looking each table seperately on the execution time.

```SQL
CREATE TABLE reference_table(id int PRIMARY KEY);
SELECT create_reference_table('reference_table');

CREATE TABLE distributed_table(id int PRIMARY KEY, value_1 int);
SELECT create_distributed_table('distributed_table', 'id');


ALTER TABLE 
	distributed_table 
ADD CONSTRAINT 
	fkey_delete FOREIGN KEY(value_1) 
REFERENCES 
	reference_table(id) ON DELETE CASCADE;
```

```SQL
-- The following command fails 
TRUNCATE distributed_table, reference_table;
ERROR:  cannot execute DDL on reference relation "reference_table" because there was a parallel DDL access to distributed relation "distributed_table" in the same transaction
HINT:  Try re-running the transaction with "SET LOCAL citus.multi_shard_modify_mode TO 'sequential';"
```

If you start the command with the `reference_table` it works just fine because we're automatically switching to `sequential mode`;
```
--
TRUNCATE reference_table, distributed_table;
TRUNCATE TABLE
```

Similarly, explicitly setting the mode to sequential just works
```
BEGIN;
         SET LOCAL citus.multi_shard_modify_mode TO 'sequential';
	TRUNCATE distributed_table, reference_table;
COMMIT;

```

**Comment by furkansahin** [comment]
Just leaving it as a note here for the future owner;
I spent a small amount of time debugging that issue and the solution does not seem that straightforward. The way we use triggers in `truncate` seems like the reason of this issue. For each table in the truncate list, we call the trigger separately and Citus code does not seem to be aware of the list of the tables.

**Comment by onderkalaci** [comment]
> . The way we use triggers in truncate seems like the reason of this issue

@mtuncer is currently working on a completely separate fix, which would move some parts of `TRUNCATE` functionality into `multi_ProcessUtility()`. After that change checked-in, we should be able to quickly fix this as well.

**Comment by mtuncer** [comment]
update : issue still exists after introduced distributed locking to truncate in process utility
