### ISSUE TITLE
QUESTION: Using Redis and Citus

### ISSUE THREAD

**Issue by alaxalves** [citusdata/citus#2388]
Hello!
I'd like to know if it is possible setting and using Citus as my main database along with Redis for caching. If possible, how it can be done? Is it the same way as in Postgres?? Thank you!!

**Comment by marcocitus** [comment]
Yes, should work in the same was as on Postgres.

**Comment by marcocitus** [comment]
For questions we usually recommend the [Citus Data slack channel](http://slack.citusdata.com) or [Citus Users Group](https://groups.google.com/forum/#!forum/citus-users).

**Comment by alaxalves** [comment]
@marcocitus Thank you for the answer, I didn't know about the channels, will use it from now on xD
