### ISSUE TITLE
Drop schema failed when using partition table

### ISSUE THREAD

**Issue by sannmaime** [citusdata/citus#2399]
Hello,I have met a problem that the following error message was output when dropping schema with option cascade.
ERROR:  relation "test.dist_range1_0" does not exist

The above problem was occured by the following steps。
1. create schema
2. create partitioned table with range or list 
3. distributing the partition table with method create_distributed_table
4. create partitions
5. drop schema with option cascade
Ex.
-----------------------------------------------------------\\\
create schema test;
create table test.dist_range1(c1 int, c2 int, crt_time timestamp) partition by range (c2);
select create_distributed_table('test.dist_range1','c1');
do language plpgsql $$
declare
    i int;
begin
    for i in 0..100 loop
        execute 'create table test.dist_range1_'||i||' partition of test.dist_range1(primary key(c1)) for values from ('||i*1000||') to ('||(i+1)*1000||')';
    end loop;
end;
$$;
drop schema test cascade;
-----------------------------------------------------------\\\

**Comment by metdos** [comment]
> @metdos -- Could we run the steps here and see if we can reproduce the issue?
> 
> If we can, do we have an estimate on how long the fix would take?

@mtuncer, basically could you do what Ozgun asks tomorrow :)

**Comment by mtuncer** [comment]
I did not notice any issues on current build on PG11. 

I initially hit max_connections limit which was default (100) on my setup.  Everything worked just fine after increasing that limit.

I will try with PG10, and with earlier citus version.

**Comment by mtuncer** [comment]
Also tested with PG10 with both current Citus, and with v7.5.1. Did not see any issues as reported.

@sannmaime could you please provide more information about the cluster setup. i.e. OS, PG version, Citus version, nodecount, shardcount, replication factor, max_connections etc.

**Comment by sannmaime** [comment]
> Also tested with PG10 with both current Citus, and with v7.5.1. Did not see any issues as reported.
> 
> @sannmaime could you please provide more information about the cluster setup. i.e. OS, PG version, Citus version, nodecount, shardcount, replication factor, max_connections etc.

@mtuncer The following information was used when I found this incident.
OS:RHEL6.3 x64
PG:10.2
citus:7.4.1
nodecount:4(1cn+3workers)
shardcount:8
citus.shard_replication_factor:1
max_connections:85

**Comment by marcocitus** [comment]
> I initially hit max_connections limit which was default (100) on my setup. Everything worked just fine after increasing that limit.

exceeding 100 connections seems unexpected

**Comment by mtuncer** [comment]
I am on PG 10.4 with Citus 7.4.1 still can't reproduce it. Although I am on OsX 10.13.6 not on Centos.

@marcocitus I number of active queries in workers seem to increase at each iteration of execute command in the loop.

**Comment by mtuncer** [comment]
error message suggests this might be related to MX configuration. trying that with MX.

**Comment by mtuncer** [comment]
here is the error message

```sql
postgres=# drop schema test cascade;
NOTICE:  drop cascades to table test.dist_range1
ERROR:  relation "test.dist_range1_0" does not exist
CONTEXT:  while executing command on localhost:9700
SQL statement "SELECT master_remove_distributed_table_metadata_from_workers(v_obj.objid, v_obj.schema_name, v_obj.object_name)"
PL/pgSQL function citus_drop_trigger() line 19 at PERFORM
Time: 75.781 ms
```
