### ISSUE TITLE
CTEs in modifying router queries do recursive planning

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus#2400]
**Schema:**
```
CREATE TABLE test_id(id int,tenant_id int);
SELECT create_distributed_table('test_id','tenant_id');
```
**Query that does distributed planning:**
```
EXPLAIN WITH t AS (SELECT id from test_id where tenant_id=1)
UPDATE test_id ti SET id=1 FROM t where ti.id=t.id and ti.tenant_id=1;
                                                          QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------
 Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0)
   ->  Distributed Subplan 3_1
         ->  Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0)
               Task Count: 1
               Tasks Shown: All
               ->  Task
                     Node: host=ec2-54-175-83-159.compute-1.amazonaws.com port=5432 dbname=citus
                     ->  Seq Scan on test_id_102201 test_id  (cost=0.00..38.25 rows=11 width=4)
                           Filter: (tenant_id = 1)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=ec2-54-175-83-159.compute-1.amazonaws.com port=5432 dbname=citus
         ->  Update on test_id_102201 ti  (cost=38.39..52.69 rows=55 width=42)
               ->  Hash Join  (cost=38.39..52.69 rows=55 width=42)
                     Hash Cond: (intermediate_result.id = ti.id)
                     ->  Function Scan on read_intermediate_result intermediate_result  (cost=0.00..10.00 rows=1000 width=32)
                     ->  Hash  (cost=38.25..38.25 rows=11 width=14)
                           ->  Seq Scan on test_id_102201 ti  (cost=0.00..38.25 rows=11 width=14)
                                 Filter: (tenant_id = 1)
```

We don't need to do recursive planning for the query, it can be directly pushed down. The concern is recursive planning generates connection to each worker because of reference table logic.

**Comment by mtuncer** [comment]
Query is rejected by router planner [here](https://github.com/citusdata/citus/blob/master/src/backend/distributed/planner/multi_router_planner.c#L604)

We did not intend to support cte's in router update queries.  This is [almost 2 years old](https://github.com/citusdata/citus/commit/c244b8ef4a164536458091257dbb799d930f7b5a). We should re-evaluate this decision.

**Comment by marcocitus** [comment]
We need to consider a few things to support modifying CTEs in the router planner:
1) We need to take metadata and resource locks on shards of distributed tables being modified. 
2) SELECTs need to be executed as modifications if they have modifying CTEs
3) How does shard pruning work for modifying inserts?
4) Does function evaluation and prepared statements behave correctly?
5) Does our deparsing logic handle modifying CTEs
6) What if the modifying CTE modifies a reference table?
7) What about SELECT.. FOR UPDATE in a CTE?
8) FOR_DML tracking of placements modified by CTEs in connection management

Possibly a few other things. I expect this is a 2 week project.

**Comment by mtuncer** [comment]
I already hit some of those problems when I disabled the error.  

@marcocitus question on item (5/6/7/8).  This is not about supporting modifying CTEs, more like supporting read-only CTEs in modify queries.

**Comment by marcocitus** [comment]
> question on item (5/6/7/8). This is not about supporting modifying CTEs, more like supporting read-only CTEs in modify queries.

Not sure what your question is. We already support read-only CTEs in modifying queries.

**Comment by marcocitus** [comment]
> Not sure what your question is. We already support read-only CTEs in modifying queries.

Correction, those are also recursively planned it seems.

**Comment by serprex** [comment]
Made #2776 to cover the tangent @marcocitus went on, renamed issue to match what this issue is really about
