### ISSUE TITLE
Memory leak happen when run two update SQLs in one transaction

### ISSUE THREAD

**Issue by ChenHuajun** [citusdata/citus#2405]
memory leak happen when run two update SQLs in one transaction

# env
Tested in the following environment 
- citus 7.2.1, citus 7.4.1 and citus 7.5.1
- CentOS 6.3

# How to reproduct
## DDL
create table tb1(id int,c1 int);
select create_distributed_table('tb1','id');

create table tb2(id int,c1 int);
select create_distributed_table('tb2','id');

## test SQL
[postgres@node1 before]$ cat test.sql
begin;
update tb1 set c1=c1 where id=1; // run on wokrer1
update tb2 set c1=c1 where id=2; // run on worker2
commit;

## test
pgbench -n "service=admin dbname=postgres" -T 100 -r -f  test.sql

# check memory( memory increasing )
[postgres@node1 log]$  ps auxw|grep local
postgres  7273 26.8  0.0 7892200 11992 ?       Rs   18:18   0:01 postgres: admin postgres [local] UPDATE
postgres  7562  0.0  0.0 103248   868 pts/5    S+   18:18   0:00 grep local
[postgres@node1 log]$  ps auxw|grep local
postgres  7273 24.5  0.0 7892276 12148 ?       Rs   18:18   0:01 postgres: admin postgres [local] UPDATE
postgres  7580  0.0  0.0 103248   864 pts/5    S+   18:18   0:00 grep local
[postgres@node1 log]$  ps auxw|grep local
postgres  7273 27.1  0.0 7892276 12364 ?       Ss   18:18   0:01 postgres: admin postgres [local] UPDATE
postgres  7639  0.0  0.0 103248   868 pts/5    S+   18:18   0:00 grep local

**Comment by ChenHuajun** [comment]
I run this test SQL, memory increases and never decreases.  After 26 minutes postgres was killed by OOM. ( It‘s a simulation of our production environment, in which memory will exhaust  about after  2days)

[postgres@sndsdevdb12 ~]$ cat memleak.sql
begin;
update tb1 set c1=c1 where id=1;
update tb2 set c1=c1 where id=21;
commit;

[postgres@sndsdevdb12 ~]$ pgbench -n "service=admin dbname=app_db" -c 20 -T 10000 -r -f  memleak.sql
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
WARNING:  terminating connection because of crash of another server process

[root@sndsdevdb12 ~]# tail /var/log/messages
Sep 25 20:26:52 sndsdevdb12 kernel: [27214]    26 27214   139654    17128   0       0             0 postgres
Sep 25 20:26:52 sndsdevdb12 kernel: [27215]    26 27215   139628    17084   0       0             0 postgres
Sep 25 20:26:52 sndsdevdb12 kernel: [27216]    26 27216   139603    17016   0       0             0 postgres
Sep 25 20:26:52 sndsdevdb12 kernel: [27217]    26 27217   139580    16682   0       0             0 postgres
Sep 25 20:26:52 sndsdevdb12 kernel: [27218]     0 27218    24532      246   0       0             0 sshd
Sep 25 20:26:52 sndsdevdb12 kernel: [27226]     0 27226    13672       99   0       0             0 login
Sep 25 20:26:52 sndsdevdb12 kernel: [27227]     0 27227    27084       92   0       0             0 bash
Sep 25 20:26:52 sndsdevdb12 kernel: [30117]    26 30117   134646      582   0       0             0 postgres
Sep 25 20:26:52 sndsdevdb12 kernel: Out of memory: Kill process 22178 (postgres) score 156 or sacrifice child
Sep 25 20:26:52 sndsdevdb12 kernel: Killed process 22178, UID 26, (postgres) total-vm:646600kB, anon-rss:107616kB, file-rss:51532kB

**Comment by ChenHuajun** [comment]
One table also can reproduce this problem.  but two update(or insert) SQL must run on different workers.
 
# DDL
create table tb1(id int,c1 int);
select create_distributed_table('tb1','id');

# test SQL

[postgres@node1 before]$ cat test.sql
begin;
update tb1 set c1=c1 where id=1; // run on wokrer1
update tb1 set c1=c1 where id=2; // run on worker2
commit;

**Comment by ChenHuajun** [comment]
One table also can reproduce this problem. but two update(or insert) SQL must run on different workers.

# DDL

create table tb1(id int,c1 int);
set citus.shard_count=32;
select create_distributed_table('tb1','id');

# test SQL

[postgres@node1 before]$ cat test.sql
begin;
update tb1 set c1=c1 where id=1; // run on wokrer1
update tb1 set c1=c1 where id=2; // run on worker2
commit;

**Comment by marcocitus** [comment]
@ChenHuajun thanks for that! Did you try on the current master branch as well? We very recently fixed an issue in that function (`CoordinatedRemoteTransactionsPrepare`) because it wasn't clearing all results.

**Comment by onderkalaci** [comment]
Thanks a lot @ChenHuajun for the investigation! 

> @ChenHuajun thanks for that! Did you try on the current master branch as well? We very recently fixed an issue in that function (CoordinatedRemoteTransactionsPrepare) because it wasn't clearing all results.

It'd be great if you can try it on the master branch as @marcocitus noted.

**Comment by onderkalaci** [comment]
>  We very recently fixed an issue in that function (CoordinatedRemoteTransactionsPrepare) because it wasn't clearing all results.

Btw, #2376 is the change that @marcocitus is referring.

**Comment by ChenHuajun** [comment]
I had tried the citus's master code, and reproduced this problem.

**Comment by ChenHuajun** [comment]
FinishRemoteTransactionPrepare() failed to free PGresult . And i had tested again after add calling PQclear(result), memory leak do not happen.
-------------------------------
void
FinishRemoteTransactionPrepare(struct MultiConnection *connection)
{
	RemoteTransaction *transaction = &connection->remoteTransaction;
	PGresult *result = NULL;
	const bool raiseErrors = true;

	Assert(transaction->transactionState == REMOTE_TRANS_PREPARING);

	result = GetRemoteCommandResult(connection, raiseErrors); //failed to call PQclear(result) for result

	if (!IsResponseOK(result))
	{
		transaction->transactionState = REMOTE_TRANS_ABORTED;
		HandleRemoteTransactionResultError(connection, result, raiseErrors);
	}
	else
	{
		transaction->transactionState = REMOTE_TRANS_PREPARED;
	}

	/*
	 * Try to consume results of PREPARE TRANSACTION command. If we don't
	 * succeed, rollback the transaction. Note that we've not committed on
	 * any node yet, and we're not sure about the state of the worker node.
	 * So rollbacking seems to be the safest action if the worker is
	 * in a state where it can actually rollback.
	 */
	if (!ClearResults(connection, raiseErrors))
	{
		ereport(ERROR, (errmsg("failed to prepare transaction '%s' on host %s:%d",
							   transaction->preparedName, connection->hostname,
							   connection->port),
						errhint("Try re-running the command.")));
	}
}

**Comment by onderkalaci** [comment]
Thanks a lot @ChenHuajun! 

> FinishRemoteTransactionPrepare() failed to free PGresult . And i had tested again after add calling PQclear(result), memory leak do not happen.

Your above comment aligns with the conclusion of our initial investigation. We'll look this issue asap and fix it.

**Comment by metdos** [comment]
> I use valgrind to chek memory leak,and found the the following

@ChenHuajun thanks for all the testing. We use Valgrind in our test cycles but missed this one, could you also share your Valgrind test parameters?

**Comment by mtuncer** [comment]
even after the change, I still see memory usage is increasing but at a much slower rate. I did not see any OOM issues before/after.

**Comment by ChenHuajun** [comment]
@metdos
 the following is  my Valgrind test parameters
$ valgrind --leak-check=yes --gen-suppressions=all      --time-stamp=yes     --log-file=/tmp/%p.log --trace-children=yes     --track-origins=yes --read-var-info=yes     --show-leak-kinds=all -v     postgres --log_line_prefix="%m %p "     --log_statement=all --shared_buffers=2GB
