### ISSUE TITLE
partitions with foreign keys can not be created in mx mode

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#2406]
Following fails when PG11  cluster is configured in MX mode

```sql
create table l1(a int primary key, b int);
select create_distributed_table('l1', 'a');

create table l2(a int references l1(a), b int) partition by range (b);
select create_distributed_table('l2', 'a');
create table l2_1 partition of l2 for values from (0) to (10);
```

Result
```
ERROR:  duplicate key value violates unique constraint "pg_constraint_conrelid_contypid_conname_index"
DETAIL:  Key (conrelid, contypid, conname)=(17476, 0, l2_a_fkey) already exists.
CONTEXT:  while executing command on localhost:9700
```

It works fine on cluster without mx.

**Comment by mtuncer** [comment]
More information about the issue

It turned out that main problem also exists in non-mx mode but not visible.

When we are creating distributed-partitioned tables we do following logic
- create the partition table's shards on workers
- add constraints on partition table to shards on workers
- attach each worker shard to its parent partition table.


When we attach a partition table to a parent table, postgres automatically creates each constraint on parent to the attached partition. We end up having 2 constraints on each worker shard, one is the one we created, another is the one postgres creates when we attach a partition.

Following is taken from partition shard  `l2_1_102744` who is a partition of shard `l2_102712`
```
postgres=# \d+ l2_1_102744
                                Table "public.l2_1_102744"
 Column |  Type   | Collation | Nullable | Default | Storage | Stats target | Description 
--------+---------+-----------+----------+---------+---------+--------------+-------------
 a      | integer |           |          |         | plain   |              | 
 b      | integer |           |          |         | plain   |              | 
Partition of: l2_102712 FOR VALUES FROM (0) TO (10)
Partition constraint: ((b IS NOT NULL) AND (b >= 0) AND (b < 10))
Foreign-key constraints:
    "l2_a_fkey_102712" FOREIGN KEY (a) REFERENCES l1_102680(a)
    "l2_a_fkey_102744" FOREIGN KEY (a) REFERENCES l1_102680(a)
```

As you can see constraint `l2_a_fkey_102744` is created by us, and constraint `l2_a_fkey_102712` is created by postgres when attached. (hint shard name)

We can drop the constraint that is automatically created when we drop constraint from parent table, however, the constraint we manually add is not visible from the coordinator, and we can not drop it.


Solution:
We should not be creating constraints when it is inherited from parent

**Comment by onderkalaci** [comment]
> Solution:
We should not be creating constraints when it is inherited from parent

I think that's a good idea in general. 

We seem to be creating the same foreign constraints for non-MX (or even MX) rebalance operations. I simply created 1 parent 2 child, where I created a foreign key from the parent to an unrelated table. When I move a placement, we get duplicate foreign constraints on the child tables:
```
Referenced by:
    TABLE "collections_102074" CONSTRAINT "c1_102074" FOREIGN KEY (key, collection_id) REFERENCES onder_102202(a, b)
    TABLE "collections_1_102106" CONSTRAINT "c1_102074" FOREIGN KEY (key, collection_id) REFERENCES onder_102202(a, b)
    TABLE "collections_2_102138" CONSTRAINT "c1_102074" FOREIGN KEY (key, collection_id) REFERENCES onder_102202(a, b)
    TABLE "collections_1_102106" CONSTRAINT "c1_102106" FOREIGN KEY (key, collection_id) REFERENCES onder_102202(a, b)
    TABLE "collections_2_102138" CONSTRAINT "c1_102138" FOREIGN KEY (key, collection_id) REFERENCES onder_102202(a, b)

```

**Comment by onderkalaci** [comment]
Are these related https://github.com/citusdata/citus/issues/2385? Worth investigating once we fix it.

**Comment by marcocitus** [comment]
This no longer reprodcues.
