### ISSUE TITLE
Citus may leak intermediate results

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#2429]
With #2424, we've fixed a critical intermediate result leak bug. However, it turned out to be few more cases which are not too common.

1. Failures on task-tracker execution: See the discussion [here](https://github.com/citusdata/citus/pull/2424#issue-219729944) 
2. Citus on Windows, see [here](https://github.com/citusdata/citus/pull/2424#issuecomment-426563454)

Given that we don't have many users relaying on the above, we prefer to fix those later.

Once we fix both, we should be able to move `ensure_no_intermediate_data_leak .sql` file to the end of the all different regression test schedules like `check-multi` and `check-failure`.

**Comment by onderkalaci** [comment]
@serprex would you mind explaining how this issue is closed? If closed, can you ensure the following works fine?

> Once we fix both, we should be able to move ensure_no_intermediate_data_leak .sql file to the end of the all different regression test schedules like check-multi and check-failure.

**Comment by serprex** [comment]
I closed this because `multi_schedule` has no_intermediate_data_leak twice & the linked issues are all closed

I will create a PR which has ensure_no_intermediate_data_leak at the end of all schedules
