### ISSUE TITLE
VALIDATE is not supported

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus#2441]
Citus currently does not support `VALIDATE` command. We are able to add `not valid` constraints which is good but these kind of constraints are added to skip the burden of validating them initially **to be validated** later. It is also mentioned in this [comment](https://github.com/citusdata/citus/issues/968#issuecomment-391362278) by me for foreign key constraints to reference tables. 

I believe this is a nice candidate as a warm-up task though. @marcocitus should I create a label and add it to this issue as it is discussed in the dev discussions last week?

**Comment by marcocitus** [comment]
Yes, this is a good warm-up task.
