### ISSUE TITLE
ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [citusdata/citus#2455]
With PipelineDB being released as ASL 2.0 is it possible to consider ASL 2.0 than *GPL?

**Comment by ozgune** [comment]
hey @sirinath -- Thank you for your note.

We discussed Citus' license in the past. Currently, we don't have any plans to our change our license.

Could you elaborate a bit more on why you'd like Citus to have an ASL 2.0 license?

**Comment by sirinath** [comment]
There are couple of reasons:
1. *GPL is rarely whitelisted for use in projects
2. If it is used, it is difficult to say if other extensions also need to be licensed under AGPL

**Comment by ozgune** [comment]
hi @sirinath -- Thank you. I understand the motivation for needing an ASL 2.0 type license for your company.

We evaluated pros/cons for different license types and made a decision to go with AGPL 3.0. At this point, we aren't planning to change our license. If you're open to using our enterprise edition, that could allow for an easier use of Citus for your projects.

If you have further questions, please feel free to contact me at ozgun at citusdata.com
