### ISSUE TITLE
Non-index CHECK constraints from CREATE TABLE cannot be dropped from coordinator

### ISSUE THREAD

**Issue by louiseGrandjonc** [citusdata/citus#2484]
A customer ran into an issue while trying to drop a constraint.

# Repro Steps

```sql
CREATE TABLE test_constraint (id int CHECK (id>0));
-- CREATE TABLE
SELECT create_distributed_table('test_constraint', 'id');
-- create_distributed_table
-- --------------------------
-- 
-- (1 row)

ALTER TABLE test_constraint DROP CONSTRAINT test_constraint_id_check;
-- ERROR:  constraint "test_constraint_id_check_102168" of relation "test_constraint_102168" does not exist
-- CONTEXT:  while executing command on ec2-23-22-154-48.compute-1.amazonaws.com:5432
```

# Notes

On the worker, here is the constraint that it created 

```sql
-- \d+ test_constraint_102169
--                           Table "public.test_constraint_102169"
--  Column |  Type   | Collation | Nullable | Default | Storage | Stats target | Description
-- --------+---------+-----------+----------+---------+---------+--------------+-------------
--  id     | integer |           |          |         | plain   |              |
-- Check constraints:
--     "test_constraint_id_check" CHECK (id > 0)
```

As you can see, the constraint doesn't include the `shardid`…

# Workaround

I was able to drop the constraint using the following:

```sql
SELECT run_command_on_shards('test_constraint', 'ALTER TABLE %s DROP CONSTRAINT test_constraint_id_check');
```

**Comment by jasonmp85** [comment]
This looks pretty easy to address, itself, but @marcoslot's point about the root cause (_two naming schemes_) is a good one. I'm concerned that there may be other DDL commands that do something similar, especially for e.g. objects with no user-specified name (we don't want to fall back on the PostgreSQL-supplied name from the coordinator). I'll post any findings here and open new issues if required.

**Comment by ajaska** [comment]
To anyone else running into this and just wanting a solution; in my personal case at least, I needed to drop it with both the regular `ALTER TABLE` and with the `run_command_on_shards` versions, both in `IF EXISTS` mode, and if I tried to do it in a transaction, it would hang forever.

Interestingly, I was able to have the coordinator forget the constraint existed with the first command, while it was still being enforced by the workers. Ouch!

**Comment by jasonmp85** [comment]
Hey all, I've opened a pull request which _should_ be backportable to address this on existing clusters. The underlying issue (different commands deparse constraint names in different ways) has resulted in this complication being necessary and it might be nice to normalize names in the upgrade scripts leading to the next version.

**Comment by jasonmp85** [comment]
@marcoslot… I was considering returning to the old logic of _don't extend constraint names unless they have an associated index_, but it sounds like you'd rather move us to _extend all constraint names_, right?

I think _something_ should be done about the current state, so pick one way or the other and I'll write it up. I'm thinking an SQL upgrade script to normalize any previous non-extended names plus changes to unify how constraint names are generated in call cases.
