### ISSUE TITLE
Propagate DDL commands to workers v2

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#25]
Citus 5.0 propagates `Alter Table` and `Create Index` commands to worker nodes. We implemented this feature using Citus' current replication model. We also decided to switch to using 2PC (or pg_paxos) once the metadata propagation changes were implemented.

This issue tracks v2 of the DDL propagation changes and depends on #19.

**Comment by lithp** [comment]
#513 also relates to this issue. `ALTER TABLE ... SET NOT NULL` can have partial failures if some shards have rows with null values

**Comment by onderkalaci** [comment]
I have a question here. Are there any blockers not to support `CONCURRENTLY` for index creation?

**Comment by aamederen** [comment]
#633 relates to improving DDL propagation support for rename related commands.

**Comment by ozgune** [comment]
@onderkalaci -- We're now tracking ``CREATE INDEX CONCURRENTLY`` in #1007.

The reason we currently don't support it is failure semantics. With ``CREATE INDEX``, we can issue the command and wait for it to complete or error out. ``CREATE INDEX CONCURRENTLY`` runs in the background, so we may need to incorporate more logic to handle out-of-band errors.

**Comment by anarazel** [comment]
On 2016-12-20 12:00:03 -0800, Ozgun Erdogan wrote:
> @onderkalaci -- We're now tracking ``CREATE INDEX CONCURRENTLY`` in #1007.
> 
> The reason we currently don't support it is failure semantics. With ``CREATE INDEX``, we can issue the command and wait for it to complete or error out. ``CREATE INDEX CONCURRENTLY`` runs in the background, so we may need to incorporate more logic to handle out-of-band errors.

CREATE INDEX CONCURRENTLY doesn't run in the background? Isn't the issue
that you can't run it in a transaction, so we can't rollback if one of
the CREATE INDEXes fails?

**Comment by marcocitus** [comment]
Most of the issues referenced here are closed. DDL is now transactional, parallel, and supports many more commands, including `CREATE INDEX CONCURRENTLY`. We can use individual issues to track missing features (or open a new parent issue).
