### ISSUE TITLE
Enabling pg_stat_statements crashes when running queries on distributed tables

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#251]
Enabling pg_stat_statements crashes when running queries on distributed tables. pg_stat_statements hooks into executor/planner and tries to access structures not initialized for distributed execution

That said, our users reported that they tried this extension and it worked on Citus 4.1.

Email excerpts from Hunter on pg_stat_statements:

Thanks for the note. It's not a problem for us to not have pg_stat_statements for queries executed against citus from the master node. But we would really like it if pg_stat_statements were available for non-slave directed queries run on the master, of which we have a fair number. Since queries run against non-distributed tables follow the usual postgres path, it seems pretty reasonable to ask that we'd be able to track them using the standard tool for such things -- pretty much every PostgreSQL DBA uses pg_stat_statements, and for good reason.

I have verified that pg_stat_statements works on Citus 4 master and worker nodes.

**Comment by aamederen** [comment]
I have installed pg_stat_statements on my local machine and tested with some queries (both distributed and non-distributed tables, subquery joins, etc) and not encountered any problems. pg_stat_statements table grows well and shows data even for distributed queries (not accurate though).

```
postgres=# SELECT count(*) FROM 
postgres-# github_events t1, github_events_append t2 
postgres-# WHERE t1.repo_id = t2.repo_id;
  count  
---------
 1101049
(1 row)

Time: 6774.647 ms
postgres=# SELECT query, total_time FROM pg_stat_statements;
                                             query                                             | total_time 
-----------------------------------------------------------------------------------------------+------------
 SELECT count(*) FROM github_events t1, github_events_append t2 WHERE t1.repo_id = t2.repo_id; |       0.03
 (temp table creation)                                                                         |       1.03
 (copy job)                                                                                    |      0.318
 SELECT pg_stat_statements_reset();                                                            |      0.107
(4 rows)
```

**Comment by anarazel** [comment]
On 2016-02-04 12:23:48 -0800, Ozgun Erdogan wrote:
> Enabling pg_stat_statements crashes when running queries on distributed tables. pg_stat_statements hooks into executor/planner and tries to access structures not initialized for distributed execution
> 
> That said, our users reported that they tried this extension and it worked on Citus 4.1.
> 
> Email excerpts from Hunter on pg_stat_statements:
> 
> Thanks for the note. It's not a problem for us to not have pg_stat_statements for queries executed against citus from the master node. But we would really like it if pg_stat_statements were available for non-slave directed queries run on the master, of which we have a fair number. Since queries run against non-distributed tables follow the usual postgres path, it seems pretty reasonable to ask that we'd be able to track them using the standard tool for such things -- pretty much every PostgreSQL DBA uses pg_stat_statements, and for good reason.
> 
> I have verified that pg_stat_statements works on Citus 4 master and worker nodes.

I've had a PR fixing the one issue with pg_stat_statements a while back;
IIRC it was a single line change.

**Comment by metdos** [comment]
@anarazel, Eren noted that pg_stat_statements results are not accurate on the master node. Should we fix it or document it somewhere?

**Comment by anarazel** [comment]
On 2016-04-08 07:17:47 -0700, Metin Döşlü wrote:
> @anarazel, Eren noted that pg_stat_statements results are not accurate on the master node. Should we fix it or document it somewhere?

There's several things not accurate, yes. And we also log some internal
queries without showing the query text...  I'm inclined toactually work
on imporving those, rather than documenting the weakness. Except things
like the numbers of buffers touched, we should be able to dreturn mostly
useful results. And for those where we can't, they should represent cost
on the master.

**Comment by metdos** [comment]
@anarazel @ozgune 
Shall we close this and open a new issue to fix/improve pg_stat_statements results?

**Comment by sumedhpathak** [comment]
@metin: Sounds good to me.

On Fri, Apr 8, 2016 at 7:29 AM, Metin Döşlü <notifications@github.com>
wrote:

> @anarazel <https://github.com/anarazel> @ozgune
> <https://github.com/ozgune>
> Shall we close this and open a new issue to fix/improve pg_stat_statements
> results?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/citusdata/citus/issues/251#issuecomment-207452834>
>



-- 
*Sumedh Pathak*
Citus Data
650.422.9797
sumedh@citusdata.com

**Comment by aamederen** [comment]
I am closing this issue since we have seen that the crash does not occur. Result inaccuracy will be traced in #457
