### ISSUE TITLE
Replace check-multi-task-tracker-extra with a single test file

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#2517]
We currently have a separate schedule for running a lot of the regular regression tests with task-tracker as the executor. We run this schedule for every `make check`. 

To reduce the test time, I suggest adding one or two test files where we run a bunch of regular queries using task-tracker and remove the separate schedule.

**Comment by onderkalaci** [comment]
It takes 85 seconds locally. We've a meeting on `Reduce travis times`, so this seems like a good candidate.
