### ISSUE TITLE
Subquery pushdown planning with UNION/UNION ALL fails with reference tables

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#2518]
Reported by @saicitus and @marcocitus. I wanted to open an issue to not track of it.

```SQL
 CREATE TABLE test (x int, y int);
 SELECT create_distributed_table('test', 'x');

CREATE TABLE ref (a int, b int);
SELECT create_reference_table('ref');


set client_min_messages TO DEBUG;

-- unnecessarily switch to recursive planning 
 SELECT * FROM (SELECT x, y FROM test JOIN ref ON (x = a) UNION ALL SELECT x, y FROM test) a;
DEBUG:  generating subplan 1_1 for subquery SELECT test.x, test.y FROM (public.test JOIN public.ref ON ((test.x OPERATOR(pg_catalog.=) ref.a)))
DEBUG:  generating subplan 1_2 for subquery SELECT x, y FROM public.test
DEBUG:  Creating router plan
DEBUG:  Plan is router executable
DEBUG:  generating subplan 1_3 for subquery SELECT intermediate_result.x, intermediate_result.y FROM read_intermediate_result('1_1'::text, 'binary'::citus_copy_format) intermediate_result(x integer, y integer) UNION ALL SELECT intermediate_result.x, intermediate_result.y FROM read_intermediate_result('1_2'::text, 'binary'::citus_copy_format) intermediate_result(x integer, y integer)
DEBUG:  Plan 1 query after replacing subqueries and CTEs: SELECT x, y FROM (SELECT intermediate_result.x, intermediate_result.y FROM read_intermediate_result('1_3'::text, 'binary'::citus_copy_format) intermediate_result(x integer, y integer)) a
DEBUG:  Creating router plan
DEBUG:  Plan is router executable
 x | y 
---+---
(0 rows)
```

There is no reason for this query not to pushdown. We seem to have aggressive checks in `DeferErrorIfUnsupportedUnionQuery()` such that it errors out whenever we see a reference table or recurring tuple. The check seems to be added for the following types of queries, which is still valid, so we shouldn't forget those cases:

```SQL
SELECT * FROM 
(
     SELECT * FROM reference_table 
UNION
    SELECT * FROM distributed_table
);
```

**Comment by onderkalaci** [comment]
> I am thinking about allowing joins inside union if the joins is between a distributed table and a reference table on the distribution key of the table.

Why do you think we need the join to be on the distribution key?

**Comment by mtuncer** [comment]
to make sure distinctness between worker tasks
if the joins are on non-partition keys we pushing down query to workers, and merging results in the end might result in wrong result.

I haven't checked coordinator part of the query (yet).

**Comment by mtuncer** [comment]
I am thinking similar what we do for following query t1(a)
```sql
select * from ( select a from t1  union select a from t1) a;
```
since a is the distribution key, we can safely push down query to worker shard pairs without worrying about duplicate entries in the output.

**Comment by mtuncer** [comment]
if the distribution key is on the target list, I think forcing join to be on distribution key is not necessary.

**Comment by onderkalaci** [comment]
> if the distribution key is on the target list, I think forcing join to be on distribution key is not necessary.

I think, that is already enforced via this [function](https://github.com/citusdata/citus/blob/1abfce9969ee869179baa232a244d39a0661414f/src/backend/distributed/planner/relation_restriction_equivalence.c#L212-L349).

To pushdown subqueries, we currently require two things (a) all subqueries inside the unions have distribution key eq. among distributed tables (b) all subqueries have a distribution key on the same ordinal position in the target list

I think what we need to do is relax the checks in `DeferErrorIfUnsupportedUnionQuery()` regarding reference tables. After that, make sure that all of the leaf subqueries of UNION/UNION ALL contains at least one distributed table. That'd enforce the necessary equality constraints among distributed tables. 

Does that make sense to you as well?

**Comment by mtuncer** [comment]
yes that was my thought (not exactly but probably 95%)

I will need to work on `HasRecurringTuples`. Perhaps I should re-consider that name first. Name itself does not reveal much about what it does.

**Comment by onderkalaci** [comment]
> I will need to work on HasRecurringTuples. Perhaps I should re-consider that name first. Name itself does not reveal much about what it does.

Feel free to change the name. The reasoning behind the name is that (a) reference tables (b) intermediate results (c) `SELECT 5;` type of constant values (d) `SELECT * FROM generate_series()` type of functions would recur per each shard on distributed tables.

Just FYI: My thinking was to use something similar like `DeferErrorIfFromClauseRecurs()` to ensure whether all of the union/union all subqueries contains at least one distributed table.
