### ISSUE TITLE
Handle function calls in joins

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#2519]
This would be a nice warm-up task to become familiar with the Citus planner and Postgres data structures.

Currently, the following fails on Citus because it tries to do the function call on the workers:
```
CREATE TABLE test (x int, y int);
SELECT create_distributed_table('test','x');
CREATE SEQUENCE numbers;
SELECT * FROM test JOIN nextval('numbers') n ON (x = n);
...
WARNING:  relation "public.numbers" does not exist
WARNING:  relation "public.numbers" does not exist
ERROR:  failed to execute task 1
```

There is an easy workaround, which is to wrap the function call in a subquery.
```
SELECT * FROM test JOIN (SELECT * FROM nextval('numbers') n)  nv ON (x = n);
```

It would be nice if it just worked.

**Comment by hanefi** [comment]
I started working on this task ( see #2572 ). I realized that this proposed workaround does not always work, and for some cases some more action needs to be taken.


Here are some cases of function calls that are quite hard to tackle along with their complications and my ideas on how to tackle them:
- Function calls that are in the right side of a `LATERAL JOIN`
  - The inputs to the function that reference cloumns of previous tables are stored in `varno` entries. When a subquery is introduced that wraps the function, this input reference now needs to point to a `var` in the parent query and AFAIK there is no easy way to do this.
  - If we use a column of a table expression as input to a function, we modify the query tree to include `LATERAL JOIN`s, therefore some CTE's do not work.
  - Proposed solution:
    - incrementing `varlevelsup` attribute of all `Var` nodes. (for subquery `Var`s referencing outer relations, this shows how many levels up one must travel to find the referenced column)
    - Note: I was not successful in my attempts to do this. Either I am doing something wrong or this does not solve our problem.
- Joining user-defined immutable functions
  - Currently we treat immutable functions as if they are reference tables ( see [here](https://github.com/citusdata/citus/blob/1656b519c49062dee5bb5fc8174963821dda9f17/src/backend/distributed/planner/query_pushdown_planning.c#L998) ). If this function is not defined in workers, we fail to execute queries.
  - Proposed solution alternatives:
    1. Put `OFFSET 0` at the subqueries to force pushdown planning and not treat the function like a reference table.
    2. Change the behaviour of `query_pushdown_planning` and defer an error if the immutable function is a user defined one
- Functions returning a table/a record/setof records
  - This requires creating `TargetEntry` nodes for all the columns the function returns. Accessing the column types, names and a lot more information is needed for this to work properly.
  - I am currently working on solving this on #2572 .  If/When I can get these function joins working, I'll update this entry here.
- Functions with a `ROWS FROM` clause ( these have multiple function calls in a list )
  - Wrapping the functions in subqueries does not work as postgres does not allow having a subquery after a ROWS FROM clause.
  - No proposed solution yet.
- Functions with a `WITH ORDINALITY` clause
  - This clause forces the result type to be RECORD/SETOF RECORD. When record returning functions are supported, this will be supported as well

**Comment by onderkalaci** [comment]
@hanefi  it is OK to close this issue, or do we have anything remaining to implement?

**Comment by hanefi** [comment]
I think it is good for now.

At some point we may want to stop wrapping a distributed function in a subquery. If a function is distributed, we may stop forcing the function to be executed on the coordinator. I guess this is out of scope of this issues. I am closing this one.
