### ISSUE TITLE
Lingering "pg_merge_job_" schemas are not cleaned up

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#2525]
Task-tracker creates some intermediate tables during the execution (and generally! drops them at the end of the execution). On the workers, all the tables are created on schemas prefixed with `pg_merge_job_`. In some cases, task-tracker fails to clean-up those schemas/tables. So, they might stay forever there.

The code is written to clean-up them, but it turns out that it doesn't. There is probably a bug there.

Related code: 

Task-tracker bg worker at init:

https://github.com/citusdata/citus/blob/d63cbf382288358533b71d907f6a3a7fc8a1df5f/src/backend/distributed/worker/task_tracker.c#L210-L223

https://github.com/citusdata/citus/blob/d63cbf382288358533b71d907f6a3a7fc8a1df5f/src/backend/distributed/worker/task_tracker.c#L359-L419

Because of that, pg_upgrade may fail. 

```
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
```

The current work around is to manually call `SELECT worker_cleanup_job_schema_cache();
` on the workers.

**Comment by ozgune** [comment]
hey @onderkalaci -- I have a quick question.

Do you know if these tables linger on after a Postgres restart?

I'm asking because there's a scenario where these tables could linger on (by design). Let's say the coordinator node sends tasks to worker nodes. After the completing the query (or canceling the query), the coordinator then tells the worker nodes to clean up. If the coordinator can't reach the worker for a certain time period, it gives up and moves on. In that case, the tables linger on the worker node.

When the user issues a restart, these lingering tables should be cleaned up though. That's why I was curious.

**Comment by onderkalaci** [comment]
> Do you know if these tables linger on after a Postgres restart?

Yes, that's actually the reason that I opened the issue. 

I can locally reproduce that. 
- Start a repartition join
- Kill one of the workers manually (kill -9 $pid)
- Restart the worker (even multiple restarts if you prefer to)
- Run the following query, you'll see the schemas lingering
``` SQL
    SELECT 
                nspname as jobSchemaNames
            FROM 
                pg_catalog.pg_namespace
            WHERE 
                nspname LIKE 'pg_merge_job%';
 ```

As far as I can tell, that prevents `pg_upgrade` to succeed.

**Comment by ozgune** [comment]
Got it. @onderkalaci -- I think this is a known issue that's documented in [this comment](https://github.com/citusdata/citus/blob/d63cbf382288358533b71d907f6a3a7fc8a1df5f/src/backend/distributed/worker/task_tracker.c#L369).

In earlier versions of Postgres, we used to read the list of database names from a "flat database file", iterate over all databases, and then clean up schemas / tables. After PG deprecated this file (and we rebased to a newer version of Postgres), we didn't spend the time to fix this issue.

If we can determine the database name in which the Citus extension, we can quickly fix this issue.

**Comment by onderkalaci** [comment]
> Got it. @onderkalaci -- I think this is a known issue that's documented in this comment.

Thanks for the pointer, I agree that it should be a quick fix.

**Comment by sumedhpathak** [comment]
Hey @onderkalaci , we ran into this issue in Citus Cloud, where it prevented a clean upgrade. Is there a path to fixing this?
It has since caused a fair bit of pain in continuing the failed upgrade, as the procedure was left incomplete with some steps done, and others not.

**Comment by will** [comment]
It'd also be nice if `citus_prepare_pg_upgrade()` was idempotent

**Comment by onderkalaci** [comment]
@sumedhpathak 

> The current work around is to manually call SELECT worker_cleanup_job_schema_cache(); on the workers.

**Comment by onderkalaci** [comment]
> It'd also be nice if citus_prepare_pg_upgrade() was idempotent

@thanodnl just fyi, as far as I can see, it shouldn't be that hard?

**Comment by onderkalaci** [comment]
> Hey @onderkalaci , we ran into this issue in Citus Cloud, where it prevented a clean upgrade. Is there a path to fixing this?

Thinking about this a bit more, we could consider calling the necessary clean-up functions in `atexit` callback. An example call to `atexit` in Postgres source: https://github.com/postgres/postgres/blob/2247a1ea5fabafc11a6deab1c6fe822c9df45bb1/src/bin/pg_upgrade/server.c#L207
