### ISSUE TITLE
Our regression tests don't exercise FetchRegularTable()

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#253]
We ran code coverage with our regression tests. We found out that FetchRegularTable() wasn't getting called. In other words, we don't exercise "shard caching on joins" functionality at all. This is because we only start up 2 worker nodes, and stage with a shard replication factor of 2. Hadi's fdw regression tests seem to be aware of this limitation and manually lower the shard replication factor to 1. We probably want to do something similar in our regular tests.

**Comment by onderkalaci** [comment]
> It looks to me like multi_append_table_to_shard is testing this.

Same here. As far as I can see, the regression tests do not exercise `FetchForeignTable()` as seen from the code-coverage [outputs](https://codecov.io/gh/citusdata/citus/src/3ea73b7879b43ccb38fa43fc69cfa41b675eaef6/src/backend/distributed/worker/worker_data_fetch_protocol.c#L821) of the master branch.

**Comment by velioglu** [comment]
Data fetch logic has been removed by #1980 and tests have been updated by #1980 and #1991
