### ISSUE TITLE
Non-correlated subselects in the targetlistlist are buggy

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#254]
Uncorrelated subqueries (e.g. SELECT (SELECT count(*) FROM customer);) returns 0 instead of erroring out because postgres' planner converts the subselect into a initplan and removes it from the parsetree. After that NeedsDistributedPlanning() doesn't see it anymore.

Either those initplans have to be separately planned/executed or we need to error out.

I found this example because plpgsql generates equivalent plans for x := SELECT \* FROM some_distributed; (not for SELECT ... INTO x tho).

**Comment by marcocitus** [comment]
Today the subselect is separately planned and executed via recursively planning.
