### ISSUE TITLE
8.1.1 is broken

### ISSUE THREAD

**Issue by devrimgunduz** [citusdata/citus#2591]
Hi,

CREATE EXTENSION citus;

fails with:

ERROR:  58P01: could not stat file "/usr/pgsql-11/share/extension/citus--8.1-1.sql": No such file or directory
LOCATION:  read_whole_file, extension.c:3133

Looks like the .sql files are missing.

Regards, Devrim

**Comment by metdos** [comment]
Hi @devrimgunduz, which packages did you try out?

**Comment by hanefi** [comment]
I am assuming that we are talking about the packages at [Official PostgreSQL Yum repository](https://yum.postgresql.org/)

I see that the file `citus--8.1-1.sql` is missing in directory `/usr/pgsql-11/share/extension/`. On the other hand the files `citus--8.0-13.sql` and `citus--8.0-13--8.1-1.sql` are there and I am guessing that PostgreSQL was clever enough to take this path on my tests. 

@devrimgunduz can you provide more context to include the steps you took to encounter this issue?

To test this issue, I 
- Created a fresh `centos/7` machine
`docker run -it centos bash`
- Added Postgresql yum repo
`yum install https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm`
- Installed `citus_11.x86_64` package
`yum install citus_11`
- Created 1 coordinator and 2 workers, and checked the Citus Versions:
```
postgres=# select citus_version();
                                              citus_version
----------------------------------------------------------------------------------------------------------
 Citus 8.1.1 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit
(1 row)

postgres=# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description
---------+---------+------------+------------------------------
 citus   | 8.1-1   | pg_catalog | Citus distributed database
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)
```

**Comment by marcocitus** [comment]
Note that 8.1 dropped support for PostgreSQL 9.6. As of PostgreSQL 10, extensions no longer need a separate file for the precise version as CREATE EXTENSION will now follow the upgrade scripts.

**Comment by hanefi** [comment]
This problem seems to be only on `PG9.6` I tested that the packages on PG10 and PG11 are just fine.

> ERROR: 58P01: could not stat file "/usr/pgsql-11/share/extension/citus--8.1-1.sql": No such file or directory

What I do not understand is that this error message suggests this happened on PG11.

**Comment by devrimgunduz** [comment]
'cause I edited the text before submitting :( Apologies.

So, I'll rollback 8.1.1 from 9.6 repos, right?

**Comment by metdos** [comment]
> So, I'll rollback 8.1.1 from 9.6 repos, right?

Yeap, that makes sense. Thank you @devrimgunduz
