### ISSUE TITLE
Distributed don't work with OR operator

### ISSUE THREAD

**Issue by khoabeotv** [citusdata/citus#2593]
**My distributed tables**
```
SELECT create_distributed_table('ad_accounts', 'id');
SELECT create_distributed_table('ad_creatives', 'ad_account_id', colocate_with => 'ad_accounts');
```
**I had a small test with 2 queries**
```
EXPLAIN SELECT * from campaigns c 
JOIN ad_accounts ac ON ac.id = c.ad_account_id
WHERE 
  c.ad_account_id = ANY(ARRAY['act_5092490462070123', 'act_509249046207012']) 
  AND (ac.fb_import OR c.creator_id NOTNULL)

=====Query Plan======
Custom Scan (Citus Real-Time)  (cost=0.00..0.00 rows=0 width=0)
Task Count: 128
Tasks Shown: One of 128
```

```
EXPLAIN SELECT * from campaigns c 
JOIN ad_accounts ac ON ac.id = c.ad_account_id
WHERE c.ad_account_id = ANY(ARRAY['act_5092490462070123', 'act_509249046207012'])

=====Query Plan======
Custom Scan (Citus Real-Time)  (cost=0.00..0.00 rows=0 width=0)
Task Count: 2
Tasks Shown: One of 2
```

I need to query from a list of user adaccounts. Is there any solution in this case to take advantage of distribution tables?

**Comment by onderkalaci** [comment]
Related to https://github.com/citusdata/citus/issues/1537

Well, I can only think of ugly solutions which probably wouldn't perform well. But, you can try the following:

```SQL
WITH q1 AS ( SELECT * from campaigns c 
JOIN ad_accounts ac ON ac.id = c.ad_account_id
WHERE c.ad_account_id = ANY(ARRAY['act_5092490462070123', 'act_509249046207012']))
SELECT * FROM q1 WHERE (ac.fb_import OR c.creator_id NOTNULL)
```

Note that the above uses [pull&push](https://docs.citusdata.com/en/v8.1/develop/reference_processing.html#subquery-cte-push-pull-execution) execution, that's why it might be slower.

**Comment by khoabeotv** [comment]
The above is only a small test in fact I have more complex queries. This solution will make the query more complex and possibly slower.
