### ISSUE TITLE
Implement "round-robin" task assignment policy for intermediate results

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#2595]
With #2472, we've implemented round-robin task assignment policy for router queries with only reference tables. We could implement that for router queries with only intermediate results as well for the same performance considerations. 

However, the challenge is that the code that does task assignment currently very tightly coupled with shardIds and placements. We should probably first decouple task assignments/orderings from placements/shardids. 

Related to #2594 as well.

**Comment by saicitus** [comment]
+1 ran into this with a customer. Related to https://github.com/citusdata/citus/issues/1887#issuecomment-473034463

**Comment by marcocitus** [comment]
Discussed this with @hanefi . In the router planner we currently call `RoundRobinAssignTaskList` -> `ReorderAndAssignTaskList`, but only for single-task queries and only for round-robin policy and we already considered whether the placements are active. That means we could actually bypass `ReorderAndAssignTaskList` and call `RoundRobinReorder` directly. `RoundRobinReorder` does not depend on having real shards / placements.

**Comment by onderkalaci** [comment]
It looks like #1835 already implements that? I guess at that time we didn't have the intermediate results, but that seems to work fine with intermediate results as well.
