### ISSUE TITLE
Fix foreign key constraints to reference tables in partitioned tables

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#2600]
We have recently faced https://github.com/citusdata/citus/issues/2592 . Due to a change in PGs regarding foreign keys in partitioned tables.

PG used to skip foreign key push down to partitions when a FK is created on the parent partition. Now it propagates FK constraint creation down to individual partitions.

A side effect of this is the validation part. When we handle FKs, we set `skip_validation` flag before letting standard processing to execute. However, after the change, PG tries to validate each partition against any violations via running a select query.

When this happens, we try to perform a DDL operation on a shard that has already seen a select on a different connection, therefore we bail out preventing the DDL operation on a partitioned tables.

We partially fixed this by forcing sequential execution. It let us perform FK creation and detach partition operations. However, attach partition is still broken due to same issue. 

Longer term fix is to have a flag that would block such distributed select queries that come from standard processing during DDL (alter table) operations.

Note that there is still some work going on PG side when we open this issue.  I am opening this issue to not to loose track and provide the proper fix.

**Comment by mtuncer** [comment]
discussion on psql-hackers https://www.postgresql.org/message-id/f2b8ead5-4131-d5a8-8016-2ea0a31250af%40lab.ntt.co.jp

**Comment by mtuncer** [comment]
and here
https://www.postgresql.org/message-id/7ae17c95-0c99-d420-032a-c271f510112b%402ndquadrant.com

**Comment by metdos** [comment]
PostgreSQL 11.2 is released, I think we should be able to have a permanent fix now.

https://www.postgresql.org/docs/11/release-11-2.html

**Comment by pykello** [comment]
> Longer term fix is to have a flag that would block such distributed select queries that come from standard processing during DDL (alter table) operations.

@mtuncer I'm not sure if I understand the above sentence correctly. By "block", do you mean to not run the SELECT queries caused by DDLs? Or do you mean detect those SELECTs and handle them in a way that won't fail?

**Comment by pykello** [comment]
@mtuncer I think I understand what you mean now. Did you mean to not run the SELECTs in the coordinator because they will run from the worker nodes?

**Comment by mtuncer** [comment]
@pykello mostly that.

Problem is with forwarding query to workers that are performing alter table operation. Workers already perform this when they see attach partition command. We do not need coordinator sending a select query for validation.

**Comment by marcocitus** [comment]
I think skipping distributed planning for those queries such that they only run on the local data would be ok.

**Comment by pykello** [comment]
> I think skipping distributed planning for those queries such that they only run on the local data would be ok.

@marcocitus this works fine in most cases, but doesn't work if we have loaded some data into the tables before making them distributed, because we don't truncate after copying local data into  the distributed table. I'm still think about how to resolve this.

**Comment by marcocitus** [comment]
Maybe we should truncate after copying local data into the distributed table? :)

Usually if someone wants to revert they will do a `CREATE TABLE local AS SELECT * FROM distributed`, the alternative procedure almost never happens. 

Truncating would fix a few issues at once, e.g. https://github.com/citusdata/citus/issues/1770

**Comment by pykello** [comment]
Makes sense. I thought we were postponing truncation because of performance, etc.  I'll create a PR for truncation after loading.

**Comment by pykello** [comment]
Since implementing `TRUNCATE` after load isn't trivial (because of FK constraints), I'm trying to inject `LIMIT 0` to the constraint check queries for this issue and execute the locally on coordinator so constraint checks run fast and succeed even in presence of left-over local data. We'll deal with the `TRUNCATE` issues later.

**Comment by marcocitus** [comment]
Uff, foreign keys make everything super hard. You might be able to do something in ExecutorRun to actually just skip the query execution altogether.
