### ISSUE TITLE
Integration with Kubernetes

### ISSUE THREAD

**Issue by botzill** [citusdata/citus#2603]
Hi.

I would like to know if there are any plans to integrate it with kuberentes? 

Thx!

**Comment by mtuncer** [comment]
Hi @botzill 
There is no concrete plan on kubernetes integration yet.  We have an [existing issue](https://github.com/citusdata/citus/issues/425) on that opened some time ago. There is some information on that.

I will close this one in favor of [#425](https://github.com/citusdata/citus/issues/425)
