### ISSUE TITLE
\STAGE bug with HEADER option


### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#261]
Basically, when \stage creates more than 1 shards, we don't touch the \COPY parameters on each shard creation. In our case*, we have the HEADER flag on the \stage command. Thus, on each shard creation, we skip the first line in the file. So, we end up (N -1) less rows, where N is the total shard count created by the \stage. The first shard is not affected by this, because we actually need to skip the first line. I think, in production, we aim each \STAGE command to create a single shard. That's why we've never realized it.

The developer of this item should also consider whether any of the other \COPY parameters can lead to such inconsistency.

**Comment by metdos** [comment]
Fixed with #445 and #468.
