### ISSUE TITLE
Inaccurate timings in EXPLAIN ANALYZE for cold cache queries

### ISSUE THREAD

**Issue by colton-citus** [citusdata/citus#2613]
EXPLAIN ANALYZE for router queries run against cold cache misleadingly attributes time spent on the query to the coordinator when it was actually spent on workers, leading to confusion in investigations. 

Steps to reproduce: 

1. Apply and populate example schema:
```
drop table if exists t1;
create table t1(col1 int,col2 int,col3 text);
select create_distributed_table('t1','col2');
insert into t1(col1,col2,col3) select generate_series(1,10000000),floor(random()*10)::int,md5(random()::text);
```
2. Reboot cluster to get cold cache results
3. Connect to coordinator and issue router query:
```
explain analyze select count(*) from t1 where col2 = 1;
```
4. Identify worker used in (3) and restart it
5. Connect to same worker and issue query against appropriate local table:
explain analyze select count(*) from t1_102073 where col2 = 1;
6. Compare explain plans. Note similar overall times, but implausible results from coordinator copy

Example worker explain plan:
```
 Finalize Aggregate  (cost=16614.66..16614.67 rows=1 width=8) (actual time=882.279..882.279 rows=1 loops=1)
   ->  Gather  (cost=16614.44..16614.65 rows=2 width=8) (actual time=882.163..884.418 rows=3 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         ->  Partial Aggregate  (cost=15614.44..15614.45 rows=1 width=8) (actual time=874.948..874.948 rows=1 loops=3)
               ->  Parallel Seq Scan on t1_102073  (cost=0.00..14571.54 rows=417163 width=0) (actual time=0.929..857.8
22 rows=333730 loops=3)
                     Filter: (col2 = 1)
 Planning Time: 2.481 ms
 Execution Time: 884.494 ms
(9 rows)

```

Example coordinator explain plan:
```
 Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0) (actual time=885.738..885.739 rows=1 loops=1)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=ec2-34-206-28-19.compute-1.amazonaws.com port=5432 dbname=citus
         ->  Finalize Aggregate  (cost=16614.66..16614.67 rows=1 width=8) (actual time=166.809..166.809 rows=1 loops=1)
               ->  Gather  (cost=16614.44..16614.65 rows=2 width=8) (actual time=164.384..166.853 rows=3 loops=1)
                     Workers Planned: 2
                     Workers Launched: 2
                     ->  Partial Aggregate  (cost=15614.44..15614.45 rows=1 width=8) (actual time=157.810..157.810 rows=1 loops=3)
                           ->  Parallel Seq Scan on t1_102073 t1  (cost=0.00..14571.54 rows=417163 width=0) (actual time=0.007..87.527 rows=333730 loops=3)
                                 Filter: (col2 = 1)
             Planning Time: 0.057 ms
             Execution Time: 166.897 ms
 Planning Time: 0.110 ms
 Execution Time: 885.760 ms
(16 rows)
```

**Comment by colton-citus** [comment]
@saicitus has advised that he has seen this in the wild several times.

**Comment by saicitus** [comment]
We have seen this a number of times (4-5) with prospects doing POCs and existing customers. **As the distributed explain plans are deceiving, it becomes hard for the customer to identify the real bottleneck**.
 
It also happens with EXPLAIN ANALYZE BUFFERS on a distributed cold cache query where you don't see any workload using disk I/O.  But then when you profile (dstat, iotop etc) whilst the query is running you see I/O.
