### ISSUE TITLE
multi_partitioning of regress check failed (Citus 8.1.1 and PostgreSQL 11.2 at CentOS)

### ISSUE THREAD

**Issue by sunshinerxu** [citusdata/citus#2615]
Citus 8.1.1 and PostgreSQL 11.2 at CentOS, multi_partitioning of regress check failed , content of src/test/regress/regression.diffs :
@@ -710,20 +710,21 @@
 CREATE TABLE partitioning_test_reference(id int PRIMARY KEY, subid int);
 INSERT INTO partitioning_test_reference SELECT a, a FROM generate_series(1, 50) a;
 SELECT create_reference_table('partitioning_test_reference');
 NOTICE:  Copying data from local table...
  create_reference_table
 ------------------------

 (1 row)

 ALTER TABLE partitioning_test ADD CONSTRAINT partitioning_reference_fkey FOREIGN KEY (id) REFE
RENCES partitioning_test_reference(id) ON DELETE CASCADE;+ERROR:  cannot perform DDL on placement 1033, which has been read over multiple connections
 CREATE TABLE partitioning_test_foreign_key(id int PRIMARY KEY, value int);
 SELECT create_distributed_table('partitioning_test_foreign_key', 'id');
  create_distributed_table
 --------------------------

 (1 row)
 INSERT INTO partitioning_test_foreign_key SELECT * FROM partitioning_test_reference;
 ALTER TABLE partitioning_hash_test ADD CONSTRAINT partitioning_reference_fk_test FOREIGN KEY (
id) REFERENCES partitioning_test_foreign_key(id) ON DELETE CASCADE; -- check foreign keys on partitions
@@ -805,22 +806,26 @@
   3 |     7
   4 |     4
   8 |     5
   9 |    12
 (6 rows)

 DELETE FROM partitioning_test_foreign_key WHERE id = 2 OR id = 9;
 -- see data is deleted from referencing table
 SELECT * FROM partitioning_test WHERE id = 11 or id = 12;
  id | time | new_column
-----+------+------------
-(0 rows)
+----+------------+------------
+ 11 | 01-02-2011 |           
+ 11 | 01-02-2011 |           
+ 12 | 01-02-2012 |           
+ 12 | 01-02-2012 |           
+(4 rows)

 SELECT * FROM partitioning_hash_test ORDER BY 1, 2;
  id | subid
 ----+-------
   1 |     2
   3 |     7
   4 |     4
   8 |     5
 (4 rows)

======================================================================

**Comment by sunshinerxu** [comment]
$cat /etc/system-release
CentOS Linux release 7.6.1810 (Core) 
$ uname -a
Linux host 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 
GNU/Linux

**Comment by onderkalaci** [comment]
Probably relates to #2600 (cc:@mtuncer)

**Comment by mtuncer** [comment]
Update : run the tests using the latest release (8.1.1) on latest PG releases (11.2 and 10.7)

PG11.2 shows the problem as mentioned. There is an interim fix for this in the master branch.
PG 10.7 works fine with 8.1.1 without any issues.

**Comment by metdos** [comment]
Closing this in favor of #2600.
