### ISSUE TITLE
Dynamically set GUC variables for queries

### ISSUE THREAD

**Issue by exialin** [citusdata/citus#2622]
Hi,

I want to set some GUC variables provided by Postgres to test different query plans. For example, set `enable_parallel_append` to see if Parallel Append would bring some benefits. But in Citus, queries are sent to workers and executed in new sessions, so I have to change the GUC variables in `postgresql.conf` and reload the databases, which is inconvenient. So, any better ways to solve this problem?

Thanks in advance!

**Comment by pykello** [comment]
Maybe you can try `run_command_on_workers` to avoid modifying variables in worker `postgresql.conf` manually:

```sql
SELECT run_command_on_workers('ALTER SYSTEM SET enable_parallel_append TO off');
SELECT run_command_on_workers('SELECT pg_reload_conf()');
```

**Comment by exialin** [comment]
@pykello Thanks for your help!

**Comment by metdos** [comment]
Closing this issue given the solution Hadi provided.
