### ISSUE TITLE
Make shard creation atomic

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#265]
CitusDB runs each shard DDL (create table, create index, etc.) command in a separate transaction, which permits partial failures. We can fix this by making `worker_apply_ddl_command` accept multiple commands in one go.

**Comment by ozgune** [comment]
@aamederen and @sumedhpathak -- does #513 also close this issue?

**Comment by marcocitus** [comment]
No, shard xreation follows a separate (increasingly outdated) code path.

**Comment by marcocitus** [comment]
Shard creation has been transactional for a while.
