### ISSUE TITLE
Investigate if dropped-column alias issue is now fixed

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#266]
We had a problem since Citus 3.0 where dropping two or more columns caused some junk fields to be added to the SQL task query in ruleutils.c.
Apparently this was fixed in 9.4 in this commit:https://github.com/postgres/postgres/commit/9b35ddce93a2ef336498baa15581b9d10f01db9c

We could possibly now remove our check in ruleutils.c (or ruleutils_94.c) here:
`else if (rte->rtekind != RTE_SHARD) { /* Else print column aliases as needed */ get_column_alias_list(colinfo, context); }`

However, before doing so, we should validate and test more thouroughly.

This is a low-priority item for now, since we've anyway copied ruleutils.c from Postgres.

**Comment by marcocitus** [comment]
This seems to be no longer an issue.
