### ISSUE TITLE
Multi tenant primary key ordering

### ISSUE THREAD

**Issue by ozum** [citusdata/citus#2675]
Hi,

In Citus docs about multi-tenant modelling, there are two sections which provides very similar examples, but with different key orders.

[Get started example](http://docs.citusdata.com/en/v8.1/get_started/tutorial_multi_tenant.html?highlight=tenant#creating-tables) has `id, company_id` whereas [use cases example](http://docs.citusdata.com/en/v8.1/use_cases/multi_tenant.html#preparing-tables-and-ingesting-data) has `company_id, id`.

Assuming:
* `id` is most selective (actually it is unique by itself.)
* Sharding is done by `company_id` column
* 50% of queries have `WHERE id = x AND company_id = y AND others...`
* 50% of queries have `WHERE company_id = y AND others...`

Which key-ordering is preferable?

[Get started example](http://docs.citusdata.com/en/v8.1/get_started/tutorial_multi_tenant.html?highlight=tenant#creating-tables):

```sql
CREATE TABLE campaigns (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    ...
);

ALTER TABLE campaigns ADD PRIMARY KEY (id, company_id);
```

[Use cases example](http://docs.citusdata.com/en/v8.1/use_cases/multi_tenant.html#preparing-tables-and-ingesting-data):

```sql
CREATE TABLE campaigns (
  id bigserial,       -- was: PRIMARY KEY
  company_id bigint REFERENCES companies (id),
  ...
  PRIMARY KEY (company_id, id) -- added
);
```

Many thanks,

**Comment by marcocitus** [comment]
> 50% of queries have WHERE company_id = y AND others...

Because of this, company_id first seems preferable. Postgres can then decide to use the subtree under company_id y.

**Comment by ozgune** [comment]
Hi @ozum -- thank you for getting in touch with us.

Did the reply from @marcocitus resolve this issue? If it did, we'll close this issue.

Also, if you have any questions in the future, please feel free to reach out to us in our Slack channel: https://slack.citusdata.com/

**Comment by ozum** [comment]
Yes @ozgune you may close the case.

Also @marcocitus thanks for the answer.
