### ISSUE TITLE
Round robin with a distributed sub query bug

### ISSUE THREAD

**Issue by alhassan-fadel** [citusdata/citus#2680]
Hi, 

When activating the round robin task assignment policy, this query will result in unexpected behavior.
```sql
select * from (select * from ditributed_table where distributed_key = $1 ) as dist
left join reference_table as ref  on dist.ref_id = ref.id
where 1=1
```
It seems that for some reason citus sends the query to a wrong node and this warning is thrown in the master:
`WARNING:  relation "public.ditributed_table_102542" does not exist`

In one of the workers, we will find the following error:

```sql
ERROR:  relation "public.ditributed_table_102542" does not exist at character XXX
STATEMENT:  
SELECT *
 FROM ((SELECT * 
 	FROM public.ditributed_table_102542 dist1 
 	WHERE (dist1.distributed_key OPERATOR(pg_catalog.=) $1)) dist 
 LEFT JOIN public.reference_table_102446 ref ON ((dist.ref_id OPERATOR(pg_catalog.=) ref.id)))
  WHERE (1 OPERATOR(pg_catalog.=) 1)
```

Fortunately, we found that using a CTE query will solve the problem but we need to know if this is expected behavior or it is a possible bug.

Thanks,

**Comment by onderkalaci** [comment]
> it is a possible bug.

It is obviously a bug. Thanks for reporting it

**Comment by hanefi** [comment]
@alhassan-fadel we implemented the fix for this bug. It will be a part of our next releases. You can use our `master` branch to test that the query works for you.
