### ISSUE TITLE
Set shardid / jobid sequence explicitly in regression tests before staging data.

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#271]
Currently, whenever we add regression tests it messes up those tests which have explicit shard ids or job ids within them. If we explicitly set shard id and job id sequences, then we don't have to update the shard / job ids every time we add more queries or stage more data.

**Comment by sumedhpathak** [comment]
Removed 5.1 milestone from this issue.

**Comment by ozgune** [comment]
@lithp -- if we fixed this, would that resolve part of problem you're observing about updating regression test output on check-ins?

I'm tentatively assigning this issue to @aamederen assuming that the answer is yes. If not, please unassign this issue.

**Comment by lithp** [comment]
Yeah, this would definitely help the problem
