### ISSUE TITLE
Automating some of the remaining parts of release testing

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#2711]
* Concurrency Testing: We've already automated good chunk of concurrency tests via isolation tests. The items under `Concurrency testing` are mostly MX concurrency tests. Those were not possible to implement before Citus 8.0. But, with Citus 8.0, we added infrastructure to run isolation tests for Citus MX.
* Enterprise Testing : Most of the enterprise tests we execute can simply be automated with isolation tests. In fact, some of them are already automated but we still continue to do them manually. This requires some investigation before moving all to the isolation tests since some of them might already be in the tests. 
* Basic integration testing: With some basic bash/python scripts, we should be able to automate them. In fact, we should be able to integrate this to the [test-automation repo](https://github.com/citusdata/test-automation).

**Comment by metdos** [comment]
Now we are merging shard rebalancer into the enterprise repo. Should we also automatize shard rebalancer tests with this issue or would you prefer to open another issue?

**Comment by onderkalaci** [comment]
> Now we are merging shard rebalancer into the enterprise repo. Should we also automatize shard rebalancer tests with this issue or would you prefer to open another issue?

That's true, but I think `Enterprise Testing` already covers that in the release testing. So, let's only keep this issue ?
