### ISSUE TITLE
Allow users to run unsupported DDL statements manually

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#274]
Currently, we error out on the DDL commands which we don't propagate to worker shards.

However, this may lead to issues for existing users who've built their own tools to execute DDL commands. So, we need to evaluate if we should WARN in this case.

**Comment by samay-sharma** [comment]
Another solution would be to add a config `enable_ddl_propagation`. When that config setting is off, Citus wouldn't propagate any commands and would allow users to run their own scripts on the worker shards and the master node table.

**Comment by anarazel** [comment]
@sumedhpathak This would also allow to avoid issues where our current command propagation is too slow. So I think it'd make sense to schedule this for 5.1? It's a 30min fix.

**Comment by sumedhpathak** [comment]
Works for me. @ozgune Any comment or objection here?

**Comment by mtuncer** [comment]
@ozgune would you prefer if we inform user that DDL changes are not propagated if this mode is on ?
