### ISSUE TITLE
Considering rewriting tests in order to remove variant files.

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#275]
As a part of the 9.5 integration changes, we added variant files for the output of several regression tests. This solution works but it'd be better if rewrite the tests such that we don't need the variants.

**Comment by mtuncer** [comment]
There are 3 tests fitting in this area
```
multi_explain
multi_large_table_join_planning
multi_upsert
```

**Comment by mtuncer** [comment]
There are 3 points causing us the have variant files here
1- postgresql 9.5 wraps the numbers in filter clause with a single quote while typecasting, where 9.4 does not
2-  differences in explain sort key text
3 - messages related to upsert not being supported in postgresql 9.4

**Comment by mtuncer** [comment]
variant files for multi_explain and multi_large_table_join_planning are removed, but multi_upsert_0.out can not be removed.

It's better to not to run this test in 9.4

**Comment by metdos** [comment]
> It's better to not to run this test in 9.4

Is there a way to do this?
