### ISSUE TITLE
Citus and PostgreSQL 12

### ISSUE THREAD

**Issue by devrimgunduz** [citusdata/citus#2755]
Hi,

PostgreSQL 12 beta is out, and I started rolling out RPMs against it. Citus currently does not support v12. Do you have a timeline for that?

Thanks!

Regards, Devrim

**Comment by ozgune** [comment]
^ @utkuazman and @metdos 

Hi Devrim, thank you for opening this issue. We'll provide you with a concrete timeline within one week.
