### ISSUE TITLE
Use PostgreSQL planner to generate master plan

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#2761]
The physical planner currently constructs `PlannedStmt` for the part of the distributed query that is executed on the coordinator. It would be better to construct a `Query *` with a dummy function that represents the `CustomScan` and pass it to `planner()` to generate the `PlannedStmt`. That will make it easier to support SQL features such as window functions and sublinks and give better plans.

**Comment by serprex** [comment]
I created a branch [gather-row-window](https://github.com/citusdata/citus/commits/gather-row-window) which ran into how using the standard planner would help
