### ISSUE TITLE
Modifying CTEs in router queries do recursive planning

### ISSUE THREAD

**Issue by serprex** [citusdata/citus#2776]
Router planner should support things like
```
EXPLAIN
WITH t AS (SELECT id from test_id where tenant_id=1),
 t2 as (UPDATE test_id ti SET id=1 FROM t where ti.id=t.id and ti.tenant_id=1 returning ti.id, t.id)
	select * from t2;
```
without breaking query up through recursive planning. See https://github.com/citusdata/citus/issues/2400#issuecomment-425837423 for things to think about

See https://github.com/citusdata/citus/blob/6741ffd716593f09b22a01dab70f64d7c62922cd/src/backend/distributed/planner/multi_router_planner.c#L3077

**Comment by marcocitus** [comment]
As a first step we should improve function evaluation (citus_clauses.c) to only evaluate volatile functions in contexts where they only need to be evaluated once (e.g. VALUES). That way, we can safely run function evaluation on a SELECT even if it contains modifying CTEs.
