### ISSUE TITLE
Easy Homebrew for OS X users

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#279]
We need to make installing the Citus extension easier for OS X users.

This item relates to #13.

**Comment by jasonmp85** [comment]
They accepted our pull request. If you use Homebrew, a `brew update` followed by `brew install citus` will install our extension (you'll still need to `CREATE EXTENSION` on any DBs you run). Closing.

**Comment by contra** [comment]
@jasonmp85 Maybe I'm doing something wrong, but the process you outlined (brew install, then create extension) errors out with this message:

```
Citus can only be loaded via shared_preload_libraries
```

Maybe an issue with the homebrew setup for citus?

**Comment by lfittl** [comment]
@contra You'll need to add citus to the `shared_preload_libraries` setting in PostgreSQL before, and then restart the server.

Also see https://docs.citusdata.com/en/v6.0/installation/single_machine_osx.html for all steps you need to do.
