### ISSUE TITLE
Easy installation from Linux packages

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#280]
We need to have an easier installation path through apt-get and yum.

This issue relates to #13 and #226

**Comment by jasonmp85** [comment]
OK, so we're in the RPM PGDG now and I have a checklist from Christoph Berg to get into the Debian one:

  - [ ] Rewrite description to be more technical
  - [ ] Update copyright information (include PostgreSQL license for those files)
  - [ ] Move into a branch or repo that has _just_ the `debian` folder from the packaging repo
  - [ ] Add simple smoke test (ensure extension installed and can load)
  - [ ]  Bump `Standards-Version` to 3.9.7

I've got an account on [Alioth](https://alioth.debian.org) now and Christoph told me the missing bit of information about how to access the Jenkins build system (which I can now access). One the above list is complete I'll ping him again and he says he'll add our repo to the build job list :confetti_ball:!

**Comment by jasonmp85** [comment]
We're in PGDG for Debian/Ubuntu now. Closing.
