### ISSUE TITLE
citus_table_visible function hides some extra tables

### ISSUE THREAD

**Issue by furkansahin** [citusdata/citus#2818]
Back in time, we have implemented a citus table visibility infra that hides shards in mx workers. I hit to an issue that I believe that walker has false positives.

We hide tables in public schema if there is a table with the same name in citus schema. I guess the walker doesn't search for oid with the schema name appended? Didn't have time to debug yet but here is how you can reproduce the issue;

```SQL
citus=# create table citus.a(a int);
CREATE TABLE
citus=# \d
               List of relations
 Schema |        Name        |   Type   | Owner
--------+--------------------+----------+-------
 citus  | a                  | table    | citus
(1 row)

citus=# create table public.a(a int);
CREATE TABLE
citus=# \d
               List of relations
 Schema |        Name        |   Type   | Owner
--------+--------------------+----------+-------
 citus  | a                  | table    | citus
(1 row)

citus=# drop table citus.a;
DROP TABLE
citus=# \d
               List of relations
 Schema |        Name        |   Type   | Owner
--------+--------------------+----------+-------
 public | a                  | table    | citus
(1 row)
```

**Comment by onderkalaci** [comment]
I cannot reproduce this @furkansahin. Both `citus_table_is_visible()` and `pg_table_is_visible ()` only considers the relations that are in the search path. Could you somehow used non-consistent search paths for the above tests?

**Comment by marcocitus** [comment]
Seems fine, just search_path at work.
