### ISSUE TITLE
Dynamic executor for simple look-up queries

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#282]
Our users need to manually choose between one of three executors (real-time, task-tracker, and router). This introduces issues if the user is running a mixed workload -- they then need to manually set executors between different queries.

We could add another executor type, dynamic executor, that picks the right executor by looking at the query. Or, we could reintegrate the pg_shard ``SELECT`` planner logic into modify planner, and divert simple look up queries to this planner.

@onderkalaci also asked today, "if we had parameterized ``PREPARE`` support, would we need to make improvements to our constraint exclusion logic?" We need to investigate what percentage of early users query Citus using parameterized ``PREPARE``s.

**Comment by mtuncer** [comment]
router planner for single shard queries are in the works now. Here are the restrictions for this planner to get activated
- task executor type is real-time or (router until we drop this executor type configuration)
- query references to a single table, no joins, or subqueries.
- table is distributed by hash
- there are shards created for this distributed table
- where clause contains an equality match for partition column. It is AND'ed to rest of the expression.
- There is no other references to partition column inside the where clause.
- Query does not contain usual unsupported constructs like window functions, sublinks, common table expressions
