### ISSUE TITLE
how to access google doc about citus

### ISSUE THREAD

**Issue by ifquant** [citusdata/citus#2843]
https://github.com/citusdata/citus/issues/18
i  find some design doc on google drive about citus, for example https://docs.google.com/document/d/13CNsb87A5BMwEvAdKcI9eILyWa7UYBE-cBu3iKfuoRI/edit#heading=h.2n8vrtd2ibzj

i want use google account wuyouxx@gmail.com  to access this doc, but google say i have  no permission.  citus could release more design doc to community? thanks.

**Comment by hanefi** [comment]
That linked document is intended for internal use only. If you wish to learn more about our design choices you can check out our blog posts here: https://www.citusdata.com/blog/
