### ISSUE TITLE
pg_dist_node default value wrong

### ISSUE THREAD

**Issue by zlianzhuang** [citusdata/citus#2856]
test=# \d pg_dist_node
                               Table "pg_catalog.pg_dist_node"
   Column    |   Type   | Collation | Nullable |                   Default                    
-------------+----------+-----------+----------+----------------------------------------------
 nodeid      | integer  |           | not null | nextval('pg_dist_groupid_seq'::regclass)
 groupid     | integer  |           | not null | nextval('pg_dist_node_nodeid_seq'::regclass)

nodeid/groupid default is wrong.  the default values not used actual. but this looks strange.

**Comment by onderkalaci** [comment]
Already tracked on #1081, so closing this. Feel free to add your comments there. Basically, there is nothing dangerous/wrong, but, as you noted that looks unusual.
