### ISSUE TITLE
Recursive CTE docs

### ISSUE THREAD

**Issue by bologer** [citusdata/citus#2870]
I believe you should mention in FAQ section of documentation that recursive CTE is possible to do if you include [distributed key in the query](https://github.com/citusdata/citus/blob/master/src/test/regress/expected/multi_router_planner.out#L408-L418). Otherwise I was migrating to CItus and then realized that it does not support recursive CTE and then by luck I came to your tests and found out that I can actually use it, just should include dist. key.

**Comment by quentin-arzalier** [comment]
bump
