### ISSUE TITLE
Concurrent query executions and master_apply_delete_command calls result in errors in query executions.

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#288]
Concurrent query executions and master_apply_delete_command calls result in errors in query executions. The problem can be summarized as follows: shard tables are gone after the query is planned but before the task is executed.

**Comment by ozgune** [comment]
I'm noting #727 as an issue related to this one.

**Comment by marcocitus** [comment]
master_apply_delete_command was removed
