### ISSUE TITLE
Wanted: x86/i386/i686 etc .deb repo

### ISSUE THREAD

**Issue by supaplextor** [citusdata/citus#2895]
Any chance there is a Debian repository for i386? I have at least ten HP t5740's (thin client) running as worker nodes. Checked out git sources and they seem to make and make install fine... Thanks!

Edit, an older 8.0.0 release is on the Debian mirrors.

```
# apt-cache policy postgresql-11-citus
postgresql-11-citus:
  Installed: (none)
  Candidate: 8.0.0.PGDG-2
  Version table:
     8.0.0.PGDG-2 500
        500 http://mirrors.edge.kernel.org/debian buster/main i386 Packages

```

**Comment by hanefi** [comment]
Hi @supaplextor 

If you check out the recommended steps to install citus repositories for your distro at https://www.citusdata.com/download/ you will see that there is a bash script that detects your os and tries to install the correct citus repository:

```bash
curl https://install.citusdata.com/community/deb.sh | sudo bash
sudo apt-get -y install postgresql-11-citus-8.3
```

I did not try to test the script on a i386 machine, but after reading the script, I believe you will get this error message:

> Unfortunately, the Citus repository does not contain packages for non-x86_64 architectures.
>
> Please contact us via https://www.citusdata.com/about/contact_us with any issues.

If you think that this is needed for your business and we should invest resources in this area feel free to contact us using [the link above](https://www.citusdata.com/about/contact_us)
