### ISSUE TITLE
How do I use certificates to connect work nodes

### ISSUE THREAD

**Issue by efynn** [citusdata/citus#2916]
How do I use certificates to connect work nodes?
```sql
DETAIL:  FATAL:  connection requires a valid client certificate
FATAL:  connection requires a valid client certificate
```

**Comment by efynn** [comment]
The certificate can be connected directly using `psql`, I don't know how to specify the location of the certificate in the citus

**Comment by efynn** [comment]
I created certificates for every database user, not just the ca

**Comment by marcocitus** [comment]
You would normally need to use Citus enterprise which has a pg_dist_authinfo table for configuring certificate authentication.

**Comment by efynn** [comment]
Ok, thank you for your reply
