### ISSUE TITLE
Remove obsolete code paths that use TRANSMIT

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#292]
I'm adding my higher level observations about our use of the TRANSMIT command here. These observations don't impact this code review.

At a high level, we use TRANSMIT to copy a flat file between two machines. We currently call this command in five places.
- [x] stage.c -- We use TRANSMIT to stage foreign files into the cluster (file_fdw). We explored this use-case when file_fdw.c first came up, and we thought it could offer a nice alternative to Hadoop's approach to dumping flat files into the cluster. We don't have anyone using this functionality, and can remove it from our codebase.
- [ ] worker_data_fetch_protocol.c -- worker_fetch_query_results_file() uses TRANSMIT to fetch query results. This function is currently unused. The goal is to replace the TRANSMIT calls in task_tracker_executor.c (see below) with this function.
- [x] worker_data_fetch_protocol.c -- worker_fetch_foreign_file() uses TRANSMIT to cache foreign files during broadcast joins. If we deprecate the file_fdw functionality in stage.c, I'm in favor of removing this function too.
- [ ] worker_data_fetch_protocol.c -- worker_fetch_partition_file() uses TRANSMIT to copy repartitioned files. We use this function in any SQL query that involves a repartition. We could replace this transmit command with PostgreSQL's pg_read_file() or its binary equivalent if we need to.
- [ ] task_tracker_executor.c -- We use TRANSMIT to fetch remote query results. We don't need to do this in the real time executor, since we open one connection per outgoing query in that case. This particular usage may or may not be immediately removed. Some alternatives are:
    * pg_read_file(): This function is synchronous and may block the task tracker executor's loop.
    * COPY : We could reevaluate using COPY .. FROM STDIN in here.

We could have a task tracker process on the master node, and assign worker_fetch_query_results_file() to the master's task tracker process. Since this will take more time, I'd like to decouple these items from pull request 17 in GitHub.

**Comment by lithp** [comment]
I'm spending a little time looking at our unused functions and `worker_fetch_query_results_file` came up. Is this still work which might happen some day, or are we safe to remove this function?
