### ISSUE TITLE
Fix task tracker's schema cleanup logic

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#294]
In task_tracker.c, we currently have an outdated TrackerCleanupJobSchemas() function.

This function used to read the database names from DatabaseNameList, and clean up any lingering namespaces (schemas) from before at process start-up time. After the DatabaseNameList function has been deprecated, TrackerCleanupJobSchemas() did nothing.

We have three options:
1. Remove TrackerCleanupJobSchemas() completely. If the database crashes when executing tasks and we have lingering schemas, the user can manually clean up these schemas.
2. Find a way to read database names from pg_database. autovacuum seems to have logic for this, but I'm not sure about the details.
3. Create schemas in such a way that they go away if the database shuts down or crashes. (We need to keep these across sessions.)

**Comment by ozgune** [comment]
@byucesoy -- @sumedhpathak mentioned that you guys wanted to only test that our behavior is correct for #294 since this issue isn't directly related to #122. This makes perfect sense; and I'm removing the v5.2 milestone tag.

Could you provide a quick update on this issue?

**Comment by marcocitus** [comment]
Same as #2525
