### ISSUE TITLE
Add a cache for efficiently looking up pg_dist_object rows

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#2945]
Once we add procedures to pg_dist_object we need to be able to efficiently determine whether a function is distributed and what its additional properties are (distribution argument index, colocation ID). This could also be useful in the future to replicate other objects on demand if they appear in queries.

It appears we can reuse the catalog cache by initialising it with a magic number that is not used for any of the Postgres catalog tables:
https://github.com/citusdata/citus/pull/2829/files#diff-801332ee4319b28e7065fb6c9c32154eR389

**Comment by thanodnl** [comment]
Looking into the diff linked we use `SearchCatCache1` which uses a `Datum` as the lookup key. Would this work for the triplet primary key of `pg_dist_object`?
