### ISSUE TITLE
Rename types on a worker instead of dropping it when a name conflict happens with type distribution

### ISSUE THREAD

**Issue by thanodnl** [citusdata/citus#2953]
When a type gets distributed we call `worker_create_or_replace` with the create statement. If there is a conflict (same name different specification) we drop cascade the old type. This is a potential data destructive operation if there were tables that used the type.

Instead we should rename the type on the worker. This allows the user to go in and resolve conflicts without losing data at a later moment.

**Comment by marcocitus** [comment]
Fixed by #2983
