### ISSUE TITLE
Issue with query having HAVING qual

### ISSUE THREAD

**Issue by insafk** [citusdata/citus#2959]
Citus is throwing an error, whenever I execute the following query:
```sql 
SELECT FROM companies HAVING avg(revenue) > 5000;
```
Which throws the error
> ERROR: unexpected number of columns from worker: 2, expected 0

In this query, no columns are selected. I'm not sure whether this type of queries has any practical significance. But I just executed them for testing purpose.

**Comment by thanodnl** [comment]
Seems to be solved as a side effect of #3326 when we land it

**Comment by marcocitus** [comment]
Seems to be fixed
