### ISSUE TITLE
Evaluate removing postgresql-hll regression tests

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#297]
We added regression tests for HyperLogLog. These tests require manually downloading and building the HLL extension, and they aren't included as part of our standard check-full.

Evaluate removing check-multi-hll and related files from CitusDB's regression tests.

**Comment by jasonmp85** [comment]
The tests will stay. We've packaged HyperLogLog ourselves, so installing it in Travis (or on developer laptops) is trivial. I've added a variant of the relevant test's output that passes when HLL is absent, meaning I've added the tests to standard `check-full` with little developer impact. At the moment, setting the `TESTHLL` variable turns on HLL installation at test-time.
