### ISSUE TITLE
Assertion Failure: if LIMIT clause is not a constant(Rather Mutable expression)

### ISSUE THREAD

**Issue by insafk** [citusdata/citus#2976]
I was just testing some queries within Citus, and this query resulted in a crash.
```sql 
SELECT * FROM ads LIMIT extract(epoch from now())::bigint 
```

The LIMIT clause is a mutable function call and so cannot be evaluated during planning phase.
Within the code, some function is asserting that the LIMIT expression is Const which results in crash

**Comment by onderkalaci** [comment]
This is definitely not good.

What happens when you run the query with asserts disabled? If it runs without any issues, we should probably update the title to `Assertion failure ...`. I'm asking this because the priority of fixing a crash vs assertion failure is different.

**Comment by insafk** [comment]
It's Assertion failure, I tried removing those Asserts and tested it. It works fine without crashing.

Will update the title now.

**Comment by marcocitus** [comment]
Other variant of this bug `SELECT * FROM test limit (SELECT 1);`
