### ISSUE TITLE
Evaluate removing multi_task_tracker_executor.conf and binary_worker_copy_format.conf files with the new regression testing framework

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#298]
CitusDB's regression tests are now driven by the pg_regress_multi script.

With this script, we have more flexibility around reading input parameters and setting config values. This may remove the need for having additional config files such as multi_task_tracker_executor.conf and binary_worker_copy_format.conf. We need to evaluate.

**Comment by jasonmp85** [comment]
I believe this can be closed now, no?
