### ISSUE TITLE
"ERROR:  not supposed to get here, did you cheat?" with SELECT FOR UPDATE

### ISSUE THREAD

**Issue by euan-dietchef** [citusdata/citus#2988]
With the following table:

```
CREATE TABLE error_test (tenant_id INT, date TIMESTAMP WITH TIME ZONE);
SELECT create_distributed_table('error_test', 'tenant_id');
```

running either:

```
SELECT tenant_id
FROM error_test
WHERE tenant_id = 1 AND date < '2019-09-18T10:08:43.829165+01:00'::timestamptz + interval '1 second'
FOR UPDATE;
```

or:

```
SELECT tenant_id
FROM error_test
WHERE tenant_id = 1 AND date < now()
FOR UPDATE;
```

but not:
```
SELECT tenant_id
FROM error_test
WHERE tenant_id = 1 AND date < '2019-09-18T10:08:43.829165+01:00'::timestamptz
FOR UPDATE;
```

will result in:
```
ERROR:  not supposed to get here, did you cheat?
```

I'm using the latest Citus docker image (8.3.2), and found the issue was also present on 8.2.2.

http://docs.citusdata.com/en/v8.3/develop/reference_dml.html#updates-and-deletion suggests this should work, since it's on a single shard, though http://docs.citusdata.com/en/v8.3/faq/faq.html#are-there-any-postgresql-features-not-supported-by-citus possibly contradicts that?

The above is obviously a cut down version of my actual query, which was more like:
```
SELECT ...
FROM jobs
WHERE tenant_id = 1 AND start_date + timeout_seconds < now()
LIMIT 1
FOR UPDATE SKIP LOCKED;
```
(i.e., select-for-update the first available job row which has timed out, where the timeout length varies per-row)

**Comment by onurctirtir** [comment]
seems fixed already
