### ISSUE TITLE
Create tutorial that shows fast aggregations and sub-second OLAP queries

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#3]
We need to have a tutorial that shows how to ingest time-series data into Citus and to run fast aggregations on this data. These tutorials should enable customers to set up a Citus cluster themselves and run OLAP queries on real-time data.

A rough breakdown of these tasks include:
- Decide on the underlying installation platform (Docker, VM, etc.)
- Revisit the examples section in documentation
- Write an example server script to help with installation and start-up
- Introduce a cache in front of immutable shards (for historical data) to cache query fragment results
- Write an example client script to read example data in real-time and insert it in
- Install HyperLogLog and topN extensions and aggregate functions for them out of the box

**Comment by davidalejandroaguilar** [comment]
> I believe [Real Time Aggregation](https://www.citusdata.com/documentation/citus-documentation-5/tutorials/tut-real-time.html) covers this.
> 


The link is dead. Would you know what the updated link is?

**Comment by thanodnl** [comment]
Unfortunately web.archive.org didn't give a conclusion, but guessing from the slug, I think it might have moved to https://docs.citusdata.com/en/v11.3/use_cases/realtime_analytics.html or based on the description in the initial issue it might also be covered at https://docs.citusdata.com/en/v11.3/use_cases/timeseries.html
