### ISSUE TITLE
Some of docker images not using the latest pg minor version

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#3004]
In some of our docker images we do not have the latest pg minor version. For example for failtester we are using pg11.2
https://github.com/citusdata/the-process/blob/master/circleci/images/failtester/Dockerfile-11#L80

I have heard that this could cause a problem, for example if a change in pg11.5 results in an unexpected behavior in the linked image in citus, we cannot detect it currently.

Would it make sense to have a script that updates the images daily possibly? So that if there is a new minor version for postgres, it will be installed and we will be testing with that from now on instead of the old one.

This is true for other images as well, for example for `exttester` we install postgres at the time of creating the image. https://github.com/citusdata/the-process/blob/master/circleci/images/exttester/Dockerfile#L3

**Comment by JelteF** [comment]
I think updating to pg11.5 might actually fix this issue: https://github.com/citusdata/citus/issues/2827
