### ISSUE TITLE
Cancelling multi-row inserts in adaptive executor.

### ISSUE THREAD

**Issue by pykello** [citusdata/citus#3023]
We use `SequentialRunDistributedExecution()` for multi-row inserts which calls `RunDistributedExecution()` with the same execution object multiple times. A cancel terminates `RunDistributedExecution()`, but we don't check for it in `SequentialRunDistributedExecution()`, and make the next call to `RunDistributedExecution()` regardless, which might have an unexpected behaviour because the execution object was not cleaned-up in the previous round.

We should handle cancellation in `SequentialRunDistributedExecution()`.

**Comment by marcocitus** [comment]
Note that normally CHECK_FOR_INTERRUPTS throws an error so we also break out of SequentialRunDistributedExecution. This is mostly relevant when we run the executor in a HOLD_INTERRUPTS block.
