### ISSUE TITLE
COPY for append-partitioned tables

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#305]
(Ozgun will clean up this item.)

As part of the extension work, we copied the code in psql into a separate binary to continue supporting the \stage command.

We also talked about an alternative where we exposed this functionality through a user-defined function. After our conversation, we decided that the current approach was good enough and doing this "in a better way" would block the extensification work for too long.

I'm including the entire email thread below.

--
Hey Andres,

We talked about extensify-26 and whether there was an alternative that allowed us to not fork psql. We were looking to see if we can avoid code duplication. We also thought having another client-side binary may be hard from the user (deciding which binary to use and when).

An alternative that came to mind was to wrap this functionality into a UDF - similar to the functions in master_stage_protocol.c. We thought of a super draft udf alternative:

master_stage_file_to_shard(master_node name/port, 'copy command');

What do you think about talking about this alternative in tomorrow's extension sync-up?

--

Hi,

We can discuss them then, yes.

But I personally don't see the below suggestion as a realistic alternative, given that it requires the data files to be on the server that ends up actually executing the copy command. That'd make it significantly more cumbersome to load data for existing customers. They don't just have to change the path to a binary, but they'd have to use ssh or something to copy the files beforehand.

--

Hey Andres,

I'm jotting down the benefits and drawbacks ahead of our chat tomorrow. A third alternative is to first review this change and get it checked in. We can then talk about another approach if we have the time.

At a higher level, we found that users get started with the \stage command to test out CitusDB. In production however, we don't have any customers using \stage and we were evaluating why.

\stage through csql benefits:
* No need to copy file to the server
* Pull request already out
* Security benefits? -- Sumedh had a question here

stage through UDF benefits:
* Users don't need to know about / run a modified psql client
* Avoids code duplication between psql and csql
* Uniform behavior between existing stage UDFs and \stage command

--

We also talked about the historical limitations in \stage around requiring files to be on the worker nodes, and our reasons for removing those restrictions. I'm also including those emails in an unstructured fashion below.

--

Hey Samay,

We had a brief discussion on your next project. One of the issues almost all our customers have is our current restriction of loading data from one of the worker nodes (and connecting to the master node). This is a confusing setup which is hard to communicate via documentation. Another pain point this causes is the string comparison we do of hostnames based on the input connection and the worker node list, as that is often different.

We want to modify stage to remove that restriction, and allow users to load data from anywhere (including the master node). We had initially modeled this on Hadoop, but Hadoop itself now allows data loading from any node.

Could you start looking into this project? Ozgun had some specific ideas on how to do this, so after a few days of research it might be good for you guys to sync up on this.

--

Hey Samay,

I'm listing below some of the ideas I have around improving our \staging logic.

At a high level, almost every new Citus customer runs into one of these two issues: (1) they need to move their source data files to one of the workers, start psql on that worker node, but connect to the master node, and (2) the hostnames in pg_worker_list.conf and the ones returned by gethostname() need to be an exact match.

Fortunately for us, all that logic lives in master_get_candidate_nodes() -- a function that you're already familiar with. If we change \stage to default to a different UDF for node selection, we can therefore remove two important usability problems our customers observe today.

For the new function, we have a couple of design considerations:

(a) How do we evenly distribute the shards across the cluster? (Randomly pick nodes, round-robin, another policy?)
(b) Should this new policy support co-located joins (or not)?
(c) Do we support data-center aware replication?

I'm cool with focusing on (a) and solving the two usability issues that I mentioned above. If we find a policy that can also do (b) and (c), all the better.---
Hey Ozgun,

I am listing down the current high level tasks for solving the usability issues with \stage.

1. Enable \stage to be run from the master node.
1(a). Choose a node selection policy such that shards get evenly distributed throughout the cluster.
1(b). Also decide if node selection policy should support data-centre aware replication and co-location.

As you mentioned, the above can be achieved by changing the master_get_candidate_nodes() or using a new UDF for node selection.

2. Make \staging from worker nodes simpler (Still have to connect to master from the worker nodes).
2(a) Do we use the current node selection policy while using \stage from workers (i.e. place 1st replica on same node and others on randomly chosen nodes)?
* If yes, figure out a way to do this without the exact host matching comparison.
* If not, choose a node selection policy (same as master node policy(?))

2(b) Allow users to simply \stage from workers by connecting to the local postgres instance there.
* I think this is going to be more complex as currently the worker nodes don't have information about the master node.

I was thinking of tackling 1 and 2(a) first and we can think about 2(b) later. What do you think?

**Comment by metdos** [comment]
Fixed with #445 and #468.
