### ISSUE TITLE
ALTER EXTENSION citus UPDATE cannot be run after running another command

### ISSUE THREAD

**Issue by aybuket** [citusdata/citus#3074]
Problem: Running ALTER EXTENSION citus UPDATE gives error if it is not the first command of psql. 

I realised that after we install binaries for new version, if we run another command in psql, ALTER EXTENSION citus UPDATE gives an error. 

For example: 
```
> docker exec -it PostgreSQLCitus psql -U citus
psql (11.2)
Type "help" for help.

citus=> SELECT * from pgbench_accounts LIMIT 1;
ERROR:  loaded Citus library version differs from installed extension version
DETAIL:  Loaded library requires 9.0, but the installed extension version is 8.3-1.
HINT:  Run ALTER EXTENSION citus UPDATE and try again.
citus=> ALTER EXTENSION citus UPDATE; 
ERROR:  could not open relation with OID 24582
CONTEXT:  SQL statement "SELECT master_unmark_object_distributed(v_obj.classid, v_obj.objid, v_obj.objsubid)"
PL/pgSQL function citus_drop_trigger() line 28 at PERFORM
citus=> \q
could not save history to file "/home/azuredb/.psql_history": No such file or directory
> docker exec -it PostgreSQLCitus psql -U citus
citus=> ALTER EXTENSION citus UPDATE; 
ALTER EXTENSION 
```

Since this is an update operation, I'm expecting that it can be done in any part of the session especially when PostgreSQL gives HINT as "run this and try again".

**Comment by metdos** [comment]
> Problem: Running ALTER EXTENSION citus UPDATE gives error if it is not the first command of psql.

Note if directly run 'ALTER EXTENSION citus UPDATE', it works properly as implicitly mentioned by @aybuket.

**Comment by marcocitus** [comment]
I cannot reproduce this locally. Do we know which commit this is?

**Comment by aybuket** [comment]
After Hanefi updated the branch, I rerun the steps and now ALTER EXTENSION citus UPDATE works as expected.
