### ISSUE TITLE
Cartesian product problem

### ISSUE THREAD

**Issue by mbakli** [citusdata/citus#3079]
Hello, thank you for this amazing work. I have a question, suppose that we have two tables: one table contains 10 rows and it is the distributed table . The other table contains 5 rows and it is a reference table. So, when I use this query: select * from T1, T2 it should work because If we have 2 worker nodes, then every worker will take part of the rows that are different than the other node. So the Cartesian product can be applicable, all what you need is to push the results to the caller. Correct me if I have wrong understanding about this issue. Thanks for your help.

**Comment by marcocitus** [comment]
Hmz, you're right. That's on oversight in the planner.

Currently it seems the only way to get a cartesian product between distributed and a reference table is to beat it into some kind of subquery that postgres does not rewrite. 
```sql
SELECT * FROM test, (SELECT *, random() FROM ref) ref;
```

Cartesian products with a reference table are pretty useful for things like spatial joins.

**Comment by mbakli** [comment]
Thank you for your reply. I tried your example that can execute the Cartesian product between distributed and reference tables but it crashes after 1 or 2 min.

**Comment by JelteF** [comment]
Just to be clear, a fix for this is on master and will be released in 9.2.
