### ISSUE TITLE
Async metadata sync can cause replica inconsistency

### ISSUE THREAD

**Issue by pykello** [citusdata/citus#3182]
Some functions like `master_update_node()` mark `metadatasynced=false` so maintenanced asynchronously propagates metadata to worker nodes. If during this period we activate a node from the coordinator, the change won't be available immediately in the metadata workers. So DML from metadata nodes can result in inconsistent replicas. I think the fix is to disallow users from activating a node when some metadata nodes are out of sync.

**Comment by marcocitus** [comment]
Can this be closed after #3226?
