### ISSUE TITLE
Using identity column in a non-shard key

### ISSUE THREAD

**Issue by ccleve** [citusdata/citus#3187]
This is related to #511, #687, #735, #1089, and #1302. It's a bit different, though, because I don't need to use the generated key as a shard key. My code:

```
CREATE TABLE public.contacts (
    list_id integer NOT NULL,
    contact_id integer NOT NULL,
    name character varying(64)
)
ALTER TABLE public.contacts ALTER COLUMN contact_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.contacts_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT pk_list_id_contact_id PRIMARY KEY (list_id, contact_id);
SELECT create_distributed_table('contacts', 'list_id');
```
generates this error:

```
ERROR:  cannot distribute relation: contacts
DETAIL:  Distributed relations must not use GENERATED ... AS IDENTITY.
SQL state: 0A000

```
list_id is the shard key. I do not need contact_id to be part of the shard key, and I do not need it to be unique across the whole table. It just needs to be unique within a shard/list.

Do I need to use older-style SERIAL columns? Will it even work with serial columns?

Here's a bit of context on SERIAL vs IDENTITY: https://stackoverflow.com/questions/55300370/postgresql-serial-vs-identity

Is this a bug?

**Comment by marcocitus** [comment]
Citus supports serial/bigserial, but does not supported GENERATED ALWAYS AS IDENTITY yet. Thanks for the detailed example.

**Comment by bharathwaaj** [comment]
Are there any plans to support this?

Django 4.1 by default creates GENERATED ALWAYS AS IDENTITY for primary keys. This change was done here https://github.com/django/django/commit/2eea361eff58dd98c409c5227064b901f41bd0d6.

As a result, it makes it impossible to use citus with Django 4.1.

**Comment by naisila** [comment]
Closing this issue as this scenario is now supported in open source Citus.

(altering the column to become an identity column _after_ the table has been distributed is not supported yet)
