### ISSUE TITLE
copy_to_distributed_table fails loading tab delimiter CSV files

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#319]
We encountered the following on a customer pilot. We tried to load a tab delimited CSV file via `copy_to_distributed_table`, but, it failed.

To reproduce it:

```SQL
CREATE TABLE test (x int, y int, z int);
SELECT master_create_distributed_table('test', 'x', 'hash');
SELECT master_create_worker_shards('test', 4, 1);

-- INSERT some data
INSERT INTO test VALUES (1,1,1);
INSERT INTO test VALUES (2,2,2);
INSERT INTO test VALUES (3,3,3);

-- now COPY out the data to a file
COPY test TO '/tmp/test.csv' WITH CSV DELIMITER E'\t';

-- test that copied file is ok
CREATE TABLE test_local (x int, y int, z int);
COPY test_local FROM  '/tmp/test.csv' WITH CSV DELIMITER E'\t';
```

Now, run `copy_to_distributed_table`:
```bash

copy_to_distributed_table -C -d E'\t' test.csv test
ERROR:  COPY delimiter must be a single one-byte character 
```

It seems that `copy_to_distributed_table` script seems to skip the `E` character in front of the `\t` [here](https://github.com/citusdata/citus/blob/master/src/bin/scripts/copy_to_distributed_table#L68).

**Comment by ozgune** [comment]
We implemented native ``COPY`` support with #33 and #225. Once we release v5.1, we plan to deprecate support for ``copy_to_distributed_table``.

@sumedhpathak / @begriffs, does removing this script makes sense? If it does, could we close this issue?
