### ISSUE TITLE
\stage related bugs and usability issues

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#320]
I'm creating this issue to track `\stage` related issues in one place.

(We also have an open issue #305 (closed) that aims to replace \stage. Some of the following issues might be resolved with that integration.)

We currently have  5 issues open out of 11 issues that relate to \staging data to append partitioned tables.
- (Closed) Issue #261 relates to `\stage` not supporting the `HEADER` option. As a result, if the user specifies this option and `\stage` operates on a large file that creates multiple shards, we skip staging the first row in each shard.
- (Closed) Issue #164 relates to `\stage` ignoring the `PROGRAM` option.
- Issue #252 notes usability issues related to the `local-node-first` placement policy. Since this placement policy isn't the default anymore, it has lower priority.
- Issue #338 notes usability issues related to the `local-node-first` placement and how that exhibits itself for `localhost`.
- (Closed) Issue #250 relates to a bug with `\stage` supporting multiple users.
- (Closed) Issue #163 relates to a big refactoring in `\stage`. We previously had the notion of primary and secondary nodes -- each shard would first get staged to the primary node and would then get replicated from there. We no longer have this logic and this makes it easy to refactor big parts of the staging code.
- Issue #133 relates to an improvement around `\stage` and regression tests' duration.
- (Closed) Issue #67 relates to staging binary data to a distributed table.
- Issue #82 relates to a bug that triggers when filenames have double quotes within them.
- Issue #90 relates to an inconsistency between regular and foreign tables. This issue triggers when filenames have single quotes within them.
- (Closed) Issue #85 relates to an inconsistency between regular and foreign tables. This issue triggers when filenames aren't fully qualified.
- (Closed) Issue #100  relates to an inconsistency between regular and foreign tables. This issue triggers when the `\stage` command for a foreign table ends with a semi-colon.

**Comment by marcocitus** [comment]
Should we start closing these issues now that \stage is deprecated?

**Comment by ozgune** [comment]
@metdos -- could you go over these issues and mark/close the ones that are resolved by the ``COPY`` changes?

**Comment by metdos** [comment]
@ozgune -- updated the issues and the descriptions here.

**Comment by anarazel** [comment]
\stage does not exist anymore.
