### ISSUE TITLE
Flaky test overview

### ISSUE THREAD

**Issue by JelteF** [citusdata/citus#3206]
### Multi MX
- [x] multi_mx_node_metadata: verify_metadata: 58827, 59685
- [x] multi_mx_master_update_node: verify_metadata : 53199, 50060, 49363
- [ ] multi_mx_node_metadata: deadlock `LOCK TABLE pg_dist_node IN SHARE ROW EXCLUSIVE MODE`: 59801, 59991, 66984, 14420
- [x] ch_bench_having.stock_1640001 does not exist: 57728, 55861
- [x] schema ch_bench_having does not exist: 55864, 55364
- [x] multi_extension: test.maintenance_worker returning different extowner:  61418, 61605, ent-12247, ent-13644, ent-14425 (@onurctirtir & @halilozanakgul: investigated, see https://github.com/citusdata/citus/issues/3409) 
- [x] Too long with no output https://circleci.com/gh/citusdata/citus/105695
### Multi
- [ ] multi_foreign_key_relation_graph: cannot perform query with placements that were modified over multiple connections: 58829, 14452
- [x] propagate_extension_commands: wrong hstore version + cascade order inconsistent: 59648, 59688 (@onurctirtir: already fixed before merging the related pr)
- [ ] distributed_functions: there is a shard placement in node group but there are no nodes in that group: 36799
- [ ] multi_partitioning: parallel seq scan instead of append hash join: 23148, ent-12067
- [x] multi_utilities: pg_stat_get_analyze_count 0 instead of 1: 41285, 38727
- [ ] multi_partitioning: merge append instead of parallel hash join: 46835
- [ ] dml_recursive.out: FATAL:  sorry, too many clients already: ent-15184
- [ ] adaptive_executor: sum of run_command_on_workers 4 instead of 2: ent-15618
- [ ] multi_index_statements: stuck with Hangup : ent-16408

### Failure
- [x] recover_prepared_transactions wrong number in failure_ddl:
	- [x] 1 instead of 4, line 938: 4855, 39413, 33564
	- [x] 0 instead of 1, line 516: 59795
	- [x] 1 instead of 2, line 469: 42417, 26253
	- [x] 1 instead of 2, line 610: 39309, 38776, 26492
	- [x] 3 instead of 4, line 828: 35994
- [ ] failure_ddl: stuck with Hangup: 59081, ent-12066, 67328, ent-13775
- [x] failed to prepare transaction instead of connection not open: 59644, 59671
- [x] connection not open warning not shown: 54082
- [x] connection error localhost:9060: 2945
- [ ] failure_connection_establishment: dump_network_traffic number 2 instead of 1: 67145, 53622, 53419, 46489, 22419, ent-13490
- [ ] failure_connection_establishment: dump_network_traffic too many rows: 41482
- [ ] failure_connection_establishment: extra worker row with AuthenticationOk: 67352, 67782 
- [ ] failure_ddl: canceling statement due to user request : ent-13357, 68964
- [ ] failure_create_distributed_table_non_empty : canceling statement due to user request : 68184
- [ ] failure_truncate: stuck with Hangup : 70666

### Vanilla
- [ ] partition_prune: explain parallel workers launched 0 instead of 2: 69375, 62357, 53993, 49083, 44092, 42781, 32195 (#3524)

### Isolation
- [ ] isolation_ensure_dependency_activate_node: canceling statement due to user request: 48748, 38410, 36408, 34425, 30530, 30030, 2949
- [ ] isolation_ddl_vs_all: s1-master-modify-multiple-shards blocked: 47980
- [ ] isolation_distributed_deadlock_detection: canceling the transaction since it was involved in a distributed deadlock: 47975, 44981, 28660, 24393, 21365, ent-13653, ent-15166
- [ ] isolation_ref2ref_foreign_keys: ref_table_3 not waiting: 42320
- [ ] isolation_ensure_dependency_activate_node: 67138

**Comment by SaitTalhaNisanci** [comment]
I am just adding the first failing test name here, is that fine?

**Comment by JelteF** [comment]
I think that's fine, but also add the line number then. A test sometimes fails in multiple places.

**Comment by SaitTalhaNisanci** [comment]
The line number might change later though and if we are going to look at the job from circleci then we will already see why the test failed. 
When you write the other messages, what do you use as a reference? Do you read the error message and put that? I feel like writing the test name will be easier for people.

**Comment by JelteF** [comment]
For the others I put the error message or a description of the problem. Let's combine the two: e.g `{test_name} : {error message/description} : {failed jobs}

**Comment by SaitTalhaNisanci** [comment]
Yeah I think we should include test name because this list is going to get bigger and people wont be reading all the list to see if there is a similar problem, but searching for the test name is much easier. I think we can go with {test_name} : [{error message/description}] : {failed jobs} but I would say error message/description should be optional because people dont even open their failing tests and writing the error message requires more work. test_name and job id are enough to take a look at the issue later.

**Comment by JelteF** [comment]
I updated all the failing tests with name of the test for easy searching.

**Comment by onurctirtir** [comment]
Me and Ozan, investigated the below flaky test, opened an issue for it and attached the link to investigation by editing Jelte's main issue comment, fyi

>   multi_extension: test.maintenance_worker returning different extowner: 61418, 61605, ent-12247, ent-13644, ent-14425

**Comment by SaitTalhaNisanci** [comment]
I think we should fix our flaky tests as soon as possible, currently I almost always try at least once more for CI to pass.

**Comment by onurctirtir** [comment]
Probably not applicable anymore as we don't see any more occurrences of them.
