### ISSUE TITLE
DROP SCHEMA support

### ISSUE THREAD

**Issue by serprex** [citusdata/citus#3210]
https://github.com/citusdata/citus/blob/master/src/test/regress/expected/distributed_functions.out

This test leaves the `function_tests`/`function_tests2` schema on workers, along with all the distributed functions. We have a `src/backend/distributed/commands/schema.c` which only implements dropping distributed tables when a `DROP SCHEMA CASCADE` occurs

Should we be propagating `DROP`/`ALTER` for schemas when they're in pg_dist_object?

**Comment by marcocitus** [comment]
We should, but the challenge is to do it in a transaction block, since the preceding statements may have accessed objects in the schema over multiple connections. 

We could consider propagating DROP SCHEMA when it is issued outside of a transaction block.
