### ISSUE TITLE
ERROR: XX000: unsupported aggregate function string_agg

### ISSUE THREAD

**Issue by kevinlinhg** [citusdata/citus#3212]
Hi,

I am recently migrating my company's single-server Postgres database to servers with a Citus deployment. 

One of our old queries uses `string_agg()` and it works well in a single-server Postgres environment. The query looks like this:

```
SELECT nw.id, nw.word, STRING_AGG(nwam.author_name, '、、' ORDER BY nwam.id) AS customers, COUNT(*) AS num, STRING_AGG(nwam.dialogue_id::text, '、、' ORDER BY nwam.id) AS dialogue_ids, STRING_AGG(nwam.content_id::text, '、、' ORDER BY nwam.id) AS content_ids 
FROM conf.negative_word AS nw 
INNER JOIN conf.negative_word_author_map AS nwam 
ON nw.id = nwam.nw_id 
WHERE nw.status = 1 AND nw.is_dangerous = 1 AND nwam.author_type = 1 AND nwam.publish_time <= 1574265599 AND nwam.publish_time >= 1571587200 
GROUP BY nw.id, nw.word ORDER BY num DESC;
```

In our Citus environment, `conf.negative_word_author_map` is a distributed table and `conf.negative_word` is a reference table. 

When I tried to execute this query on Citus coordinator node, an `unsupported aggregate function string_agg` error was thrown. The full DEBUG log is copied below:

```
DEBUG:  00000: StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0
LOCATION:  ShowTransactionStateRec, xact.c:5167
LOG:  00000: statement: SELECT nw.id, nw.word, string_agg(nwam.author_name, '、、' ORDER BY nwam.id) AS customers, COUNT(*) AS num, string_agg(nwam.dialogue_id::text, '、、' ORDER BY nwam.id) AS dialogue_ids, string_agg(nwam.content_id::text, '、、' ORDER BY nwam.id) AS content_ids 
FROM conf.negative_word AS nw 
INNER JOIN conf.negative_word_author_map AS nwam 
ON nw.id = nwam.nw_id 
WHERE nw.status = 1 AND nw.is_dangerous = 1 AND nwam.author_type = 1 AND nwam.publish_time <= 1574265599 AND nwam.publish_time >= 1571587200 
GROUP BY nw.id, nw.word ORDER BY num DESC;
LOCATION:  exec_simple_query, postgres.c:975
DEBUG:  0A000: Router planner cannot handle multi-shard select queries
LOCATION:  PlanRouterQuery, multi_router_planner.c:2008
ERROR:  XX000: unsupported aggregate function string_agg
LOCATION:  GetAggregateType, multi_logical_optimizer.c:2907
```

To my understanding, `string_agg()` should not be a concern of Citus and can be passed down to the workers and handled by Postgres. This is why I do not understand it is "unsupported", as shown in the error message.

I will fully trace the source code and try to understand what was happening later when I have more time. But I am still a rookie on Citus, if anyone had any clue about what was causing this issue, or noticed I was making careless mistakes, please let me know. Thank you so much!

**Comment by serprex** [comment]
Citus only supports a specific set of aggregates by name: https://github.com/citusdata/citus/blob/99164398bfcd5db28808d6aea45e5bb38882a2d3/src/include/distributed/multi_logical_optimizer.h#L123

I'm have been working on adding support for custom aggregates, however `string_agg` is a difficult case since it doesn't implement `COMBINEFUNC`. `string_agg` is dependent on the order of rows, so the results will be wrong since each worker's results would need to be interleaved

Is `nw.id` or `nw.word` your distribution key? Ideally we should support aggregates when grouped by distribution key. However, I don't know if we actually have that support implemented

**Comment by kevinlinhg** [comment]
Hi Philip,

Thank you so much for answering my question! 

`nw` actually is a reference table, so there is no distribution key to use right?

 We will try to find an alternative to our query that is compatible with the distributed database. Your explaination helped me understood this issue much better. Thanks a lot!

**Comment by serprex** [comment]
> `nw` actually is a reference table, so there is no distribution key to use right?

Right, my bad

> We will try to find an alternative to our query that is compatible with the distributed database. Your explaination helped me understood this issue much better. Thanks a lot!

If you're output can be a bit flexible, you may be able to get away with replacing `string_agg` with an `array_agg`, but you'll also have to drop the `ORDER BY nwam.id`

If you can't be flexible, but your intermediate result set fits within memory (which, given that you're using string_agg, I believe is the case), you can wrap the intermediate results as a CTE:
```
WITH subq AS (
        SELECT nw.id, nw.word, nwam.id nwamid, nwam.author_name, nwam.dialogue_id, nwam.content_id
        FROM conf.negative_word AS nw
        INNER JOIN conf.negative_word_author_map AS nwam ON nw.id = nwam.nw_id
        WHERE nw.status = 1 AND nw.is_dangerous = 1 AND nwam.author_type = 1 AND nwam.publish_time <= 1574265599 AND nwam.publish_time >= 1571587200
)
SELECT id, word, STRING_AGG(author_name, '、、' ORDER BY nwamid) AS customers, count(*) AS num, STRING_AGG(dialogue_id::text, '、、' ORDER BY nwamid) AS dialogue_ids, STRING_AGG(content_id::text, '、、' ORDER BY nwamid) AS content_ids
FROM subq
GROUP BY id, word
ORDER BY num DESC;
```

**Comment by kevinlinhg** [comment]
Thank you so much for your suggestions! We have tested these queries. The `array_agg` query worked well for us!

**Comment by marcocitus** [comment]
Keeping this open to track string_agg support.
