### ISSUE TITLE
run_command_on_shards() doesn't run on replicated shards

### ISSUE THREAD

**Issue by jmattsson** [citusdata/citus#3214]
When using `run_command_on_shards()` in an environment where `citus.shard_replication_factor = 2` has been used, it appears the command only gets run on a single copy of that shard, rather than all copies of that shard.

I don't know if that's per design, but it was certainly counter-intuitive for me, and doesn't seem to match the docs which say *"The next level of granularity is running a command across **all shards** of a particular distributed table"* (emphasis mine).

In my case I was trying to deploy a trigger for on-demand table partitioning, and was surprised to only see the child tables appearing in one of my workers. Going back and reviewing the output of `run_command_on_shards()` I see that each `shardid` is only listed once despite there being multiple copies of said shard.

This is observed on 9.1devel from a couple of days ago.

**Comment by marcocitus** [comment]
You can use run_command_on_placements to run on a command on all replicas.

**Comment by jmattsson** [comment]
Ah, my bad - thanks for pointing it out!
