### ISSUE TITLE
Aggregate result of empty set should be initcond

### ISSUE THREAD

**Issue by pykello** [citusdata/citus#3219]
Postgres returns `initcond`'s value when there are no input tuples, but our custom aggregate implementation returns `NULL`.

**Comment by serprex** [comment]
https://github.com/citusdata/citus/blob/99164398bfcd5db28808d6aea45e5bb38882a2d3/src/backend/distributed/utils/aggregate_utils.c#L548

Addressing this when we are generating support aggregates means we can have `coord_combine_agg` created with initcond matching the aggregate it wraps

**Comment by serprex** [comment]
Took another look into this this morning. Idea: the master's aggregate expression needn't be deparsable, so we should be able to use `AGGSPLIT_FINAL_DESERIAL` in lieu of `coord_combine_agg`. Unfortunately I wasn't able to piece together a suitable expression tree for this purpose
