### ISSUE TITLE
Reference table's placement selection strategy may has limitation

### ISSUE THREAD

**Issue by hellocodeM** [citusdata/citus#3240]
### Scenario
A reference table is placed cross all worker nodes, which is read-only. Distributed transaction should be avoid, when a transaction read the reference table and write another distributed table.

The Transaction likes:
```SQL
SELECT name INTO name FROM ref_table WHERE id = 123;
INSERT INTO dis_table VALUES(d_id, name);
```

However,  I found that only the first placement of reference table could be read, and ignore the other placements. 

### Analysis
In the case of reference table, multiple placements/workers are available. However, the executor/planner could not make the best choice before the subsequent statement, due to the lack of placement info. 

I can not think of any solution for this scenario, could you give me some advice?

**Comment by marcocitus** [comment]
You can use `SET citus.task_assignment_policy TO 'round-robin'`
