### ISSUE TITLE
compiler warning: 'compareValueFunctionCall' with variable sized type 'FunctionCall2InfoData' not at the end of a struct

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#3245]
While building packages for debian (buster & stretch) in travis, we get the following warning:

```
/9.1.0.citus/src/backend/distributed/planner/shard_pruning.c:179:24: warning: field 'compareValueFunctionCall' with variable sized type 'FunctionCall2InfoData' not at the end of a struct or class is a GNU extension [-Wgnu-variable-sized-type-not-at-end]
```

This seems to be related with that [pr](https://github.com/citusdata/citus/pull/2844)

**Comment by serprex** [comment]
https://github.com/citusdata/citus/blob/cb7105d1dd3e2349fd32b9d72126de2e741059b0/configure.in#L165

That warning should be disabled

**Comment by onurctirtir** [comment]
Actually, instead of removing this flag from `configure.in`, I guess we should develop a more comprehensive solution for this warning. This is because using variable sized types as intermediate elements in a struct could really lead undefined behaviors in some other context.

**Comment by serprex** [comment]
The way to work around the warning without sacrificing the performance of having the two fields inline is to store them in the struct as only `char fcinfo_data[SizeForFunctionCallInfo(2)]` & cast to `FunctionCall2InfoData` on use

**Comment by onurctirtir** [comment]
Inspecting the PosgreSQL codebase for usage of `FunctionCallInfo`, current usage of that struct is okay to me considering the integrity of `ClauseWalkerContext`. I decided to remove this warning flag while packaging the Citus. Closing the issue
