### ISSUE TITLE
2PC should skip read-only participants?

### ISSUE THREAD

**Issue by hellocodeM** [citusdata/citus#3250]
## Scenario
Multiple workers are involved in a global transaction, some of them are read-only. When the transaction commits, all participants go through prepare and commit phases. 

However, the read-only participant has nothing to prepare, since it does not change the state of database.

## Question
Cloud Citus  optimizes 2PC to skip read-only participants, which may create great contributions in some circumstance?

**Comment by marcocitus** [comment]
Yes, it should. Thanks for the suggestion!
