### ISSUE TITLE
Force push down of function calls in a distributed transaction

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#3265]
It would be useful if `create_distributed_function` would allow you to force pushdown of stored procedure calls even if the procedure is called from a bigger stored procedure/transaction, with the restriction that the inner procedure can only do local execution and will error out if it opens a connection.

This would also be useful infrastructure for implementing co-located triggers.

**Comment by tejeswarm** [comment]
Sure @marcocitus , I think we might need some to do something at the compile/planning level to prevent such cases, the biggest challenge with Postgres PLpgSQL is, it compiles the functions but not the individual embedded SQL in it. 

I haven't looked at your draft PR yet, but I was trying to write some primitive testcases to see if my understanding of the requirements is correct. 

https://github.com/citusdata/citus/pull/5390/commits/e569c1834dc6850f89189de722936dc71e5c4916

Please eyeball it, especially the testcases, though our goal is to support triggers, I believe we should ensure the transaction semantics are not compromised in the process. This is just a hack to see the viability and the approach to take, we can discuss more in our tomorrow's meeting.

**Comment by tejeswarm** [comment]
Marco:
In citus_custom_scan.c there's some usage of workerJob->partitionKeyValue, which is set to a Const for single shard queries.
it might be a good place to check whether it's a) not null, b) equal to the distribution column argument of the procedure call
In principle, the worker could be smart enough to recognize that it is receiving a delegated procedure call (e.g. in TryToDelegateFunctionCall) and pick up the value from the distribution argument of the function call. This does assume the worker knows about distributed functions (has it in pg_dist_object).

We currently do not sync pg_dist_object metadata, though plan is to do that for Citus 11.
https://github.com/citusdata/citus/pull/5132
