### ISSUE TITLE
Commands on reference table get stuck after removing all workers

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#3281]
Reference tables get into a weird state after removing the last worker causing DDL commands to block forever after a warning.
```sql
CREATE TABLE ref (a int, b int);
SELECT create_reference_table('ref');
SELECT master_remove_node(nodename, nodeport) FROM pg_dist_node;
ALTER TABLE ref ADD COLUMN z int;
WARNING:  could not find any shard placements for shardId 102040
```

**Comment by onderkalaci** [comment]
we prevent removing of the last node (https://github.com/citusdata/citus/pull/4127) as of now, so I guess this issue does not apply anymore
