### ISSUE TITLE
User can cause segfault by directly calling coord_combine_agg or worker_partial_agg

### ISSUE THREAD

**Issue by serprex** [citusdata/citus#3328]
Example that segfaults:

```
create table nulltable(id int);
insert into nulltable values (0);
select pg_catalog.worker_partial_agg('string_agg(text,text)'::regprocedure, id) from nulltable;
```

We don't currently typecheck the aggregate. Some options, listed in order of my preference:

- use previous method of creating stub aggregates made sure to not create aggregates which would accept invalid input. This gets in the way of being zero config, so we'll likely want a typecheck path for when we're not using generated stubs unless we can have zero config path generate stubs
- when we do permission checking we can also lookup the aggregate's name & then `FuncnameGetCandidates` to make sure we end up resolving to the supplied aggregate. Use `get_fn_expr_argtype` to achieve this
- replace oid parameter with text parameter to use FuncnameGetCandidates to lookup the oid
- include a cryptographic signature alongside the arguments which tells the code that these arguments are blessed

*edit: we don't need to use `FuncnameGetCandidiates`, just lookup the info in pg_proc*

**Comment by onderkalaci** [comment]
can you trigger this via a distributed query?

**Comment by serprex** [comment]
Not without messing with table schemas on workers
