### ISSUE TITLE
query using shards in state==3 for partitioned, sharded tables.

### ISSUE THREAD

**Issue by snblitz** [citusdata/citus#3331]
A few months ago I started noticing inconsistent results when querying a partitioned and sharded table between using the parent table with time range limits and querying the underlying partition directly.

for example:
SELECT
  count(*) AS n
FROM myschema.parenttable
WHERE ts >= '2019-12-01 00:00:00'
AND ts < '2019-12-02 00:00:00' 
returns 4377277

When I select by a partition of the parent table I get roughly half the results
SELECT
  count(*) AS n
FROM myschema.parenttable_20191201 
returns 2045170

I reported this on slack on Dec 5th 2:42pm pacific time

Given some clues by Frederic's similar sounding issue (Dec 17th, 7:34am) I realized that I was likely suffering from the same problem.

Further testing shows conclusively that when doing queries against the partitions of a partitioned and sharded table, the system is mistakenly using shards in state 3.

I am running postgresql 11.1 and citusdata 8.1

Manually cleaned up the state 3 shards (so they are all state 1) and both queries now return the correct result.

**Comment by onderkalaci** [comment]
The source of the issue is that, once a parent table's shard is marked  as INACTIVE, it's partitions are not marked as INACTIVE. So, querying directly the partitions yields  the  issue explained above. This  does not happen if  the parent is queried.

The current workarounds: (a) repair the placements  of the parent table, which will re-create the corresponding shard of  the partitions (b) Use PG 12 and always query the parent table,  because PG 12 has lots of performance improvements for querying the partitioned table, so you wouldn't need to query partitions seperately

Steps to reproduce the issue:
```SQL
SET citus.shard_replication_factor TO 2;
SET "citus.replication_model" to "statement";
SET citus.shard_count TO 4;

CREATE TABLE collections_list (
	dist_key bigint,
	collection_id integer
) PARTITION BY LIST (collection_id );

SELECT create_distributed_table('collections_list', 'dist_key');
CREATE TABLE collections_list_0 
	PARTITION OF collections_list (dist_key, collection_id)
	FOR VALUES IN ( 0 );


SET client_min_messages TO DEBUG;
SET citus.log_remote_commands TO ON;

-- hitting 9701 and 9702
INSERT INTO collections_list VALUES (0, 0);
...
LOG:  issuing INSERT INTO public.collections_list_102179 (dist_key, collection_id) VALUES (0, 0)
DETAIL:  on server onderkalaci@localhost:9701 connectionId: 2
LOG:  issuing INSERT INTO public.collections_list_102179 (dist_key, collection_id) VALUES (0, 0)
DETAIL:  on server onderkalaci@localhost:9702 connectionId: 3
..
INSERT 0 1
Time: 6.492 ms

-- stop 9701
pg_ctl -D /Users/onderkalaci/Documents/data_dir/worker_9701 -o "-p 9701"  stop

-- do one more INSERT 
INSERT INTO collections_list VALUES (0, 0);
INSERT 0 1
Time: 3.705 ms

-- now placement on 9701 should be INVALID
select shardstate from pg_dist_shard_placement WHERE  shardid  = 102179 AND nodeport = 9701;
┌────────────┐
│ shardstate │
├────────────┤
│          3 │
└────────────┘
(1 row)


-- start the worker back
pg_ctl -D /Users/onderkalaci/Documents/data_dir/worker_9701 -o "-p 9701"  start

-- use both placements
 SET citus.task_assignment_policy TO "round-robin";


 -- and, query the partitions, which produces inconsistent results
 SELECT count(*) FROM collections_list_0;
┌───────┐
│ count │
├───────┤
│     1 │
└───────┘
(1 row)


SELECT count(*) FROM collections_list_0;
┌───────┐
│ count │
├───────┤
│     2 │
└───────┘
(1 row)

Time: 2.113 ms
```

I'll try to  fix  this ASAP on the master branch,  however I cannot know  when/how to backport to older versions.

**Comment by snblitz** [comment]
You might be interested in our particular use case.

We do a daily migration of partitions from our "hot" SSD backed cluster to
our longer term "warm" HDD backed cluster.

We first noticed the records disappearing when the partitions moved from
hot to warm.

We use pg_dump by partition to move the partitions very quickly.

Our work-around (pseudo-code) now that we understand the issue:

daily_migrate_partition:

if (brokenshards_in_partition) {
   fix_shards;
}
pg_dump(partition);
if (brokenshards_in_partition) {
   die "partition failure during pg_dump";
}
