### ISSUE TITLE
Automatically add local tables on the coordinator to the metadata

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#3335]
It appears to be useful to add local tables on the coordinator to the Citus metadata as single-shard tables if the coordinator is added to pg_dist_node. That way, we can, for example, move local tables to a new coordinator during an upgrade, make them visible on workers, move individual tables to workers without sharding or replication, or (in the future) do non-blocking shard splits. It may also simplify our planning logic for local+reference tables, since the router planner will determine both to be on the same node.

I'm wondering whether it's useful to internally create a shard for each of the local tables such that all of the current logic immediately applies. Otherwise, we need to change the way the shard name is generated for local tables and make various other changes (e.g. shard moves should not drop the source, but rather truncate it). 

We need to make sure that we don't lose any functionality by adding the tables to the metadata, since, for instance, not all DDL is supported on distributed tables.

**Comment by onurctirtir** [comment]
(Related https://github.com/citusdata/citus/pull/4143/)
