### ISSUE TITLE
master_add_node may fail when function declaration refers to table name

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#3378]
`create_distributed_function` creates a function on all existing nodes, and `master_add_node` creates previously distributed functions on new nodes.

However, when a function declaration refers to a distributed table in the RETURNS, DECLARE, or arguments section then function creation will fail in `master_add_node` because metadata syncing happens after function propagation.

```sql
-- Sync metadata to existing node, normally triggered by an earlier create_distributed_function
SELECT start_metadata_sync_to_node(nodename, nodeport) FROM pg_dist_node;

-- Create a distributed table
CREATE TABLE test (x int, y int);
SELECT create_distributed_table('test','x');

-- Create a function that refers to the distributed table
CREATE OR REPLACE FUNCTION public.zoop(a int)
RETURNS int
LANGUAGE plpgsql
AS $$
DECLARE
    b test.x%TYPE := 3;
BEGIN
    return a + b;
END;
$$;
SELECT create_distributed_function('zoop','$1');

-- Try to add a new node
SELECT master_add_node('localhost', 9701);
ERROR:  invalid type name "test.x%TYPE "
CONTEXT:  while executing command on localhost:9701
```

A similar issue is likely to exist for types which refer to table names.

Supporting this properly is complicated because we need to change the way we create distributed tables on workers. For now, we should not allow types or functions that refer to table names to be replicated, since it leads to operational issues.

**Comment by marcocitus** [comment]
The following does *not* break master_add_node:
```sql
CREATE OR REPLACE FUNCTION public.zoop(a int)
RETURNS int
LANGUAGE plpgsql
AS $$
DECLARE
    b int := 3;
BEGIN
    return a + b::text.x%TYPE;
END;
$$;
```

Somehow the DECLARE section is parsed at creation time, whereas the BEGIN-END section is not.

**Comment by thanodnl** [comment]
There is a guc which can control if the function body is checked during creation.
```sql
SET check_function_bodies TO off;
```

If this is set on the worker being added before we create the function, the function will actually be created.
