### ISSUE TITLE
"Local first" staging has problems with localhost

### ISSUE THREAD

**Issue by jasonmp85** [citusdata/citus#338]
Though it seems a reasonable assumption that a TCP connection from e.g. `127.0.0.1` or `::1` always resolves as having come from `localhost`, certain OSes have alternate entries in `/etc/hosts`. For instance, Ubuntu's hostfile contains `::1    ip6-localhost`, and CentOS and its ilk often return `localhost.localdomain` for local connections.

Because users often list `localhost` in their worker files, this leads to confusion, and weirdly OS-specific worker files. Using a hostname is reasonable for non-local connections, but for local connections, it would be safer to detect any _IP address_ in `127.0.0.1/8` or `::1`, and then match it to the appropriate worker file entry, treating `localhost` as "anything with those IPs".

**Comment by begriffs** [comment]
This issue affected me on a CentOS 7.2 Digital Ocean box. It causes the multi_master_protocol regression test to fail.

regression.diffs:
```diff
*** /var/lib/pgsql/citus/src/test/regress/expected/multi_master_protocol.out	2016-03-24 20:18:29.511000000 -0400
--- /var/lib/pgsql/citus/src/test/regress/results/multi_master_protocol.out	2016-03-24 20:46:27.926000000 -0400
***************
*** 24,35 ****
  (1 row)

  SELECT * FROM master_get_local_first_candidate_nodes();
!  node_name | node_port
! -----------+-----------
!  localhost |     57638
!  localhost |     57637
! (2 rows)
!
  SELECT * FROM master_get_round_robin_candidate_nodes(1);
   node_name | node_port
  -----------+-----------
--- 24,30 ----
  (1 row)

  SELECT * FROM master_get_local_first_candidate_nodes();
! ERROR:  could not find worker node for hostname: centos-2gb-sfo1-01
  SELECT * FROM master_get_round_robin_candidate_nodes(1);
   node_name | node_port
  -----------+-----------

======================================================================
```

Putting `localhost` first in my `/etc/hosts` file for ipv4 and ipv6 fixes the issue:

```diff
*** hosts.new	2016-03-24 20:44:20.478000000 -0400
--- hosts	2016-03-24 20:44:29.811000000 -0400
***************
*** 1,16 ****
--- 1,18 ----
  # Your system has configured 'manage_etc_hosts' as True.
  # As a result, if you wish for changes to this file to persist
  # then you will need to either
  # a.) make changes to the master file in /etc/cloud/templates/hosts.redhat.tmpl
  # b.) change or remove the value of 'manage_etc_hosts' in
  #     /etc/cloud/cloud.cfg or cloud-config from user-data
  # The following lines are desirable for IPv4 capable hosts
+ 127.0.0.1 localhost.localdomain localhost
  127.0.0.1 centos-2gb-sfo1-01 centos-2gb-sfo1-01
  127.0.0.1 localhost.localdomain localhost
  127.0.0.1 localhost4.localdomain4 localhost4

  # The following lines are desirable for IPv6 capable hosts
+ ::1 localhost.localdomain localhost
  ::1 centos-2gb-sfo1-01 centos-2gb-sfo1-01
  ::1 localhost.localdomain localhost
  ::1 localhost6.localdomain6 localhost6
```

**Comment by anarazel** [comment]
\stage does not exist anymore.

**Comment by jasonmp85** [comment]
So I don't think we should close this… the complaint is re: `\stage`, but the underlying problem wasn't removed and isn't in dead code (had to go check and you closed in the interim 🙄)

I believe there is still a problem inside of `WorkerGetLocalFirstCandidateNode` in how it detects whether the connecting machine is the same as the local machine. I did a bit of a spike into the best way to detect this, but it's hazy now and after merging #339 we punted on the problem.

I'm not sure anything is _crucial_ here, but `master_create_empty_shard` and `master_get_local_first_candidate_nodes` both call the above method, which may or may not be affected by the symptom described in this issue.

**Comment by jasonmp85** [comment]
(Of course, I'm not sure what `master_get_local_first_candidate_nodes` is even used for, though `master_create_empty_shard` is used by the `COPY` pipeline)

**Comment by anarazel** [comment]
I only went by #590 which listed issues that should be closed after \stage removal, which was closed without performing that action.

**Comment by jasonmp85** [comment]
OK, so `master_get_local_first_candidate_nodes` is gone now, but `master_create_empty_shard` is still around, and I think this issue technically persists.
