### ISSUE TITLE
Use list_qsort and remove SortList()

### ISSUE THREAD

**Issue by pykello** [citusdata/citus#3392]
PostgreSQL 11 introduced `list_qsort()` which is pretty much same as our `SortList()`. Now that we don't support pre-11, we can remove `SortList()` and use `list_qsort()` instead.

The difference is that `list_qsort()` receives arguments of `ListCell **`.

**Comment by serprex** [comment]
Postgres13 replaces `list_qsort`

https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=569ed7f48312c70ed4a79daec1d7688fda4e74ac
