### ISSUE TITLE
Synchronize metadata as current user

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#3398]
When we sync metadata we always do so as superuser because we need to modify tables like pg_dist_partition directly.

However, we also create tables as superuser, which means that we need to open a new session that cannot see uncommitted `CREATE TYPE`. That means we cannot support a transaction that first creates a type and then a distributed table that depends on that type. We currently work around this by creating the types in a non-transactional way, which creates other issues.

To stop this issue from proliferating we need to create distributed tables as a the current user when inside a transaction block, while changing the metadata as superuser. This is non-trivial since the OID of the uncommitted table and distribution column type need to be written to the metadata table.

**Comment by marcocitus** [comment]
I think we could just introduce some UDFs for manipulating shard metadata that check whether the user is the owner of the ((placement of the ) shard of the) distributed table. That way, we can do the metadata syncing as the regular user without doing a complicated dance between superuser and current user.

**Comment by onderkalaci** [comment]
> I think we could just introduce some UDFs for manipulating shard metadata that check whether the user is the owner of the ((placement of the ) shard of the) distributed table.

I think this makes sense. So, in functions like `DistributionCreateCommand()` instead of generating commands like `INSERT INTO pg_dist_partition...` we can generate commands `SELECT insert_into_pg_dist_partition(...)` where the function does the check whether the current user can manipulate the table identified by the parameters. Is that what you have in mind -- or am I missing anything here?

**Comment by marcocitus** [comment]
That is indeed what I have in mind.

**Comment by onderkalaci** [comment]
We fixed this issue via #5105 and several follow-up PRs
