### ISSUE TITLE
Installation not working on Ubuntu 19.04

### ISSUE THREAD

**Issue by gotqn** [citusdata/citus#3405]
I am following this [documentation][1] to install PostgreSQL and Citus extension:

    # Add Citus repository for package manager
    curl https://install.citusdata.com/community/deb.sh | sudo bash
    
    # install the server and initialize db
    sudo apt-get -y install postgresql-12-citus-9.1

and I get:

[![enter image description here][2]][2]

I have look though the bash script and it seems to do what it needs. Could anyone tell why the package is not  found? 

I am running Ubuntu 19.04 on virtual machine using Hyper-V under Windows 10. Also, I have PostgreSQL 12 install and running:

[![enter image description here][3]][3]

  [1]: http://docs.citusdata.com/en/v9.1/installation/single_machine_debian.html
  [2]: https://i.stack.imgur.com/bNXdH.png
  [3]: https://i.stack.imgur.com/HmfBE.png

**Comment by onurctirtir** [comment]
As we replied in https://askubuntu.com/a/1206309/605239, we do not release packages for Citus 9.x on Ubuntu except 16.04 & 18.04. 

This is both because Citus does only support LTS versions of Ubuntu currently and also because 19.04 has reached its EOL.

Thanks for your attention

**Comment by shodayme** [comment]
I'l having the exact same issue with Ubuntu 20.04.4 LTS
