### ISSUE TITLE
Multiple Citus Maintenance Daemon

### ISSUE THREAD

**Issue by halilozanakgul** [citusdata/citus#3409]
Dropping and re-creating Citus extension with another user creates a new Citus Maintenance Daemon.

To recreate the issue, run:
```
CREATE USER new_user SUPERUSER;
SET ROLE new_user;
DROP EXTENSION Citus;
CREATE EXTENSION Citus;
```
And to see the results, after waiting a while, run:
```
SELECT * FROM pg_stat_activity WHERE application_name = 'Citus Maintenance Daemon';
```
There normally should be only one row, however now there are two. If you do this again with another user, the daemon number increases.

This causes some flaky tests #3206 (multi-extension)
The commit that caused this seems to be 76f3933b05f29e90dc04763d8b1259c192dd0e55.
However that doesn't make the tests flaky, the commit that made this detectable by tests is 18843af688ddd638043ddae0a8dbb350e46649e8.

**Comment by onderkalaci** [comment]
@marcocitus and @pykello tagging you since the mentioned commits might be interesting to you and github wouldn't notify you automatically.

**Comment by JelteF** [comment]
I'd expect the maintenance daemon to be stopped when the extension is dropped, no matter if the user that dropped it is different than the one that created the extension.

**Comment by marcocitus** [comment]
It seems like we're missing a `StopMaintenanceDaemon` call for `DROP EXTENSION citus` like we have for `DropdbStmt`. I don't think this was caused by 76f3933, but rather a long-standing issue that was not exposed by regression tests until 18843af.

Note that it is normal to have multiple maintenance daemons when there are multiple databases with the Citus extension, but there should only ever be one maintenance daemon per database.

**Comment by onurctirtir** [comment]
As I observed while preparing enterprise release branch, it fails very frequently. Solving this issue as soon as possible would help us.

**Comment by serprex** [comment]
I've locally modified multi_extension to be able to hit this,

```
SELECT * FROM pg_stat_activity WHERE application_name = 'Citus Maintenance Daemon';

-- check that maintenance daemon gets (re-)started for the right user
CREATE USER testuser SUPERUSER;
SET ROLE testuser;
DROP EXTENSION citus;
CREATE EXTENSION citus;

SELECT * FROM pg_stat_activity WHERE application_name = 'Citus Maintenance Daemon';
select pg_sleep(10);
SELECT * FROM pg_stat_activity WHERE application_name = 'Citus Maintenance Daemon';
```

Interestingly the 2nd select has no records. The pid of the daemon before the drop is different from the two listed after sleeping for 10s

Some light is shed by this comment: https://github.com/citusdata/citus/blob/master/src/backend/distributed/utils/maintenanced.c#L539-L547

My guess is that the original maintenance daemon notices the change of user & restarts itself. In that case I'd think the new user shouldn't matter, but it is necessary (commenting out `SET ROLE` will stop hitting this issue)

There's quite a few timing related things happening here. I'm considering whether it'd be better to have a reactive fix where when two daemons exist the one with the highest pid terminates

**Comment by JelteF** [comment]
Interesting. I still think it makes sense to simply stop the daemon when the extension is dropped. When not recreating the extension that would also be what I would expect as a user, i.e. dropping the extension removes all traces of it including background daemons.
