### ISSUE TITLE
Don't normalize test failure diffs

### ISSUE THREAD

**Issue by pykello** [citusdata/citus#3417]
We normalize test outputs because in most cases we don't care about what shard id failed or which node executed a task.

When CI tests fails with addition of an error or warning, it'd be useful to see not-normalized diff instead of the normalized diff. Because the values in the error/warning message might help us with pinpointing the bug.

For example, a failure we recently got was:

```
+ status=2
+ diffs=/home/circleci/project/build-12/src/test/regress/regression.diffs
+ test -f /home/circleci/project/build-12/src/test/regress/regression.diffs
+ cat /home/circleci/project/build-12/src/test/regress/regression.diffs
diff -dU10 -w /home/circleci/project/src/test/regress/expected/cte_inline.out /home/circleci/project/build-12/src/test/regress/results/cte_inline.out
--- /home/circleci/project/src/test/regress/expected/cte_inline.out    2020-01-20 14:38:17.469291725 +0000
+++ /home/circleci/project/build-12/src/test/regress/results/cte_inline.out    2020-01-20 14:38:17.485292106 +0000
@@ -878,20 +878,21 @@
               fist_table_cte;
 DEBUG:  distributed INSERT ... SELECT can only select from distributed tables
 DEBUG:  CTE fist_table_cte is going to be inlined via distributed planning
 DEBUG:  Router planner cannot handle multi-shard select queries
 DEBUG:  performing repartitioned INSERT ... SELECT
 DEBUG:  partitioning SELECT query by column index 0 with name 'key'
 DEBUG:  distributed statement: INSERT INTO cte_inline.test_table_1960000 AS citus_table_alias (key, value) SELECT key, value FROM read_intermediate_results('{repartitioned_results_xxxxx_from_1960000_to_0}'::text[], 'binary'::citus_copy_format) intermediate_result(key integer, value text)
 DEBUG:  distributed statement: INSERT INTO cte_inline.test_table_1960001 AS citus_table_alias (key, value) SELECT key, value FROM read_intermediate_results('{repartitioned_results_xxxxx_from_1960001_to_1}'::text[], 'binary'::citus_copy_format) intermediate_result(key integer, value text)
 DEBUG:  distributed statement: INSERT INTO cte_inline.test_table_1960002 AS citus_table_alias (key, value) SELECT key, value FROM read_intermediate_results('{repartitioned_results_xxxxx_from_1960002_to_2}'::text[], 'binary'::citus_copy_format) intermediate_result(key integer, value text)
 DEBUG:  distributed statement: INSERT INTO cte_inline.test_table_1960003 AS citus_table_alias (key, value) SELECT key, value FROM read_intermediate_results('{repartitioned_results_xxxxx_from_1960003_to_3}'::text[], 'binary'::citus_copy_format) intermediate_result(key integer, value text)
+ERROR:  could not find valid entry for shard xxxxxx
```

Here it really would have helped if the shard id in the error message wasn't normalized. If it is 196000{0,1,2,3}, we should probably look for a bug in `metadata_cache.c`, or a bug in not acquiring enough locks. If it is some other value like 0, then our task creation in `insert_select_executor.c` is where to look for bugs.

One easy way to do this is to modify `src/test/regress/bin/diff` to check if it is in CI environment, and if so, also output non-normalized diff if exit code is non-zero.

**Comment by serprex** [comment]
The files without replacements should be stored in `cte_line.out.unmodified`, however that's a bit out of reach on CI. But getting a pleasant diff will be difficult because the original is itself normalized. We'd want to have a diff program that does the comparison between the modified versions, but spits out the line from `$file2` when there's a diff

It might make sense to break away from a shell script & write our diff program in Python, leverage something like https://docs.python.org/3/library/difflib.html, but that starts to get us away from easily matching vanilla diff behavior. More likely it makes sense to have a preprocessor script `./unnormalize.py "$diffresult" "$file2.unmodified"`
