### ISSUE TITLE
Different shard sizes for \stage and master_append_table_to_shard()

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#343]
I get different shard sizes for \stage and master_append_table_to_shard() for the same data.

As an example for customer_reviews_1998.csv:
- 145940480  \stage
- 145555456  master_append_table_to_shard()

Although, I couldn't find any problems with the queries.

One point to investigate would be to check if we treat "not null" columns differently.

**Comment by marcocitus** [comment]
Is this issue still relevant?

**Comment by metdos** [comment]
No, I'm closing the issue.
