### ISSUE TITLE
INSERT..SELECT with re-partition join errors out

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#3444]
I would expect the following query to fall back to INSERT..SELECT via the coordinator.

```sql
CREATE TABLE test (x int, y int);
SELECT create_distributed_table('test','x');

INSERT INTO test SELECT a.* FROM test a JOIN test b USING (y);
ERROR:  cannot perform distributed planning for the given modification
DETAIL:  Select query cannot be pushed down to the worker.
```

**Comment by marcocitus** [comment]
Interestingly, it does work when switching the columns to force it to go via the coordinator:
```sql
INSERT INTO test (y,x) SELECT a.* FROM test a JOIN test b USING (y);
```

(or the old OFFSET 0 trick)

**Comment by pykello** [comment]
It indeed falls back to INSERT ... SELECT via coordinator, and INSERT ... SELECT via coordinator errors out. I verified that we get the same error in 9.1.

I'll look into this.
