### ISSUE TITLE
Try to shorten insert_select_connection_leak test

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#3474]
As I've noted here, the test takes pretty long to finish:
https://github.com/citusdata/citus/pull/3448#issuecomment-581314119

We wanted to explicitly open an issue to keep track of it. We should consider making the test last shorter.

**Comment by pykello** [comment]
65s is not expected. It takes only couple of seconds locally. I'll look into later this week.

**Comment by SaitTalhaNisanci** [comment]
This test fails so frequently, is that because it takes long, our timeout is 2 mins.

**Comment by agedemenli** [comment]
Line 21: `INSERT INTO source_table SELECT i, 2 * i FROM generate_series(1, 10000) i;`
->**Changed 10000 to 1000**
Line 60: `INSERT INTO target_table SELECT a, CASE WHEN a < 5000 THEN b ELSE null END  FROM source_table;`
->**Changed 5000 to 500**

I've run the test four times on CircleCI and all of them, except one, took below 20 seconds. Still, doesn't seem like a good time.
Does these changes work for us? Any suggestions would be welcome.

**Comment by metdos** [comment]
> Line 21: `INSERT INTO source_table SELECT i, 2 * i FROM generate_series(1, 10000) i;`
> ->**Changed 10000 to 1000**
> Line 60: `INSERT INTO target_table SELECT a, CASE WHEN a < 5000 THEN b ELSE null END FROM source_table;`
> ->**Changed 5000 to 500**
> 
> I've run the test four times on CircleCI and all of them, except one, took below 20 seconds. Still, doesn't seem like a good time.
> Does these changes work for us? Any suggestions would be welcome.

I have 2 questions;
i. What was the running time before and after your changes
ii. Does decreasing the data amount effects the purpose of the test?

**Comment by agedemenli** [comment]
i. Before my changes, running time was sometimes even exceeding 100 seconds. After my changes, one test took 42 seconds, each of seven other tests took below 20 seconds.
ii. That is my main concern. If it does not frustrate the purpose of the test, we can easily reduce these redundant columns to get a better running time.

I've just divided these column numbers by 10 again, reducing them to 100 and 50. Now CircleCI is running tests for the 5th time and all of the first four completed tests took very short time like **~2 seconds** on CircleCI, which is very short comparing to the initial case. If we can clearly answer the second question @metdos asked, maybe we can solve this issue this way.

For anyone who wants to take a closer look: [Pipeline](https://app.circleci.com/pipelines/github/citusdata/citus?branch=shorten-insert-select-test)

**Comment by metdos** [comment]
@agedemenli you can check with git blame who made changes on this file and ask them for their opinion. It looks like in this case, it is @pykello 
https://github.com/citusdata/citus/blame/b0f9f94a5274601f9c001240688f92334202cd76/src/test/regress/sql/insert_select_connection_leak.sql
