### ISSUE TITLE
Adaptive Executor throws Out Of Memory error when pulling a lot of records to coordinator

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus#3476]
**pg_dump on 300GB database results in the below error:**
```
pg_dump: error: Dumping the contents of table "my_table" failed: PQgetResult() failed.
pg_dump: error: Error message from server: ERROR:  out of memory
DETAIL:  Failed on request of size 624 in memory context "ExecutorState".
```
**INSERT INTO SELECT via coordinator also throws Out Of Memory sometimes**

**SELECT that pulls a lot of records (~20 million records) to the coordinator node also throws OOM.**

Workaround is to change the executor type to real-time and the OOM doesn't occur.

**Comment by marcocitus** [comment]
Probably fixed by https://github.com/citusdata/citus/pull/3114

**Comment by saicitus** [comment]
@marcocitus  Should this fix be a part of 9.0 on Hyperscale (Citus)

**Comment by marcocitus** [comment]
It is part of 9.0.1

**Comment by onderkalaci** [comment]
@saicitus should we close this? Have you seen this on >9.0.1 ?

**Comment by marcocitus** [comment]
Closing until we see it on newer versions.
