### ISSUE TITLE
Improve real-time executor performance through poll()

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#352]
The real-time executor runs ``SELECT`` queries using a state machine, and uses ``pg_sleep()`` between its state transitions.

This introduces a latency of ``5 * citus.remote_task_check_interval`` for queries that touch a single table, and ``7 * citus.remote_task_check_interval`` for queries that trigger broadcast joins. By default, this adds 50-70ms to ``SELECT`` queries that span across shards. This issue relates to going from a sleep-based model to an event-driven one in the real-time executor, and replacing ``pg_sleep`` statements with ``poll``.

A couple of additional notes:

* If we think ``remote_task_check_interval`` introduces more latency than the one mentioned here, let's update the issue notes here.
* We have three internal benchmark numbers from customer engagements around the real-time executor. Our goal here was to deliver sub-second query responses to users. I'll check if these benchmarks are shared with the entire team.
* @samay-sharma and I looked at a user benchmark in detail two weeks ago. One finding was related to a particularly poor query. When this query pulled 2 million rows (57MB) to the master node, the latency increased from 18s to 20s due to ``citus.remote_task_check_interval``. (I hypothesized that this issue relates to the transmit stage in the real-time executor and could be fixed with a simple change.)

**Comment by sumedhpathak** [comment]
Removing the 5.1 release milestone as this was not planned for the current release.
