### ISSUE TITLE
error when distributing table with generated column and default timestamp

### ISSUE THREAD

**Issue by taybin** [citusdata/citus#3538]
Using postgresql-12.1 and citus-9.2.1, this was the minimal example I was able to create:

```pgsql
CREATE TABLE test_table (
    test_id    UUID    PRIMARY KEY    DEFAULT uuid_generate_v1mc(),
    gen_n     int    GENERATED ALWAYS AS (1) STORED,
    created_at    TIMESTAMPTZ NOT NULL    DEFAULT now()
);

SELECT create_distributed_table('test_table', 'test_id');
```
The error is `ERROR:  cannot cast 23 to 1184` and is 100% repeatable.  The exact numbers change depending on the exact columns in the table.

If I remove either `gen_n` or `created_at` I am able to distribute the table.

**Comment by taybin** [comment]
My workaround was to add the `created_at` column after distributing the table, which worked fine.

**Comment by serprex** [comment]
23 is `INT4OID`. 1184 is `TIMESTAMPTZOID`
