### ISSUE TITLE
Add support for Alter Index Commands

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#354]
Found this issue while testing index propagation. create/drop index commands are reflected to worker nodes, but alter index is not.

Renaming index on distributed tables is not supported. However, we do not give an error message and let master node rename the index locally. This leads to having different index names on master and worker nodes. You can not drop or do any distributed operations on this index afterwards.

It is not exactly a corruption since you can recover from it but I think it should be fixed.

Repro steps
uph(a int, b int) is a hash distributed table with 8 shards.

``` SQL
postgres=# create index ix on uph(a);
CREATE INDEX
postgres=# alter index ix rename to hix;
ALTER INDEX
postgres=# drop index ix;
ERROR:  index "ix" does not exist
postgres=# drop index hix;
WARNING:  could not receive query results from 10.179.173.10:5432
DETAIL:  Client error: index "hix_102091" does not exist
ERROR:  could not execute DDL command on worker node shards
```

You can recover from this by

``` sql
postgres=# alter index hix rename to ix;
ALTER INDEX
postgres=# drop index hix;
ERROR:  index "hix" does not exist
postgres=# drop index ix;
DROP INDEX
```

@samay-sharma  suggested this issue is more widespread than I observed. we should respond to 
`alter schema`, `alter tablespace`, `alter database`  commands too.

**Comment by marcocitus** [comment]
This has been causing quite a bit of pain for various users.
