### ISSUE TITLE
Router select queries that require master evaluation fails with prepared statements

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#3548]
```SQL
CREATE TABLE test_1 (id int, name text);
SELECT create_distributed_table('test_1', 'id');
PREPARE router_select_require_master_evaluation(int) AS SELECT json_agg(json_build_object('id', a.id, 'name', a.name)) FROM test_1 a JOIN test_1 b USING (id) WHERE id = $1 GROUP BY a.id, a.name ;

EXECUTE router_select_require_master_evaluation(1);
ERROR:  there is no parameter $1
CONTEXT:  while executing command on localhost:9701
Time: 40.670 ms
```

Both ` json_agg` and `json_build_object` are stable functions, so requiresMasterEvaluation returns true.

**Comment by taybin** [comment]
Is there a workaround for this?  Or do I need to wait for this get merged?  I looked into what it would take to downgrade citus, but I'm not sure how safe `DROP EXTENSION citus CASCADE` is.  Will that delete the partitions?

**Comment by onderkalaci** [comment]
> Will that delete the partitions?

Yes, it'd drop all the shards.

> Is there a workaround for this? 

Yes, a nasty one unfortunately. The problem is a combination of volatile/stable functions used in prepared statements. If you're sure that the functions used in the query are marked as stable but OK to be treated as immutable, you can apply the workaround.

In this case `json_build_object ` and `json_agg `, are OK to be marked as `immutable`, you can mark them immutable in pg_proc, like `update pg_proc set provolatile = 'i' WHERE proname = 'json_build_object'; `

Or, better, create `json_build_object_immutable` type of  wrapper functions and use them in the queries.

**Comment by taybin** [comment]
@onderkalaci ouch.  Okay, I'll work on that.  Thank you.

**Comment by taybin** [comment]
@onderkalaci Does setting these functions as IMMUTABLE (or wrapping them) mean they will run on the nodes, giving a performance benefit?  Or is the query re-writer more complicated than that and they sometimes run on the nodes anyways?

**Comment by taybin** [comment]
@onderkalaci The workaround worked! Thank you!

**Comment by onderkalaci** [comment]
@taybin  Is it possible for you to run your [unchanged] tests against the branch in https://github.com/citusdata/citus/pull/3553? We're planning to merge that soon, and any feedback is welcome

**Comment by taybin** [comment]
@onderkalaci I'd love to, but I'm not sure I'll be able to in a timely manner.
