### ISSUE TITLE
INSERT .. SELECT via coordinator may fail when requires access to sequence 

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#3552]
```SQL
create table table_1 (key bigserial, value int);
SELECT create_distributed_table('table_1', 'key');

create table table_2 (key bigint, value int);
SELECT create_distributed_table('table_2', 'key', colocate_with:='none');
INSERT INTO table_2  SELECT i, i % 10 FROM generate_series(0,100)i;
INSERT INTO table_1 (value) SELECT value FROM table_2 OFFSET 0;

ERROR:  result "2_1" does not exist
Time: 3.470 ms
```

This is working in Citus 9.0 but not 9.1+, likely to be related to #3183

**Comment by marcocitus** [comment]
Not sure why this worked on 9.0. The nextval call is normally pushed down to the worker where it fails. Was it working correctly?

**Comment by onderkalaci** [comment]
> This is working in Citus 9.0 but not 9.1+, likely to be related to #3183
> Not sure why this worked on 9.0. The nextval call is normally pushed down to the worker where it fails. Was it working correctly?


I tried it again, it failed with the same error on Citus 9.0.1 as well. So, probably doesn't require backport?

**Comment by marcocitus** [comment]
The error message is definitely not expected, but backport seems unnecessary, since we would just change the error message. The actual fix is involved (need to move the nextval to the master query).
