### ISSUE TITLE
multi_extension can get stuck on a spinlock

### ISSUE THREAD

**Issue by serprex** [citusdata/citus#3567]
Introduced by #3522

Reproducable with ` while make check-empty EXTRA_TESTS="multi_extension";do :;done`

**Comment by marcocitus** [comment]
Also seeing this, specifically in DROP EXTENSION.

**Comment by onderkalaci** [comment]
I've seen lots of CI failures, either Postgres cannot start at all, or all the tests starting from `multi_extension` fails.

Do we expect such cases be related to this issue?
