### ISSUE TITLE
Improve support for single shard tables

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#3583]
Single-shard tables can serve several purposes:
- Small tables with high concurrency and full SQL support that need to be accessible from any node (e.g. in delegated stored procedure calls).
- Schema-based sharding for multi-tenant applications where each table in a "distributed schema" automatically becomes a single-shard table that is co-located with the other tables in the schema.
- Stepping stone to non-blocking create_distributed_table and create_reference table by converting a local table into a local table on the coordinator and then applying shard split / shard copy primitives.

We want single-shard tables to be convertible into distributed or reference tables such that you can choose to turn a table into a distributed table even if you created it in a distributed schema. Moreover, it's a prerequisite for non-blocking create_distributed_table / create_reference_table.

We can already create single-shard hash-distributed tables, but the distribution column would be redundant. Eventually, we may want to automatically treat all local tables on the coordinator as single-shard tables, but currently that would constitute a regression in terms of SQL functionality for those tables.

For now, it might make sense to add a `create_single_shard_table` function or something similar and add a new distribution type to `pg_dist_partition`.

**Comment by onurctirtir** [comment]
I could not get the difference between reference tables & single shard tables. Does "single shard table" mean a reference table having one-and-only placement on coordinator ?

**Comment by marcocitus** [comment]
Probably the naming should be improved, since we also see reference tables as having a single shard. 

The single shard tables also only have one placement, which may be on the coordinator or any of the worker nodes.

**Comment by onurctirtir** [comment]
(Related https://github.com/citusdata/citus/pull/4143/)
