### ISSUE TITLE
Support UNION SQL syntax

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus#359]
Noted by @samay-sharma as a frequent customer facing issue.
UNIONs: I think this may be one of the most encountered SQL constructs which we don't support. Also, it is relevant in the real-time analytics context.

**Comment by onderkalaci** [comment]
> WITH month_to_date AS (
  SELECT pkey_id, sum(counter) AS counter FROM daily_data GRUOP BY pkey_id
), all_months AS (
  SELECT pkey_id, counter FROM month_to_date
  UNION ALL
  SELECT pkey_id, counter FROM monthly_data
)
SELECT pkey_id, sum(counter) FROM all_months GROUP BY pkey_id;

Verified that the above is resolved with #1894
