### ISSUE TITLE
Local execution can cause queries to go to the wrong shard or something

### ISSUE THREAD

**Issue by serprex** [citusdata/citus#3590]
```
WITH a as (SELECT rt.value_2 FROM reference_table_test rt where rt.value_2 = 2)
SELECT ct.value_1, count(*) FROM colocated_table_test ct join a on ct.value_1 = a.value_2
WHERE exists (select * from a)
GROUP BY 1 ORDER BY 1;
```

Put this at the end of `multi_reference_table.sql`. Then `make check-base EXTRA_TESTS="multi_reference_table add_coordinator multi_reference_table"`

Initially ran into this while creating test cases for #3568 where I've included changes to `local_executor.c` to work around the issue, but which I don't believe are ultimately correct

My proposed fix was to not push an empty local tasklist task. This ends up essentially tricking the adaptive executor into not thinking it's doing local execution for the latter task list, but we're supposed to error out due to read-your-own-writes reasons. Which implies we could at least allow this sort of thing if no local writes have happened in the transaction yet. However better would be to inhibit local execution from ever happening for this query

**Comment by onderkalaci** [comment]
The main reason seems that we overlooked replication factor > 1 for distributed tables during local execution. This cannot be an issue for MX, but seems a problem when reference tables are replicated on the coordinator and joined with replicated distributed tables. 

https://github.com/citusdata/citus/blob/master/src/backend/distributed/executor/local_executor.c#L314-L321

And, actually after intermediate result pruning, the statement for the intermediate results look wrong as well.

I'll think on this, but to unblock you, use replication factor = 1 in the tests you write

**Comment by serprex** [comment]
afaict replication factor = 1 didn't fix my test in HAVING PR. However, I'm not blocked, as I reduced the test to only EXPLAIN

**Comment by onderkalaci** [comment]
> afaict replication factor = 1 didn't fix my test in HAVING PR. However, I'm not blocked, as I reduced the test to only EXPLAIN

That's unexpected for me. I'll try to look the issue this week, there might be some other dimensions of the bug as well

**Comment by onderkalaci** [comment]
Setting rep. factor seems to fix the issue?
```SQL
diff --git a/src/test/regress/expected/multi_reference_table.out b/src/test/regress/expected/multi_reference_table.out
index 2012f8ee5..e3028f7df 100644
--- a/src/test/regress/expected/multi_reference_table.out
+++ b/src/test/regress/expected/multi_reference_table.out
@@ -988,7 +988,7 @@ INSERT INTO
 (1 row)
 
 SET citus.shard_count TO 6;
-SET citus.shard_replication_factor TO 2;
+SET citus.shard_replication_factor TO 1;
 CREATE TABLE colocated_table_test (value_1 int, value_2 float, value_3 text, value_4 timestamp);
 SELECT create_distributed_table('colocated_table_test', 'value_1');
  create_distributed_table
@@ -1602,6 +1602,15 @@ BEGIN;
 ALTER TABLE reference_table_test ADD COLUMN value_dummy INT;
 INSERT INTO reference_table_test VALUES (2, 2.0, '2', '2016-12-02');
 ROLLBACK;
+WITH a as (SELECT rt.value_2 FROM reference_table_test rt where rt.value_2 = 2)
+SELECT ct.value_1, count(*) FROM colocated_table_test ct join a on ct.value_1 = a.value_2
+WHERE exists (select * from a)
+GROUP BY 1 ORDER BY 1;
+ value_1 | count
+---------------------------------------------------------------------
+       2 |     5
+(1 row)
+
```

**Comment by onderkalaci** [comment]
My initial take for the fix: https://github.com/citusdata/citus/compare/fix_replicated_table_bug?expand=1
