### ISSUE TITLE
Cannot create distributed table with foreign key to reference table with local placement

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#3613]
We error out while checking the foreign key validity:

```sql
SELECT * from master_add_node('localhost', 5432, groupid := 0);
SELECT master_set_node_property('localhost', 5432, 'shouldhaveshards', true);
CREATE TABLE ref (a int primary key, b int);
SELECT create_reference_table('ref');
CREATE TABLE test (x int primary key, y int references ref (a));
SELECT create_distributed_table('test','x');
ERROR:  cannot join local tables and reference tables in a transaction block, udf block, or distributed CTE subquery
CONTEXT:  while executing command on localhost:5432
SQL statement "SELECT fk."y" FROM ONLY "public"."test_102780" fk LEFT OUTER JOIN ONLY "public"."ref_102747" pk ON ( pk."a" OPERATOR(pg_catalog.=) fk."y") WHERE pk."a" IS NULL AND (fk."y" IS NOT NULL)"
```

Edit: added master_add_node and master_set_node_property.

**Comment by onurctirtir** [comment]
+1, I also observed this bug last week, I was planning to inspect this bug in my fkey between local tables & reference tables task

**Comment by onurctirtir** [comment]
As a work around, we can still create those tables and then setting the fkey constraint between them via `alter table` commands (if it is the case that a customer falling into this issue)

**Comment by onurctirtir** [comment]
I could not reproduce the bug on master with your queries, do we any additional configurations etc. ?

**Comment by marcocitus** [comment]
Good point, this only happens when some of the `test` shards are on the coordinator.

**Comment by onurctirtir** [comment]
Inspecting the issue there, it actually seems not a bug. To explain, the table `test` is not a distributed table yet as `create_distributed_table` is not finalized yet. And as we do not allow joins between local tables & reference tables in transaction blocks, we error out there.

I purpose to:
* Early erroring out in `create_distributed_table function in a better & informative way
* Or allowing joins between local tables & reference tables within transaction blocks, which would probably cause more problems that I cannot foresee now

**Comment by onurctirtir** [comment]
Given that we now support the underlying join query and the intermediate foreign key creating (from local to reference table, before distributing `test`), this is not applicable anymore.
