### ISSUE TITLE
Evaluate joining regular tables with distributed tables

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#364]
Many people have smaller tables which they want to keep in PostgreSQL and not distribute. However, they want to join these tables with distributed tables.

The answer currently is to distribute these tables with a replication factor = number of nodes and then execute the join. This is a good answer generally, but a lot of people run into this roadblock. Also, the smaller tables usually undergo updates etc., which makes it easier if this is just a PostgreSQL table.

From a technical viewpoint, we'd need to find a way to incorporate "local tables" into our logical planner and optimizer. The Multi-relational Algebra (MRA) [paper](http://homepages.uel.ac.uk/u0214270/queryExecutionStrategies.pdf) assumes that each operator operates on a distributed table.

**Comment by marcocitus** [comment]
We could do this by wrapping local tables in a subquery. Recursive planning will then plan the subquery as a local query and broadcast the result. We will likely want to subquery to have relevant projections and filters.

**Comment by onderkalaci** [comment]
> We could do this by wrapping local tables in a subquery. Recursive planning will then plan the subquery as a local query and broadcast the result. We will likely want to subquery to have relevant projections and filters.

fyi, #2504 has the code for doing that
