### ISSUE TITLE
Foreign keys between reference tables and coordinator local tables: A different approach

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#3641]
# Current approach & quick summary

As of I started implementing foreign keys between coordinator local tables and reference tables (for the ones that are replicated to the coordinator), our current approach was simply setting up the foreign key directly on the coordinator placement of the reference table. To this end, we were having some problems related with our approach requiring some workarounds (some implemented).

See the existing code at https://github.com/citusdata/citus/tree/local-ref-fkey-dev

## assuming foreign key: reference_table -> local_table:

- Now that we set foreign key on the coordinator placement of reference table, the dependent object here is just the coordinator placement, not the reference table. Hence a drop (or truncate) command like

```sql
DROP local_table, reference_table;
```
were erroring out by postgres claiming "missing dependent object". 

- appending such reference tables' coordinator placements to the drop/truncate commands is a working workaround (implemented)

##  assuming foreign key: local table -> reference table

- As citus sends per-placement drop/truncate commands always with `CASCADE`, when dropping/truncating reference table with such a command

```sql
DROP reference_table;
```

, we were "automatically" cascading to the foreign key constraint between them, which was not the natural behavior comparing with the postgres.

- checking manually for drop/truncate commands if there exists such reference tables to be dropped/truncated and the command is not cascading, manually erroring out in citus side is a working workaround (implemented)

##  `\d reference_table`  doesn't show such foreign key constraints.

- A workaround for this is to overwrite behavior of `\d reference_table`.  Would it be doable, convenient and feasible ? (requires some research) 

## cascade issues when foreign key: reference_table -> local_table:

- If we are to set foreign key constraints by specifying `ON DELETE/UPDATE CASCADE`, we would just be cascading to the coordinator placement of the reference table and other placements of the reference table would be "out-of-sync" with the coordinator placement.

- Preventing such foreign keys seems to be a future breaking work-around (implemented). This is because in that case users will never be able to delete row from local table before deleting the referencing row from reference table

- Same inconsistency problem still applies to the commands like `TRUNCATE local table CASCADE` 
(This can also be prevented but wouldn't be the native behavior again.)

- The only proper workaround for those two cascade issues seems to be implementing a "trigger" mechanism to be issued when such commands are cascaded to the coordinator placement to make those modifications effective for other placements as well.

--------------------------------------------

Those were the cases that I could foresee and some fixed until now.

-------------------------

- Discussed with @onderkalaci in person on Thursday, we thought that there can also be more SQL commands & queries that we may not be able to fully support (other than the above ones).
- Also there can be some other edge cases that can lead us to bunch of bugs in future or slowing down our development process due to thinking of current extraordinary design whenever we are to develop something around reference tables and foreign keys etc.

-----------------------

# Another way to implement this feature ?

One of the other ways to implement this feature is to introducing a new type of Citus table -say single placement table- . Similar to what described in below issues but with the following properties:

- #3583
- #3335

* Single placement table will only have one "real" placement and it will be in the coordinator
* In other nodes, we will also have placements for that table, but they will be *empty* (just to keep PostgreSQL quiet when we are setting the foreign key with the reference table)
* Hence SQL query & command execution on that table will only be allowed from the coordinator (as if a regular PostgreSQL table).
* We will add related entries to `pg_dist_partition` for bookkeeping of those tables as well.

## Implementing foreign keys between local tables and reference tables on top of single placement tables

* When we encounter with such a DDL command setting a foreign key between local table and reference table:
   * We would first seamlessly convert that local table to a single placement one
   * Or require user to call a udf `create_local_table` to make this happen
   * Or we will directly convert all coordinator local tables to single placement tables.
* Then we will directly set foreign key on reference table and on its coordinator placements marking as valid. We will also be setting that foreign key constraint on its other placements but this time marking as "invalid".
* Rationale behind this is to prevent further failures that may occur whenever we are to `INSERT` some data to the reference table (referencing to a local table) (as the worker placements of the local table would have no data in it and foreign key constraint check would fail)

## Benefits considering the foreign keys between local tables and reference tables

* This way, we can easily setup foreign key directly on the reference table and local tables without having to deal with several workarounds explained above.
* We can keep our current reference table operation support from mx nodes untouched as any modifying command execution will be done on all nodes.
* We will still be able to detect constraint violations, while executing the command on the coordinator placement.

* There also some other benefits implementing single placement tables explained in  #3583 & #3335 out of the foreign keys between coordinator local tables & reference tables.

## Some considerations with this approach

~- We should preserve consistent DDL execution on all nodes. Hence we should enable 2PC for this new table type.~ (Table would only have one placement already)
~- If we convert all regular PostgreSQL tables to single placement tables in creation time, user may fall into needless network overheads due to 2PC execution explained above. (Or we are good to go just converting the local tables involved in a foreign key relation with reference tables)~
~- As we will be doing some extra stuff over the network for those tables, users may face with meaningless errors (e.g due to error on connection to worker nodes) that they wouldn't expect for such a command execution on a pure local PostgreSQL table.~
- Lots of changes around the codebase where we are checking to determine the code-flow according to table type.

**Comment by onurctirtir** [comment]
Needless to say, but, any comments & questions are welcome :)

**Comment by onurctirtir** [comment]
To set an analogy between the single placement tables and the existing citus table types from the implementation aspect:,

* single placement tables will be similar to `reference tables` in the sense that they do not include a distribution column
* single placement tables will not require forcing sequential execution etc. as they will actually act as a single shard distributed tables

**Comment by marcocitus** [comment]
>we will be able to set foreign keys between single shard placement tables and reference tables and between single shard placement tables and single shard placement tables freely

We won't be able to cascade updates/deletes on foreign keys from reference tables to single shard placement tables.

It would be nice if the placements could still be moved around if there was a foreign key from a reference table to single shard placement table, since the foreign key can be re-established on the other side. I think we can initially just error out when trying to move a single shard placement that has a foreign key from a reference table.

Foreign keys between co-located single shard placement tables should be fine.

**Comment by onurctirtir** [comment]
> We won't be able to cascade updates/deletes on foreign keys from reference tables to single shard placement tables.

Should we be setting foreign key between the actual tables as well (not on their placements) ? In that case would it be a problem to cascade updates/deletes ?

**Comment by marcocitus** [comment]
Cascading happens on the placement level, and if we were to cascade into the coordinator placement of the reference table only, it would go out of sync with the other placements.

**Comment by onurctirtir** [comment]
> Cascading happens on the placement level, and if we were to cascade into the coordinator placement of the reference table only, it would go out of sync with the other placements.

Also talked with @onderkalaci, we decided to prevent fkeys with "on delete/update cascade" behavior from `reference tables` to `single placement tables` for now.

What do you think @marcocitus ?

**Comment by marcocitus** [comment]
Makes sense.

**Comment by onurctirtir** [comment]
Some of the design & implementation details in this issue might be outdated.
Please see https://github.com/citusdata/citus/pull/4143 also
