### ISSUE TITLE
CREATE TYPE command sync from coordinator to MX wrongly

### ISSUE THREAD

**Issue by hellocodeM** [citusdata/citus#3646]
## Scenario
When executing `CREATE TYPE mytype AS (name varchar(16))` on coordinator, MX will receive wrong command `CREATE TYPE mytype AS (name character varying)`. 

## Root cause
In `AppendColumnDef` function, it use `format_type_be_qualified ` to deparse column type definition, but it will wrongly convert `varchar(16)` to `character varying`.

## Fix approach
The correct approach to deparse `varchar(16)` is to use `format_type_extended`, this function could reserve typemod information. 

I have fix this issue, I could submit a patch if you have make sure this is the correct fix approach.

**Comment by hellocodeM** [comment]
## Test case to reproduce this issue
```sql
CREATE TYPE create_order_delegator_t AS (
     out_w_tax decimal(4, 4),
     out_d_tax decimal(4, 4),
     out_o_id integer,
     out_c_discount decimal(4, 4),
     out_c_last varchar(16),
     out_c_credit char(2),
     out_o_entry_d timestamp
);

\d create_order_delegator_t

\c - - - :worker_1_port
\d create_order_delegator_t
```

**Comment by serprex** [comment]
> I have fix this issue, I could submit a patch if you have make sure this is the correct fix approach.

Yes, please open a pull request
