### ISSUE TITLE
Adding a column with custom type in custom schema in search_path fails

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#3678]
Adding a column of a custom type that is in the local search path, but not in the global search_path fails

```sql
CREATE SCHEMA foo;
SET search_path TO foo;
CREATE TABLE test (x int, y int);
SELECT create_distributed_table('test','x');
CREATE TYPE xy AS (x int, y int);
ALTER TABLE test ADD COLUMN z xy;
ERROR:  type "xy" does not exist
CONTEXT:  while executing command on localhost:9701
```

The reason is that the type is not qualified when we send the command to alter the shard:
```sql
SELECT worker_apply_shard_ddl_command (102112, 'foo', 'ALTER TABLE test ADD COLUMN z xy;')    
```

Using fully qualified names does work:
```sql
ALTER TABLE foo.test ADD COLUMN z foo.xy;
```

**Comment by naisila** [comment]
We didn't have a deparser for `ALTER TABLE .. ADD COLUMN` at the time when this issue was opened but now we do, and we should extend it.
