### ISSUE TITLE
Improve INSERT performance for hash partitioned tables

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#368]
When the user issues an ``INSERT``, we currently create a constraint for each shard and then linearly search over these constraints. As a result, when the user issues parallel insert statements, the master node becomes bottlenecked on CPU. Further, this approach doesn't scale with the number of shards.

We can resolve this issue in one of two ways:

1. We hash the partition column's value and do an index lookup on ``pg_dist_shard``, or
2. We sort the shard interval cache and then do a binary search in the sorted cache.

Once we decide on our approach, we should keep this code path consistent with the work on COPY for hash partitioned tables. I'm therefore marking issue #33 as related to this item.

**Comment by onderkalaci** [comment]
#446 fixes this. Should we close this item?

**Comment by sumedhpathak** [comment]
@onderkalaci Yup, go ahead and close this issue.
