### ISSUE TITLE
master_get_active_worker_nodes() UDF does not return the active nodes

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#371]
`master_get_active_worker_nodes()` returns the worker nodes that are present in the `pg_worker_list.conf` as it's documented in the [source](https://github.com/citusdata/citus/blob/2fcfa011aeafb19e95654acf4056edc5eed8807a/src/backend/distributed/master/master_node_protocol.c#L467). 

Instead of returning the workers in the file, the workers should be filtered with a UDF similar to `worker_node_responsive()` that is in the rebalancer extension. 

Or, there could be another UDF, which returns the reponsive worker node list. This might be helpful during cluster setup or cluster monitoring.

**Comment by pykello** [comment]
@onderkalaci Is this issue still relevant?
