### ISSUE TITLE
tables with GENERATED ALWAYS AS columns can't be partitioned

### ISSUE THREAD

**Issue by Dishwasha** [citusdata/citus#3712]
Without any generated columns, or without calling create_distributed_table, everything works fine.  When one or more columns are defined as generated columns for a distributed table, it throws an error.

postgres=# CREATE TABLE github.events (
  event_id bigint,
  event_type text,
  event_public boolean,
  repo_id bigint,
  **payload text GENERATED ALWAYS AS (event_type) STORED,**
  repo jsonb, actor jsonb,
  org jsonb,
  created_at timestamp
) PARTITION BY RANGE (created_at);
postgres=# SELECT create_distributed_table('github.events', 'repo_id');
postgres=# CREATE TABLE github.events_2016 PARTITION OF github.events FOR VALUES FROM ('2016-01-01') TO ('2016-12-31');
**ERROR:  cannot cast 3802 to 1114**
postgres=#

**Comment by serprex** [comment]
This was fixed with #3550 

Until that fix is released, you'll want to move `GENERATED ALWAYS` to being the last columns of a table
