### ISSUE TITLE
master_update_node does not work when using dbcp

### ISSUE THREAD

**Issue by hancci** [citusdata/citus#3743]
### master_update_node does not work when using dbcp
* **version** : citus-v9.1.2
* **symptom** : master_update_node does not work when using dbcp

* I have 2 worker groups. Each group has a primary and a standby.
```sql
-- two dist nodes
pgdb# select nodeid, nodename, nodeport from pg_dist_node;
 nodeid |       nodename       | nodeport 
--------+----------------------+----------
      1 | dev-testcitus003-g0  |     5432
      2 | dev-testcitus005-g1  |     5432

--Each group has a primary and a standby.
               Name |   Port | Group |  Node |     Current State |    Assigned State
---------------------+--------+-------+-------+-------------------+------------------
dev-testcitus003-g0 |   5432 |     0 |     1 |           primary |           primary
dev-testcitus004-g0 |   5432 |     0 |     2 |         secondary |         secondary
dev-testcitus005-g1 |   5432 |     1 |     3 |           primary |           primary
dev-testcitus006-g1 |   5432 |     1 |     4 |         secondary |         secondary

```
In my case, the following error occurred in my application
when dev-testcitus003-g0 failed and dev-testcitus004-g0 was promoted.

```java
org.postgresql.util.PSQLException: ERROR: connection error: dev-testcitus003-g0:5432
  Detail: could not connect to server: Connection refused
	Is the server running on host "dev-testcitus003-g0" (10.113.255.1) and accepting
	TCP/IP connections on port 5432?
```
so, I updated work node metadata on the coordinator.
and I performed an ad-hoc query via psql to confirm that there was no problem.
Everything was perfect.
```sql
--master_update_node
pgdb# select master_update_node(1, 'dev-testcitus004-g0', 5432);

--test : OK! 
pgdb# select count(*) from ads;
 count 
-------
  4766
(1 row)

```
But my application was still throwing errors.
The errors seemed to be still referring to the old primary worker node.
```java
org.postgresql.util.PSQLException: ERROR: connection error: dev-testcitus003-g0:5432
  Detail: could not connect to server: Connection refused
	Is the server running on host "dev-testcitus003-g0" (10.113.255.1) and accepting
	TCP/IP connections on port 5432?
```
Of course, I know how to fix it with validationQuery of Apache commons-dbcp.
But I think the master_update_node function should work properly.

Could I get some help please.

Regards,
Han

**Comment by marcocitus** [comment]
Interesting. Are you using prepared statements?

I'm wondering whether the old IP is getting cached in prepared statements.

**Comment by hancci** [comment]
Thank you for your feedback.

Let me test it again using statemets instead of prepared statements
I'll keep you posted.

**Comment by marcocitus** [comment]
Confirmed that the old hostname (below: "localhost" instead of "127.0.0.1") lingers in prepared statements when it was replaced in the metadata. We should clear the prepared statement cache when a master_update_node happens.
```sql
PREPARE foo AS SELECT * FROM test WHERE x = 1;
EXECUTE foo;
EXECUTE foo;
EXECUTE foo;
EXECUTE foo;
EXECUTE foo;
EXECUTE foo;

SELECT master_update_node(2, '127.0.0.1', 9701);

EXECUTE foo;
NOTICE:  issuing SELECT x, y FROM public.test_102009 test WHERE (x OPERATOR(pg_catalog.=) 1)
DETAIL:  on server marco@localhost:9701 connectionId: 1
┌───┬───┐
│ x │ y │
├───┼───┤
│ 1 │ 1 │
└───┴───┘
(1 row)

SELECT * FROM test WHERE x = 1;
NOTICE:  issuing SELECT x, y FROM public.test_102009 test WHERE (x OPERATOR(pg_catalog.=) 1)
DETAIL:  on server marco@127.0.0.1:9701 connectionId: 2
┌───┬───┐
│ x │ y │
├───┼───┤
│ 1 │ 1 │
└───┴───┘
(1 row)
```

**Comment by hancci** [comment]
You were right.
I really hope you fix it and include it in the next release. 
Thank you again for your kind cooperation.  :)
