### ISSUE TITLE
Propagate DDL commands that are database specific to worker nodes

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#376]
We propagate table specific DDL commands such as `ALTER TABLE` and `CREATE INDEX` to all shards. We however follow a split approach in propagating database specific DDL commands.
1. We don't propagate `CREATE TYPE`, `CREATE FUNCTION`, and similar commands to worker nodes. Users manually run these commands on the worker nodes. It's also worth noting that these DDL commands could get executed as part of `CREATE EXTENSION`.
2. We propagate foreign data wrapper related commands, such as `CREATE SERVER` and `CREATE FOREIGN TABLE` when we create a new shard for the foreign table. This on-demand approach may lead to small confusions like in here: https://github.com/citusdata/cstore_fdw/issues/84 
3. We propagate commands such as `CREATE SCHEMA` when we create a new shard within the schema (#122 and #210). We could be following a similar approach when granting permissions for a role. 

We need to evaluate a better approach to propagate database related DDL commands to worker nodes.

**Comment by ozgune** [comment]
I'm also documenting #122 and #522 as other issues that may be related to this one.

**Comment by ozgune** [comment]
I wanted to share two quick comments on this issue.

First, we now have user-defined functions (udfs) to propagate commands such as ``CREATE TYPE`` or ``CREATE FUNCTION`` to worker nodes.

Second, we had a feature request from a user on this issue. Today, if the user runs ``CREATE TYPE`` on worker nodes and then adds new machines into the cluster, they have to re-run these commands on the newly added machines. If we stored or could reproduce commands that relate to a database (such as ``CREATE TYPE`` or ``CREATE FUNCTION``), then we could automatically re-run these commands before rebalancing.

**Comment by ozgune** [comment]
We recently observed an issue because Citus doesn't automatically propagate `CREATE TYPE` statements. The issue was related to Citus trying to replicate a reference table to a new machine, where the machine had a custom type (Enum) on it.

In Citus Cloud, the coordinator was stuck in "configuring" state (I believe when calling master_add_node):

<pre>
[3] production(main)> Server['XXX'].lw
4 TID-gpkn2gjqo INFO: Working/1 Server['XXX'] configuring
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
NOTICE:  Replicating reference table "..." to the node XXX.compute-1.amazonaws.com:5432
NOTICE:  Replicating reference table "..." to the node XXX.compute-1.amazonaws.com:5432
NOTICE:  Replicating reference table ".." to the node XXX.compute-1.amazonaws.com:5432
NOTICE:  Replicating reference table "..." to the node XXX.compute-1.amazonaws.com:5432
ERROR:  type "public.my_type" does not exist
CONTEXT:  while executing command on XXX.compute-1.amazonaws.com:5432
/home/mapi/lib/util.rb:4:in `r': unhandled exception
	from bin/worker-updater:84:in `block (2 levels) in <main>'
...
</pre>

Manually running CREATE TYPE on the new worker fixed it, but until that happened the coordinator would have been stuck in "configuring", which isn't great.

**Comment by marcocitus** [comment]
We do this now for the main commands (e.g. CREATE TYPE)
