### ISSUE TITLE
Potential null pointer exception on debug message

### ISSUE THREAD

**Issue by hanefi** [citusdata/citus#3766]
Citus has a debug4 message that can potentially create a null pointer exception at https://github.com/citusdata/citus/blob/13a35c6813fc2199f448cde80b2b2277848a74ea/src/backend/distributed/planner/deparse_shard_query.c#L117-L121

## Reproduction steps
```sql
SET client_min_messages TO debug4;

CREATE TABLE numbers(a int);
SELECT create_reference_table('numbers');
INSERT INTO numbers VALUES (1), (2), (3), (4);
```

## Call trace
```
__pthread_kill (Unknown Source:0)
pthread_kill (Unknown Source:0)
abort (Unknown Source:0)
ExceptionalCondition (/Users/hanefi/pgenv/src/postgresql-12.2/src/backend/utils/error/assert.c:54)
dopr (/Users/hanefi/pgenv/src/postgresql-12.2/src/port/snprintf.c:442)
pg_vsnprintf (/Users/hanefi/pgenv/src/postgresql-12.2/src/port/snprintf.c:195)
pvsnprintf (/Users/hanefi/pgenv/src/postgresql-12.2/src/common/psprintf.c:110)
appendStringInfoVA (/Users/hanefi/pgenv/src/postgresql-12.2/src/backend/lib/stringinfo.c:136)
errmsg (/Users/hanefi/pgenv/src/postgresql-12.2/src/backend/utils/error/elog.c:794)
RebuildQueryStrings (/Users/hanefi/code/citus/citus/src/backend/distributed/planner/deparse_shard_query.c:117)
RegenerateTaskListForInsert (/Users/hanefi/code/citus/citus/src/backend/distributed/executor/citus_custom_scan.c:506)
CitusBeginModifyScan (/Users/hanefi/code/citus/citus/src/backend/distributed/executor/citus_custom_scan.c:370)
ExecInitCustomScan (/Users/hanefi/pgenv/src/postgresql-12.2/src/backend/executor/nodeCustom.c:103)
ExecInitNode (/Users/hanefi/pgenv/src/postgresql-12.2/src/backend/executor/execProcnode.c:282)
InitPlan (/Users/hanefi/pgenv/src/postgresql-12.2/src/backend/executor/execMain.c:1020)
standard_ExecutorStart (/Users/hanefi/pgenv/src/postgresql-12.2/src/backend/executor/execMain.c:266)
CitusExecutorStart (/Users/hanefi/code/citus/citus/src/backend/distributed/executor/multi_executor.c:117)
ProcessQuery (/Users/hanefi/pgenv/src/postgresql-12.2/src/backend/tcop/pquery.c:156)
PortalRunMulti (Unknown Source:0)
PortalRun (/Users/hanefi/pgenv/src/postgresql-12.2/src/backend/tcop/pquery.c:796)
```

**Comment by SaitTalhaNisanci** [comment]
This does not happen in pg 11.5, but when I switched to pg 12 it happened.

**Comment by hanefi** [comment]
It maybe a nice thing to test the whole test suite with `SET log_min_messages TO DEBUG1` and see if we have any more issues like this

**Comment by SaitTalhaNisanci** [comment]
Why DEBUG1? Wouldn't it be better to test that nothing crashes with DEBUG4? For example in this example, if we use DEBUG1 we wouldn't catch this error.

**Comment by hanefi** [comment]
You are right, It should have been `debug4`

**Comment by SaitTalhaNisanci** [comment]
That is actually a good idea, and we should probably include something like that in our release testings, because a user can set debug level to debug4 and we should make sure that we don't crash in that case. So I feel like that is a "should-have" in our release tests.

**Comment by SaitTalhaNisanci** [comment]
One script that comes to my mind is this:

- globally set client_min_messages to debug4
- replace all client_min_messages in tests with debug4 ( so that it doesn't decrease the log level during tests)
- run all the tests and make sure that we don't have any crash messages in the test logs.

This will capture any crashes that could happen in our tests when debug4 is set.

**Comment by serprex** [comment]
Ideally our test coverage would have coverage of this null case explicitly, rather than having a blanket debug4 that hopes we cover this

**Comment by hanefi** [comment]
> Ideally our test coverage would have coverage of this null case explicitly, rather than having a blanket debug4 that hopes we cover this

The most verbose debug outputs tend to contain too much of information that makes it hard to use them in regression tests.

Here are some issues in my mind that makes it difficult to write verbose and yet deterministic outputs in tests:
1. The order of those message can sometimes change due to differing order of operations, network latency etc. Should we intercept these messages in regression tests and sort them somehow?
2. The numeric data in those can change over time. Should we capture all possible regexes and replace them with placeholder values?
3. When set to DEBUG4, so much information gets logged and it may get harder to focus on the regression outputs

**Comment by serprex** [comment]
We can write functions which run a query & scan the output, we already do this in some cases:

https://github.com/citusdata/citus/blob/2e0cb6160c87c38f70fc547c2adcfed77ec6415e/src/test/regress/sql/multi_mx_metadata.sql#L10

**Comment by onderkalaci** [comment]
> You are right, It should have been debug4

Yes, but we could have used `log_min_messages`, which I'm going to change soon
