### ISSUE TITLE
master_create_empty_shard placement selection is uneven

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#380]
I was trying to run a demo with 20 nodes and ran into an issue during data ingestion with a very slow node. The node turned out to have 3x more shard placements than some other nodes. The demo had 365 shards, which were all created using master_create_empty_shard.

I then tried generating 365 shards on 20 nodes and observed there was consistently a 2x difference between smallest and largest number of placements.

```
postgres=# SELECT master_create_empty_shard('github_events') FROM generate_series(1, 365);
...
postgres=# SELECT nodename, count(*) FROM pg_dist_shard_placement GROUP BY nodename ORDER BY 2 DESC;
           nodename           | count 
------------------------------+-------
 ip-10-192-0-80.ec2.internal  |    47
 ip-10-192-1-132.ec2.internal |    45
 ip-10-192-0-122.ec2.internal |    43
 ip-10-192-0-81.ec2.internal  |    42
 ip-10-192-0-77.ec2.internal  |    41
 ip-10-192-0-123.ec2.internal |    41
 ip-10-192-0-120.ec2.internal |    39
 ip-10-192-1-206.ec2.internal |    39
 ip-10-192-1-204.ec2.internal |    38
 ip-10-192-1-134.ec2.internal |    37
 ip-10-192-1-133.ec2.internal |    36
 ip-10-192-1-203.ec2.internal |    36
 ip-10-192-1-207.ec2.internal |    35
 ip-10-192-0-78.ec2.internal  |    34
 ip-10-192-1-131.ec2.internal |    33
 ip-10-192-0-121.ec2.internal |    32
 ip-10-192-0-79.ec2.internal  |    31
 ip-10-192-1-205.ec2.internal |    29
 ip-10-192-0-124.ec2.internal |    27
 ip-10-192-1-135.ec2.internal |    25
```

The reason is that master_create_empty_shard uses the random() function to select a worker node, which follows the same pattern:

```
postgres=# SELECT num, count(*) FROM (SELECT FLOOR(RANDOM()*20)+1 num FROM generate_series(1, 365)) a GROUP BY num ORDER BY 2 DESC;
 num | count 
-----+-------
  17 |    26
  12 |    24
   6 |    24
   4 |    22
   1 |    22
  13 |    21
  11 |    21
  20 |    20
   8 |    20
   5 |    17
  10 |    17
  15 |    16
   3 |    16
   9 |    16
  16 |    15
   2 |    14
  19 |    14
  18 |    14
  14 |    13
   7 |    13
```

`    (20 rows)

This distribution is mathematically expected and makes random() a poor choice for distributing shard placements, given a typical number of nodes and placements. 

For example, when placing 100 shards on 20 nodes, there is typically a 10x difference in the number of placements between nodes.

**Comment by marcocitus** [comment]
We use round-robin by default now.

**Comment by lithp** [comment]
Wow, do you know why random()'s distribution is so wrong?

**Comment by marcocitus** [comment]
It's basically just probability / the law of small numbers. For large enough samples (think millions), random() will approximate a uniform distribution, but the number of worker nodes and the number of shard placements are small, meaning relatively large deviations are likely.
