### ISSUE TITLE
ExtractLocalAndRemoteTasks may copy task and fail

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#3801]
`ExtractLocalAndRemoteTasks` is a little odd. It assumes that either a task has a single placement or will go to all placements:
https://github.com/citusdata/citus/blob/master/src/backend/distributed/executor/local_executor.c#L471

However, object propagation will typically create a task that has multiple remote-only placements (workers only) and hence runs through the `else` without have local tasks.

That might have been ok, except we call `copyObject` on the `Task`:
https://github.com/citusdata/citus/blob/master/src/backend/distributed/executor/local_executor.c#L497

copyObject on a Task does not actually work, because a task may contain a list of `char *` (e.g. in `queryStringList`, which is used by object propagation) and `copyObject` assumes the list contains only Postgres `Node`s, such that it can tell how to copy the list members from the node type.  
https://github.com/citusdata/citus/blob/master/src/backend/distributed/utils/citus_copyfuncs.c#L280

While making code changes to support distributing tables created by extensions, I've seen this result in:
```
DROP EXTENSION hll;
ERROR:  unrecognized node type: 542393683
```

It seems likely that there is some way to reproduce this on the current master / release-9.3 branch, but even if there isn't we should clean this up.

**Comment by onderkalaci** [comment]
Probably related to https://github.com/citusdata/citus/issues/3590

**Comment by SaitTalhaNisanci** [comment]
This is easy to reproduce:

```sql
SET citus.shard_replication_factor TO 2;
CREATE TABLE dist_table(a int);
SELECT create_distributed_table('dist_table', 'a');
BEGIN;
-- use transtion block so that we will call ExtractLocalAndRemoteTasks
INSERT INTO dist_table SELECT a + 1 FROM dist_table;
ROLLBACK;
```
