### ISSUE TITLE
Citus install directions are not working for Ubuntu 20.04

### ISSUE THREAD

**Issue by pushshift** [citusdata/citus#3810]
Following the guide here: https://www.citusdata.com/download/

    curl https://install.citusdata.com/community/deb.sh | sudo bash
    sudo apt-get -y install postgresql-12-citus-9.2
    sudo pg_conftool 12 main set shared_preload_libraries citus

Step 2 fails as the package doesn't appear to be in the Ubuntu 20.04 repos. 

Just a heads up.

**Comment by onurctirtir** [comment]
Thanks for the heads up! We didn't yet release any packages for Ubuntu 20.04 but we plan to introduce them as soon possible.
