### ISSUE TITLE
Proper error message for citus table creation from a temp table

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#3847]
It is obvious that we do not support creating distributed tables and reference tables from `TEMPORARY` tables. However, we give such errors when it is the case:

```sql
postgres=# create temp table reference_table(a int);                                                                                                                                                               
postgres=# select create_reference_table('reference_table');                                                                                                                                                       ERROR:  unacceptable schema name "pg_temp_3"
DETAIL:  The prefix "pg_" is reserved for system schemas.
CONTEXT:  while executing command on localhost:9701
```

It is because we first try to propagate the underlying schema, which is a temp schema and fortunately PostgreSQL errors out for that.

Intercepting create citus table udf's and giving a better error message telling that we do not support creating tables from `TEMPORARY` tables could be more useful.

**Comment by onderkalaci** [comment]
maybe we should guide users towards `UNLOGGED` tables in  the error hint when we fix it

**Comment by onurctirtir** [comment]
same as https://github.com/citusdata/citus/issues/4533
