### ISSUE TITLE
IsDropCitusStmt possible bug

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#3856]
IsDropCitusStmt checks if the name is 'citus' but it doesn't check the `removeType` of `DropStmt`. 

We have the following code in utility hook:

```c
	if (IsDropCitusStmt(parsetree))
	{
		StopMaintenanceDaemon(MyDatabaseId);
	}
```

So if we are dropping a table named 'citus' it might possibly stop the maintenance daemon I guess even though it shouldn't.

**Comment by onurctirtir** [comment]
Agreed, we should definitely check for `ObjectType == OBJECT_EXTENSION`.
