### ISSUE TITLE
Prototype for masterless using "simple replication groups"

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#389]
We're evaluating three higher level approaches to masterless. With this issue, we're going to build a working prototype for one of those approaches with the intent to better understand requirements and evaluate the timeline.

I'm writing down my current understanding in this description. Let's update this issue as we learn and know more.

1. This approach uses simple replication groups. In each replication group, we have a Postgres primary and secondary set up.
2. We use a Yoke-like approach. In this setup, we have a separate monitor node that checks for the primary nodes' healths.
3. We propagate distributed metadata changes to all primaries through a mechanism like 2PC.

**Comment by jasonmp85** [comment]
Removing from 5.1

**Comment by ozgune** [comment]
@marcocitus -- what do you think about closing this issue? 😄 

@sebastianwebber and @manigandham -- we recently announced [Citus MX beta](https://www.citusdata.com/blog/2016/09/22/announcing-citus-mx). If you're interested in learning more, we have an impressive demo in our blog and we'd be happy to hear from you.

**Comment by manigandham** [comment]
@ozgune  Thanks, read that blog post but will reach out to learn more. 

Lots of current distributed relational databases use a master or query node architecture which isn't great. A masterless design where every node is equivalent is easier to setup, more resource efficient, has better availability support, and scales better for performance. The resource overhead of running any single query is trivial compared to holding the data anyway and the queries are also evenly distributed.

Glad to see this progress, will be nice to have it in the main on-premise distribution too once it's ready.
