### ISSUE TITLE
Real-time PostgreSQL: Blog entry, webinar, and documentation

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#39]
Once we pick and implement an approach for roll-up tables in #38, we need to gather feedback and create content to communicate this approach.

**Comment by ozgune** [comment]
We explored several methods to create roll-up tables and also presented a tutorial on it. We could evaluate our learnings from this tutorial and pick and implement an approach: https://www.youtube.com/watch?v=0ybz6zuXCPo

**Comment by marcocitus** [comment]
There are now many companies that successfully implemented a real-time analytics on Citus by creating rollup tables and using INSERT...SELECT.

Blog post: https://www.citusdata.com/blog/2018/06/14/scalable-incremental-data-aggregation/
Documentation: https://docs.citusdata.com/en/v7.4/use_cases/realtime_analytics.html
