### ISSUE TITLE
questions for connection problem with worker

### ISSUE THREAD

**Issue by louis-shon** [citusdata/citus#3905]
Hi.
I have a some connection problems between citus & worker node.

Main error message is

`Cause: org.postgresql.util.PSQLException: ERROR: canceling statement due to user request`

I think, it is base on the connection wait issues from coordinator and worker.
(Wait up-to 60 seconds (?) if there is not avaliable connection slot on the worker)

**q1)**
  How citus manages this connections? is there any way to increase this connections more?
**q2)**
  Is there any proper executer configurations or cluster managment strateges to avoid this canceling statement case?

Please let me know if you need more information on my environments.

thanks.

```
Our cluster environments are
- 32 shard
- 10g over data size
- 8 primary workers and 8 secondery workers with 2pc
- 10 core x 2 on each worker
- connection time out 60s.
- excuter connection pool size 32
```

**Comment by onurctirtir** [comment]
It might help to take a look at following parameters if you didn't yet:

http://docs.citusdata.com/en/v9.3/develop/api_guc.html?highlight=citus-max-shared-pool-size-integer#citus-max-shared-pool-size-integer

http://docs.citusdata.com/en/v9.3/develop/api_guc.html?highlight=citus-max-shared-pool-size-integer#citus-max-adaptive-executor-pool-size-integer

Could you also share a bit more details for the query (or the query itself) that leads to connection failure ?

**Comment by louis-shon** [comment]
Thanks!
I will perform this configuration test on my environment soon and will give you the feedback.

By the way, In my situation, it's not depends on a query it self but slightly i think it's associated with citus activity counts. (I hope this to be helpful hint..)
![image](https://user-images.githubusercontent.com/45617982/84612748-8b488a00-aefc-11ea-8ad8-efc4e63ad6c9.png)

When activity count comes up to 250~300 then this connection wait symptoms are occurs very often.

**Comment by louis-shon** [comment]
And, is there any documents for describing GUC?
(Thanks)

**Comment by metdos** [comment]
Hi @louis-shon, we use GitHub issues to keep track of features and bugs. To keep here clear, I'm closing this issue, you can ask your questions on our Slack channel.

Thanks.

**Comment by louis-shon** [comment]
@metdos Okay thaks.!!
