### ISSUE TITLE
Extensions are not installed on CI

### ISSUE THREAD

**Issue by thanodnl** [citusdata/citus#3908]
We have integrated 3 extensions in the Citus planner, which have tests, but are not tested in our regular CI run since the extensions are not installed there.

This causes coverage of the integration to be not captured by our coverage tracking system, which we can overcome.

More importantly if there are changes that cause regressions we can't rely on CI to catch these regressions. Also since the tests are not executed often they might start rotting when other changes are made that changes the behaviour or output of the tests.

Ideally we would have all extensions natively integrated in Citus installed in our CI pipeline to keep verifying their behaviour.

**Comment by SaitTalhaNisanci** [comment]
#3888

**Comment by thanodnl** [comment]
Duplicate of #3888
