### ISSUE TITLE
How to efficiently export billions of data from Citus?

### ISSUE THREAD

**Issue by ChenHuajun** [citusdata/citus#3915]
We often need to export data from Citus to other systems.
Currently, when exporting the data (`select * from xx`) form Citus, all data in Workers will be temporarily saved in the Coordinator first.
When the amount of exported data is large, the Coordinator will be under great pressure.

We consider to export data in batches, but in this scenario `offset + limit` is less efficient.

Is there any way to efficiently export billions of data from Citus?

Can it support taking only one shard at a time?
In this way, the application can export each shard in turn, each time the data exported is less, and the intermediate data is not placed in the Coordinator.

Similar to the hidden field `gp_segment_id` in Greenplum
```
select * from tbxx where gp_segment_id=1 and ...
```

**Comment by onurctirtir** [comment]
Hi ChenHuajun,

You can use `COPY xx TO STDOUT`  to efficiently export your distributed table via stdout.

(Also see the pr brings that feature: https://github.com/citusdata/citus/pull/3361)

**Comment by ChenHuajun** [comment]
Thanks for answering!

But the `COPY xx TO STDOUT` can only satisfy a small part of our scene.
There are still problems in the following scenarios

1. The application only needs to obtain part of the data in the table, that is, it needs to support where condition filtering (such as filtering by time, etc.).
2. The application needs to process the query results. The application parsing the results of COPY is obviously more troublesome than directly processing the selected result set
