### ISSUE TITLE
How to create distributed table by range

### ISSUE THREAD

**Issue by sipakov** [citusdata/citus#3926]
Hi!
I try to create distribution table by range. 
But the documentation is extremely scarce in this matter. I do not know if this functionality is supported in the latest version. I know that you need to edit metadata tables. But I have a lot of questions.
I have two nodes: a coordinator and a worker.
I do this on the coordinator (simple table for example):
```
CREATE TABLE devices (
  device_id bigint NOT NULL,
  device_type int NOT NULL,
  PRIMARY KEY (device_id)
);
SELECT create_distributed_table('devices', 'device_id', 'range');
```
This creates a table on the coordinator and creates an entry in `pg_class`, but how do you know which shard it is? Is it necessary to manually create a table on the worker? And in what tables and what needs to be entered in order for sharding to work?
The best is a small example instruction step by step. Many thanks

**Comment by onderkalaci** [comment]
> But the documentation is extremely scarce in this matter.

Yes, I  don't think you can use all  the latest features of Citus with append distribution. It might be useful for you to consider: Hash distributed by Citus + Partition by Range by Postgres, an example table from PG documentation: https://www.postgresql.org/docs/10/ddl-partitioning.html

```SQL
CREATE TABLE measurement (
    id         int not null,
    logdate         date not null,
    peaktemp        int,
    unitsales       int
) PARTITION BY RANGE (logdate);
SELECT create_distributed_table('measurement', 'id');

CREATE TABLE measurement_y2006m02 PARTITION OF measurement
    FOR VALUES FROM ('2006-02-01') TO ('2006-03-01');

CREATE TABLE measurement_y2006m03 PARTITION OF measurement
    FOR VALUES FROM ('2006-03-01') TO ('2006-04-01');

...
CREATE TABLE measurement_y2007m11 PARTITION OF measurement
    FOR VALUES FROM ('2007-11-01') TO ('2007-12-01');
```
With that, you'll get the shards and each shard would have its partitions.

Would such an approach useful for you?

**Comment by sipakov** [comment]
Interesting solution. However, there are a couple of questions.
Does query efficiency remain with this solution?
`SELECT create_distributed_table ('measurement', 'id');` will create shards both on the coordinator and on the worker.
Is the `CREATE TABLE measurement_y2006m02 PARTITION OF measurement` operation to be applied manually to each shard (or to the main table?) On both machines?

**Comment by onderkalaci** [comment]
> Does query efficiency remain with this solution?

It depends on the use case & data size & number of partitions etc. But, I'd expect to perform fairly good with this approach as well (especially with PG12+). 

When you query the distributed table with filters containing the partition key, Citus will send the queries to all the shards and on each shard only relevant partitions are accessed.

Overall, I'd suggest you to try this approach and do some basic benchmarks with your use-case/query patterns etc.

> SELECT create_distributed_table ('measurement', 'id'); will create shards both on the coordinator and on the worker.

Shards are only created on the workers.

> Is the CREATE TABLE measurement_y2006m02 PARTITION OF measurement operation to be applied manually to each shard (or to the main table?) On both machines?

This is automatic, you only need to apply this on the coordinator.

**Comment by yonj1e** [comment]
I did not see the content of creating distributed tables by range in the documentation, 
but I did see `SELECT create_distributed_table('range_partitioned', 'id', 'range');` in regress test cases;
Later, I tried to use start_metadata_sync_to_node in the MX architecture, 
but it was not synchronized to the MX node. 
Is this operation not supported?

**Comment by ozgune** [comment]
Hi @yonj1e - We don't officially support sharding by range in Citus. In most cases, our users follow the approach recommended by @onderkalaci.

I'll defer to @mulander on whether we'd like to close this Github issue as unsupported.

**Comment by mulander** [comment]
Yes, as @ozgune said we don't support sharding by range. We found PostgreSQL partitioning along with distributing over a different column as the most optimal solution for time series data. This is nicely described in our best practices for time series data modelling:

> Best Practices [🔗](https://docs.citusdata.com/en/v11.1/sharding/data_modeling.html#id2)
**Do not choose a timestamp as the distribution column**. Choose a different distribution column. In a multi-tenant app, use the tenant id, or in a real-time app use the entity id.
> **Use PostgreSQL table partitioning for time instead**. Use table partitioning to break a big table of time-ordered data into multiple inherited tables with each containing different time ranges. Distributing a Postgres-partitioned table in Citus creates shards for the inherited tables.

We also have a nice doc going into the details of such design here: https://docs.citusdata.com/en/v11.1/use_cases/timeseries.html#scaling-timeseries-data-on-citus

I am closing down this issue, please feel free to reach out with details if you think your workload can't be handled nicely by this approach.

**Comment by LauJosefsen** [comment]
@mulander 

We are using Citus with MobilityDB to handle large scale spatio-temporal trajectory data analytics.

We desire to use a sharding method that allows us to distribute data spatially co-located. I of course do not expect Citus to have predefined behavior for this use case, but as I understand it, we cannot currently implement a custom function that maps a spatio-temporal attribute to a shard id for distribution?

I wish we could have range partitioning or the ability to provide a UDF to translate the distribution column into a shard id.

Our idea was to create a global index/table dictating what areas can be found in what shard, and use that for candidate elimination on the shard-level, to avoid scanning all shards.

Other examples of spatio temporal global partitioning schemes can be seen in:
Distributed Trajectory Similarity Join: https://doi.org/10.1145/3183713.3183743
Distributed Trajectory KNN Join: https://doi.org/10.1145/3474717.3484209

Also I noted that the Citus paper says Citus allows for range distribution? It is a bit confusing this is not the case in practice?
> Range-partitioning is also available for some advanced use cases.
https://doi.org/10.1145/3448016.3457551
