### ISSUE TITLE
Add "Limit / Offset" support

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#394]
Citus supports queries that involve ``LIMIT`` clauses, but not yet ``LIMIT / OFFSET``.

For these queries, we currently offer one of two workarounds:
1. Use cursors on the master node, or
2. Run ``CREATE TABLE AS (SELECT ... LIMIT 100)`` first, and then run ``OFFSET`` on that temporary table.

This issue tracks adding native ``LIMIT / OFFSET`` support to Citus.

**Comment by ozgune** [comment]
I'm adding a quick clarification note. This particular issue covers ``LIMIT .. OFFSET`` clauses on the outer most query. ``LIMIT .. OFFSET`` clauses that appear as part of subselects aren't addressed by this issue.

**Comment by mtuncer** [comment]
example with using cursors. Following code snippet skips the first 10 rows and returns next 2 rows.

```sql
BEGIN;
DECLARE lineitem_cursor CURSOR FOR select * from lineitem;
MOVE forward 10 from lineitem_cursor;
fetch lineitem_cursor;
fetch lineitem_cursor;
END;
```

**Comment by ozgune** [comment]
``LIMIT .. OFFSET`` came up again as a user request. I'm adding relevant exchange to this thread, and Daniel's informative notes on pagination.

--

Pagination

Citus does not support LIMIT, OFFSET. We have to run those queries and fetch data to master and then run the offset. This may fetch 10s-100s of thousands of rows and we don't want to make that the bottleneck.

Can you use cursors for pagination? Active Record doesn't support cursors.

--

@fdr noted the following: It should probably support cursors, but for common use cases cursors are not a good idea for activerecord (rails) workloads, because cursors retain a snapshot. If you are paginating a bunch of things on a web page, how long do you retain the cursor? How do you go backwards?

will_paginate uses the pretty lousy limit/offset approach.  It's even lousy for regular Postgres.  Better would be to use greater than and a limit, and many codes do this.  This has small correctness problems under concurrent operations, but is so much drastically faster that for human consumption it's a pretty big win.
