### ISSUE TITLE
FILTER does not work on distributed tables

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#395]
postgres=# select count(*) FILTER (where event_type = 'PushEvent') from github_events;
ERROR:  attribute number 2 exceeds number of columns 1

**Comment by mtuncer** [comment]
There is another issue #569 opened on a similar subject.

**Comment by ozgune** [comment]
@metdos / @onderkalaci -- we resolved #569. Does that fix also resolve this issue?

**Comment by onderkalaci** [comment]
No, it does not. Our re-partition subquery count distinct [logic](https://github.com/citusdata/cloudcitus/blob/539eb6a874a8b8a73fa5709561bb5b486876f838/src/backend/distributed/planner/multi_logical_optimizer.c#L1358) is separate from the other aggregations. 

But, it looks like we can apply the same simple solution here as well.

**Comment by scottbessler** [comment]
When working around this behavior I tried something out that did not error but effectively returned an approximate distinct count that was the same as the unfiltered version:

```

set citus.count_distinct_error_rate to 0.005;
SELECT
  count(DISTINCT identified_user_id),
  count(DISTINCT CASE WHEN category LIKE 'home|shop|f%' THEN identified_user_id ELSE NULL END),
  count(DISTINCT identified_user_id) filter (where category LIKE 'home|shop|f%')
FROM
  art_l30;

113566	18791	113566

```

**Comment by ozgune** [comment]
@metdos / @onderkalaci -- What's your estimate on the fix for this issue?

Could you also describe why we started running into this issue? I thought the issue was related to ruleutils.c, but I don't remember the specifics.

**Comment by metdos** [comment]
Hey @ozgune,

FILTER clause is added in PostgreSQL 9.4, and I think we've had this problem after that. The problem is that we push FILTER clause to workers correctly but we also try to run the same filter on the master query which is wrong. I verified this by setting Aggref->aggfilter to NULL and the failing query just worked fine.

A couple of days should be enough to fix this if there are not other problems which I can't foresee now.

**Comment by metdos** [comment]
> When working around this behavior I tried something out that did not error but effectively returned an approximate distinct count that was the same as the unfiltered version:
> 
> 
> set citus.count_distinct_error_rate to 0.005;
> SELECT
>   count(DISTINCT identified_user_id),
>   count(DISTINCT CASE WHEN category LIKE 'home|shop|f%' THEN identified_user_id ELSE NULL END),
>   count(DISTINCT identified_user_id) filter (where category LIKE 'home|shop|f%')
> FROM
>   art_l30;
> 
> 113566  18791   113566

On the contrary to my comment above, this happens because we don't push FILTER to worker nodes. We behave differently for normal aggregates and approximate count distincts. The fix for this also seems simple.

**Comment by mtuncer** [comment]
We need to be fixing 2 parts here
1. master query should not have filters at all. We should explicitly set aggfilter to NULL
1. worker query should have filter. All worker aggregates except hll count distinct have filters. original query's filter expression should be added hll aggregate.

Preliminary testing shows those fixes solves the problem.
