### ISSUE TITLE
Errors for CREATE INDEX CONCURRENTLY are hard to understand

### ISSUE THREAD

**Issue by thanodnl** [citusdata/citus#3951]
When you create an index concurrently and an error happens most of the time you will get the same error message irregardless of the error that caused it. The error message looks like:

```sql
ERROR:  CONCURRENTLY-enabled index command failed
DETAIL:  CONCURRENTLY-enabled index commands can fail partially, leaving behind an INVALID index.
HINT:  Use DROP INDEX CONCURRENTLY IF EXISTS to remove the invalid index, then retry the original command.
```

It would be great if this error is only given if we detect the creation failed due to a naming conflict. Maybe even go as far as verifying the index is the same as the one we want to create, and is active. If the index would be the same as the one we wanted to create we can actually just move on without failure as the system will be in a consistent state after the creation finishes.

A user ran into an issue when creating a unique index concurrently on a table. The failure was not due to the index being partially created. Instead the failure was due to a unique constraint violation that the index creation enforces. However the error the user got was the error above resulting in a support ticket.

Instead it would be great to pass the original message for the failure, potentially with a hint that the index might be partially created and could require removal.

Example to reproduce:
```sql
CREATE TABLE t1 (a int, b int);
CREATE TABLE
Time: 7.818 ms

SELECT create_distributed_table('t1','a');
┌──────────────────────────┐
│ create_distributed_table │
├──────────────────────────┤
│                          │
└──────────────────────────┘
(1 row)

Time: 28.010 ms

INSERT INTO t1 VALUES (1,1), (1,2);
INSERT 0 2
Time: 7.711 ms

SELECT * FROM t1;
┌───┬───┐
│ a │ b │
├───┼───┤
│ 1 │ 1 │
│ 1 │ 2 │
└───┴───┘
(2 rows)

Time: 29.419 ms

CREATE UNIQUE INDEX CONCURRENTLY a_is_not_unique ON t1(a);
ERROR:  CONCURRENTLY-enabled index command failed
DETAIL:  CONCURRENTLY-enabled index commands can fail partially, leaving behind an INVALID index.
HINT:  Use DROP INDEX CONCURRENTLY IF EXISTS to remove the invalid index, then retry the original command.
Time: 25.887 ms
```

**Comment by naisila** [comment]
The reason for the same error appearing is a `try-catch` situation so that needs to be updated.
