### ISSUE TITLE
Citus should but does not support SET STATISTICS subcommand

### ISSUE THREAD

**Issue by nukoyluoglu** [citusdata/citus#3984]
```
CREATE TABLE t0(c0 int, c1 text);
SELECT create_distributed_table('t0','c0');
ALTER TABLE t0 ALTER COLUMN c1 SET STATISTICS 100;
ERROR:  alter table command is currently unsupported
DETAIL:  Only ADD|DROP COLUMN, SET|DROP NOT NULL, SET|DROP DEFAULT, ADD|DROP|VALIDATE CONSTRAINT, SET (), RESET (), ENABLE|DISABLE|NO FORCE|FORCE ROW LEVEL SECURITY, ATTACH|DETACH PARTITION and TYPE subcommands are supported.
```
According to [this](https://github.com/citusdata/citus/blob/40da78c6fd2c0c4396fe63c870fc4efc8e4c8cad/src/test/regress/output/multi_alter_table_statements.source#L926) line from MULTI_ALTER_TABLE_STATEMENTS regression tests, this statement should now be supported.

**Comment by onderkalaci** [comment]
Ops, I misguided to you on this. It looks like Citus doesn't support this ALTER TABLE command, what we see on the test output is after `SET citus.enable_ddl_propagation to false;`, which means that it is only executed on local shell table on the coordinator: https://github.com/citusdata/citus/blame/40da78c6fd2c0c4396fe63c870fc4efc8e4c8cad/src/test/regress/output/multi_alter_table_statements.source#L911

And, if you look this other example, Citus errors out: https://github.com/citusdata/citus/blame/40da78c6fd2c0c4396fe63c870fc4efc8e4c8cad/src/test/regress/output/multi_alter_table_statements.source#L377
