### ISSUE TITLE
create table and select table error occured on workers after 'master_add_node()' function is executed

### ISSUE THREAD

**Issue by zyDaemon** [citusdata/citus#4012]
1. phenomenon
The table cannot be created and looked up in public schema on workers after 'master_add_node()' function is executed.

		[postgres@zhengy ~/citus]$ psql -p9701
		psql (12.3)
		Type "help" for help.

		postgres=# create table tb1(c1 int);
		ERROR:  no schema has been selected to create in
		LINE 1: create table tb1(c1 int);
							 ^
		postgres=# create table public.tb1(c1 int);
		CREATE TABLE
		postgres=# select * from tb1;
		ERROR:  relation "tb1" does not exist
		LINE 1: select * from tb1;
							  ^
		postgres=# \dx
						 List of installed extensions
		  Name   | Version |   Schema   |         Description
		---------+---------+------------+------------------------------
		 citus   | 9.3-2   | pg_catalog | Citus distributed database
		 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
		(2 rows)

		postgres=# select version();
														 version
		---------------------------------------------------------------------------------------------------------
		 PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
		(1 row)

2. Operation
After executing the commands in the following order, the table cannot be created and looked up in public schema on workers.

		mkdir -p citus/coordinator citus/worker1 citus/worker2
		initdb -D citus/coordinator
		initdb -D citus/worker1
		initdb -D citus/worker2

		echo "log_min_duration_statement = 0" >> citus/coordinator/postgresql.conf
		echo "log_min_duration_statement = 0" >> citus/worker1/postgresql.conf
		echo "log_min_duration_statement = 0" >> citus/worker2/postgresql.conf

		echo "shared_preload_libraries = 'citus'" >> citus/coordinator/postgresql.conf
		echo "shared_preload_libraries = 'citus'" >> citus/worker1/postgresql.conf
		echo "shared_preload_libraries = 'citus'" >> citus/worker2/postgresql.conf

		pg_ctl -D citus/coordinator -o "-p 9700" -l coordinator_logfile start
		pg_ctl -D citus/worker1 -o "-p 9701" -l worker1_logfile start
		pg_ctl -D citus/worker2 -o "-p 9702" -l worker2_logfile start

		psql -p 9700 -c "CREATE EXTENSION citus;"
		psql -p 9701 -c "CREATE EXTENSION citus;"
		psql -p 9702 -c "CREATE EXTENSION citus;"

		psql -p 9700 -c "CREATE schema test;"
		psql -p 9701 -c "CREATE schema test;"
		psql -p 9702 -c "CREATE schema test;"

		psql -p 9700 -c "alter user postgres set search_path = test, public;"
		psql -p 9701 -c "alter user postgres set search_path = test, public;"
		psql -p 9702 -c "alter user postgres set search_path = test, public;"

		psql -p 9700 -c "SELECT * from master_add_node('localhost', 9701);"
		psql -p 9700 -c "SELECT * from master_add_node('localhost', 9702);"

3. Occurrence condition
	PostgreSQL：12.3
	citus：9.3-2
	OS：centOS7.3 x86_64

**Comment by marcocitus** [comment]
We appear to be propagating the following during master_add_node:
```sql
NOTICE:  issuing SELECT alter_role_if_exists('marco', 'ALTER ROLE marco SET search_path = ''test, public''')
```

This treats "test, public" as a single schema name, rather than two separate schema names.

**Comment by marcocitus** [comment]
fwiw, we do the right thing when the actual ALTER USER happens and quote the schemas separately:
```sql
ALTER USER marco SET search_path TO test, public;
...
NOTICE:  issuing SET citus.enable_ddl_propagation TO 'off';ALTER ROLE marco SET search_path = 'test', 'public';SET citus.enable_ddl_propagation TO 'on'
DETAIL:  on server marco@localhost:9701 connectionId: 2
```

**Comment by hanefi** [comment]
We indeed quote the schema names, and treat the list as if it is a single schema.

This issue affects all configs that allow a list of values.

Here is a query that help identify user setting defaults on a machine:

```SQL
SELECT unnest(s.setconfig), r.rolname, d.datname)
FROM pg_db_role_setting s
	LEFT JOIN pg_authid r ON (s.setrole=r.oid)
	LEFT JOIN pg_database d ON (d.oid=s.setdatabase);
```

Healthy coordinator node:
```
┌────────────────────────┬─────────┬─────────┐
│         unnest         │ rolname │ datname │
├────────────────────────┼─────────┼─────────┤
│ search_path=s1, public │ hanefi  │ [NULL]  │
└────────────────────────┴─────────┴─────────┘
```

New node with corrupt search path default:
```
┌──────────────────────────┬─────────┬─────────┐
│          unnest          │ rolname │ datname │
├──────────────────────────┼─────────┼─────────┤
│ search_path="s1, public" │ hanefi  │ [NULL]  │
└──────────────────────────┴─────────┴─────────┘
```

**Comment by zyDaemon** [comment]
> fwiw, we do the right thing when the actual ALTER USER happens and quote the schemas separately:
> 
> ```sql
> ALTER USER marco SET search_path TO test, public;
> ...
> NOTICE:  issuing SET citus.enable_ddl_propagation TO 'off';ALTER ROLE marco SET search_path = 'test', 'public';SET citus.enable_ddl_propagation TO 'on'
> DETAIL:  on server marco@localhost:9701 connectionId: 2
> ```
