### ISSUE TITLE
Check merge enterprise job should fail if compilation fails on enterprise

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#4024]
Currently check merge enterprise job will succeed even if there are compilation errors on enterprise after merging community. In this case the job should fail. So basically as a last step in the script, we should run our compilation command.

**Comment by JelteF** [comment]
This indeed sounds like a good tradeoff between speed of the builds and confidence that the merged code works. Maybe running some short test that basically never fails would still be useful. Something like `make check-base`. Running more tests than that would probably make the this job take too long and be to flaky.
