### ISSUE TITLE
insert select does not support inserting from distributed table to local table

### ISSUE THREAD

**Issue by ChenHuajun** [citusdata/citus#4026]
In our scenario, we need to output the calculation results to the report to provide highly concurrent queries.
Due to the high access frequency of the report and the uncertain query conditions, it is not suitable to use a distributed table to store the report.
So we now store the report as a local table.

Currently Citus does not support the following insert select, we have to use temporary table transfer, which is not convenient to use.

```
insert into ${local table} select ... from ${distributed table}
```

problem
1. Is there a better solution to this problem?
    For example, the report uses a distributed table storage with only one shard. However, if there are a large number of reports, all report's one shard will be concentrated on the first worker, and data skew occurs.
2. If the answer of 1 is not, could support local table in insert select SQL?

**Comment by halilozanakgul** [comment]
We implemented this feature and will be available with our next release.
If you want you can test it on our [master](https://github.com/citusdata/citus) or [9.4 release](https://github.com/citusdata/citus/tree/release-9.4) branch.
