### ISSUE TITLE
ALTER TABLE ... SET LOGGED/UNLOGGED support

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#4031]
Currently we don't support `ALTER TABLE ... SET LOGGED/UNLOGGED` command for distributed tables.

If a table is UNLOGGED, then it will not be logged to WAL(write-ahead-log), which will be faster compared to ordinary table, but then they are not crash-safe. Currently we can use the following work-around to execute these commands on a distributed table:

```sql
BEGIN;

SET LOCAL citus.enable_ddl_propagation to OFF;

ALTER TABLE table SET UNLOGGED;

SET LOCAL citus.enable_ddl_propagation to ON;

SELECT run_command_on_placements('table', 'ALTER TABLE %s SET UNLOGGED');

COMMIT;
```

We should handle `AT_SetLogged/AT_SetUnLogged` cases in the codebase.

**Comment by onderkalaci** [comment]
Noting here as this came-up in a customer conversation.
