### ISSUE TITLE
CREATE INDEX CONCURRENTLY on a Local Table

### ISSUE THREAD

**Issue by halilozanakgul** [citusdata/citus#4057]
```
CREATE TABLE tbl (a int);
CREATE INDEX CONCURRENTLY ON tbl(a);
```
This crashes. It gives an error message if the table is distributed but crashes if it is not.

**Comment by halilozanakgul** [comment]
I checked that this bug exists at least since 9.2

**Comment by onderkalaci** [comment]
That's interesting, `check-vanialla` seems to pass

**Comment by marcocitus** [comment]
does check-vanilla do CREATE EXTENSION citus?

**Comment by halilozanakgul** [comment]
> That's interesting, `check-vanilla` seems to pass

@onderkalaci check vanilla does not create the extension.

**Comment by onderkalaci** [comment]
Related to https://github.com/citusdata/citus/pull/1457/files

**Comment by JelteF** [comment]
> @onderkalaci check vanilla does not create the extension.

Are you sure? If so that sounds like a pretty useless test then.

**Comment by onderkalaci** [comment]
Interesting that we seem to have the same test: https://github.com/citusdata/citus/blob/master/src/test/regress/expected/multi_index_statements.out#L94-L96

**Comment by onderkalaci** [comment]
> Interesting that we seem to have the same test: https://github.com/citusdata/citus/blob/master/src/test/regress/expected/multi_index_statements.out#L94-L96

Seems not anymore as we've changed the test from `no named index` to `named index` in the past: https://github.com/citusdata/citus/commit/111c04c2bdf3c0e83f33e05aa90a8a0a22e8bf63#diff-241e638f329e25ca48c336a1e7474e5cR102

**Comment by metdos** [comment]
An older version( https://github.com/citusdata/citus/issues/1456) is actually fixed in this PR: https://github.com/citusdata/citus/pull/1457

**Comment by halilozanakgul** [comment]
This bug does not exists in 9.1
