### ISSUE TITLE
Table with deleted IDENTITY column cannot be distributed

### ISSUE THREAD

**Issue by colton-citus** [citusdata/citus#4062]
If you create a GENERATED ... AS IDENTITY column in a table and delete that column, you cannot distribute the table. 

Reproduction code:

``` 
create table ident_test(col1 int, col2 int generated always as identity);
alter table ident_test drop column col2;
select create_distributed_table('ident_test','col1');
```

Example output: 

```
citus=> select create_distributed_table('ident_test','col1');
ERROR:  cannot distribute relation: ident_test
DETAIL:  Distributed relations must not use GENERATED ... AS IDENTITY.
```

I suspect thatRelationUsesIdentityColumns isn't checking whether the column has been deleted.

**Comment by naisila** [comment]
Not an issue anymore since now identity columns are supported anyway.
