### ISSUE TITLE
New flaky test detection 

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#4063]
Currently we have a lot of flaky tests as we all know and they keep increasing over time because when a job fails most people just rerun it from the failed on CI and therefore sometimes we introduce new flaky tests without being aware of it. I think it could be nice to find a way to prevent this from happening. One idea is:
- Run our whole test suite 10 times and compare failures to the previous day and if there is any new flaky test give us a warning so that we at least know that we introduced a new one and can take an action.

Ideally it would be better to determine this before merging a PR but that might require running the same jobs over and over which is not really feasible as that takes a long time and not really that efficient.

**Comment by onderkalaci** [comment]
Another idea could be run the newly added tests 10 times (or such) in a PR with `check-base`. With that, we can also ensure that the  test  passes with `check-base` and  could be randomly placed in the test suite in the future.

**Comment by SaitTalhaNisanci** [comment]
understanding the newly added tests might be a bit hard, like if we are adding a new test file it might be easy but what if I am changing 20 test files, will we run all of them with check-base in that case?

**Comment by onderkalaci** [comment]
> understanding the newly added tests might be a bit hard, like if we are adding a new test file it might be easy but what if I am changing 20 test files, will we run all of them with check-base in that case?

Some thoughts, not direct answer to your note:

- I have the impression that the flaky tests very often comes with new test files. Though, I might be wrong, I need to trace back.
- On the other, the flaky tests sometimes stem from running them in parallel with others (such as some deadlocks happen etc.). So, running them with `check-base` might not always work.  
- Similarly, re-running the tests might not always find all the flaky tests as moving the test files around might cause new random failures (or adding some concurrent test/earlier tests in the schedule etc.).
- Ideally, the ownership of fixing the problem should be on the author of the PR, so re-running the tests offline sounds really hard to keep track of to me.

**Comment by onurctirtir** [comment]
Outdated, today we have a CI job that detects flaky tests.
