### ISSUE TITLE
error during compilation

### ISSUE THREAD

**Issue by AlexaPopov** [citusdata/citus#408]
Hello.
I try to make citus from source.
I set  PG_CONFIG.
When I do make, I have next error:
What is it? Whot do I not right?

In file included from /home/worker1/soft/pg_sql-worker-1/include/postgresql/server/postgres.h:47:0,
                 from master/master_create_shards.c:13:
master/master_create_shards.c: In function ‘master_create_worker_shards’:
/home/worker1/soft/citus/src/include/distributed/master_metadata_utility.h:25:37: error: invalid suffix "ULLL" on integer constant
 #define HASH_TOKEN_COUNT INT64CONST(4294967296UL)
                                     ^
/home/worker1/soft/pg_sql-worker-1/include/postgresql/server/c.h:280:33: note: in definition of macro ‘INT64CONST’
 #define INT64CONST(x)  ((int64) x##LL)
                                 ^
master/master_create_shards.c:118:23: note: in expansion of macro ‘HASH_TOKEN_COUNT’
  hashTokenIncrement = HASH_TOKEN_COUNT / shardCount;
                       ^
make[1]: *** [master/master_create_shards.o] Error 1

**Comment by ozgune** [comment]
@AlexaPopov, could you share the following info to help us reproduce this?

* The underlying platform (OS X version, Ubuntu version, etc.)
* PostgreSQL version you're building against
* The set of steps you used to configure and build the Citus extension

**Comment by ImreSamu** [comment]
@AlexaPopov, : similar,  maybe related to this ?  https://github.com/citusdata/citus/pull/407 ( INT64CONST , 4294967296ULLL, FreeBSD )

**Comment by AlexaPopov** [comment]
I use Ubuntu (Distributor ID: Ubuntu,Description:    Ubuntu 14.04.4 LTS, Release:        14.04, Codename:       trusty)
Postgresql (9.5.1) from github.
 git clone https://github.com/citusdata/citus.git
cd citus
PG_CONFIG=/home/alex/soft/pg_sql-citus1/bin/pg_config
./configure
(all ok)
make -s 
and the error is 

In file included from /home/alex/soft/pg_sql-citus1/include/postgresql/server/postgres.h:47:0,
                 from master/master_create_shards.c:13:
master/master_create_shards.c: In function ─≤master_create_worker_shards─≥:
/home/alex/soft/citus/src/include/distributed/master_metadata_utility.h:25:37: error: invalid suffix "ULLL" on integer constant
 #define HASH_TOKEN_COUNT INT64CONST(4294967296UL)
                                     ^
/home/alex/soft/pg_sql-citus1/include/postgresql/server/c.h:280:33: note: in definition of macro ─≤INT64CONST─≥
 #define INT64CONST(x)  ((int64) x##LL)
                                 ^
master/master_create_shards.c:118:23: note: in expansion of macro ─≤HASH_TOKEN_COUNT─≥
  hashTokenIncrement = HASH_TOKEN_COUNT / shardCount;
                       ^
make[1]: *** [master/master_create_shards.o] Error 1
make: *** [extension] Error 2

**Comment by sumedhpathak** [comment]
@AlexaPopov This appears to be a 32-bit build issue. I was able to reproduce it on 32-bit systems, and not on 64-bit. Are you using a 32-bit instance for the Ubuntu image?

As @ImreSamu noted, it is related and fixed by #407, however we'd like to evaluate if that proposed fix is the right one for our use-case. @lithp could you look into this issue? Thanks!

**Comment by AlexaPopov** [comment]
@sumedhpathak .Yes, if I using  a 32-bit instance, I have this problem. And I have not this problem on a  64-bit sistem. Thanks for help.
In the [page](https://www.citusdata.com/docs/citus/5.0/installation/requirements.html) has written that citus works with  64-bit systems. Do you not  support 32-bit systems?

**Comment by lithp** [comment]
@AlexaPopov sorry for the delay in responding. #407 fixes compilation but Citus later crashes when run on a 32-bit system.

> Do you not support 32-bit systems?

We're discussing that internally, hope to have an answer for you soon.

**Comment by lithp** [comment]
Thanks for trying Citus out, and for one of our first external bug reports @AlexaPopov!

The changes in #407 fix compilation and will make their way in, that solves this issue.

We've decided not to support 32 bit systems though. It's unlikely someone will want to run Citus on a 32-bit machine in production and we want to focus our efforts on making Citus work better there.

I'm sorry to be closing one of our first issues with this kind of response! Hope to be more helpful next time.
