### ISSUE TITLE
Regression tests are broken on OS X

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#4080]
On OS X, I followed the instructions to contribute to Citus: https://github.com/citusdata/citus/blob/master/CONTRIBUTING.md

The last step to run the tests fails with the following message.

<pre>
ozgun$ make check
...
============== installing citus                       ==============
CREATE EXTENSION
============== running regression test queries        ==============
test multi_extension              ... env: python3: No such file or directory
diff command failed with status 32512: diff  "/workplace/citus/src/test/regress/expected/multi_extension.out" "/workplace/citus/src/test/regress/results/multi_extension.out" > "/workplace/citus/src/test/regress/results/multi_extension.out.diff"
waiting for server to shut down.... done
</pre>

I went back a few releases to see when we broke the regression tests.  If I build from our citus-9.3 branch, I see the above failure. If I build from citus-9.1, all regression tests pass.

**Comment by serprex** [comment]
We expect python3 to be installed for tests: https://docs.python-guide.org/starting/install3/osx
