### ISSUE TITLE
Redhat 6 epoll error from package

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#4105]
On redhat6, when I install citus from packages, I get the following error when trying to add a node: (this is citus 9.3.5 with pg12)
ERROR:  epoll_ctl() failed: No such file or directory

However if I install citus 9.3.5 from the source code, I don't get any errors and things work as expected.

Some extra compilation flag could be triggering this. See https://github.com/citusdata/packaging/blob/all-enterprise/citus-enterprise.spec#L42..L55

**Comment by onderkalaci** [comment]
> However if I install citus 9.3.5 from the source code, I don't get any errors and things work as expected.

If  we  compile from source and use the security flags mentioned, what would be the outcome?  Did you have a chance to look into that?

**Comment by SaitTalhaNisanci** [comment]
I tried using the security flags manually and it also worked as far as I remember. It is possible that I missed some flags though

**Comment by jonels-msft** [comment]
Still getting the error for packaged Citus 9.5

**Comment by ozgune** [comment]
Red Hat 6 reached End of Life on 12/2020. So, I'm closing this issue.

https://access.redhat.com/discussions/4768501
