### ISSUE TITLE
Why didn't pg_get_table_grants be called?

### ISSUE THREAD

**Issue by yonj1e** [citusdata/citus#4119]
pg_get_table_grants returns a list of sql statements which recreate the permissions for a specific table.
I see this function, but it is not called in the code. Is this a problem for the MX node?Or the open source version was deliberately commented out.

**Comment by thanodnl** [comment]
Hi, Thanks for you interest in this topic.

From a business perspective we have marked everything related to user management as an enterprise feature. To prevent errors during the distribution of a table we have chosen to not propagate grants on tables to the worker nodes.

If we were to propagate the grants on a table to the workers where the roles being granted are not managed we would encounter hard to decipher errors from the workers during table distribution or rebalancing of shard -albeit also an enterprise feature-.

As you see from the linked issue, we have found the function as well as being unused. We are planning to clean up the code.

In the future our separation of products might shift and code might move around. But for now this is unsupported for community.
