### ISSUE TITLE
Use PQconnectdbParams() in MultiClientConnect

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#412]
While discussing a change @jasonmp85 and I came across `MultiClientConnect()`'s current method of building a connection string. Which isn't good, as it misses out on escaping user/connect/database names, while not actually being simpler.  We should model this more like
`src/backend/distributed/utils/connection_cache.c`'s `ConnectToNode()`. Possibly by unifying the raw connection establishment.

**Comment by marcocitus** [comment]
`MultiClientConnect` no longer calls `PQconnectdbParams` directly.
