### ISSUE TITLE
added node not visible in the rest of the statement execution

### ISSUE THREAD

**Issue by thanodnl** [citusdata/citus#4121]
When a new node is added to the cluster the added row in `pg_dist_node` doesn't become visible till the next statement. This causes commands the want to process some information of the node to not see this information.

```sql
SELECT * FROM pg_dist_node WHERE nodeid = master_add_node('foobarbaz', 9700)
```

As you can see, the first time this command is executed it does not return the row containing the node information. When executed repeatedly the row becomes visible due to the idempotent behaviour of `master_add_node`.

Most likely we need to increment postgres' command counter before returning the nodeid to the user. This will make the row visible, even within the same statement.

**Comment by marcocitus** [comment]
Isn't this normal PG behaviour? The SELECT get its snapshot before the master_add_node is called.

**Comment by thanodnl** [comment]
As Marco already mentioned, this is not a bug in Citus, instead this is Postgres behaviour.

```sql
CREATE TABLE t1 (a BIGSERIAL PRIMARY KEY, b text);

CREATE OR REPLACE FUNCTION foobar(b text) 
RETURNS bigint
    LANGUAGE plpgsql
    AS $$
DECLARE
	v_a			bigint;

BEGIN
	
	INSERT INTO t1 (b) VALUES (b) RETURNING a INTO v_a;
	RETURN v_a;

END
$$;


SELECT * FROM t1 WHERE a = foobar('baz');
```

This snippet shows that the behaviour is the same when a plpgsql function causes side effects. This makes us believe that changing Citus to actually make the row visible is undoable -or hard atleast- and secondly undesirable as it changes the semantics of a Postgres query.

This does make single statement automation around the node metadata a bit harder, but not undoable.

```sql
CREATE OR REPLACE FUNCTION my_add_node(nodename text, nodeport int) 
RETURNS pg_dist_node
    LANGUAGE plpgsql
    AS $$
DECLARE
	v_nodeid		int;
BEGIN
	
	SELECT master_add_node(nodename, nodeport) INTO v_nodeid;
	RETURN (SELECT n FROM pg_dist_node n WHERE n.nodeid = v_nodeid);

END
$$;

[local] nilsdijk@postgres:9700-33768=# SELECT * FROM my_add_node('localhost', 7779);
┌────────┬─────────┬───────────┬──────────┬──────────┬─────────────┬──────────┬──────────┬─────────────┬────────────────┬──────────────────┐
│ nodeid │ groupid │ nodename  │ nodeport │ noderack │ hasmetadata │ isactive │ noderole │ nodecluster │ metadatasynced │ shouldhaveshards │
├────────┼─────────┼───────────┼──────────┼──────────┼─────────────┼──────────┼──────────┼─────────────┼────────────────┼──────────────────┤
│     13 │      13 │ localhost │     7779 │ default  │ f           │ t        │ primary  │ default     │ f              │ t                │
└────────┴─────────┴───────────┴──────────┴──────────┴─────────────┴──────────┴──────────┴─────────────┴────────────────┴──────────────────┘
(1 row)

Time: 11.271 ms
```

As the snippet above shows this wrapper will be able to read the row and return, which allows further automation.
