### ISSUE TITLE
[QUESTION] Azure for Postgres Citus Data migration cluster to cluster.

### ISSUE THREAD

**Issue by redondoxx** [citusdata/citus#4130]
Hi, currently we are using Azure for Postgres Hyper scale citus. With some specific requirement from business. We have to migrate whole DB to on-premise. So we would like to find a way to migrate (replication / clone) DB citus from Azure to our on-premise, is it possible?

**Comment by hanefi** [comment]
Please open a support ticket on Azure Portal. This repository is for the Citus Engine product and we have limited information on our SaaS offering.
