### ISSUE TITLE
Support CREATE TABLE LIKE syntax to automatically distribute tables

### ISSUE THREAD

**Issue by thanodnl** [citusdata/citus#4134]
Postgres supports the `CREATE TABLE ... (LIKE ...)` syntax. This syntax is used, among other places, in `pg_partman` to create new partitions before attaching them.

To improve partitioning for Citus we often hear that archiving older tables is desirable. Some operations for archival could benefit from the `CREATE TABLE LIKE` syntax if the table gets created colocated with the old table. A subsequent `INSERT INTO SELECT` would be fully parallel without data repartitioning.

A prototype of this behaviour has been created in https://github.com/citusdata/citus/tree/feature/create-table-like

Things not addressed in the prototype are:
 - [ ] Tests
 - [ ] Verified if it is always correct to use the distribution column VAR data structure of the LIKE table.

For the last points it would be important to create tables like tables that use the not the first column as the distribution column. Use a non-first column with a preceding column deleted before the like syntax is called.

These situations might, depending on how Postgres implements -now and in the future- the CREATE TABLE LIKE and how attributes are numbered.

**Comment by metdos** [comment]
@thanodnl removing the Citus 10 milestone, let me know if it is not okay.

**Comment by thanodnl** [comment]
makes sense, this got deprioritized. SE uses the LIKE syntax often and wanted to not change its behaviour when ran on distributed tables.

Instead we have added the UDF's to rotate old partitions. Will close this issue (bydesign)
