### ISSUE TITLE
Support Table Access Methods on distributed tables

### ISSUE THREAD

**Issue by thanodnl** [citusdata/citus#4135]
Postgres 12 introduced the Table Access Method API.

Currently Citus does not apply the AM of a table during distribution or shard creation. This results in the shards always being created with the database default access method, which is mostly the heap.

Ideally the shards would be created with the same access method the table on the Coordinator had before distribution. Since access methods require C code to work they will mostly if not always be packed in an extension. To make sure the table can be created with the Access Method the extension needs to be resolved as a dependency for the table to be distributed.

A prototype of this work is available in https://github.com/citusdata/citus/tree/feature/tableam

Things that are known to not work:
 - [ ] Scanning of the original table with a different access method and even the heap.
 - [ ] Tests
    - [ ] Traversing of extensions providing Table AM's
    - [ ] Table AM's being applied to distributed tables
    - [ ] Table AM's being applied to new shards due to shard splits (enterprise) etc.

**Comment by marcocitus** [comment]
Closed by #4250
