### ISSUE TITLE
how to pg11-citus9.1.1 to pg13-citus(master branch) to make citus support pg 13

### ISSUE THREAD

**Issue by canon99** [citusdata/citus#4153]
- what i want to do

upgrade **pg11-citus9.1.1** to  **pg13-citusmaster**

- what document i am following: 

[citusdata.com/upgrade](http://docs.citusdata.com/en/v9.4/admin_guide/upgrading_citus.html?highlight=upgrade#upgrading-postgresql-version-from-11-to-12), which said to upgrade "citus version" first, upgrade "pg version" second.

- what is my problem:

how to upgrade **citus(9.1.1)** to **citus(master branch),** because citus(latest version **9.4** not support **pg13** as image below)

**Comment by canon99** [comment]
![111](https://user-images.githubusercontent.com/19160032/92702526-e404b300-f383-11ea-94f4-c473a1c3e372.png)

**Comment by canon99** [comment]
how to upgrade citus in my case, help~~~
![222](https://user-images.githubusercontent.com/19160032/92703317-ac4a3b00-f384-11ea-9bd0-496edd70742e.jpg)

**Comment by canon99** [comment]
![444](https://user-images.githubusercontent.com/19160032/92706429-14018580-f387-11ea-9c68-97ea30b4a5c7.jpg)

**Comment by onurctirtir** [comment]
https://github.com/citusdata/citus/issues/4153#issuecomment-690096108
It looks like you managed to install Citus from master branch, should we close this issue ?
