### ISSUE TITLE
copy_to_distributed_table should support database uri

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus#417]
The hash distribution page in the 5.0 docs asks the user to run

```bash
copy_to_distributed_table -C github_events-2015-01-01-0.csv github_events
```

However when using the `try-citus` distribution the master database will be running on a nonstandard port (9700). For maximum flexibility this script should accept a standard `postgres://` uri to accommodate.

**Comment by lithp** [comment]
`copy_to_distributed_table` ends up calling `psql`, and therefore [the standard environment variables](http://www.postgresql.org/docs/9.5/static/libpq-envars.html), such as PGPORT, PGHOST, and PGDATABASE, should work.

Point taken though, it should probably match the tutorials and also accept a uri.

**Comment by ozgune** [comment]
@begriffs and @lithp, we're working on native ``COPY`` support for hash and range partitioned tables in #416. This pull request offers notably superior performance and a much better user-experience.

@marcocitus or @metdos, can you think of any reasons to keep ``copy_to_distributed_table`` once #416 gets checked in? If not, I'll close this issue with the 5.1 timeline in mind.

**Comment by metdos** [comment]
I think with the 5.1 release, we shouldn't need it anymore.

**Comment by marcocitus** [comment]
I kind of like it as a form of insert benchmarking, but should definitely be removed before 5.1.

**Comment by ozgune** [comment]
I'm then closing this issue as "will not fix". @begriffs, if you aren't convinced that native ``COPY`` support will resolve this problem, could you re-open this issue?

Two quick notes:
* We're tracking native ``COPY`` support in #416
* We'll need to update our 5.1 documentation. For and after 5.1, we need to refer to ``COPY`` instead of ``copy_to_distributed_table``
