### ISSUE TITLE
Provide Citus with Amazon Web Services RDS

### ISSUE THREAD

**Issue by thedrow** [citusdata/citus#418]
It'd be awesome to be able to install Citus on Postgres RDS instances instead of having to manage the machines ourselves.
I'm not sure if this is the right place to raise this but I'm going to anyway.
Could you guys try to talk to AWS and see if it's possible to add support for Citus in their Postgres RDS instances?

**Comment by marcocitus** [comment]
Citus is not currently available on RDS. However, with a number of limitations, it is possible to use RDS nodes as worker instances. 

This is experimental and uses an older version of Citus:
https://www.citusdata.com/blog/14-marco/178-scaling-out-postgresql-on-amazon-rds-using-masterless-pg-shard

**Comment by thedrow** [comment]
I know that blog post. 
What I'm asking if it is possible to contact AWS in order to provide Citus support on their Postgres RDS offering.

**Comment by craigkerstiens** [comment]
@thedrow thanks for the input, we'd love to see Citus be more available and easier to use on cloud providers out of the box such as RDS. We'll see what can do to work with them in the future around this.

**Comment by gajus** [comment]
> @thedrow thanks for the input, we'd love to see Citus be more available and easier to use on cloud providers out of the box such as RDS. We'll see what can do to work with them in the future around this.

Was there any progress regarding this?

**Comment by marcocitus** [comment]
We've made Citus available natively on [Azure](https://azure.microsoft.com/en-gb/services/postgresql/). There are no plans to make it available on RDS.

**Comment by francoisruty** [comment]
@marcocitus is there any plan to provide Citus on AWS RDS?
You're missing on a lot of tech companies
In most azure companies, Azure is forced onto tech by the business, why would you chose Azure to provide Citus natively?

**Comment by qnm** [comment]
> why would you chose Azure to provide Citus natively?

https://www.citusdata.com/blog/2019/01/24/microsoft-acquires-citus-data/
