### ISSUE TITLE
EXPLAIN (ANALYZE, WAL) is not supported - PG 13

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#4193]
PG 13 added support for `WAL` parameter to explain analyze and Citus doesn't support it yet
```SQL
EXPLAIN (ANALYZE, WAL) DELETE FROM table WHERE c1 = 20000 ;
...
WAL: records=XX bytes=XX
```
```

Should be fairly easy to support. This parameter could be useful to detect IO heavy write queries

**Comment by JelteF** [comment]
This should only require a little addition here: https://github.com/citusdata/citus/blob/64d5ac6a104129ab16c105e00caa436d94508def/src/backend/distributed/planner/multi_explain.c#L878
