### ISSUE TITLE
Syncing data / shards after Node fail?

### ISSUE THREAD

**Issue by mega-rok** [citusdata/citus#4195]
Hello,
I have set my replicaton_factor in Citus to 2 so every Node (Worker) has every data in case that if one Node (Worker) gets a failure (goes offline) I can still get all the data.
The problem and example I have is: I don't know how to get data inside of a Node (Worker) that failed while I was using INSERT and adding data to the DB? I have two Nodes and one Coordinator so basically after Node1 went offline and I added data to the DB Node2 got the data (Node1 obviously didn't because it was offline). Now I need to sync that data / shards to Node1 because at this time Node1 is basically useless. How can I do that (do I need Enterprise for that)?

Best regards

**Comment by onderkalaci** [comment]
No, you can use master_copy_shard_placement to repair the  INVALID shard placement on citus community edition: https://docs.citusdata.com/en/v9.4/develop/api_udf.html?highlight=master_copy_shard_placement#master-copy-shard-placement

You  can see some examples in the regression test files: https://github.com/citusdata/citus/blob/c563e0825c6e564160aa007056681c102ebf1740/src/test/regress/sql/multi_repair_shards.sql

I'll close the issue @mega-rok, let us know if you need anything further
