### ISSUE TITLE
Publish TPC-DS benchmarks on PostgreSQL

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#42]
TPC-DS benchmarks are new and target mixed workloads. The [TPC-DS website](http://www.tpc.org/tpcds/) shows that there are currently no published benchmark results.

We considered publishing benchmark results for PostgreSQL. However, the benchmark looked too long and complex for us to prioritize this ahead of other activities.

**Comment by serprex** [comment]
Some progress has been made in past few years:

https://www.slideshare.net/SergeyPetrunya/lessons-for-the-optimizer-from-running-the-tpcds-benchmark

repo from above link: https://github.com/spetrunia/tpcds-run-tool
greenplum: https://github.com/pivotalguru/TPC-DS

**Comment by ozgune** [comment]
Over time, we moved towards publishing benchmarks for transactional (TPC-C / HammerDB) and real-time analytics (CH Benchmark) workloads. You can read a summary of our latest understanding here:

https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/how-to-benchmark-performance-of-citus-and-postgres-with-hammerdb/ba-p/3254918

We don't have any immediate plans to publish TPC-DS results. We'll likely make more progress on HammerDB, CH Benchmark, and potentially TPC-H. As such, I'll close this issue.
