### ISSUE TITLE
Consider changing nodeport type in pg_dist_shard_placement to int4

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#424]
Currently, the type of nodeport in the pg_dist_shard_placement is int8, which should be int4.

Changing the type will require an version change with an upgrade script containing:
ALTER TABLE pg_dist_shard_placement ALTER COLUMN nodeport TYPE int4;

To upgrade, users need to install the new version and run:
ALTER EXTENSION citus UPDATE;

While using the wrong type is currently causing issues on 32-bit platforms (#422), there is a simple fix (#423) and it might be better to defer changing metadata until other metadata changes are required.

**Comment by anarazel** [comment]
> Currently, the type of nodeport in the pg_dist_shard_placement is int8, which should be int4.
> 
> Changing the type will require an version change with an upgrade script containing:
> ALTER TABLE pg_dist_shard_placement ALTER COLUMN nodeport TYPE int4;
> 
> To upgrade, users need to install the new version and run:
> ALTER EXTENSION citus UPDATE;
> 
> While using the wrong type is currently causing issues on 32-bit platforms (#422), there is a simple fix (#423) and it might be better to defer changing metadata until other metadata changes are required.

We'd probably need to prevent doing any substantial work until the ALTER
EX UP is done - otherwise we'd risk crashes.

**Comment by marcocitus** [comment]
> We'd probably need to prevent doing any substantial work until the ALTER EX UP is done - otherwise we'd risk crashes.

There's a time window between the reloading the library, which reverts to using UInt32GetDatum, and running the alter extension, which updates the column to 32-bit. Given that the current code works on 64-bit systems, it seems like only 32-bit systems could crash in this time window, right?  

(optimistically assuming that the current code doesn't crash on any 64-bit systems)

**Comment by anarazel** [comment]
> > We'd probably need to prevent doing any substantial work until the ALTER EX UP is done - otherwise we'd risk crashes.
> 
> There's a time window between the reloading the library, which reverts to using UInt32GetDatum, and running the alter extension, which updates the column to 32-bit. Given that the current code works on 64-bit systems, it seems like only 32-bit systems could crash in this time window, right?  

It's quite possible that you'd get a crash on 64bit systems after
changing this; because the C perspective would not correlate to the
database layout in a number of scenarios.

**Comment by lithp** [comment]
I looked into this some more, I can't find anywhere in the code where we treat node port as a 64-bit integer. The only reference to int8 I could find was in the catalog.

Any objections to forgoing the change which fixes this crash, and just releasing an update instead?

**Comment by ozgune** [comment]
Sounds good to me. @marcocitus and @anarazel, if you have any objections, could you chime in?

**Comment by marcocitus** [comment]
I don't have strong objections as long as we consider the downsides/risks:

- No way of undoing an extension update except manually altering back the column
- Temporary inconsistency between C and database could cause crashes
- Users might install the new version (e.g. via yum), but forget to run the update

**Comment by lithp** [comment]
I don't have a response to the first point but:

> Temporary inconsistency between C and database could cause crashes

The proposal is to not merge #423 PR which treats nodeport as 64 bit, and
instead just change nodeport to 32-bit. I don't believe this will cause any
temporary inconsistency, but instead a transition from inconsistency to
consistency.

> Users might install the new version (e.g. via yum), but forget to run the
update

I don't think this is any worse than not releasing the update. We've only
noticed a problem on 32-bit systems, which currently don't work at all. If
we release this with 5.1, presumably they'd update to get everything else
5.1 comes with?

**Comment by sumedhpathak** [comment]
@lithp What are the next steps here? Is there an extension upgrade script that needs to be written which does the ALTER statement?

**Comment by anarazel** [comment]
Note that, in the course of #423, we changed ```TupleToShardPlacement()`` and ```InsertShardPlacementRow()``` to treat Anum_pg_dist_shard_placement_nodeport as a 64bit integer. That'll have to be changed back once we're going forward with this.

**Comment by sumedhpathak** [comment]
@lithp @anarazel Is the plan then on not making this change in 5.1?

**Comment by anarazel** [comment]
> @lithp @anarazel Is the plan then on not making this change in 5.1? 

Personally I think 5.2 is a better target; we have more than enough on
our plate for 5.1.

**Comment by jasonmp85** [comment]
Removing from 5.1.

**Comment by ozgune** [comment]
When working on the int8 -> int4 change, we found out a scenario where the user needs to pay special attention during the upgrade. @anarazel therefore opened an issue (#907) to propose improvements to the safety of extension upgrades. This proposal would allow us to safely upgrade the Citus extension even when we change a metadata table's column type.

I'm therefore removing the v6.0 tag from this issue. I'll add #907 to our shortlist of items for v6.2 planning.

**Comment by marcocitus** [comment]
Fixed by #1453
