### ISSUE TITLE
Unable to download the package for Linux.

### ISSUE THREAD

**Issue by mahajanankur** [citusdata/citus#4263]
I am unable to update or install the Citus data 9.4 on my ubuntu 18.04. Please find below the error I get when I try to upgrade or install.

```
curl https://install.citusdata.com/community/deb.sh | sudo bash
sudo apt-get -y install postgresql-12-citus-9.4
```

**ERROR**
`E: Failed to fetch https://repos.citusdata.com/community/ubuntu/dists/bionic/InRelease  402  Payment Required [IP: 2600:9000:2149:e000:0:fb01:a740:93a1 443]`

![citus_error](https://user-images.githubusercontent.com/7963490/96680648-89537380-1393-11eb-91a4-9c603fbc0d23.png)

**Comment by arghaya** [comment]
Hi Citus team, 

I am also facing the same issue. Hope its fixed asap.

**Comment by rajbasnet0007** [comment]
I'm also facing same error on my server, when upgrading with latest version.....

**Comment by onderkalaci** [comment]
We are looking into this now, we'll keep you updated. Sorry for the inconvenience

**Comment by allan-heap** [comment]
Thanks @onderkalaci is there an update or status page that we can monitor the issue on?

**Comment by onderkalaci** [comment]
> Thanks @onderkalaci is there an update or status page that we can monitor the issue on?

Unfortunately we don't have such a status page :/

**Comment by james727** [comment]
Any updates on this or estimated time to resolution?

**Comment by metdos** [comment]
This problem is resolved now.

**Comment by wissam-khair** [comment]
again ... we have this issue today ??

https://repos.citusdata.com/community/ubuntu/dists/jammy/main/source/Sources

please .. we need your help and support.
