### ISSUE TITLE
Update Package in Redhat/Centos 

### ISSUE THREAD

**Issue by bilbusra** [citusdata/citus#4266]
Hi,
I'm having a `HTTPS Error 402 - Payment Required` error from your **https://repos.citusdata.com/community/el/7/x86_64/repodata/repomd.xml**. When I inspect that repo, I find that there is no package in that repo. How can I solve this problem? Can you also repo link for update and install in your documentation? It seems like the links are not ok for installation.

**Comment by bilbusra** [comment]
I also share error logs:

[root@test ~]# **sudo yum update citus94_12**
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.natro.com
 * epel: ftp.plusline.net
 * extras: istanbul.centos-mirror.guzel.net.tr
 * updates: istanbul.centos-mirror.guzel.net.tr
https://repos.citusdata.com/community/el/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 402 - Payment Required
Trying other mirror.
https://repos.citusdata.com/community/el/7/SRPMS/repodata/repomd.xml: [Errno 14] HTTPS Error 402 - Payment Required
Trying other mirror.
_No Match for argument: citus94_12
No package citus94_12 available._

**Comment by onurctirtir** [comment]
We know and trying to solve that issue, sorry for that

Also, same with https://github.com/citusdata/citus/issues/4263

**Comment by bilbusra** [comment]
Sorry, I did not see the issue. 
Thank you for your answer.

**Comment by metdos** [comment]
This problem is resolved now.
