### ISSUE TITLE
Citus shard helper view

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#4277]
In general we need to join some metadata tables to learn where a shard is, or what table it belongs to or what type of table it is etc.

I think it would be convenient to create a view for this purpose so that we don't have to do this over and over. This issue is more of a discussion on this. For example we could have the following view:

```sql
CREATE VIEW shard_helper AS
SELECT
     pg_dist_shard.shardid, 
     pg_dist_shard.logicalrelid,
     pg_dist_partition.partmethod,
     pg_dist_node.nodename,
     pg_dist_node.nodeport
FROM
   pg_dist_shard 
JOIN 
   pg_dist_placement
ON 
   pg_dist_shard.shardid = pg_dist_placement.shardid   
JOIN
   pg_dist_node
ON
   pg_dist_placement.groupid = pg_dist_node.groupid      
JOIN
   pg_dist_partition         
ON
   pg_dist_partition.logicalrelid = pg_dist_shard.logicalrelid
;     

```

And then while investigating an ICM/ticket or some local debugging we can just see information about a shard with:

```psql
[local] talha@talha:9700-17357=# SELECT * FROM shard_helper where shardid = 102071;
 shardid | logicalrelid | partmethod | nodename  | nodeport
---------+--------------+------------+-----------+----------
  102071 | ab           | h          | localhost |     9702
(1 row)

```

So if people agree that such a view could be useful, we can decide what columns to have there as well.

**Comment by marcocitus** [comment]
covered by citus_tables & citus_shards
