### ISSUE TITLE
Join with Recursive View and Condition Fails

### ISSUE THREAD

**Issue by halilozanakgul** [citusdata/citus#4280]
```
CREATE TABLE local_table(a INT);
CREATE RECURSIVE VIEW vw(c) AS (SELECT 1 FROM local_table);

CREATE TABLE ref_table(b INT);
SELECT create_reference_table('ref_table');

SELECT * FROM ref_table LEFT OUTER JOIN (SELECT * FROM vw WHERE FALSE) AS sub ON FALSE;

ERROR:  relation "public.local_table" does not exist
CONTEXT:  while executing command on localhost:9701
```
This query does not fail when the view is not recursive or when there is no `WHERE FALSE` statement.

**Comment by halilozanakgul** [comment]
This issue was introduced in 9.4

**Comment by onderkalaci** [comment]
Verified that it is caused by https://github.com/citusdata/citus/pull/3887

**Comment by onderkalaci** [comment]
It looks like when there is  `WHERE FALSE`, the relation do  not  get into `multi_join_restriction_hook `. Hence ,  the logic  [here](https://github.com/citusdata/citus/pull/3887/files#diff-3a10926b5b6507fef6f9e9fe86a6a95220a5775ae4529358ebd49a879c4a0383R2139) is broken.

We  should find a better way to get that information
