### ISSUE TITLE
Union with Distributed Partitioned Table Fails

### ISSUE THREAD

**Issue by halilozanakgul** [citusdata/citus#4287]
```
CREATE TABLE dist(a int) PARTITION BY RANGE(a);
SELECT create_distributed_table('dist', 'a');

SELECT * FROM dist UNION SELECT 1;
```
```
ERROR:  could not run distributed query with UNION, INTERSECT, or EXCEPT
HINT:  Consider using an equality filter on the distributed table's partition column.
```

**Comment by onderkalaci** [comment]
This seems like a significant regression from 9.4:

https://github.com/citusdata/citus/pull/4143/commits/3a73fba81082480b6d80cc348b944407f93bfe69

This commit breaks  this query and many other, like `SELECT * FROM dist UNION SELECT * FROM dist`

Note that if we use a non-partitioned table, the query works fine. We should probably add `RELKIND_PARTITIONED_TABLE` [here](https://github.com/citusdata/citus/commit/3a73fba81082480b6d80cc348b944407f93bfe69#diff-0c034f54cf4c096f600bdf9b18cb35142e6ac0ef12638cccf0aad86c2a4538cfR2292)

**Comment by onderkalaci** [comment]
This has some other side effects, such as a non-pushdownable query on partitioned tables are pushed down, where `b` is not the distribution key:

```SQL
select * from (SELECT b, random() FROM partitioned_dist GROUP BY b) as foo;
..
DEBUG:  distributed statement: SELECT worker_column_1 AS b, worker_column_2 AS random FROM (SELECT foo.b AS worker_column_1, foo.random AS worker_column_2 FROM (SELECT partitioned_dist.b, random() AS random FROM public.partitioned_dist_102265 partitioned_dist GROUP BY partitioned_dist.b) foo) worker_subquery
...
```
