### ISSUE TITLE
Gitter channel

### ISSUE THREAD

**Issue by benhutchison** [citusdata/citus#429]
Congrats and thank you for making citus db open source! 

One of the features of a healthy open source project is a healthy community, and a place to gather and discuss the technology. I'd like to see a gitter channel for citus. I think gitter offers some compelling features eg:
- User accounts linked to github
- Easily searchable archives
- Notifications when somebody mentions you
- Integration with github issues
- Code formatting inline

Im in #citus IRC and there are 11 people in the channel. Surely there are more than 11 people interested in this awesome tech? I think offering a gitter channel can support and grow community around the project.

**Comment by ozgune** [comment]
@benhutchison, thanks for your comment. For the open source announcement, we looked at IRC, Gitter, and Slack and decided to go with IRC.

We're constantly looking for better ways to improve on interacting with our users. I'll chat with @begriffs and @craigkerstiens -- one of them will own this issue.

**Comment by benhutchison** [comment]
Actually I was unaware of the Citus Google Group when I raised this issue.
While Im not personally much of a fan of IRC and would prefer Gitter for
chat style interaction, the google group will help support community
discussion & support.

**Comment by begriffs** [comment]
@benhutchison I just updated the readme to try to make the google group easier to find. Would you say it's more discoverable now?

**Comment by begriffs** [comment]
Slack room is also available: https://slack.citusdata.com
