### ISSUE TITLE
Geqo Causes failure_ddl Failure Test to Fail

### ISSUE THREAD

**Issue by halilozanakgul** [citusdata/citus#4290]
The failure_ddl of failure tests fails when qego is turned on.
The fails look like this:
```
SELECT citus.mitmproxy('conn.onAuthenticationOk().cancel(' ||  pg_backend_pid() || ')');
  mitmproxy 
 -----------
  
 (1 row)
 
 ALTER TABLE test_table ADD COLUMN new_column INT;
 ERROR:  canceling statement due to user request
 SELECT array_agg(name::text ORDER BY name::text) FROM public.table_attrs where relid = 'test_table'::regclass;
-  array_agg
----------------------------------------------------------------------
- {key,value}
-(1 row)
-
+ERROR:  canceling statement due to user request
```

One way to test this is to add
```
push(@pgOptions, "geqo_threshold=2");
push(@pgOptions, "geqo_pool_size=1000");
push(@pgOptions, "geqo_generations=1000");
```
at the pg_regress_multi.pl file (for example [here](https://github.com/citusdata/citus/blob/feca38150023ffd195b29537a82bd689040856de/src/test/regress/pg_regress_multi.pl#L428))

**Comment by onderkalaci** [comment]
It is very likely that the the geqo changes do not directly effect the unrelated failure test. But, it was very surprising that we consistently get this failure when geqo is enabled

**Comment by marcocitus** [comment]
did not see this for a long time
