### ISSUE TITLE
ERROR:  cannot calculate the size because replication factor is greater than 1

### ISSUE THREAD

**Issue by hancci** [citusdata/citus#4291]
### following sql occurs an error
* **version** : 
   * PostgreSQL 12.2 
   * citus-v9.2-4
* **symptom** : `ERROR:  cannot calculate the size because replication factor is greater than 1`
* **sql**
```sql
select b.logicalrelid, pg_size_pretty(citus_total_relation_size(b.logicalrelid)) AS size
from pg_dist_colocation a, pg_dist_partition b
where a.shardcount =1 and a.replicationfactor =1
and a.colocationid = b.colocationid
;
ERROR:  cannot calculate the size because replication factor is greater than 1
```

If I change the condition **`a.shardcount = 1`** to **`a.shardcount <> 1`**, It returns the result well.
Any help please? Thanks.

**Comment by onurctirtir** [comment]
Yes, `citus_total_relation_size` currently does not support relations with `replication factor > 1`.
But for relations with `replication factor > 1`, you can use below query to get total relation size:

```sql
SELECT sum(result::int) FROM run_command_on_placements(
'<tableName>',
$cmd$
select pg_total_relation_size('%s');
$cmd$
);
```

Does that work for you ?

**Comment by hancci** [comment]
No, my `replication factor` is all `1`.
And there is `a.replicationfactor =1` condition in the where clause. 
Nevertheless, it is strange that an error occurred.

**Comment by hancci** [comment]
@onurctirtir 
This is the evidence. It seems like a bug. What do you think of the results below?

```sql
mycitus=# create table my_test_table ( c1 int not null, c2 int );
CREATE TABLE
Time: 1.964 ms

mycitus=# set citus.shard_count to 1;
SET
Time: 0.295 ms

mycitus=# select create_distributed_table('my_test_table','c1');
 create_distributed_table
--------------------------

(1 row)

Time: 18.866 ms

mycitus=# insert into my_test_table select generate_series(1,10), generate_series(1,10);
INSERT 0 10
Time: 5.889 ms

mycitus=# select citus_total_relation_size('my_test_table');
ERROR:  cannot calculate the size because replication factor is greater than 1
Time: 0.402 ms

```

**Comment by onurctirtir** [comment]
> @onurctirtir
> This is the evidence. It seems like a bug. What do you think of the results below?


Hi, unfortunately I couldn't reproduce the issue.
Can you share the output of below :

```sql
select logicalrelid, a.colocationid, a.replicationfactor from pg_dist_colocation a, pg_dist_partition b where a.colocationid = b.colocationid;
```

**Comment by hancci** [comment]
@onurctirtir 
Thank you. please help me.
```sql
# select logicalrelid, a.colocationid, a.replicationfactor
from pg_dist_colocation a, pg_dist_partition b
where a.colocationid = b.colocationid
and logicalrelid='my_test_table'::regclass;
 logicalrelid  | colocationid | replicationfactor
---------------+--------------+-------------------
 my_test_table |            6 |                 1
(1 row)

Time: 0.626 ms

```

**Comment by hancci** [comment]
@onurctirtir 
Don't you think it's a bug?

**Comment by colton-citus** [comment]
Could you give the results of this query? I'm curious about the state of the metadata.

```
select * from pg_dist_shard_placement where shardid in (select shardid from pg_dist_shard where logicalrelid::text='my_test_table')
```

**Comment by hancci** [comment]
@colton-citus 
Thank you. The results of the query are as follows.
```sql
select * from pg_dist_shard_placement where shardid in (select shardid from pg_dist_shard where logicalrelid::text='my_test_table');

 shardid | shardstate | shardlength |      nodename       | nodeport | placementid
---------+------------+-------------+---------------------+----------+-------------
  102104 |          1 |           0 | dev-cituspoc003-ncl |     6432 |          97
```

**Comment by colton-citus** [comment]
This table apparently only has one shard. Did you create this as a reference table and/or set citus.shard_count to 1?

**Comment by hancci** [comment]
@colton-citus 
Yes. shard_count is 1. - Only a few have a table with shard_count=1 because I have some internal reasons.
This is a script that you could test. https://github.com/citusdata/citus/issues/4291#issuecomment-723735303

**Comment by colton-citus** [comment]
I am able to reproduce this on 9.3-2 with a shard_count of 1. Here's the script I used. This behavior does not happen with a shard_count of >1. 

```
create table my_test_table ( c1 int not null, c2 int );
set citus.shard_count to 1;
select create_distributed_table('my_test_table','c1');
select citus_total_relation_size('my_test_table');
```
@onurctirtir , let me know if you need access to my test environment where I observed this behavior.

**Comment by onurctirtir** [comment]
> I am able to reproduce this on 9.3-2 with a shard_count of 1. Here's the script I used. This behavior does not happen with a shard_count of >1.
> 
> ```
> create table my_test_table ( c1 int not null, c2 int );
> set citus.shard_count to 1;
> select create_distributed_table('my_test_table','c1');
> select citus_total_relation_size('my_test_table');
> ```
> 
> @onurctirtir , let me know if you need access to my test environment where I observed this behavior.

Yes, I could also reproduce this now, even on 9.5.1 but not on master.
Surprisingly, Citus actually shouldn't behave such tables as replicated ones, this is a bug.
But as we started to support size functions on replicated tables, the issue is **hidden** on master, by commit 4098d33acb7576b13481ffc320aff1b88188582b
