### ISSUE TITLE
count(distinct case when ... end) does not work

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#434]
When I run a query like the following on a distributed table, Citus says that the query isn't supported.

Lineitem is partitioned on l_orderkey by hash and has just one shard.

```sql
  select
  	count(DISTINCT CASE
            WHEN l_quantity > 10
               	THEN l_orderkey
            ELSE
               	NULL
            END) as c 
  from
  	lineitem
  group by 
  	l_orderkey;
```

The error message is

```
ERROR:  cannot compute aggregate (distinct)
DETAIL:  aggregate (distinct) on complex expressions is unsupported
HINT:  You can load the hll extension from contrib packages and enable distinct approximations.
```

We check if the given aggregate expression's distinct clause is on a single column, and if it is not, we error out - in AggregateDistinctColumn() function. Theoretically, if the query is grouped by partition column or it is a repartition subquery, we should able to run complex count(distinct) expressions.

**Comment by metdos** [comment]
We ran into this issue during a customer engagement in subquery repartition context. Related to #365.

**Comment by metdos** [comment]
Also related with #311.

**Comment by mtuncer** [comment]
Just a side node, router planner/executor can support this query if user provides a filter clause on partition column (l_orderkey = <some order key>) instead of group by.

**Comment by mtuncer** [comment]
we have a relatively simple way to execute distinct aggregates if the query
1 - is on a single table
2 - has no subqueries
3 - has a group by on the partition column
and
4 - source table shards' partitionColumn ranges do not overlap

Supporting this query for repartition queries require little bit more work on the planner side.
