### ISSUE TITLE
Documentation search optimized

### ISSUE THREAD

**Issue by tostasqb** [citusdata/citus#435]
Just began testing citus db, seems really promising and useful. I would like to leave a suggestion concerning documentation since it's not easy to find something in there, and getting started with citus is all about documentation.

I just searched for [Adding a worker](https://www.citusdata.com/docs/citus/5.0/search.html?q=Adding+a+worker&check_keywords=yes&area=default) and results were none. After digging a little finally got [the page](https://www.citusdata.com/docs/citus/5.0/admin_guide/cluster_management.html?highlight=adding) I was looking for.

I thought the documentation was made using [mkdocs](http://www.mkdocs.org/) since the theme looks similar to other I have seen but since the search is not that good, and I didn't find the documentation as a github repo, my suggestion would be to switch to mkdocs, or try to solve this search problem.

**Comment by ozgune** [comment]
@tostasqb -- thanks for getting in touch with us. We're working on making two improvements to our documentation:

1. We keep our documentation source in a Github repository. We intend to make this repo and its issues public to be more transparent. (once we check that the repo's history doesn't have any sensitive info). I'll talk to @lithp and @begriffs on this.
2. We are improving the "search" functionality on our website. I'll chat with @craigkerstiens on this and will update this thread in a few days.

**Comment by tostasqb** [comment]
:thumbsup:

**Comment by begriffs** [comment]
@tostasqb our documentation source is now publicly accessible at https://github.com/citusdata/citus_docs

We are investigating three options to improve the search accuracy

1. Hosting on [readthedocs](https://readthedocs.org/) which "features a powerful built-in search that exceeds the possibilities of Sphinx' JavaScript-based offline search.”
2. Adding a google custom search to the docs page
3. Installing a [Sphinx search adapter](http://www.sphinx-doc.org/en/stable/web/searchadapters.html) (seems kind of difficult though)

**Comment by tostasqb** [comment]
Option 1 seems to be a good move from where I'm standing, but nicely done making it available for the community already.

**Comment by ozgune** [comment]
@begriffs -- I know that we made notable improvements to our documentation search. Are we in a good place with our docs search now (that we can close this issue)?

**Comment by begriffs** [comment]
@ozgune the docs are currently searchable but with poor indexing as explained in https://github.com/citusdata/citus_docs/issues/89.

@agjohnson is currently working on fixing this issue.

**Comment by begriffs** [comment]
Search now returns more and better results.

**Comment by tostasqb** [comment]
@begriffs, Although I'm not actively developing a project in citus anymore, I'm a little disappointed with the result here (not the efford), I mean, a search for "adding a worker" should return the page:

http://docs.citusdata.com/en/v5.2/admin_guide/cluster_management.html?highlight=worker#adding-a-worker

Instead, this is the result: 

http://docs.citusdata.com/en/v5.2/search.html?q=adding+a+worker&check_keywords=yes&area=default

ReadTheDocs surely has it's perks, and maintaining multiple versions may be the top feature, but search is at the bottom. The day may come when you'll consider evaluating other documentation software so I won't dwell on this.

PS. For posterity this may be interesting to keep an eye on this mkdocs issue https://github.com/mkdocs/mkdocs/issues/193

**Comment by begriffs** [comment]
Weird, it looks like the RTD search API is temporarily broken. This is currently responding with a 500:
https://readthedocs.org/api/v2/search/?q=worker&project=citus-docs&version=v5.2&language=en

**Comment by agjohnson** [comment]
Should be resolved, there was an issue with our search stack.

**Comment by sumedhpathak** [comment]
Re-opening the issue, since the search seems to have regressed again.

**Comment by begriffs** [comment]
@sumedhpathak it's looking good today, when I search for "adding a worker" as mentioned above it returns the cluster management page. Also the RTD search API is returning results. Do you have an example search term that performs poorly?

**Comment by begriffs** [comment]
@tostasqb things are looking good now. I set up a network monitoring tool to watch the search API endpoint health and see if there are any intermittent problems.
