### ISSUE TITLE
Wrong link in DOC

### ISSUE THREAD

**Issue by KES777** [citusdata/citus#437]
On [this](https://www.citusdata.com/docs/citus/5.0/installation/single_node_linux.html) page for Citus 5.0 documentation there link to old 4.0 citus

    We’ve provided a tarball which lets you configure and start Citus without requiring sudo.
    https://s3.amazonaws.com/packages.citusdata.com/tutorials/try-citus-4.tar.gz

Please fix to point to try-citus-5.tar.gz

**Comment by ozgune** [comment]
@KES777 -- thanks for opening up an issue on this.

I'm guessing the "4" in the package name reflects an internal version number for the "try-citus" bundle rather than the actual Citus version.

@lithp bundled up our tutorials, and I'm assigning this issue to him to clarify.

**Comment by lithp** [comment]
Yep, sorry about the confusion. We never had these kinds of tarballs for the old citus, that's the 4th internal version of the try-citus tarball.

I'll see if we can change that url to make it less confusing,

**Comment by lithp** [comment]
The tutorials have been updated and use a better naming scheme. Thanks for the ticket!

**Comment by KES777** [comment]
thank you
