### ISSUE TITLE
Link is not clickable

### ISSUE THREAD

**Issue by KES777** [citusdata/citus#438]
on [this](https://www.citusdata.com/) page the text 'Read more' is not clickable

    Read more about Citus 5.0 which unforked from Postgres–It is now a Postgres extension and fully...

something hide it from click. I even can not select a text.

Reproducable in FF and Chrome

**Comment by ozgune** [comment]
@KES777 -- thanks for letting us know. @craigkerstiens owns the content on our website and we'll inform him of this issue.

**Comment by ozgune** [comment]
@KES777 -- I wanted to drop in a quick update. This seems to be an issue with that particular frame in our website and we couldn't find a quick fix. @craigkerstiens will look deeper into this in the next two weeks.

**Comment by jasonmp85** [comment]
Hey @craigkerstiens, it appears there's a `div` drawing atop this link (perhaps with a higher `z-index`?)…

The `div` has its height set to zero, but it contains an `ol` with a non-zero height. This is what's capturing clicks intended for the link.

The element matches `div.section-wrap.campaign-nav-holder`. Making a rule like `section-wrap.campaign-nav-holder { display: none; }` permist clicks to go through.

If that's too broad, you could also try adding `display:none;` directly in the style attribute of the `ol`, i.e. `<ol class="flex-control-nav flex-control-paging" style="display:none;"></ol>`.

**Comment by lfittl** [comment]
@jasonmp85 Thanks for debugging - put the fix in place!

(sidenote: I'll be very happy once we have a better content management system in place 🙈)
