### ISSUE TITLE
Metadata syncing may experience undetected distributed deadlock

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#4393]
We observed an undetected distributed deadlock that involved metadata syncing and pull-push execution. The metadata syncing was blocked waiting for a `COPY .. FROM .. WITH (format 'result')` command on the worker, which was likely blocked waiting for the metadata syncing on the coordinator. The deadlock held up even `SELECT 1`, which suggests we take an AccessShareLock on pg_dist_node somewhere in the planner.

The distributed deadlock went undetected because the distributed deadlock detector and metadata syncing are both done by the maintenance daemon, and it can only do one of them at a time right now.

A few work items:
- Reproduce the distributed deadlock and look for ways of avoiding it
- Move the metadata syncing to a separate process to avoid holding up distributed deadlock detection
- Consider replacing TRUNCATE by DELETE to clear pg_dist_node during metadata syncing without holding up common code paths 
- Do a separate transaction per worker node on the coordinator, to make progress even when some workers have issues

**Comment by pykello** [comment]
The following can reproduce the issue:

```sql

-- setup
SELECT start_metadata_sync_to_node('localhost', :worker_1_port);
SELECT start_metadata_sync_to_node('localhost', :worker_2_port);

CREATE TABLE deadlock_detection_test (user_id int UNIQUE, some_val int);
INSERT INTO deadlock_detection_test SELECT i, i FROM generate_series(1,7) i;
SELECT create_distributed_table('deadlock_detection_test', 'user_id');

CREATE TABLE t2(a int);
SELECT create_distributed_table('t2', 'a');

-- coordinator, s1
BEGIN;
UPDATE deadlock_detection_test SET some_val = 1 WHERE user_id = 1;

-- worker 2, s2
BEGIN;
UPDATE deadlock_detection_test SET some_val = 1 WHERE user_id = 2;
truncate t2; -- this will cause metadata sync to be blocked, since metadata sync tries to get AccessShareLock on all tables on all nodes
UPDATE deadlock_detection_test SET some_val = 1 WHERE user_id = 1;

-- coordinator, s1
UPDATE deadlock_detection_test SET some_val = 1 WHERE user_id = 2;

-- coordinator, s3
update pg_dist_node SET metadatasynced = false;
-- trigger metadata sync
```

In above, deadlock will happen between s1 and s2, but maintenanced is blocked on s2, so deadlock detection doesn't run and progress doesn't happen.

I'll try to add a test to reproduce the above situation & then I'll fix it by moving metadata sync to a separate worker.

**Comment by pykello** [comment]
The following isolation test reproduces the problem: https://github.com/citusdata/citus/compare/metadata_sync?expand=1#diff-4c4d00287f03aadc05135b7a312c9dc459ce850fb92555b4ebc3c0df9c933662R63

After the fix, instead of the timeout error, we should see a distributed deadlock error. I'll create a fix for this.
