### ISSUE TITLE
Add logging to our IRC channel

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#440]
(proposal from @lithp)

Someone's already made their own log to reference something which has happened there: https://gist.github.com/lfittl/d54dc3e9754b975c936e#file-gistfile1-txt-L61

We don't even have to set it up ourself, there are some bots which will log for us, such as: https://botbot.me/freenode/ipfs/

**Comment by lithp** [comment]
Quick update: I filed a request with botbot.me but they haven't responded. I'm looking into alternatives, we might have to host our own logs.

**Comment by sumedhpathak** [comment]
@lithp Any further news here? Are there any other easy options to do this?

**Comment by jasonmp85** [comment]
Anyone object to submitting our channel to [BotBot.me](https://botbot.me)? The UI is fantastic and it's free. I don't know what the qualifications for inclusion are, but we can find out (just submit our channel and ensure there's an op around to give permissions to the bot)?

**Comment by lithp** [comment]
I already submitted it. But it's been long enough with no response that
they probably dropped the email and it's worth pinging them again.

6 May 2016 Cum 00:06 tarihinde Jason Petersen <notifications@github.com>
şunu yazdı:

**Comment by samay-sharma** [comment]
I think that we're going to deprecate the IRC channel. If so, it might not be worth putting in this effort. @ozgune @sumedhpathak , could you chime in?

**Comment by metdos** [comment]
Just as a note, we may want to update the community support page if we deprecate IRC.
https://www.citusdata.com/community-support

**Comment by lithp** [comment]
On another note, just found this: https://github.com/chrisdone/ircbrowse which seems useful

**Comment by lfittl** [comment]
@ozgune Should we close this issue now that we've mostly moved onto Slack? (which has archives)

**Comment by ozgune** [comment]
@lfittl -- yup, I think this issue is now resolved.
