### ISSUE TITLE
Distributed deadlock when creating index on a partitioned table

### ISSUE THREAD

**Issue by pykello** [citusdata/citus#4412]
A customer was getting distributed deadlocks when trying to create on a partitioned table. The index was on `(partition_key, col_1, distribution_key)`. The partitions was created by pg_partman. I couldn't reproduce it locally when I created the exact same schema. The customer is on Azure Hyperscale and uses citus 9.3.5 and postgres 11.9.

Looking at server logs, it was a self deadlock with messages like:

`[DistributedTransactionId: (0, 77848, ...)] = [WaitsFor transaction numbers: 77848,77848,77848,77848,77848,77848,77848,77848,77848,77848,77848,77848,77848,77848,77848]`

We looked at `pg_stat_activity` and there were no concurrent query or transaction running that might have interfered with the create index.

**Comment by onderkalaci** [comment]
Could it be similar to this one https://github.com/citusdata/citus/issues/2714? It is fixed on 9.5, and the workaround on the earlier versions is to `set citus.multi_shard_modify_mode to 'sequential';`

**Comment by onderkalaci** [comment]
I'm closing this issue as it is already fixed in the recent versions, and we have a workaround mentioned above for the earlier versions
