### ISSUE TITLE
Support router executable subqueries and joins

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#448]
Our current planner has some restrictions on subqueries (no window functions, no  having clauses, limited grouping etc).  

Router planner/executor can support wider range of queries if they have certain properties.  Currently we do not consider any subquery as router executable. However we should be able to support subqueries if

- they are on a single hash distributed table (no joins)
- there is a filter on the deepest level of the query limiting this query to a single shard ``(partitionColumn = <some value>``
- no CTE
- no recursion
- no inner select statements in target list or where clauses

a sample query is on a users table hash partitioned on class_id. This query is currently not supported by current planner since it has a ```having``` clause, and no ```group by``` on the outer query.

```sql
select count(*) from (
    select
         group_id , count(*)
    from  
          users
    where
        class_id = 155344
    group by
         group_id
    having count(*) > 2) as inner
```

Another candidate query is

```sql
select 
    *
from (
    select 
        count(distinct(user_id)) as user_count,
        sum(game_points) as user_game_points,
        max(user_timestamp) as user_lastseen,
    from
        user_log
    where
        class_id = 124
    group by
        year) inner
  where
      user_game_points >  100
  order by
       user_game_points desc
  limit 
       5
```

We should be able to support this query  it reduces this query to a single shard.

However we will not be supporting queries if the innermost where clause looks like
```sql 
      where
           class_id = 124 or class_id = 130
```

even if both class id 124 and class id 130 is served from a single shard.

**Comment by mtuncer** [comment]
We can also support joins b/w tables and subqueries with router executor if they satisfy certain criteria

- query is targeted to single shard from each joined table
- if there is a subquery, filter clause is on the deepest level subquery
- subquery is on the from clause, no subqueries in where claus or in target list.
- the most important one : **shards belonging to joined tables are placed on the same worker**
- joins should be co-located joins, no broadcast joins or repartition joins

we should be able to router execute queries that are
- regular queries joining two or more tables
- queries that involve subquery joins
- queries that involve joins between subquery and table

Router planner check function might need to be changed considerably to avoid multiple shard prunings during routable check and plan creation.

We are going to need another task assignment method to assign router executable queries to workers that has all the required shards. This assignment policy is different than existing ones (first replica, greedy, round robin).  We would be loosing a bit on the high availability area. Requirement of having a worker including all joined shards would reduce available task placement options.


Some sample queries on lineitem and orders tables from tpch data would look like following.
```sql
select 
    o_orderkey, o_custkey, count(l_linenumber) 
from 
    lineitem, orders
where 
    l_orderkey = 100 and o_orderkey = 100 and l_orderkey = o_orderkey
group by 
    o_orderkey, o_custkey;
```

Notice the filter on both partition columns, and join on the partition column. 

subquery join example
```sql
select * 
from (
      select o_orderkey, o_custkey
      from orders
      where o_orderkey = 100) o,
      (select l_orderkey, l_partkey, l_shipmode
       from lineitem
       where  l_orderkey = 100) l
where o_orderkey = l_orderkey
order by 
    l_partkey;
```

**Comment by ozgune** [comment]
@mtuncer @sumedhpathak -- Since #501 provides a superset of the functionality mentioned in #448, can we resolve this issue as fixed?

**Comment by mtuncer** [comment]
correct, we can resolve this now.
