### ISSUE TITLE
Reads from reference tables trigger 2PC when in a transaction block

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#4510]
When we read from a (remote shard placement of a) reference table in a transaction block, we needlessly do a 2PC:
```sql
set citus.task_assignment_policy TO 'round-robin';
begin;
select * from ref;
commit;
NOTICE:  issuing PREPARE TRANSACTION 'citus_0_19173_11_0'
DETAIL:  on server marco@localhost:1201 connectionId: 1
NOTICE:  issuing COMMIT PREPARED 'citus_0_19173_11_0'
DETAIL:  on server marco@localhost:1201 connectionId: 1
```

Related to https://github.com/citusdata/citus/issues/3250, but probably a slightly different code path.

TaskListRequires2PC blindly checks whether the replication model is 2PC without considering whether the task actually performs a write.

**Comment by naisila** [comment]
Fixed by #4587
