### ISSUE TITLE
Does Citus replicaiton support load balancing of query requests

### ISSUE THREAD

**Issue by chinagui** [citusdata/citus#4515]
I have seen from the citus document that using citus replication can achieve high availability of worker nodes, and I have verified that it is effective. But I did not find out whether load balancing can be achieved. I verified that citus replcation does not seem to have the effect of load balancing. Is that right?

**Comment by marcocitus** [comment]
If you use `set citus.task_assignment_policy to 'round-robin'` the SELECTs would be load-balanced.

**Comment by chinagui** [comment]
OK, thank you.
