### ISSUE TITLE
Evaluate collecting optional and anonymous usage statistics

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#453]
Citus could automatically collect usage information and send it anonymously and securely. The data should only be sent with user's explicit consent.

The following could serve as guidelines when evaluating this feature:
- Anonymous: All usage data is collected and sent anonymously. None of the information submitted identifies the user personally.
- Usage data is kept confidential and is never sold to third parties.
- Usage data is submitted securely using the HTTPS protocol. (or another secure protocol)

**Comment by sumedhpathak** [comment]
@ozgune Should we mark this as non-6.0 release since we have some information now as part of package cloud?

**Comment by ozgune** [comment]
@sumedhpathak / @pykello -- Do we consider this issue closed now?
