### ISSUE TITLE
Columnar may crash with zero column tables 

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#4626]
Steps to repro:

```SQL
BEGIN;
create table local(y int);
insert into local values (1), (2);
alter table local drop column y;

CREATE TABLE local_columnar (like local) USING COLUMNAR;
ALTER TABLE local RENAME TO local_xxxxx;
INSERT INTO local_columnar SELECT * FROM local_xxxxx;
COMMIT;

server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 7.135 ms
 @:-!> 
```

One interesting observation is that removing `ALTER TABLE local RENAME TO local_xxxxx;` prevents the crash.

Also, note that `alter_table_set_access_method` does the same thing, so would be nice to test that a little further

**Comment by pykello** [comment]
In cstore_reader.c we assume that the table has at least 1 column. To avoid that assumption, we can either have a specialized code path for 0 columns, or refactor the read path.

Given that (1) the same bug existed in cstore_fdw for many years, (2) we anyway were going to refactor the read path in the next release, I'm inclined to not make the change for this release & keep it for the next release.
