### ISSUE TITLE
Make alter_distributed_table robust on colocation with reference tables

### ISSUE THREAD

**Issue by hanefi** [citusdata/citus#4637]
Partition keys are null for reference tables, and we usually check if they are null before accessing any members.

I suggest we test the behavior with reference tables more thoroughly and add assertions or extra checks around the lines below:
 https://github.com/citusdata/citus/blob/2be14cce2eeda2f42d799f0207cbcea3fe59ca1c/src/backend/distributed/commands/alter_table.c#L1266-L1270

Related: #4387 
Parent issue: #4636

**Comment by metdos** [comment]
Does #4661 fix this? Can we close this issue?
