### ISSUE TITLE
Improve query planning times for very high shard counts

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#465]
As we already implemented in #446  and [here](https://github.com/citusdata/citus/commit/70304eb2beb8103ef646e8aa341aeb5990d852f3), some additional features such as sorting the shard interval array and caching the shard interval compare function has a great impact on query planning times with very high shard counts.
Basically, as soon as #446 checked-in, let's check-in [this](https://github.com/citusdata/citus/commit/70304eb2beb8103ef646e8aa341aeb5990d852f3) as well.

**Comment by onderkalaci** [comment]
since #446 checked-in, @lithp it's your turn!

**Comment by lithp** [comment]
Your turn to review :)
