### ISSUE TITLE
 Distributed relations cannot have UNIQUE, EXCLUDE, or PRIMARY KEY constraints that do not include the partition column (with an equality operator if EXCLUDE).

### ISSUE THREAD

**Issue by kalrashubham49** [citusdata/citus#4656]
Whenever i am using select create_distributed_table , i am getting below error:

 Distributed relations cannot have UNIQUE, EXCLUDE, or PRIMARY KEY constraints that do not include the partition column (with an equality operator if EXCLUDE).

Not able to understand what it signifies, tried to figure it out from docs but no help as of now.

**Comment by onderkalaci** [comment]
It means that the table that you are trying to distribute has one of the mentioned constraints on a column that is different than the distribution column. An example:
```SQL
CREATE TABLE pkey_test (key int, value int PRIMARY KEY);
CREATE TABLE
Time: 15.487 ms
 SELECT create_distributed_table('pkey_test', 'key');
ERROR:  cannot create constraint on "pkey_test"
DETAIL:  Distributed relations cannot have UNIQUE, EXCLUDE, or PRIMARY KEY constraints that do not include the partition column (with an equality operator if EXCLUDE).
Time: 5.046 ms
```

To make it work, drop the PRIMARY KEY such as:
```SQL
ALTER TABLE pkey_test DROP CONSTRAINT pkey_test_pkey ;
ALTER TABLE
Time: 4.509 ms
SELECT create_distributed_table('pkey_test', 'key');
 create_distributed_table 
--------------------------
 
(1 row)

Time: 55.657 ms
```

These type of question can be answered much faster on our slack channel: https://slack.citusdata.com/

**Comment by gsmat** [comment]
Why doesn't Citus support this? because I have the same issue. And I really need unique columns,
