### ISSUE TITLE
Distributing a temporary table

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#4658]
Distributing a temporary table gives an error message that is related to how temp tables are stored in postgres. It could be more informative to users if we gave an error like "Temporary tables cannot be distributed".

[local] talha@talha:9700-31535=# select create_reference_table('a');
ERROR:  unacceptable schema name "pg_temp_3"
DETAIL:  The prefix "pg_" is reserved for system schemas.
CONTEXT:  while executing command on localhost:9701
Time: 18.671 ms
[local] talha@talha:9700-31535=#

**Comment by halilozanakgul** [comment]
SQLancer also hit this error
