### ISSUE TITLE
ERROR:  date/time field value out of range: "0000-00-00 00:00:00"

### ISSUE THREAD

**Issue by KES777** [citusdata/citus#466]
Trying to select from table field defined as:

```
ctime timestamp without time zone DEFAULT now()
```

and in mysql as

```
`ctime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
```

when the field value has '0000-00-00 00:00:00'

Feature request:
implement an option to do default conversion:

```
NULLIF(your_field_name,'0000-00-00 00:00:00')::timestamp
```

**Comment by sumedhpathak** [comment]
@KES777 Thanks for your error report. I'll try to reproduce it tomorrow and evaluate its priority.

**Comment by marcocitus** [comment]
Since `'0000-00-00 00:00:00'` is not a valid timestamp in PostgreSQL, this is not something we'll support.
