### ISSUE TITLE
Support IDENTITY columns with citus tables and table operations

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#4660]
We already [don't support](https://github.com/citusdata/citus/blob/3a403090fd2d4381321c0748dc702a28740e6e92/src/backend/distributed/commands/create_distributed_table.c#L835..L841) identity columns for distributed tables & reference tables.

With #4635 & #4633, we disallowed having such columns i) when adding local table to metadata and ii) when executing `alter_table.*`, `undistribute_table` udfs on such tables.

The main reason behind is that our deparser (i.e `GetPreLoadTableCreationCommands->pg_get_tableschemadef_string` codepath) doesn't know how to re-define such columns.

Opening this issue to track that missing piece.

**Comment by onurctirtir** [comment]
Seems that `pg_dump` utilizes a hidden syntax for that ? Might worth to have a look:
https://github.com/postgres/postgres/blob/master/src/bin/pg_dump/pg_dump.c#L17303..L17304

**Comment by onurctirtir** [comment]
Given https://github.com/citusdata/citus/pull/6591, should we close or update this @gokhangulbiz / @naisila ?

**Comment by naisila** [comment]
We can close this issue as completed, given that we now support the following with tables that have identity columns:
- `create_distributed_table()`
- `create_reference_table()`
- `citus_add_local_table_to_metadata()`
- `alter_distributed_table()`
- `undistribute_table()`
- `ALTER TABLE ... ADD COLUMN ... GENERATED {BY DEFAULT | ALWAYS} AS IDENTITY`
