### ISSUE TITLE
Fix equality operator check based on operator name

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#467]
We need to check if an operator is equality comparison at some places. We are doing it in a less preferred way: 1 - get the operator name, 2-string compare to check if it is  equal to ```EQUAL_OPERATOR_STRING``` ( "=").

There were 4 instances of it at the time of this writing.
```
multi_logical_optimizer.c:SupportedLateralQuery()
multi_logical_planner.c:IsJoinClause()
multi_physical_planner.c::HashableClauseMutator();
multi_router_planner.c:ColumnMatchExpressionAtTopLevelConjunction()
```

We need to migrate from name based comparison to strategy based comparison. In the end codebase should not have any reference to ```EQUAL_OPERATOR_STRING```. 

See ```multi_physical_planner.c:MakeOpExpression()``` for similar use of strategy.

**Comment by anarazel** [comment]
In your email you'd described that you tried using  equality_ops_are_compatible() - that's to see whether two comparison functions are compatible, not whether they're about equality.

What you basically have to do is to check what strategy the operator implements.  Something like
```
     /* search all opfamilies the operator is a member of */
     catlist = SearchSysCacheList1(AMOPOPID, ObjectIdGetDatum(opno));

     for (i = 0; i < catlist->n_members; i++)
     {
             HeapTuple       tuple = &catlist->members[i]->tuple;
             Form_pg_amop aform = (Form_pg_amop) GETSTRUCT(tuple);

             /* only btree am's determine equality */
             if (aform->amopmethod != BTREE_AM_OID)
             {
                     continue;
             }

             if (aform->amopstrategy == BTEqualStrategyNumber)
             {
                     /* represents equality in at least this opfamily */
                     return true;
             }
    }

    /* didn't find any family in which this operator represents equality */
    return false;
```
