### ISSUE TITLE
Workers might think they are the coordinator

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#4671]
When metadata is not synced, workers have a local group id of 0 hence they happily pass IsCoordinator, EnsureCoordinator checks even though they are not the coordinator.

This is a bit confusing in the code and would be nice to address.

One solution is to send the local group id with citus_add_node to the new worker but that might break assumptions on citus_add_node not opening any connection.

**Comment by marcocitus** [comment]
We set groupid as part of citus_add_node now
