### ISSUE TITLE
alter_distributed_table breaks colocation with procedures/functions

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#4708]
```SQL
set citus.replication_model TO streaming ;

CREATE TABLE test (a int);
SELECT create_distributed_table('test', 'a');

create or replace procedure proc(dist_key integer)
language plpgsql    
as $$
DECLARE
    res INT := 0;
begin
    INSERT INTO test VALUES (dist_key);
    SELECT count(*) INTO res FROM test;
    RAISE NOTICE 'Res: %', res;
    commit;
end;$$;
SELECT create_distributed_function('proc(integer)', 'dist_key', 'test' );



SELECT bool_and(hasmetadata) FROM pg_dist_node;


SET client_min_messages TO DEBUG1;
CALL proc(2);
DEBUG:  pushing down the procedure
NOTICE:  issuing CALL public.proc(2)
DETAIL:  on server pguser@10.192.0.4:5432 connectionId: 1

NOTICE:  Res: 2
DETAIL:  from 10.192.0.4:5432
CALL

-- CALL after alter_distributed_table cannot be pushed down
SELECT alter_distributed_table('test', shard_count:= 19);
CALL proc(2);
DEBUG:  stored procedure does not have co-located tables
...

```

**Comment by marcocitus** [comment]
Not entirely sure what the right behaviour should be. What's a bit unfortunate is that we don't remember the original table specified in the colocate_with when distributing the function; we only remember the colocation ID. 

It seems there are several scenarios:

1. Shard_count or colocate_with change
    a. Distributed table breaks away from co-location group
    b. Entire co-location group is altered
2. Distribution column change 
    a. Changes co-location ID because of new distribution column type
    b. Does not change co-location ID

I think 1b is the only scenario in which updating the co-location ID of functions is always desirable.
