### ISSUE TITLE
Alter distributed table add column bigserial/sequence fails

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#4721]
It seems that we cannot add a new column with a bigserial or a bigint that depends on a sequence even though we can use them at table creation. The workaround is to disable ddl propagation but we should fix this. 

```sql
CREATE SEQUENCE table_id_seq;
CREATE TABLE tbl (a int);
SELECT create_distributed_table('tbl','a');
 ALTER TABLE tbl ADD COLUMN _id BIGINT DEFAULT nextval('table_id_seq');
 ERROR:  relation "table_id_seq" does not exist
 CONTEXT:  while executing command on 10.0.98.206:5432
```

**Comment by SaitTalhaNisanci** [comment]
It seems that this also happens when we have an mx cluster and try to distribute a table with sequence.

```SQL
-- assuming the cluster is mx
create sequence seq;
create table a(a int default nextval('seq');
ERROR:  relation "public.seq" does not exist
CONTEXT:  while executing command on localhost:9701
```

Maybe a workaround could be to create the sequence manually on the workers but we need to fix this.

**Comment by onderkalaci** [comment]
also if you have this table, and distribute a function, right? (and then the metadata sync would fail?)

**Comment by onderkalaci** [comment]
```SQL
create sequence seq;
create table a(a int default nextval('seq'));
 select create_distributed_table('a','a');

select create_distributed_function('public.reload_pgbench(int)', '$1', colocate_with:='a');
 create_distributed_function 
-----------------------------
```

And, the logs would be:
```


2021-03-23 18:18:30.645 CET [87009] WARNING:  relation "public.seq" does not exist
2021-03-23 18:18:30.645 CET [87009] CONTEXT:  while executing command on localhost:9700
	Citus maintenance daemon for database 13720 user 10
2021-03-23 18:18:30.695 CET [87009] WARNING:  relation "public.seq" does not exist
2021-03-23 18:18:30.695 CET [87009] CONTEXT:  while executing command on localhost:9701
	Citus maintenance daemon for database 13720 user 10

2021-03-23 18:18:30.746 CET [87009] WARNING:  relation "public.seq" does not exist
2021-03-23 18:18:30.746 CET [87009] CONTEXT:  while executing command on localhost:9702
	Citus maintenance daemon for database 13720 user 10
```

And:
```SQL
 select nodeport, hasmetadata, metadatasynced from pg_dist_node;
 nodeport | hasmetadata | metadatasynced 
----------+-------------+----------------
     9700 | t           | f
     9701 | t           | f
     9702 | t           | f
(3 rows)

Time: 1.765 ms

```

which is pretty bad actually

**Comment by SaitTalhaNisanci** [comment]
yes metadata sync will fail, we saw this in a cluster with @halilozanakgul. So nothing will work after this "sync failure" happens because you will constantly get `out-of-sync` error. Like if you try to create or drop a table you will get this error, and at that point we don't have a nice solution:
- We either ask the customer to not have mx cluster
- We manually create the sequences on the workers (this would be a problem with new sequences)
...

**Comment by marcocitus** [comment]
To solve this, we need to propagate CREATE SEQUENCE statements to workers with metadata (ideally in the same way we do bigserial).

**Comment by onderkalaci** [comment]
> ideally in the same way we do bigserial

I think as a workaround, users can rely on bigserial instead of sequence at the moment?

**Comment by SaitTalhaNisanci** [comment]
>I think as a workaround, users can rely on bigserial instead of sequence at the moment?

bigserial will work but how will existing clusters switch to bigserial from an explicitly created sequence?

**Comment by onderkalaci** [comment]
> bigserial will work but how will existing clusters switch to bigserial from an explicitly created sequence?

Sequence is not working, so they just need to create tte table with bigserial?

**Comment by SaitTalhaNisanci** [comment]
Yes, but this becomes a problem when metadata sync starts. So before that they don't have any problem with an explicit sequence. So when the problem happens they already have a distributed table that is using the explicit sequence and at that point it isn't easy to switch to bigserial I think
