### ISSUE TITLE
pgaudit + citus doesn't work 

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#4726]
It seems that pgaudit extension doesn't work nicely with citus because we might call its hook from our function. 

An example of how this might cause a problem:

We have a call like `SELECT worker_apply_sequence_command('CREATE sequence a','bigint');`.

This will call pgaudit hook with a SELECT command at the beginning hence it will not give any error because pgaudit is okay with `SELECT` events even if their stack is not empty: https://github.com/pgaudit/pgaudit/commit/671dd2a628e3ea7bc56f662c9b07d574546f5aeb#diff-732f45c2566567903ce7d398b6a6a35131e40d9eb81dfa4f37a2201c630884e2R1373

Then in `worker_apply_sequence_command` we will call `CitusProcessUtility` with a Create statement: https://github.com/citusdata/citus/blob/1eec630640be0d13e53e955233c088ec23d516bd/src/backend/distributed/worker/worker_data_fetch_protocol.c#L464

This will again call the pgaudit hook, which now will give an error because:
- stack is not empty
- we passed `PROCESS_UTILITY_TOPLEVEL`
- the event is `CREATE`, hence it errors at: https://github.com/pgaudit/pgaudit/commit/671dd2a628e3ea7bc56f662c9b07d574546f5aeb#diff-732f45c2566567903ce7d398b6a6a35131e40d9eb81dfa4f37a2201c630884e2R1377

**Comment by marcocitus** [comment]
we should probably use PROCESS_UTILITY_QUERY

**Comment by SaitTalhaNisanci** [comment]
also we should check each usage of `PROCESS_UTILITY_TOPLEVEL` there are other usages that will lead to the same problem.

**Comment by metdos** [comment]
Removing cherry-pick-10.0 label because we should get the proper commit message from the fixup PR #4730
