### ISSUE TITLE
Rebalancer by_disk_size start-up is very slow with many partitions

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#4740]
I tried to rebalance a table with 1095 partitions and rebalance_table_shards took ~10 minutes before it started a shard move, which was surprising.

```sql
DROP TABLE IF EXISTS github_events;
DELETE FROM partman.part_config WHERE parent_table = 'public.github_events';

CREATE TABLE github_events (
    batch_hour timestamptz,
    event_id bigserial,
    data jsonb
)
PARTITION BY RANGE (batch_hour);


SELECT create_distributed_table('github_events', 'event_id');

CREATE TABLE template_github_events (LIKE github_events);

SELECT partman.create_parent(
  p_parent_table := 'public.github_events',
  p_control := 'batch_hour',
  p_type := 'native',
  p_interval := '1 day',
  p_start_partition := '2018-01-01',
  p_template_table := 'public.template_github_events'
);
DROP TABLE github_events_default;

-- add a node

select rebalance_table_shards(rebalance_strategy := 'by_disk_size', shard_transfer_mode := 'block_writes');
```

It also appeared to use an excessive amount of memory.

by_shard_count was almost instant

**Comment by marcocitus** [comment]
We should probably add a function to get the total size of a partitioned shard.

**Comment by agedemenli** [comment]
![image](https://user-images.githubusercontent.com/20187509/111832382-c485ae80-8901-11eb-868d-b6e53573b9df.png)

**Comment by agedemenli** [comment]
Refactored here: #4898
Introduced new functions here: #4899 

Will create a separate (3rd) PR for integrating these with the shard rebalancer functionality
