### ISSUE TITLE
'ONLY' clause prevents using inherited tables on worker nodes

### ISSUE THREAD

**Issue by a-bro** [citusdata/citus#475]
Distributed queries to worker nodes include the ONLY clause. This prevents using table inheritance on worker node tables.  Queries in the 5.0 release did not have this clause and worked as expected with inherited tables.  I suspect this is a side effect of pushdown support using the default postgres planner and the master node has no way of knowing that the worker table is inherited.  

The logic for inserting ONLY comes from the ruleutils_9*.c files afaik. As a quick hack to make this work I was able to edit this line:
https://github.com/citusdata/citus/blob/master/src/backend/distributed/utils/ruleutils_95.c#L405

So that "ONLY" is never used.  I assume ONLY has a performance benefit for queries on non inherited tables, but I don't know how impactful it is.

Seems like there are two options here to allow inherited worker tables to work.
1. Never include the ONLY clause in distributed queries
2. Add a flag to the metadata tables to indicate if the worker table has inheritance.

**Comment by mrjgreen** [comment]
Is this related to this issue, which is around sharding tables with inheritance? https://github.com/citusdata/citus/issues/183

**Comment by a-bro** [comment]
I think that #183 is a slightly different problem, it seems to be a problem with the table setup.  In my situation,  we create the distributed table using `master_create_distributed_table`  and then inherit the distributed table manually on the worker node.  All queries are expected to be made on the worker parent table and then passed through to specific child tables based on conditions.

**Comment by marcocitus** [comment]
This seems to be an issue with the new router planner/executor.

Real-time executor query:

    postgres=# SELECT * FROM customer WHERE customer_id = 'a' AND customer_id = 'a'; 
    ...
    DETAIL:  query string: "SELECT customer_id, name FROM customer_103738 customer WHERE ((customer_id = 'a'::text) AND (customer_id = 'a'::text))"

Router executable query:

    postgres=# SELECT * FROM customer WHERE customer_id = 'a'; 
    ...
    DEBUG:  distributed statement: SELECT customer_id, name FROM ONLY customer_103738 WHERE (customer_id = 'a'::text)
    DEBUG:  Plan is router executable

(set client_min_messages to DEBUG4 to show the queries sent to the workers)

**Comment by mtuncer** [comment]
it looks like it is specific to hash distributed tables where the worker query is created by router planner. 

worker queries for range distributed tables do not have ```ONLY``` in them.

**Comment by ozgune** [comment]
@mtuncer -- do we know how involved the fix for this issue is?

**Comment by mtuncer** [comment]
the easiest one is to set inherited flag (inh) to true just before creating the sql query.
fix is in ```multi_router_planner.c::RouterSelectTask()```. We need to get to the range table entry and the set the flag on it.  Afterwards ```deparse_shard_query()``` generated the query without 'ONLY' keyword.

**Comment by marcocitus** [comment]
Can we also do this for update/delete? Those also shouldn't use ONLY.
