### ISSUE TITLE
A small mistake

### ISSUE THREAD

**Issue by ybtsdst** [citusdata/citus#4762]
https://github.com/citusdata/citus/blob/9da9bd3dfd41d075b54ae0c76cb56176a18d8e24/src/backend/distributed/sql/citus--8.0-1.sql#L388

Maybe the nodeid column should use pg_dist_node_nodeid_seq?

**Comment by onderkalaci** [comment]
Good catch:) Though, this has been fixed on ~Citus 9.0: https://github.com/citusdata/citus/pull/3016/files

Closing the issue
