### ISSUE TITLE
ALTER TABLE ... ADD CONSTRAINT error

### ISSUE THREAD

**Issue by pykello** [citusdata/citus#4774]
We don't seem to generate correct worker query for ALTER TABLE ... ADD CONSTRAINT

```sql
drop table if exists visitors;

create table visitors (
        col1 text,
        col2 int
);

SELECT create_distributed_table('visitors', 'col1');

CREATE UNIQUE INDEX visitors_col2_col1_ky ON visitors(col2,col1);
ALTER TABLE visitors ADD CONSTRAINT visitors_constraint UNIQUE USING INDEX visitors_col2_col1_ky;

NOTICE:  ALTER TABLE / ADD CONSTRAINT USING INDEX will rename index "visitors_col2_col1_ky" to "visitors_constraint"
ERROR:  index "visitors_col2_col1_ky" does not belong to table "visitors_102137"
```

**Comment by onderkalaci** [comment]
non-dist tables gives the same error? Shouldn't it be `INSERT INTO visitors (col2, col1) VALUES (1, 'qqq')
ON CONFLICT ON CONSTRAINT visitors_constraint DO NOTHING `?

**Comment by pykello** [comment]
@onderkalaci you are right. I created the issue hastily. I updated the issue, we get the error earlier in ALTER TABLE ... ADD CONSTRAINT. We don't get the ERROR for non-dist tables.

**Comment by marcocitus** [comment]
Duplicate of #3232
