### ISSUE TITLE
ERROR:  cannot create constraint without a name on a distributed table

### ISSUE THREAD

**Issue by bkalpa9** [citusdata/citus#4776]
Unable to add primary key to citus distributed table :

```
ALTER TABLE test ADD PRIMARY KEY (id);
ERROR:  cannot create constraint without a name on a distributed table
```

**Comment by onderkalaci** [comment]
We should support this for Citus local tables as well. Some reference on this: https://github.com/citusdata/citus/pull/4273  (and make sure we don't need anything like this for constraints: https://github.com/citusdata/citus/pull/5291 )

**Comment by marcocitus** [comment]
The issue also applies to other types of constraints, e.g.:
```
alter table test add check (x>0);
ERROR:  cannot create constraint without a name on a distributed table
```

**Comment by onderkalaci** [comment]
> The issue also applies to other types of constraints, e.g.:

Reference to all types of constraints can be found here: https://www.postgresql.org/docs/current/ddl-constraints.html

**Comment by onurctirtir** [comment]
Taking a look into the similar work made for indexes might be helpful too: https://github.com/citusdata/citus/pull/4273

**Comment by naisila** [comment]
@emelsimsek is there another type of constraint that can be added without a name, that Citus doesn't support?
If not, let's close this issue! 🚀

**Comment by naisila** [comment]
Thanks to @emelsimsek , we now support adding constraints without a name directly on a table on Citus open source🥳 
- `ALTER TABLE ... ADD CHECK ...`
- `ALTER TABLE ... ADD UNIQUE ...`
- `ALTER TABLE ... ADD PRIMARY KEY ...`
- `ALTER TABLE ... ADD EXCLUDE ...`
- `ALTER TABLE ... ADD FOREIGN KEY ...`

There are no other types of nameless constraints that can be added directly to a table, so I'm closing this issue.
