### ISSUE TITLE
UNION ALL Pushdown doesn't work if there is an aggregate above 

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#4781]
Reported by @saicitus:
Below are steps to repro:
```SQL

CREATE TABLE test_a (id int, k int);
CREATE TABLE test_b (id int, k int);
 SELECT create_distributed_table('test_a','id');
SELECT create_distributed_table('test_b','id');

-- Different filters for sub-queries (Need workaround for this case)

CREATE OR REPLACE VIEW v AS SELECT * from test_a where k>1 UNION ALL SELECT * from test_b where k<1;
explain select count(*) from v; -- aggregate not pushed down to workers, recursive planning

CREATE OR REPLACE VIEW v AS (SELECT * from (SELECT * from test_a)a1 where k>1) UNION ALL SELECT * from (SELECT * from test_b)b1 where k<1;
explain select count(*) from v; -- aggregate not pushed down to workers, recursive planning

--Tried a couple of other cases as below and I was able to find workarounds but they are not what the customer has...

-- No filters for sub-queries:

CREATE OR REPLACE VIEW v AS SELECT * from test_a UNION ALL SELECT * from test_b; -- push down occurs
explain select count(*) from v; -- aggregate is pushed down to workers as per explain plan

-- Same filters for sub-queries:

CREATE OR REPLACE VIEW v AS SELECT * from test_a where k<1 UNION ALL SELECT * from test_b where k<1;
explain select count(*) from v; -- aggregate not pushed down to workers, recursive planning

-- Workaround for above
CREATE OR REPLACE VIEW v AS SELECT * from (SELECT * from test_a UNION ALL SELECT * from test_b)a where k<1;
explain select count(*) from v; -- aggregate is pushed down to workers as per explain plan

```

> -- Different filters for sub-queries (Need workaround for this case)

The problem is that Postgres pulls-up the subqueries and Citus' logic becomes broken. The workarounds is to prevent Postgres to pull-up the union subqueries, so that Citus can pushdown the query
There are two workarounds.

1) Use an ORDER BY for the leaves of the UNION ALL:
```SQL
CREATE OR REPLACE VIEW v AS
(SELECT * from test_a where k>1 ORDER BY 1)
UNION ALL 
(SELECT * from test_b where k<1 ORDER BY 1);

explain select count(*) from v ;
                                                   QUERY PLAN                                                    
-----------------------------------------------------------------------------------------------------------------

 Aggregate  (cost=250.00..250.02 rows=1 width=8)
   ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=100000 width=8)
         Task Count: 32
         Tasks Shown: One of 32
         ->  Task
               Node: host=localhost port=9700 dbname=postgres
               ->  Aggregate  (cost=178.58..178.59 rows=1 width=8)
                     ->  Append  (cost=74.23..174.82 rows=1506 width=0)
                           ->  Subquery Scan on "*SELECT* 1"  (cost=74.23..83.64 rows=753 width=0)
                                 ->  Sort  (cost=74.23..76.11 rows=753 width=8)
                                       Sort Key: test_a.id
                                       ->  Seq Scan on test_a_102042 test_a  (cost=0.00..38.25 rows=753 width=8)
                                             Filter: (k > 1)
                           ->  Subquery Scan on "*SELECT* 2"  (cost=74.23..83.64 rows=753 width=0)
                                 ->  Sort  (cost=74.23..76.11 rows=753 width=8)
                                       Sort Key: test_b.id
                                       ->  Seq Scan on test_b_102074 test_b  (cost=0.00..38.25 rows=753 width=8)
                                             Filter: (k < 1)
(18 rows)

Time: 5.743 ms
```

2) Add a subquery on top and use a volatile function in the SELECT part. But, Postgres is sometimes smart about eliminating un-used elements in the SELECT part, so make sure to use it in an expression with a real-column

```SQL

CREATE OR REPLACE VIEW v AS
SELECT *, id * random() FROM (
SELECT * from test_a where k>1
	UNION ALL 
SELECT * from test_b where k<1) as bar;

explain select count(*) from v ;
                                                   QUERY PLAN                                                    
-----------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=250.00..250.02 rows=1 width=8)
   ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=100000 width=8)
         Task Count: 32
         Tasks Shown: One of 32
         ->  Task
               Node: host=localhost port=9700 dbname=postgres
               ->  Aggregate  (cost=144.27..144.28 rows=1 width=8)
                     ->  Result  (cost=0.00..125.45 rows=1506 width=16)
                           ->  Append  (cost=0.00..99.09 rows=1506 width=4)
                                 ->  Subquery Scan on "*SELECT* 1"  (cost=0.00..45.78 rows=753 width=4)
                                       ->  Seq Scan on test_a_102042 test_a  (cost=0.00..38.25 rows=753 width=8)
                                             Filter: (k > 1)
                                 ->  Subquery Scan on "*SELECT* 2"  (cost=0.00..45.78 rows=753 width=4)
                                       ->  Seq Scan on test_b_102074 test_b  (cost=0.00..38.25 rows=753 width=8)
                                             Filter: (k < 1)
(15 rows)

Time: 6.868 ms
```

My initial investigation shows that the main reason is that we use `plannerinfoRoot->append_rel_list`, but the `append_rel_list` might be in `plannerInfoRoot->parent_root->append_rel_list`

**Comment by SaitTalhaNisanci** [comment]
The problem is that when postgres doesn't need the columns it can convert them to a `const` from a `var`. While checking if a specific column is a partition key, we rely on the entries to be a `VAR` and we don't consider `CONST`:

https://github.com/citusdata/citus/blob/a4944a21029fc73774f66b822f539075c899e2af/src/backend/distributed/planner/relation_restriction_equivalence.c#L1780-L1791

So as a workaround if we do `COUNT(partition_column)` instead of `COUNT(*)` all of these are pushed down as expected.

In the code, we should find a way for detecting if an optimized column belongs to a partition key so that we can push down even when that is `count(*)`.

**Comment by marcocitus** [comment]
Not sure whether it matters in this context, but worth noting that count(column) is semantically different from count(*) because the former does not count NULLs.

**Comment by SaitTalhaNisanci** [comment]
>Not sure whether it matters in this context, but worth noting that count(column) is semantically different from count(*) because the former does not count NULLs.

I guess we wouldn't be affected by this as we can't insert NULL entries to a partition column I guess right? (The workaround works only if you do count(partition_column))

**Comment by marcocitus** [comment]
Correct, though it would be good if we can avoid codifying that assumption, such that we can fix it later.

At a high level, why do we need the partition column in the output when doing a union all?

**Comment by SaitTalhaNisanci** [comment]
We don't need the partition column at the top level, but when we don't have it postgres optimizes it in the `targetList` as a `Const` from `Var`(in the subqueries), and Citus doesn't know how to handle `Const` while checking if a query is safe to pushdown.

**Comment by marcocitus** [comment]
We seem to require partition column in the target list:
https://github.com/citusdata/citus/blob/a4944a21029fc73774f66b822f539075c899e2af/src/backend/distributed/planner/relation_restriction_equivalence.c#L292 https://github.com/citusdata/citus/blob/a4944a21029fc73774f66b822f539075c899e2af/src/backend/distributed/planner/relation_restriction_equivalence.c#L303 

We can push down `select * from (select non_part_column, random() from test) a`, which does not have a partition column on the target list. I don't really get what's special about `union all` (except when the union all is in a join) or even `union`.

**Comment by onderkalaci** [comment]
I think when any join exists, we use dist keys in the target list for ensuring the colocation of all tables across leaf queries. That is probably required for that reason. Though, thinking about it, not sure if it is strictly required.

When no joins exist, for UNION, I think the main reason is that we do not run UNION on the coordinator, meaning that we can return duplicate values.
```SQL
select create_distributed_table('test', 'a');

SELECT b FROM (SELECT b  FROM test UNION  SELECT b  FROM test) as foo;
 b 
---
 1
 1
 1
 1
(4 rows)

Time: 62.528 ms
select undistribute_table('test');
SELECT b FROM (SELECT b  FROM test UNION  SELECT b  FROM test) as foo;
 b 
---
 1
(1 row)

Time: 2.348 ms

table test ;
 a | b 
---+---
 1 | 1
 4 | 1
 3 | 1
 2 | 1
(4 rows)

Time: 3.096 ms
```

For UNION ALL, I might need to think a little more to remember :)

**Comment by marcocitus** [comment]
Makes sense, UNION (without ALL) we cannot safely push down.

**Comment by onderkalaci** [comment]
> We don't need the partition column at the top level, but when we don't have it postgres optimizes it in the targetList as a Const from Var(in the subqueries), and Citus doesn't know how to handle Const while checking if a query is safe to pushdown.

@SaitTalhaNisanci  I think we should add regression tests with count(dist_key), and also check out other aggregates if possible such as avg(dist_key).

For example, how can we approach `avg(non-dist-key)`  is also a concern, but maybe for 10.2

**Comment by SaitTalhaNisanci** [comment]
@onderkalaci sure, I tried some other aggregates such as `avg` and all seem to be pushed down when we use a `dist_key`. I think it makes sense because when we use the `dist_key` it is not optimized so we are able to understand if it is safe to push down.
