### ISSUE TITLE
ERROR:  columnar_parallelscan_estimate not implemented

### ISSUE THREAD

**Issue by mewwts** [citusdata/citus#4787]
Hello! 

I'm trying to follow [this guide ](http://docs.citusdata.com/en/v10.0/use_cases/timeseries.html?highlight=alter_old_partitions_set_access_method#archiving-with-columnar-storage) after reading your citus 10 announcement. When running

`select alter_table_set_access_method('p0', 'columnar')` I get the following error `ERROR:  columnar_parallelscan_estimate not implemented`.

`p0` here is one of many partitions of a larger table in our system. The parent table has indexes defined.

I'd love to know how what's going on here, and how I can get past this! Thanks in advance.

**Comment by marcocitus** [comment]
Unfortunately, using columnar partitions when there are indexes on the parent table is currently unsupported. 

What you can do is drop the index from the parent, define a template table, e.g. `CREATE TABLE template (LIKE parent_table including all)`, and then pass `p_template_table := 'template'` to `partman.create_parent(..)`. The new partitions will then have the index, and they will be dropped when converting to columnar.

We should update the error message and this workaround to the docs.

**Comment by mewwts** [comment]
Thanks for your reponse @marcocitus, but I'm not sure I understand the process here.

Are you suggesting that I create a new parent table, and then detach the partitions from the old parent and attach to the new parent?

**Comment by mewwts** [comment]
I think i understand now.

You mean the template should have all indexes defined, but not the parent. Thank you.
