### ISSUE TITLE
ERROR: parameter "citus.max_shared_pool_size" cannot be changed now

### ISSUE THREAD

**Issue by bkalpa9** [citusdata/citus#4790]
Hi everyone,
I am trying to change  citus.max_shared_pool_size     from coordinator but getting the error:
```
ALTER DATABASE test SET citus.max_shared_pool_size = '100';
ERROR: parameter "citus.max_shared_pool_size" cannot be changed now
```
I checked  citus documents  for common error message  but nothing is there. 
Any help will be welcome.

**Comment by yjhjstz** [comment]
ALTER SYSTEM SET citus.max_shared_pool_size TO 5;
SELECT pg_reload_conf();

**Comment by onderkalaci** [comment]
> ALTER SYSTEM SET citus.max_shared_pool_size TO 100;
SELECT pg_reload_conf();

@bkalpa9 

Yes, this is correct. Though, the value 100 is typically too low. I just wanted check if you deliberately using this value. 

By default `citus.max_shared_pool_size` == `max_connections` on the coordinator node. And, by default Postgres has `max_connections` = `100`. Though, `100` is a very conservative value as Postgres aims to run on even not so powerful hardware without issues (hence low default values for many things). 

Depending on the specs of the cluster, it might make sense to increase this value. It is hard to give definitive answers to set it which values as it depends on your workload as well. But, you should be able to run quick benchmarks to see which value provides better perf for you. For example, to set it 300, follow the commands below

```
-- on all nodes (including coordinator)
ALTER SYSTEM SET max_connections TO 300;

-- on the coordinator reset citus.max_shared_pool_size
-- so that it always becomes to max_connections
ALTER SYSTEM RESET citus.max_shared_pool_size;

-- and restart all nodes (including coordinator)
-- as changing max_connection requires restart

```

**Comment by bkalpa9** [comment]
@onderkalaci 
Thanks, for your explanation, I am already aware of the relations between max_connections and citus.max_shared_pool_size,
I was trying to change in live server and got an error message. The actual value is quite higher, I am using [pgtune](https://pgtune.leopard.in.ua/#/) to tune the nodes postgres.
