### ISSUE TITLE
Improve error messages on failed unique indexes

### ISSUE THREAD

**Issue by will** [citusdata/citus#480]
Related to https://github.com/citusdata/citus/issues/221, when creating a unique index, if there is duplicate data in a shard, the only error reported back to the master is `PG::InternalError: ERROR:  could not execute DDL command on worker node shards`. This gives no indication to the root cause of `DETAIIL:  Key ... is duplicated.` which can only be found in the worker node's logs.

**Comment by ozgune** [comment]
This issue came up again in a customer conversation. I'm copy/pasting our notes from that conversation below (05/11/2016).

---

Dealing with Failures (Better error messaging).

For places where unique key violation constraints is violated, the error message is not propagated back to us. Ideally, we'd want to get a better error message which tells us that the unique constraint was violated.

Currently, it just says "cannot modify .....".

**Comment by metdos** [comment]
This also marks all involved shard placements as inactive.

Quick way to replicate;

```sql
CREATE TABLE temp(key int);
SELECT master_create_distributed_table('temp', 'key', 'hash');
SELECT master_create_worker_shards('temp', 8, 2);

INSERT INTO temp VALUES(10);
INSERT INTO temp VALUES(10);

CREATE UNIQUE INDEX temp_idx ON temp (key);

select * from pg_dist_shard_placement where shardstate = 3;
```

**Comment by jasonmp85** [comment]
#552 added mechanisms for detecting certain classes of errors and failing fast with an `ERROR` rather than a `WARNING`. It uses these mechanisms to fail fast for constraint violation errors; further errors can be added as needed.

If needed, we can throw in some DDL error categories here, though IMO we should make 2PC the dominant style for DDL propagation, which could obviate this whole business.

**Comment by sumedhpathak** [comment]
Jason, DDL propagation via 2PC is scheduled for 5.2, #513.

On Tue, Jun 7, 2016 at 12:45 PM, Jason Petersen <notifications@github.com>
wrote:

> #552 <https://github.com/citusdata/citus/pull/552> added mechanisms for
> detecting certain classes of errors and failing fast with an ERROR rather
> than a WARNING. It uses these mechanisms to fail fast for constraint
> violation errors; further errors can be added as needed.
>
> If needed, we can throw in some DDL error categories here, though IMO we
> should make 2PC the dominant style for DDL propagation, which could obviate
> this whole business.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/citusdata/citus/issues/480#issuecomment-224392292>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACeeC90K-eGWLcSC7LHizIo-IWcRKxqnks5qJcpHgaJpZM4ITQWN>
> .
>



-- 
*Sumedh Pathak*
Citus Data
650.422.9797
sumedh@citusdata.com

**Comment by sumedhpathak** [comment]
After discussion with @aamederen , PR #618 resolves the issue with the errors causing placements to be marked as inactive. However the PR currently doesn't actually improve the error message. Leaving this issue as open, but removing the 5.2 release tag as it won't be tackled in this cycle.

**Comment by ozgune** [comment]
I'm adding the 5.3 milestone assuming that improving the error message is a quick fix.

**Comment by mtuncer** [comment]
I am testing with current (Oct 13th) master branch
added a table ```t2```  hash distributed on field ```a```. Created some shards, added rows with the same value for distribution key.

Than tried to create a unique index on the distribution field, got the following.
```SQL
postgres=# create unique index t2b on t2(a);
NOTICE:  using one-phase commit for distributed DDL commands
HINT:  You can enable two-phase commit for extra safety with: SET citus.multi_shard_commit_protocol TO '2pc'
WARNING:  could not create unique index "t2b_102042"
DETAIL:  Key (a)=(1) is duplicated.
CONTEXT:  while executing command on localhost:9701
ERROR:  could not execute DDL command on worker node shards
```

Then switched to ```2pc``` protocol and tried to create the index again

```SQL
postgres=# SET citus.multi_shard_commit_protocol TO '2pc';
SET

postgres=# create unique index t2b on t2(a);
WARNING:  could not create unique index "t2b_102042"
DETAIL:  Key (a)=(1) is duplicated.
CONTEXT:  while executing command on localhost:9701
ERROR:  could not execute DDL command on worker node shards
postgres=# 
```

An error message stating unique index is not created at a particular shard, and accompanying error detail is also displayed.

**Comment by mtuncer** [comment]
@sumedhpathak I think we can resolve this issue. I don't see any more actionable item. Unless we want to display very specific constraint violation error.

**Comment by will** [comment]
Yes those errors seem a lot better to me. @ozgune asked me to close it if it looked good, so I am.
