### ISSUE TITLE
rebalance_table_shards reports error

### ISSUE THREAD

**Issue by jamexu98918** [citusdata/citus#4815]
my citus version is 10.0.1, I added some new worker nodes to existing coordinator, and run "SELECT rebalance_table_shards();"
I got error message

NOTICE:  Moving shard 102011 from citusworker4:5432 to citusworker5:5432 ...
ERROR:  epoll_ctl() failed: No such file or directory

no error message found in citusworker4 and citusworker5

**Comment by hanefi** [comment]
This is most probably related to missing entries on pg_hba.conf. A node should be able to connect to itself as well as other nodes in the Citus cluster.

```
local   all   all  trust
```

We also have a thread on our slack channel.
