### ISSUE TITLE
Regression test failure on master branch

### ISSUE THREAD

**Issue by athensofamerican** [citusdata/citus#483]
Checked out the latest master code. Built it and run regression tests with make check and saw one test failure (1 out of 73 tests): 

"test multi_explain           ...FAILED"

**Comment by marcocitus** [comment]
Thanks for reporting this, which PostgreSQL version are you building against?

**Comment by athensofamerican** [comment]
PostgreSQL 9.5

**Comment by marcocitus** [comment]
Which minor version? (postgres --version). Also, could you post the contents of src/test/regress/regression.diffs ?

**Comment by athensofamerican** [comment]
The exact PostgreSQL version is: 9.5.2

The content of the regression.diffs file:

*** /home/chuchen/citus/src/test/regress/expected/multi_explain.out	2016-05-02 10:36:27.020095223 -0400
--- /home/chuchen/citus/src/test/regress/results/multi_explain.out	2016-05-02 10:41:40.246060660 -0400
***************
*** 296,304 ****
    Tasks Shown: All
    ->  Task
          Node: host=localhost port=57637 dbname=regression
!         ->  Bitmap Heap Scan on lineitem_102009 lineitem  (cost=4.31..19.58 rows=5 width=18)
                Recheck Cond: (l_orderkey = 5)
!               ->  Bitmap Index Scan on lineitem_pkey_102009  (cost=0.00..4.31 rows=5 width=0)
                      Index Cond: (l_orderkey = 5)
  -- Test CREATE TABLE ... AS
  EXPLAIN CREATE TABLE explain_result AS
--- 296,304 ----
    Tasks Shown: All
    ->  Task
          Node: host=localhost port=57637 dbname=regression
!         ->  Bitmap Heap Scan on lineitem_102009 lineitem  (cost=4.35..28.89 rows=9 width=18)
                Recheck Cond: (l_orderkey = 5)
!               ->  Bitmap Index Scan on lineitem_pkey_102009  (cost=0.00..4.34 rows=9 width=0)
                      Index Cond: (l_orderkey = 5)
  -- Test CREATE TABLE ... AS
  EXPLAIN CREATE TABLE explain_result AS
***************
*** 309,315 ****
    Tasks Shown: One of 6
    ->  Task
          Node: host=localhost port=57637 dbname=regression
!         ->  Seq Scan on lineitem_102010 lineitem  (cost=0.00..58.80 rows=980 width=374)
  Master Query
    ->  Seq Scan on pg_merge_job_0048  (cost=0.00..0.00 rows=0 width=0)
  -- Test all tasks output
--- 309,315 ----
    Tasks Shown: One of 6
    ->  Task
          Node: host=localhost port=57637 dbname=regression
!         ->  Seq Scan on lineitem_102010 lineitem  (cost=0.00..66.64 rows=1764 width=197)
  Master Query
    ->  Seq Scan on pg_merge_job_0048  (cost=0.00..0.00 rows=0 width=0)
  -- Test all tasks output

======================================================================

**Comment by anarazel** [comment]
I guess e should run the queries with COSTS off - such minor cost
differences are very likely, given the sampling involved in building
stats.

**Comment by marcocitus** [comment]
Oops, it seems I missed the (COSTS FALSE) in the last 2 queries that were added to the tests. Will send out a fix.
