### ISSUE TITLE
Postgres Citus extension enable

### ISSUE THREAD

**Issue by micemuni** [citusdata/citus#4842]
Hi Team,
I have used  postgres:13.1-alpine in my dockerfile and trying to enable/install citus extension. but when i do docker build i got below error,. 
As per the citus deb.sh script, is citus install will work on only debian OS..?   

Error 

```
Step 7/10 : RUN curl https://install.citusdata.com/community/deb.sh > add-citus-repo.sh     && bash add-citus-repo.sh     && apk add postgresql-13-citus-10.0
 ---> Running in 12aa4dab2c67
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7577  100  7577    0     0  99697      0 --:--:-- --:--:-- --:--:-- 99697
Unfortunately, your operating system distribution and version are not supported by this script.

Please contact us via https://www.citusdata.com/about/contact_us with any issues.
The command '/bin/sh -c curl https://install.citusdata.com/community/deb.sh > add-citus-repo.sh     && bash add-citus-repo.sh     && apk add postgresql-13-citus-10.0' returned a non-zero code: 1
```

Please let me know if any solution / workaround for this. 

thanks in advance.

**Comment by onurctirtir** [comment]
>is citus install will work on only debian OS..?

Yes. deb.sh is for debian/ubuntu and rpm.sh is for centos/el/ol. So citus doesn't have alpine packages.

But good news is, citus already has an alpine based docker image ([citusdata/citus:alpine](https://hub.docker.com/layers/citusdata/citus/alpine/images/sha256-a3e6a7c18d7556654ee38413cbb5b7120fa21bea9046cea73afa843eda032b12?context=explore))

**Comment by micemuni** [comment]
Ok fine, but my requirement is that already i have running postgres:13.1-alpine as docker container and i have enable citus extension on this current container, I have custom dockerfile for postgres:13.1-alpine
My dockerfile is : - 

```
FROM postgres:13.1-alpine AS extension_builder

ARG PG_SQUEEZE_VERSION="REL1_3_1"
ENV PG_CONFIG="/usr/local/bin/pg_config"
RUN apk update && apk add musl-dev make gcc curl clang llvm
RUN curl -Ls https://github.com/cybertec-postgresql/pg_squeeze/archive/${PG_SQUEEZE_VERSION}.tar.gz | tar xvz
RUN cd pg_squeeze-${PG_SQUEEZE_VERSION} && make && make install

FROM postgres:13.1-alpine

COPY --from=extension_builder /usr/local/lib/postgresql/pg_squeeze* /usr/local/lib/postgresql/
COPY --from=extension_builder /usr/local/share/postgresql/extension/pg_squeeze* /usr/local/share/postgresql/extension/
```

So in this case, how do i enable Citus extension with this dockerfile..?  Please provide your inputs/fix.?

**Comment by onurctirtir** [comment]
Then I think you can follow our alpine dockerfile to install citus extension in your dockerfile.
(Mostly this part https://github.com/citusdata/docker/blob/master/alpine/Dockerfile#L12..L33)

Or, you can take citus:alpine as base docker file (i.e `FROM: `)

**Comment by micemuni** [comment]
@onurctirtir  Thanks for the inputs, it's building image,

**Comment by onurctirtir** [comment]
So closing the issue 👍
