### ISSUE TITLE
Support for fixed length BIT

### ISSUE THREAD

**Issue by Luxxii** [citusdata/citus#4843]
Hi everyone, 

currently i am trying to distribute two large tables across multiple shards via citus.  I would like to distribute them by the column with the datatype `BIT(n)` (specifically in my case: `BIT(452)`).  

---

Database Generation:

For this i first created the database on all database instances and registered the nodes via 
> SELECT * from master_add_node('<node_x>');

Executing `SELECT * FROM master_get_active_worker_nodes();` also returns me all the registered nodes. In my case `4` + one master node.

---

Tables have been added in the master node as follows:
```sql
CREATE TABLE  if not exists temp (   
    id BIT(452),   
    weight BIGINT NOT NULL,   
    des TEXT NOT NULL,  -- And some other columns
    PRIMARY KEY (id)
);

CREATE TABLE  if not exists ref_temp (   
    id BIGSERIAL,   
    temp_id BIT(452) NOT NULL,   
    des TEXT  NOT NULL,  -- And some other columns
    PRIMARY KEY (id)
);
```

Since i will use the `JOIN` operator with these two tables, it is reasonable to use the `temp.id` and `ref_temp.temp_id`  column to distribute the table, so that the nodes contain the needed entries for a `JOIN`.

So executing `create_distributed_table` should be sufficient. But i get error messages if i execute: 
```text
db=# SELECT create_distributed_table('temp', 'id');
ERROR:  data type bit has no default operator class for specified partition method
DETAIL:  Partition column types must have a default operator class defined.

db=# SELECT create_distributed_table('ref_temp', 'temp_id');
ERROR:  data type bit has no default operator class for specified partition method
DETAIL:  Partition column types must have a default operator class defined.
```

I am not sure whether the datatype `BIT` is supported by citus or if i have simply overlooked some steps before creating the tables. From the documentation it is also not clear to me which native datatypes from PostgreSQL are supported and which not. 

If the datatype is "not supported", which steps need to be done to get a datatype to work with `create_distributed_table` ?

**Comment by onderkalaci** [comment]
By default, Citus does sharding based on the hash values of distribution keys. `BIT(452)` doesn't have a hash function, so it cannot shard based on the `BIT(452)`.

But, on Postgres, you can define hash functions for any data types. For example, this GIST shows how to define hash functions on a composite key: https://gist.github.com/sumedhpathak/b8d4d46a656dbc58f364

You should be able to follow similar steps to create hash functions for `BIT(452)`

One simpler route could be to use `text` instead of `BIT(452)`, and cast it back to `BIT(452)` when you need to use bit specific operations.

**Comment by Luxxii** [comment]
I tried the steps mentioned in https://gist.github.com/sumedhpathak/b8d4d46a656dbc58f364 
 
 In detail, i executed the following on each instance:
 First the equal test for the type bit. I am a bit confused here, since it is only a wrapper for `bit = bit`.
 ```sql
CREATE FUNCTION equal_test_bit_function(bit(452), bit(452)) RETURNS boolean
AS 'select $1 = $2;'
LANGUAGE SQL
IMMUTABLE
RETURNS NULL ON NULL INPUT;
```

Then the operator: 
 ```sql
CREATE OPERATOR = (
    LEFTARG = bit(452),
    RIGHTARG = bit(452),
    PROCEDURE = equal_test_bit_function,
    HASHES
);
```

The function `bit_hash`:
 ```sql
CREATE FUNCTION bit_hash(bit(452)) RETURNS int
AS 'SELECT hashtext($1::text);'   
LANGUAGE SQL
IMMUTABLE
RETURNS NULL ON NULL INPUT;
```

and this statement:
 ```sql
CREATE OPERATOR CLASS new_op_fam_hash_class
DEFAULT FOR TYPE bit(452) USING HASH AS
OPERATOR 1 = (bit(452), bit(452)),
FUNCTION 1 bit_hash(bit(452));
 ```
 
 ---

 I could not execute: 
 ```sql
 CREATE OPERATOR CLASS new_op_fam_btree_class
DEFAULT FOR TYPE bit(452) USING BTREE AS
OPERATOR 3 = (bit(452), bit(452));
```

Due to the following error:
```text
ERROR:  could not make operator class "new_op_fam_btree_class" be default for type pg_catalog.bit
DETAIL:  Operator class "bit_ops" already is the default.
SQL state: 42710
```
which makes sense, since `bit` is already a primitve type. 


---
This did not help in my case. After those statements, i created the tables mentioned above and executed `create_distributed_table` which again gave me the same error: 
```
db=# SELECT create_distributed_table('temp', 'id');
ERROR:  data type bit has no default operator class for specified partition method
DETAIL:  Partition column types must have a default operator class defined.
```
 
 Yes, i could convert `bit(452)` into `text`, however, this is not a great solution imo, since i am using the `bit` column specifically to compress information in it as well as to generate it uniquely. I do this mainly for efficiency reasons and would like to keep it as this type.

**Comment by naisila** [comment]
We executed the commands you just showed in the coordinator, and although the definition of the operator class for btree access method fails, the distribution completes successfully. Could you maybe try again and see if it works?

Note: the distribution of `ref_temp` fails since the primary key doesn't include the partition column.

**Comment by Luxxii** [comment]
My apologies! I did not notice that i have created the functions on the wrong database and tried to partition the created tables on another one. Yes it is working. For the `ref_temp` table it is not a problem to additionally add it to the PKs.
