### ISSUE TITLE
Error building on OS X 10.11

### ISSUE THREAD

**Issue by theory** [citusdata/citus#491]
$ ./configure  
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for pg_config... /usr/local/pgsql/bin/pg_config
    configure: building against PostgreSQL 9.5
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc supports -Wall... yes
    checking whether gcc supports -Wextra... yes
    checking whether gcc supports -Wno-unused-parameter... yes
    checking whether gcc supports -Wno-sign-compare... yes
    checking whether gcc supports -Wno-missing-field-initializers... yes
    checking whether gcc supports -Wno-clobbered... no
    checking whether gcc supports -Wdeclaration-after-statement... yes
    checking whether gcc supports -Wendif-labels... yes
    checking whether gcc supports -Wmissing-format-attribute... yes
    checking whether gcc supports -Wmissing-declarations... yes
    checking whether gcc supports -Wmissing-prototypes... yes
    configure: creating ./config.status
    config.status: creating Makefile.global
    config.status: creating src/include/citus_config.h
    $ make
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -C src/backend/distributed/ all
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o shared_library_init.o shared_library_init.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o commands/create_distributed_table.o commands/create_distributed_table.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o commands/multi_copy.o commands/multi_copy.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o commands/transmit.o commands/transmit.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o executor/multi_client_executor.o executor/multi_client_executor.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o executor/multi_executor.o executor/multi_executor.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o executor/multi_real_time_executor.o executor/multi_real_time_executor.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o executor/multi_router_executor.o executor/multi_router_executor.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o executor/multi_server_executor.o executor/multi_server_executor.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o executor/multi_task_tracker_executor.o executor/multi_task_tracker_executor.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o executor/multi_utility.o executor/multi_utility.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o master/master_create_shards.o master/master_create_shards.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o master/master_delete_protocol.o master/master_delete_protocol.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o master/master_metadata_utility.o master/master_metadata_utility.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o master/master_node_protocol.o master/master_node_protocol.c
    master/master_node_protocol.c:665:19: warning: implicit declaration of function
          'pg_get_constraintdef_command' is invalid in C99 [-Wimplicit-function-declaration]
                            statementDef = pg_get_constraintdef_command(constraintId);
                                           ^
    master/master_node_protocol.c:665:17: warning: incompatible integer to pointer conversion
          assigning to 'char *' from 'int' [-Wint-conversion]
                            statementDef = pg_get_constraintdef_command(constraintId);
                                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o master/master_repair_shards.o master/master_repair_shards.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o master/master_stage_protocol.o master/master_stage_protocol.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o master/worker_node_manager.o master/worker_node_manager.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o planner/multi_explain.o planner/multi_explain.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o planner/multi_join_order.o planner/multi_join_order.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o planner/multi_logical_optimizer.o planner/multi_logical_optimizer.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o planner/multi_logical_planner.o planner/multi_logical_planner.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o planner/multi_master_planner.o planner/multi_master_planner.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o planner/multi_physical_planner.o planner/multi_physical_planner.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o planner/multi_planner.o planner/multi_planner.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o planner/multi_router_planner.o planner/multi_router_planner.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o relay/relay_event_utility.o relay/relay_event_utility.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o test/connection_cache.o test/connection_cache.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o test/create_shards.o test/create_shards.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o test/distribution_metadata.o test/distribution_metadata.c
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/Users/david/dev/pgxn/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include -I/usr/local/pgsql/include  -c -o test/fake_fdw.o test/fake_fdw.c
    test/fake_fdw.c:68:29: warning: incompatible pointer types assigning to
          'GetForeignPlan_function' (aka 'struct ForeignScan *(*)(struct PlannerInfo *, struct
          RelOptInfo *, unsigned int, struct ForeignPath *, struct List *, struct List *)') from
          'ForeignScan *(PlannerInfo *, RelOptInfo *, Oid, ForeignPath *, List *, List *, Plan
          *)' (aka 'struct ForeignScan *(struct PlannerInfo *, struct RelOptInfo *, unsigned
          int, struct ForeignPath *, struct List *, struct List *, struct Plan *)')
          [-Wincompatible-pointer-types]
            fdwroutine->GetForeignPlan = FakeGetForeignPlan;
                                       ^ ~~~~~~~~~~~~~~~~~~
    test/fake_fdw.c:105:29: error: too many arguments to function call, expected 8, have 9
      ...NULL, NULL, NIL));
                     ^~~
    /usr/local/pgsql/include/server/nodes/pg_list.h:69:18: note: expanded from macro 'NIL'
    #define NIL                                             ((List *) NULL)
                                                            ^~~~~~~~~~~~~~~
    /usr/local/pgsql/include/server/optimizer/pathnode.h:82:1: note: 'create_foreignscan_path'
          declared here
    extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
    ^
    test/fake_fdw.c:132:8: error: too many arguments to function call, expected 7, have 8
                                                            outer_plan);
                                                            ^~~~~~~~~~
    /usr/local/pgsql/include/server/optimizer/planmain.h:46:1: note: 'make_foreignscan' declared
          here
    extern ForeignScan *make_foreignscan(List *qptlist, List *qpqual,
    ^
    1 warning and 2 errors generated.
    make[1]: *** [test/fake_fdw.o] Error 1
    make: *** [extension] Error 2

Compiler:

    $ cc --version
    Apple LLVM version 7.3.0 (clang-703.0.29)
    Target: x86_64-apple-darwin15.4.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by theory** [comment]
This diff gets everything to compile, though I've no idea if it's correct.

    diff --git a/src/backend/distributed/test/fake_fdw.c b/src/backend/distributed/test/fake_fdw.c
    index 5a821bd..b877b5a 100644
    --- a/src/backend/distributed/test/fake_fdw.c
    +++ b/src/backend/distributed/test/fake_fdw.c
    @@ -102,7 +102,7 @@ FakeGetForeignPaths(PlannerInfo *root, RelOptInfo *baserel, Oid foreigntableid)
     #else
     	add_path(baserel, (Path *) create_foreignscan_path(root, baserel, baserel->rows,
     													   startup_cost, total_cost, NIL,
    -													   NULL, NULL, NIL));
    +													   NULL, NULL));
     #endif
     }
 
    @@ -128,7 +128,7 @@ FakeGetForeignPlan(PlannerInfo * root, RelOptInfo * baserel, Oid foreigntableid,
     #if (PG_VERSION_NUM >= 90300 && PG_VERSION_NUM < 90500)
     	return make_foreignscan(tlist, scan_clauses, scan_relid, NIL, NIL);
     #else
    -	return make_foreignscan(tlist, scan_clauses, scan_relid, NIL, NIL, NIL, NIL,
    +	return make_foreignscan(tlist, scan_clauses, scan_relid, NIL, NIL, NIL,
     							outer_plan);
     #endif
     }

**Comment by ozgune** [comment]
Hey David, thanks for reporting this! We're looking to reproduce the issue and will post an update in the next 1-2 days.

**Comment by anarazel** [comment]
Hi David,

On 2016-05-04 16:08:46 -0700, David E. Wheeler wrote:
>     $ ./configure  
>     checking for a sed that does not truncate output... /usr/bin/sed
>     checking for pg_config... /usr/local/pgsql/bin/pg_config
>     configure: building against PostgreSQL 9.5

Any chance that the postgres installation in that path is a beta release
of 9.5? The signature of create_foreignscan_path et al. changed pretty shortly
before the 9.5 release.

>     test/fake_fdw.c:68:29: warning: incompatible pointer types assigning to
>           'GetForeignPlan_function' (aka 'struct ForeignScan *(*)(struct PlannerInfo *, struct
>           RelOptInfo *, unsigned int, struct ForeignPath *, struct List *, struct List *)y') from
>           'ForeignScan *(PlannerInfo *, RelOptInfo *, Oid, ForeignPath *, List *, List *, Plan
>           *)' (aka 'struct ForeignScan *(struct PlannerInfo *, struct RelOptInfo *, unsigned
>           int, struct ForeignPath *, struct List *, struct List *, struct Plan *)')
>           [-Wincompatible-pointer-types]
>             fdwroutine->GetForeignPlan = FakeGetForeignPlan;
>                                        ^ ~~~~~~~~~~~~~~~~~~


Andres

**Comment by theory** [comment]
Oh, yeah it is, 9.5beta2. I didn't realize that I hadn't upgraded. Will do and get back to you.

**Comment by theory** [comment]
Bah, confirmed it all works on 9.5.2. Sorry for the noise.

**Comment by theory** [comment]
I got some test failures, though: 

    test multi_explain            ... FAILED

     multi_hash_pruning       ... FAILED

You care to see the full report?
