### ISSUE TITLE
Shardstate in citus_shards

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#4912]
When we have multiple shard placements with different shard states, we shard placement is in healthy state etc so we might consider adding shardstate to citus_shards view.

An example:

![image](https://user-images.githubusercontent.com/17179875/115050147-1eb76680-9ee4-11eb-8c5d-6821ad8a6c64.png)

**Comment by marcocitus** [comment]
I think should change citus_shards to only show shardstate 1.
