### ISSUE TITLE
Wrong storage type for table.

### ISSUE THREAD

**Issue by KES777** [citusdata/citus#496]
According to the [answer](http://stackoverflow.com/a/36898566/4632019)
>We do automatically create shards with storage-type 'f', when you issue master_create_distributed_table.

But 
```
CREATE FOREIGN TABLE "files2" (
  "id" character varying(16) DEFAULT '' NOT NULL,
  "site_id" bigint DEFAULT 0 NOT NULL
) 
SERVER mysql_svr
   OPTIONS (dbname 'test', table_name 'files2');

SELECT master_create_distributed_table( 'files2', 'site_id', 'range');
select master_create_empty_shard( 'files2' );
select * from pg_dist_shard;
 logicalrelid | shardid | shardstorage | shardalias | shardminvalue |    shardmaxvalue    
--------------+---------+--------------+------------+---------------+---------------------
        36465 |  102019 | t            |            |               | 
\d+ files2;
 Foreign table "public.files2"
.....
Server: mysql_svr
FDW Options: (dbname 'test', table_name 'files2')
```
On the worker:
```
\d+ files2_102019 ;
Foreign table "public.files2_102019"
....
Server: mysql_svr_102019
FDW Options: (dbname 'test', table_name 'files2')
```

As you can see the `shardstorage` is 't' but should be 'f' if I understand the stackoverflow [answer](http://stackoverflow.com/a/36898566/4632019) and [this doc](https://www.citusdata.com/docs/citus/5.0/reference/metadata_tables.html#shard-storage-types) right.

**Comment by marcocitus** [comment]
Thanks for reporting this, it appears that master_create_empty_shard doesn't set the correct storage type for foreign tables. For the moment, a workaround is to manually update the storage type to 'f'.
