### ISSUE TITLE
CREATE INDEX self-deadlocks when partition names are long in a metadata synced enviorment

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#4979]
Similar to #4962, when an index is created on a parent table, the indexes auto-cascades into partitions. Citus is smart enough to calculate the length of the indexes on the partitions, and switches to sequential execution.

However, when metadata is synced, the `sequential` execution is broken, because Citus sends some commands over separate connections which are not part of the executor's pool size.

When we send the commands which run on the shell table on the workers, we use a separate connection with a superuser (e.g., `SendCommandToWorkersWithMetadata ` uses superuser):
https://github.com/citusdata/citus/blob/33c620f232e8c1cc96adbf43f8a04dfd20714013/src/backend/distributed/commands/utility_hook.c#L865-L885

It means that, when the partition names are long, both the shell table and the shards would try to assign the same auto-generated index name by Postgres **over different connections**. Hence, leading to a self deadlocks. 

Steps to repro:
```SQL
CREATE USER citus WITH LOGIN;
GRANT ALL ON SCHEMA public TO citus; 

psql -U citus postgres

-- make sure that metatadata sync is possible
set citus.replication_model TO streaming ;

CREATE TABLE partitioned_table (long_column_names_1 int, long_column_names_2 int, long_column_names_3 int, long_column_names_4 int, long_column_names_5 int, long_column_names_6 int, long_column_names_7 int, long_column_names_8 int, long_column_names_9 int, long_column_names_10 int, long_column_names_11 timestamp) PARTITION BY RANGE (long_column_names_11);
CREATE TABLE very_long_child_partition_name_is_required_to_repro_the_bug PARTITION OF partitioned_table FOR VALUES FROM ('2011-01-01') TO ('2012-01-01');

SELECT create_distributed_table('partitioned_table', 'long_column_names_1');

create or replace procedure proc(dist_key integer)
language plpgsql    
as $$
DECLARE
    res INT := 0;
begin
    INSERT INTO partitioned_table  (long_column_names_1, long_column_names_11) VALUES(1, '2011-05-01');
    SELECT count(*) INTO res FROM partitioned_table;
    RAISE NOTICE 'Res: %', res;
    commit;
end;$$;
SELECT create_distributed_function('proc(integer)', 'dist_key', 'test' );
-- make sure that metadata is synced, it may take few seconds
SELECT bool_and(hasmetadata) FROM pg_dist_node;


CREATE INDEX long_index_on_parent_table ON partitioned_table (long_column_names_1, long_column_names_2, long_column_names_3, long_column_names_4, long_column_names_5, long_column_names_6, long_column_names_11) INCLUDE (long_column_names_7, long_column_names_7, long_column_names_9, long_column_names_10);

ERROR:  canceling the transaction since it was involved in a distributed deadlock
```

**Comment by marcocitus** [comment]
It's probably time to implement https://github.com/citusdata/citus/issues/3398

**Comment by onderkalaci** [comment]
The changes in #5105 is not applicable for backport, so I have to remove the backport tag. The users who experience the issue would have to upgrade to higher versions
