### ISSUE TITLE
Decide on deferred shard naming

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#4988]
We don't have a consistent naming to call "left-over" shards. We currently use old/deferred/marked and more terms for this. We should decide on a single name and use it everywhere, especially in the errors.

**Comment by SaitTalhaNisanci** [comment]
Nils suggested "deprecated" shards.

**Comment by JelteF** [comment]
Orphaned shards is another option

**Comment by JelteF** [comment]
I used orphaned in this PR: https://github.com/citusdata/citus/pull/5024

**Comment by marcocitus** [comment]
orphaned is now somewhat commonplace
