### ISSUE TITLE
Add support for Postgres 14

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#4991]
As PG 14 is on the horizon, we should make Citus work with PG 14. 

As a development strategy, I think we should follow a similar approach to PG 13 integration, where any change is documented with a separate commit and the commit has a reference to the related change in PG: https://github.com/citusdata/citus/pull/3900/commits

So that the review becomes much easier

**Comment by devrimgunduz-edb** [comment]
Thanks, I did not have to create a ticket :)

**Comment by SaitTalhaNisanci** [comment]
@onderkalaci I wanted to write the high level steps for how pg13 support was added:
1-> Enable postgres 14 in configure
2-> Copy ruleutils13 as ruleutils14 and apply the relevant changes from postgres14 on top of ruleutils14, (note that this diverges from the postgres ruleutils, see https://github.com/citusdata/citus/issues/3855
3-> Compile citus with postgres 14, to solve the compilation issues:
- For each issue, find the relevant commit on postgres side
- Update the citus code to address the changes on postgres side(put the postgres commit message to citus commit for easier review, future reference). Also we should try to use `version_compat.h` as much as possible instead of inlining `PG_VERSION_NUM` macros inside the code.
4-> After Citus compiles with postgres 14, run the tests and for each failing test:
- Find the commit that causes the failure on postgres side
- Fix the citus code to address the change on postgres side (put the postgres commit message to citus commit)
5-> After all tests pass, for each postgres 14 changelog:
- Check if it works with Citus, if so add a test to `pg14.sql`
- If it doesn't work, add relevant error messages to Citus code and create issues on Github so that we can support it later. And add a test for the error message in `pg14.sql`.
- Have a separate commit for each changelog entry that we address with Citus
6-> Add postgres 14 test images to our CI

**Comment by onderkalaci** [comment]
Some issues I hit while testing #5209


- [ ] Creating multi-column extended statistics crashes
```SQL
CREATE TABLE t1 (c1 int, c2 int);
SELECT create_distributed_table('t1', 'c1');

 CREATE STATISTICS extstat1_data1 ON MOD(c1, 10),
MOD(c2, 10) FROM t1 ;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 5.304 ms
```


- [ ] pg_stat_progress_copy doesn't show tuples_processed when COPY TO dist/ref table
pg_stat_progress_copy doesn't much when COPY FROM dist/ref table


- [ ]  We do not propagate compressed columns to the shards
```SQL
CREATE TABLE compress1(c1 TEXT COMPRESSION pglz, c2 TEXT COMPRESSION pglz) ;
SELECT create_distributed_table('compress1', 'c1');

 \d+ compress1
                                       Table "public.compress1"
 Column | Type | Collation | Nullable | Default | Storage  | Compression | Stats target | Description 
--------+------+-----------+----------+---------+----------+-------------+--------------+-------------
 c1     | text |           |          |         | extended | pglz        |              | 
 c2     | text |           |          |         | extended | pglz        |              | 
Access method: heap

-- connect to worker -- check shard
 \d+ compress1_102113
                                   Table "public.compress1_102113"
 Column | Type | Collation | Nullable | Default | Storage  | Compression | Stats target | Description 
--------+------+-----------+----------+---------+----------+-------------+--------------+-------------
 c1     | text |           |          |         | extended |             |              | 
 c2     | text |           |          |         | extended |             |              | 
Access method: heap
```


- [ ] We do not propagate ALTER COLUMN .. SET COMPRESSION
```SQL
ALTER TABLE compress1 ALTER COLUMN c2 SET COMPRESSION pglz ;
ERROR:  alter table command is currently unsupported
```


- [ ] Citus doesn't support creating bloom filters after create_distributed_table

```SQL
CREATE TABLE t3 (key int, c1 numeric);

CREATE INDEX idx1_data1 ON t3 USING brin 
(c1 numeric_bloom_ops (false_positive_rate = 0.05,
n_distinct_per_range = 100)) ;

select create_distributed_table('t3', 'key');

-- fails
CREATE INDEX idx1_data2 ON t3 USING brin 
(c1 numeric_bloom_ops (false_positive_rate = 0.05,
n_distinct_per_range = 100)) ;
ERROR:  citus currently doesn't support operator class parameters in indexes
Time: 1.177 ms
```



- [ ] DETACH CONCURRENTLY weirdly errors out

```SQL
CREATE TABLE users_table_part(user_id bigint, value_1 int, value_2 int) PARTITION BY RANGE (value_1);
CREATE TABLE users_table_part_0 PARTITION OF users_table_part FOR VALUES FROM (0) TO (1);
CREATE TABLE users_table_part_1 PARTITION OF users_table_part FOR VALUES FROM (1) TO (2);
SELECT create_distributed_table('users_table_part', 'user_id');

alter table users_table_part detach partition users_table_part_0 concurrently; 
ERROR:  ALTER TABLE ... DETACH CONCURRENTLY cannot run inside a transaction block
CONTEXT:  while executing command on localhost:9702
Time: 10.850 ms
```


- [ ] CURRENT_ROLE can be used instead of CURRENT_USER fails weirdly
```SQL
GRANT CREATE ON SCHEMA sc1 TO CURRENT_ROLE;
ERROR:  unexpected role type 1
```



- [ ]  REINDEX on partitioned tables fail 
```SQL
CREATE TABLE part1(c1 NUMERIC, c2 VARCHAR(10)) PARTITION BY RANGE (c1);

SELECT create_distributed_table('part1', 'c1');

CREATE TABLE part1v1 PARTITION OF part1 FOR VALUES FROM (0) TO (100000) ;
CREATE TABLE part1v2 PARTITION OF part1 FOR VALUES FROM (100000) TO (200000) ;

CREATE INDEX idx1_part1 ON part1(c1) ;
REINDEX TABLE part1 ;

ERROR:  REINDEX TABLE cannot run inside a transaction block
CONTEXT:  while reindexing partitioned table "public.part1_102942"
while executing command on localhost:9701
Time: 12.581 ms
```

- [ ] Recursive CTE deparse problem
```SQL
 CREATE TABLE graph0(f INT, t INT, label TEXT); 
SELECT create_distributed_table('graph0', 'f');

INSERT INTO graph0 VALUES (1, 2, 'arc 1 -> 2'),
 (1, 3, 'arc 1 -> 3'), (2, 3, 'arc 2 -> 3'),
 (1, 4, 'arc 1 -> 4'), (4, 5, 'arc 4 -> 5') ;

 WITH RECURSIVE search_graph(f, t, label) AS (
SELECT * FROM graph0 g WHERE f = 1
UNION ALL
SELECT g.* FROM graph0 g, search_graph sg WHERE 
g.f = sg.t and  g.f = 1
) SEARCH DEPTH FIRST BY f, t SET seq
SELECT * FROM search_graph ORDER BY seq ;

ERROR:  column reference "seq" is ambiguous
CONTEXT:  while executing command on localhost:9701

WITH RECURSIVE search_graph(f, t, label) AS (
SELECT * FROM graph0 g WHERE f = 1
UNION ALL
SELECT g.* FROM graph0 g, search_graph sg WHERE g.f = sg.t and g.f = 1
) SEARCH BREADTH FIRST BY f, t SET seq
SELECT * FROM search_graph ORDER BY seq ;
ERROR:  column reference "seq" is ambiguous
CONTEXT:  while executing command on localhost:9701
Time: 19.813 ms
```

- [ ]  Add several regression tests (incomplete list)

    - [ ]  join alias 
```SQL
CREATE TABLE data1(c1 int, c2 int);
CREATE TABLE data2(c1 int, c2 int);
SELECT create_distributed_table('data1', 'c1');
SELECT create_distributed_table('data2', 'c1');

SELECT d1.c1, x.c1, x.c2 FROM data1 d1 JOIN data2 d2 
USING (c1, c2) AS x ;

-- router DISTINCT rollup
select c1, c2
FROM
data2
WHERE c1=1
group by distinct rollup(c1, c2), rollup(c1, c3);
```

> logical decoding of two-phase commit (2PC)

**Comment by hanefi** [comment]
I am going through the differences in PG14 grammar, and this is a comment is a WIP. I want us to go through this exhaustive list and make sure we are ok with all the changes. 

Please do not update the checklist, as I will constantly add some more items to the list, and I do not want to overwrite any of your changes.

# New nodes
- [ ] Stmt nodes
  - [ ] ReturnStmt
  - [ ] TransactionStmtLegacy
- [ ] Others
  - [ ] PLpgSQL_Expr
  - [ ] PLAssignStmt

# Removed Stmt s
- [ ] AlterForeignTableStmt ( They are now a kind of AlterTableStmt )
- [ ] DropPLangStmt

# New fields
- [ ] PartitionCmd -> concurrent
- [ ] ColumnDef -> compression

# Renames
- [ ] field rename relkind -> objtype
	- [ ] AlterTableStmt
	- [ ] AlterCompositeTypeStmt
	- [ ] CreateAsStmt
	- [ ] CreateMatViewStmt
- [ ] variable rename vac_analyze_* -> utility_*
	- [ ] str vac_analyze_option_name
	- [ ] defelt vac_analyze_option_elem
	- [ ] list vac_analyze_option_list
	- [ ] node vac_analyze_option_arg

# New operators to existing Stmt s
- [ ] ALTER TABLE <name> DETACH PARTITION <partition_name> **[CONCURRENTLY]**
- [ ] ALTER TABLE <name> DETACH PARTITION <partition_name> **FINALIZE**
- [ ] ALTER TABLE <name> ALTER [COLUMN] <colname> **SET COMPRESSION <cm>**
- [ ] CREATE_TABLE_LIKE_COMPRESSION ?
- [ ] CREATE STATISTICS .. ON expr_list .. -> CREATE STATISTICS .. ON stats_params .. (they can either be simple column references or arbitrary expressions in parens now)

**Comment by ozgune** [comment]
Hi @onderkalaci , @hanefi - Did we complete this work? If so, should we close this issue?
