### ISSUE TITLE
Ensure no data loss when truncating local data on single node Citus

### ISSUE THREAD

**Issue by hanefi** [citusdata/citus#4998]
We ran some tests in single node Citus and some tests for `truncate_local_data_after_distributing_table` failed. I failed to reproduce this one yet.

However some of my tests introduced in https://github.com/citusdata/citus/pull/3752/files#diff-92ea87f6322375d0dd82e14cd7d404cfe1e6ab3b1362cc5cd9f01cdd33954a34R505 are not really intact, and the comments contradict with the behavior.

I plan to revisit and improve the tests that were introduced in #3752

Below are the results we got from single node citus regression tests:
```diff
 HINT:  To remove the local data, run: SELECT truncate_local_data_after_distributing_table($$multi_truncate.ref$$)
  create_reference_table
 ------------------------
 
 (1 row)

 CREATE TABLE dist(id int, ref_id int REFERENCES ref(id));
 INSERT INTO dist SELECT x,x FROM generate_series(1,10000) x;
 -- test that we do not cascade truncates to local referencing tables
 SELECT truncate_local_data_after_distributing_table('ref');
-ERROR:  cannot truncate a table referenced in a foreign key constraint by a local table
-DETAIL:  Table "dist" references "ref"
+NOTICE:  truncate cascades to table "dist"
+ truncate_local_data_after_distributing_table
+----------------------------------------------
+
+(1 row)
+
 -- distribute the table and start testing allowed truncation queries
 SELECT create_distributed_table('dist','id');
-ERROR:  cannot distribute "dist" in sequential mode because it is not empty
-HINT:  If you have manually set <user>.multi_shard_modify_mode to 'sequential', try with 'parallel' option. If that is not the case, try distributing local tables when they are empty.
+NOTICE:  Copying data from local table...
+NOTICE:  copying the data has completed
+DETAIL:  The local data in the table is no longer visible, but is still on disk.
+HINT:  To remove the local data, run: SELECT truncate_local_data_after_distributing_table($$multi_truncate.dist$$)
+ create_distributed_table
+--------------------------
+
+(1 row)
+
```

**Comment by onderkalaci** [comment]
> CREATE TABLE dist(id int, ref_id int REFERENCES ref(id));
 INSERT INTO dist SELECT x,x FROM generate_series(1,10000) x;
 -- test that we do not cascade truncates to local referencing tables
 SELECT truncate_local_data_after_distributing_table('ref');
-ERROR:  cannot truncate a table referenced in a foreign key constraint by a local table
-DETAIL:  Table "dist" references "ref"
+NOTICE:  truncate cascades to table "dist"

this might be cache invalidation issues with foreign keys between local/dist tables such that the foreign key from local table to ref table has not been reflected in the metadata yet, so `truncate_local_data_after_distributing_table` is happily truncating.

@onurctirtir for visibility

**Comment by onurctirtir** [comment]
Can it be the case that coordinator might or might not be added to metadata from run to run ?
If coordinator is added to metadata, then the local table that references to reference table would become a citus table.  With that, `EnsureLocalTableCanBeTruncated->IsCitusTable` check would return false.

**Comment by onderkalaci** [comment]
> Can it be the case that coordinator might or might not be added to metadata from run to run ?
If coordinator is added to metadata, then the local table that references to reference table would become a citus table. With that, EnsureLocalTableCanBeTruncated->IsCitusTable check would return false.

But, we'd expect this behaviour to be consistent, right? The test is not running in parallel with any of the other tests.

I think it is more likely that `EnsureLocalTableCanBeTruncated()->ReferencingRelationIdList()` doesn't return the local table. And, that's likely due to cache invalidation has not been consumed yet (as the dist table is created 1 line before)

**Comment by onurctirtir** [comment]
>But, we'd expect this behaviour to be consistent, right? The test is not running in parallel with any of the other tests.

Yes, this should be consistent. I was expecting some other tests to be running in parallel with that test.

>And, that's likely due to cache invalidation has not been consumed yet (as the dist table is created 1 line before)

Makes a lot sense.
