### ISSUE TITLE
Error message is useless

### ISSUE THREAD

**Issue by KES777** [citusdata/citus#500]
Doing insert I get the error, but from the error I do not understand what is coming on.
```
EXECUTE dbdpg_p7432_1 (
$1: 79b23bdea1d08c85
$2: (null)
$3: (null)
$4: 3:s1177./u/f0/55dd832710f99a511c5169eccdc046.png
$5: 1177
$6: 
$7: png
$8: 33458
$9: 1
$10: 0
$11: 1
$12: 0
$13: 250
$14: 81
$15: 0
$16: (null)
$17: (null)
$18: (null)
$19: (null)
$20: 2012-04-26 20:45:09
$21: (null)
);

    !! ERROR: 7 "ERROR:  cannot plan sharded modification containing values which are not constants or constant expressions" (err#0)
    <- execute("79b23bdea1d08c85", undef, ...)= ( undef ) [1 items] at migrate_data.pl line 192
DBD::Pg::st execute failed: ERROR:  cannot plan sharded modification containing values which are not constants or constant expressions at ./migrate_data.pl line 193.
```
You can see that all values are constants. In other query I have same data which inserted without error:
```
EXECUTE dbdpg_p7432_1 (
$1: b5b5e31ceb634de9
$2: (null)
$3: (null)
$4: 3:s1176./4f/ad31c2373a8dcb837b37df6821b63b.png
$5: 1176
$6: 
$7: png
$8: 29431
$9: 1
$10: 0
$11: 1
$12: 0
$13: 250
$14: 81
$15: 0
$16: (null)
$17: (null)
$18: (null)
$19: (null)
$20: 2012-04-26 20:36:49
$21: (null)
);

    <- execute("b5b5e31ceb634de9", undef, ...)= ( 1 ) [1 items] at migrate_data.pl line 192
```
In the server log:
```
2016-05-06 10:04:56  [7433-10] a@b STATEMENT:  INSERT INTO files2 values( $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21 )
2016-05-06 10:04:56  [7433-11] a@b ERROR:  cannot plan sharded modification containing values which are not constants or constant expressions
```

Please do meaningful error message. for example show 'not constants or constant expressions' or, at least field name for which error occour

**Comment by KES777** [comment]
Manual inserting same data from `psql` console inserts it without error ((

**Comment by KES777** [comment]
I have notice next: every seven insert fail.

**Comment by KES777** [comment]
I have added: log_statement = 'all'
And what I saw:
```
2016-05-06 14:43:48 [11639-16] a@b DETAIL:  parameters: $1 = '234519'
, $2 = '2014-05-05 15:11:56', $3 = 'o@s.ru', $4 = '+7 (812) 718-44-83', $5 = NULL, $6
 = 'VMB-Сервис', $7 = 'телекоммуникационная компания', $8 = '195112, Санкт-Петербург', $9 = 'Интернет / Связь / Информационные техн
ологии / Услуги телефонной связи', $10 = NULL, $11 = NULL, $12 = NULL, $13 = NULL, $14 = NULL, $15 =
 '0', $16 = NULL, $17 = '1', $18 = '{"phones":["+7 (812) 718-44-13"]}'
2016-05-06 14:43:48 [11639-17] a@b ERROR:  cannot plan sharded modifi
cation containing values which are not constants or constant expressions
```
I have count, this is **seven** insert I have done. I shift a bit so this insert is **six** now. It were done without error:

```
2016-05-06 14:45:38 [11884-14] a@b DETAIL:  parameters: $1 = '234519'
, $2 = '2014-05-05 15:11:56', $3 = 'o@s.ru', $4 = '+7 (812) 718-44-83', $5 = NULL, $6
 = 'VMB-Сервис', $7 = 'телекоммуникационная компания', $8 = '195112, Санкт-Петербург', $9 = 'Интернет / Связь / Информационные техн
ологии / Услуги телефонной связи', $10 = NULL, $11 = NULL, $12 = NULL, $13 = NULL, $14 = NULL, $15 =
 '0', $16 = NULL, $17 = '1', $18 = '{"phones":["+7 (812) 718-44-13"]}'
2016-05-06 14:45:38 [11884-15] a@b LOG:  execute dbdpg_p11883_1: INSE
RT INTO offers values( $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $
18 )
```

**Comment by marcocitus** [comment]
This relates to #306. PostgreSQL switches to parameterized plans after 5 executions, but Citus does not support parameterized plans yet.

**Comment by KES777** [comment]
If you use DBI (DBD::Pg) As workaround we may use `{ pg_server_prepare => 0 }` parameter
In detail [here](http://search.cpan.org/dist/DBD-Pg/Pg.pm#prepare)

**Comment by ozgune** [comment]
@anarazel / @onderkalaci - is there a quick way to improve the error message that we display on parameterized prepare?

We should look to resolve the underlying issue. At the same time, I think part of what makes this confusing for users is that it happens on every 6th execution.

**Comment by anarazel** [comment]
On 2016-05-25 16:10:44 -0700, Ozgun Erdogan wrote:
> @anarazel / @onderkalaci - is there a quick way to improve the error message that we display on parameterized prepare?
> 
> We should look to resolve the underlying issue. At the same time, I think part of what makes this confusing for users is that it happens on every 6th execution.

Don't really see an easy way.

**Comment by jasonmp85** [comment]
@ozgune I think that error message _is_ completely accurate for cases when a user tries to e.g. use a function in an `INSERT` command, so I don't think it should be changed.

That said, this error message appears any time a _non-constant_ expression shows up in a modification. That's probably too broad a condition: even though this `INSERT` has non-constant expressions (i.e. variables), all their _values_ are constant, which leads to confusion. So maybe we should scan the query for parameters and emit a better error message in that case.

Finally, @KES777: can you present your original query, as well as the definition for this table? I'm a _little_ suspicious that this might be due to a cast. Sometimes date/time-related casts are not marked as `IMMUTABLE` because they depend on things like server time zone. In that case, there might be a hidden function call that is indeed non-constant in your code. Maybe we could figure it out and get you a fix.

**Comment by KES777** [comment]
This error exists for all our tables. Example some of them:
```
CREATE TABLE "event_types" (
  "id" serial NOT NULL,
  "name" character varying(255) NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("name")
);

--
-- Table: events.
--
CREATE TABLE "events" (
  "id" serial NOT NULL,
  "type_id" integer NOT NULL,
  "timestamp" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "talk_id" integer DEFAULT 0 NOT NULL,
  "data" character varying(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);

```

```
my $job =  sub{
	# Работа выполняется в дочернем процессе
	my( $dbh, $row ) =  @_;

	$dbh->do( $dst_sql, { pg_server_prepare => 0 }, @$row );
	return $dbh->errstr   if $dbh->errstr;

	return "Ready";
};

$fetch_data =  sub{
	return   unless $sth->{ Active };     # Пока есть данные...

	my $data =  $sth->fetchrow_arrayref;  # ...читаем
	return $sth->errstr   if $sth->errstr;

	return $data;
};

print "Migrating data...\n$dst_sql\n";
parallel( $PREFORK, $init, $job, $fetch_data );
```

When we do `$dbh->do( $dst_sql, { pg_server_prepare => 0 }, @$row );` without ` { pg_server_prepare => 0 }` we always get error after 6 executions. bind values are always supplied because they are read from same table in other DB, so no calculation is done.

**Comment by KES777** [comment]
$dst_sql is calculated as:
```
			my $placeholders =  join ', ', ('?')x$sth->{ NUM_OF_FIELDS };
			my $dst_sql      =  ref $table eq 'HASH'  &&  $table->{ dst }
				||  "INSERT INTO \"$dst_table\" values( $placeholders )";
```

and looks like:
```
insert into table values ( ?,?,?,?,? );
```

**Comment by jasonmp85** [comment]
Thanks for the info; looks like it's not just `timestamptz` weirdness, then.

**Comment by ozgune** [comment]
@KES777 -- since we're tracking the issue with parameterized PREPARE statements in #306 and #572, I'm planning to close this issue. Please let us know if you have strong reservations on this.
