### ISSUE TITLE
Shards are shown on PgAdmin/AzureDataStduio  with Starter Plan / MX / Reference Tables on the coordinator 

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#5002]
When users connect to the coordinator -- or workers on mx -- if the node contains both the metadata and the shards, Citus hides the shards to prevent any confusion on psql. See https://github.com/citusdata/citus/pull/2323 and `citus.override_table_visibility`

However, with PgAdmin, our trick doesn't work and I have seen several users confused about seeing the shards. In fact, I have seen some users **Dropping the shards**, thinking that those are left over tables or such.

We should improve table override functionality and make sure that external tools such as pgAdmin or Azure Data Studio.

**Comment by onderkalaci** [comment]
One idea we had in the past to move the shards into a separate schema, which turned out to be complex. Just noting my memories while working on #2323

**Comment by marcocitus** [comment]
It would be good to block destructive operations (drop, truncate) on known shards in a way that does not prevent Citus from performing the operation and can be overridden via a GUC.

**Comment by marcocitus** [comment]
PgAdmin query to get table list:
```
SELECT rel.oid, rel.relname AS name,
        (SELECT count(*) FROM pg_catalog.pg_trigger WHERE tgrelid=rel.oid AND tgisinternal = FALSE) AS triggercount,
        (SELECT count(*) FROM pg_catalog.pg_trigger WHERE tgrelid=rel.oid AND tgisinternal = FALSE AND tgenabled = 'O') AS has_enable_triggers,
        (CASE WHEN rel.relkind = 'p' THEN true ELSE false END) AS is_partitioned,
        (SELECT count(1) FROM pg_catalog.pg_inherits WHERE inhrelid=rel.oid LIMIT 1) as is_inherits,
        (SELECT count(1) FROM pg_catalog.pg_inherits WHERE inhparent=rel.oid LIMIT 1) as is_inherited
    FROM pg_catalog.pg_class rel
        WHERE rel.relkind IN ('r','s','t','p') AND rel.relnamespace = 759729::oid
        AND NOT rel.relispartition
            ORDER BY rel.relname;
```

**Comment by marcocitus** [comment]
Azure Data Studio query to get table list:
```sql
SELECT  n.nspname schema_name,                                                                                                                                    
                        c.relname table_name                                                                                                                                      
                FROM    pg_catalog.pg_class c
                        LEFT JOIN pg_catalog.pg_namespace n
                            ON n.oid = c.relnamespace
                WHERE   c.relkind = ANY(ARRAY['r'])
                ORDER BY 1,2;
```
