### ISSUE TITLE
Not try parallel scan on columnar tables 

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#5003]
We already don't support parallel scans on columnar tables (#4669) and throw `ERROR:  columnar_parallelscan_estimate not implemented` if postgres decides to use parallel scan on columnar table.
However, throwing an error doesn't seem to be enough, for several reasons:

1) Usability: User has a large table and runs a `SELECT` query, then they encounter with that error.
2) (For the upcoming index support)
a) Same usability issue applies to index builds without `CONCURRENTLY` option
b) Plus, if user wants to use `CONCURRENTLY` option, then throwing an error leaves an `INVALID` index behind

**Comment by onurctirtir** [comment]
Looks like 1) is not valid, we already prevent parallel scan for regular queries. (#4617)

On the other hand, 2) is still valid since we still don't prevent postgres choosing parallel scan when building columnar indexes on #4950.

**Comment by kinghuang** [comment]
I'm finding that I also can't create a columnar table using a [CTAS statement](https://www.postgresql.org/docs/current/sql-createtableas.html) with a parallel query. Forcing non-parallel makes it a lot slower.
