### ISSUE TITLE
master_create_empty_shard function does not propagate schema when search_path is used

### ISSUE THREAD

**Issue by trifthen** [citusdata/citus#502]
If a table is created within a schema implicitly with `search_path` instead of explicitly by prepending the schema, subsequent use of the `master_create_empty_shard` function will create shards in the default `search_path` context on shards. This is despite calling all functions with the explicit schema designation.

## How to Replicate

```
CREATE SCHEMA foo;
SET search_path TO foo;

CREATE TABLE bar (id INT, created_dt TIMESTAMPTZ);

SELECT master_create_distributed_table(
  'foo.bar', 'created_dt', 'append'
);

SELECT master_create_empty_shard('foo.bar');
```

## Results

Attempting to utilize the new table results in a strange error:

```
SELECT * FROM foo.bar;

WARNING:  Bad result from localhost:6100
WARNING:  Bad result from localhost:6101
ERROR:  could not receive query results
```

The error occurs because the shard table, `bar_10217` in this case, exists within the `PUBLIC` schema, while citus expects it in the `foo` schema. Connecting to a shard and viewing the tables shows what happened:

```
\dt

             List of relations
 Schema |     Name      | Type  |   Owner
--------+---------------+-------+-----------
 public | bar_102017    | table | postgres
```

**Comment by ozgune** [comment]
@trifthen -- thanks for reporting this issue. We have been tracking issues related to our schema support in #122; and I'll add this issue to that thread as well. #267 may also be a related issue.

We're prioritizing features for v5.2, and we will likely prioritize #122 for our next release.

**Comment by onderkalaci** [comment]
Well, this seems to happen creating the table on a different schema. Following the steps below allows to create the empty shard on both cases:
```SQL

CREATE SCHEMA tpch;

CREATE TABLE tpch.nation_append (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152));
SELECT master_create_distributed_table('tpch.nation_append', 'n_nationkey', 'append');


 SELECT master_create_empty_shard('tpch.nation_append');
 master_create_empty_shard 
---------------------------
                    102008
(1 row)

SET search_path to tpch;
SET
postgres=# 
 SELECT master_create_empty_shard('nation_append');
 master_create_empty_shard 
---------------------------
                    102009
(1 row)

```

So, while implementing the comprehensive schema support (#122) we should consider this as well.
