### ISSUE TITLE
Local execution with cached query execution mode may fail due to dropped columns

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#5038]
For local cached plans, Citus gets the original query and simply updates the relationIds to the corresponding shard relations via `UpdateRelationsToLocalShardTables()`. While doing that, Citus assumes that the attribute numbers of the shell table and the shard are in sync. However, under certain circumstances the attribute numbers of the shards may differ from the shell table. The main source of such changes is `DROP COLUMN ..`. And, if the attribute numbers differ, some operations may fail, such as the below:

```SQL
CREATE TABLE t1 (a int, b int, c int UNIQUE);
SELECT create_distributed_table('t1', 'c');

-- drop a column that is before "ON CONFLICT" clause
ALTER TABLE t1 DROP COLUMN b;

SELECT start_metadata_sync_to_node(nodename,nodeport) FROM pg_dist_node;

-- connect to a worker node where local execution is done
[local] onderkalaci@postgres:9701-97280=# prepare p1(int) as insert into t1(a,c) VALUES (5,$1) ON CONFLICT (c) DO NOTHING;
PREPARE
Time: 1.664 ms
[local] onderkalaci@postgres:9701-97280=# execute p1(2);
INSERT 0 0
Time: 9.402 ms
[local] onderkalaci@postgres:9701-97280=# execute p1(2);
INSERT 0 0
Time: 0.740 ms
[local] onderkalaci@postgres:9701-97280=# execute p1(2);
INSERT 0 0
Time: 1.235 ms
[local] onderkalaci@postgres:9701-97280=# execute p1(2);
INSERT 0 0
Time: 0.775 ms
[local] onderkalaci@postgres:9701-97280=# execute p1(2);
INSERT 0 0
Time: 0.987 ms
[local] onderkalaci@postgres:9701-97280=# execute p1(2);
INSERT 0 0
Time: 1.012 ms
[local] onderkalaci@postgres:9701-97280=# execute p1(2);
ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification
Time: 0.704 ms

set client_min_messages to debug5;

execute p1(2);
DEBUG:  StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0
DEBUG:  query before rebuilding: (null)
DEBUG:  query after rebuilding:  INSERT INTO public.t1_102098 AS citus_table_alias (a, c) VALUES (5, 2) ON CONFLICT(c) DO NOTHING
DEBUG:  assigned task 0 to node localhost:9701
ERROR:  invalid attnum 2 for relation "t1"
Time: 0.705 ms

select attrelid::regclass, attname, attnum, attisdropped from pg_attribute WHERE attrelid IN ('t1'::regclass, 't1_102102'::regclass) and attname NOT IN ('tableoid','cmax', 'xmax', 'cmin', 'xmin', 'ctid') ;
 attrelid  |           attname            | attnum | attisdropped 
-----------+------------------------------+--------+--------------
 t1_102102 | a                            |      1 | f
 t1_102102 | ........pg.dropped.2........ |      2 | t
 t1_102102 | c                            |      3 | f
 t1        | a                            |      1 | f
 t1        | c                            |      2 | f
(5 rows)
```

## Workaround to avoid the error
```SQL
SET citus.enable_local_execution TO false;
execute p1(2);
INSERT 0 0
```

# Can we reproduce with other queries

Yes, almost any query.

```SQL
prepare p2(int) as SELECT count(*) FROM t1 WHERE c = $1 GROUP BY c;

 execute p2(9);
 execute p2(9);
 execute p2(9);
 execute p2(9);
 execute p2(9);
 execute p2(9);
DEBUG:  StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0
DEBUG:  constraint value: 9
DEBUG:  shard count after pruning for t1: 1
ERROR:  invalid attnum 2 for relation "t1"
Time: 0.827 ms

-- or with logs enabled
 execute p2(9);
NOTICE:  executing the command locally: SELECT count(*) AS count FROM public.t1_102102 t1 WHERE (c OPERATOR(pg_catalog.=) 9) GROUP BY c
ERROR:  attribute 2 of type t1_102102 has been dropped
Time: 1.153 ms
```

## Potential approaches to fix the issue:

1) Always make sure that the table definitions are in sync. So, instead of sending `CREATE TABLE ..` commands to the shards with the only existing columns, we should include all the dropped columns in the table definition as well as `DROP COLUMN` definitions.

2) As we update the shell relations to shard relations on the queryTree via `UpdateRelationsToLocalShardTables()`, we should also build a map of `Vars` on the shell tables to the shard tables. We should probably rely on column names while creating the mapping. Plus, we should be careful that we cannot simply use `varno`s as the common keys because `varno`s are defined per query. 

3) We could just deparse/parse once and then cache the plan

## Why remote executions are not affected by this (or non-cached local executions )

Router planner follows a similar approach via `UpdateRelationToShardNames()` function, where table names are replaced with shard names. However, in that case all the deparsing is done on the original query and original shell table. We only use the `CITUS_RTE_SHARD` hack to generate the shard name via deparsing functions like `generate_rte_shard_name()/generate_fragment_name()`

When we don't use cached plan local executions, the query string is generated via `TaskQueryString()`. In that case, we use `deparse_shard_query()` which uses the shell table's attributes while generating the query.

**Comment by onderkalaci** [comment]
Note that we improved the query caching behavior with Citus 10.0 via https://github.com/citusdata/citus/pull/4849/commits/644b266deed2e9dc32664ffe75c902424d2f3361

So, the steps do not require prepared statements prior to 10.1

**Comment by SaitTalhaNisanci** [comment]
I really liked the structure of this issue
