### ISSUE TITLE
Support single Insert, Update, Delete statements wrapped within transaction blocks

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#505]
Citus executes single ``INSERT``, ``UPDATE``, ``DELETE`` statements. Still, if the user explicitly wraps their DML statement with a transaction block, Citus emits the following error:

<pre>
postgres=# BEGIN;
postgres=# INSERT INTO github_events VALUES (2489373118,'PublicEvent','t',24509048,'{}','{"id": 24509048, "url": "https://api.github.com/repos/SabinaS/csee6868", "name": "SabinaS/csee6868"}','{"id": 2955009, "url": "https://api.github.com/users/SabinaS", "login": "SabinaS", "avatar_url": "https://avatars.githubusercontent.com/u/2955009?", "gravatar_id": ""}',NULL,'2015-01-01 00:09:13');

ERROR:  distributed commands cannot run inside a transaction block
</pre>

This behavior introduces usability issues with ORMs that wrap each command into transaction blocks.

@lfittl -- Active Record likes to create BEGIN+COMMIT for really just about [any change you make](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html#module-ActiveRecord::Transactions::ClassMethods-label-save+and+destroy+are+automatically+wrapped+in+a+transaction). 
@fdr -- If I remember correctly, psycopg2 and the python world is also trigger-happy with BEGIN.

**Comment by ozgune** [comment]
I'm also noting #233 as a related issue.

**Comment by anarazel** [comment]
I think there's three different ways to go about this:

1) simply allow INSERTs in a transaction, warn if somebody ABORTs
2) issue DML to workers, but keep a transaction open on all of
   them. Only issue commit when commit on the master is received.
3) Use a transactional queue on the master - but that has disadvantages
   around error reporting too.

I'm inclined to go for 1 or 2. One is trivial, two isn't that much work either.

**Comment by marcocitus** [comment]
+1 on 2. It seems like a logical next step from Jason's UPDATE changes and the multi_transaction functions, and it works with the current replication model since we only need to change a shardstate if there's an actual commit.

**Comment by KES777** [comment]
I think you may resolve many issues when start to use `postgres_fdw`. See [F.31.3. Transaction Management](http://www.postgresql.org/docs/9.5/static/postgres-fdw.html)

It seems you will get much benefit from that, because each shard on worker node is, actually, `FOREIGN TABLE` from side of master node.

**Comment by jasonmp85** [comment]
Hey all,

I've been working on this issue for a bit and wanted to cover my approach/general design here in advance of it actually getting merged in (the pull request is not yet open):

@KES777 — Thanks for the suggestion; we've already considered the `fdw` APIs and realized [they weren't flexible enough](https://www.citusdata.com/blog/19-ozgun/265-postgresql-pgshard-and-what-we-learned-our-failures) for us to generally do what we want to do in Citus. However, `postgres_fdw`'s use of transactions is a good example of how to implement this kind of thing, and I'm _very_ familiar with that particular wrapper in its entirety.

We're going with something similar to what @anarazel mentions as his second option. Essentially, we'll have a `static` variable (i.e. local to a particular session) which keeps track of which shard is being modified (it will be initialized to an invalid shard identifier).

If a modification command (`INSERT`, `UPDATE`, `DELETE`) is encountered in a transaction block context, we'll note the shard it targets in this variable and prepend its SQL with `BEGIN` or `START TRANSACTION`. This will create a transaction on all placements of that shard. We'll note (in the aforementioned `static` variable) the shard being modified.

So for opening the transaction, we'll actually send `BEGIN` ourselves (though we'll do so by using e.g. `IsTransactionBlock` during the first modification command and not by hooking into a hand-issued `BEGIN`).

During the transaction, the active session would permit any currently-supported modification command to go through, so long as that command targets the shard of the previous modification command.

To wrap up the transaction, we're using the same approach as `postgres_fdw`, namely registering a callback using `RegisterXactCallback`.

When a transaction is aborted, we'll abort all remote transactions.

After a transaction successfully commits locally (in case there are modifications locally), we'll commit all remote transactions, treating the `COMMIT` as we already treat existing modification commands (i.e. marking placements as unhealthy if they reject the `COMMIT` where others have succeeded).

This solution will reject nested transactions (i.e. savepoints) outright by detecting them (with `GetCurrentTransactionNestLevel`) and erroring out.

This approach should permit even long-lived modifications (i.e. a `SELECT`, then `BEGIN`, then `INSERT`, then `UPDATE`, then `COMMIT`), making many ORM queries possible (i.e. looking up an object by a key and modifying/creating it if found/absent), and making things like ActiveRecord and Django slightly happier.

**Comment by anarazel** [comment]
> This solution will reject nested transactions (i.e. savepoints) outright by detecting them (with GetCurrentTransactionNestLevel) and erroring out.

Not sure if that's a good idea. Several PLs (e.g. plpython) unconditionally use savepoints internally. How about erroring out only when such a savepoint is rolled back?

**Comment by anarazel** [comment]
> We're going with something similar to what @anarazel mentions as his second option. Essentially, we'll have a static variable (i.e. local to a particular session) which keeps track of which shard is being modified (it will be initialized to an invalid shard identifier).

I wonder whether a better / more flexible solution would instead be to do this on connection level.  After executing the first modification command we set a static variable saying 'noNewTransactions'. Once set we error out when a) new connections are established (both via connection_cache.c and multi_client_executor.c)  b) when starting new transactions.   That'd allow modifications on co-located shards, as long as they're all on the same set of nodes, without any complicated tracking. It'll also catch the case that we establish a new connection to a new node to run SELECT queries, which would violate read-your-own-writes.

I think that might end up being just about as complex, and a bit more flexible.

**Comment by jasonmp85** [comment]
> Not sure if that's a good idea. Several PLs (e.g. plpython) unconditionally use savepoints internally. How about erroring out only when such a savepoint is rolled back?

Hm. OK. And erroring out would result in an `ABORT` so nothing would be applied.

I hadn't prioritized db-side PLs other than PL/pgSQL… do we have anyone who needs e.g. PL/Python?

> I wonder whether a better / more flexible solution would instead be to do this on connection level.

I'm not sure why I didn't think of this. It doesn't change the complexity whatsoever, just keeps track of the valid set of connections rather than a valid `shardId`. I'm going ahead with the shard thing but could move towards the connection thing during code review, as I agree the change would be minor.
