### ISSUE TITLE
Foreign Key  Validation  for new Empty Citus distributed Table blocks write on existing citus distributed table

### ISSUE THREAD

**Issue by bkalpa9** [citusdata/citus#5062]
I am  adding a new table  to our citus cluster which references the existing  distributed citus tables (2 tables), as foreign keys with ON DELETE CASCADE but when executing function:
`SELECT   create_distributed_table ();`
To distribute a new table, it is taking a very long time (in hours)  and also blocking all the write-to-parent tables.
The issue is caused by validation of fk Constraints on both tables, since these existing tables are quite big their size , in several TBs. 

I have the following questions:
1. Is it possible to add a check to skip validation of fk Constraints on new/empty tables from citus extension when creating new tables or adding fk constraints on old empty tables.
2. What can be a workaround for this to deploy the table in a production environment except using a NOT VALID option on fk?
Thanks
Note: I am  using PG13 and Citus 10.0-3

**Comment by hanefi** [comment]
I do not think that there is a workaround other than using `NOT VALID` options here.

**Comment by hanefi** [comment]
Citus ( >= v8.1.0 ) supports `NOT VALID` constraints and `VALIDATE CONSTRAINT` commands. See #2488

For the time being, you can add the constraints with `NOT VALID` option after `create_distributed_table()` completes. You will not really need to use `VALIDATE CONSTRAINT` because the original data on the coordinator node is known to work with the earlier constraints, and the constraints should still be valid on the worker nodes.

An [excerpt](https://www.postgresql.org/docs/current/sql-altertable.html) from PG docs:

> ALTER TABLE .. ADD table_constraint [ NOT VALID ]
> 
> This form adds a new constraint to a table using the same constraint syntax as CREATE TABLE, plus the option NOT VALID, which is currently only allowed for foreign key and CHECK constraints.
> 
> Normally, this form will cause a scan of the table to verify that all existing rows in the table satisfy the new constraint. **But if the NOT VALID option is used, this potentially-lengthy scan is skipped.** The constraint will still be enforced against subsequent inserts or updates (that is, they'll fail unless there is a matching row in the referenced table, in the case of foreign keys, or they'll fail unless the new row matches the specified check condition). But the database will not assume that the constraint holds for all rows in the table, until it is validated by using the VALIDATE CONSTRAINT option. See Notes below for more information about using the NOT VALID option.

The aforementioned note on the previous paragraph:

> Scanning a large table to verify a new foreign key or check constraint can take a long time, and other updates to the table are locked out until the ALTER TABLE ADD CONSTRAINT command is committed. The main purpose of the NOT VALID constraint option is to reduce the impact of adding a constraint on concurrent updates. With NOT VALID, the ADD CONSTRAINT command does not scan the table and can be committed immediately. After that, a VALIDATE CONSTRAINT command can be issued to verify that existing rows satisfy the constraint. The validation step does not need to lock out concurrent updates, since it knows that other transactions will be enforcing the constraint for rows that they insert or update; only pre-existing rows need to be checked. Hence, validation acquires only a SHARE UPDATE EXCLUSIVE lock on the table being altered. (If the constraint is a foreign key then a ROW SHARE lock is also required on the table referenced by the constraint.) In addition to improving concurrency, it can be useful to use NOT VALID and VALIDATE CONSTRAINT in cases where the table is known to contain pre-existing violations. Once the constraint is in place, no new violations can be inserted, and the existing problems can be corrected at leisure until VALIDATE CONSTRAINT finally succeeds.
