### ISSUE TITLE
table access method columnar_beginscan does not support project push down

### ISSUE THREAD

**Issue by yjhjstz** [citusdata/citus#5074]
```c++
static TableScanDesc
columnar_beginscan(Relation relation, Snapshot snapshot,
				   int nkeys, ScanKey key,
				   ParallelTableScanDesc parallel_scan,
				   uint32 flags)
{
	int natts = relation->rd_att->natts;

	/* attr_needed represents 0-indexed attribute numbers */
	Bitmapset *attr_needed = bms_add_range(NULL, 0, natts - 1);

	TableScanDesc scandesc = columnar_beginscan_extended(relation, snapshot, nkeys, key,
														 parallel_scan,
														 flags, attr_needed, NULL);

	bms_free(attr_needed);

	return scandesc;
}
```

attr_needed  current is all columns .

**Comment by onurctirtir** [comment]
Thank you for your interest.

`columnar_beginscan_extended` is the lower level function used by both plain seq. scan & `ColumnarCustomScan`.

We support projection push-down for `ColumnarCustomScan`, but we don't support it for regular seq. scan.
To give some more detail, `ColumnarScanNext` is the function used for `ColumnarCustomScan` and it sets `attr_needed` according to which columns needs to be read when it's called for the first tuple.

**Comment by yjhjstz** [comment]
any way to make seqscan also projection push down?

**Comment by onurctirtir** [comment]
Unfortunately no, currently this is not supported.

To understand your use case better, would you like to share some details regarding why you don't want to use columnar custom scan ?

The only difference between columnar custom scan & "hypothetical" projection-pushdown-enabled seq scan is that columnar custom scan also enables qual pushdown (`columnar.enable_qual_pushdown`). That means, columnar custom scan uses quals in where clause to directly skip the chunks by using chunk min/max values.

**Comment by yjhjstz** [comment]
many thanks.
