### ISSUE TITLE
INSERT INTO (SELECT ...) where the user wants to roll-up data from a distributed table to another one

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#508]
Citus users currently create roll-up tables in the following way: they pick a distribution column, for example sensor_id. They then ingest all event data related to the sensor_id. They then create roll-up tables for per-hour and per-day aggregates on sensor_id. Since all tables are hash partitioned on sensor_id, both raw data and roll-up tables end up being co-located on the same node.

Citus users currently use PL/PgSQL or simple scripts to create these roll-up tables. We need to make this simpler.

We could tackle this issue by thinking about the right way to write `INSERT INTO (SELECT ...)` and adding support for these type of queries.

**Comment by ozgune** [comment]
I'm noting the following links as issues related to this one:

* Issue #40 relates to providing distributed materialized views. Since the user would need to run ``REFRESH`` regularly, ``INSERT INTO (SELECT ...)`` could be a better alternative.
* Issue #11 covers providing this functionality as a user-defined function. This issue (#508) offers native integration into PostgreSQL.
* Issue #212 mentions ``INSERT INTO (SELECT ...)`` support. @jberkus noted in his last reply two separate use-cases: (a) loading from a local table, and (b) water-fountain analytics. We'll keep #212 open for the first use-case and track the analytics use-case as part of this issue.
* [This thread](https://groups.google.com/forum/#!topic/citus-users/GbVZ1ds9bjo) in our public forums captures a related discussion.

**Comment by ozgune** [comment]
We currently provide sample PL/PgSQL scripts to enable this. This feature came up twice in recent customer conversations that providing native support for it could make sense.

**Comment by anarazel** [comment]
It's pl/perl FWIW, because that allows more dynamic statements.

**Comment by lfittl** [comment]
Implemented roll-up in the reference app today and ran into this as well - if we could support `INSERT INTO` it would have saved some effort.

**Comment by ozgune** [comment]
We talked about this in our planning session last week; and I wanted to add two related notes to this issue.

First, we think formally defining table colocation (#695) will make implementing this feature easier. This way, we'll be able to easily verify that the source and destination tables are colocated and that we could push down the ``INSERT INTO (SELECT ...)`` statements.

Second, we think implementing this for ``INSERT`` and ``INSERT ... ON CONFLICT`` (upsert) use the same constructs. We could therefore implement UPSERTs as defined in #509. I'm copy/pasting an example workflow below:

--

I am loading data into staging tables using COPY.  When those are loaded, I need to insert or update the data into my main table, then delete the data from the staging tables.  All staging tables and the main table are distributed using hash partitioning.

My first attempt was simple SQL:

<pre>
UPDATE profile_segment main
SET utc_timestamp = staging.utc_timestamp
FROM profile_segment_staging_000 staging
WHERE staging.segment_id = main.segment_id
AND staging.profile_id = main.profile_id
AND staging.utc_timestamp > main.utc_timestamp;

INSERT INTO profile_segment (profile_id,segment_id,utc_timestamp)
SELECT profile_id, segment_id, utc_timestamp
FROM profile_segment_staging_000
ON CONFLICT DO NOTHING;
</pre>

I was planning on combining these once I had each working.

The first ``UPDATE`` failed with this:
<pre>
ERROR:  cannot perform distributed planning for the given modification
DETAIL:  Joins are not supported in distributed modifications.
</pre>

The second ``INSERT INTO (SELECT ...) ON CONFLICT`` failed with this:
<pre>
ERROR:  cannot perform distributed planning for the given modifications
DETAIL:  Subqueries are not supported in distributed modifications.
</pre>

**Comment by onderkalaci** [comment]
@ozgune @sumedhpathak @samay-sharma 

We discussed with @anarazel about function evaluations for INSERT ... SELECT queries. As far as I can see, that is in the requirements list. However, on the first PR we plan **not** to have function evaluation (i.e., `now()` and `date_trunc()`) in the `SELECT` clauses. 

Then, we plan to add them with separate PR as time permits for 6.0. What do you guys think about that? How critical is having function evaluations for those queries?

**Comment by jberkus** [comment]
As long as function evaluation is on the roadmap, go ahead.  One can't do everything at once.

The reason folks will want function evaluation is that the main reason for INSERT INTO ... SELECT is to do data transformations.

**Comment by ozgune** [comment]
We merged this feature in pull request #859 and I'm removing the v6.0 milestone based on this.

We also talked about several issues that relate to the default customer experience in the [second part of this comment](https://github.com/citusdata/citus/issues/508#issuecomment-217660634). I'm keeping this issue open until we resolve #949, #951, and #954.

**Comment by marcocitus** [comment]
As originally described, this issue seems resolved.
