### ISSUE TITLE
UPDATE / UPSERT INTO (SELECT ...) where the user wants to upsert data from one distributed table to another

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#509]
I'm copy + pasting the following from [this thread](https://groups.google.com/forum/#!topic/citus-users/GbVZ1ds9bjo) in our public forums.

I am loading data into staging tables using COPY.  When those are loaded, I need to insert or update the data into my main table, then delete the data from the staging tables.  All staging tables and the main table are distributed using hash partitioning.

My first attempt was simple SQL:

<pre>
UPDATE profile_segment main
SET utc_timestamp = staging.utc_timestamp
FROM profile_segment_staging_000 staging
WHERE staging.segment_id = main.segment_id
AND staging.profile_id = main.profile_id
AND staging.utc_timestamp > main.utc_timestamp;

INSERT INTO profile_segment (profile_id,segment_id,utc_timestamp)
SELECT profile_id, segment_id, utc_timestamp
FROM profile_segment_staging_000
ON CONFLICT DO NOTHING;
</pre>

I was planning on combining these once I had each working.

The first `UPDATE` failed with this:

<pre>
ERROR:  cannot perform distributed planning for the given modification
DETAIL:  Joins are not supported in distributed modifications.
</pre>

The second `INSERT INTO (SELECT ...) ON CONFLICT` failed with this:

<pre>
ERROR:  cannot perform distributed planning for the given modifications
DETAIL:  Subqueries are not supported in distributed modifications.
</pre>

**Comment by marcocitus** [comment]
I think the aim in the thread was not to upsert from one distributed table to another, but rather to upsert from a staging table. I proposed using a distributed staging table, because that allowed doing the upsert locally on the shard placement (and may thus be easier to support).

**Comment by ozgune** [comment]
I wanted to drop a quick update on this thread.

Citus 6.0 has the ``INSERT INTO (SELECT ...) ON CONFLICT`` syntax implemented in #508.

**Comment by marcocitus** [comment]
Assuming `profile_id` is the distribution column then both the UPDATE and INSERT ... SELECT are supported.
