### ISSUE TITLE
Add NOTICE message when replicating reference tables 

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#5112]
We have seen that it gets confusing for users when they try to create a reference table or do something that triggers replicating reference tables to the nodes missing them.

We should probably add a clear NOTICE message when we are replicating reference tables.

Currently it is confusing because when they are trying to create a table, say name X, they see a message about some other table and they think that there is a bug in Citus.

Idea from Jelte:
NOTICE: Not all reference tables are present on all nodes. Fixing that now automatically, before completing this operation.

**Comment by marcocitus** [comment]
fixed by f4a2d99ce9
