### ISSUE TITLE
Can I manage multiple databases at the same time with Citus?

### ISSUE THREAD

**Issue by AliYildizoz909** [citusdata/citus#5125]
I know Citus distributes tables and improves performance. 
The architecture I want; Working with multiple databases such as master-slave database architecture. I want to read and write from different databases using Citus. Can I manage these databases from a common location with Citus?

**Comment by onderkalaci** [comment]
Hi,

I may need some clarification on the term `database` in your question.  Are you considering databases that are created by `CREATE DATABASE ..` such as [here](https://www.postgresql.org/docs/14/sql-createdatabase.html) or physical database servers?

For the former, yes Citus (mostly) supports using multiple databases. For the latter, I'd suggest reading the architecture of Citus: http://docs.citusdata.com/en/v10.0/get_started/concepts.html#concepts

The short answer is that yes Citus handles multi-node clusters where queries should be run from the coordinator node.

For these types of questions, our [slack channel](https://citus-public.slack.com/) is more appropriate where we use Github for more bug tracking/feature requests etc.
