### ISSUE TITLE
SELECT should not work if shard(min/max)value is not initialized

### ISSUE THREAD

**Issue by KES777** [citusdata/citus#515]
```
# select * from pg_dist_shard;
 logicalrelid | shardid | shardstorage | shardalias | shardminvalue | shardmaxvalue 
--------------+---------+--------------+------------+---------------+---------------
       235437 |  102008 | f            |            |               | 
       235437 |  102009 | t            |            |               | 
       235655 |  102010 | f            |            |               | 
       235655 |  102011 | t            |            |               | 
(4 rows)

# insert into offers (id, ctime, email) values (260000, '1970-01-01 05:00:00', 'asdf@asdf.com' );
ERROR:  distributed modifications must target exactly one shard
# select count(*) from offers;
 count  
--------
 231954
(1 row)
```

If SELECT statement is special case when shard are not initialized It should be described in the doc.
If no, I expect error like 'shardmaxvalue/shardminvalue should be initialized to make SELECT queries'

**Comment by onderkalaci** [comment]
INSERTs should exactly go to a single shard. That's why if there exists any shard without min/max values, Citus cannot decide on which shard the INSERT should go into, and thus errors out.

SELECTs, on the other hand, is different than INSERTs. Shard min/max values are used to find which shards the query should hit (i.e., shard pruning). 
For instance, in your example assume that we have the following pg_dist_shard for an append partitioned table:
```
# select * from pg_dist_shard;
 logicalrelid | shardid | shardstorage | shardalias | shardminvalue | shardmaxvalue 
--------------+---------+--------------+------------+---------------+---------------
       235437 |  102008 | t            |            |       0      |   10
       235437 |  102009 | t            |            |       11    |   20 
       235437 |  102010 | t            |            |       21    |   30
       235437 |  102011 | t            |            |       31  |     40
(4 rows)
```

```SQL
SELECT count(*) from table WHERE partition_column > 15 and partition_column < 25;
```

The above query should only hit `102009` and `102010` shards on the workers such as:

```SQL
SELECT count(*) from table_102009 WHERE partition_column > 15 and partition_column < 25;
SELECT count(*) from table_102010 WHERE partition_column > 15 and partition_column < 25;
```
 But if  shards don't have min/max values, citus can send query fragment to that shard and get the results such as:

```SQL
SELECT count(*) from table_102008 WHERE partition_column > 15 and partition_column < 25;
SELECT count(*) from table_102009 WHERE partition_column > 15 and partition_column < 25;
SELECT count(*) from table_102010 WHERE partition_column > 15 and partition_column < 25;
SELECT count(*) from table_102011 WHERE partition_column > 15 and partition_column < 25;
```

Does the above explanation make sense?

**Comment by KES777** [comment]
Yes, thank you. It is good too see it at the doc
But fix: 'citus can send query fragment to that shard' -> 'citus send query fragment to each such shard also'

**Comment by KES777** [comment]
But this behaviour may cause problems when data migrations in progress:
```
# select * from pg_dist_shard;
 logicalrelid | shardid | shardstorage | shardalias | shardminvalue | shardmaxvalue 
--------------+---------+--------------+------------+---------------+---------------
       235437 |  102008 | f            |            |       0      |   250000
       235437 |  102009 | t            |            |       250001    |   300000
```
we do not delete data from mysql backend to be more failsafe.

When we migrate 6<=id<=10 into postgres shard the metadata should be updated
```
# select * from pg_dist_shard;
 logicalrelid | shardid | shardstorage | shardalias | shardminvalue | shardmaxvalue 
--------------+---------+--------------+------------+---------------+---------------
       235437 |  102008 | f            |            |       0      |   200000
       235437 |  102009 | t            |            |       200001    |   300000
```
But now the 102008 and 102009 shards has duplicated data
so select queries will not work right:
```
# select id from offers order by id desc limit 6;
   id   
--------
 234607
 234607
 234606
 234606
 234605
 234605
(6 rows)

# select id from offers where id > 200000 order by id desc limit 6;
   id   
--------
 234607
 234606
 234605
 234604
 234603
 234602
(6 rows)

```

To fix this you should apply right ranges:

    SELECT count(*) from table WHERE partition_column > 15 and partition_column < 25;

The above query should only hit 102009 and 102010 shards on the workers such as:

    SELECT count(*) from table_102009 WHERE partition_column > 15 and partition_column < 25;
    SELECT count(*) from table_102010 WHERE partition_column > 15 and partition_column < 25;


Should be instead:

    SELECT count(*) from table_102009 WHERE partition_column > 15 and partition_column <= 20;
    SELECT count(*) from table_102010 WHERE partition_column > 21 and partition_column < 25;

**Comment by KES777** [comment]
When the SELECT query is issued without ranges:

    SELECT * FROM table;

Citus should push down next queries:

```
SELECT count(*) from table_102008 WHERE partition_column >= 0 and partition_column <= 10;
SELECT count(*) from table_102009 WHERE partition_column >= 11 and partition_column <= 20;
SELECT count(*) from table_102010 WHERE partition_column >= 21 and partition_column <= 30;
SELECT count(*) from table_102011 WHERE partition_column >= 31 and partition_column <= 40;
```

Thus shards without shardmax/min values configured should not be queried

**Comment by onderkalaci** [comment]
Wait
>When we migrate 200001<=id<=250000 into postgres shard the metadata should be updated

There is no such update, Citus never changes shard min/max values of two shards with a single operation. If you append to `102008 ` shard we get:
```
# select * from pg_dist_shard;
 logicalrelid | shardid | shardstorage | shardalias | shardminvalue | shardmaxvalue 
--------------+---------+--------------+------------+---------------+---------------
       235437 |  102008 | f            |            |       0      |   250000
       235437 |  102009 | t            |            |       200001    |   300000
```

If you append to `102009` shard, we get (i.e., no change)
```
# select * from pg_dist_shard;
 logicalrelid | shardid | shardstorage | shardalias | shardminvalue | shardmaxvalue 
--------------+---------+--------------+------------+---------------+---------------
       235437 |  102008 | f            |            |       0      |   200000
       235437 |  102009 | t            |            |       200001    |   300000
```

In both cases, the query logic works.

**Comment by KES777** [comment]
>Wait

You misunderstood me because of lack of context I think.

We have mysql database with big table, very big. We plan to move data into citus cluster. Data moving should take some days. Because of mysql_fdw support all required operations we can create FOREIGN TABLE in postgres and switch to work with postgres (with mysql backend) instead of mysql.
This step will not require change application logic to work with two databases while migrating data.

Step 2. Simultaneous work
Because citus support foreign tables we do next:
create one shard with 'f' type for data laying in mysql database and shard with 't' type for new data

```
# select * from pg_dist_shard;
 logicalrelid | shardid | shardstorage | shardalias | shardminvalue | shardmaxvalue 
--------------+---------+--------------+------------+---------------+---------------
       235437 |  102008 | f            |            |       0      |   250000
       235437 |  102009 | t            |            |       250001    |   300000
```

Step 3. Moving data 
We are required to migrate data from one database to another. 
Our script do (in detail [here](https://github.com/citusdata/citus/issues/506#issuecomment-218071096) )

1. `insert into audit_102009 select * from audit_102008 where id >=200001 and id <= 250000`
2. update citus metadata 

Yes, we must remove data from 102008 after moving it, but we decide to keep it for backup.

I think it will be even not fix boundaries but just append shardmix/min. So

> The above query should only hit 102009 and 102010 shards on the workers such as:
SELECT count(\*) from table_102009 WHERE partition_column > 15 and partition_column < 25;
SELECT count(\*) from table_102010 WHERE partition_column > 15 and partition_column < 25;

Should be instead:

    SELECT count(*) from table_102009 WHERE partition_column > 15 and partition_column < 25 and partition_column >= 11 and partition_column <= 20;
    SELECT count(*) from table_102010 WHERE partition_column > 15 and partition_column < 25 and partition_column >= 21 and partition_column <= 30;

It looks very safe and do not break anything.

**Comment by marcocitus** [comment]
> Citus should push down next queries:
> 
>     SELECT count(*) from table_102008 WHERE partition_column >= 0 and partition_column <= 10;

Citus doesn't add partition column filters to the shard; it sends roughly the same query to every shard with whatever filters where in the original query.

Would it be possible to define views that match the partition column range? You could maybe switch the mysql_fdw to a different view after copying the data.

I'm not sure if it applies to your use-case, but something we've done in the past to atomically merge  multiple shards into one is to temporarily set the logicalrelid on the new shard to 0, which takes it out of distributed queries. You can later reset it and remove the old shards in the same transaction. This probably works best for read-only shards.

**Comment by KES777** [comment]
Thank you for the idea with views.

**Comment by marcocitus** [comment]
Append-partitioning is now mostly deprecated
