### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by SaiManikantha** [citusdata/citus#5167]
hi ,

is there any helm chart  for the citus data can some one help with that.

**Comment by onderkalaci** [comment]
This has been replied on Slack by @JelteF 

> no we don't have a helm chart. You might be interested in Azure Arc though, which can be used to run citus on your own kubernetes cluster (wherever that kubernetes cluster is): https://docs.microsoft.com/en-us/azure/azure-arc/data/what-is-azure-arc-enabled-postgres-hyperscale
