### ISSUE TITLE
Cannot shard table containing custom types

### ISSUE THREAD

**Issue by lpfeup** [citusdata/citus#518]
I am trying to shard a table with custom types: 

```sql
DROP TABLE IF EXISTS testtable;
DROP TYPE IF EXISTS mycomptype;
DROP TYPE IF EXISTS myenumtype;

CREATE TYPE mycomptype AS (myid uuid, mytext text);
CREATE TYPE myenumtype AS ENUM ('test');

CREATE TABLE testtable (
	id uuid,
	column_a mycomptype NOT NULL,
	column_b myenumtype NOT NULL,

	PRIMARY KEY (id)
);

SELECT master_create_distributed_table('testtable', 'id', 'hash');
SELECT master_create_worker_shards('testtable', 1, 1);
```

but I get the following error:

<pre>
WARNING:  could not receive query results from citus_worker_1:5432
DETAIL:  Client error: type "mycomptype" does not exist
WARNING:  could not create shard on "citus_worker_1:5432"

ERROR:  could only create 0 of 1 of required shard replicas
********** Error **********

ERROR: could only create 0 of 1 of required shard replicas
SQL state: XX000
</pre>

I am running citus with docker compose, single worker (https://github.com/citusdata/docker#docker-compose)

**Comment by saicitus** [comment]
@lpfeup The reason for this seems that the composite types do not exist on the worker.
Could you create the types(like below) on the worker and check if the error is resolved.

```sql
CREATE TYPE mycomptype AS (myid uuid, mytext text);
CREATE TYPE myenumtype AS ENUM ('test');
```

**Comment by lpfeup** [comment]
@saicitus Yes, that did it, thanks.

I thought I could run it just from the master without having to create the custom types explicitly on the workers.
