### ISSUE TITLE
Columnar self-insert sometimes runs forever

### ISSUE THREAD

**Issue by jeff-davis** [citusdata/citus#5180]
```
create table selfinsert(x int) using columnar;
insert into selfinsert select generate_series(1,150000);
insert into selfinsert select * from selfinsert; -- runs forever
```

**Comment by onurctirtir** [comment]
On master, we use transaction snapshot to find the next stripe to read during self-insert, which is able to see the stripes written by itself during the self-insert. This causes self-insert to run forever.

However, on #5154, we make sure to use the snapshot provided by postgres during reads, hence during the self-insert. This prevents self-insert from reading its own writes again and again.

See https://en.wikipedia.org/wiki/Halloween_Problem (cc: @thanodnl :) )
