### ISSUE TITLE
Doesn't install correctly on Ubuntu 21.04.

### ISSUE THREAD

**Issue by cyraid** [citusdata/citus#5182]
The install script ran successfully but since there's no IP found when doing the install, you can't install on 21.04 (and since only installs on latest LTS). Could you either throw an error or give us the repo URL directly so we can 'tee' it like other sites provide?

Something like:

For the key: `curl -L https://repos.citusdata.com/community/gpgkey | sudo apt-key add -`
For the apt-source: `echo "deb https://repos.citusdata.com/community/ubuntu/ focal main" | sudo tee /etc/apt/sources.list.d/citusdata_community.list` ?

Then the usual apt install after?

**Comment by hanefi** [comment]
Our installation scripts do more than install the packaging repositories. There are many steps that we did not place in any documentation. Here is the installation script you have used: https://github.com/citusdata/packaging/blob/gh-pages/community/deb.sh

Here is roughly what the script does:
- check for gpg for encryption
- check for curl
- check for PGDG repositories, install if missing
- install our package repositories.

What you want is a manual step for the last item in the list. I will come up with a simple solution and share it here.

**Comment by hanefi** [comment]
The following command will install the packaging repository for Ubuntu Focal in your system:

```console
curl https://install.citusdata.com/community/deb.sh | sudo os=Ubuntu dist=focal bash
```

However, you should do this on your discretion as we do not test binary compatibility for Non-LTS distributions of Ubuntu.
