### ISSUE TITLE
Preliminary work on comprehensive schema support

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#522]
We capture 11 reported issues related to schema changes in #122.

Before we start assigning these issues, we should look at the schema support as a whole, potentially categorize open issues, and develop a simple game plan. I'm opening this issue to do this initial work, and also to coordinate the comprehensive schema support work.

**Comment by ozgune** [comment]
I have a quick question about schema support.

We currently pass down ``CREATE SCHEMA`` commands to worker nodes as we're creating the shards. Another alternative is to pass this down as the user runs the command.

What are the implications of passing this down at shard creation time? Does this play nice when we have features such as multi-user?

**Comment by sumedhpathak** [comment]
@onder: Could you look into this as your next task? We have 11 issues captured already, so the goal would be to evaluate if those are sufficient to provide full schema support, or add new issues if not.

**Comment by onderkalaci** [comment]
@sumedhpathak I started looking into this and try to capture if there exist any other issues with schemas.
I'll share my progress soon.

**Comment by onderkalaci** [comment]
I decided to write down all the functionality that Citus provides, and exercise them on/cross different schemas. As I progress on this task, I'll update all the items below either with referencing the old issues, opening new issues or mentioning that it works fine.

* COPY FROM  
* COPY TO -- Updated [267](https://github.com/citusdata/citus/issues/267)
* EXPLAIN -- Works fine
* SELECT 
   * real-time, task-tracker, router executors
   * router planner, multi planner
   * Various query types:
      * single-shard, multi-shard, task-tracker, repartition subquery, subquery pushdown (w/wthout UDFs defined on other schemas)
      * Aggragates, count distrint approximations, array Aggragates
      * Newly defined UDFs on the same schema / on cross schemas
      * JOINs on the same schema / on cross schemas
      * Foreign data wrappers such as cstore_fdw and file_fdw
      * Composite types on the same schema / on cross schemas
* INSERT / UPSERT / UPDATE / DELETE
* DROP TABLE
* ALTER TABLE 
* append_table_to_shard
* create_empty_shard -- Updated [267](https://github.com/citusdata/citus/issues/267)
* master_create_distributed_table for append
* master_create_distributed_table for hash + master_create_worker_shards -- Updated [267](https://github.com/citusdata/citus/issues/267)
* master_apply_delete_command -- Udated [73](https://github.com/citusdata/citus/issues/73)
* worker_fetch_regular_table -- Updated [504](https://github.com/citusdata/citus/issues/504)
* DROP EXTENSION
* DROP schema
* CREATE / DROP Indexes
* Prepared Statements
* master_copy_shard_placement
* shard_rebalancer
* CREATE TABLE AS (SELECT from schema.dist_table)
* CURSORS
* Multi user patch - Accesses to the users 
 * CREATE SCHEMA schemaname AUTHORIZATION username;

**Comment by ozgune** [comment]
@onderkalaci -- As you find new issues with schema support (say #555, #556, #565), could you also update the notes in #122 for tracking purposes?

**Comment by onderkalaci** [comment]
@ozgune @sumedhpathak I'm done with finding the issues that we should fix for proper schema support. I updated the issues in #122 as well. 
In the end of schema support work, I'd expect to see all the examples in [here](https://gist.github.com/onderkalaci/14794dced563773d778e139561862e7f) works smoothly. I may add new issues/tests if I find more.

Now, I'm looking into multi-user support part of schema support. If I find any issues on that, I'll be opening issue to the enterprise repo.

**Comment by marcocitus** [comment]
I wanted to bring this up for discussion: What if we put all shards in the same schema (e.g. the citusdata. schema)? This would be a usability improvement for masterless, since users wouldn't see the shards when connecting to a worker, plus it might make implementing schema support simpler and less prone to bugs. In any case, it would be nice if there was an easy way to change the shard schema later on.

**Comment by onderkalaci** [comment]
@marcocitus Once we check-in all the schema related items, it'd be possible to create the shards on different schemas. From the usability perspective, I think that makes a lot of sense for the masterless to have the shards on a separate schema.

The only thing I'm not sure is the `AUTHORIZATION` part. If we create the master tables on the `a_test_sch` schema and the shards on the `citusdata` schema, we should make sure that shards have correct authorization values. So, we may need to create `citusdata_1`, `citusdata_2` schemas that match the master schemas with correct privileges. 
(ps: We're still tracking the authorization piece of schemas on [here](https://github.com/citusdata/citus-enterprise/issues/136))

**Comment by sumedhpathak** [comment]
@byucesoy Can this issue now be closed?

**Comment by ozgune** [comment]
@onderkalaci / @byucesoy -- Do we have any information on this issue (#522) that we haven't already captured in #122? (If not, as @sumedhpathak mentioned, could we close this issue?)

**Comment by ozgune** [comment]
We internally synced up on this issue and agreed that we could now close it.
