### ISSUE TITLE
rebalance_table_shards inserting a row to pg_dist_colocation

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [citusdata/citus#5221]
I am mostly creating this issue so that we investigate this further. We realized that rebalance_table_shards might be inserting a new row to pg_dist_colocation, which is not expected or we couldn't reason about this.

We can close the issue, if:
- We reason about why this is happening and we decide to keep it
- We find that this is unexpected and fix that
- We find that it is a false-positive, meaning rebalance_table_shards doesn't insert to pg_dist_colocation.

**Comment by JelteF** [comment]
See test added in this PR: https://github.com/citusdata/citus/pull/5205

**Comment by marcocitus** [comment]
fixed by 07cfba461a
