### ISSUE TITLE
Fixing placements on partitions

### ISSUE THREAD

**Issue by jcuric** [citusdata/citus#5249]
When trying to fix partitioned distributed table with citus_copy_shard_placement error is given

ERROR:  modifications on partitions when replication factor is greater than 1 is not supported
HINT:  Run the query on the parent table "....." instead.

Does anyone know a workaround ?

**Comment by agedemenli** [comment]
We do not allow repairing partitions to prevent any edge cases, `if replication_factor > 1`.

We're already not allowing any kind of modifications on the partition tables, so their placements are not likely to be marked as `INVALID`. Instead, we ask users to run any kind of modification queries on the parent table.

You can run the query on the parent table, as suggested in the hint part.

**Comment by jcuric** [comment]
Maybe I haven't been clear enough.
citus 10.1.0/PG13
some tables have been distributed and partitioned using replication factor 2 ( to have redundancy and also option to move to nearline storage tablespace ) 
there was an hardware issue with one of worker nodes (dbnode03) . It was fixed and some tables are now in invalid shardstate (3) on that node. 
So when i tried to use:
select citus_copy_shard_placement(155791, 'dbnode02',5432,'dbnode03',5432);
to copy active placement over inactive I get:

ERROR:  modifications on partitions when replication factor is greater than 1 is not supported
HINT:  Run the query on the parent table "...." instead.
SQL state: 0A000

I cannot run  citus_copy_shard_placement on parent table as you suggested as its placements are in valid state and therefore will not try to fix already good data.
What is your solution for this kind of situation ?

**Comment by jcuric** [comment]
In case anyone encountered this problem the solution ( after reading Code ) 
is to detach partition from parent table, fix placements using citus_copy_shard_placement ( as is it now a regular distributed table ) and attach partiotion to parent table using original values.
