### ISSUE TITLE
Router executor ignores CTRL+C interrupts

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#525]
In both real-time and task-executors, when a user presses CTRL+C during a query execution, the executors recieves the cancel requests and stops the execution.

However, router executor gets the signal, but, does not terminate the execution.

``` SQL
CREATE TABLE test (a int);
select master_create_distributed_table('test', 'a', 'hash');
select master_create_worker_shards('test', 16, 1);

# on the real-time executor the user could cancel the query execution
postgres= SELECT sum(a), pg_sleep(7) FROM test;
^CCancel request sent
ERROR:  canceling statement due to user request
Time: 622.042 ms

# on the task-tracker executor the user could cancel the query execution
postgres= set citus.task_executor_type to "task-tracker";
SET
postgres= SELECT sum(a), pg_sleep(7) FROM test;
^CCancel request sent
ERROR:  canceling statement due to user request
Time: 370.625 ms

# on the task-tracker executor the user CANNOT cancel the query execution
# note that the backend gets the interrupt, but, the execution is not terminated
postgres= set citus.task_executor_type to "real-time";
SET
postgres= SELECT sum(a), pg_sleep(7) FROM test WHERE a = 5;
^CCancel request sent
Time: 7004.447 ms


```

**Comment by onderkalaci** [comment]
I think when we fix this, we should keep in mind that router executor is also responsible for modify queries. So, cancelling a modify query might be trickier due to replication. 

Assume that the user presses CTRL_C when the executor already INSERTed into one placement and not the second placement yet. In that case, we should not change the current beheviour.

**Comment by anarazel** [comment]
@onderkalaci Afaics this is fixed?

**Comment by marcocitus** [comment]
Agreed
