### ISSUE TITLE
Citus health check view for connectivity among the nodes

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#5290]
A simpler version of #4276. The description of #4276 aims to ensure that a view can provide information about the consistency of the objects. 

Although the proposed view could be very useful, a simpler (and probably a higher priority) view could be to provide information about the connectivity of the nodes in the cluster. 

Citus MX and (in general Citus) requires the nodes to be able to connect to each other. Citus can provide a simple view that provides this information.

```SQL
SELECT * FROM citus_node_health;
source_node target_node success
9700  9700  TRUE
9700  9701  TRUE
9700  9702  TRUE
9701  9700  TRUE
9701  9701  TRUE
9701  9702  TRUE
9702  9700  TRUE
9702  9701  TRUE
9702  9702  TRUE
```

And, the users can check the overall health by something like:
```
SELECT bool_and(success) FROM citus_node_health;
```

The lower level API can be something like:
```SQL
SELECT * FROM check_connection_to_nodes();
target_node success
9700  TRUE
```
Where the node that we execute this command tries to connect all the nodes in pg_dist_node with `isactive` and the same `noderole` & `nodecluster`. With that, on the read-replicas we can make sure that this view works as expected.

**Comment by SaitTalhaNisanci** [comment]
>SELECT * FROM check_connection_to_nodes();

Should this also take hostnames/ports of the nodes that it will check the connection to? Because in non-mx case, pg_dist_node will be empty but nodes might still need to connect to each other, such as with repartition joins
