### ISSUE TITLE
[0A000] ERROR: indexes not supported for columnar tables

### ISSUE THREAD

**Issue by ivarzap** [citusdata/citus#5295]
Is it possible to create an index to a columnar table?
`CREATE TABLE table1 (
    time_stamp  TIMESTAMP WITH TIME ZONE,
    value       DOUBLE PRECISION,
    ticker      TEXT
) USING columnar;
CREATE INDEX tabl1_idx ON table1(ticker, time_stamp)
`

I get:
[0A000] ERROR: indexes not supported for columnar tables

**Comment by onurctirtir** [comment]
Yes! We started supporting a class of indexes, btree & hash, with 10.2, which is just tagged today.

Being the author of this feature, I'm looking forward for the community feedback :)

**Comment by onurctirtir** [comment]
Btw, since this error message doesn't apply to the newest version of Citus, I'm closing the issue.

But I'd like to emphasize that one more time, we are looking forward for your feedback via our Slack channel!
https://citus-public.slack.com/
