### ISSUE TITLE
Re-consider the foreign table implementation via Citus Local Tables or Reference tables

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#5299]
Citus' foreign table implementation is heavily aimed to work with `cstore_fdw`, where each shard is a foreign table. In fact, this approach doesn't make much sense for many of the foreign data wrappers, such as postgres_fdw. As we rolled out columnar as part of [Citus 10.0](https://www.citusdata.com/blog/2021/03/06/citus-10-columnar-compression-for-postgres/), we can drop support for cstore_fdw, and implement the foreign tables in a more natural way.

An approach could be to use Citus local tables for foreign tables. These foreign tables can be accessed in the CitusMX workers as well. The coordinator (hence the shard) would have access to the user mapping. So, we don't even need to propagate that to the workers. The queries executed on the w

Marco already has a prototype for that: https://github.com/citusdata/citus/compare/marcocitus/fix-foreign-table?expand=1

Though there are certain things like `undistribute_table` does not work in the prototype. 

Another approach could be to use `foreign reference tables`, which can be more performant when queries from MX workers and could be more efficient when joined with distributed tables

**Comment by agedemenli** [comment]
```sql
CREATE FUNCTION fake_fdw_handler()
RETURNS fdw_handler
AS 'citus'
LANGUAGE C STRICT;

CREATE FOREIGN DATA WRAPPER fake_fdw HANDLER fake_fdw_handler;

CREATE SERVER fake_fdw_server FOREIGN DATA WRAPPER fake_fdw;

CREATE FOREIGN TABLE foreign_table (
  id bigint not null,
  full_name text not null default ''
) SERVER fake_fdw_server OPTIONS (encoding 'utf-8', compression 'true');

select citus_add_local_table_to_metadata('foreign_table');
NOTICE:  foreign-data wrapper "fake_fdw" does not have an extension defined
NOTICE:  server "fake_fdw_server" already exists, skipping
NOTICE:  foreign-data wrapper "fake_fdw" does not have an extension defined
ERROR:  foreign-data wrapper "fake_fdw" does not exist
CONTEXT:  while executing command on localhost:9701
```
