### ISSUE TITLE
Citus 10.2 - Postgres 13.4 - Unable to Insert into Columnar table.

### ISSUE THREAD

**Issue by BrainTonic** [citusdata/citus#5306]
With Postgres 13.4 and Citus 10.2, when running the equivalent query
```sql
CREATE TABLE my_schema.cs_foo (LIKE my_schema.foo) USING columnar;
INSERT INTO my_schema.cs_foo SELECT * FROM my_schema.foo;
```
I'm getting the following
```
[XX000] ERROR: cannot execute SQL without an outer snapshot or portal Where:  SQL statement "SELECT 1 FROM ONLY "columnar"."stripe" x WHERE "storage_id" OPERATOR(pg_catalog.=) $1 AND "stripe_num" OPERATOR(pg_catalog.=) $2 FOR KEY SHARE OF x"
```
I've also tried to create the `cs_foo` in the public schema too, but to no avail. 

I can do the following:
- Create the Columnar version of `foo`
- Do a simple `SELECT * FROM my_schema.cs_foo;` which will come back w/ 0 rows--as it should. 

What I can't do:
- Any inserts of any kind. Anytime I attempt a single insert, multi-insert, insert into, etc..., i get the above error. 

In this database, I already have a columnar table that's located in another schema that's roughly 84 GB (10,390,107,244 records) in size and is working as intended. This table was created about 4 months.

Table's definition in question:
```sql
create table cboe.hist_spx_option_trades
(
	underlying_symbol varchar,
	quote_datetime timestamp,
	sequence_number bigint,
	root varchar,
	expiration date,
	strike numeric,
	option_type varchar(1),
	exchange_id integer,
	trade_size numeric,
	trade_price numeric,
	trade_condition_id integer,
	canceled_trade_condition_id integer,
	best_bid numeric,
	best_ask numeric,
	trade_iv numeric,
	trade_delta numeric,
	underlying_bid numeric,
	underlying_ask numeric,
	number_of_exchanges integer,
	exchange integer,
	bid_size integer,
	bid numeric,
	ask_size integer,
	ask numeric,
	trade_date date
);
```

**Comment by marcocitus** [comment]
That's odd. It seems like there are still foreign keys between metadata tables, but those should have been removed by the 10.0 -> 10.1 upgrade script: https://github.com/citusdata/citus/blob/master/src/backend/columnar/sql/columnar--10.0-3--10.1-1.sql

@BrainTonic did you run `ALTER EXTENSION citus UPDATE`?

**Comment by BrainTonic** [comment]
@marcocitus:

```
.... > ALTER EXTENSION citus UPDATE
[2021-09-21 13:38:18] completed in 129 ms
```

```
.... > CREATE TABLE cboe.cs_hist_spx_option_trades (LIKE cboe.hist_spx_option_trades) USING columnar
[2021-09-21 13:39:32] completed in 11 ms
```

```
.... >  INSERT INTO cboe.cs_hist_spx_option_trades SELECT * FROM cboe.hist_spx_option_trades
[2021-09-21 13:41:23] [XX000] ERROR: cannot execute SQL without an outer snapshot or portal
[2021-09-21 13:41:23] Where: SQL statement "SELECT 1 FROM ONLY "columnar"."stripe" x WHERE "storage_id" OPERATOR(pg_catalog.=) $1 AND "stripe_num" OPERATOR(pg_catalog.=) $2 FOR KEY SHARE OF x"
```

**Comment by marcocitus** [comment]
Can you share `\d columnar.chunk` and `\d columnar.chunk_group` and `SELECT * FROM pg_extension WHERE extname = 'citus';`?

**Comment by onurctirtir** [comment]
> @marcocitus:
> 
> ```
> .... > ALTER EXTENSION citus UPDATE
> [2021-09-21 13:38:18] completed in 129 ms
> ```
> 
> ```
> .... > CREATE TABLE cboe.cs_hist_spx_option_trades (LIKE cboe.hist_spx_option_trades) USING columnar
> [2021-09-21 13:39:32] completed in 11 ms
> ```
> 
> ```
> .... >  INSERT INTO cboe.cs_hist_spx_option_trades SELECT * FROM cboe.hist_spx_option_trades
> [2021-09-21 13:41:23] [XX000] ERROR: cannot execute SQL without an outer snapshot or portal
> [2021-09-21 13:41:23] Where: SQL statement "SELECT 1 FROM ONLY "columnar"."stripe" x WHERE "storage_id" OPERATOR(pg_catalog.=) $1 AND "stripe_num" OPERATOR(pg_catalog.=) $2 FOR KEY SHARE OF x"
> ```

Did you also run ALTER EXTENSION command on worker nodes ?
It doesn't seem like the error is coming from workers, but wanted to double check.

**Comment by onurctirtir** [comment]
Could you also share the output of the following:

```sql
CREATE OR REPLACE FUNCTION columnar_storage_info(
    rel regclass,
    version_major OUT int4,
    version_minor OUT int4,
    storage_id OUT int8,
    reserved_stripe_id OUT int8,
    reserved_row_number OUT int8,
    reserved_offset OUT int8)
  STRICT
  LANGUAGE c AS 'citus', $$columnar_storage_info$$;

select * from columnar_storage_info('<table_name>');
```

**Comment by BrainTonic** [comment]
`SELECT * FROM information_schema.columns WHERE table_name ='chunk'`

| table\_catalog | table\_schema | table\_name | column\_name | ordinal\_position | column\_default | is\_nullable | data\_type | character\_maximum\_length | character\_octet\_length | numeric\_precision | numeric\_precision\_radix | numeric\_scale | datetime\_precision | interval\_type | interval\_precision | character\_set\_catalog | character\_set\_schema | character\_set\_name | collation\_catalog | collation\_schema | collation\_name | domain\_catalog | domain\_schema | domain\_name | udt\_catalog | udt\_schema | udt\_name | scope\_catalog | scope\_schema | scope\_name | maximum\_cardinality | dtd\_identifier | is\_self\_referencing | is\_identity | identity\_generation | identity\_start | identity\_increment | identity\_maximum | identity\_minimum | identity\_cycle | is\_generated | generation\_expression | is\_updatable |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| ********* | columnar | chunk | storage\_id | 1 | NULL | NO | bigint | NULL | NULL | 64 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int8 | NULL | NULL | NULL | NULL | 1 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ********* | columnar | chunk | stripe\_num | 2 | NULL | NO | bigint | NULL | NULL | 64 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int8 | NULL | NULL | NULL | NULL | 2 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ********* | columnar | chunk | attr\_num | 3 | NULL | NO | integer | NULL | NULL | 32 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int4 | NULL | NULL | NULL | NULL | 3 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ********* | columnar | chunk | chunk\_group\_num | 4 | NULL | NO | integer | NULL | NULL | 32 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int4 | NULL | NULL | NULL | NULL | 4 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ********* | columnar | chunk | minimum\_value | 5 | NULL | YES | bytea | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | bytea | NULL | NULL | NULL | NULL | 5 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ********* | columnar | chunk | maximum\_value | 6 | NULL | YES | bytea | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | bytea | NULL | NULL | NULL | NULL | 6 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ********* | columnar | chunk | value\_stream\_offset | 7 | NULL | NO | bigint | NULL | NULL | 64 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int8 | NULL | NULL | NULL | NULL | 7 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ********* | columnar | chunk | value\_stream\_length | 8 | NULL | NO | bigint | NULL | NULL | 64 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int8 | NULL | NULL | NULL | NULL | 8 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ********* | columnar | chunk | exists\_stream\_offset | 9 | NULL | NO | bigint | NULL | NULL | 64 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int8 | NULL | NULL | NULL | NULL | 9 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ********* | columnar | chunk | exists\_stream\_length | 10 | NULL | NO | bigint | NULL | NULL | 64 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int8 | NULL | NULL | NULL | NULL | 10 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ********* | columnar | chunk | value\_compression\_type | 11 | NULL | NO | integer | NULL | NULL | 32 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int4 | NULL | NULL | NULL | NULL | 11 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ********* | columnar | chunk | value\_compression\_level | 12 | NULL | NO | integer | NULL | NULL | 32 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int4 | NULL | NULL | NULL | NULL | 12 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ********* | columnar | chunk | value\_decompressed\_length | 13 | NULL | NO | bigint | NULL | NULL | 64 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int8 | NULL | NULL | NULL | NULL | 13 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ********* | columnar | chunk | value\_count | 14 | NULL | NO | bigint | NULL | NULL | 64 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int8 | NULL | NULL | NULL | NULL | 14 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |


`SELECT * FROM information_schema.columns WHERE table_name ='chunk_group';`

| table\_catalog | table\_schema | table\_name | column\_name | ordinal\_position | column\_default | is\_nullable | data\_type | character\_maximum\_length | character\_octet\_length | numeric\_precision | numeric\_precision\_radix | numeric\_scale | datetime\_precision | interval\_type | interval\_precision | character\_set\_catalog | character\_set\_schema | character\_set\_name | collation\_catalog | collation\_schema | collation\_name | domain\_catalog | domain\_schema | domain\_name | udt\_catalog | udt\_schema | udt\_name | scope\_catalog | scope\_schema | scope\_name | maximum\_cardinality | dtd\_identifier | is\_self\_referencing | is\_identity | identity\_generation | identity\_start | identity\_increment | identity\_maximum | identity\_minimum | identity\_cycle | is\_generated | generation\_expression | is\_updatable |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| ******** | columnar | chunk\_group | storage\_id | 1 | NULL | NO | bigint | NULL | NULL | 64 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int8 | NULL | NULL | NULL | NULL | 1 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ******** | columnar | chunk\_group | stripe\_num | 2 | NULL | NO | bigint | NULL | NULL | 64 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int8 | NULL | NULL | NULL | NULL | 2 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ******** | columnar | chunk\_group | chunk\_group\_num | 3 | NULL | NO | integer | NULL | NULL | 32 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int4 | NULL | NULL | NULL | NULL | 3 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |
| ******** | columnar | chunk\_group | row\_count | 4 | NULL | NO | bigint | NULL | NULL | 64 | 2 | 0 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | ******** | pg\_catalog | int8 | NULL | NULL | NULL | NULL | 4 | NO | NO | NULL | NULL | NULL | NULL | NULL | NO | NEVER | NULL | YES |

`SELECT * FROM pg_extension WHERE extname = 'citus';`

| oid | extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 57016 | citus | 10 | 11 | false | 10.0-4 | NULL | NULL |

```sql
*******> CREATE OR REPLACE FUNCTION columnar_storage_info(
               rel regclass,
               version_major OUT int4,
               version_minor OUT int4,
               storage_id OUT int8,
               reserved_stripe_id OUT int8,
               reserved_row_number OUT int8,
               reserved_offset OUT int8)
             STRICT
             LANGUAGE c AS 'citus', $$columnar_storage_info$$
```
`[2021-09-22 14:28:29] [42883] ERROR: could not find function "columnar_storage_info" in file "/usr/lib/postgresql/13/lib/citus.so"`

```sql
*******> CREATE FUNCTION columnar_storage_info(
                      rel regclass,
                      version_major OUT int4,
                      version_minor OUT int4,
                      storage_id OUT int8,
                      reserved_stripe_id OUT int8,
                      reserved_row_number OUT int8,
                      reserved_offset OUT int8)
                    STRICT
                    LANGUAGE c AS 'citus', $$columnar_storage_info$$
```
`[2021-09-22 14:28:40] [42883] ERROR: could not find function "columnar_storage_info" in file "/usr/lib/postgresql/13/lib/citus.so"`

```sql
*******> select * from columnar_storage_info('<table_name>')
```
`[2021-09-22 14:31:51] [42883] ERROR: function columnar_storage_info(unknown) does not exist`
`[2021-09-22 14:31:51] Hint: No function matches the given name and argument types. You might need to add explicit type casts.`
`[2021-09-22 14:31:51] Position: 15`

**Comment by marcocitus** [comment]
Can you also share SELECT citus_version()? 

Somehow the ALTER EXTENSION citus UPDATE did not go through and the SQL schema is still on 10.0.

It may also help to build the release-10.2 branch which contains a small fix.

**Comment by BrainTonic** [comment]
| citus\_version |
| :--- |
| Citus 10.0.5 on x86\_64-pc-linux-gnu, compiled by gcc \(Ubuntu 9.3.0-17ubuntu1\~20.04\) 9.3.0, 64-bit |

**Comment by BrainTonic** [comment]
>  How did you install 10.2? It kind of seems like you're on an older version of 10.0.
At this moment, i don't recall, but if i do, I'll leave a comment. 


> It may also help to build the release-10.2 branch which contains a small fix.
okay.

**Comment by marcocitus** [comment]
> Citus 10.0.5 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit

Alright, it seems like you're not yet using 10.2, which explains why you're getting foreign key-related errors even though 10.2 does not have those foreign keys. It does seem like there's a bug in 10.0. Upgrading to 10.2, restarting, then running ALTER EXTENSION should fix the issue.

**Comment by BrainTonic** [comment]
1. http://docs.citusdata.com/en/v10.2/admin_guide/upgrading_citus.html#step-1-update-citus-package
```
sudo apt-get update
sudo apt-get install postgresql-12-citus-10.2
sudo service postgresql restart
```

```
********> ALTER EXTENSION citus UPDATE
[2021-09-23 21:10:58] [00000] version "10.0-4" of extension "citus" is already installed
[2021-09-23 21:10:58] completed in 15 ms
```

**Comment by BrainTonic** [comment]
Reran the above using `sudo apt-get install postgresql-13-citus-10.2` and the reran the `ALTER EXTENSION citus UPDATE;` and still got the followng:

| citus\_version |
| :--- |
| Citus 10.0.5 on x86\_64-pc-linux-gnu, compiled by gcc \(Ubuntu 9.3.0-17ubuntu1\~20.04\) 9.3.0, 64-bit |

**Comment by BrainTonic** [comment]
When running `SELECT citus_version()`, it comes back with.

| citus\_version |
| :--- |
| Citus 10.2.0 on x86\_64-pc-linux-gnu, compiled by gcc \(Ubuntu 9.3.0-17ubuntu1\~20.04\) 9.3.0, 64-bit |


Is that supposed to be like that?

**Comment by BrainTonic** [comment]
```sql
INSERT INTO cboe.cs_hist_spx_option_trades SELECT * FROM cboe.hist_spx_option_trades
```
```
[2021-09-23 21:26:41] [XX000] ERROR: attempt to write columnar data of length 1250 to offset 24 of block 2 of relation 110211
```

**Comment by marcocitus** [comment]
> Is that supposed to be like that?

Yes. I think you were installing the PG12 version of Citus 10.2 before, but using PG13. Did you run ALTER EXTENSION citus UPDATE on PG13 after installing the PG13 version?

**Comment by BrainTonic** [comment]
Yeah, in [this one](https://github.com/citusdata/citus/issues/5306#issuecomment-926328935), I modified it to be `13` instead of `12`. 

For some reason, when i did [this](https://github.com/citusdata/citus/issues/5306#issuecomment-926332552), I got an error. However, after dropping the table and then rerunning `CREATE TABLE cboe.cs_hist_spx_option_trades (LIKE cboe.hist_spx_option_trades) USING columnar;` and then the below command, it worked. 

Thank you for all y'all help. 
```
> INSERT INTO cboe.cs_hist_spx_option_trades SELECT * FROM cboe.hist_spx_option_trades
```
```
[2021-09-23 21:33:15] 32,800,518 rows affected in 3 m 56 s 530 ms
```
