### ISSUE TITLE
Add global cancellation function

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#5336]
We have views like citus_dist_stat_activity to see queries across the cluster. Sometimes, users will want to cancel some of those queries, but to do so they currently need to be connected to the initiator node. It would be nice if we had a `citus_cancel_backend` function to do cancellations globally.

or maybe we could overload `pg_cancel_backend`, but that might be trickier due to different nodes using the same PID. 

We might want a global PID that includes the node ID.

**Comment by onderkalaci** [comment]
@halilozanakgul can you link your PR and close this issue?

**Comment by halilozanakgul** [comment]
#5699 overrides pg_cancel_backend (and pg_terminate_backend) to cancel queries across clusters.
