### ISSUE TITLE
Unable to find c.h file

### ISSUE THREAD

**Issue by kotsachin** [citusdata/citus#534]
Hi,

$ gcc --version
gcc (GCC) 4.7.2 20121015 (Red Hat 4.7.2-5)

My pg_config:
------------
$ pg_config
BINDIR = /home/linuxadmin/pg_git_install/9.4.7/bin
DOCDIR = /home/linuxadmin/pg_git_install/9.4.7/share/doc/postgresql
HTMLDIR = /home/linuxadmin/pg_git_install/9.4.7/share/doc/postgresql
INCLUDEDIR = /home/linuxadmin/pg_git_install/9.4.7/include
PKGINCLUDEDIR = /home/linuxadmin/pg_git_install/9.4.7/include/postgresql
INCLUDEDIR-SERVER = /home/linuxadmin/pg_git_install/9.4.7/include/postgresql/server
LIBDIR = /home/linuxadmin/pg_git_install/9.4.7/lib
PKGLIBDIR = /home/linuxadmin/pg_git_install/9.4.7/lib/postgresql
LOCALEDIR = /home/linuxadmin/pg_git_install/9.4.7/share/locale
MANDIR = /home/linuxadmin/pg_git_install/9.4.7/share/man
SHAREDIR = /home/linuxadmin/pg_git_install/9.4.7/share/postgresql
SYSCONFDIR = /home/linuxadmin/pg_git_install/9.4.7/etc/postgresql
PGXS = /home/linuxadmin/pg_git_install/9.4.7/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-libxml' '--enable-cassert' '--enable-debug' '--enable-profiling' '--prefix=/home/linuxadmin/pg_git_install/9.4.7/' '--with-python' 'CFLAGS=-g -O0'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -pg -DLINUX_PROFILE -g -O0
CFLAGS_SL = -fpic
LDFLAGS = -L../../../src/common -Wl,--as-needed -Wl,-rpath,'/home/linuxadmin/pg_git_install/9.4.7/lib',--enable-new-dtags
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxml2 -lz -lreadline -lrt -lcrypt -ldl -lm 
VERSION = PostgreSQL 9.4.7

------------

While installing citus-v5.0.0 and citus-v5.0.1 I am getting following error:

/opt/centos/devtoolset-1.1/root/usr/bin/gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -pg -DLINUX_PROFILE -g -O0 -fpic -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wno-clobbered -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/home/linuxadmin/citus/src/include' -I. -I./ -I/home/linuxadmin/pg_git_install/9.4.7/include/postgresql/server -I/home/linuxadmin/pg_git_install/9.4.7/include/postgresql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/home/linuxadmin/pg_git_install/9.4.7/include  -c -o test/connection_utils.o test/connection_utils.c
test/connection_utils.c:16:24: fatal error: internal/c.h: No such file or directory
compilation terminated.
make[1]: *** [test/connection_utils.o] Error 1
make[1]: Leaving directory `/home/linuxadmin/citus/src/backend/distributed'
make: *** [extension] Error 2

---------

Please let me know is it error or I am missing something?

Regards,
Sachin

**Comment by aamederen** [comment]
Hi @kotsachin,

This issue is very similar to #384. To fix this, please either
1. Install PostgreSQL to the default path
2. Use Citus 5.1-rc.1

Thank you for mentioning.

**Comment by kotsachin** [comment]
Hi,

Thanks for reply.
I think issue id fixed in latest version in https://github.com/citusdata/citus/pull/378

Regards,
Sachin
