### ISSUE TITLE
Citus 10.2 rebalance_table_shards not working

### ISSUE THREAD

**Issue by islam-taha** [citusdata/citus#5407]
We have a ready made 2 nodes cluster, after adding 3 more nodes and upgrading to citus 10.2 we are trying to rebalance existing shards to cover the new nodes, but it's not working under any condition.

```
SELECT rebalance_table_shards();
NOTICE:  Moving shard 102008 from x.x.x.x:6432 to x.x.x.x:6432 ...
ERROR:  source placement must be in active state
CONTEXT:  while executing command on localhost:5432
```
Source is already active as the cluster is already working and traffic is there, we have no issues at all with the 2 nodes before, so I think they should be in active state already.

Listing active worker nodes shows that all nodes are active already.

`select * from pg_dist_node` return `isactive = true` for all worker nodes;

**Comment by islam-accredible** [comment]
@JelteF Thank you so much, I've fixed the shards, allowed access across nodes, and rebalancing shards worked perfectly.

**Comment by metdos** [comment]
Closing this issue based on the comments.
