### ISSUE TITLE
not meaningful error for COPY ... FROM ...  command

### ISSUE THREAD

**Issue by KES777** [citusdata/citus#543]
```
# begin;
BEGIN
# copy files2 from '/home/kes/psql/tmp.csv'  with csv;
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

expectect error:
```
ERROR:  distributed commands cannot run inside a transaction block
```

**Comment by metdos** [comment]
This seems to work for me. Which version of Citus are you using?

**Comment by KES777** [comment]
5.1-1

**Comment by metdos** [comment]
I'm still not able to replicate this problem. Could you share how you create, distribute your table etc?

**Comment by KES777** [comment]
I do know what was changed, but also can not replicate this.

**Comment by metdos** [comment]
Then, I'm closing this issue. Please let us know if you experience it again.
