### ISSUE TITLE
Replace \stage with COPY in regression tests

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#547]
Two notes;

- COPY uses the size of transmitted data to calculate the shard size. Therefore, this change will change min/max values of current shards. Playing with the shard max size in regression tests would help to keep shard counts same.

- Currently, COPY creates new shards randomly, after #489 is merged, it will be round-robin as it is in regression tests now.

**Comment by samay-sharma** [comment]
Hey guys,

We have a similar issue for replacing `\stage` with `INSERT` (#133). I don't know if we want to couple these items or not, but it might be easy enough to just do a quick check to see if we can replace `\stage` with `INSERT` in other tests too.

Previously, the pg_shard code was not a part of Citus and there _may_ be tests which used \stage at that point of time which could get away with inserts.

**Comment by marcocitus** [comment]
Unless there's a strong need for insert, it seems cleaner to just use inline COPY in those cases.

**Comment by samay-sharma** [comment]
Inline COPY also works.

My main point was that we shouldn't need to COPY whole files. For eg. In case of the alter table test, to check if default values are added,  NULLs fails etc. we were staging files which is unnecessary.
