### ISSUE TITLE
 postgresql-14-citus-10.2 public key is not available

### ISSUE THREAD

**Issue by yxlwfds** [citusdata/citus#5489]
Reading state information... Done
E: Unable to locate package postgresql-14-citus-10.2
E: Couldn't find any package by glob 'postgresql-14-citus-10.2'
root@linux:~# apt-get update -y
Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease                                                                                                                
Hit:4 http://archive.canonical.com/ubuntu focal InRelease                                                                        
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                  
Get:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                                                      
Hit:7 http://apt.postgresql.org/pub/repos/apt focal-pgdg InRelease                                                                                                    
Get:2 https://repos.citusdata.com/community/ubuntu focal InRelease [24.4 kB]                                                                                          
Err:2 https://repos.citusdata.com/community/ubuntu focal InRelease                             
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0D750985D6AF6C22
Get:8 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1346 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [876 kB]
Reading package lists... Done                        
W: GPG error: https://repos.citusdata.com/community/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0D750985D6AF6C22
E: The repository 'https://repos.citusdata.com/community/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by yxlwfds** [comment]
Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0 x86_64)

**Comment by gurkanindibay** [comment]
We had a problem in our repo installation scripts. Now fixed it. Please try again after executing repo installation script below
```
curl -s https://install.citusdata.com/community/deb.sh | bash
```

**Comment by kokrui** [comment]
Hi! I'm getting the same issue today using the latest repo installation script (same commands, same OS)
