### ISSUE TITLE
COPY on quoted table names fails

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#550]
Follow the steps:

```SQL

-- On master node:
CREATE TABLE "customer_reviews_hash//"
(
    customer_id TEXT,
    review_date DATE,
    review_rating INTEGER,
    review_votes INTEGER,
    review_helpful_votes INTEGER,
    product_id CHAR(10),
    product_title TEXT,
    product_sales_rank BIGINT,
    product_group TEXT,
    product_category TEXT,
    product_subcategory TEXT,
    similar_product_ids CHAR(10)[]
);

SELECT master_create_distributed_table('"customer_reviews_hash//"', 'customer_id', 'hash');
SELECT master_create_worker_shards('"customer_reviews_hash//"', 4, 1);

COPY "customer_reviews_hash//" FROM '/tmp/customer_reviews_1999.csv' WITH CSV;

Worker log:

ERROR:  syntax error at or near "_102013" at character 38
STATEMENT:  COPY public."customer_reviews_hash//"_102013 FROM STDIN WITH (FORMAT BINARY)

```
**Reason for that:**
On [ConstructCopyStatement()](https://github.com/citusdata/citus/blob/2db30af07fe4b36bcd5644a9af028d936a1826d1/src/backend/distributed/commands/multi_copy.c#L1204), we quote the table name before we add the shardId.
So, instead of having:
```SQL
COPY public."customer_reviews_hash//_102013" FROM STDIN WITH (FORMAT BINARY)
```
We end up with:
```SQL
COPY public."customer_reviews_hash//"_102013 FROM STDIN WITH (FORMAT BINARY)
```
Since we have a very common use of generating the table name as follows in the code:
```C
	qualifiedName = quote_qualified_identifier(relation->schemaname,
									    relation->relname);
```

In general, we should ensure that shardIds are added before we call `quote_qualified_identifier()` function.

**Note:** `quote_qualified_identifier()` adds quotes only when needed. So, since our tests do not include any tables which require to be quoted, we should consider all the issues in #122 with quoted table names.

**Comment by metdos** [comment]
Related with #82.
