### ISSUE TITLE
Access Node PSQL Hangs

### ISSUE THREAD

**Issue by CaptainK5** [citusdata/citus#5507]
I'm using CitusDB multi-node setup.  It's working great except occasional problem connecting to AN.  

* Using docker pull citusdata/citus:alpine
* I can docker exec into the AN but running psql command hangs
* What can I do to find out what is happening to the AN?
* Running psql on DN responds 

Is there a log file somewhere?

**Comment by onderkalaci** [comment]
Hi,

I'm not familiar with the AN/DN concepts. Can you clarify a little further the steps you take? 

> I can docker exec into the AN but running psql command hangs

Can you share the psql command and the parameters? Maybe try with `-h localhost` or `-h 127.0.0.1`

**Comment by CaptainK5** [comment]
What are some reasons why just running psql hangs?

- disk is full?
- other reasons?

I can exec into the container, then just running `psql -U postgres` hangs.

**Comment by onderkalaci** [comment]
It mostly feels like a DNS/hostname/connection issue. So, try one of these:
```
psql -U postgres -h localhost
psql -U postgres -h 127.0.0.1
psql -U postgres -h /tmp
```

**Comment by CaptainK5** [comment]
i took everything down (docker-compose down), delete the database directories, brought everything back up (docker-compose up)

everything working again

Will try suggested the next time this happens.

Thank you for the response.
