### ISSUE TITLE
Command to verify data is distributed evenly

### ISSUE THREAD

**Issue by CaptainK5** [citusdata/citus#5508]
* Is there a command to verify all the data is distributed evenly?
* I'm trying to determine if any of my table is too large

**Comment by onderkalaci** [comment]
Hi @CaptainK5,

Our slack channel is more convenient for these types of questions, there is a chance that it is overlooked here for longer periods. Here is the link: https://slack.citusdata.com/  So please use that for further questions!

There is a view, called `citus_shards`, where you can write queries to determine.

> Is there a command to verify all the data is distributed evenly?

For example, you can check the data sizes on the nodes like this:

```SQL
SELECT nodename,
       nodeport,
       pg_size_pretty(sum(shard_size))
FROM citus_shards
GROUP BY nodename, nodeport;
```

 > I'm trying to determine if any of my table is too large

For this one, there is also `citus_tables` view, which probably gives the answer you need `table_size`:
```SQL
select * from citus_tables;
 table_name | citus_table_type | distribution_column | colocation_id | table_size | shard_count | table_owner | access_method 
```

And, then you can use rebalancer to balance the cluster based on `rebalance_strategy := disk_size` if the cluster is imbalanced, such as described [here](https://docs.citusdata.com/en/v10.2/develop/api_udf.html?highlight=rebalance_strategy#rebalance-table-shards)
