### ISSUE TITLE
Broadcast joins may operate on stale data on worker node failures

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#56]
1. Call append to table UDF, say on the TPC-H benchmark's part table. Have one of the worker nodes fail. The failed shard placement will be marked as inactive on the master node's metadata.
2. Issue a query that joins the lineitem and part tables.

We have this bug because the master node will ask the worker to fetch the part shard from a healthy node, but the worker node only checks if the relation locally exists. If the relation exists, the worker just skips fetching the shard.

**Comment by onderkalaci** [comment]
Well, with reference tables this bug wouldn't happen. But, since we are still going to have broadcast tables for a while, I'm not sure whether to close this issue or not. 

Any comments?
