### ISSUE TITLE
Citus should propagate  TEXT SEARCH CONFIGURATION

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#5607]
```SQL
CREATE TEXT SEARCH CONFIGURATION french_noaccent ( COPY = french );
CREATE TABLE test(id int, name text);
CREATE INDEX test_index ON public.test USING gin (to_tsvector('public.french_noaccent'::regconfig, (COALESCE(name, ''::character varying))::text));
select create_distributed_table('test', 'id');
DETAIL: on server onderkalaci@localhost:9701 connectionId: 4
ERROR: text search configuration "public.french_noaccent" does not exist
CONTEXT: while executing command on localhost:9700
```

Until fixed, you may create the search config via:
```SQL
SELECT run_command_on_workers($$CREATE TEXT SEARCH CONFIGURATION french_noaccent ( COPY = french );$$)
```

And, if new nodes are added, the config should be created before any operations is done (e.g., sync metadata or rebalance)

Also, don't forget:
```SQL
CREATE TEXT SEARCH DICTIONARY ispell (
                        Template=ispell,
                        DictFile=ispell_sample,
                        AffFile=ispell_sample
);

```

**Comment by thanodnl** [comment]
guess this should cascade into `CREATE TEXT SEARCH TEMPLATE` as well. These can refer/depend on functions, which we already know how to distribute.

Quickly looking into the dependency graph shows the following:
`index` -> `text search configuration` -> `text search dictionary` -> `text search template` -> `function`

We need to make sure to call `EnsureDependenciesExist...` for indexes being created.
Make sure to implement the deserialization of the following objects:
 - [`TEXT SEARCH CONFIGURATION`](https://www.postgresql.org/docs/current/sql-createtsconfig.html)
 - [`TEXT SEARCH DICTIONARY`](https://www.postgresql.org/docs/current/sql-createtsdictionary.html)
 - [`TEXT SEARCH TEMPLATE`](https://www.postgresql.org/docs/current/sql-createtstemplate.html)
 - `CREATE FUNCTION` is already supported, but we might want to understand how functions used in these scenarios behave and if we need more checks in `CREATE FUNCTION` propagation. I believe it is hard/undoable to resolve dependencies functions have some times as they are mostly runtime errors and not function creation errors. 

Resolution should happen automatically if we support these 3 objects.
They should be able to follow the normal rules for propagation.

**Comment by thanodnl** [comment]
Not directly related to `TEXT SEARCH`, however we will run into it here, as there are many prepopulated objects from PG in these catalogs. We probably need a filter for objects with a oid below the first OID a database will allocate. Postgres defines `FirstNormalObjectId` as 16384. So naively we can assume any oid lower is provided by Postgres. This assumption should be validated, especially what will happen with OID wraparound.

**Comment by thanodnl** [comment]
I think once we land `TEXT SEARCH DICTIONARY` support we can close this.

waiting on #5772
