### ISSUE TITLE
Intermittent issue creating distributed function that references a reference table

### ISSUE THREAD

**Issue by colton-trm** [citusdata/citus#5617]
This cannot be reliably reproduced- I have one cluster where this happens every time, and one cluster where this never happens. 

Reproduction script:
```
CREATE TABLE reference_table (col1 int);

SELECT create_reference_table('reference_table');

CREATE OR REPLACE FUNCTION example_distributed_function()
RETURNS BOOLEAN
AS
$$
  SELECT count(*) > 0 FROM public.reference_table;
$$
LANGUAGE SQL
;

SELECT create_distributed_function('example_distributed_function()',colocate_with => 'reference_table');
```

Error seen:
```
ERROR:  relation "public.reference_table" does not exist
CONTEXT:  while executing command on 10.128.0.99:5432
```

If I instead create this using `PLPGSQL` as follows, then the behavior is permanently fixed on the cluster, even when dropping and creating the function, or creating different functions that refer to different reference tables. 

```
DROP TABLE IF EXISTS reference_table;
DROP FUNCTION IF EXISTS example_distributed_function;
SELECT run_command_on_workers($$
DROP FUNCTION IF EXISTS example_distributed_function;
$$);
CREATE TABLE reference_table (col1 int);

SELECT create_reference_table('reference_table');

CREATE OR REPLACE FUNCTION example_distributed_function()
RETURNS BOOLEAN
AS
$$
BEGIN
  SELECT count(*) > 0 FROM public.reference_table;

END;
$$
LANGUAGE PLPGSQL
;

SELECT create_distributed_function('example_distributed_function()',colocate_with => 'reference_table');
```

**Comment by marcocitus** [comment]
Are you calling the function immediately after `create_distributed_function`? The first create_distributed_function kicks of a background metadata sync, which can take some time to complete, though is normally quick. The pg_dist_node tables shows whether metadata is already synced in the `metadatasynced` column.

Can you check the logs for any metadata syncing failures? 

(in the next release, metadata syncing will be default enabled and this will no longer be an issue).

**Comment by colton-trm** [comment]
Thanks for looking!

It turns out that, while I do have other distributed functions on these clusters, none of them have a `distribution_argument_index` or `colocationid` value in `citus.pg_dist_object`. Further testing validates that only systems with `metadatasynced` of False show the issue, which seems to line up with what you're saying.

**Comment by onderkalaci** [comment]
Well, I'm confident enough to close this issue. This is fixed by multiple PRs
