### ISSUE TITLE
Rename master_stage_protocol.c

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#562]
Since we are planning to deprecate and later get rid of \stage, after COPY is included in Citus, I think we need to get rid of "stage" in master_stage_protocol.c.

**Comment by ozgune** [comment]
@aamederen, I wanted to drop in a quick note.

We borrowed the concept of staging data into the cluster from Hadoop; and several customers use the functions in this file irrespective of ``\stage``. Do you have a file renaming proposal in mind?

**Comment by aamederen** [comment]
I have thought that the stage in `master_stage_protocol` is the same as `\stage` so since `\stage` is going as should `master_stage_protocol`. Since these functions are shard-related functions, one possibility could be `master_shard_protocol`.

**Comment by ozgune** [comment]
@aamederen -- ``master_shard_protocol`` feels a bit generic to me. Since ``stage`` also refers to the concept of uploading data into the cluster, I'm leaning towards closing this issue for now. Any strong reservations?

**Comment by aamederen** [comment]
@ozgune No I don't have any. Let's close it.
