### ISSUE TITLE
Is it a bug in multi_log_hook function

### ISSUE THREAD

**Issue by dxscjx123** [citusdata/citus#5638]
```c
static void
multi_log_hook(ErrorData *edata)
{
	/*
	 * Show the user a meaningful error message when a backend is cancelled
	 * by the distributed deadlock detection.
	 */
	if (edata->elevel == ERROR && edata->sqlerrcode == ERRCODE_QUERY_CANCELED &&
		MyBackendGotCancelledDueToDeadlock())
	{
		edata->sqlerrcode = ERRCODE_T_R_DEADLOCK_DETECTED;
		edata->message = "canceling the transaction since it was "
						 "involved in a distributed deadlock";
	}
}
```

edata->message is not a ptr from pstrdup, how to deal with it, if it is running in errfinish or FreeErrorData for postgresql. In errfinish and FreeErrorData, edata->message will be free by pfree, but for this message in citus, it can not be call pfree

**Comment by onurctirtir** [comment]
Even though we didn't get any core dumps regarding that, theoretically this seems correct.
To be on the safe side, maybe we should `pstrdup()` the errmsg always before setting a msg field of an `ErrorData *` object in the codebase.
