### ISSUE TITLE
Partition entries still exist in `pg_dist_partition` after DROP SCHEMA

### ISSUE THREAD

**Issue by agedemenli** [citusdata/citus#5644]
Steps to reproduce:

```sql
create schema partitioning_schema;
set search_path to partitioning_schema;

CREATE TABLE part_table (
      col timestamp
  ) PARTITION BY RANGE (col);

CREATE TABLE part_table_1
  PARTITION OF part_table
  FOR VALUES FROM ('2010-01-01') TO ('2015-01-01');

SELECT create_distributed_table('part_table', 'col');

drop schema partitioning_schema cascade;

select run_command_on_workers($$SELECT count(*) FROM  pg_dist_partition where not exists(select * from pg_class where pg_class.oid=pg_dist_partition.logicalrelid);$$);
```

After dropping the schema that the partitioned table depends on, all of the partitions are dropped on the workers along with the parent table. The `pg_dist_partition` entry for the parent table is deleted as well. However, `pg_dist_partition` entries for partitions still exist on the mx worker node.

The check on the last line gives the number of `pg_dist_partition` entries that doesn't exist on `pg_class`. Here, for this example, the output is 1, as there is only one partition table.

Possible reason:
When `DROP SCHEMA CASCADE` is executed, the coordinator sends `worker_drop_distributed_table` queries to the workers:
```
NOTICE:  issuing SELECT worker_drop_distributed_table('partitioning_schema.part_table')
DETAIL:  on server ahmet@localhost:9701 connectionId: 3
NOTICE:  issuing SELECT worker_drop_distributed_table('partitioning_schema.part_table')
DETAIL:  on server ahmet@localhost:9702 connectionId: 4
NOTICE:  issuing SELECT worker_drop_distributed_table('partitioning_schema.part_table_1')
DETAIL:  on server ahmet@localhost:9701 connectionId: 3
NOTICE:  issuing SELECT worker_drop_distributed_table('partitioning_schema.part_table_1')
DETAIL:  on server ahmet@localhost:9702 connectionId: 4
```

The command for the parent table deletes the parent table's entry from `pg_dist_partition`.
It also drops the table by calling `performDeletion` function in `worker_drop_distributed_table`, here: https://github.com/citusdata/citus/blob/master/src/backend/distributed/worker/worker_drop_protocol.c#L116

Probably the partition tables are getting dropped when the parent is dropped. But the `pg_dist_partition` entries for them doesn't get deleted. It's because when the command `SELECT worker_drop_distributed_table('partitioning_schema.part_table_1')` is getting issued on the worker node, we return here: https://github.com/citusdata/citus/blob/master/src/backend/distributed/worker/worker_drop_protocol.c#L116

without reaching the line
```
DeletePartitionRow(relationId);
```

that is located at the end of the function, as the relation is already dropped.

**Comment by onderkalaci** [comment]
that is a good observation. We are changing the behavior via https://github.com/citusdata/citus/pull/5619/files and it seems the bug is fixed there

**Comment by onderkalaci** [comment]
Though, now they probably stay in pg_dist_object, and related to https://github.com/citusdata/citus/issues/5615

**Comment by agedemenli** [comment]
Please remove the lines
```sql
-- remove tables from pg_dist_partition, if they don't exist i.e not found in pg_class
delete from pg_dist_partition where not exists(select * from pg_class where pg_class.oid=pg_dist_partition.logicalrelid);
select 1 from run_command_on_workers($$
    delete from pg_dist_partition where not exists(select * from pg_class where pg_class.oid=pg_dist_partition.logicalrelid);$$);
```

from `multi_colocation_utils.sql`, once this issue is resolved

**Comment by onderkalaci** [comment]
@agedemenli anything needed to close this issue?

**Comment by onderkalaci** [comment]
also, pg_dist_shard / shard_placement

**Comment by onderkalaci** [comment]
pg_dist_object entries also not removed
