### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Joan-Healy** [citusdata/citus#5648]
Please reinstall the pgAudit extension for Azure Hyperscale. It is documented [here](https://docs.microsoft.com/en-us/azure/postgresql/hyperscale/concepts-audit#:~:text=The%20pgAudit%20extension%20is%20pre-installed%20and%20enabled%20on,audit%20logging%20emits%20detailed%20logs%20of%20executed%20statements.), but is no longer available in Hyperscale.

**Comment by onderkalaci** [comment]
Hi @Joan-Healy,  as far as I can tell, you'd get faster response if you open a support request on Azure Hyperscale portal.
