### ISSUE TITLE
User-defined functions (UDF) to run arbitrary commands on distributed tables

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#566]
@marcocitus wrote some general-purpose, at-your-own-peril, not-production-ready functions for executing arbitrary commands on distributed tables in parallel using dblink. I'm opening this issue to evaluate making some or all of these functions production ready.

https://gist.github.com/marcocitus/0af4455bd1bc1224ce0476560235b49e

``citus_run_on_all_workers(command)`` - runs a command on every worker in parallel
``citus_run_on_all_placements(table, command)`` - runs a command on every placement in parallel
``citus_run_on_shards(table, command)`` - runs a command on one placement of each shard

The latter two functions pass the command to PostgreSQL's format function with the shard name as a parameter. This means %I will be replaced by the shard name as an identifier, %L will be replaced by
the shard name as a quoted string, and %s will be replaced by the shard name as is.

The functions return some information about whether the command succeeded on each placement/worker, and the query result as text. SELECT queries that don't return a single column will error out, but you can easily work around this.

For example, vacuum all workers:
<pre>
SELECT * FROM citus_run_on_all_workers('VACUUM');
</pre>

Update all shards:
<pre>
SELECT * FROM citus_run_on_all_placements('counters', 'UPDATE %I SET value = value + 1');
</pre>

Call some hypothetical rotate_partition function:
<pre>
SELECT * FROM citus_run_on_all_placements('counters', 'SELECT rotate_partition(%L)');
</pre>

Run a multi-statement transaction:
<pre>
SELECT * FROM citus_run_on_all_placements('counters', 'BEGIN');
SELECT * FROM citus_run_on_all_placements('counters', 'UPDATE %I SET value = value + 1 WHERE id < 10 RETURNING (id, value)');
SELECT * FROM citus_run_on_all_placements('counters', 'ABORT');
</pre>

You can also mimic distributed SELECT:
<pre>
SELECT sum(result::int) FROM citus_run_on_shards('counters', 'SELECT count(*) FROM %I');
</pre>

Interestingly, the above query is faster than SELECT count(*) FROM counters, since there's no sleep overhead. You can also use window functions and the likes.

Current limitations (mostly fixable):
- There are no safe-guards against deadlock for multi-statement transactions
- There are no safe-guards against mid-query failures and resulting
inconsistencies
- Query results are cached in memory; it can't deal with very big result sets
- It errors out early if it cannot connect to a node, but placements
that are already inactive
- You can do very bad things

**Comment by ozgune** [comment]
I'm also noting #10 and #486 as issues that may be related to this.

**Comment by aamederen** [comment]
master_modify_multiple_shards UDF works very similar to these functions. Basically, it does the following:

1. Take Explicit Locks
2. Take a simple UPDATE or DELETE query, parse it and prune the shard list
3. Send BEGIN to all target shard placements
4. For each target shard, replace the table name with the shard name in the query
5. Send the query to all replacements of that shard
6. If commit protocol is 2PC, send PREPARE TRANSACTION commands to each connection
7. COMMIT everything

In this sense, master_modify_multiple_shards functionality is very similar to these functions. I think explicit locks and using connection IDs for 2PC are the differences of master_modify_multiple_shards. I am not sure these function take any locks.

**Comment by ozgune** [comment]
@aamederen -- Could we then use ``master_modify_multiple_shards()`` in place of ``citus_run_on_all_placements()`` in this example?

Or, does ``citus_run_on_all_placements()`` covers a broader use-case because it uses variable interpolation?

**Comment by aamederen** [comment]
Well, citus_run_on_all_placements covers a broader use case but have some limitations:
- I am not sure if there are any ways to take locks on shards with these functions. `master_modify_multiple_shards` take locks either shared or explicit, depending on the replication factor. It also takes `citus.all_modifications_commutative` parameter into account when deciding the shard lock type.
- As stated in OP, there are no safe-guards against mid-query failures and resulting inconsistencies in these functions. `master_modify_multiple_shards` runs immediate rollback when any kind of problem is detected so it can be considered a safer approach.
- I am not sure is it possible to use 2PC easily with these functions. `master_modify_multiple_shards` can use 2PC if `citus.multi_shard_commit_protocol` is set to `'2pc'`. 

So, for multi-shard UPDATE or DELETE queries, using `master_modify_multiple_shards` seems to be the safer choice. And also, using it is easier, with just one function call.

**Comment by sumedhpathak** [comment]
@mtuncer Any update on this issue? Thanks.

**Comment by ozgune** [comment]
@mtuncer / @marcocitus -- I have two questions related to the apis.

1. We use the prefix ``citus_`` when naming these UDFs. In our table creation functions, we completely bypassed the prefix and referred to our functions as ``create_distributed_table``. Over time, it would be nice to converge on a naming protocol for all our upcoming UDFs. What are your thoughts?
2. In ``citus_run_all_workers``, we have an argument ``parallel`` that defaults to ``true``. Do we envision a scenario where we'd like it to be ``false``? (don't know, just curious). Similarly, for the other three functions, we have ``parallel`` default to ``false``. Is this because we'd like to be safe with our default settings?

**Comment by mtuncer** [comment]
@ozgune 
1 - We are using prefixes to denote where the UDF is supposed to be run, like ``master_create_distributed_table`` , ``worker_fetch_regular_table`` and such. Since the newly introduced UDFs are not part of citus package, I felt like we should treat them differently. @marcocitus 's approach looked sound, and I followed it. These ``citus_XXX``` functions were definitely meant to be run on master, but they can run on any node in MX mode. 

2 - I can't think of any reasonable scenario when making parallel execution by default would hurt. We should still keep the flag in case some use case needs sequential execution.

**Comment by lithp** [comment]
For (2), if there is a large number of shard placements parallel execution will hit connection limits, where serial execution will only keep a connection open at a time.

**Comment by ozgune** [comment]
@mtuncer -- This isn't a showstopper, but I'm a bit confused by your reply.

We originally used the prefix ``master_`` and ``worker_`` to differentiate between functions that would run on the master or worker nodes. For our upcoming release, we're moving towards a direction where you could run these UDFs on any one of the nodes. We therefore dropped the prefixes altogether and went with ``create_distributed_table`` / ``create_reference_table``.

I had a clarification question. Could we run these udfs from any one of the nodes? If so, what was our motivation for putting them in ``src/backend/distributed/master``?
