### ISSUE TITLE
Get rid of !HAVE_POLL support

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#567]
The code currently support select(2) as a fallback on platforms that don't support poll(2). But there's nothing relevant without poll support. The last straggler was OSX 10.3 in 2003.  Postgres is also going to start requiring poll support after 9.6.

**Comment by mtuncer** [comment]
I still see HAVE_POLL flags in PG 10 Beta1 source.

**Comment by anarazel** [comment]
On 2017-06-22 00:46:56 -0700, Murat Tuncer wrote:
> I still see HAVE_POLL flags in PG 10 Beta1 source.

Most uses have been removed, I was too slow to remove all of them for
v10 (so far, might still remove).  Nevertheless it's all unused code.
