### ISSUE TITLE
Node calling citus_add_node on itself doesn't fail and locks other citus_add_node operations on that same node

### ISSUE THREAD

**Issue by gledis69** [citusdata/citus#5720]
1) On one terminal:
```
psql -p 9700
SELECT citus_add_node('localhost', 9700);
```

2) On another terminal
```
psql -p 9700
SELECT citus_add_node('localhost', 9701);
```

There is deadlock and both operations wait forever.

**Comment by onderkalaci** [comment]
> SELECT citus_add_node('localhost', 9700);

For adding the coordinator, you need `groupid:=0`, otherwise it is sort of expected. We could be smarter to detect this, and give a proper error.

Is the the case here?
