### ISSUE TITLE
Distribute by tenant/entity and partition on time

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#573]
We had a scoping meeting on distributing by entity/tenant and partitioning on time (#183).

Our motivation for this change is to first support efficient data expiration (by dropping old partitions before a particular date). We later intent to expand on this change so that users can benefit from compression by integrating with cstore.

In the scoping meeting, we defined our requirements as the following. Note that we could implement these requirements in different ways.

1. Auto-partition tables by time: We provide a simple user-defined function (UDF) that partitions a distributed table. The underlying api could look like the following:

<pre>
CREATE TABLE events(id, time);
SELECT create_distributed_table('events', 'id');
SELECT partitioin_distributed_table('events', 'event_time', start_time => '2017-01-01'); // default increment interval: Daily
</pre>

2. Auto data expiration: We have three options - (a) provide a simple UDF that drops partitions that went over the retention period, (b) create a background process that does this automatically, or (c) integrate with a simple cron job on Citus Cloud.

3. Must enable cstore_fdw integration in the future
4. Must work with shard rebalancer and tenant isolation features
5. Should propagate ``CREATE INDEX`` to partitions
6. Supports only replication factor = 1
7. Foreign keys and automatically creating partitions for colocated tables won't be supported (PG also doesn't provide FK support)

**Comment by ozgune** [comment]
Now that we have a better understanding of enabling this (re: Citus / Postgres: sharding on one column and partitioning on time), I'd like to document alternative deliverables for this task.

This issue also relates to technical solutions and use-cases. @lithp had a proposal on the technical solutions side, and @craigkerstiens was interested from a use-case standpoint. On the technical side, we could add our solution to an Examples section in our documentation, have a corresponding github repo, and also post replies to existing open questions (on github issues or SO).

We could also break this issue up into two pieces:

1. We generalize the existing scripts that we have and sanitize any sensitive data. We also describe each script in our docs / github repo. In this step, we emphasize simple data expiration.
2. On top of the previous item, we could introduce cstore_fdw. We show compression's benefits in this section, and also answer questions on update / delete and indexes.

**Comment by ozgune** [comment]
I'm also noting pg_partman as a possible extension we could explore: https://devcenter.heroku.com/changelog-items/942

**Comment by ozgune** [comment]
I'm noting an exchange in #763. The ideal implementation would *automate* the following:

* Create a hash distributed table and create partitions for each shard
* Create new partitions and drop old partitions

**Comment by ozgune** [comment]
We prioritized this feature for our 7.0 release. I'm editing the original issue description to capture our conversations. I'm copy/pasting the original description in this comment.

-- June 1st, 2016

A common question that receive from users is whether they could shard their tables on hash, and then use table inheritance on each shard to further partition the shard by time.

This way, they can expire old data quickly by dropping old partitions. They can also optionally convert old partitions into cstore tables to benefit from 3-4x compression.

Once we understand more about the use-case in #183, this issue involves implementing the needed components to make creating sharded and then partitioned tables simpler.

**Comment by ozgune** [comment]
We had a scoping meeting to define our requirements (updated issue description).

We then talked about two possible approaches to implementing these requirements. I'm documenting these potential approaches here. @onderkalaci and @byucesoy will investigate how these two approaches could satisfy our requirements and also any other potential issues on the implementation side.

1. Inherit from a distributed table, and create a distributed table for every partition: This approach treats partitioning as a cluster wide (distributed concept). It's therefore in line with the declarative partitioning approach in Postgres 10.
2. Create a distributed table and create partitions for each shard: This approach treats partitioning as a local concept. It's therefore easier to implement it through a tool such as [pg_partman](https://github.com/keithf4/pg_partman).

We also said that regardless of the approach we pick, we should look deeper into scripts our existing customers use, the set of questions in #183, and pg_partman's detailed [readme](https://github.com/keithf4/pg_partman/blob/master/doc/pg_partman.md).

**Comment by robin900** [comment]
For comparison/contrast, hash + time-range partitioning is practically the primary motive of the TimescaleDB PG extension project. Here's their [API documentation:](https://docs.timescale.com/api-docs) `create_hypertable` is their equivalent of `create_distributed_table`. Their table distribution scheme relies entirely on the partitioning features of core PG, using postgres_fdw foreign tables, regular tables, and partitions that are themselves partitioned tables.

**Comment by ozgune** [comment]
@robin900 -- I wanted provide an update on this thread. We've been working on this feature and Citus now fully supports PostgreSQL's native partitioning.

[Citus 7](https://www.citusdata.com/blog/2017/09/07/citus-7-distributed-transactions-frameworks-and-pg10/) supports declarative partitioning that comes with PostgreSQL 10. This way, you can hash distribute your tables on one dimension and further partition them on time.

Citus 7.2 makes further improvements to support pg_partman. pg_partman automatically manages Postgres partitions for users (by creating new partitions and dropping old ones). You can read more about it in Citus and pg_partman: Creating a scalable time series database on Postgres.
