### ISSUE TITLE
I can not use pg_prewarm  to load a distributed table to buffer cache.

### ISSUE THREAD

**Issue by levanhai82** [citusdata/citus#5769]
I can not use pg_prewarm  to load a distributed table to buffer cache.

```sql
--------------------------------------
--test pg_prewarm for distributed table
--------------------------------------
CREATE TABLE t_test( a int primary key, b int );
select * from  t_test;

--create distributed table
select create_distributed_table('public.t_test', 'a');

-- insert sample data
insert into t_test(a, b)
select id, id
from (
SELECT  generate_series(1, 1000000) AS id
) t ;

select count(1) from t_test;

-- use pg_prewarm to load table to buffer, but it return 0
SELECT * FROM pg_prewarm('public.t_test');
pg_prewarm|
----------+
         0| 
```

**Comment by hanefi** [comment]
Suggested workaround:

```sql
SELECT * FROM run_command_on_placements('dist_table', $cmd$
	SELECT pg_prewarm( '%s' )
$cmd$);
```

**Comment by levanhai82** [comment]
Hi @hanefi 

It works fine. thank you for your suggest

SELECT * FROM run_command_on_placements('public.t_test', $cmd$
	SELECT pg_prewarm( '%s' )
$cmd$);

nodename                    |nodeport|shardid|success|result|
----------------------------+--------+-------+-------+------+
citus-worker-0.citus-workers|    5432| 105402|true   |140   |
citus-worker-1.citus-workers|    5432| 105403|true   |139   |
citus-worker-0.citus-workers|    5432| 105404|true   |139   |
citus-worker-1.citus-workers|    5432| 105405|true   |139   |
citus-worker-0.citus-workers|    5432| 105406|true   |139   |
citus-worker-1.citus-workers|    5432| 105407|true   |139   |
citus-worker-0.citus-workers|    5432| 105408|true   |137   |
citus-worker-1.citus-workers|    5432| 105409|true   |139   |
citus-worker-0.citus-workers|    5432| 105410|true   |139   |
citus-worker-1.citus-workers|    5432| 105411|true   |138   |
citus-worker-0.citus-workers|    5432| 105412|true   |139   |
citus-worker-1.citus-workers|    5432| 105413|true   |139   |
citus-worker-0.citus-workers|    5432| 105414|true   |139   |
citus-worker-1.citus-workers|    5432| 105415|true   |139   |
citus-worker-0.citus-workers|    5432| 105416|true   |139   |
citus-worker-1.citus-workers|    5432| 105417|true   |139   |
citus-worker-0.citus-workers|    5432| 105418|true   |139   |
citus-worker-1.citus-workers|    5432| 105419|true   |139   |
citus-worker-0.citus-workers|    5432| 105420|true   |139   |
citus-worker-1.citus-workers|    5432| 105421|true   |139   |
citus-worker-0.citus-workers|    5432| 105422|true   |139   |
citus-worker-1.citus-workers|    5432| 105423|true   |139   |
citus-worker-0.citus-workers|    5432| 105424|true   |139   |
citus-worker-1.citus-workers|    5432| 105425|true   |139   |
citus-worker-0.citus-workers|    5432| 105426|true   |138   |
citus-worker-1.citus-workers|    5432| 105427|true   |140   |
citus-worker-0.citus-workers|    5432| 105428|true   |139   |
citus-worker-1.citus-workers|    5432| 105429|true   |138   |
citus-worker-0.citus-workers|    5432| 105430|true   |139   |
citus-worker-1.citus-workers|    5432| 105431|true   |138   |
citus-worker-0.citus-workers|    5432| 105432|true   |139   |
citus-worker-1.citus-workers|    5432| 105433|true   |139   |
