### ISSUE TITLE
Regression on inline schema creation

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#5775]
The following fails on master, but not on 10.2:
```
create schema foo create table test (x int, y int);
ERROR:  schema creating is not supported with other create commands
```
We should consider how to handle this command.

**Comment by agedemenli** [comment]
I think it has nothing to do with the GUC `citus.create_object_propagation`. The result will be the same for any value of the GUC

I'm not sure the "bug" label is appropriate or not. We had intentionally omitted deparsing the second part there, for these kind of statements, as it would be costly to support it in terms of time.

As far as I can see, the second part can be a `CREATE TABLE` statement, as well as `CREATE SEQUENCE`, `CREATE TRIGGER`, view, index, grant... maybe even all of them together?

What do you think @marcocitus ? To what extent should we support this?

We can maybe directly call the deparser functions with these parsenodes in the main `CreateSchemaStmt`. Of course, only if we have the deparsers for all of these objects

**Comment by agedemenli** [comment]
We also don't support CREATE SCHEMA statements if the schema name is not given.
Like in:
```sql
CREATE SCHEMA AUTHORIZATION joe;
ERROR:  schema name should be specified
```

It could break some users that already use this functionality.

For our limitations on CREATE SCHEMA statements:
https://github.com/citusdata/citus/blob/master/src%2Fbackend%2Fdistributed%2Fdeparser%2Fdeparse_schema_stmts.c#L90-L98

**Comment by marcocitus** [comment]
> I'm not sure the "bug" label is appropriate or not. We had intentionally omitted deparsing the second part there, for these kind of statements, as it would be costly to support it in terms of time.

Updated the description. To clarify, this statement fails on master but not on 10.2. We should figure out how to make sure it is handled correctly with 11.0 changes.
