### ISSUE TITLE
Prepared statement with an unused parameter of a custom type in a CTE fails

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#5787]
We currently throw an error when a prepared statement has an unused parameter with a custom type in a CTE
```sql
create type foo as (x int, y int);
create table test (x int, y int, z foo);
select create_distributed_table('test','x');

-- add a redundant parameter
PREPARE q1(foo,foo) AS WITH a AS (SELECT * FROM test WHERE z = $1 AND x = 1 OFFSET 0) SELECT * FROM a;

-- regular execution fails
EXECUTE q1('(1,2)','(2,3)');
NOTICE:  issuing SELECT x, y, z FROM (SELECT test.x, test.y, test.z FROM public.test_102010 test WHERE ((test.z OPERATOR(pg_catalog.=) $1::public.foo) AND (test.x OPERATOR(pg_catalog.=) 1)) OFFSET 0) a
ERROR:  could not determine data type of parameter $2
```

**Comment by tejeswarm** [comment]
Coordinator is sending this query
SELECT x, y, z FROM (SELECT test.x, test.y, test.z FROM citus.test_102043 test WHERE ((t
est.z OPERATOR(pg_catalog.=) $1::citus.foo) AND (test.x OPERATOR(pg_catalog.=) 1)) OFFSET 0) a
and in ExtractParametersFromParamList () replaces the custom type with 0 (invalidoid) before sending to worker nodes.

Worker node receives 2 parameters with 0, and is inferring only the first parameter during query parsing.
parse_analyze_varparams ()... transformTypeCast().... variable_paramref_hook() Marks the paramtype from 0 to UNKNOWNID and prepares a T_Param node with UNKNOWNID.
coerce_type()...variable_coerce_param_hook() Changes to paramTypes[paramno - 1] = targetTypeId (17028)

When evaluating the second parameter which is still undefined(0) we are getting this exception.
