### ISSUE TITLE
Extend relation name occurrences in places other than FROM clause in SELECTs

### ISSUE THREAD

**Issue by samay-sharma** [citusdata/citus#582]
Currently, we extend the relation names in FROM clauses with the corresponding shard ids.

This works for queries like:

`SELECT row_to_json(test) from test;`
OR
`SELECT * from test where row_to_json(test) IS NOT NULL;`

But, queries like below fail: 

`SELECT test from test`

OR 

`SELECT row(test) from test`

Other than above, to integrate with [ZomboDB](https://github.com/zombodb/zombodb), we may also need to extend relation names in the where clauses to correctly run queries like:

`SELECT * FROM products WHERE zdb('products', products.ctid) ==> 'sports or box';`

**Comment by eeeebbbbrrrr** [comment]
Note that the @zombodb query example you gave uses a `::regclass` to reference the 'products' table, not a ROW reference, whereas the generic SQL examples above are ROW references.

Basically, @zombodb needs `::regclass` and row references to be expanded in `CREATE INDEX` and only `::regclass` in `SELECT` statements.

**Comment by ozgune** [comment]
@eeeebbbbrrrr -- we're planning on making you this issue's owner. If that doesn't work, could you let us know?

Also, @samay-sharma noted that this change would touch a few places in our distributed planner. Once you have an initial understanding of Citus' planner, what do you think of having a mini-session to go over it together?

**Comment by eeeebbbbrrrr** [comment]
Hi @ozgune!  Yes, I *think* the plan will be for me to own this.  I have details to work out with our mutual partner, however.

And sure, I'd love to have a pairing session once I've gotten into things.  That makes a lot of sense!

**Comment by ozgune** [comment]
@eeeebbbbrrrr I just wanted to drop a quick ping on this issue. If there's anything we could help with, could you let us know? Also happy to chat about this over email.

**Comment by eeeebbbbrrrr** [comment]
I'm still working out details with our mutual customer.  If things go as planned, I'll be starting on this work around the 25th of this month.  When that happens I'll make sure to let you know!

**Comment by ozgune** [comment]
@eeeebbbbrrrr -- we're going into code freeze for v5.2. I'm planning to drop the v5.2 milestone from this issue and mark it as a high priority item for v5.3. Could you let us know if this doesn't work?

**Comment by eeeebbbbrrrr** [comment]
I've forwarded this on to our mutual customer.  I intend to start on this issue Tuesday morning.  Hopefully y'all will at least have some time to help with code reviews and such during the 5.2 code freeze.  Thanks for the heads-up!

**Comment by eeeebbbbrrrr** [comment]
Hi @ozgune!  I started on this work yesterday.  For what it's worth, it was fairly easy to take care of issue #581.

This issue, however, is proving to be an interesting problem.  I want a few more days to continue to familiarize myself with the Citus codebase and execution flow, and then I think I'm going to want to take you up on your offer to talk.  :)  I just want to make sure I know what I'm talking about first.

**Comment by eeeebbbbrrrr** [comment]
It's me again.  I've gotten this working.  I wouldn't say it's remotely close to committable yet, nor is it well tested, but it's doing the RightThing (to some definition of RightThing).

I'll come back in a day or so after I've spent a little more time on this and outline what I've done.  Maybe we can talk sometime next week?

**Comment by ozgune** [comment]
@eeeebbbbrrrr -- This is exciting and next week sounds good!

I'm adding @sumedhpathak and @samay-sharma to this comment to keep them in the loop. We'll reach out with a few proposed times to talk in a few days.

**Comment by eeeebbbbrrrr** [comment]
Hi @ozgune!  What are the chances we can talk this week?  You can email me at eebbrr@gmail.com to coordinate.

**Comment by ozgune** [comment]
@eeeebbbbrrrr -- We talked about the overall approach yesterday and @jasonmp85 will provide an update on this issue shortly.

**Comment by jasonmp85** [comment]
@samay-sharma I think this issue has been expanded to cover two uses: row-type and `regclass`. The main issue with the queries you posted (such as `SELECT test from test`) is the cast that gets added during the deparse phase:

```sql
-- table
CREATE TABLE foo (id integer, name text);

-- user queries
SELECT foo.* FROM foo;
SELECT foo FROM foo;

-- what worker sees
SELECT id, name FROM foo_102032 foo;
SELECT foo.*::public.foo AS foo FROM foo_102032 foo;
```

The simple fix here is to ensure that the type is appropriately shard-extended (or omitted entirely, to be honest). It's clear that the end user wants to query row values from a distributed table, whose shard rowtypes are essentially identical to the distributed table's own rowtype. So this is a missing feature that can be added easily enough.

The other issue is `regclass`-typed values. I don't think we can make the same assumptions in this case: there are (pathological) queries in which there is no 1—1 mapping between shards and `regclass` constants (brought up by @anarazel), and as @onderkalaci worried, there might be cases in the future that we _want_ to preserve the distributed table's name in a `regclass` constant going to a worker. It's possible we'll change our minds on this, but I don't think the `regclass` case is as clear-cut as the rowtype one.
