### ISSUE TITLE
Create reference table fails on table which is referred to by FK when enable_local_execution set to OFF

### ISSUE THREAD

**Issue by gledis69** [citusdata/citus#5853]
Steps how to reproduce:
1. Create a cluster without initializing citus.
2. Only install the extension. E.g runs at port 9700 and there are pg instances running at 9701, 9702:
```sql
CREATE EXTENSION citus;
\c - - - 9701
CREATE EXTENSION citus;
\c - - - 9702
CREATE EXTENSION citus;
```
3. Run on any of the nodes:
```sql
SET citus.enable_local_execution TO OFF;

CREATE TABLE table_with_pk(a bigint PRIMARY KEY);
CREATE TABLE table_with_fk(a bigint, b bigint, FOREIGN KEY (b) REFERENCES table_with_pk(a));

SELECT create_reference_table('table_with_pk');
ERROR:  cannot execute command because a local execution has accessed a placement in the transaction
DETAIL:  Some parallel commands cannot be executed if a previous command has already been executed locally
HINT:  Try re-running the transaction with "SET LOCAL citus.enable_local_execution TO OFF;"
Time: 4.484 ms
```

**Note**: it appears this behavior is the same for citus 10.2 as well so the bug was not introduced with mx.

**Comment by onderkalaci** [comment]
> SET citus.enable_local_execution TO OFF;

When this is set, the behavior you observe seems expected (not ideal). The reason is commented here: https://github.com/citusdata/citus/blob/3a44fa827aa04fd15d04ec37632075722a5eb040/src/backend/distributed/commands/citus_add_local_table_to_metadata.c#L204-L210

**Comment by gledis69** [comment]
This error is apparently expected due to `create_reference_table` relying on local execution which is turned off in this example.
