### ISSUE TITLE
Deprecate \STAGE

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#590]
We added native COPY support to ingest data, and we will deprecate \STAGE. We have multiple issues around \STAGE. After depreciation, we should close all of them.

Here is the list of issues: 

Issue #320: \stage related bugs and usability issues
Issue #547: Replace \stage with COPY in regression tests
Issue #82 : Problem with double-quoted table names
Issue #133: Replace \stage by INSERT wherever possible in the multi_alter_table_statements regression test.

csql related
Issue #507: csql broke psql history

**Comment by ozgune** [comment]
@metdos -- Once we deprecate ``\stage``, do we have any reason to keep ``csql`` around? Or could we also deprecate ``csql`` (and makefile related changes if we made any)?

**Comment by metdos** [comment]
> @metdos -- Once we deprecate \stage, do we have any reason to keep csql around? Or could we also deprecate csql (and makefile related changes if we made any)?

@ozgune, I think there is not any reason to keep csql!

**Comment by ozgune** [comment]
@metdos -- I had two clarification questions on this issue.

* Do we need to close these listed issues to deprecate ``\stage``, or after we deprecate ``\stage``?  For example, #547 relates to replacing ``\stage`` with COPY and I'm guessing we need to close this issue to deprecate ``\stage``. On the other hand, #507 relates to broken csql history. We can only close this issue after we deprecate \stage and csql.

* When we deprecate ``\stage``, do these issues automatically go away for ``COPY``? For example, #338 relates to our shard placement policy. Once we deprecate \stage, we expect this not to be an issue for ``COPY``, is that correct?

**Comment by metdos** [comment]
> Do we need to close these listed issues to deprecate \stage, or after we deprecate \stage? For example, #547 relates to replacing \stage with COPY and I'm guessing we need to close this issue to deprecate \stage. On the other hand, #507 relates to broken csql history. We can only close this issue after we deprecate \stage and csql.
> 
> When we deprecate \stage, do these issues automatically go away for COPY? For example, #338 relates to our shard placement policy. Once we deprecate \stage, we expect this not to be an issue for COPY, is that correct?

@ozgune -- I just wanted to group stage related issues quickly.

I can create two groups, requirements to depreciate (it seems only #547) and the remaining ones. I think we would still have #252 and #338 with COPY, so I'm removing them.

When do we want to remove \stage related code completely. Now or in upcoming releases?
Should we add a depration note to \stage at the moment?

**Comment by ozgune** [comment]
@metdos -- I don't think we need to add a deprecation notice for ``\stage`` because of the following reasons:

* Our production customers who use append-distribution prefer ``master_append_table_to_shard()`` over ``\stage``. This is because they don't want to load in ``csql`` into their client-side applications.
* I think we removed all references to ``\stage`` from our documentation.

**Comment by ozgune** [comment]
I'm adding the v5.3 milestone tag assuming that removing ``\stage`` is a quick fix.

**Comment by lithp** [comment]
Just to confirm, you mean remove \stage entirely?

**Comment by sumedhpathak** [comment]
Hey @lithp As we discussed durn sync-up, the goal is to remove csql and STAGE. Any blockers on this so far?

**Comment by lithp** [comment]
@sumedhpathak Hey, no blockers. Just haven't gotten to it yet.

**Comment by sumedhpathak** [comment]
@lithp can we close this issue now?
