### ISSUE TITLE
Broadcast joins: Command and/or config to determine data freshness

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#594]
When the user issues a broadcast join today, Citus worker nodes cache the source table the very first time. In subsequent queries, we look at the ``ExpireCachedShards`` and table size changes to determine if we should refetch the table from scratch.

https://github.com/citusdata/citus/blob/master/src/backend/distributed/worker/worker_data_fetch_protocol.c#L508

We talked about this behavior with the Citus Cloud team and thought about two simple methods to make this behavior more controllable for the user:

1. The user can run a ``refresh`` user-defined function (UDF) that drops all cached copies of a broadcasted table. The next time the user runs a broadcast join, this ensures that the table is refetched in its entirety.
2. We extend on ``ExpireCachedShards`` so that we refetch the broadcasted table every single time. This way, the user can determine if they want these tables to be updated every single time.

**Comment by mtuncer** [comment]
Why are we limiting this to broadcast join only. The same problem also exists for large tables. Are we okay with returning wrong results if it occurs on a large table ?  

Reason I am asking this is our table fetch command ```worker_fetch_regular_table``` does not know about why it is called for. It just knows it needs to fetch a table from another node. If we need to limit this feature to broadcast joins only, we are going to need to make an api change.

**Comment by mtuncer** [comment]
Perhaps we can introduce an age concept here. Table gets older upon each use, and after some time we expire the cache and refetch. We can use a configuration parameter, user can disable caching altogether or let it expire after some short, or long time. **Time**  could be actual time or number of usages, or entirely something else.

**Comment by ozgune** [comment]
@mtuncer -- For now, we're scoping this issue as a quick fix for the Cloud team. @marcocitus proposed a one liner that dropped cached copies of broadcasted tables; and I'm copy/pasting his email below. @craigkerstiens -- we're now looking into this workaround.

Also, we probably want to have a simple check that the table the user's looking to refresh is a small one.

--

I don't have the full context here, but just wanted to make a note that a relatively simple workaround for broadcast join is to drop cached shards periodically or before running a query.

Now that passwords are the same for all nodes, it's easier to do this on Citus Cloud. I confirmed this works using the following script:

<pre>
psql  postgres://citus:password@masterhost:5432/citus?sslmode=require -tA -F" " \
-c "SELECT node_name FROM master_get_active_worker_nodes() WHERE node_name NOT IN (SELECT nodename FROM pg_dist_shard_placement p JOIN pg_dist_shard s USING (shardid) WHERE logicalrelid = 'test2'::regclass)" | \
xargs -n 1 sh -c "psql postgres://citus:password@\$0:5432/citus?sslmode=require -c \"DROP TABLE IF EXISTS test2_102076\""
</pre>

**Comment by marcocitus** [comment]
Careful with that. Instead, you should call worker_fetch_regular_table with some large size parameter and expire_cached_shards enabled. Otherwise, you might drop the table while a distributed query is still in progress.

**Comment by mtuncer** [comment]
@marcocitus are you suggesting re-fetching broadcast table all the time ? 

My understanding after discussion with @ozgune was that we have already decided to go UDF way that user manually invokes cache invalidation for a specific table. In this case dropping a table while another query in progress is less of an issue.

**Comment by marcocitus** [comment]
No, I'm suggesting proactively re-fetching the broadcast table when the user calls the UDF, rather than dropping it, since dropping can cause ongoing queries to fail, whereas re-fetching it is safe and makes queries go faster.

**Comment by jasonmp85** [comment]
> ping can cause ongoing queries to fail, whereas re-fetching it is safe and makes queries go faster (but the UDF a lot slower)

Is this the case if the `DROP-add` cycle is done in a transaction? Or maybe using `TRUNCATE`?

**Comment by mtuncer** [comment]
@anarazel is working on https://github.com/citusdata/citus/issues/704 . He stated his work on that issue may help us implementing this one.

**Comment by ozgune** [comment]
@mtuncer / @marcocitus, I think it's OK for concurrent queries to fail when the user runs this UDF -- since we already prioritized this issue as a quick workaround until our next release.
