### ISSUE TITLE
can not create citus extension

### ISSUE THREAD

**Issue by DeoLeung** [citusdata/citus#5944]
```sql
CREATE EXTENSION IF NOT EXISTS citus SCHEMA public;
-- ERROR:  extension "citus" must be installed in schema "pg_catalog"

-- type it 1st time
CREATE EXTENSION IF NOT EXISTS citus;
-- ERROR:  cannot update table "pg_dist_rebalance_strategy" because it does not have a replica identity and publishes updates
-- HINT:  To enable updating the table, set REPLICA IDENTITY using ALTER TABLE.

-- type it 2nd time
CREATE EXTENSION IF NOT EXISTS citus;
-- ERROR:  could not open relation with OID 7647558
-- CONTEXT:  SQL statement "SELECT master_unmark_object_distributed(v_obj.classid, v_obj.objid, v_obj.objsubid)"
-- PL/pgSQL function citus_drop_trigger() line 28 at PERFORM
```

using postgres 13.5, citus 10.2-4 and timescaledb enabled before

extension could be created on another db using the same docker image, how shall I fix this?

**Comment by tejeswarm** [comment]
![image](https://user-images.githubusercontent.com/44680808/170539141-cb9452f8-1e68-49ed-95c3-1012fdff1f3b.png)

Please provide more details. Is this server a replica, it appears that server is using logical replication?

**Comment by DeoLeung** [comment]
> ![image](https://user-images.githubusercontent.com/44680808/170539141-cb9452f8-1e68-49ed-95c3-1012fdff1f3b.png)
> 
> Please provide more details. Is this server a replica, it appears that server is using logical replication?

the database once enabled logical replica, but it's off at the moment
```
shared_preload_libraries = 'citus,timescaledb'
# timescaledb
timescaledb.telemetry_level=off
# pgroonga
pgroonga.enable_wal = on

# overwritten
max_connections = 1000
shared_buffers = 4GB
wal_level = minimal
archive_mode = off
archive_command = 'true'
max_wal_senders = 0
max_replication_slots = 0
hot_standby = on
lc_messages = 'C.UTF-8'
lc_monetary = 'C.UTF-8'
lc_numeric = 'C.UTF-8'
lc_time = 'C.UTF-8'
log_min_duration_statement = 0
log_line_prefix = '"%m" "%a" "%u" "%h" "%i" "%e" '
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_truncate_on_rotation = on
log_rotation_age = 1d
log_rotation_size = 0
```
attached my `postgresql.conf` config.
I changed to another image using `13.7` , the problem persists, so I think there shall be some problem with the data

**Comment by tejeswarm** [comment]
The error is emanating from logical replication code, can you please print the output for this
select * from pg_publication_tables;
select * from pg_catalog.pg_stat_subscription;
select * from pg_stat_replication;
select * from pg_replication_slots;
select * from pg_subscription_rel;

**Comment by DeoLeung** [comment]
> select * from pg_publication_tables;
> select * from pg_catalog.pg_stat_subscription;
> select * from pg_stat_replication;
> select * from pg_replication_slots;
> select * from pg_subscription_rel;

```sql
-- this contains all the table(we once enable it before)
-- CREATE PUBLICATION pub1 FOR ALL TABLES;
select * from pg_publication_tables;

-- belows are empty
select * from pg_catalog.pg_stat_subscription;
select * from pg_stat_replication;
select * from pg_replication_slots;
select * from pg_subscription_rel;
```

we remove the publication
```sql
DROP PUBLICATION pub1;
```
and did a server restart(without it still fails), now we can create the extension!

Thank you for your help

**Comment by tejeswarm** [comment]
Thanks for confirming.
