### ISSUE TITLE
PG14 CREATE STATISTICS with expressions does not work on distributed tables

### ISSUE THREAD

**Issue by JelteF** [citusdata/citus#5947]
PG14 added fancier statistics than PG13. In PG14 you can add statistics on expressions.

Works:
```sql
create table t(id bigint, a bigint);
CREATE STATISTICS mystatistics ON greatest(100, id) FROM t;
select create_distributed_table('t', 'id');
```

Fails:
```sql
create table t2(id bigint, a bigint);
select create_distributed_table('t2', 'id');
CREATE STATISTICS mystatistics2 ON greatest(100, id) FROM t;
-- ERROR:  0A000: only simple column references are allowed in CREATE STATISTICS
-- LOCATION:  AppendColumnNames, deparse_statistics_stmts.c:251
```

I didn't look into it much, but the error is coming from our deparsing logic. So it seems that we're not handling the deparsing of these expression statistics correctly.

**Comment by onderkalaci** [comment]
seems like a known limitation https://github.com/citusdata/citus/issues/5264
