### ISSUE TITLE
what is the shard_size ?

### ISSUE THREAD

**Issue by amwps290** [citusdata/citus#5999]
the size is the disk size used or other?

when i execute  `select * from citus_shard`?

**Comment by amwps290** [comment]
Thank you ! I also find the pg_table_size and the TOSAT data

**Comment by oldsterIL** [comment]
It would be great to add this information to the documentation. I spent a lot of time finding this.

**Comment by JelteF** [comment]
I think these days it uses pg_total_relation_size (which includes toast and indexes)
