### ISSUE TITLE
Fast OLAP tutorial: Write an example server script to help with installation and start-up

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#6]
We need to have a tutorial that shows how to ingest time-series data into Citus and to run fast aggregations on this data. This subtask covers writing an example server script to help with installation and server start-up.

This item is a subtask of #3

**Comment by marcocitus** [comment]
We have various tutorials and blog posts on this topic, e.g.:
- https://www.citusdata.com/blog/2018/06/14/scalable-incremental-data-aggregation/
- https://docs.citusdata.com/en/v8.2/get_started/tutorial_realtime_analytics.html
