### ISSUE TITLE
installing not possible on ubuntu 22.04

### ISSUE THREAD

**Issue by Tomato6966** [citusdata/citus#6013]
What I did?

1. install postresql 14 from the build 
2. tried to do:
```
# Add Citus repository for package manager
curl https://install.citusdata.com/community/deb.sh | sudo bash

# install the server and initialize db
sudo apt-get -y install postgresql-14-citus-11.0
```
but it fals on the apt-get install command saying:
![image](https://user-images.githubusercontent.com/68145571/174390607-caba1b3d-3b89-4a6e-a77c-6da4ec77e9c9.png)

and then on apt-update this error comes too...
![image](https://user-images.githubusercontent.com/68145571/174390560-f938c9e5-e692-4b9e-b624-be35ff8e69ea.png)

Please help / guide what to do

**Comment by HarunOr** [comment]
The repo seems to be down right now. You could build it yourself from the source code, or just wait. It'll probably be fixed soon.

**Comment by gurkanindibay** [comment]
Unfortunately no, We're  still waiting for Postgres support for 22.04
You can check it in 
https://www.postgresql.org/download/linux/ubuntu/
Latest LTS ubuntu release being supported by Postgres is 20.04
When Postgres starts supporting 22.04. We will add support as well

**Comment by jsplink** [comment]
Related? OS: Debian bullseye

```
Installing /etc/apt/sources.list.d/citusdata_community.list... done.
Importing Citus Data Community gpg key... done.
Running apt-get update... done.

The repository is set up! You can now install packages.
Err:1 https://repos.citusdata.com/community/debian bullseye InRelease
  Invalid response from proxy: HTTP/1.1 403 CONNECT to https://repos.citusdata.com:443/ not permitted  Connection: close  Date: Sun, 19 Jun 2022 13:06:53 GMT  Server: apt-cacher/1.7.22  Content-Length: 0     [IP: 172.17.0.1 3142]
```

**Comment by drednout** [comment]
Patiently waiting ...  :)

![zhdun](https://user-images.githubusercontent.com/1097155/174485408-6caf2670-d261-4493-bde5-c8c95bf0855a.jpeg)

**Comment by Naeem-Akhter** [comment]
Now Postgres does support for 22.04 and 22.10, citus still not supported on ubuntu/22? 

`
server~/$$ curl https://install.citusdata.com/community/rpm.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8471  100  8471    0     0   9949      0 --:--:-- --:--:-- --:--:--  9942
Detected operating system as ubuntu/22.
Unfortunately, your operating system distribution and version are not supported by this script.

Please contact us via https://www.citusdata.com/about/contact_us with any issues.

server~/$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy`

**Comment by iopanda** [comment]
Here's the same issue, just the version of Ubuntu is different.

https://github.com/citusdata/citus/issues/7692

I wrote a temporary solution in above issue, please check.

**Comment by iopanda** [comment]
ah sorry, I didn't mention this issue has been opened 2 years. Amazing.
Now I think this issue has already been solved.

**Comment by hanefi** [comment]
As of today we have 286 Citus packages for Ubuntu 22.04.
