### ISSUE TITLE
'ALTER INDEX non_index_relation RENAME' Error

### ISSUE THREAD

**Issue by aykut-bozkurt** [citusdata/citus#6043]
Postgres supports 

```sql
ALTER INDEX non_index_relation RENAME ...
```
But Citus fails with not found in cache. Lockmodes for index_relation(ShareUpdateExclusiveLock) and non_index_relation(AccessExclusiveLock) are not respected as well.

**Comment by onderkalaci** [comment]
Related to https://github.com/citusdata/citus/issues/5337 but this has more details about the locks as well
