### ISSUE TITLE
Schema support for shard alias

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#605]
The question is that should we have the schema within the shard alias or should we use the schema of  the distributed relation? I prefer using the  schema of the distributed relation and use shard alias as only the substitute for the table name on the worker node.

We have both usage in the codebase. A simple search on LoadShardAlias() shows this.

**Comment by ozgune** [comment]
@metdos -- I'm inclined to hold off on this because we don't have any users or customers that rely on the shard alias column. (#95)

Personally, I'm also happy to remove the ``shardalias`` column, and reintroduce it when we have a well defined use-case for it.

**Comment by robin900** [comment]
#95 resolved by #739, which renders this issue moot, and it can be closed.

**Comment by metdos** [comment]
Thanks @robin900, closing this issue!
