### ISSUE TITLE
Database not accepting commands to avoid wraparound data loss & columnar tables

### ISSUE THREAD

**Issue by PepperJo** [citusdata/citus#6053]
I get the following error message when trying to execute commands:
```
ERROR:  database is not accepting commands to avoid wraparound data loss in database "XXX"
HINT:  Stop the postmaster and vacuum that database in single-user mode.
You might also need to commit or roll back old prepared transactions, or drop stale replication slots.
```

Now when I try to run in single-user mode I cannot VACUUM the database because single-user mode does not support `shared_preload_libraries` which I need for my columnar citus tables.

**Comment by jeff-davis** [comment]
This appears to be caused by #5958, which has been fixed.

I have reproduced a similar problem, and believe the following will fix it:

1. Start postgres in single-user mode, attaching to the affected database: `./bin/postgres --single -D data $AFFECTED_DATABASE`
2. Run:
```
update pg_class set relfrozenxid='0'::xid where relam=(select oid from pg_am where amname='columnar');
update pg_database set datfrozenxid=(select relfrozenxid from pg_class where relam=(select oid from pg_am where amname='heap') order by age(relfrozenxid) desc limit 1) where datname=current_database();
```
3. Stop postgres.
4. Start postgres normally, then wait for autovacuum to run.

**Comment by PepperJo** [comment]
In the meantime I had some discussions on the Citus and PG Slack but this particular solution was not suggested. I can't test it anymore since I restored my DB otherwise but good to know for others to run into the same issue that there is a PG way to fix this.

**Comment by jeff-davis** [comment]
Committed a change to PG 15+ that should avoid part of the problem: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=6c31ac091f31171601ee00972e131d8683e7b828

That will load shared_preload_libraries even in single-user mode.

**Comment by PepperJo** [comment]
Thanks Jeff. I saw some thread about someone wanting to change this in an earlier version but the PG folks didn't seem to happy about it. Good luck :-)
