### ISSUE TITLE
Problem upgrading Citus on OSX -> 11.0-3 to 11.0-4

### ISSUE THREAD

**Issue by danielnc** [citusdata/citus#6068]
Originally installed citus via brew on 11.0-3 and it works as expected.

I've updated the extension using `brew upgrade citus`, restarted the server but when I call extenstion update I get an error

select citus_version() and \dx both shows a different version and I am not sure how to proceed

```
[danielnc] # \dx
                                            List of installed extensions
        Name        | Version |   Schema   |                              Description
--------------------+---------+------------+------------------------------------------------------------------------
 citus              | 11.0-3  | pg_catalog | Citus distributed database
...
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
(6 rows)

[danielnc] # SELECT * FROM citus_version();
                                                  citus_version
-----------------------------------------------------------------------------------------------------------------
 Citus 11.0.4 on x86_64-apple-darwin21.5.0, compiled by Apple clang version 13.1.6 (clang-1316.0.21.2.5), 64-bit
(1 row)

Time: 22.643 ms
[danielnc] # ALTER EXTENSION citus UPDATE;
NOTICE:  00000: version "11.0-3" of extension "citus" is already installed
LOCATION:  ExecAlterExtensionStmt, extension.c:3087
ALTER EXTENSION
Time: 33.431 ms
```

**Comment by hanefi** [comment]
Hi Daniel,

This is the expected result. `11.0-3` is the schema version that we use for `11.0.4` release. Please note the format difference between the two. Let me tell you the difference between them.

`11.0.4` is the user facing release version. You can check the changelog on what changed in this version for example. We usually prepend a `v` at the beginning and call this version as `v11.0.4`

`11.0-3` is the schema version of this particular Citus release. Whenever we make some changes in database objects, we bump this version. It is not directly coupled with the release version. For example both version `v11.0.3` and `v11.0.4` share the same migration version `11.0-3` as we did not change anything in the schema but some C implementation.

If there are no schema changes, you can see this notice message to indicate that it was basically a no-op. Restarting the database is enough in this case.
