### ISSUE TITLE
Failure to reset RelationAccessHash at the end of a transaction

### ISSUE THREAD

**Issue by tejeswarm** [citusdata/citus#6079]
In a single coordinator environment

CREATE TABLE test (id int, nonid int);
SELECT create_distributed_table('test', 'id', colocate_with := 'none');
INSERT INTO test  select  generate_series(6, 10000, 1), 0;

CREATE or REPLACE function foo()
returns setof test
AS $$
BEGIN
RETURN query select * from test order by 1 limit 10;
end;
$$ language plpgsql;

CREATE TABLE test2 (id int, nonid int);

-- Leak the relation-access in this session
select foo();

-- As we didn't reset the flag at the end of above transaction, this should fail
BEGIN;
SET LOCAL citus.multi_shard_modify_mode TO sequential;
SELECT create_distributed_table('test2', 'id', colocate_with := 'none');
END;

This fails even though we haven't done any parallel query in the explicit BEGIN-END

 ERROR:  cannot distribute "test2" in sequential mode because a parallel query was executed in this transaction
HINT:  If you have manually set citus.multi_shard_modify_mode to 'sequential', try with 'parallel' option.

**Comment by onderkalaci** [comment]
Which citus version is this? Might be solved by https://github.com/citusdata/citus/pull/5653 on Citus 11.

**Comment by tejeswarm** [comment]
> Which citus version is this? Might be solved by #5653 on Citus 11.

@onderkalaci  This is from [release-11.0]

**Comment by onderkalaci** [comment]
> In a single coordinator environment

Ah, missed this one, now reproduced it locally. 

I think I can fix this quickly because found out what is happening. Basically, we tied resetting RelationAccessHash to connection resets, probably pre-dating local execution times. Nowadays, it should be in a more generic place.

I'll try to open a PR and ask your review on this @tejeswarm

**Comment by tejeswarm** [comment]
Thanks @onderkalaci Yeah I tried that fix locally and it works, but felt that there are other objects, such as, ColocatedPlacementsHash that needs to be checked if we are missing something. Please go ahead with the fix.
