### ISSUE TITLE
Rebalancing error after adding new node

### ISSUE THREAD

**Issue by SerhanBent** [citusdata/citus#6084]
First of all, I have set the coordinator node by executing the following query.

`SELECT citus_set_coordinator_host('192.168.1.100', 5432);`
Right after that, I have distributed my table by

`select create_distributed_table('public."Table"','distributedField')`
For citus rebalancing to make sense, we should be able to add n number of nodes and re-balance our data to those added nodes. So we have executed the following query to do so.

`
`Select * from rebalance_table_shards('public."Table"');
The following errors occur every time we try to execute the query after different configurations or fixes.

`connection to the remote node localhost:5432 failed with the following error: fe_sendauth: no password supplied`
After hours of research and applying all the suggested solutions, I decided to create a new issue to discuss about it.

The system details and configuration files are below.
OS: Ubuntu 20.04.4 LTS

Citus Version : 11.0-2

DB: PostgreSQL 14.4 (Ubuntu 14.4-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit

pg_hba.conf file content :

```
local   all             postgres                                peer

local   all             all                                     peer

host    all             all             127.0.0.1/32            scram-sha-256

host    all             all             ::1/128                 scram-sha-256

local   replication     all                                     peer
host    replication     all             127.0.0.1/32            scram-sha-256
host    replication     all             ::1/128                 scram-sha-256
host    all             all             192.0.0.0/8             trust

host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust
host    all             all             192.168.1.101/32        trust
```

**Comment by onderkalaci** [comment]
Hi @SerhanBent,

This topic has been discussed several times on the slack channel: https://app.slack.com/client/T0XRK61LP/search/search-eyJkIjoiZmVfc2VuZGF1dGglM0ElMjBubyUyMHBhc3N3b3JkJTIwc3VwcGxpZWQiLCJxIjoiVTAzQkNDQzFFNUMiLCJyIjoiZmVfc2VuZGF1dGglM0ElMjBubyUyMHBhc3N3b3JkJTIwc3VwcGxpZWQifQ==/thread/C0XRHT1KJ-1640318608.205900

Does this help?

**Comment by onderkalaci** [comment]
> Our "pg_hba.conf" is OK. We got all lines in "pg_hba_file_rules" table.

An answer that might help you from Slack:
```
 The rebalancer connects to localhost and it seems you don't allow that in pg_hba.conf without a password. There's a few ways you could solve this:
- add an entry for localhost to your .pgpass file, with the password for localhost
- add an entry to pg_hba.conf to allow passwordless logins from localhost, by using trust authentication
- If you are on Citus 10.1 or higher, you can set citus.local_hostname to something that currently is in your pg_hba.conf file. It will then connect to the hostname/IP that you specify there instead of to localhost: https://docs.citusdata.com/en/v10.2/develop/api_guc.html#citus-local-hostname-text
```

Also, note that pg_hba.conf follows: `The first record with a matching connection type, client address, requested database, and user name is used to perform authentication.

So, put `trust` for localhost above could help

**Comment by SerhanBent** [comment]
I have solved the problem by applying the following steps,

- moving  trust lines above the scram lines in pg_hba.conf,
- defining a primary key for the distributed table and
- setting wal_level=logical in the postgresql.conf

then my table have been successfully rebalanced now.

Thank you for your cooperation. I hope others with similar problems would benefit from this solution.
