### ISSUE TITLE
Queries that copy large volumes of data to the master node may error out

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#613]
I'm opening this issue to track and reproduce the problem mentioned in this Slack conversation:  https://citus-public.slack.com/archives/general/p1466187776000304

The issue seems to be that when the master node needs to copy large volumes of data, it may error out. A few data points to help reproduce this issue on our part:
- The user has a table that has 5GB of data. 8M rows.
- The table has 16 shards, 2 replicas, spread across 3 worker nodes.
- When the user runs `SELECT * FROM my_table LIMIT 10;` or `SELECT count(*) FROM my_table`, everything works just fine.

When the user runs `SELECT * FROM my_table;`, the following messages show up on the master node:

<pre>
WARNING:  01000: could not read data from worker node
LOCATION:  MultiClientCopyData, multi_client_executor.c:624
WARNING:  01000: could not read data from worker node
LOCATION:  MultiClientCopyData, multi_client_executor.c:624
ERROR:  XX000: failed to execute job 45
DETAIL:  Failure due to failed task 20
</pre>

The following error messages show up on the worker node:

<pre>
STATEMENT:  COPY (SELECT <COLUMNS> FROM <mytable>_102065 WHERE true)
FATAL:  connection to client lost
</pre>

The warning message on the master node comes from the following code segment. PQconsumeInput()'s documentation is here: https://www.postgresql.org/docs/current/static/libpq-async.html

<pre>
    /*
     * Consume input to handle the case where previous copy operation might have
     * received zero bytes.
     */
    consumed = PQconsumeInput(connection);
    if (consumed == 0)
    {
        ereport(WARNING, (errmsg("could not read data from worker node")));
        return CLIENT_COPY_FAILED;
    }
</pre>

As a first step, let's look to reproduce the issue on our end. @fawad (on Slack) has been pretty helpful in gathering this data from his end.

**Comment by fhalim** [comment]
FWIW, I tried recreating the table with more shards but I still get the same error message trying to read from that table.

**Comment by saicitus** [comment]
@fhalim: Could you provide details on the setup (RAM and number of CPU cores) of the master and workers.

**Comment by fhalim** [comment]
@saicitus The master has 1 core and 2 GB of memory. The 3 workers have 2 cores and 8GB of memory each. All nodes are running the public citusdb 5.1 docker image backed by EBS volumes with plenty of IOPS.

**Comment by marcocitus** [comment]
This has no been observed in the last few years with the new executor.
