### ISSUE TITLE
Wrong version number in the control file for tag 11.0.5

### ISSUE THREAD

**Issue by gelias** [citusdata/citus#6160]
Hi everyone! 

Congratulations for the release 11.0.5(tag v11.0.5)! 

We believe (https://stackgres.io team) have found a tiny detail, maybe was forgotten in this release. Inside the [control file](https://github.com/citusdata/citus/blob/v11.0.5/src/backend/distributed/citus.control) the `default_version` property still with the old value `11.0-4` instead of `11.0-5`

<img width="416" alt="image" src="https://user-images.githubusercontent.com/379981/184003346-95c90850-311c-414c-8a78-560955bc9982.png">

```
❯ kubectl exec -it teste-ext-0 -c patroni -- psql
psql (14.4 OnGres Inc.)
Type "help" for help.

postgres=# select * from pg_available_extensions;
        name        | default_version | installed_version |                                comment                                 
--------------------+-----------------+-------------------+------------------------------------------------------------------------
 dblink             | 1.2             | 1.2               | connect to other PostgreSQL databases from within a database
 pg_stat_statements | 1.9             |                   | track planning and execution statistics of all SQL statements executed
 plpgsql            | 1.0             | 1.0               | PL/pgSQL procedural language
 plpython3u         | 1.0             | 1.0               | PL/Python3U untrusted procedural language
 citus              | 11.0-4          |                   | Citus distributed database
(5 rows)
```

The same thing for version 10.2.4(tag 1.0.2.4). This could be a problem in some cases and some users!

Please let me know if this makes sense, so I can submit the MR tweaking it.
Thanks in advance!

**Comment by gledis69** [comment]
While this is admittedly a bit confusing, this is actually correct.
A similar issue arose before: https://github.com/citusdata/citus/issues/6068
The user facing citus version can be displayed with `SELECT citus_version();`.
The `11.0-4` is used by us to keep track of changes in the schema, and is not necessarily tightly coupled with the user facing citus version.

**Comment by gelias** [comment]
Thanks for clarifying this @gledis69
