### ISSUE TITLE
Citus doesn't compile on assert enabled 9.4 

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#619]
fd1b088208ca48d88ed6520df7023330bdee1461 references PG_UINT32_MAX, which doesn't exist < 9.5.

**Comment by anarazel** [comment]
Furthermore it's debatable whether the use of assert is a good idea here.

**Comment by jasonmp85** [comment]
This is a pretty big edge case at any rate. Replacing with `0xFFFFFFFF` and calling it a day.
