### ISSUE TITLE
Improve DROP TABLE performance for large shared buffers

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#620]
(copy / pasting from internal email thread)

We earlier today observed that DROP TABLE was rather slow on a user's setup -- as in 90s and more for a distributed relation.  Part of that is caused by the relatively high number of shards due to the high number of available cores (~300 total cores); but 90s was more than what could be explained by that.

That's rather annoying because it means just re-initializing the test-setup consisting of several tables  takes a fair amount of time.  It'll likely also be a noticeable factor in how long data ingest/ETL process takes, as we'll probably want to create / empty a number of tables.

I'm rather sure that the reason for this is that the workers have all a high shared memory setting, and used all of that shared memory when we issued the DROP TABLE for a shard on the worker. Part of the work DROP TABLE has to do is to remove all pages for that relation from `shared_buffers`. Postgres currently has to do so by searching shared buffers sequentially (cf. DropRelFileNodeBuffers()). This user uses 64GB of shared buffers per node.

On my laptop, with three workers, dropping a table with 300 shards takes:

512 MB shared-buffers: 5408.331 ms
8 GB shared buffers:   7153.198 ms
16 GB shared buffers:  12335.333 ms

And that's without those buffers actually being filled.

Postgres has an optimization that shared buffers are only searched once when several tables are dropped at once / within one transaction (cf. `DropRelFileNodesAllBuffers()`).  It looks fairly easy to do that in `master_drop_all_shards()`: just construct DROP TABLE IF EXISTS shard_1, shard_2, ...; for each worker; or even more radically, build one list and send it to each of the affected workers.

**Comment by marcocitus** [comment]
Shard placements are now typically dropped in a single transaction per worker. Dropping a table with 300 shards with 8GB shared_buffers takes <500ms on my desktop.
