### ISSUE TITLE
Citus 11 favors parallel seq scan?

### ISSUE THREAD

**Issue by kojoa** [citusdata/citus#6218]
I was benchmarking Citus for a use case with approximately 3 billion rows dataset.
For some reason, Citus seems to favor doing parallel seq scan (and reading data from disk) instead of using index that is perfect fit for the query and can easily fit into memory. On top of that, behaviour seems quite random as mildly tweaking query parameters, Citus uses the index?

Consider table structure like this:

```
CREATE TABLE events (
    device integer NOT NULL,
    time timestamp with time zone not null,
    event integer not null
)
```

which is distributed by the device-column and 3bn rows loaded from CSV-files.
After that index is created:

```CREATE INDEX events_device_time_event ON events (device, time, event)```

After that `ANALYZE` is run on the table.

then running query 1 for small subset of the data:

```
 select event, count(*) from events where device in (22515, 22516, 22984, 22985, 22986, 22988, ...
)
and time > '2020-01-01'
group by 1
```

Will produce results:

```
3	12728757
0	3589442
2	3624335
1	1543035

Execution time 200ms
```

And plan confirms that index was used:

```
HashAggregate (cost=500.00..503.50 rows=200 width=12)
Group Key: remote_scan.event
-> Custom Scan (Citus Adaptive) (cost=0.00..0.00 rows=100000 width=12)
Task Count: 32
Tasks Shown: One of 32
-> Task
Node: host=10.100.1.7 port=5432 dbname=postgres
-> HashAggregate (cost=1885994.96..1885995.00 rows=4 width=12)
Group Key: event
-> Index Only Scan using events_device_time_event_106404 on events_106404 events (cost=0.57.1867423.99 rows=3714193 width=4)
Index Cond: ((device = ANY ('(22515,22516,22984,22985,22986,22988,.. }':integer ])) AND ("time" > '2020-01-01 00:00:00+00'timestamp with time zone)) 
```

Then query number 2 with only difference in time-filter 1 month earlier:

```
 select event, count(*) from events where device in (

             22515, 22516, 22984, 22985, 22986, 22988, …
)
and time > '2019-12-01'
group by 1
```

with results:

```
3	13400561
0	3813905
2	3818781
1	1643497

Execution time 77 seconds
```

and plan:

```
HashAggregate(cost=500.00..603.60 rows=200 width=12)
Group Key: remote_scan.event
-> Custom Scan (Citus Adaptive) (cost=0.00.0.00 rows=100000 width=12)
Task Count: 32
Tasks Shown: One of 32
-> Task
Node: host=10.100.1.7 port=5432 dbname=postgres
-> Finalize GroupAggregate (cost=2020679.17..2020680.18 rows=4 width=12)
Group key: event
Merge (cost=2020679.17..2020680.10 rows=8 width=12
Workers Planned:
-> Sort (cost=2019679.15..2019679.16 rows=4 width=12)
Sort Key: event
-> Partial HashAggregate (cost=2019679.07 2019679.11 rows=4 width=12)
Group Key: event
Parallel Seq Scan on events_106404 events (cost=1.59..2011002.28 rows=1735357 width=4)
Filter: (("time" > '2019-12-01 00:00:00+00':timestamp with time zone) AND (device = ANY ('(22515,22516,22984,22985,22986,22988,.. }':integer)
```

Trying different parameters, the behaviour seems quite random and unpredictable. Can't work with query times all over the place 😢 

With vanilla Postgres, following tricks could be used:
 - use planner hints, like: `set enable_seqscan=0; set enable_indexonlyscan=1;`
 - tweak statistics and analyze
 - change cost values to bigger values (random_page_cost, seq_page_cost)
 - tweak memory settings
 - partition table
 
 Nothing above seems to have any effect.
 
 Some details on the setup. Running on 7 EC2 instances (c6i.4xlarge). 1 Coordinator, 6 workers.
 Data is spread quite evenly by devices and time spanning from 2012 to 2022.
 Setup has been done based on the official Citus 11 documents for Ubuntu installation.
 No tweaks to OS has been done so far.
 Initial tests done with default Postgres 14 settings.
 Later tried tweaking shared_buffers and other memory settings suggested in Postgres documents.
 
 Confirmed by running queries that index is in memory. Whenever index is hit, no noticable disk IO happens.
 
 Also, comparing this to other system running on Greemplum 6 (Postgres 9.4) with exactly same hardware,
 the index is always used and query speed is consistent.
 
 Going to run same experiment on Postgres 14 bit later.
 
 This is blocking our evaluation of the product usage, as we can't get past simple data-aggregation queries.
 
 Have been reading the documentation but can't find anything that would help Citus to use that index.
 Any ideas how to get Citus to use the index?
 
 Sorry for the long post and thanks for reading.

**Comment by kojoa** [comment]
Just realized, that I tried some of the setting tweaks by passing them as session parameters. Is it so then, that Citus won't pass those session settings from coordinator planner to the planner in other instances?

**Comment by onderkalaci** [comment]
> Just realized, that I tried some of the setting tweaks by passing them as session parameters. Is it so then, that Citus won't pass those session settings from coordinator planner to the planner in other instances?

Yes, the way to pass those is via https://docs.citusdata.com/en/v11.0/develop/api_guc.html?highlight=propagate#citus-propagate-set-commands-enum


You should do something like:
```SQL
SET citus.propagate_set_commands  TO local ;

BEGIN; 
SET LOCAL enable_seqscan TO false;
SELECT ...
````


> Any ideas how to get Citus to use the index?

Citus doesn't interfere how Citus does planning on the shard queries. So, my initial reaction would be try to optimize the same query to use indexes on local tables, maybe even manually try the same queries on the shards. (ps: If you do `SET citus.log_remote_commands TO ON`, you can see all the queries sent to the shards)

**Comment by grin31** [comment]
@kojoa 
Please try to increase to max per-column statistics target for each column `events` table and gather statistics again.
`ALTER TABLE <name> ALTER <column_name> SET STATISTICS 10000`

**Comment by kojoa** [comment]
I managed to get this working by tweaking COST settings directly in shards config files. Thank you both for comments.
