### ISSUE TITLE
Deprecate csql

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#622]
We added native COPY support for data ingestion, and this removes the motivation for having a separate ``\stage`` command. Once we deprecate ``\stage`` (tracked in #590), we should look to remove csql and all related Makefile and regression test dependencies.

**Comment by ozgune** [comment]
I'm adding the v5.3 milestone assuming that this is a quick fix.

**Comment by lithp** [comment]
By deprecate do you mean remove or emit an error message at startup?

**Comment by lithp** [comment]
Or maybe replace with a binary that prints "you can use sql now", and remove that binary in 5.4?

**Comment by lithp** [comment]
This might be blocked on https://github.com/citusdata/citus/issues/632. Our tests rely on being able to \stage into a distributed foreign table (file_fdw), and COPY into foreign tables doesn't seem to be supported.

**Comment by lithp** [comment]
After looking into it some more, I can fix the test by creating the shards "manually" but it makes me question whether we want to remove stage, do we have anybody still using file_fdw that we're leaving behind? @ozgune

**Comment by jasonmp85** [comment]
@lithp I brought all this up last week when doing the PR for #630. I think we're (a) OK entirely removing csql, and (b) don't have any `file_fdw` users to worry about. I could be wrong, though.

**Comment by ozgune** [comment]
@lithp -- I'm cool with removing multi_fdw tests too.

I'm noting #98 and #325 as issues related to file_fdw and regression tests. It may be worth looking at them. I'm also documenting #506 to see if it's documented in any way.

Last, if we remove these tests, are we officially dropping support for file_fdw related code paths? If so, could we open up an issue to remove related code? I know that we special-cased how we propagate ``CREATE SERVER`` and ``CREATE FOREIGN TABLE`` commands. We currently track this logic in #376.

**Comment by mtuncer** [comment]
I agree that multi_fdw is not used much and could be removed. 

However, we are adding more cstore specific code to citus with each release.  I saw lot's of not covered code while examining coverage logs yesterday.

Perhaps we should replace multi_fdw with multi_cstore type of tests. We could exclude this test from check-full as we did for hll tests.
