### ISSUE TITLE
Add Support for Renaming Columns for Distributed Tables

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#633]
Currently, we do not support renaming distributed tables or their objects, which is a requested feature. 

We error out with the following message:

```
postgres=# ALTER TABLE test_keyval RENAME COLUMN val TO value;
ERROR:  renaming distributed tables or their objects is currently unsupported
```

@samay-sharma noted that merging #618 would make it easier to add support for renaming distributed tables and their columns. We already capture RENAME statements so adding support for it should also be pretty straight-forward.

This issue can be tracked under #25 (DDL Propagation v2).

**Comment by ozgune** [comment]
We also recently heard about this as a feature request in citus-users: https://groups.google.com/forum/#!topic/citus-users/GFWcUXeq78U

**Comment by sumedhpathak** [comment]
Updated title to only add support for renaming of columns in distributed tables. For 6.2 we've only prioritized renaming of columns, and not the tables themselves. That is captured in a different issue: https://github.com/citusdata/citus/issues/1249
