### ISSUE TITLE
Evaluate shard caching code in broadcast joins

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#638]
When Citus joins a large table against smaller tables, it applies broadcast joins.

We currently provide users two options in setting up smaller tables. In one of those approaches, Citus keeps the smaller table on a subset of the machines, and at query time, asks the other worker nodes to cache the data.

We originally designed the shard caching and refetching logic with append-type workloads in mind. With 5.0 however, users can also `INSERT` or `UPDATE` into those smaller tables and those commands don't update the shard size on the master node.

Therefore, we don't need the following code path anymore (also checked this with existing customers): https://github.com/citusdata/citus/blob/master/src/backend/distributed/worker/worker_data_fetch_protocol.c#L510

**Comment by ozgune** [comment]
I'm also noting #594 as a semi-related issue.

**Comment by marcocitus** [comment]
> Therefore, we don't need the following code path anymore (also checked this with existing customers)
> https://github.com/citusdata/citus/blob/master/src/backend/distributed/worker/worker_data_fetch_protocol.c#L510

We also use this particular function for copying shards around (e.g. shard rebalancer,  adding a reference table to a new node), but we can stop using it for broadcast joins.

**Comment by velioglu** [comment]
We have removed shard data fetch logic by #1915
