### ISSUE TITLE
Rebalancer might try using logical replication when replicating a reference table that doesn't have a primary key

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#6384]
```sql
SET citus.replicate_reference_tables_on_activate TO off;

CREATE TABLE ref_table(a int);
SELECT create_reference_table('ref_table');

SELECT citus_add_node('localhost', 10701);

SELECT rebalance_table_shards();
NOTICE:  replicating reference table 'ref_table' to localhost:10701 ...
ERROR:  cannot use logical replication to transfer shards of the relation ref_table since it doesn't have a REPLICA IDENTITY or PRIMARY KEY
DETAIL:  UPDATE and DELETE commands on the shard will error out during logical replication unless there is a REPLICA IDENTITY or PRIMARY KEY.
HINT:  If you wish to continue without a replica identity set the shard_transfer_mode to 'force_logical' or 'block_writes'.
CONTEXT:  while executing command on localhost:10700
```

I would expect this to automatically chose `block_writes` mode because reference table doesn't have a primary key; though this would cause rebalance operation to block writes for distributed tables etc., so maybe this is a design choice ?

**Comment by onurctirtir** [comment]
Talked to @onderkalaci and learnt that this is a design choice, meaning that the caller either needs to specify block_writes or force_logical.

**Comment by onurctirtir** [comment]
Or maybe we should automatically switch to 'block_writes' mode by emitting a warning ?

**Comment by tejeswarm** [comment]
> Or maybe we should automatically switch to 'block_writes' mode by emitting a warning ?

I wouldn't recommend that, by setting the value explicitly, users will know what they are signing up for.

**Comment by onderkalaci** [comment]
> Rebalancer incorrectly tries using logical replication when replicating reference tables

I wouldn't call this "incorrectly", this is how the API is designed. I think we are just following what shard rebalancer does. If you try to rebalance_table_shards() with no pkeys, you get the same error.

For PG 16, I'm working on a [PG patch](https://www.postgresql.org/message-id/flat/CACawEhVujhCCsrDhNHPLfHr7tWzkj-Ar8q41%2BuQ%2B4DFjJKknYw%40mail.gmail.com#b15cd77be43527246da0cb36944545f4) where we can use any index for this purposes. If that patch lands, we can use an existing index (or create on the fly to highest cardinality column).

Though, open for discussion what the behavior should be for now. cc'ing @mulander for visibility.

**Comment by mulander** [comment]
I think the current behavior mimicking what we have for rebalance_table_shards() is correct and as Teja mentioned, it is better to have the user be explicit here. The user already has a way to retry the operation providing a `shard_transfer_mode` to `citus_rebalance_start()`.

The PG patch that @onderkalaci mentioned is our target solution and with that I consider that we can close down this issue.
