### ISSUE TITLE
Creating shards *after* loading data into table does not send the data to shards

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus#641]
I created a table and `\copy`'d values into it. Then I ran `master_create_distributed_table` and `master_create_worker_shards` on the table. Citus didn't give me an error so I assumed the existing data had been sent to the shards. However connecting to a worker and inspecting it showed that no data had been copied. If this is the intended behavior it would be helpful if Citus could raise an error or warning telling me it detected existing data but is not distributing it.

I'm creating this github issue because @samay-sharma said he's noticed that this has confused other new users as well.

**Comment by ozgune** [comment]
@begriffs -- I think this issue is related to #510.

If you think they are the same issue, what do you think about copy/pasting this issue's content into #510 and closing this one out?

**Comment by begriffs** [comment]
You're right, this is a duplicate issue. Closing.
