### ISSUE TITLE
Citus crashes on prepared insert query if the partition column is parameterized

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#645]
Here is how to replicate the problem. At the 6th execution, it crashes.

```sql
CREATE TABLE articles_hash (
    id bigint NOT NULL,
    author_id bigint NOT NULL,
    title varchar(20) NOT NULL,
    word_count integer
);

SELECT master_create_distributed_table('articles_hash', 'author_id', 'hash');
SELECT master_create_worker_shards('articles_hash', 2, 2);

PREPARE prepared_statement_insert(bigint, bigint, varchar(20), integer) AS
INSERT INTO articles_hash VALUES ($1,  $2, $3, $4);

EXECUTE prepared_statement_insert( 1,  1, 'arsenous', 9572);
EXECUTE prepared_statement_insert( 1,  1, 'arsenous', 9572);
EXECUTE prepared_statement_insert( 1,  1, 'arsenous', 9572);
EXECUTE prepared_statement_insert( 1,  1, 'arsenous', 9572);
EXECUTE prepared_statement_insert( 1,  1, 'arsenous', 9572);
EXECUTE prepared_statement_insert( 1,  1, 'arsenous', 9572);

```

Assert in ExtractInsertPartitionValue() fails.
https://github.com/citusdata/citus/blob/master/src/backend/distributed/planner/multi_router_planner.c#L748
```
Assert(IsA(targetEntry->expr, Const));
```

Replacing the Assert with an error message should be fine. We have an issue (#306) for prepared statement support, but we should not leave a code path that crashes.

**Comment by ozgune** [comment]
@metdos -- @anarazel noted that this issue has been fixed by @lithp's recent changes.

Could you check with Brian to see how we can incorporate your regression tests into master?

**Comment by anarazel** [comment]
On 2016-07-15 11:16:39 -0700, Ozgun Erdogan wrote:
> @metdos -- @anarazel noted that this issue has been fixed by @lithp's recent changes.
> 
> Could you check with Brian to see how we can incorporate your regression tests into master?

The changes currently are part of the router parametrized prepare PR.

**Comment by metdos** [comment]
Fixed with this;
https://github.com/citusdata/citus/blame/master/src/backend/distributed/planner/multi_router_planner.c#L308

PR #649 will add regression tests.
