### ISSUE TITLE
The broken CONCURRENTLY INDEX cant DROP

### ISSUE THREAD

**Issue by hisahin** [citusdata/citus#6457]
PG version: 14.4
Citus version: 11.0.6

I interrupted when creating index with councurrently. But after i couldnt drop this incomplete index. Because deletion is complete in workers.
Give me this error:
                drop index indexname;
ERROR:  index "indexname" does not exist
CONTEXT:  while executing command on nodehostname:5414

**Comment by onurctirtir** [comment]
Using `drop index if exists indexname` should help. Please re-open the issue if this doesn't help, thank you.

**Comment by hisahin** [comment]
Thanks Onur. This worked for me.
