### ISSUE TITLE
Cannot add node as a worker when the data directory is copied from coordinator

### ISSUE THREAD

**Issue by lamhktommy** [citusdata/citus#6478]
```
postgres=# SELECT * from citus_add_node('10.0.2.155', 5432);
ERROR:  Node cannot add itself as a worker.
HINT:  Add the node as a coordinator by using: SELECT citus_set_coordinator_host('10.0.2.155', 5432);
```
while i have run citus_set_coordinator_host() for another ip address
citus version: v11.1
postgresql version: 14

**Comment by onurctirtir** [comment]
I couldn't quite understand the problem here. Is it the error that looks unexpected to you, or something else ?

Are you trying to add '10.0.2.155':5432 as a worker node ? And, on which postgres server are you running this command ?

**Comment by lamhktommy** [comment]
yes, I am trying to add '10.0.2.155':5432 as a worker node. And the command is run in the coordinator node. 
Actually, I am following the tutorial here https://docs.citusdata.com/en/v11.1/installation/multi_node_debian.html and it turns out return error when I run add node

**Comment by onurctirtir** [comment]
Could you share output of following from both nodes (coordinator and worker(s)) ?
```sql
SELECT * FROM pg_dist_node;
SELECT * FROM pg_dist_node_metadata;
```

**Comment by lamhktommy** [comment]
`SELECT * FROM pg_dist_node;`
![image](https://user-images.githubusercontent.com/35717697/200857601-82a7edeb-6812-4c99-b775-339f7dd9a25e.png)
`SELECT * FROM pg_dist_node_metadata;` 
![image](https://user-images.githubusercontent.com/35717697/200857841-4186f435-100d-4f00-9051-3a0b3559e242.png)

**Comment by onurctirtir** [comment]
Could you also please the same for worker node ?

**Comment by onurctirtir** [comment]
> `SELECT * FROM pg_dist_node;` ![image](https://user-images.githubusercontent.com/35717697/200857601-82a7edeb-6812-4c99-b775-339f7dd9a25e.png) `SELECT * FROM pg_dist_node_metadata;` ![image](https://user-images.githubusercontent.com/35717697/200857841-4186f435-100d-4f00-9051-3a0b3559e242.png)

Also, what is the hostadress of this node (coordinator) ?

**Comment by lamhktommy** [comment]
worker node generates the same output (with the same server id also). My address for coordinator is 10.0.2.157

**Comment by bluefishcc** [comment]
I was also got this problem and solved it with execute `drop extension citus;` and `create extension citus;` again in the worker node.

**Comment by onurctirtir** [comment]
> worker node generates the same output (with the same server id also). My address for coordinator is 10.0.2.157

Are server_id's end-to-end same or do they differ by some bytes ?

**Comment by lamhktommy** [comment]
@onurctirtir the server id are the same. BTW I have create another database in both coordinator node and worker node and it works when I run add node function

**Comment by onurctirtir** [comment]
Got it. I'm still trying to understand how the same "server_id" could have been assigned to those two nodes, so let me ask a few more questions:

1) How did you create data directories for those two servers ? Did you run `initdb` once and copied the data directory to other node, or did you run separate `initdb` commands ?
2) Or if those nodes are served on virtual machines, are they copy of each other ?

Or in other words, if you forked data directory --either by simply copying data directory or by forking the vm-- after creating citus extension, then it would be normal to see them sharing the same server_id. In that case, workaround would be to update `server_id` of one of those nodes by using:
```sql
UPDATE pg_dist_node_metadata SET metadata = jsonb_set(metadata, '{server_id}', to_jsonb(citus_server_id()));
```

**Comment by lamhktommy** [comment]
For 1, I havent run `initdb`. I assume when i start the postgresql service the postgres database is automatically created.
For 2, I created 3 AWS ec2 instances using terraform. It would install the packages required according to the tutorial and then run the command ```sudo -i -u postgres psql -c "CREATE EXTENSION citus;"``` in each instance. So i guess both of them are identical until i run set_coordinator_host() and add_node().

**Comment by onurctirtir** [comment]
> So i guess both of them are identical until i run set_coordinator_host() and add_node().

Yeah, apparently that is the reason why they have the same 'server_id's. That is good news since this is totally expected --although not much user friendly.

**Comment by lamhktommy** [comment]
So maybe I should create the instances with PostgreSQL setup first, and then run ```sudo -i -u postgres psql -c "CREATE EXTENSION citus;"``` separately?

**Comment by onurctirtir** [comment]
Yeah, definitely.
