### ISSUE TITLE
Check if semver extension is compatible with citus.

### ISSUE THREAD

**Issue by emelsimsek** [citusdata/citus#6486]
semver (https://pgxn.org/dist/semver) is an extension which introduces a data type called "semver".  We want to make this library available to citus users. 

This issue will cover the following scenarios:

- [x] 1. A column of semver type can be distribution column and filtering queries with various operators work properly.
        https://gist.github.com/emelsimsek/00c3ecc36d63c47688df883bcff5f4b3

- [x] 2.  Repartition joins: SELECT … FROM table JOIN table_2 USING (semver_columns)
     https://gist.github.com/emelsimsek/00c3ecc36d63c47688df883bcff5f4b3?permalink_comment_id=4366072#gistcomment-4366072

- [x] 3.  Prepared statements: PREPARE p1 (semvar) AS SELECT .. WHERE semver=$1; EXECUTE p1(…)
https://gist.github.com/emelsimsek/00c3ecc36d63c47688df883bcff5f4b3?permalink_comment_id=4366153#gistcomment-4366153

- [x] 4. Columnar storage (Basic tests:  table create, insert, select )
-https://gist.github.com/emelsimsek/00c3ecc36d63c47688df883bcff5f4b3?permalink_comment_id=4366237#gistcomment-4366237

- [x] 5. GROUP BY semver; 
https://gist.github.com/emelsimsek/00c3ecc36d63c47688df883bcff5f4b3?permalink_comment_id=4364961#gistcomment-4364961

- [x] 6. SELECT count(DISTINCT semver) 
https://gist.github.com/emelsimsek/00c3ecc36d63c47688df883bcff5f4b3?permalink_comment_id=4366262#gistcomment-4366262

**Comment by onderkalaci** [comment]
Thanks for sharing all your tests!  Are we good to close the issue @emelsimsek?
