### ISSUE TITLE
Distribute Table with Generated As Identity

### ISSUE THREAD

**Issue by RichardBurns1982** [citusdata/citus#6491]
We are looking to move our Postgres databases to Azure CosmosDb and distribute tables.  All of our tables which require identity are using Generated As Identity and not Serial.

When will Citus support this as without it we cannot distribute any of our tables.  Postgres 10 introduced Generated As Identity and Serial is considered the legacy way.

Many thanks, this is blocking us from moving our production instances as without being able to distribute there is little benefit.

**Comment by marcocitus** [comment]
Related to #3187 

currently no timeline to announce, but it's definitely becoming more urgent

**Comment by naisila** [comment]
Thanks to @gokhangulbiz we now support the following with tables that have identity columns:
- `create_distributed_table()`
- `create_reference_table()`
- `citus_add_local_table_to_metadata()`
- `alter_distributed_table()`
- `undistribute_table()`
- `ALTER TABLE ... ADD COLUMN ... GENERATED {BY DEFAULT | ALWAYS} AS IDENTITY`
