### ISSUE TITLE
Is citus ext is columnar storage or not?

### ISSUE THREAD

**Issue by lukashes** [citusdata/citus#650]
[Here](https://docs.citusdata.com/en/v5.1/reference/user_defined_functions.html?highlight=master_create_distributed_table) I read about different type of storages: 
* Table
* Columnar
* Foreign Table

I third that citus ext is column-based storage. But in my distributed tables I saw, that is `common tables`. In docs I can not find info about columnar storages. Can you help me to know about storage?

**Comment by aamederen** [comment]
Hey @lukashes 

Citus is not columnar itself. However, there is an extension called [cstore_fdw](https://github.com/citusdata/cstore_fdw), which adds columnar store capabilites to PostgreSQL and you can use Citus with it.

**Comment by lithp** [comment]
@lukashes Also, for questions about Citus, you're likely to get a faster answer if you email citus-users@googlegroups.com :) Going to close this issue, feel free to email that group if aamederen didn't fully answer your question!
