### ISSUE TITLE
Parameterize supported postgres versions in configure.ac

### ISSUE THREAD

**Issue by gurkanindibay** [citusdata/citus#6500]
Currently, postgres versions in configure.ac is hard-coded, which denotes supported postgres versions of the current source.Supported postgres versions are also being used newly introduced pipeline packaging-test.yml. Therefore, it is duplicated now. We can centralize this parameter so that both can get the supported versions from the same place.

**Comment by onurctirtir** [comment]
> Therefore, it is duplicated now.

It's not yet duplicated as we didn't yet agree on the design / the PR has not been merged in yet; but we can re-open this issue as needed.
