### ISSUE TITLE
remote connection citus

### ISSUE THREAD

**Issue by rahul-chawla** [citusdata/citus#6562]
i am new in citus can anyone help me to resolve this issue 
i have using single node citus my coordinator node running on 9700 and my postgressql running on 5432  i don't know how i can  remote connect my  citus coordinate node i am trying its give tcp ip connection not enabled how can i enable it

**Comment by onderkalaci** [comment]
Hi, please use the slack channel for these types of questions. We aim to use Github for feature requests and bug reports
