### ISSUE TITLE
Duplicate shards when a tx block with a move is aborted

### ISSUE THREAD

**Issue by agedemenli** [citusdata/citus#6580]
When we move a shard in a transaction block, there remains a shard on the target when transaction is aborted.

```sql
create table t1 (a int primary key);
select create_distributed_table('t1','a');
begin;
select citus_move_shard_placement(102008,'localhost',9701,'localhost',9702);
abort;
SELECT run_command_on_workers($$select count(*) from pg_class where relname like 't1_102008'$$);
┌────────────────────────┐
│ run_command_on_workers │
├────────────────────────┤
│ (localhost,9701,t,1)   │
│ (localhost,9702,t,1)   │
└────────────────────────┘
(2 rows)
```

And there is no cleanup record for it:
```sql
table pg_dist_cleanup;
┌───────────┬──────────────┬─────────────┬─────────────┬───────────────┬─────────────┐
│ record_id │ operation_id │ object_type │ object_name │ node_group_id │ policy_type │
├───────────┼──────────────┼─────────────┼─────────────┼───────────────┼─────────────┤
└───────────┴──────────────┴─────────────┴─────────────┴───────────────┴─────────────┘
(0 rows)
```

**Comment by JelteF** [comment]
Does this reproduce on the main branch? How about the latest release? If so this seems like a pretty serious bug.

**Comment by agedemenli** [comment]
It does reproduce on both main and v11.1.5

**Comment by agedemenli** [comment]
It's because we send the table creation commands to the worker OUTSIDE transaction. Whether the actual transaction with the move command is committed or aborted, the table remains there on the target.
see: https://github.com/citusdata/citus/blob/main/src/backend/distributed/operations/shard_transfer.c#L1199-L1208

I see no data loss here. The metadata is healthy as well. pg_dist_placement still points to the source node for that shard, which is correct. So it doesn't look that bad for now.

Potential problems are:
* It could cause unexpected errors like "relation .. already exists" when a user tries to move that shard
* It could cause unexpected errors when rebalancing, for the same reason
* It could cause unexpected errors if the user tries to do some manual operations on shards

**Comment by marcocitus** [comment]
>  How about the latest release? If so this seems like a pretty serious bug.

This was always the case. We only dropped orphaned shard placements when repeating the move. The cleanup framework allows us to insert CLEANUP_ON_FAILURE records for the new shard placement, but so far this is only done for splits so far.
