### ISSUE TITLE
Support function-delimited transaction blocks

### ISSUE THREAD

**Issue by jasonmp85** [citusdata/citus#659]
As part of #627, @anarazel and I discussed methods to detect transactions initiated as part of a function. The core of the problem is that `IsTransactionBlock` (which is how that PR detects transactions) will only return `true` if the session is literally within a lexical transaction block (i.e. between a `BEGIN` and a `COMMIT`). Since functions automatically take part in the snapshot of the command that runs them, a simple one-line call to a function _should_ take part in a transaction even if no `BEGIN`/`END` wraps it.

@anarazel found a way to detect this: simply look at the `queryDesc->dest` `CommandType`. If it is _not_ anything remote, it means we're sending results back to some sort of language handler locally rather than to an end user. By looking for this (in addition to `IsTransactionBlock`) we could cover both the `BEGIN`\- and function-triggered cases. However…

It turns out some customers _already_ use modification commands within a function. Previously (i.e. `pg_shard`) we detected and rejected modification commands within a transaction block (as we could not apply them atomically), but did _not_ make use of the above logic to detect functions. So customers used this as a workaround to have "multi-statement" calls (even if not atomic). Adding the correct transactional semantics to function calls would break all their code.

That said, we might still want to add transaction handling to function calls. By providing a GUC, we could permit existing customers to opt-out of this handling, so they could continue to have functions which modify many shards in one call (perhaps even on a per-function level).

We didn't want this to block #627, but are noting it here for future prioritization.

**Comment by jasonmp85** [comment]
@ozgune asked me to list our options here. My TODO says "write down the four options for function handling", but I'm not sure I can remember more than three (oh, well). So I'll try to flesh out what I can remember discussing.

# Do Nothing

We can just leave things as-is, possibly adding a warning so customers know our new transactional behavior does _not_ apply within functions, which are generally regarded as transactional blocks within PostgreSQL.

# Enable Function Transactions

This would give users transactional behavior, but has two downsides:

  * Some customers may already depend on non-transactional behavior
  * Others may not care one way or the other, but have functions which don't restrict themselves to a stable set of nodes (i.e. subsequent `INSERT`s, etc. will hit nodes not participating in a transaction)

If a customer, for instance, does _not_ care about transactions, it's possible they'll be bothered by new errors preventing them from using the functions they wrote that perform modifications across many nodes. This leads to:

# Add GUC for Transactional Functions

We could simply add a GUC to permit users to opt out of transactional functions. Yet another GUC isn't wonderful, but in the context of functions they can be pretty seamless. In particular, [`CREATE FUNCTION`'s `SET` clause](https://www.postgresql.org/docs/9.5/static/sql-createfunction.html) makes it easy to auto-set and unset a variable when entering/exiting a function, respectively.

# Upgrade to Two-Phase Commit–Based Transactions

This is a more general solution, and would have to be something we add at the transaction-handling level (and might be best implemented during the unification of our connection- and transaction-handling APIs), but the essence is we'd _always_ give users transactional functions. If they happen to expand the transaction participant list during a transaction, we'll just switch to two-phase commit behavior for better atomicity.

**Comment by lithp** [comment]
@jasonmp85 Re: customers who are relying on non-atomic functions for running multi-statement transactions, do you know if their use-case is covered by your PR supporting such?

**Comment by jasonmp85** [comment]
> do you know if their use-case is covered by your PR supporting such?

If you're asking whether their function can be replaced with `BEGIN`/`END`-delimited blocks… I don't think so. The customer in mind (ask @samay-sharma over email) just hits a ton of shards in a function with no consideration as to whether the function spans shards.

**Comment by lithp** [comment]
For future reference: #731 has a concrete example of what this means.

**Comment by lithp** [comment]
Added [an issue](https://github.com/citusdata/citus_docs/issues/142) for documenting this behavior.

**Comment by marcocitus** [comment]
@jasonmp85 is this still relevant? If so, should we fix it?

**Comment by jasonmp85** [comment]
@marcocitus it's still relevant, but might not be possible to fix entirely yet? PL/pgSQL functions can contain e.g. DDL and DML and `COPY`… are we yet at a point where all three can be interleaved within a single transaction block?

As hinted at in the above, certain customers might find their previously-working functions failing if we just turn this on without fully supporting arbitrary interleavings of different command types.

What do you think the ideal scenario would be? Maybe have an opt-out GUC that legacy customers could engage and have all other functions get transactional semantics?

**Comment by marcocitus** [comment]
> are we yet at a point where all three can be interleaved within a single transaction block?

Yep. There are certain caveats such as when you run multiple DML statements over one connection and then try to run a DDL or COPY commands that requires a connection per shard placement. However, these seem like exotic cases that likely don't exist and even if they do, it's probably worth breaking them to make sure that PL/pgSQL functions are always transactional.

**Comment by jasonmp85** [comment]
> it's probably worth breaking them to make sure that PL/pgSQL functions are always transactional

Reasonable customers may disagree, though I think last time the blocker was simply a customer who had DML hitting many shards. Maybe we should just enable this, provide an opt-_out_ GUC, and see who yelps?
