### ISSUE TITLE
Rebalancing fails when owner of a table has OID greater than 2147483647

### ISSUE THREAD

**Issue by ivyazmitinov** [citusdata/citus#6598]
During the rebalncing Citus creates temporary subscriptions and roles names of which are based on the OID of the owner of a rebalanced table. Due to error in the name pattern for those subscriptions\roles, Citus may generate syntactically invalid statements, like `CREATE USER citus_shard_move_subscription_role_-1896737196 SUPERUSER IN ROLE "some-role";`.

The error lies in the `SubscriptionName` and `SubscriptionRoleName` functions:
```c
/*
 * SubscriptionName returns the name of the subscription for the given owner.
 */
char *
SubscriptionName(LogicalRepType type, Oid ownerId)
{
	return psprintf("%s%i_%lu", subscriptionPrefix[type],
					ownerId, CurrentOperationId);
}


/*
 * SubscriptionRoleName returns the name of the role used by the
 * subscription that subscribes to the tables of the given owner.
 */
char *
SubscriptionRoleName(LogicalRepType type, Oid ownerId)
{
	return psprintf("%s%i_%lu", subscriptionRolePrefix[type], ownerId,
					CurrentOperationId);
}
```

They both use the modifier `%i` for the `Oid ownerId`, which is `unsigned int`, resulting in an overflow. The correct modifier here would be `%u`.

**Comment by agedemenli** [comment]
Hi @ivyazmitinov, thank you for reporting that. I will look into it.
