### ISSUE TITLE
PurgeConnection may segfault when re-raising error

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#664]
We recently made this change https://github.com/citusdata/citus/commit/16fc92bf6b95eed0ee7e7097572b4337a27f0573

However, there are various callers to ReportRemoteError that use it on connections that are not from the connection cache (e.g. COPY, master_modify_multiple_shards, DDL), and this will segfault if the connection cache hasn't been initialized, meaning that those callers may segfault whenever there is a remote error.

**Comment by jasonmp85** [comment]
> We recently made this change 16fc92b

If I had to point to the commit that introduced this, it's d25ee8f, which changed the API to the connection cache by directly exposing the internal function `ConnectToNode`. Only when I started poking around in other places that acquired connections (i.e. during the transaction support work) did I notice this breakage…

The connection cache was supposed to provide some encapsulation of connections and most of its methods were written with that use in mind; having it also just hand out connections directly (possibly more than one to a single node!) breaks all of that encapsulation.

I suppose we can throw in a simple `NULL` check or `purge` flag parameter, but both increase the API complexity somewhat.

Long-term, we have to get _all_ of the connection and transaction stuff under one roof; right now there are several places to get connections, several ways to start transactions, and several ways of handling their failure (ignore, set health, roll back, 2PC). I think we're beginning to get to the point where refactoring all of it makes sense, but I don't think now (pre-5.2) is the best time to do it.

Adding a quick fix for this now.

**Comment by marcocitus** [comment]
> The connection cache was supposed to provide some encapsulation of connections and most of its methods were written with that use in mind; having it also just hand out connections directly (possibly more than one to a single node!) breaks all of that encapsulation.

Previously, ReportRemoteError, ConnectToNode, et al. had no dependency on NodeConnectionHash and had no side-effects, which is a nicer property to maintain. In fact, it makes it much easier to add new features without changing existing code. If we're making opaque API assumptions then we should document them, but preferably we should avoid them.

> Long-term, we have to get all of the connection and transaction stuff under one roof; right now there are several places to get connections, several ways to start transactions, and several ways of handling their failure (ignore, set health, roll back, 2PC).

Completely agree. I would like us to spend some time on this, since it's really starting to bite. 

We've started bringing some of the multi-node transaction work under one roof in the transaction/ directory. The (stateless) commit_protocol and multi_shard_transaction API's introduced for COPY have proven quite useful in adding new features such as DDL over 2PC and master_modify_multiple_shards. In MX, we've also added a worker_transaction API for metadata transactions across workers, which uses the same commit_protocol API. We also added a 2PC recovery function with almost no change to the commit_protocol API.

While working on DROP table, we found it was pretty straight-forward to rework code to use the worker_transaction API, which gives us transactional (/abortable) DROP table and master_apply_delete_command in MX:
https://github.com/citusdata/citus-mx/pull/28

Potentially, we can implement other administrative operations via this API as well.

In general, I'm not a huge fan of the MultiClient API. I find that working with libpq and stateless helper functions makes development a lot faster because API is well-documented (and Googlable) and the MultiClient API hides important information like results and errors.

The main thing I'm missing in the existing API's is the ability to queue up commands and send them in parallel in the way the real-time executor does. Ideally we could have one executor for DDL, DML and SELECTs. The existence of the router executor doesn't make that much sense. It would be very beneficial if we had a executor that could send to all shard placements in parallel and polled for results.

**Comment by jasonmp85** [comment]
> Previously, ReportRemoteError, ConnectToNode, et al. had no dependency on NodeConnectionHash and had no side-effects, which is a nicer property to maintain. In fact, it makes it much easier to add new features without changing existing code. If we're making opaque API assumptions then we should document them, but preferably we should avoid them.

I suppose as the author more of this lives in my head than it should. This is pretty heavily modeled after the `connection.c` file from `postgres_fdw`, which hands out connections from a cache, reports errors, and provides some transaction hooks. I didn't intend the reporting functionality to depend on the cache, but it kind of happened by accident once we added the ability to directly re-raise an error. Due to some negligence, I didn't even realize it was _possible_ to ask for a connection from this file without going through `GetOrEstablishConnection`.

But we're all 100% in agreement about the need for some refactoring and API polish here! Seeing other comments in other PRs to the same effect.
