### ISSUE TITLE
Issues in adding nameless constraints using existing index

### ISSUE THREAD

**Issue by naisila** [citusdata/citus#6644]
We shouldn't treat nameless constraints using existing index as "nameless" because the name of the existing index will be used.

Even if we do treat them as nameless, our deparser currently doesn't include "USING INDEX index_name" when deparsing unique/primary key constraints

Steps to reproduce:
```SQL
create table tbl (col1 int, col2 int);
select create_distributed_table('tbl', 'col1');
create unique index my_index on tbl(col1);
alter table tbl add primary key using index my_index;
```

Error:
```
alter table tbl add primary key using index my_index;
NOTICE:  ALTER TABLE / ADD CONSTRAINT USING INDEX will rename index "my_index" to "tbl_pkey"
ERROR:  syntax error at or near ")"
CONTEXT:  while executing command on localhost:9701
```

**Comment by marcocitus** [comment]
Seems we send:
```
NOTICE:  issuing ALTER TABLE tbl ADD CONSTRAINT tbl_pkey  PRIMARY KEY ();
DETAIL:  on server marco@localhost:1502 connectionId: 2
ERROR:  syntax error at or near ")"
```

**Comment by naisila** [comment]
What should be done is sending
`alter table tbl_102008 add primary key using index my_index_102008` type of commands to the shards

**Comment by naisila** [comment]
Letting `worker_apply_shard_ddl_command` handle it without deparsing the command should work

**Comment by marcocitus** [comment]
Can't we just deparse it correctly?

**Comment by naisila** [comment]
We dont need to deparse and we shouldnt deparse, because it's not really a nameless constraint: that command expects the constraint's name to be the name of the existing index.
