### ISSUE TITLE
"GRANT group_role TO my_role;" is not being propagated to worker nodes

### ISSUE THREAD

**Issue by lucasbfernandes** [citusdata/citus#6648]
**Settings**

PostgreSQL version: **15**

Citus version: **11.1**

For the purpose of this issue, create at least 2 worker nodes.

**Problem description**

When executing the `GRANT group TO my_role;` statement, the grant is not being propagated to the workers nodes, making statements fail with permission errors inside the worker nodes even though the group is authorized.

**How to reproduce**

First, create 2 roles:

1. analyticsdevs
2. user1

Both should be allowed to log in. After it, log in as admin and execute the following statements:

```
CREATE SCHEMA analytics;

GRANT USAGE ON SCHEMA analytics to analyticsdevs;
GRANT CREATE ON SCHEMA analytics to analyticsdevs;
GRANT ALL PRIVILEGES ON SCHEMA analytics to analyticsdevs;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA analytics TO analyticsdevs;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT ALL privileges ON TABLES TO analyticsdevs;

GRANT analyticsdevs TO user1;

CREATE TABLE analytics.samples(
    id bigint,
    description text,
    value bigint,
    company_id bigint
);

SELECT create_distributed_table('analytics.samples', 'company_id');

INSERT INTO analytics.samples(id, description, value, company_id)
SELECT
    generate_series(1, 10000),
    'sample description',
    10,
    floor(random() * 2000 + 1);
```

With grants & table ready, now log in with `user1` and execute the following statement:

```
SELECT 
    company_id,
    sum(value)
FROM 
    analytics.samples
GROUP BY
    1;
```

It will fail with an error like this:

```
ERROR:  permission denied for schema analytics
CONTEXT:  while executing command on private-w0.demo-cluster.postgres.database.azure.com:5432
```

In order to fix it, execute the following statement logged in as admin and retry the select statement above (logged as user1):

```
SELECT run_command_on_workers($cmd$
    GRANT analyticsdevs TO user1;
$cmd$);
```

**Comment by marcocitus** [comment]
This works fine on engine. It's a Cosmos PG-specific configuration issue.
