### ISSUE TITLE
Merge command on distributed tables with INSERT is too permissive 

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#6672]
```SQL
create table source (
    id   integer
);
SELECT create_distributed_table('source', 'id');

create table target (
    id   integer 
);
SELECT create_distributed_table('target', 'id');

-- happening on shard source_102073
INSERT INTO source VALUES (1);
NOTICE:  issuing INSERT INTO test.source_102073 (id) VALUES (1)
DETAIL:  on server onderkalaci@localhost:9701 connectionId: 44

-- happening on shard source_102073 AND target_102105
-- so INSERT to target with 10000 target_102105
merge into target sda
using source sdn
on sda.id = sdn.id AND sda.id = 1
when not matched then
  insert (id)
  values (10000);
NOTICE:  issuing MERGE INTO test.target_102105 sda USING test.source_102073 sdn ON ((sda.id OPERATOR(pg_catalog.=) sdn.id) AND (sda.id OPERATOR(pg_catalog.=) 1)) WHEN NOT MATCHED THEN INSERT (id) VALUES (10000)

MERGE 1


-- however, target with 10000 value is on target_102130
SELECT * FROM target WHERE id = 10000;
NOTICE:  issuing SELECT id FROM test.target_102130 target WHERE (id OPERATOR(pg_catalog.=) 10000)
DETAIL:  on server onderkalaci@localhost:9705 connectionId: 62

┌────┐
│ id │
├────┤
└────┘
(0 rows)

```

**Comment by onderkalaci** [comment]
>  values (10000);

We should perhaps only allow  `VALUES (sdn.id)` for `insert (id)` such that we always operate on the same distribution key?  We have a function that does a similar check for `INSERT .. SELECT` which is `InsertPartitionColumnMatchesSelect `. We probably cannot directly use that function, but still could be good starting point to see what are the cases we might be interested in looking

**Comment by naisila** [comment]
Yeah I guess we should only allow values within the source shard's hash distribution range.

I guess this has been overlooked, since it is expected to refer to source table values in the case of "NOT MATCHED".

**Comment by tejeswarm** [comment]
> Yeah I guess we should only allow values within the source shard's hash distribution range.
> 
> I guess this has been overlooked, since it is expected to refer to source table values in the case of "NOT MATCHED".

Typical usage is, when NOT MATCHED use the source values but we are not strictly enforcing it, in regular Postgres that may not be a big problem, but for it is. Let's completely avoid constants for distribution column at the very beginning and raise an exception.

**Comment by tejeswarm** [comment]
Similar context: It's not just WHEN clause-DML but there are other loopholes we need to cover. This is one route we are preventing now.

```
-- We have a potential pitfall where a function can be invoked in
-- the MERGE conditions which can insert/update to a random shard
CREATE OR REPLACE function merge_when_and_write() RETURNS BOOLEAN
LANGUAGE PLPGSQL AS
$$
BEGIN
        INSERT INTO t1 VALUES (100, 100);
        RETURN TRUE;
END;
$$;
-- Test preventing "ON" join condition from writing to the database
BEGIN;
MERGE INTO t1
USING s1 ON t1.id = s1.id AND t1.id = 2 AND (merge_when_and_write())
WHEN MATCHED THEN
        UPDATE SET val = t1.val + s1.val;
ERROR:  functions used in the WHERE/ON/WHEN clause of modification queries on distributed tables must not be VOLATILE
ROLLBACK;
```
