### ISSUE TITLE
Problem with generated column when rebalancing tables shards.

### ISSUE THREAD

**Issue by yuratushnyak** [citusdata/citus#6705]
Hi,
We're using Citus 11.1.4

## Steps to reproduce

1. Create distributed table and insert some data into it
```sql
CREATE TABLE t1 (id int PRIMARY KEY);
SELECT create_distributed_table('t1', 'id');
INSERT INTO t1 SELECT generate_series(1,1000) AS id;
```
2. Move shards off the designated node and disable the node temporarily
```sql
SELECT * FROM citus_drain_node('citus_worker_3', 5432);
SELECT * FROM citus_disable_node('citus_worker_3', 5432);
```
3. Add a new generated column to the distributed table
```sql
ALTER TABLE t1 ADD COLUMN new_id INT GENERATED ALWAYS AS ( id + 3 ) STORED;
```
4. Activate node
```sql
SELECT * FROM citus_activate_node('citus_worker_3', 5432);
SELECT * FROM citus_set_node_property('citus_worker_3', 5432, 'shouldhaveshards', true);
```
5. Start to rebalance tables shards
```sql
SELECT * FROM citus_rebalance_start();
```
6. Run query to monitor rebalance progress
```sql
SELECT * FROM pg_dist_background_task WHERE job_id = 1 ORDER BY task_id ASC \gx
```
```bash
-[ RECORD 1 ]--------------------------------------------------------------------------------------------------------
job_id      | 1
task_id     | 1
owner       | postgres
pid         |
status      | error
command     | SELECT pg_catalog.citus_move_shard_placement(102009,'citus_worker_2',5432,'citus_worker_3',5432,'auto')
retry_count | 33
not_before  |
message     | ERROR: row field count is 2, expected 1                                                                +
            | CONTEXT: while executing command on citus_worker_2:5432                                                +
            | Citus Background Task Queue Executor: docker/postgres                                                  +
```
or see logs on the citus_worker_3
```sql
2023-02-08 14:58:22.165 UTC [1088] ERROR:  row field count is 2, expected 1
2023-02-08 14:58:22.165 UTC [1088] CONTEXT:  COPY t1_102009, line 1
```
(Above steps has been reproduced in the docker environment using https://github.com/citusdata/docker/blob/master/docker-compose.yml)

**Comment by emelsimsek** [comment]
Debugged this issue a bit. 

Citus uses COPY command to transfer data from the source shard to the target shard when moving a shard between nodes.

COPY command ignores GENERATED columns in both COPY TO and COPY FROM. 

For instance, if you provide explicit column names including the GENERATED column, COPY FROM gives an error upfront:

> COPY t1(id, new_id) from stdin (FORMAT 'csv');
ERROR:  column "new_id" is a generated column
DETAIL:  **Generated columns cannot be used in COPY.**

If you omit the column names, but provide the GENERATED column values as input, COPY FROM fails with the unexpected column error.

> COPY t1 from stdin (FORMAT 'csv');
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
\>> 9, 12
\>> \\.
ERROR:  **extra data after last expected column**
CONTEXT:  COPY t1, line 1: "9, 12"

When copying data from the source shard to target shard through a connection between source node and target node, citus gets the data out by SELECT all query and COPY the generated stream at the target end of the connection:

```
 SELECT * FROM <source_shard>;
 COPY <target_shard> FROM STDIN WITH (format binary);
```
This is where Citus fails to omit generated column values from the input stream.

One fix would be to change the commands as follows:

```
SELECT (non-GENERATED columns) from <source_shard>;
 
COPY (non-GENERATED columns) FROM STDIN WITH (format binary);
```

**Comment by yuratushnyak** [comment]
thanks for the explanation
