### ISSUE TITLE
error: redefinition of ‘RelationGetSmgr’

### ISSUE THREAD

**Issue by anthonator** [citusdata/citus#6709]
When building Citus 11.2.0 on PostgreSQL 13.10 and 14.7 we're receiving the following errors.

```
/usr/local/src/citus/src/include/pg_version_compat.h:59:1: error: redefinition of ‘RelationGetSmgr’
   59 | RelationGetSmgr(Relation rel)
      | ^~~~~~~~~~~~~~~
In file included from /usr/include/postgresql/14/server/access/tableam.h:24,
                 from /usr/local/src/citus/src/include/columnar/columnar_tableam.h:7,
                 from columnar_customscan.c:46:
/usr/include/postgresql/14/server/utils/rel.h:544:1: note: previous definition of ‘RelationGetSmgr’ was here
  544 | RelationGetSmgr(Relation rel)
      | ^~~~~~~~~~~~~~~
make[1]: *** [<builtin>: columnar_customscan.o] Error 1
make[1]: Leaving directory '/usr/local/src/citus/src/backend/columnar'
make: *** [Makefile:19: columnar] Error 2
```

We do not see this error on PostgreSQL 15.2.

**Comment by JelteF** [comment]
Our own backport of that function conflicted with the backport that was done by postgres in this release: https://github.com/postgres/postgres/commit/32d5a4974c81aeaca7ffc025f0a5fda88b71cba6

I fixed this issue in https://github.com/citusdata/citus/pull/6711 and I backported the change to our 11.2 branch: https://github.com/citusdata/citus/commit/341fdb32fc07a3aea2dda2fa33a70d22819be37b. So when we tag the next 11.2 patch release, you can use that one. For now you can probably use the specific commit.
