### ISSUE TITLE
Cancellation leaks open connections in real-time executor

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#671]
In the real-time executor, we now call MultiClientWait to poll open connections. Currently, this function may throw errors:
https://github.com/citusdata/citus/blob/3dac0a4d1476757a80902159d0fbd875fd7437ab/src/backend/distributed/executor/multi_client_executor.c#L828 

The real-time and task-tracker executors need to clean up and close connections once they're done. So far, our approach to dealing with failures and cancellation has been to avoid throwing errors in executor code paths (which is tricky), such that we can eventually get to the clean-up code. Otherwise, we would break out of the control flow and skip over the clean up code, which results in leaking a lot of open connections.

A quick fix would be to avoid throwing errors in MultiClientWait and let the caller handle cancellations and failures. A longer term fix might be to move the executor into a PG_TRY block to make sure we catch everything, or introduce some persistent connection management into the executors.

**Comment by onderkalaci** [comment]
Re-producing the bug may not happen in the first cancellation, but the following steps got me to the error:

```SQL

CREATE TABLE test_table (int a);
SELECT master_create_distributed_table('test_table', 'a', 'hash');
SELECT master_create_worker_shards('test_table', '512',1);

\COPY test_table FROM 'path/to/a/sufficiently/big/file';

-- for some time do the following iteration
     SELECT * FROM test_table;
     -- then press CTRL_C

-- Some time later, you start to see the following errors:
WARNING:  connection failed to localhost:9700
DETAIL:  FATAL:  sorry, too many clients already
WARNING:  connection failed to localhost:9700
DETAIL:  FATAL:  sorry, too many clients already

**Comment by anarazel** [comment]
Hrmpf. The correct solution here seems to make connections in executors owned by the resource-owner framework (that's how limited lifetime resources like buffer pins, heavyweight locks and such are managed).  That way the code doesn't have to be sprinked with PG_TRY/CATCH blocks, subtransactions et al. can be handled, and it's in-line with postgres' architecture. But I think you're right, that's out of scope for 5.2.

And I also agree that we should unify the connection management. Using resource owner should make it easier to have a connection pool with "leases", so we can have multiple connections to nodes. But also out of scope.

I don't think we actually handled errors really before this change either. The likelihood of hitting problems was smaller though.

**Comment by marcocitus** [comment]
This can no longer happen, right?

**Comment by anarazel** [comment]
> This can no longer happen, right?

Right. We should really clean up some of the code now.
