### ISSUE TITLE
citus_set_coordinator_host() is not propagated to workers

### ISSUE THREAD

**Issue by CyberDem0n** [citusdata/citus#6757]
Currently Patroni intentionally using `citus_set_coordinator_host()` instead of` citus_update_node()` after failover/switchover of the coordinator. It changes address of the coordinator primary, but this change is not propagated to workers.

As a workaround I switched the `citus_update_node()` in Patroni, which doesn't have this problem: https://github.com/zalando/patroni/pull/2597

IMO, it would be nice if `citus_set_coordinator_host()` changes are also synced to workers.

**Comment by onderkalaci** [comment]
probably same https://github.com/citusdata/citus/issues/6731
