### ISSUE TITLE
array_cat_agg object causes an error while pg_upgrade

### ISSUE THREAD

**Issue by HalacliSeda** [citusdata/citus#6774]
Hi,
I use postgresql 12.14 and citus_12 10.2.5
I want to upgrade postgresql from 12 to 14.

I ran pg_upgrade command like this:
/usr/pgsql-14/bin/pg_upgrade -b /usr/pgsql-12/bin -B /usr/pgsql-14/bin -d /var/lib/pgsql/12/data -D /var/lib/pgsql/14/data -c
I got error:
Your installation contains user-defined objects that refer to internal
polymorphic functions with arguments of type "anyarray" or "anyelement".
These user-defined objects must be dropped before upgrading and restored
afterwards, changing them to refer to the new corresponding functions with
arguments of type "anycompatiblearray" and "anycompatible".
A list of the problematic objects is in the file:
    incompatible_polymorphics.txt

 cat incompatible_polymorphics.txt
In database: mydb
  aggregate: array_cat_agg(anyarray)

I could not drop this object:
drop aggregate  array_cat_agg ( anyarray) ;
ERROR:  cannot drop function array_cat_agg(anyarray) because extension citus requires it
HINT:  You can drop extension citus instead.

So, if I want to upgrade postgres major version, I should delete citus first.
Could this be a bug?

Thanks,
Seda

**Comment by onurctirtir** [comment]
Did you use citus_prepare_pg_upgrade/citus_finish_pg_upgrade() functions?

https://docs.citusdata.com/en/v11.2/admin_guide/upgrading_citus.html?highlight=upgrade#upgrading-postgresql-version-from-14-to-15 would probably help.

**Comment by HalacliSeda** [comment]
Hi @onurctirtir ,

" SELECT citus_prepare_pg_upgrade();" solved my problem. Thanks a lot.
