### ISSUE TITLE
Change default transaction manager for DDL propagation to one-phase commit

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#679]
As it stands, we default to 2PC for DDL propagation and 1PC for COPY commands.

The challenge with defaulting to 2PC for DDL is that the user needs to manually configure ``max_prepared_transactions`` setting before starting up all nodes. @anarazel noted that we may force incrementing this setting in our code. This solves the usability issue, but brings up the question around the default value we pick (see below).

We also talked about failure semantics. If the user spins up a new cluster, fails a machine, and then runs a DDL command, 1PC works well.

We're going to default to 1PC for COPY and DDL commands. We'll emit a (one-time?) notice message that informs the user about 2PC being extra-safe.

**Comment by sumedhpathak** [comment]
@aamederen Could you work on this tomorrow?
