### ISSUE TITLE
Introduce a GUC variable to disable router planner

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#680]
Router planner performs a shard pruning to decide if a query is router plannable. This may cause performance issues for users with non-router plannable queries and large number of shards. 

We could introduce a guc variable to disable router plannar when such things encountered.

Currently router planner is disabled only if task executor is set to task tracker. We could also remove this check to enable router planner for task tracker executor.

**Comment by ozgune** [comment]
@mtuncer @marcocitus @anarazel -- I had a quick clarification question (side question). What's our behavior today when the task executor type is set to ``real-time`` and ``task-tracker``?

That is, do we behave consistently in terms of overriding the executor type with router executor?

**Comment by anarazel** [comment]
On 2016-07-30 13:18:07 -0700, Ozgun Erdogan wrote:
> @mtuncer @marcocitus @anarazel -- I had a quick clarification question (side question). What's our behavior today when the task executor type is set to ``real-time`` and ``task-tracker``?
> 
> That is, do we behave consistently in terms of overriding the executor type with router executor?

No, we don't. We always override when it's set to real-time, but never
when task-tracker. That behaviour doesn't make much sense to me - if we
want a safety hatch against router, it shouldn't require using
task-tracker, which will often be unusably slow.

**Comment by marcocitus** [comment]
Fixed by c3a60bff
