### ISSUE TITLE
Could not create socket: Too many open files

### ISSUE THREAD

**Issue by thecatontheflat** [citusdata/citus#6818]
I get the following error when calling `select create_distributed_table('gpra', 'g_id');`:

```
ERROR:  connection to the remote node 192.168.111.3:11337 failed with the following error: connection to server at "192.168.111.3", port 13311 failed: could not create socket: Too many open files
```

**Comment by onderkalaci** [comment]
You may need to update `/etc/security/limits.conf`  (or such) OS settings.

For these kinds of questions, the [slack channel](https://citus-public.slack.com/) is more active and possible to search for history for similar problems.  We try to maintain the Github repository for bug reports, feature requests etc.

So, for now, I'm closing the issue, please move your question to the slack.
