### ISSUE TITLE
How to output logical wal as a cluster unit in citus?

### ISSUE THREAD

**Issue by zicjin** [citusdata/citus#6828]
I understand that it is generally not recommended to use Citus and ClickHouse simultaneously. However, due to the accumulation of a large number of ClickHouse queries in my project (including some specific syntax), modifying them would incur high costs. Therefore, I retained the ClickHouse cluster after implementing the upgrade from PG to Citus. Surprisingly, the MaterializedPostgreSQL engine in ClickHouse became invalid. Essentially, it only pretended to be a PG replica instance receiving logical WAL messages from PG. I configured wal_level=logical in the postgresql.conf file on the coordinator node, and created the MaterializedPostgreSQL ('coordinator_host:5432') database in ClickHouse. It could obtain the latest data replica at the time but could not update any subsequent data in real-time. This was not a problem on the previous single-node PG before migrating to Citus.

I understand that not all data of Citus distributed tables is available on the Coordinator node (I think?), but I found on [that](https://pg-auto-failover.readthedocs.io/en/main/citus.html#citus-secondaries-and-read-replica) pg_auto_failover can create another read-only cluster successfully and synchronize data in real-time from the default cluster. Therefore, theoretically, Citus should be able to output logical WAL as a cluster unit to the outside world, but I don't know how to do it specifically. I hope to get help from the community.

**Comment by rajeshkt78** [comment]
@zicjin We have done some changes to the Logical Replication Decoding to  support this kind of replication as a logical unit for Distributed Tables from a Citus Cluster. The changes are already in the main branch now and scheduled to be part of the Citus 11.3 release (pending final tests).  There will be some setup required by creating the logical replication slots in each worker node and a Publication for the distributed table from co-ordinator node. and connect to each worker node from the client side to get the changes in real-time.

**Comment by zicjin** [comment]
@rajeshkt78 Do we have a schedule for Milestones 11.3?

**Comment by mulander** [comment]
@zicjin currently we are aiming for the first week of May for the release of 11.3. Hope this helps.

**Comment by rajeshkt78** [comment]
@zicjin  The CDC feature for distributed tables (Preview) is availabe in Citus 11.3 release.
Please find the release notes on CDC here:
https://www.citusdata.com/updates/v11-3/

Please try the CDC feature for your use case and give us any feedback.
Thanks.

**Comment by zicjin** [comment]
it works fine. thx
