### ISSUE TITLE
Can not create user on workers via run_command_on_workers

### ISSUE THREAD

**Issue by ykun91** [citusdata/citus#6838]
When following this [doc](https://docs.citusdata.com/en/v11.2/faq/faq.html#how-do-i-create-database-roles-functions-extensions-etc-in-a-citus-cluster) to create user in citus, got `ERROR:  operation is not allowed on this node`

I am using Citus 11.2 + Postgres 15 + Patroni 3.0

The Error
![image](https://user-images.githubusercontent.com/10774721/230829509-b0ab5277-6f6b-48f8-b62d-a820fed923a6.png)

Whoami
![image](https://user-images.githubusercontent.com/10774721/230829519-e425e42e-975e-415b-b14c-9870563b5ddf.png)

**Comment by aykut-bozkurt** [comment]
Role creation is not allowed on workers. (Only allowed from the coordinator) But, when you run the command on the coordinator, it would also create the role on the workers.

**Comment by ykun91** [comment]
@aykut-bozkurt thanks for reply, I confirmed that run `CREATE ROLE ...` will create role on workers automatically, just misled by the document, maybe that document need get update.

Anyway my problem is solved and please close this issue.

Have a good day
