### ISSUE TITLE
Support evaluating functions on master to determine partition column value

### ISSUE THREAD

**Issue by lfittl** [citusdata/citus#687]
**Use case:** I have a distributed `customers` table with a `customer_id` column as SERIAL/UUID. `customer_id` is also my partition column.

My intention is for Citus to generate the `customer_id` (using a sequence or `uuid_generate_v4()`) and return it back to me using `RETURNING` on insertion.

Right now we're failing with `ERROR:  values given for the partition column must be constants or constant expressions`.

The current workaround is to have the client generate the ID, which works easy enough for UUIDs, but is rather cumbersome for sequences/SERIAL.

Full example for SERIAL:

``` sql
CREATE TABLE example_serial(id serial, name text, created_at timestamp);
SELECT master_create_distributed_table('example_serial', 'id', 'hash');
SELECT master_create_worker_shards('example_serial', 16, 1);

INSERT INTO example_serial (name, created_at) VALUES ('My test', now());
-- ERROR:  values given for the partition column must be constants or constant expressions

INSERT INTO example_serial (id, name, created_at) VALUES (nextval('example_serial_id_seq'::regclass), 'My test', now());
-- ERROR:  values given for the partition column must be constants or constant expressions

INSERT INTO example_serial (id, name, created_at) VALUES (1, 'My test', now());
-- INSERT 0 1
```

Full example for uuid:

``` sql
CREATE TABLE example_uuid(id uuid default uuid_generate_v4(), name text, created_at timestamp);
SELECT master_create_distributed_table('example_uuid', 'id', 'hash');
SELECT master_create_worker_shards('example_uuid', 16, 1);

INSERT INTO example_uuid (name, created_at) VALUES ('My test', now());
-- ERROR:  values given for the partition column must be constants or constant expressions

INSERT INTO example_uuid (id, name, created_at) VALUES (uuid_generate_v4(), 'My test', now());
-- ERROR:  values given for the partition column must be constants or constant expressions

INSERT INTO example_uuid (id, name, created_at) VALUES ('fa5f4b4b-6c97-47ee-9f84-fa702e01c98c', 'My test', now());
-- INSERT 0 1
```

**Comment by lithp** [comment]
This is potentially related to #681, we probably have to fix it by moving shard pruning into the executor, which might fix #681 at the same time.

**Comment by marcocitus** [comment]
It seems we mainly need to support INSERT. What if we defer pruning to the executor for INSERT only? It's not the most elegant solution, but it's the simple case and it doesn't seem like we really need to defer pruning for anything else.

**Comment by xbogdan** [comment]
What is the progress with this ?  Is it going to happen soon ?

Right now I'm between generating the ID on the client by doing:
```sql
select nextval('seq');
```
before inserting

OR

not using a ```PRIMARY KEY``` and trying to simulate one like this:
```sql
CREATE TABLE example_serial(id serial, name text, created_at timestamp);
CREATE INDEX xxx ON example_serial(id);
SELECT master_create_distributed_table('example_serial', 'name', 'hash');
SELECT master_create_worker_shards('example_serial', 16, 1);
```
 but this doesn't offer uniqueness and there is a change of having duplicate rows

**Comment by marcocitus** [comment]
Not the pretties solution, but I hacked something together on this branch:
https://github.com/citusdata/citus/tree/serial_partition_column

**Comment by lfittl** [comment]
@marcocitus Nice, thats excellent news! How much more work would be required to get that into a mergeable state?

**Comment by marcocitus** [comment]
Not that much I think. I'll just open a PR.
