### ISSUE TITLE
11.2.0 Build error against PostgreSQL 13 and 14

### ISSUE THREAD

**Issue by devrimgunduz** [citusdata/citus#6870]
Hi,

I just noticed that 11.2.0 fails to build against PostgreSQL 13 and 14. However it seems bizarre, as I 'm quite sure that it used to build before. This may be something with the latest minor releases, but I'm not sure. Below is the log. It does not fail to build against v15.

Can you please take a look? Thanks! Devrim

`gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -std=gnu99 -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wno-clobbered -Wno-declaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -Wshadow -Werror=vla -Werror=implicit-int -Werror=implicit-function-declaration -Werror=return-type -fstack-clash-protection -I '/var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/citus/F-37/citus-11.2.0/src/include' -I'../../../src/include' -I/usr/pgsql-14/include -I/var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/citus/F-37/citus-11.2.0/vendor/safestringlib/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o columnar_metadata.o columnar_metadata.c
In file included from columnar_debug.c:27:
/var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/citus/F-37/citus-11.2.0/src/include/pg_version_compat.h:59:1: error: redefinition of 'RelationGetSmgr'
   59 | RelationGetSmgr(Relation rel)
      | ^~~~~~~~~~~~~~~
In file included from /usr/pgsql-14/include/server/access/tableam.h:24,
                 from /usr/pgsql-14/include/server/access/nbtree.h:20,
                 from columnar_debug.c:14:
/usr/pgsql-14/include/server/utils/rel.h:544:1: note: previous definition of 'RelationGetSmgr' with type 'SMgrRelationData *(struct RelationData *)'
  544 | RelationGetSmgr(Relation rel)
      | ^~~~~~~~~~~~~~~
make[2]: *** [<builtin>: columnar_debug.o] Error 1
make[2]: *** Waiting for unfinished jobs....
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -std=gnu99 -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wno-clobbered -Wno-declaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -Wshadow -Werror=vla -Werror=implicit-int -Werror=implicit-function-declaration -Werror=return-type -fstack-clash-protection -fno-lto /var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/citus/F-37/citus-11.2.0//src/bin/pg_send_cancellation/pg_send_cancellation.o -L/usr/pgsql-14/lib -lpgcommon -lpgport -L/usr/pgsql-14/lib -lpq -L/usr/pgsql-14/lib -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1  -L/usr/lib64  -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-14/lib',--enable-new-dtags -L/usr/pgsql-14/lib -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1  -L/usr/lib64  -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-14/lib',--enable-new-dtags -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes -lzstd -llz4 -lcurl     -lpgcommon -lpgport -lselinux -llz4 -lxslt -lxml2 -lssl -lcrypto -lgssapi_krb5 -lm -o pg_send_cancellation
In file included from /var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/citus/F-37/citus-11.2.0/src/include/distributed/listutils.h:19,
                 from columnar_customscan.c:47:
/var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/citus/F-37/citus-11.2.0/src/include/pg_version_compat.h:59:1: error: redefinition of 'RelationGetSmgr'
   59 | RelationGetSmgr(Relation rel)
      | ^~~~~~~~~~~~~~~
In file included from /usr/pgsql-14/include/server/access/tableam.h:24,
                 from /var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/citus/F-37/citus-11.2.0/src/include/columnar/columnar_tableam.h:7,
                 from columnar_customscan.c:46:
/usr/pgsql-14/include/server/utils/rel.h:544:1: note: previous definition of 'RelationGetSmgr' with type 'SMgrRelationData *(struct RelationData *)'
  544 | RelationGetSmgr(Relation rel)
      | ^~~~~~~~~~~~~~~
make[2]: *** [<builtin>: columnar_customscan.o] Error 1
In file included from /var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/citus/F-37/citus-11.2.0/src/include/distributed/listutils.h:19,
                 from columnar_metadata.c:30:
/var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/citus/F-37/citus-11.2.0/src/include/pg_version_compat.h:59:1: error: redefinition of 'RelationGetSmgr'
   59 | RelationGetSmgr(Relation rel)
      | ^~~~~~~~~~~~~~~
In file included from /var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/citus/F-37/citus-11.2.0/src/include/columnar/columnar_storage.h:18,
                 from columnar_metadata.c:28:
/usr/pgsql-14/include/server/utils/rel.h:544:1: note: previous definition of 'RelationGetSmgr' with type 'SMgrRelationData *(struct RelationData *)'
  544 | RelationGetSmgr(Relation rel)
      | ^~~~~~~~~~~~~~~
make[2]: *** [<builtin>: columnar_metadata.o] Error 1
make[2]: Leaving directory '/var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/citus/F-37/citus-11.2.0/src/backend/columnar'
make[1]: *** [Makefile:19: columnar] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/citus/F-37/citus-11.2.0/src/bin/pg_send_cancellation'
make[1]: Leaving directory '/var/lib/pgsql/git/pgrpms/rpm/redhat/main/non-common/citus/F-37/citus-11.2.0'
error: Bad exit status from /var/tmp/rpm-tmp.gIzHfD (%build)

`

**Comment by JelteF** [comment]
v11.2.1 got a tag just now

**Comment by devrimgunduz** [comment]
Thanks, I can confirm that the fix works. Closing.
