### ISSUE TITLE
Table Creation is not idempotent during Nontransactional sync

### ISSUE THREAD

**Issue by aykut-bozkurt** [citusdata/citus#6888]
Below sql lines could not run successfully at second time as we record dependency between table and sequence. At second run `drop table cascade` would also drops depended sequence, then `create table` would fail due to nonexisting sequence.

```sql
CREATE SEQUENCE IF NOT EXISTS mytable_myserial_seq AS integer INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;

DROP TABLE IF EXISTS mytable CASCADE;CREATE TABLE mytable (myserial integer DEFAULT worker_nextval('mytable_myserial_seq'::regclass) NOT NULL, event_time timestamp without time zone) PARTITION BY RANGE (event_time) ;

SELECT pg_catalog.worker_record_sequence_dependency('mytable_myserial_seq'::regclass,'mytable'::regclass,'myserial');
```

Solution can be to drop dependency between sequence and table before `drop table cascade` so that sequence would not be dropped. This is safe since we still record dependency at the end.

**Comment by aykut-bozkurt** [comment]
When we break just before `SendDistTableMetadataCommands` and kill the session in the middle of the nontransactional sync, table would not be in `pg_dist_partition` table at worker node even if it is in `pg_dist_partition` table at coordinator. Then when we again run the sync, `BREAK_CITUS_TABLE_SEQUENCE_DEPENDENCY_COMMAND = "SELECT pg_catalog.worker_drop_sequence_dependency(logicalrelid::regclass::text) FROM pg_dist_partition"` would not actually break any sequence-table dependency at worker since `pg_dist_partition` at worker does not contain the table.

I can reproduce via

```sql
create table zz(id serial);
select create_distributed_table('zz','id');
--- break before executing `SendDistTableMetadataCommands` and kill -9 <pid> ---
select start_metadata_sync_to_node('localhost', 9701);

--- create a new session and now sync would fail ---
select start_metadata_sync_to_node('localhost', 9701);
WARNING:  relation "public.zz_id_seq" does not exist
ERROR:  failure on connection marked as essential: localhost:9701
"""

**Comment by onderkalaci** [comment]
> When we break just before SendDistTableMetadataCommands and kill the session in the middle of the nontransactional sync, table would not be in pg_dist_partition table at worker node even if it is in pg_dist_partition table at coordinator

And, when you have lots of distributed tables, `SendDependencyCreationCommands` could take a really long time, and hence any cancellation before `SendDependencyCreationCommands` finishes and starts/finishes `SendDistTableMetadataCommands`, we are in this situation.
