### ISSUE TITLE
different number of dashes in regression tests in citus and Postgres

### ISSUE THREAD

**Issue by ivan-v-kush** [citusdata/citus#6911]
Hello. I'd like to use citus, but regression tests can't pass due to difference in dashes. 
I use Postgres 15.2. It prints the  floating number of dashes `-------`, number corresponds to result string  length, but citus uses  the fixed number of dashes for all outputs `---------------------------------------------------------------------`

Do citus development team uses custom pg_regress or even Postgres, where they have coded fixed number of dashes?

```
   1 diff -dU10 -w /build/contrib/citus/src/test/regress/expected/columnar_create.out /build/contrib/citus/src/test/regress/results/columnar_create.out
   2 --- /build/contrib/citus/src/test/regress/expected/columnar_create.out  2023-05-04 13:31:25.349140192 +0000
   3 +++ /build/contrib/citus/src/test/regress/results/columnar_create.out   2023-05-04 14:55:03.627541501 +0000
   4 @@ -8,177 +8,177 @@
   5  ALTER TABLE contestant SET (columnar.compression = none);
   6  CREATE INDEX contestant_idx on contestant(handle);
   7  -- Create zstd compressed table
   8  CREATE TABLE contestant_compressed (handle TEXT, birthdate DATE, rating INT,
   9     percentile FLOAT, country CHAR(3), achievements TEXT[])
  10     USING columnar;
  11  -- Test that querying an empty table works
  12  ANALYZE contestant;
  13  SELECT count(*) FROM contestant;
  14   count
  15 ----------------------------------------------------------------------
  16 +-------
  17       0
  18  (1 row)
```

Also 3 years ago citus have used floating number of dashes in tests/

https://github.com/citusdata/citus/blame/de22b633cb390462e930f0ff28228ba39fdb91fb/src/test/regress/output/am_create.source#L17

**Comment by JelteF** [comment]
If you use `make check` this should automatically work. We use a custom `diff` command that normalizes the output of pg_regress: https://github.com/citusdata/citus/blob/main/src/test/regress/bin/diff

**Comment by ivan-v-kush** [comment]
Thank you!
custom diff haven't had permission for execution - that was the reason.

`chmod +x src/test/regress/bin/diff` solved the problem
