### ISSUE TITLE
We should qualify all citus_move_shard_placement and citus_copy_shard_placement

### ISSUE THREAD

**Issue by JelteF** [citusdata/citus#6926]
As a defense in depth against privilege escalations we should fully qualify all functions that we call with pg_catalog. Otherwise users might be able to trick us into calling another function.

Known places (but maybe more):
1. https://github.com/citusdata/citus/blob/main/src/backend/distributed/utils/reference_table_utils.c#L422-L429
2. https://github.com/citusdata/citus/blob/main/src/backend/distributed/operations/shard_rebalancer.c#L2279-L2294

**Comment by pinodeca** [comment]
Isn't there a tool we can include in our CI that catches any function calls that aren't fully qualified?
