### ISSUE TITLE
Display informative and consistent error messages after router executor changes

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#693]
@marcocitus noted in #692 that small changes in incoming queries could lead to very different error messages. This is a consequence of having two planners (router and logical/physical) and three executors (router, real-time, and task-tracker).

I'm opening this issue to evaluate if we can emit error messages that provide a more consistent experience to the user. In practice, @marcocitus shared three example queries where the user observes different characteristics in terms of supported functionality. Are there other example queries?

Also, are there quick improvements we could make to these messages to make our users successful?

I'm also noting #684 as a related issue. (This issue could be a superset of #684.)

I'm copy/pasting @marcocitus' description from #692 below.
## 

First-time users often start with 2 worker nodes and a replication factor of 2. In this case, the router planner can run practically any SQL query that hits a single shard in each table. When users start expanding their cluster and moving shards or changing filter values, this may no longer be the case, potentially causing and outage or forcing the user to redesign their application.

Some examples of confusing behaviour:

The following query requires task-tracker when changing one value because we're joining tables that are not always co-located:

```
postgres=# SELECT * FROM review JOIN customer USING (customer_id) WHERE product_id = 1 AND customer_id = 1;
 customer_id | product_id | score | name 
-------------+------------+-------+------
(0 rows)

postgres=# SELECT * FROM review JOIN customer USING (customer_id) WHERE product_id = 1 AND customer_id = 2;
ERROR:  cannot use real time executor with repartition jobs
HINT:  Set citus.task_executor_type to "task-tracker".
```

Union is simultaneously supported and "unsupported" (we should revise our error messages):

```
postgres=# SELECT * FROM customer WHERE customer_id = 1 UNION SELECT * FROM customer WHERE customer_id = 5;
 customer_id | name 
-------------+------
(0 rows)

postgres=# SELECT * FROM customer WHERE customer_id = 1 UNION SELECT * FROM customer WHERE customer_id = 4;
ERROR:  cannot perform distributed planning on this query
DETAIL:  Union, Intersect, or Except are currently unsupported
```

Running shard rebalancer might cause the same query to suddenly become "unsupported":

```
postgres=# SELECT * FROM customer WHERE customer_id = 1 UNION SELECT * FROM customer WHERE customer_id = 7;
 customer_id | name
-------------+------
(0 rows)
postgres=# SELECT rebalance_table_shards('customer');
NOTICE:  Moving shard 102032 from localhost:9701 to localhost:9700 ...
 rebalance_table_shards 
------------------------

(1 row)

postgres=# SELECT * FROM customer WHERE customer_id = 1 UNION SELECT * FROM customer WHERE customer_id = 7;
ERROR:  cannot perform distributed planning on this query
DETAIL:  Union, Intersect, or Except are currently unsupported
```

**Comment by begriffs** [comment]
What if we had a `citus.warning_level` variable which, when set to a suitable value, would cause Citus to output warnings for these kind of statements? The example statement above might say something like:

```
WARNING: this statement contains a UNION and may stop working if data is rearranged across your shards.
```

**Comment by samay-sharma** [comment]
This came in from a user:

His tables are distributed by id.

"We use `generate_series` to fill in 0’s where data does not exist (to make it easier to show the data on a graph). the following is the sort of query I’m trying to run

```sql
SELECT day, COALESCE(downloads, 0) AS downloads, id
    FROM
    (SELECT DAY::date
    FROM generate_series('2016-07-09', '2016-08-09', interval '1 day') DAY) range
    LEFT JOIN
    (SELECT sum(total) AS downloads, date AS date, id
    FROM table
    WHERE id IN ('....', '....')
    AND date between '2016-07-09' AND '2016-08-09'
    GROUP BY date, id) values ON values.date = day
    ORDER BY day, id
```

and I get the following error

```
NOTICE:  cannot use shard pruning with ANY/ALL (array expression)
HINT:  Consider rewriting the expression with OR/AND clauses.
ERROR:  cannot perform distributed planning on this query
DETAIL:  Join in subqueries is not supported yet
```

It seems to work for a single entity (if the `IN` clause contains only a single element), but fails as soon as there is more then 1

**Comment by ozgune** [comment]
We ran into another scenario where this message caused confusion for a Citus user.

The user issued queries that had complex joins and window functions. These queries could typically be pushed down to a particular worker node and therefore the router-executor would kick in.

For example, let's say the user was joining table ``conversions`` with table ``visits`` on an on-prem deployment. The conversions table has the shard conversions_100 and the visits table has the shard visits_200, and the user wants to join them. Node A has conversions_100 and visits_200, and node B has the replica shards conversions_100 and visits_200. Due to write failures to node A and node B, Citus marks conversions_100 on node A, and visits_200 on node B as invalid. In this case, the router executor can't find healthy shards to push down a query to node A or node B, and instead falls back to the real-time executor.

"We are now getting the following error when running this in our database:

<pre>
ERROR: cannot perform distributed planning on this query
DETAIL: Window functions are currently unsupported
</pre>

If I remove the window function from the query, it then has a different error saying subquery joins are not supported.

We haven't deployed any new code that would affect this and the query has not changed, and when I check the Citus version using \dx in psql, it says Citus 5.2-1 for the master and all of the workers. Any idea what might be happening here?"

**Comment by ozgune** [comment]
We talked about this error message earlier this week; and I wanted to add a summary here.

Our users are nicely relying on the router executor for their queries. Then, something unrelated to their application changes, Citus emit an error message (from the real-time executor), and they get confused. This change could happen in one of three ways:

1. Colocation and invalid shards -- If the user is using statement-based replication, and Citus marks colocated shards on separate machines as invalid, then router executor can't push down this query. ([the example scenario above](https://github.com/citusdata/citus/issues/693#issuecomment-258241017))
2. Colocation and shard rebalancer -- Shard rebalancer previously didn't respect colocation between colocated tables' shards. This is no longer the case.
3. Filter clauses -- If the user has a filter clause in their query that reduce the scope of that query to a particular machine, and later change that filter clause so that the query can't be pushed down to a particular machine, we then fall back to the real-time executor. We have example scenarios in the [comment above](https://github.com/citusdata/citus/issues/693#issue-168739976). We also had this issue reported by users in #750.

**Comment by metdos** [comment]
@sumedhpathak, @ozgune, this is on the prioritized task list, shall we tag it with 6.1?

**Comment by sumedhpathak** [comment]
@metdos Yep, tagged it with 6.1.

**Comment by mtuncer** [comment]
I am considering adding 2 hints when a query rejected in logical planner.

1 - if it is join related 
```
HINT:  Consider joining tables on partition column and have equal filter on joining columns
```
2 - otherwise
```
HINT:  Consider using equal filter on partition column
```

I displayed this error only if relations in the query are hash partitioned and co-located. if range/append partitioned relation is used, I did not display the hint.  If a reference table is used, the hint is displayed only if there is also a hash partitioned relation used in the query.

However, this does not address ANY/ALL message @marcocitus mentioned.

**Comment by metdos** [comment]
> I am considering adding 2 hints when a query rejected in logical planner.
> 
> 1 - if it is join related
> 
> HINT:  Consider joining tables on partition column and have equal filter on joining columns.
> 2 - otherwise
> 
> HINT:  Consider using equal filter on partition column.
> I displayed this error only if relations in the query are hash partitioned and co-located. if range/append partitioned relation is used, I did not display the hint. If a reference table is used, the hint is displayed only if there is also a hash partitioned relation used in the query.
> 
> However, this does not address ANY/ALL message @marcocitus mentioned.

@samay-sharma, @lfittl any comments?
