### ISSUE TITLE
Flaky tests to fix

### ISSUE THREAD

**Issue by agedemenli** [citusdata/citus#6940]
Test files that fail on main branch when
`src/test/regress/citus_tests/run_test.py $test_name --repeat 8 --use-base-schedule --use-whole-schedule-line`

* alter_distributed_table
* multi_metadata_sync
* ~view_propagation~
* ~function_propagation~
* ~distributed_functions~

**Comment by onurctirtir** [comment]
Probably not applicable anymore as we don't see any more occurrences of them.
