### ISSUE TITLE
citus_drain_node errors out when replication_factor > 1

### ISSUE THREAD

**Issue by agedemenli** [citusdata/citus#6948]
With a Citus cluster with 2 workers, `citus_drain_node` errors out for the node that has a shard replication. It's because we are running a shard move in the background, trying to move the shard to a node that it already exists on.
We should probably throw an error with a better message, or maybe ignore these shards when draining.

```sql
set citus.shard_replication_factor to 2;
create table t1 (a int primary key);
select create_distributed_table('t1','a');
select * from citus_drain_node('localhost',9702);
NOTICE:  Moving shard 102008 from localhost:9702 to localhost:9701 ...
ERROR:  shard 102008 already exists in the target node
CONTEXT:  while executing command on localhost:9700
```

**Comment by JelteF** [comment]
It's because this function doesn't take into account if there's already a placement for that shard on the node: https://github.com/citusdata/citus/blob/d99a5e2f62f3de0e520062c835025eeeb487447e/src/backend/distributed/operations/shard_rebalancer.c#L2770
