### ISSUE TITLE
Insert query with arguments inside a plpgsql function throws error

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus#700]
**Citus Version:** Current 5.2 Master branch.

The following are  the steps to reproduce
```
CREATE SCHEMA test_schema;
create table test_schema.table1 (
key int not null,
value int
);
select master_create_distributed_table('test_schema.table1','key','hash');
select master_create_worker_shards('test_schema.table1',16,1);

CREATE OR REPLACE FUNCTION test_schema.insert_func( key_arg int,
val_arg int
) RETURNS void as $$
DECLARE
distribution_col CONSTANT INTEGER := key_arg;
BEGIN
INSERT INTO test_schema.table1 (key, value)
VALUES (distribution_col,val_arg);
END;
$$ language plpgsql;

select test_schema.insert_func(1,3);

ERROR:  cache lookup failed for type 0
CONTEXT:  SQL statement "INSERT INTO test_schema.table1 (key, value)
VALUES (distribution_id,val_arg)"
PL/pgSQL function test_schema.insert_func(integer,integer) line 5 at SQL statement
```

Even after the distribution column is hardcoded by 1, the error persists.
After I hardcode both the key and value, then it works, which makes sense because it would become an INSERT query without argument.

Even if I remove the schema from the above SQL commands and do the above steps for the public schema, the same error arises.

If I wrap the INSERT statement in the function with an execute-format statement, it fixes the problem.
```
CREATE OR REPLACE FUNCTION test_schema.insert_func( key_arg int,
val_arg int
) RETURNS void as $$
DECLARE
distribution_id CONSTANT INTEGER := key_arg;
BEGIN
EXECUTE format('INSERT INTO test_schema.table1 (key, value)
VALUES (%s,%s)',distribution_id,val_arg);
END;
$$ language plpgsql;
```

In **Citus 5.1** the issue was that **select test_schema.insert_func(1,3);** ran for 5 times(because of a custom plan which fetches the partition key) and fails since the 6th time. The above error is seen in Citus 5.2(pre-release master branch)

**Comment by ozgune** [comment]
@anarazel @metdos -- is this issue related to our prepare or transaction changes?

@samay-sharma, do you consider this issue to notably impact our production customers?

**Comment by anarazel** [comment]
On 2016-08-04 09:00:11 -0700, Ozgun Erdogan wrote:
> @anarazel @metdos -- is this issue related to our prepare or transaction changes?

Prepare.

> @samay-sharma, do you consider this issue to notably impact our production customers?

I think that shows a weakness in the prepare code, that at least
partially needs to be addressed.

**Comment by anarazel** [comment]
On 2016-08-04 09:20:44 -0700, Andres Freund wrote:
> On 2016-08-04 09:00:11 -0700, Ozgun Erdogan wrote:
> > @anarazel @metdos -- is this issue related to our prepare or transaction changes?
> 
> Prepare.
> 
> > @samay-sharma, do you consider this issue to notably impact our production customers?
> 
> I think that shows a weakness in the prepare code, that at least
> partially needs to be addressed.

It's also looking like a very easy fix. We just need to check for
parameterData->ptype == 0 - and skip the bottom part of the loop in
static void
ExtractParametersFromParamListInfo(ParamListInfo paramListInfo, Oid **parameterTypes,
								   const char ***parameterValues)
which, in this case, then yields the expected:
ERROR:  0A000: values given for the partition column must be constants or constant expressions

Greetings,

Andres Freund

**Comment by samay-sharma** [comment]
@ozgune : This was actually found by one of our users who were testing Citus (possibly using the master branch as it had schema support). So, I would say it has user facing impact.

Some of the production customers already wrap their statements with execute with 5.1, as this would have worked 5 times and then failed previously.

Talking to @anarazel , it seems like a simple fix and I think we should fix it.
