### ISSUE TITLE
Evaluate reducing serialization cost during query planning

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#703]
We already have some discussion around this issue in citus-mx [repo](https://github.com/citusdata/citus-mx/issues/14). We're not sure to check-in this feature immediately, see the discussion below:

The observation here is that it takes long time to  serialize/de-serialize target list entries as the target list grows. However, router executor has nothing to do with the target list elements that we have in the workerJob except for evaluating functions on the master node.

So, we could discuss getting rid of the target list for the router jobs which has performance benefits.

I created a branch called performance/reduce_serialization_cost and did some tests on citus with 1 + 2 c4.2xlarge cluster where the shard size and replication factor is fixed (128 and 1). On each test, I changed the column*\* count to see the effect of the change. Below are the results (inserts per second):

|  | master | performance/reduce_serialization_cost |
| --- | --- | --- |
| 1 Column: | 34090 | 36200 |
| 16 Columns: | 18184 | 26101 |
| 128 Columns: | 7020 | 13200 |
| 512 Columns: | 1088 | 2488 |
| 1024 Columns: | 485 | 963 |

On the average, (excluding 1 column case), we get **1.5x** to **2x** improvement. 

There is a PR which we've not merged, but a representative solution for the fix: #648 

But, I should also note that the above PR conflicts with [Evaluate functions on master](https://github.com/citusdata/citus/pull/488), so, we should find slightly different way of implementing this optimization.

Also, some important notes from @anarazel:
-  Btw, the citus branch for 9.6 support that I have, gets entirely rid of the (de-)serialization; by using the 9.6 support for extensible nodes.
- I think it'll quite possibly cause issues for prepared statements for router queries. There we need to keep the Query around, and re-generate SQL after replacing parameters. After I mention that this change is scoped with router plans: There it'll possibly become problematic when we support prepared params on the partitioning key.
- I'm a bit suspicious of the general approach. I think it's better to get rid of excessive copying, and then do relatively fragile optimizations like this one. But on the other hand, this is a fairly major win, for few lines of code.
- Because it breaks the semantics of a well defined data structure. Again, I think it might be worthwhile in this case, but I think we should be hesitant to do that in more places.

**Comment by onderkalaci** [comment]
@metdos / @anarazel I think this is a good reason to stop serialization/deserialization 😄  Are we close to this after the custom scans?

**Comment by metdos** [comment]
> @metdos / @anarazel I think this is a good reason to stop serialization/deserialization 😄 Are we close to this after the custom scans?

Yes, but we need to stop 9.5 support.

**Comment by ozgune** [comment]
Our semi-official policy has been that each major Citus release supports the last two major PostgreSQL releases. For example, Citus 6.x supports Postgres 9.5 & 9.6.

With that in mind, we could incorporate these changes starting with Citus 7.x releases.

**Comment by marcocitus** [comment]
Will PG10 be out when we release 7.0 though?

**Comment by ozgune** [comment]
@marcocitus -- When we release 7.0, PG 10 should be close enough. 😄 

@onderkalaci -- I saw that we closed #648 and had a curiosity question. If we wanted to merge a proper fix for this change, how long would it take?

**Comment by jasonmp85** [comment]
> When we release 7.0, PG 10 should be close enough

I feel like one of the recent releases dropped 9.4 before 9.6 was ready, no? So there is precedent, but it would also probably be best to support 9.6 until 10 is official official.

**Comment by anarazel** [comment]
Plan:
* add copyfuncs for our node types
* use that instead of serialization/deserialization in multi_planner.c
  * do so optionally if we want to continue supporting 9.5

**Comment by ozgune** [comment]
@byucesoy -- I wanted to drop a quick note here for the write performance benchmarks you're running.

@anarazel mentioned we incorporated many related changes after @onderkalaci's original pull request (#648) and that it likely won't work. Andres mentioned that coming up with a prototype that uses copyfuncs would be the right way to go -- if we think the effort isn't that high.

**Comment by anarazel** [comment]
To bring some numbers into this.  In a very quick and dirty benchmark (pgbench -S), default citus has a profile (1 coordinator, 4 workers on my laptop) like:
```
-    3.66%  postgres         postgres                      [.] pg_strtok
   - 74.53% pg_strtok
      - 39.74% parseNodeString
         - nodeRead
            + 61.02% nodeRead
            + 14.69% _readRangeTblFunction
            + 9.59% stringToNode
            + 7.61% _readTargetEntry
            + 4.17% _readRangeTblEntry
            + 1.77% ReadMultiPlan
            + 0.63% _readFromExpr
      + 14.94% _readQuery
      + 12.78% nodeRead
      + 7.60% _readRangeTblEntry
      + 6.37% readDatum
      + 5.00% _readOpExpr
      + 4.09% _readExtensibleNode
      + 3.52% _readTargetEntry
      + 2.83% _readRangeTblFunction
      + 2.06% _readBitmapset
      + 0.61% _readFromExpr
   + 22.32% citus_pg_strtok@plt
+    2.89%  postgres         postgres                      [.] AllocSetAlloc
+    2.60%  postgres         postgres                      [.] hash_search_with_hash_value
-    2.60%  postgres         libc-2.24.so                  [.] vfprintf
   - 97.32% vfprintf
      - _IO_vsnprintf
         - 87.12% pvsnprintf
            - appendStringInfo
               + 34.13% outNode.part.2
               + 19.44% outDatum
               + 9.36% _outQuery
               + 7.28% OutTask
               + 5.62% _outRangeTblEntry
               + 4.27% OutShardPlacement
               + 3.60% _outOpExpr
               + 3.44% _outFuncExpr
               + 3.01% _outTargetEntry
               + 2.65% OutJob
               + 2.18% OutMultiPlan
               + 1.72% get_rule_expr
               + 1.62% _outRangeTblFunction
               + 0.99% get_from_clause_item
               + 0.68% OutRelationShard
         + 12.88% __snprintf
+    2.36%  postgres         postgres                      [.] SearchCatCache
-    1.37%  postgres         libc-2.24.so                  [.] _IO_default_xsputn
   - 96.97% _IO_default_xsputn
      + vfprintf
+    1.37%  postgres         postgres                      [.] hash_seq_search
+    1.36%  postgres         libc-2.24.so                  [.] __memset_avx2_unaligned_erms
+    1.28%  postgres         libc-2.24.so                  [.] _int_malloc
+    1.16%  postgres         libc-2.24.so                  [.] strlen
+    1.00%  postgres         postgres                      [.] base_yyparse
+    0.99%  postgres         postgres                      [.] expression_tree_walker
+    0.90%  postgres         postgres                      [.] copyObject
+    0.82%  postgres         libc-2.24.so                  [.] __memmove_avx_unaligned_erms
+    0.67%  postgres         postgres                      [.] palloc
+    0.66%  postgres         [kernel.vmlinux]              [k] do_raw_spin_lock
+    0.65%  postgres         libc-2.24.so                  [.] __strchrnul
+    0.62%  postgres         postgres                      [.] hash_search
+    0.62%  postgres         libc-2.24.so                  [.] __GI_____strtoll_l_internal
+    0.57%  postgres         postgres                      [.] appendStringInfo
+    0.56%  postgres         libc-2.24.so                  [.] _IO_vsnprintf
+    0.55%  postgres         libc-2.24.so                  [.] __errno_location
+    0.54%  postgres         [kernel.vmlinux]              [k] __fget_light
+    0.53%  postgres         libc-2.24.so                  [.] _int_free
+    0.51%  postgres         postgres                      [.] PostgresMain
+    0.47%  postgres         libc-2.24.so                  [.] __strcmp_sse2_unaligned
```
I.e. a good chunk of the time is spent in serialization (vfprintf, xsputn,strlen, ...), unserialization (pg_strtok, strchr, ...).  I get
```
 andres@alap4:~$ pgbench -h localhost -U postgres -M prepared -p 57636 -S -n -c 64 -j 64 -T 1000 -P 1
progress: 1.0 s, 11500.6 tps, lat 4.757 ms stddev 13.271
progress: 2.0 s, 14841.2 tps, lat 4.303 ms stddev 2.071
progress: 3.0 s, 14154.9 tps, lat 4.510 ms stddev 3.810
progress: 4.0 s, 13702.7 tps, lat 4.671 ms stddev 2.309
progress: 5.0 s, 13595.5 tps, lat 4.704 ms stddev 1.627
progress: 6.0 s, 13445.7 tps, lat 4.754 ms stddev 1.980
progress: 7.0 s, 13662.4 tps, lat 4.683 ms stddev 1.741
progress: 8.0 s, 13297.7 tps, lat 4.805 ms stddev 1.994
progress: 9.0 s, 13643.6 tps, lat 4.692 ms stddev 1.769
progress: 10.0 s, 13768.4 tps, lat 4.642 ms stddev 1.752
progress: 11.0 s, 13558.4 tps, lat 4.709 ms stddev 2.291
progress: 12.0 s, 12243.8 tps, lat 5.226 ms stddev 1.896
progress: 13.0 s, 13392.3 tps, lat 4.779 ms stddev 1.976
progress: 14.0 s, 13751.9 tps, lat 4.652 ms stddev 1.409
progress: 15.0 s, 14241.5 tps, lat 4.491 ms stddev 1.801
progress: 16.0 s, 15200.2 tps, lat 4.209 ms stddev 1.555
progress: 17.0 s, 14755.1 tps, lat 4.335 ms stddev 1.450
progress: 18.0 s, 15038.0 tps, lat 4.255 ms stddev 1.468
progress: 19.0 s, 15114.8 tps, lat 4.232 ms stddev 1.307
progress: 20.0 s, 14452.9 tps, lat 4.427 ms stddev 1.749
progress: 21.0 s, 14927.0 tps, lat 4.283 ms stddev 1.794
```

A quick and dirty implementation of the copyfuncs gets me:
```
+    3.30%  postgres         postgres                      [.] AllocSetAlloc
+    2.99%  postgres         postgres                      [.] hash_search_with_hash_value
+    2.97%  postgres         postgres                      [.] SearchCatCache
+    1.69%  postgres         postgres                      [.] hash_seq_search
+    1.63%  postgres         libc-2.24.so                  [.] _int_malloc
+    1.45%  postgres         libc-2.24.so                  [.] __memset_avx2_unaligned_erms
+    1.37%  postgres         postgres                      [.] copyObject
+    1.24%  postgres         postgres                      [.] base_yyparse
+    1.17%  postgres         libc-2.24.so                  [.] strlen
+    0.92%  postgres         postgres                      [.] expression_tree_walker
+    0.82%  postgres         [kernel.vmlinux]              [k] do_raw_spin_lock
+    0.78%  postgres         postgres                      [.] palloc
+    0.77%  postgres         libc-2.24.so                  [.] __memmove_avx_unaligned_erms
+    0.70%  postgres         libc-2.24.so                  [.] _int_free
```
performance
```
progress: 1.0 s, 15015.9 tps, lat 3.880 ms stddev 17.186
progress: 2.0 s, 18127.3 tps, lat 3.523 ms stddev 1.999
progress: 3.0 s, 18072.8 tps, lat 3.548 ms stddev 2.182
progress: 4.0 s, 18337.8 tps, lat 3.485 ms stddev 0.982
progress: 5.0 s, 18339.2 tps, lat 3.487 ms stddev 0.982
progress: 6.0 s, 18235.9 tps, lat 3.508 ms stddev 1.066
progress: 7.0 s, 17814.8 tps, lat 3.589 ms stddev 1.075
progress: 8.0 s, 18156.9 tps, lat 3.524 ms stddev 1.276
progress: 9.0 s, 18228.3 tps, lat 3.509 ms stddev 1.106
progress: 10.0 s, 18414.4 tps, lat 3.474 ms stddev 0.970
progress: 11.0 s, 18395.8 tps, lat 3.477 ms stddev 1.068
progress: 12.0 s, 18325.8 tps, lat 3.488 ms stddev 1.116
progress: 13.0 s, 18427.3 tps, lat 3.474 ms stddev 1.038
progress: 14.0 s, 18503.1 tps, lat 3.458 ms stddev 0.868
progress: 15.0 s, 17922.4 tps, lat 3.569 ms stddev 1.320
progress: 16.0 s, 17850.9 tps, lat 3.582 ms stddev 1.099
progress: 17.0 s, 18216.9 tps, lat 3.513 ms stddev 1.146
progress: 18.0 s, 18229.6 tps, lat 3.508 ms stddev 1.050
progress: 19.0 s, 17799.9 tps, lat 3.593 ms stddev 1.568
progress: 20.0 s, 18392.8 tps, lat 3.474 ms stddev 1.158
progress: 21.0 s, 18319.8 tps, lat 3.495 ms stddev 1.105
``` 

My hack is at https://github.com/citusdata/citus/tree/feature/copyfuncs - I chose to implement it myself, because it's perhaps not entirely obvious how to do so.  With that model in mind, we should also do the same with equalfuncs, then we can get rid of TaskListUnion() etc.

**Comment by ozgune** [comment]
@mtuncer -- Could you also run 1-2 quick benchmarks and share #1477's benefits (maybe similar to the one @onderkalaci has in the original description)?

I have two ideas, but we could choose to run different ones too:

1. Standard Citus Cloud formation, and a table with 16 columns
2. Standard Citus Cloud formation, and a table with jsonb columns (similar to the github_events one we have on our website)

**Comment by mtuncer** [comment]
I have run test on ec2  with master + 2 worker on using c4.2xlarge nodes. I used 16 and 32 column int tables with 128 shards. Used pgbench for 20 seconds to run a file that inserts 4 rows to different shards.

| Inserts per second | before | after | difference |
| :----------------- | -----: | -----: | :---: |
| 16 columns    | 2000 |  2400 |  20% |
| 32 columns | 1850 | 2200| 19% |

**Comment by mtuncer** [comment]
previous benchmark was run with few number of clients (```pgbench -f t2_ins.sql -U ubuntu -n -T 20 -j 32 -c 4  postgres```)

I run another benchmark with ```-j 64 -c 64``` to generate higher throughput.

| Inserts per second | before | after | difference |
| :----------------- | -----: | -----: | :---: |
| 16 columns    | 20000 |  26000 |  30% |
| 32 columns | 14000 | 22500| 60% |

We are saving big but just removing serialization

**Comment by ozgune** [comment]
@mtuncer -- Thanks for the update. I had two quick questions.

* Did you run pgbench from a separate EC2 instance or on the coordinator node? -- I'm asking just to clarify
* When you run the tests with 32 shards (our default), do you see any difference?

**Comment by mtuncer** [comment]
@ozgune This results are from the test when I run pgbench on coordinator node.  For some reason running pgbench on a different node resulted lower insert rate (about 20-30%) in both before/after configurations.

When I run in 32 shard configuration I still saw the better results, but I did not test this on my test cluster. I could generate the numbers if you want to see.

**Comment by mtuncer** [comment]
Hey @ozgune 

Here is another comparison. This time margins are closer due to using a different ec2 setup. I picked a different SSD on the same hardware and insert rate went down a bit.
I have tested 32 and 128 shard configuration on 16 and 32 column tables using pgbench with ```-n -T 20 -j 64 -c 64``` parameters as before. pgbench is run on both on coordinator (l) and a remote node (r) 

| Inserts per second | before (l) | after (l) | speedup (l) | before (r) | after (r) | speedup (r) |
| :----------------- | -----: | -----: | :---: | -----: | -----: | :---: |
| 16 columns (32)    | 12360 |  13450 |  9% | 12100 |  13200 |  9% |
| 32 columns (32)| 10700 | 12700| 19% |  10200 | 12850 | 26% |
| 16 columns  (128)   | 11350 |  12250 |  8% | 12250 |  13000 |  6% | 
| 32 columns (128) | 10150 | 11850| 17% |  10150 | 11800 | 16% |

Speedup is less than previous comparison possibly due to insert rates are lower, and single insert time is spend by other factors (network/disk etc). But still we observed up to 20% difference when number of columns is 32. We should see even further speedups with higher number of columns.

Other than that the test does not show a significant difference between inserting from coordinator node vs a different node. Having large number of shards has slightly worse performance.
