### ISSUE TITLE
the next tenant is like oceanbase?

### ISSUE THREAD

**Issue by GPF199541** [citusdata/citus#7039]
The current version of multi tenant is not very suitable for most production

**Comment by onderkalaci** [comment]
Can you elaborate a little more? What part of Citus is not suitable for production?

**Comment by GPF199541** [comment]
the citus tenant is not like oceanbase, We want to create a large citus cluster，then assign an independent schema to one application,for more control resource usage

**Comment by mulander** [comment]
Hi @GPF199541, we just released Citus 12.0 with schema-based sharding support. Read more about it here: https://www.citusdata.com/blog/2023/07/18/citus-12-schema-based-sharding-for-postgres/

Does this fit your application requirements?

**Comment by GPF199541** [comment]
so good, my application can use this function,but if citus can control the resources of each tenant,we can support some high priority systems,The current architecture is prone to mutual influence among tenants

**Comment by mulander** [comment]
@GPF199541 we have multi tenant monitoring, it shows you CPU utilization and query traffic per tenant. There is no enforcement mechanism but you can monitor the usage and decide to isolate tenants based on that:

https://www.citusdata.com/blog/2023/05/12/tenant-monitoring-in-citus-and-postgres-with-citus-stat-tenants/

Tenant monitoring works both for schema-based and row-based sharding.

I'm closing this ticket as I think we covered all the questions raised here. If there are specific feature ideas, feel free to file them as separate issues with as much details as possible.

**Comment by GPF199541** [comment]
thanks,although there is monitoring, we are concerned that tenants are competing for resources with each other. It would be better if we could control it in advance. This is just a suggestion
