### ISSUE TITLE
why two citus wokers  qps  low than a single-node postgres?

### ISSUE THREAD

**Issue by lygn128** [citusdata/citus#7047]
hi:
1 i deploy a citus cluster with two worker, and distribution tables with column  id(auto incr)
2 i do multi thread insert 
3 but the result show that:  the citus qps is low than a single postgres
4 i change the concurent, but the result is the same;

if you have some suggestion？thank you very much.

**Comment by marcocitus** [comment]
The added latency lowers per-connection throughput.

Citus will only help in the OLTP case if a single node is unable to keep up with the workload (reaching CPU or disk bottlenecks).
