### ISSUE TITLE
DDL commands fail on high number of shard count

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#709]
If we try to create an index on a table with the high number of shards such as 4096, index creation fails. Note that this used to work with 5.1. I tested this on a cluster 5.1, it worked. Then, I upgraded the master to 5.2 candidate, it started to fail for the same index creation command. This is mostly related to the connection count. The same problem exists also for ALTER TABLE.

Steps to replicate:

``` sql
CREATE TABLE lineitem
(
    l_orderkey    BIGINT not null,
    l_partkey     INTEGER,
    l_suppkey     INTEGER,
    l_linenumber  INTEGER,
    l_quantity    DOUBLE PRECISION,
    l_extendedprice  DOUBLE PRECISION,
    l_discount    DOUBLE PRECISION,
    l_tax         DOUBLE PRECISION,
    l_returnflag  CHAR(1),
    l_linestatus  CHAR(1),
    l_shipdate    DATE,
    l_commitdate  DATE,
    l_receiptdate DATE,
    l_shipinstruct CHAR(25),
    l_shipmode     CHAR(10),
    l_comment      VARCHAR(44)
);

SELECT master_create_distributed_table('lineitem', 'l_orderkey', 'hash');
SELECT master_create_worker_shards('lineitem', 1024, 1);
```

``` sql
CREATE INDEX test_idx ON lineitem(l_partkey);

WARNING:  connection failed to ip-10-166-119-201.ec2.internal:5432
DETAIL:  could not translate host name "ip-10-166-119-201.ec2.internal" to address: System error
ERROR:  could not establish a connection to all placements of shard 107044
```

Settings on the master and workers;

```
echo "log_statement = 'all'" >> data/postgresql.conf
echo "max_prepared_transactions = 1000" >> data/postgresql.conf
echo "max_connections=1000" >> data/postgresql.conf
```

**Comment by metdos** [comment]
Related to connection handling in #704.

**Comment by ozgune** [comment]
We also talked about this issue in #1211. Once we implement this check, we should also error out with a descriptive message that explains to the user what the underlying issue is.

**Comment by lithp** [comment]
This could be fixed by not using a connection per shard. I haven't thought very hard about what this means given our new connection API but it's possible to open just one connection per machine and then pipeline the commands for each shard down those connections. For this we might have to give up the ability to run DDL commands in a transaction which also includes DML, but that doesn't sound like a bad tradeoff to make given the alternative is "don't have a large number of shards if you want DDL".

**Comment by marcocitus** [comment]
Fixed by adaptive executor
