### ISSUE TITLE
INSERT INTO (SELECT ...) syntax returns "INSERT 0 0" instead of erroring out. We should either evaluate implementing this functionality, or error out upon its execution.

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#71]
INSERT INTO (SELECT ...) syntax returns "INSERT 0 0" instead of erroring out. We should either evaluate implementing this functionality, or error out upon its execution.

**Comment by ozgune** [comment]
@onderkalaci -- We made improvements to our ``INSERT INTO (SELECT ...)`` logic in the past two releases. Do you know if Citus still exhibits this behavior?

If it doesn't, could you close this issue?
