### ISSUE TITLE
Rebalancer should use local execution for shard-size checks if the shard is on coordinator

### ISSUE THREAD

**Issue by onurctirtir** [citusdata/citus#7106]
If the shard that we're about to move has just been created in the current transaction, remote connections that the rebalancer opens to the local node (coordinator) fails to find the shard.

If the shard is local, it would make sense to run shard-size-calculation query via local execution.

```sql
SELECT citus_add_node('localhost', 9700, 0);
SELECT citus_add_node('localhost', 9701);
SELECT citus_add_node('localhost', 9702);

-- enable shards on coordinator
SELECT citus_set_node_property('localhost', 9700, 'shouldhaveshards', true);

BEGIN;
  CREATE TABLE dist(a int);
  SELECT create_distributed_table('dist', 'a');

  -- try to move one shard from coordinator to another worker node
  SELECT citus_move_shard_placement(
    shardid,
    'localhost', 9700,
    'localhost', 9701,
    shard_transfer_mode => 'block_writes'
  )
  FROM citus_shards WHERE nodeport = 9700
  LIMIT 1;
WARNING:  relation "public.dist_102008" does not exist
ERROR:  cannot get the size because of a connection error
Time: 30.816 ms
```

**Comment by JelteF** [comment]
Is there a real usecase for this or did you find this just by accident. I think unless we have real usecase, then we can consider this "just don't do this".  Pretty much no-one should be running `citus_move_shard_placement` manually. It should only be called by the rebalancer.

**Comment by onurctirtir** [comment]
I found this when implementing lazy-table conversion for Citus local tables.

Right now, when `create_reference_table()` issued for a Citus local table, we first undistribute it and then we make a reference table from it.

And the idea is that we can avoid from undistributing it by simply updating the metadata, then we can replicate the shard that present on coordinator to the other nodes.

However, this becomes a problem in such a scenario:

```sql
CREATE TABLE referenced_table(a int UNIQUE, b int);
CREATE TABLE referencing_table(a int, b int,
    FOREIGN KEY (a) REFERENCES referenced_table(a));

BEGIN;
  SELECT create_reference_table('referenced_table');
  -- now referencing_table became a Citus local table

  -- fails due to bug reported in this issue because the shard of referencing_table is not
  -- visible to remote connections
  SELECT create_distributed_table('referencing_table', NULL, distribution_type=>null);
```
