### ISSUE TITLE
The explicit NULL column constraint is not working in Citus 12

### ISSUE THREAD

**Issue by pbav** [citusdata/citus#7110]
```sql
ALTER TABLE a ADD COLUMN b INT NULL;
```
```
[2023-08-11 11:53:30] [XX000] ERROR: unsupported constraint type
[2023-08-11 11:53:30] Detail: constraint type: 0
```

Citus 12.0.0 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3), 64-bit
PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

It worked on Citus 11.2.1:
Citus 11.2.1 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3), 64-bit
PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

The `NOT NULL` constraint works on both versions.
Code like this, with the explicit NULL clause, is generated by Django.

**Comment by pbav** [comment]
Workaround - create a custom database backend:
```python
# db_backend/base.py
from django_multitenant.backends.postgresql.base import DatabaseWrapper as CitusDatabaseWrapper, TenantDatabaseFeatures

class DatabaseFeatures(TenantDatabaseFeatures):
    # The explicit NULL constraint (ALTER TABLE a ADD COLUMN b INT NULL) is broken in Citus 12
    implied_column_null = True

class DatabaseWrapper(CitusDatabaseWrapper):
    features_class = DatabaseFeatures
```

```python
# your_project/settings.py
DATABASES = {
    'default': {
        'ENGINE': 'your_project.db_backend',
        ...
    }
}
```

**Comment by JelteF** [comment]
I'm pretty sure that is fixed by this PR: https://github.com/citusdata/citus/pull/7093

It will be part of the next patch release.
