### ISSUE TITLE
The node is damaged, causing it to be unable to write

### ISSUE THREAD

**Issue by azeng528** [citusdata/citus#7121]
结构：
co节点+3worker
repl_test表是2副本，6shard
sysbench=# select * from pg_dist_shard_placement;
 shardid | shardstate | shardlength |  nodename  | nodeport | placementid
---------+------------+-------------+------------+----------+-------------
  102098 |          1 |           0 | 192.168.2.111 |     5434 |         137
  102099 |          1 |           0 | 192.168.2.111 |     5436 |         139
  102100 |          1 |           0 | 192.168.2.111 |     5434 |         142
  102100 |          1 |           0 | 192.168.2.111 |     5436 |         153
  102098 |          1 |           0 | 192.168.2.111 |     5438 |         163
  102099 |          1 |           0 | 192.168.2.111 |     5438 |         164
(6 rows)

but 5438对应的实例 damaged
![image](https://github.com/citusdata/citus/assets/19300752/31b3c57c-6f8d-4945-ac3d-7e2e1e453422)

请问我应该如何修复并且将5438替换掉？

**Comment by onderkalaci** [comment]
In order to use a system with high availability, use Citus + Patroni https://www.citusdata.com/blog/2023/03/06/patroni-3-0-and-citus-scalable-ha-postgres/
