### ISSUE TITLE
Auto Vacuum Settings Per Table

### ISSUE THREAD

**Issue by jnels124** [citusdata/citus#7129]
We are attempting to configure some autovacuum settings on a per table basis. This works on a standard postgres table but produces errors when attempting to configure in a citus cluster.
```
create table if not exists test_bigserial
(
    id                 bigserial,
    created_timestamp  bigint,
    delegating_spender bigint  default null,
    deleted            boolean default false,
    metadata           bytea,
    serial_number      bigint    not null,
    spender            bigint  default null,
    timestamp_range    int8range not null,
    token_id           bigint    not null
) partition by range (id);
```

Followed By 
```
alter table if exists test_bigserial set (
    autovacuum_vacuum_insert_scale_factor = 0
    );
```

Produces:
'ERROR:  unrecognized parameter "autovacuum_vacuum_insert_scale_factor"'

I understand with citus there are multiple shards and hence more vacuum worker processes on a per "table" basis; however, it would still be useful in some cases to configure these settings. Are there future plans to provide this support? Are there known limitations for this support preventing implementation? Any additional details you can provide on the issue will be greatly appreciated.

**Comment by JelteF** [comment]
The commands you shared fail for me on PG15 without Citus installed. So this seems to be a Postgres limitation. You apparently cannot set autovacuum settings on the parent table when you use Postgres partitioning. I guess you have to configure it on the child tables.

**Comment by jnels124** [comment]
@JelteF thanks for the quick response.
