### ISSUE TITLE
Weird error on materialized view creation

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#713]
``` sql
CREATE MATERIALIZED VIEW materialized_view_test AS SELECT * from lineitem;
ERROR:  cannot create temporary table within security-restricted operation
```

**Comment by metdos** [comment]
Related to #40.

**Comment by anarazel** [comment]
That's because you can't create temp tables while a matview is being created / refreshed (security issues).  Once we get rid of those, we should support matviews.

**Comment by lukashes** [comment]
Is any new activities to resolve current problem?

**Comment by lukashes** [comment]
Is no way to create materialized view yet?

**Comment by metdos** [comment]
Hi @lukashes, we will consider to implement it while revising our priorities for next development cycle. Could you let us know about your use-case? For example, how are you planning to use materialized views?

Thanks.

**Comment by lukashes** [comment]
I have about 10,000,000 rows per day in citus+cstore_fdw and if query covers 1 month - it is too slow.

I want create materialized view to keep aggregated data of last month. And refresh it after any new COPY requests into citus cluster.

**Comment by metdos** [comment]
Hi @lukashes, until we implement materialized views, you can try to use distributed roll-ups and roll-up from raw data to aggregate tables similar to Cloudflare (They explain details of their architecture in this [blog post]( https://blog.cloudflare.com/scaling-out-postgresql-for-cloudflare-analytics-using-citusdb/)).

Moreover, with the upcoming release, we are adding implicitly co-located tables and INSERT INTO ... SELECT. Therefore, doing distributed roll-ups will be very easy.

**Comment by lukashes** [comment]
@metdos thank you for attention.

Yes, I did the same (if I get topic right): every 5 minutes append raw data, then recalculate it. Finaly: one shard - one day. But `sum(...)` by month (about 300,000,000 rows) is really slow.

Or you mean, I need calculate 3 types of storage and save it in different distributed tables? Ex: stats_daily, stats_monthly, stats_yearly?

**Comment by metdos** [comment]
> Or you mean, I need calculate 3 types of storage and save it in different distributed tables? Ex: stats_daily, stats_monthly, stats_yearly?

Yes, I mean this. If you don't want to keep your raw data for a long time, you can delete it after inserting aggregates to aggregate tables(stats_daily, stats_monthly, stats_yearly).

Does this make sense?

**Comment by lukashes** [comment]
> Does this make sense?

Now I do not know. May be many inserts/deletes loads autovacuum, or table unavailability during truncating. I am going to check decision. You said about `INSERT INTO ... SELECT`...  When is planned release?

**Comment by metdos** [comment]
> You said about INSERT INTO ... SELECT... When is planned release?

You get it from master or release-6.0 branches. Binaries will be ready mid-November. Also, we use GitHub issues to track bug and features, but you can send your questions to the public users group:
citus-users@googlegroups.com

**Comment by ozgune** [comment]
I wanted to add a quick comment to this issue.

We now have ``INSERT INTO ... SELECT`` support available for distributed tables, where the source and destination tables are colocated with each other. We intend to add documentation on this feature soon; and we also have a blog post that demonstrates this feature: https://www.citusdata.com/blog/2016/11/29/event-aggregation-at-scale-with-postgresql

@lukashes -- does this feature help at all with your use case? If you have questions or comments, please feel free to ping us.

**Comment by lukashes** [comment]
As I understood (after reading sources) colocated may be only hash distributed tables? And I could not do "INSERT INTO ... SELECT" in my case.  Later I will check it again.
