### ISSUE TITLE
citus add worker error：password

### ISSUE THREAD

**Issue by azeng528** [citusdata/citus#7134]
#执行如下命令添加worker报错
select * from citus_add_node('XXXXX',5438);
ERROR:  connection to the remote node XXXX5438 failed with the following error: fe_sendauth: no password supplied
citus_add_node not support username、password write，so，when i add worker，How to Write Account and Password
Could you please provide the method and documentation

**Comment by onurctirtir** [comment]
You might want to check "Configure connection and authentication" section in https://docs.citusdata.com/en/v12.0/installation/multi_node_debian.html#steps-to-be-executed-on-all-nodes.

Please feel free to re-open the issue if this doesn't help.
