### ISSUE TITLE
Command counter increment in the wrong place

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#714]
On [InsertShardRow](https://github.com/citusdata/citus/blob/512d1791c25797b2b0e4d8b4c961d47d6efb64cb/src/backend/distributed/master/master_metadata_utility.c#L427), we first call `CommandCounterIncrement()` then `CitusInvalidateRelcacheByRelid(relationId);`.

This may prevent to skip invalidation of the distributed table in the next access within the same session. In citus-mx [41](https://github.com/citusdata/citus-mx/pull/41/files) we proposed a fix for this.

**Comment by anarazel** [comment]
Can you open a PR for this? This should just be fixed (and your fix looks good to me).

**Comment by jasonmp85** [comment]
@anarazel, is this something we should backport? Catching up on `cherry-pick`ing right now…
