### ISSUE TITLE
PG16 Update (GRANT...WITH INHERIT | SET) 

### ISSUE THREAD

**Issue by francisjodi** [citusdata/citus#7148]
Extending  GRANT `ADMIN` options in PG16 update to encompass `WITH INHERIT` or `WITH SET`  instead of just `WITH ADMIN OPTION`

The ability to control roles behavior using the `GRANT` statement, along with options like `WITH INHERIT` and `WITH ADMIN`, adds privilege management.

The newly proposed `SET` permission in the `GRANT` to restrict certain actions based on role capabilities, which maintains consistency and security.

https://github.com/citusdata/citus/issues/7138

**Comment by francisjodi** [comment]
@naisila Can you please review?

**Comment by naisila** [comment]
@francisjodi sure, please add me as a reviewer to the pull request when it is ready
