### ISSUE TITLE
Allow primary or unique key constraints on non-partition column for single shard (broadcast) table

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus#715]
Currently if I create a table with a primary key column and distribute the table on a non-primary key. It doesn't let me do it. Having a primary key constraint on a non-partition column is in general hard in a distributed setup because for every insert the constraint should be checked on all the shards on all the workers.
But if I guess if the table is one shard table(a typical broadcast table), allowing primary key constraint on the non-partition column could be done, because the check need not be done on more than 1 shard.

**Comment by ozgune** [comment]
I'm noting #760 and #827 as related issues.

**Comment by onderkalaci** [comment]
I don't see anything preventing that considering single-shard reference tables. Though, we should add a regression test for this while closing the issue.

**Comment by onderkalaci** [comment]
Fixed by #1018, closing the issue.
