### ISSUE TITLE
Cache lookup failed error in logs after upgrade from 10.2 to 11.3

### ISSUE THREAD

**Issue by adnanitdev** [citusdata/citus#7150]
I have citus 10.2 in kubernetes, I am trying to upgrade it to 11.3 by changing the image tag to `citusdata/citus:11.3.0-pg14.`

Here are the steps I followed to upgrade:

1. configured `citus.enable_version_checks` to false
2. Restarted the deployment for the above change to apply
3. updated the image to `citusdata/citus:11.3.0-pg14.`
4. restarted the deployment again after updating the image
5. once the pod is up and running, executed `ALTER EXTENSION citus UPDATE;` 
6. checked the version and the version shows as 11.3 
7. called the function `CALL citus_finish_citus_upgrade();`  I see the message  `Preparing to sync the metadata to all nodes`

After performing the above steps, I see below errors in the logs:

CONTEXT:  Citus maintenance daemon for database 13757 user 10
WARNING:  cache lookup failed for pg_dist_cleanup, called too early?
CONTEXT:  Citus maintenance daemon for database 13757 user 10
        Citus maintenance daemon for database 13757 user 10
ERROR:  cache lookup failed for pg_dist_background_task, called too early?
CONTEXT:  Citus maintenance daemon for database 13757 user 10
LOG:  background worker "Citus Maintenance Daemon: 13757/10" (PID 804) exited with exit code 1

Even before running the Alter extension command I see the version as 11.3. is this normal?

I have tested this in standalone mode and also with two workers however I end up with same error in logs. Is there a workaround for this or am I missing anything? 

I see both the tables `pg_dist_background_task` and `pg_dist_cleanup` in `pg_catalog` schema

**Comment by emelsimsek** [comment]
> Even before running the Alter extension command I see the version as 11.3. is this normal?

If you db is not recreated when changing to `citusdata/citus:11.3.0-pg14` tag, this is not expected. 

If you can tell me more about the docker update steps (I am not a kuberbetes user), I can try this on my side.
