### ISSUE TITLE
 cannot find shard interval

### ISSUE THREAD

**Issue by xiaoweihong** [citusdata/citus#7151]
when one node is offline ,remove the node from cluster . when insert data,errors
ERROR:  cannot find shard interval
DETAIL:  Hash of the partition column value does not fall into any shards. 

remove node from the blog 
http://citusdb.cn/?p=4002

how can i recovery the cluster?thanks

**Comment by naisila** [comment]
The problem is that you manually removed rows from pg_dist_placement
`delete from pg_dist_placement where groupid = 2;`
With this command, you deleted the metadata info, but the placements are still in the node with groupid = 2. You were able to remove the node, but theoretically that was wrong.

**Comment by xiaoweihong** [comment]
yes,but the placements with groupid = 2 has been removed,and the node 2 is shutdown. is there any metadata exist?

**Comment by xiaoweihong** [comment]
> The problem is that you manually removed rows from pg_dist_placement `delete from pg_dist_placement where groupid = 2;` With this command, you deleted the metadata info, but the placements are still in the node with groupid = 2. You were able to remove the node, but theoretically that was wrong.

yes,but the placements with groupid = 2 has been removed,and the node 2 is shutdown. is there any metadata exist?

**Comment by naisila** [comment]
Are you still able to connect to node 2? The placements should still be there - that's the only way to recover the data from those placements.

**Comment by xiaoweihong** [comment]
> Are you still able to connect to node 2? The placements should still be there - that's the only way to recover the data from those placements.

node 2 machine is broken, cannot connect. if can lose node 2 data, can  any way to do?

**Comment by naisila** [comment]
If you cannot connect to node 2, then there is no way to retrieve the data.

To recover your cluster, you can manually create the missing placements in your coordinator.

For example, if you see this error: `ERROR:  no active placements were found for shard shardid`
Then, in the coordinator you can run:
```SQL
-- run only once
SELECT citus_set_coordinator_host('localhost', :coordinator_port);

-- run the following for every shardid for which you encounter the error
-- i.e. all shardids that were in node 2 and can't be reached anymore
BEGIN;
CREATE TABLE tablename_shardid(use same table definition as table_name);
-- pick a placementid that isn't already in pg_dist_placement
INSERT INTO pg_dist_placement VALUES (placementid, shardid, 1, 0, 0);
INSERT INTO pg_dist_shard_placement VALUES (shardid, 1, 0, 'localhost', :coordinator_port, placementid);
COMMIT;
```

**Comment by naisila** [comment]
Note for the future: never manually delete rows from metadata tables, most probably things will be broken afterwards anyway.

**Comment by naisila** [comment]
@xiaoweihong did this work for you?

**Comment by xiaoweihong** [comment]
I test it ok. But I use another way to solve it. Use 
`SELECT alter_distributed_table('xxxx', shard_count:=60, cascade_to_colocated:=true);`
We have a lot of data,it take a long time to execute. When finished, search and insert is ok

**Comment by shankarmn94** [comment]
ccnsapp=# BEGIN
ccnsapp-# ;
BEGIN
ccnsapp=*# CREATE TABLE service_ports_20645(use same table definition as table_name);
ERROR:  syntax error at or near "table"
LINE 1: CREATE TABLE service_ports_20645(use same table definition a...
                                                  ^


what i have to mention heree @naisila

**Comment by shankarmn94** [comment]
ccnsapp=*# DROP TABLE public.service_ports CASCADE;
ERROR:  there is a shard placement in node group 2 but there are no nodes in that group
CONTEXT:  while executing command on 10.104.0.9:5432
SQL statement "SELECT master_remove_distributed_table_metadata_from_workers(v_obj.objid, v_obj.schema_name, v_obj.object_name)"
PL/pgSQL function citus_drop_trigger() line 13 at PERFORM

how to resolve
