### ISSUE TITLE
Individual Task Query while using tasktracker executor cannot exceed 12kb

### ISSUE THREAD

**Issue by saicitus** [citusdata/citus#716]
When the user runs a `SELECT` query and has the executor type set to `task-tracker`, the master node breaks up the query into query fragments and sends query fragments to worker nodes.  On each worker, there's a daemon process. The daemon process assigns individual query fragments to itself to execute. There is a limit on the length of these query fragments, they cannot exceed 12kb. (edited)
If the individual task query exceeds 12kb, then we get this error:

```
WARNING: could not receive query results from <worker-ip>:5432
DETAIL: Client error: task call string exceeds maximum assignable length
```

All the individual task queries are stored in shared memory and hence we put hard limit on what length the individual task query can be.

**Comment by ozgune** [comment]
I'm adding a few more details. We ``#define`` each task's maximum size on the worker node here:
https://github.com/citusdata/citus/blob/master/src/include/distributed/task_tracker.h#L27

@saicitus / @marcocitus -- I have a quick question. I remember that we talked about batching tasks when we were assigning them from the master node to the workers. If we implemented batching, does it interact with this 12 KB setting?

**Comment by anarazel** [comment]
On 2016-08-15 14:02:10 -0700, Ozgun Erdogan wrote:
> I'm adding a few more details. We ``#define`` each task's maximum size on the worker node here:
> https://github.com/citusdata/citus/blob/master/src/include/distributed/task_tracker.h#L27
> 
> @saicitus / @marcocitus -- I have a quick question. I remember that we talked about batching tasks when we were assigning them from the master node to the workers. If we implemented batching, does it interact with this 12 KB setting?

I think the right way here would be to put/append the task into a (temporary)
file, and refer to it from to it from the shared memory entry. Similar
to how pg_stat_statement works these days.

**Comment by ozgune** [comment]
When we picked 12KB as the maximum task size, PostgreSQL's ``shared_buffers`` defaulted to 32 MB. Now that the default ``shared_buffers`` is higher, what if we simply increased the maximum task size ``#define`` too?

Alternatively, we could make the maximum task setting configurable -- as a quick fix?

**Comment by anarazel** [comment]
This really shouldn't be related to shared buffers - were computing our own addition to the shared men allocation...

I haven't looked closely enough. Is the size of individual tasks or the number of simultaneous assignments the problem?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anarazel** [comment]
Short term the best fix might be to make ```struct WorkerTask``` dynamically sized. The easiest way for that appears to be to move the ```taskCallString``` to the end of the struct and make it an array of size ```FLEXIBLE_ARRAY_MEMBER```. Then we can simply, at startup time, change the entry size calculation in ```TaskTrackerShmemInit```. E.g. something like
```
...
	memset(&info, 0, sizeof(info));
	info.keysize = sizeof(uint64) + sizeof(uint32);
	info.entrysize = sizeof(WorkerTask) + guc_task_size;
	info.hash = tag_hash;
	hashFlags = (HASH_ELEM | HASH_FUNCTION);
...
```
the relevant bit is ``` + guc_task_size```. The remainder of the work then would be to actually add the guc (with a proper name), and debate whether the default should be higher.

**Comment by mtuncer** [comment]
We have 4 more places that does allocation based on ```sizeof(WorkerTask)```
- ```TaskTrackerShmemSize``` estimates shared memory size needed for task tracking
- ```SchedulableTaskList``` creates list of schedulable tasks --> ```tasksToScheduleCount * palloc0(sizeof(WorkerTask))```
-  ```SchedulableTaskPriorityQueue```  allocates flat memory for ```sizeof(WorkerTask) * queueSize``` bytes
- ```SchedulableTaskPriorityQueue``` qsort accepting ```sizeof(WorkerTask)


Proposed GUC variable : WorkerTaskStringSize
 
We could use a macro to define it like 
```c
#define WorkerTaskSize (offsetof(WorkerTask, taskCallString) +  WorkerTaskStringSize)
```

Proposed ranges for the new variable. 
Min : 8192
Max : 65536  (16 bits should be enough for everybody right ?)
Default : 12288 (the same)

Reducing min value from default one probably would not make much sense, usable only if we  want to take a smaller portion of the shared memory.

**Comment by mtuncer** [comment]
GUC variable context should be ```PGC_POSTMASTER``` similar to ```MaxWorkerNodesTracked```

**Comment by sumedhpathak** [comment]
Hey Murat, do you know how much memory each backend would actually end up allocating for some of these numbers? Does TaskTrackerShmemSize depend on other values like max-tracked-tasks-per-node etc? It might be useful to also get some current numbers for some of our production customers, so we can evaluate the memory impact.

**Comment by mtuncer** [comment]
Hey @sumedhpathak 
```TaskTrackerShmemSize``` mostly depends on 2 things.  ```MaxTrackedTasksPerNode``` and 
```TASK_CALL_STRING_SIZE```.

formula is more like
```
TaskTrackerShmemSize = 64 + MaxTrackedTasksPerNode * (TASK_CALL_STRING_SIZE + 160) + some_hash_related_number
```
I don't have formula for some_hash_related_number  in my experiments it changed between 2% and 4% of TaskTrackerShmemSize.

We also require some shared memory for ```MaintenanceDaemonShmem``` but it is pretty low (7056 bytes in my local machine when max_worker_processes is set to 8) and can be ignored in our calculations.

With our current defaults (MaxTrackedTasksPerNode = 1024, TASK_CALL_STRING_SIZE = 12288) we require around 13MB of shared memory.

Here is the table of shared memory usage (in bytes) with respected to  ```MaxTrackedTasksPerNode (MTTPN)``` and ```TASK_CALL_STRING_SIZE(TCSS)```

MTTPN\TCSS | 8192 | 12288 | 65536
--------------|------: | ------: | -------:
1024  | 8831032 | 13098360 |70388712 |
2048  | 17659096 | 25670264 | 136634600 |
4096 | 34796408 | 51337560 | 273266232|

**Comment by mtuncer** [comment]
@sumedhpathak This is a small task, would you like me to prepare a design document and estimates for this ?

**Comment by ozgune** [comment]
@mtuncer -- We had example queries where lack of this feature hurt us. Could we test this change with those example queries (and the close this issue)?

**Comment by mtuncer** [comment]
I have added a regression test that checks failure when we have a task with long text. 

In order to manually test
create table with large number of columns. My test had
```sql
create wide_table (
   long_column_001 int,
   long_column_002 int,
   ....
   long_column_200 int
);
```

and perform a self join on this table using a non-partition column.

You can increase the setting, restart the server and run the same query to verify the query works.

**Comment by mtuncer** [comment]
waiting for queries from @saicitus

**Comment by mtuncer** [comment]
We haven't received actual user queries that lead to opening of this task. I had to rely on synthetic queries to test the fix.
