### ISSUE TITLE
Installing Citus on Postgresql 15 complied through source code.

### ISSUE THREAD

**Issue by Hannan2910** [citusdata/citus#7165]
Hello, I have postgresql15 installed through sorce code and want to install citus on it. I have tried the way suggested on documentation but it does not work for me. any other help would be appreciated.

**Comment by JelteF** [comment]
Can you share the commands that you're using and the error that you get?

**Comment by Hannan2910** [comment]
The major issue I was facing was not knowing where to add my bin/pg_config path. After reading the CONTRIBUTING.md file I was easily able to  install it. Please let me know if i should post a comment here on how to install it or this issue can be closed.
