### ISSUE TITLE
Failed to convert materialized views to reference table

### ISSUE THREAD

**Issue by hisahin** [citusdata/citus#7179]
I get the following error when I try to convert a table that is in the materialized view structure.

I have a small table that is 300mb. If I can distribute this table, I will gain a nice performance.

select create_reference_table('mtviewname');
ERROR:  mtviewname is not a regular, foreign or partitioned table

**Comment by emelsimsek** [comment]
Materialized views are not supported as distributed/reference citus tables. Do you need this table to be a view?
Is it possible to convert it to a regular table?
