### ISSUE TITLE
HeapTupleHeaderGetDatumLength() has a wrong argument

### ISSUE THREAD

**Issue by Green-Chan** [citusdata/citus#7230]
Hi!

Please, check out https://github.com/citusdata/citus/blob/v12.1.0/src/backend/distributed/executor/tuple_destination.c#L110
Shouldn't type of the argument be HeapTupleHeader?
And why not just use heapTuple.t_len? Isn't it valid here?

**Comment by onurctirtir** [comment]
> And why not just use heapTuple.t_len? Isn't it valid here?

Right, using ->t_len seems like a better idea here. And as always, code-contributions are welcome too :)
