### ISSUE TITLE
The size of pg_dist_transaction has become too large.

### ISSUE THREAD

**Issue by hancci** [citusdata/citus#7246]
### The size of pg_dist_transaction increases rapidly.
* **version** : 
   * PostgreSQL 12.2 
   * citus-v9.2-4
* **symptom**
* The size of pg_dist_transaction has become too large.
```sql
SELECT quote_ident(table_schema)||'.'||quote_ident(table_name) as name
      ,pg_relation_size(quote_ident(table_schema) || '.' || quote_ident(table_name)) as size
      ,pg_total_relation_size(quote_ident(table_schema) || '.' || quote_ident(table_name)) as total_size
     , pg_size_pretty(pg_relation_size(quote_ident(table_schema)|| '.' || quote_ident(table_name))) hr_size
     , pg_size_pretty(pg_total_relation_size(quote_ident(table_schema)|| '.' || quote_ident(table_name))) hr_total_size
FROM information_schema.tables
ORDER BY total_size DESC
LIMIT 1;

              name              |     size     |  total_size   | hr_size | hr_total_size
--------------------------------+--------------+---------------+---------+---------------
 pg_catalog.pg_dist_transaction | 808757878784 | 2604196560896 | 753 GB  | 2425 GB


select pg_size_pretty(pg_relation_size('pg_dist_transaction_group_index'));
 pg_size_pretty
----------------
 367 GB

select pg_size_pretty(pg_relation_size('pg_dist_transaction_unique_constraint'));
 pg_size_pretty
----------------
 1305 GB
(1 row)
```
* I checked the issue below and performed `SELECT recover_prepared_transactions();`, but it was not performed because the lock (ShareUpdateExlusiveLock) could not be acquired. 
   * https://github.com/citusdata/citus/issues/1614
* `Vacuum` and `Reindex` could not be performed similarly. This seems to be the effect of the issue below.
   * https://github.com/citusdata/citus/issues/2670 , https://github.com/citusdata/citus/pull/4184
* The lock hoder is `Citus Maintenance Daemon`. **What happens if I kill this process?**

**Can you help me on what to do? I want to `truncate` pg_dist_transaction.**

**Comment by onderkalaci** [comment]
> Vacuum and Reindex could not be performed similarly. This seems to be the effect of the issue below.
https://github.com/citusdata/citus/issues/2670 , https://github.com/citusdata/citus/pull/4184

Yes, you should consider upgrading to 9.5+, which I suggest to upgrade 12.0

> Can you help me on what to do? I want to truncate pg_dist_transaction.


To unblock the situation, prevent autovacuum on the table first:
``` 
 ALTER TABLE pg_dist_partition SET (autovacuum_enabled = false);
```

Then, wait for `SELECT recover_prepared_transactions();` to finish properly. Please do not truncate the table manually, that might cause data loss.

**Comment by hancci** [comment]
Thank you for your kind reply.
Unfortunately, I can't upgrade to 12.0 right now.

Actually I'm having a wraparound problem. 😢 
```sql
SELECT c.relnamespace::regnamespace as schema_name,
       c.relname as table_name,
       greatest(age(c.relfrozenxid),age(t.relfrozenxid)) as age,
       2^31-1000000-greatest(age(c.relfrozenxid),age(t.relfrozenxid)) as remaining
  FROM pg_class c
  LEFT JOIN pg_class t ON c.reltoastrelid = t.oid
 WHERE c.relkind IN ('r', 'm')
and c.relname in ('pg_dist_transaction');

 schema_name |     table_name      |    age     | remaining
-------------+---------------------+------------+-----------
 pg_catalog  | pg_dist_transaction | 2021297934 | 125185714

```
So I'm thinking of blocking the traffic, restarting, and truncate the table. 
I would like to ask for advice on whether this method is okay. 😢

**Comment by hancci** [comment]
Is `SELECT recover_prepared_transactions()` as fast as `truncate` ?

**Comment by onderkalaci** [comment]
> Is `SELECT recover_prepared_transactions()` as fast as `truncate` ?

definitely not, hard to guess how much time it'd take ~seq. scan time of `pg_dist_transaction`

**Comment by hancci** [comment]
I really appreciate your help in resolving the problem. Thank you so much. 😃
