### ISSUE TITLE
Can' t distribute table

### ISSUE THREAD

**Issue by DenSaoPin** [citusdata/citus#7252]
Hello, I'm trying to distribute my local 20GB table to a citus cluster but I getting an error.
"ERROR: failed to COPY to shard 102358 on 11.117.110.144:5432"
I checked, the distribution works for some time, but during use it consumed all the available memory on the machine, 8 GB were available, of which 7.5 are free.

Citus 11.0.7 on x86_64-pc-linux-gnu, compiled by gcc (AstraLinuxSE 8.3.0-6) 8.3.0, 64-bit gitref: HEAD(sha: 360537bc4)

**Comment by DenSaoPin** [comment]
Thanks for your answer, this is oom-kill and I don't have any swap but why does it crash the process due to out of memory, I have never encountered this in postgresql.
Can I make some changes in config to limit memory usage?

**Comment by emelsimsek** [comment]
You can try to reduce` work_mem` parameter of Postgres on all your nodes. This will perevent out of memory errors but Postgres will use disk files when it needs memory.

**Comment by DenSaoPin** [comment]
@emelsimsek I used this option and it doesn't work
