### ISSUE TITLE
Citus does not work with pglogical

### ISSUE THREAD

**Issue by rootbdfy** [citusdata/citus#7260]
My config:
```
shared_preload_libraries = 'citus,pglogical'
```
SHOW shared_preload_libraries with 11.3
```
 shared_preload_libraries 
--------------------------
 pglogical
(1 row)
```
SHOW shared_preload_libraries with 12.1
```
 shared_preload_libraries 
--------------------------
 citus
(1 row)
```

I use Debian 11 with Postgresql 15.4-2

**Comment by JelteF** [comment]
What is the error that you get?

**Comment by rootbdfy** [comment]
In case of using Citus v11.3:
```
CREATE EXTENSION citus;
ERROR: Citus can only be loaded via shared_preload_ libraries
HINT: Add citus to shared_preload_libraries configuration variable in postgresql.conf in master and workers. Note that citus should be at the beginning of shared_preload_libraries.
```

In case of using Citus v12.1:
```
FATAL:  pglogical is not in shared_preload_libraries
```

**Comment by JelteF** [comment]
Did you try restarting postgres, because you're saying that your config looks like this:
```
shared_preload_libraries = 'citus,pglogical'
```
but then the `SHOW` commands output don't follow that.

Is there maybe a `postgresql.auto.conf` file that is overriding your setting from `postgresql.conf`.

**Comment by rootbdfy** [comment]
I even tried completely restarting the server.
I not have any overriding configs:
```
ls -la /etc/postgresql/15/main/
total 68
drwxr-xr-x 3 postgres postgres  4096 Oct 16 16:11 .
drwxr-xr-x 3 postgres postgres  4096 Aug 17 16:00 ..
drwxr-xr-x 2 postgres postgres  4096 Aug 17 16:01 conf.d
-rw-r--r-- 1 postgres postgres   315 Aug 17 16:01 environment
-rw-r--r-- 1 postgres postgres   143 Aug 17 16:01 pg_ctl.conf
-rw-r----- 1 postgres postgres  4994 Aug 17 16:33 pg_hba.conf
-rw-r----- 1 postgres postgres  1636 Aug 17 16:01 pg_ident.conf
-rw-r--r-- 1 postgres postgres 30103 Oct 16 16:07 postgresql.conf
-rw-r--r-- 1 postgres postgres   317 Aug 17 16:01 start.conf
```
```
s -la /etc/postgresql/15/main/conf.d/
total 8
drwxr-xr-x 2 postgres postgres 4096 Aug 17 16:01 .
drwxr-xr-x 3 postgres postgres 4096 Oct 16 16:11 ..
```

**Comment by JelteF** [comment]
Maybe the `postgresql.auto.conf` is in the data directory? Because Debian splits the data and config directory.

**Comment by rootbdfy** [comment]
No, I use `plocate postgresql.auto.conf` and get empty answer.

**Comment by rootbdfy** [comment]
I found `shared_preload_libraries = 'auto_explain'`. After deleting this line, edited the main line
```
shared_preload_libraries = 'citus,pglogical,auto_explain'
```
That works. Thanks !

**Comment by JelteF** [comment]
Closing since issue is resolved.

**Comment by onderkalaci** [comment]
> I found `shared_preload_libraries = 'auto_explain'` in end of postgresql.conf. After deleting this line, edited the main line
> 
> ```
> shared_preload_libraries = 'citus,pglogical,auto_explain'
> ```
> 
> That works. Thanks !

note that Citus and auto-explain are incompatible , see https://github.com/citusdata/citus/issues/6448
