### ISSUE TITLE
Add extensions to database.dev

### ISSUE THREAD

**Issue by riderx** [citusdata/citus#7268]
Hello i saw this extension is exactly what I need in my supabase instance .

so I would like to know if there is plan to add it to the database store to install it on runtime:
https://database.dev/

**Comment by thanodnl** [comment]
We don't have plans to do so, but thank you for bringing up the project, wasn't aware of it.

Having a quick look at the landing page I don't think Citus will be able to be listed there.

> For PostgreSQL trusted language extensions

We are pretty much not written in a way where it can be considered a trusted language extension. By definition Citus has deep hooks into postgres where it can do anything and everything, eg. not a sandbox environment where managed service providers can blindly install and trust Citus.
