### ISSUE TITLE
master_apply_delete_command() calls don't block each other

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#727]
Create multiple shards

``` sql
SET citus.shard_max_size to '100MB';
COPY lineitem from '/home/ubuntu/tpch_2_13_0/lineitem.tbl' WITH DELIMITER '|';
```

Run **two** master_apply_delete_command() concurrently

``` sql
SELECT * from master_apply_delete_command('DELETE FROM lineitem');
```

Observe that one of the calls will fail;

```
ERROR:  could not find valid entry for relationId: 34972 and shard 110613
```

Minor Edit: Clarify that we run **two** master_apply_delete_command() concurrently.

**Comment by ozgune** [comment]
@metdos -- I had a clarification question.

We see this error message when the user runs a ``COPY`` command and one ``master_apply_delete_command()`` concurrent to the ``COPY``. Is my understanding correct?

**Comment by metdos** [comment]
> @metdos -- I had a clarification question.
> 
> We see this error message when the user runs a COPY and one master_apply_delete_command() concurrent to the COPY (both on the same table). Is my understanding correct?

No, we see this error when the user runs two master_apply_delete_command() while there are multiple shards to delete.

**Comment by aamederen** [comment]
master_apply_delete_command() should block these as well:
- COPY
- INSERT/SELECT
- Rebalancer Functions
- Truncate
