### ISSUE TITLE
Colocated joins: Cleanup code paths that check if two tables are colocated

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#730]
Citus' logical and physical planners (including subquery pushdown logic) have various functions that check if two tables are colocated. Once we introduce formal colocation logic into Citus, we could remove those functions and instead directly call the new colocation apis. This would both help with query planning time and also with code cleanliness.

We have one user who uses `range` partitioning for their colocated tables. They however already expressed to us that they weren't using our colocation checks and introduced their own constraint logic to check for colocated tables.

I'm noting #695 as a related issue.

**Comment by marcocitus** [comment]
Fixed by #5359
