### ISSUE TITLE
Functions which hit distributed tables aren't transactional

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#731]
Given this schema:

```
CREATE TABLE local_table (key INT, value INT);
CREATE TABLE remote_table (key INT, value INT);
SELECT master_create_distributed_table('remote_table', 'key', 'hash');
SELECT master_create_worker_shards('remote_table', 16, 2);
```

And this function:
```
CREATE OR REPLACE FUNCTION insert_data() RETURNS void AS $$
DECLARE
BEGIN
  LOOP
    INSERT INTO local_table VALUES (1, 1);
    PERFORM pg_sleep(1);
  END LOOP;
END;
$$ LANGUAGE plpgsql;
```

If you run it in one session, and simultaneously query `local_table` from another session, you will not see the rows which the first session is inserting. If you run the function in a session, and interrupt it with ctrl-c, none of the rows will be written.

However, if you replace `local_table` with `remote_table`, you get different results.

If you run the function in one session, other sessions are able to see the inserted data while the first session is still running. If you run the function and interrupt it with ctrl-c, all of the previously written data is still there, it is not rolled back.

**Comment by lithp** [comment]
This appears to be a more specific #659

**Comment by jasonmp85** [comment]
Can I close this? This is known behavior.

**Comment by lithp** [comment]
Yep, no use having two tickets for the same issue
