### ISSUE TITLE
new role in coordinator connect to the remote node failed

### ISSUE THREAD

**Issue by spkinger** [citusdata/citus#7328]
I create a new role with `CREATE ROLE rtss_user WITH LOGIN PASSWORD 'xxxxx';` in coordinator node.
Also run `GRANT USAGE ON SCHEMA rtss TO rtss_user;`
`GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA rtss TO rtss_user;`
It's ok when i query the local table in coordinator.
But it's failed when i query the distributed table。Got this error：`connection to the remote node 10.244.19.70:11157 failed with the following error: FATAL:  password authentication failed for user "rtss_user"`
`10.244.19.70:11157` is one of worker node.
That's why?

**Comment by spkinger** [comment]
My citus version is 11.2.0

**Comment by onurctirtir** [comment]
Mu guess is that worker pg_hba files are missing some configurations that would allow connectivity with coordinator node.

This is an example reference to docs for debian machines:
https://docs.citusdata.com/en/v11.2/installation/multi_node_debian.html#steps-to-be-executed-on-all-nodes.

Please let me know if docs help you.

**Comment by onurctirtir** [comment]
Mu guess is that worker pg_hba files are missing some configurations that would allow connectivity with coordinator node.

This is an example reference to docs for debian machines:
https://docs.citusdata.com/en/v11.2/installation/multi_node_debian.html#steps-to-be-executed-on-all-nodes.

Feel free to re-open the issue if the docs don't help you.
