### ISSUE TITLE
How to use MX or masterless in Citus 12.0?

### ISSUE THREAD

**Issue by amwps290** [citusdata/citus#7329]
I want to use MX or masterless in Citus 12.0,but I can not find any useful information in documention or website,

**Comment by marcoslot** [comment]
This was a separate mode in the past. As of Citus 11, it is the default and only mode of operation. You'll be able to connect to any node in a Citus 12 cluster and perform queries on your distributed tables.

**Comment by amwps290** [comment]
thanks
