### ISSUE TITLE
Can the Columnar extension be used to exceed the 1600 column limit?

### ISSUE THREAD

**Issue by chriszrc** [citusdata/citus#7340]
Apologies, but I couldn't find the answer to this anywhere. A create table statement with the `USING COLUMNAR` still gives me an exception when I try to include more than 1600 columns. It would seem that the columnar extension should not be subject to this limitation. Is there some other way to support this, perhaps with some kind of partitioning of columns? Or something else?

**Comment by onurctirtir** [comment]
Columnar doesn't change the maximum number of columns that can be used in a table definition.
