### ISSUE TITLE
Auto increment column in distributed table.

### ISSUE THREAD

**Issue by xbogdan** [citusdata/citus#735]
Is it possible to create distributed table with a key that is auto increment ?

```
postgres=# create table test (id serial, name text);
CREATE TABLE
postgres=# SELECT master_create_distributed_table('test', 'id', 'hash');
 master_create_distributed_table
---------------------------------

(1 row)

postgres=# SELECT master_create_worker_shards('test', 2, 1);
WARNING:  could not receive query results from citus_worker_1:5432
DETAIL:  Client error: relation "test_id_seq" does not exist
WARNING:  could not create shard on "citus_worker_1:5432"
ERROR:  could only create 0 of 1 of required shard replicas
```

**Comment by marcocitus** [comment]
As of Citus 5.2 (you can build from source to try), you'll be able to use serial for colums other than the distribution column. For the distribution column, it's usually better to pick some grouping key like customer_id.

**Comment by xbogdan** [comment]
Yes but I want to use serial for the distribution column. Is that possible ?

In my case the customer_id is the primary key and its serial. Most of the foreign keys are primary keys in the join table.

**Comment by lfittl** [comment]
@xbogdan Unfortunately that is not supported at this time - my suggested approach would be to use a UUID for the distribution column and simply generate the UUID on the client side when you create new customers.

We're tracking this issue at https://github.com/citusdata/citus/issues/687 - let me know if that is the same issue you're encountering (I think it is), then we can close this and keep tracking it over there.

Sorry for the slight inconvenience!

**Comment by xbogdan** [comment]
Yes that is the problem. I don t think that having a uuid as a distribution column is efficient as long as I am doing most of my queries, especially joins, on serial primary keys.

**Comment by lfittl** [comment]
@xbogdan Practically both would work with Citus, but its up to you what you prefer.

I'll close this for now to avoid duplicates - as written before my suggestion would be to use a sequence on the master, fetch the next value using `SELECT nextval('sequence_name')` and then pass that in with the insert.

We are going to fix this problem in a future release. I know its a tad annoying (I'm testing ORMs as part of my work at Citus), but sadly nothing quick we can do right now.
