### ISSUE TITLE
Cannot add workers

### ISSUE THREAD

**Issue by professorxavier** [citusdata/citus#7383]
I'm evaluating CitusData in the Multi-Node model. To do this, I created three containers in Docker, with one of them being the master. 

Master/Coordinator: 172.17.0.3
Node 1: 172.17.0.4
Node 2: 172.17.0.5

When running the command to add a node, the following error is displayed:

```
postgres=# select * from citus_add_node('172.17.0.4',5432);
ERROR:  Node cannot add itself as a worker
```

I'm following the the tutorial for Multi Node installation on citusdata website

**Comment by onurctirtir** [comment]
All citus_add_node commands should be issued on coordinator, as in:

```sql
set citus_set_coordinator('172.17.0.3',5432);

select * from citus_add_node('172.17.0.4',5432);
select * from citus_add_node('172.17.0.5',5432);
```

Please re-open the issue if you think there is a different problem in your case.

**Comment by bouyeijiang** [comment]
I still have this mistake

ERROR: Node cannot add itself as a worker.
  Hint: Add the node as a coordinator by using: SELECT citus_set_coordinator_host

Is it related to setting coordinator errors.How can i reset the coordinator
