### ISSUE TITLE
Move all functions with `citus_internal_` prefix functions to the `citus_internal` schema.

### ISSUE THREAD

**Issue by JelteF** [citusdata/citus#7405]
This has a few caveats
1. We'd want to keep the already released internal functions at least also out of the schema, to allow for smooth rolling upgrades.
2. The `citus_internal` schema needs to be made accessible by PUBLIC
3. We should REVOKE ALL permissions on functions that are currently in the citus_internal schema from PUBLIC. Otherwise currently superuser-only might be executed by normal users, resulting in security issues.

**Comment by eaydingol** [comment]
All functions with citus_internal_ prefix are moved to citus_internal schema at version 12.2. 
As for item 1 from the description, the released ones are also kept in pg_catalog. These can be dropped once the oldest supported version is 12.2.
