### ISSUE TITLE
Node cannot add itself as a worker

### ISSUE THREAD

**Issue by bouyeijiang** [citusdata/citus#7406]
postgresql16+citus12.1
postgres=# select citus_set_coordinator_host('192.168.1.10',5432);
 citus_set_coordinator_host 
----------------------------
 
(1 row)

postgres=#select citus_add_node('192.168.1.11',5432);

ERROR:  Node cannot add itself as a worker.
HINT:  Add the node as a coordinator by using: SELECT citus_set_coordinator_host('192.168.1.11', 5432);

**Comment by emelsimsek** [comment]
Since the node is not part of the cluster, it does not know hoe to add it. You need to add new nodes through the coordinator.

1. Connect to the coordinator
2. select citus_add_node('192.168.1.11',5432);

The error is somewhat misleading, It assumes that you are trying to make an already known node a coordinator.

**Comment by emelsimsek** [comment]
This should work. It is hard to troubleshoot without the configs and environment. But I suggest you to follow https://docs.citusdata.com/en/v12.1/installation/multi_node_debian.html when setting up your cluster.

**Comment by bouyeijiang** [comment]
I configured it based on this document.So I don't know where the problem

**Comment by emelsimsek** [comment]
For help on such setup issues, I recommend posting to slack: https://citus-public.slack.com/ for help.

**Comment by bouyeijiang** [comment]
This website is not friendly to me

**Comment by bouyeijiang** [comment]
I have discovered an issue where copying the disk image of hyper-v directly from a host failed to add it. After recreating the virtual machine and installing the system in hyper-v, everything worked fine.~~~
