### ISSUE TITLE
citus_move_shard_placement to a fresh worker makes cluster unusable

### ISSUE THREAD

**Issue by crabhi** [citusdata/citus#7426]
Hi, this may be just a documentation issue. When creating a new worker, it won't immediately have reference tables. They get copied on `citus_rebalance_start()` but not on `citus_move_shard_placement(...)`.

The documentation doesn't mention that one can't use `citus_move_shard_placement(...)` on a fresh node and the function `replicate_reference_tables()` isn't documented.

Steps to reproduce:

1. Create a single-node Citus cluster on localhost.
```
postgres=# SELECT * FROM pg_dist_node;
 nodeid | groupid | nodename  | nodeport | noderack | hasmetadata | isactive | noderole | nodecluster | metadatasynced | shouldhaveshards 
--------+---------+-----------+----------+----------+-------------+----------+----------+-------------+----------------+------------------
      1 |       0 | localhost |     5400 | default  | t           | t        | primary  | default     | t              | t
```
2. Create a distributed table and a reference table.
```sql
CREATE TABLE distributed (id SERIAL PRIMARY KEY, value INT);
CREATE TABLE reference (id SERIAL PRIMARY KEY, value INT);
SELECT create_distributed_table('distributed', 'id');
SELECT create_reference_table('reference');
```
3. Add a worker node. `SELECT citus_add_node('localhost', 5401);`
```
postgres=# SELECT * FROM pg_dist_node;
 nodeid | groupid | nodename  | nodeport | noderack | hasmetadata | isactive | noderole | nodecluster | metadatasynced | shouldhaveshards 
--------+---------+-----------+----------+----------+-------------+----------+----------+-------------+----------------+------------------
      1 |       0 | localhost |     5400 | default  | t           | t        | primary  | default     | t              | t
      2 |       1 | localhost |     5401 | default  | t           | t        | primary  | default     | t              | t
```
4. Move one shard manually. 
```sql
SELECT citus_move_shard_placement(102024, 'localhost', 5400, 'localhost', 5401);
```
5. 💥 
```sql
postgres=# 
    SELECT * FROM distributed JOIN reference USING (id);

ERROR:  relation "public.reference_102040" does not exist
CONTEXT:  while executing command on localhost:5401
```

Calling undocumented `replicate_reference_tables` fixes the problem.

```sql
postgres=# SELECT replicate_reference_tables();
NOTICE:  replicating reference table 'reference' to localhost:5401 ...
 replicate_reference_tables 
----------------------------
 
(1 row)

postgres=# SELECT * FROM distributed JOIN reference USING (id);
 id | value | value 
----+-------+-------
(0 rows)
```

**Comment by JelteF** [comment]
Hmm, that is not a great user experience. I don't think we'd want to run `replicate_reference_tables` automatically from `citus_move_shard_placement` though. The main reason for that is that `citus_move_shard_placement` is a low level API, that shouldn't do extra things automatically. Two things that makes sense to improve are:
1. citus_move_shard_placement should probably error when the reference tables are not distributed to that node yet, saying that replicate_reference_tables should be called first. Because it's quite bad that it allows moving a shard to a node that does not have reference tables yet.
2. replicate_reference_tables should be documented.

**Comment by crabhi** [comment]
Oh, yeah, the point #1 alone would've prevented at least one late-night wakeup. :-D

**Comment by JelteF** [comment]
A side question: Why did you use `citus_move_shard_placement` instead of `citus_rebalance_start()`? For most users using `citus_rebalance_start()` is the recommended way of scaling out.

**Comment by crabhi** [comment]
Yes, exactly. `citus_rebalance_start()` fixed it for me before I found `replicate_reference_tables()`.

I really wanted to move just one shard - we have a replica behind a weaker network line and I wanted some time between the moves for it to catch up safely.

**Comment by shankarmn94** [comment]
ccnsapp=# SELECT * FROM get_rebalance_progress(); 

 

 sessionid |             table_name             | shardid | shard_size | sourcename | sourceport | targetname  | targetport | progress | source_shard_size | target_shard_size | operation_type |  source_lsn  | target_lsn |   status    

-----------+------------------------------------+---------+------------+------------+------------+-------------+------------+----------+-------------------+-------------------+----------------+--------------+------------+------------ 

    129334 | companies                          |  102026 |     212992 | 10.104.0.5 |       5432 | 10.104.0.10 |       5432 |        1 |            212992 |              8192 | move           | 8FE/60D49CD0 |            | Setting Up 

    129334 | agents                             |  102058 |   36380672 | 10.104.0.5 |       5432 | 10.104.0.10 |       5432 |        1 |          36380672 |              8192 | move           | 8FE/60D49CD0 |            | Setting Up 

    129334 | assets                             |  102090 |  196091904 | 10.104.0.5 |       5432 | 10.104.0.10 |       5432 |        1 |         196091904 |              8192 | move           | 8FE/60D49CD0 |            | Setting Up 

    129334 | deprecation_status                 |  102122 |      32768 | 10.104.0.5 |       5432 | 10.104.0.10 |       5432 |        1 |             32768 |                 0 | move           | 8FE/60D49CD0 |            | Setting Up 

    129334 | windows_specifics                  |  102154 |      32768 | 10.104.0.5 |       5432 | 10.104.0.10 |       5432 |        1 |             32768 |                 0 | move           | 8FE/60D49CD0 |            | Setting Up 

    129334 | mac_specifics                      |  102186 |      40960 | 10.104.0.5 |       5432 | 10.104.0.10 |       5432 |        1 |             40960 |              8192 | move           | 8FE/60D49CD0 |            | Setting Up 
    
    its says setting up... when it will start while its active and progrees..  why it takes more time?
