### ISSUE TITLE
Include HyperLogLog (HLL) extension in Docker image, CloudFormation template, and PackageCloud

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#743]
We offer the HyperLogLog (HLL) extension to our users, who need to compute fast distinct count approximations. Downloading HLL, building it from source against Citus, and then installing this extension takes effort.

We'd like to include the HLL extension as part of our standard distribution. Three distibution channels I can think of are:
- Docker image
- CloudFormation template
- PackageCloud (is this hard?)

**Comment by ozgune** [comment]
I'm adding #46 and https://github.com/citusdata/citus_docs/issues/41 as related issues.

**Comment by jasonmp85** [comment]
Kind of weird that it's not in PGDG, but I guess it was never submitted?

We'd have to make our own package for it, but that's not terribly hard given all the other packaging infrastructure we now have.

**Comment by sumedhpathak** [comment]
@jasonmp85 Should this issue be closed? I think we have it in PackageCloud now. Do we have it in Docker or CloudFormation? What are instructions for adding the HLL package if we have our PackageCloud repo installed?

**Comment by ozgune** [comment]
I'm adding the v6.2 milestone with the intention of adding the HLL package to our CloudFormation template.

**Comment by ozgune** [comment]
@velioglu merged in the changes for installing HLL on our CloudFormation template. I'm therefore removing the 6.2 milestone from this issue.

**Comment by marchelbling** [comment]
Is there any update on this?
I just checked and unless I'm missing something obvious, there is still neither the hll nor the topn extension in the citus docker image and it would be really convenient.
