### ISSUE TITLE
Documentation about upgrading

### ISSUE THREAD

**Issue by michaeldg** [citusdata/citus#7455]
Hi,

Reading your documentation about upgrading, it is a bit unclear (for me) how upgrade of worker nodes should be executed.

I am talking about this page: https://docs.citusdata.com/en/stable/admin_guide/upgrading_citus.html

My questions:
- Should worker nodes Citus package be upgraded before or after the coordinator node, or does this not matter?
- Does the same process apply for upgrading citus on the worker nodes as on the coordinator node?
- Should worker node's postgres version be upgraded before or after the coordinator node, or does this not matter?
- Does the same process apply for upgrading PostgreSQL version on the worker nodes (i.e. should 'citus_finish_pg_upgrade();' be executed on the worker nodes as well after upgrading Pg version)?

Thank you,
Michaël

**Comment by onurctirtir** [comment]
> Should worker nodes Citus package be upgraded before or after the coordinator node, or does this not matter?

To me it feels safer to first upgrade workers then the coordinator in Citus upgrades.

> Does the same process apply for upgrading citus on the worker nodes as on the coordinator node?

`ALTER EXTENSION UPDATE` needs to be done on all nodes but citus_finish_citus_upgrade() is expected to be issued on coordinator only.

> Should worker node's postgres version be upgraded before or after the coordinator node, or does this not matter?

I think it doesn't much matter whether you upgrade Postgres first on workers or on the coordinator.

> should 'citus_finish_pg_upgrade();' be executed on the worker nodes as well after upgrading Pg version

Right.

Please feel free to re-open the issue if you happen to have more questions, thanks!
