### ISSUE TITLE
Exclusion constraints on distributed tables should be forbidden just as unique constraints are

### ISSUE THREAD

**Issue by robin900** [citusdata/citus#748]
I use exclusion constraints on many of my distributed tables. Example

Table with columns `(account_id int, during tstzrange, value int)`, dist column `account_id`.
Exclusion constraint is `EXCLUDE USING gist (account_id WITH =, during WITH &&)`.

The citus code prohibits creating a distributed table if a unique constraint/index exists on the table without including the dist column. Citus should also prohibit exclusion constraints that omit the dist column `WITH =`.

**Comment by robin900** [comment]
It's easy to add the check for exclusion constraints, if the check is as simple as seeing if the distribution column is one of the index columns. However, it will be more laborious to check that the exclusion operator for the distribution column is indeed '=': there are lots of equality operators in pg_operator, varying by argument data type, which would be valid for Citus to accept, and some of which have an oprname != '='.

I think, as a decent safety measure, it would be enough just to check that the distribution column is present in the exclusion index's columns, and not have any restrictions on the operator used for the distribution column.

**Comment by ozgune** [comment]
@robin900 -- thanks for opening up this issue and the related pull request.

@sumedhpathak will assign a person to review #749 in the next few days.
