### ISSUE TITLE
Problem with rebalancing "Could not fetch disk stats for node"

### ISSUE THREAD

**Issue by DJLebedev** [citusdata/citus#7480]
I have successfully added a new empty node to the cluster.
Then I started `SELECT citus_rebalance_start();`.
As a result, I get an error:
```json
{
  "tasks": [
    {
      "state": "runnable",
      "command": "SELECT pg_catalog.citus_move_shard_placement(102031,3,4,'auto')",
      "message": "ERROR: Could not fetch disk stats for node: cs-pms-logs-db-shard-3-5432\nCONTEXT: Citus Background Task Queue Executor: pms_logs/postgres for (2/9)\n",
      "retried": 10,
      "task_id": 9
    }
  ],
  "task_state_counts": {
    "blocked": 7,
    "runnable": 1
  }
}
```
What does it mean? And how to fix it?

**Running citus 12.1 and Postgresql 16**

**Comment by JelteF** [comment]
It sounds like it's unable to connect to the node that it wants to move the shard to. One of the first things a shard move do is to check if there is enough disk space on the node to complete the move, as a safety mechanism to fill up the node.

**Comment by DJLebedev** [comment]
Thank you. Indeed, the node was killed by OOM-killer when rebalancing started.
