### ISSUE TITLE
It is hard to debug `distributed modifications must target exactly one shard` messages

### ISSUE THREAD

**Issue by fdr** [citusdata/citus#750]
This message does not have enough detail, it might be better if the shards that were going to be addressed could be summarized and printed:

``` c
    prunedShardCount = list_length(prunedShardList);
    if (prunedShardCount != 1)
    {
        ereport(ERROR, (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                        errmsg("distributed modifications must target exactly one "
                               "shard")));
    }
```

In the case where this was encountered, there was a non-trivial pl/pgsql insert trigger involved.

**Comment by mtuncer** [comment]
would an error hint help  here ?

**Comment by fdr** [comment]
Yeah, an error hint or detail showing some of the prunedShardList probably would help.

**Comment by ozgune** [comment]
I'm noting #692 and #693 as related issues.

@lfittl -- would you consider #758 as a related issue as well?

**Comment by lfittl** [comment]
@ozgune I'd say its somewhat related, depending on how you want to choose your scope ;)

The specific case described in #758 is an actual bug, since there is no point in running that particular query at all (it should just return an empty result set).

**Comment by samay-sharma** [comment]
Re-opening as per discussion with @ozgune

**Comment by metdos** [comment]
Noting a related comment https://github.com/citusdata/citus/pull/1031#issuecomment-270798443

**Comment by lithp** [comment]
It's difficult to see how any of the points in the referenced comment could be made actionable. @samay-sharma, are you the right person to ask about this?

a) appears to propose the wording which already exists? That is the HINT which INSERT statements receive.
b) proposes being smarter and, instead of HINTing both solutions to the problem, HINTing the one we think the user wants. However, I have a hard time imagining we could distinguish between a user who forgot to add a WHERE clause and a user who genuinely wants to modify every shard.
c) Seems to ignore that we now not only mention the partition column but also suggest a function to use, if you really want to modify all shards.
d) requests that we use terms such as "INSERT" and "UPDATE" rather than "distributed modification" which would make the control flow reasonably more complicated for questionable benefit.

**Comment by metdos** [comment]
@samay-sharma, do you have any comments?

**Comment by sumedhpathak** [comment]
Copying @ozgune's comment here.

I wanted to add a further quick clarification note to this issue. @mtuncer, @samay-sharma, @marcocitus and I had a meeting on this and we broke down four improvement areas @samay-sharma mentioned.

We also agreed on a solution for the following:

(a) If the user is running an INSERT, we can only get this for append or range partitioned tables. We will therefore improve the INSERT related section in this change similar to @samay-sharma's notes.

(d) The terminology "distributed modifications must target exactly one shard" is a bit dense. We're therefore going to reword it similar to how @samay-sharma's notes above.

**Comment by metdos** [comment]
@mtuncer, @ozgune noted that you have the most context on this issue, so I assigned this to you. Could you reach out to @ozgune if you have questions?

**Comment by mtuncer** [comment]
I have got following

### Insert failures on append partitioned tables
no shards
```
ERROR:  cannot run INSERT command which targets no shards
HINT:  Make sure the value for partition column "id" falls into a single shard.
```
multiple shards
```
ERROR:  cannot run INSERT command which targets multiple shards
HINT:  Make sure the value for partition column "id" falls into a single shard.
```
Notice that there is no detail part.

### Update failures
no shards
```
ERROR:  cannot run UPDATE command which targets no shards
HINT:  Consider using an equality filter on partition column "id". You can use master_modify_multiple_shards() to perform multi-shard delete or update operations.
```
multiple shards
```
ERROR:  cannot run UPDATE command which targets multiple shards
HINT:  Consider using an equality filter on partition column "id". You can use master_modify_multiple_shards() to perform multi-shard delete or update operations.
```
### Delete failures
no shards
```
ERROR:  cannot run DELETE command which targets no shards
HINT:  Consider using an equality filter on partition column "id". You can use master_modify_multiple_shards() to perform multi-shard delete or update operations.
```
multiple shards
```
ERROR:  cannot run DELETE command which targets multiple shards
HINT:  Consider using an equality filter on partition column "id". You can use master_modify_multiple_shards() to perform multi-shard delete or update operations.
```

if delete operation is on a append distributed table.  Hint message is appended with  master_apply_delete_command hint.
```
ERROR:  cannot run DELETE command which targets multiple shards
HINT:  Consider using an equality filter on partition column "c_custkey". You can use master_modify_multiple_shards() to perform multi-shard delete or update operations. You can also use master_apply_delete_command() to drop all shards satisfying delete criteria.
```

I copied and pasted these error text with actual output. Thats why there are different partition column names.

@ozgune @samay-sharma  what do you think of those ?
