### ISSUE TITLE
Range Partition

### ISSUE THREAD

**Issue by narayana1923** [citusdata/citus#7500]
I tried creating a table with an integer column and distributed that column with range partitioning. During create_distributed_table and select queries I am not getting any errors but when I try to insert a row into the column I'm getting
`ERROR:  could not find any shards
DETAIL:  No shards exist for distributed table "person".
HINT:  Run master_create_worker_shards to create shards and try again.`

I tried with citus 6.2, 9 and latest build as well.

**Comment by onurctirtir** [comment]
When using range partitioning, you need to create the shards manually by using the function that error hint mentioned.

Feel free to re-open the issue if this doesn't help you.

**Comment by JelteF** [comment]
Also, generally range partitioning is not very well supported in Citus and thus isn't recommended most of the time. It mostly still exists because of backwards compatibility and because it's still on the (long) backlog to eventually support better.

**Comment by narayana1923** [comment]
@onurctirtir In latest version of citus the function just throws error stating it is not suppoerted. In 6.2 version, I see that the shards are created based on hashing only so how is it different from range partition and hash partition

**Comment by petrucci89** [comment]
@onurctirtir in the latest version got HINT:  Run master_create_worker_shards to create shards and try again. but this function does not exist. Is any ways how can i realize range partition, i need exactly this distribution method. Thx!
