### ISSUE TITLE
rightComparisionLimit value in columnar_tableam

### ISSUE THREAD

**Issue by sminux** [citusdata/citus#7543]
Have noticed that rightComparisonLimit is the same size as left:
https://github.com/citusdata/citus/blob/f4242685e377d5eddf8c81e1c127b1c4325c83cb/src/backend/columnar/columnar_tableam.c#L2949
Is it correct?
Maybe it should be: 
rightComparisionLimit = strlen(rightVersion);

**Comment by JelteF** [comment]
Yeah, that seems like a copy paste mistake. Do you want to submit a PR to fix that? If not, one of us will probably pick it up soon-ish.

**Comment by JelteF** [comment]
To be clear, in practice this issue shouldn't be hit. Since our of the columnar extension are always of the form XY.Z, so length 4.
