### ISSUE TITLE
copy distributed table and reference table

### ISSUE THREAD

**Issue by wkgreat** [citusdata/citus#7546]
how to copy a distributed or reference tables to another shcema and the target tables are still distributed and referenced, is there any UDF or sqls?

**Comment by wkgreat** [comment]
like 
```sql
select copy_distributed_table('tb_name_dist','schema2.tb_name_dist');
select copy_reference_table('tb_name_ref','schema2.tb_name_ref');
```

**Comment by emelsimsek** [comment]
You should be able to use:
`ALTER TABLE old_schema.distributedtable SET SCHEMA new_schema;`
