### ISSUE TITLE
Add regression tests to include queries with "WHERE distribution_column = NULL"

### ISSUE THREAD

**Issue by lfittl** [citusdata/citus#758]
We've seen this with one of our customers, resulting in 100% CPU utilization due to the real-time executer running queries that were intended for the router executor.

They were doing a `SELECT ... FROM table WHERE distribution_column = $1` on a hash-distributed table (i.e. using the router executor), but in some cases `$1` was set to `NULL`, which would result in the query being run with the real-time executor instead, fanning out to all shards.

Ultimately this was a problem in the customer's scripts that they've fixed, but the cluster behavior was not easy to debug (or obvious to the customer), since it was simply showing as 100% CPU utilization, most of it spent in TLS negotiation.

My suggestion would be that Citus should either error out (a solution @anarazel was -1 on), or that we prune the query so it always returns an empty result set in such cases, without opening up connections to the worker nodes.

**Comment by mtuncer** [comment]
I am not in favor of erroring out here. Although the query is almost meaningless, it is still valid query.  Fixing prune shard list and returning empty result set looks better.

**Comment by lfittl** [comment]
According to discussion in the planning meeting, this should have been resolved by #806 as a side effect.

We did discuss adding additional regression tests, so leaving this open for now.
