### ISSUE TITLE
It is not passable to create index concurrently on the partitioned table

### ISSUE THREAD

**Issue by YMikheev** [citusdata/citus#7586]
Please make it possible to create concurrently on the partitioned table.
It will be very helpful for big tables.

**Comment by agedemenli** [comment]
It is not allowed by Postgres.

You can create index concurrently on partitions, but not on the parent table. You can maybe do create all of them concurrently and then do a regular create index on the parent table.

**Comment by YMikheev** [comment]
Since we have thousands of partitions, I will have to implement/debug a script for automation. It would be convenient if such a function was implemented in the Citus.

**Comment by JelteF** [comment]
Since Postgres does not provide this feature, Citus can also not provide it. Because Citus is built on top of Postgres. Feel free to report the feature request to Postgres itself. If Postgres implements it then Citus would probably get it automatically.
