### ISSUE TITLE
12.1.3 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [citusdata/citus#7590]
👋 it looks like 12.1.3 release was not completed, ie the github release did not get created as 12.1.2, raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/169956

**Comment by chenrui333** [comment]
cc @gurkanindibay

**Comment by gurkanindibay** [comment]
Thanks for the heads-up
Added the release
