### ISSUE TITLE
Citus backup and restore questions

### ISSUE THREAD

**Issue by yinan8128** [citusdata/citus#7593]
Hi team,

There is no backup and restore part in version 12.1 doc. We raised questions in Slack but didn't get needed answer

Please help provide answer, thanks:

1. Is pgBackRest supported in Citus backup please?
2. Do we need to backup coordinator node and worker nodes separately? For example 1 coordinator node and 4 worker nodes, 5 separate backups?
3. Can we restore Citus all nodes to point in time (PITR) by the separate backup of each node(coordinator node and worker node)?

Thank you

**Comment by yinan8128** [comment]
Hi Team,

Could you please help check? Thanks

**Comment by latot** [comment]
Hi, I has been also looking on this, related to I would like to know about:

- It is not always possible to recover 100% of a Cluster, so if a fragment is loss, the coordinator can fails? what the coordinator needs to know and must match to make it consistent?
- Which tables/data the coordinator needs?
- How can we handle inconsistencies in the nodes and/or the coordinator?

@emelsimsek
