### ISSUE TITLE
Can't add entry for certificate authentication to pg_dist_authinfo 

### ISSUE THREAD

**Issue by bensnaidero** [citusdata/citus#7595]
Hi,

I am trying to add certificate authentication for the worker nodes so I don't have to store a plain text password in this table or the .pgpass file.  I have 3 instances (one co-ordinator port 5345 and two workers ports 5432/5433) setup on a single node for testing.  You can see from the code below that the certficate authentication is working since I can connect using psql with the certificate but when I try to add a row to pg_dist_authinfo table with the same settings it fails the check constraint.  Any ideas what my issue could be?  According to the documentation all libpq options are supported.

Note: Using password='somepwd' works fine

`root@BSNAIDERO:/var/lib/postgresql# psql "postgresql://postgres@localhost:5435/ben?sslmode=verify-full&sslcert=/var/lib/postgresql/certs/client.crt&sslkey=/var/lib/postgresql/keys/client.key&sslrootcert=/var/lib/postgresql/certs/ca.crt"
psql (15.6 (Ubuntu 15.6-1.pgdg22.04+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
Type "help" for help.

ben=# insert into pg_dist_authinfo values (0,'postgres','host=localhost sslmode=verify-full sslcert=/var/lib/postgresql/certs/client.crt sslkey=/var/lib/postgresql/keys/client.key sslrootcert=/var/lib/postgresql/certs/ca.crt');
ERROR:  new row for relation "pg_dist_authinfo" violates check constraint "authinfo_valid"
DETAIL:  Failing row contains (0, postgres, host=localhost sslmode=verify-full sslcert=/var/lib/postgresql/c...).
ben=#`

**Comment by emelsimsek** [comment]
> ben=# insert into pg_dist_authinfo values (0,'postgres','host=localhost sslmode=verify-full sslcert=/var/lib/postgresql/certs/client.crt sslkey=/var/lib/postgresql/keys/client.key sslrootcert=/var/lib/postgresql/certs/ca.crt');
> ERROR: new row for relation "pg_dist_authinfo" violates check constraint "authinfo_valid"
> DETAIL: Failing row contains (0, postgres, host=localhost sslmode=verify-full sslcert=/var/lib/postgresql/c...).

You cannot put the entire connection string as the auth info. 
Only { "password", "sslcert", "sslkey" } parameters can be defined here. 

Other connection parameters that are common to all nodes should be defined by using [citus.node-conninfo ](https://docs.citusdata.com/en/v11.2/develop/api_guc.html?highlight=conninfo#citus-node-conninfo-text:~:text=%3D%2060000%3B-,citus.node_conninfo%20(text),%EF%83%81,-The%20citus.node_)
