### ISSUE TITLE
Execution order of statements of a transaction

### ISSUE THREAD

**Issue by SandeepFranklin** [citusdata/citus#7608]
Hi team, I am trying to understand the execution order of statements of a transaction in Citus, I get the diagram from this [page](https://www.citusdata.com/blog/2017/08/31/databases-and-distributed-deadlocks-a-faq/): 
![image](https://github.com/citusdata/citus/assets/4965514/74819568-9673-4e50-a222-5cf457c06018)

From the diagram, the statement(time=1: UPDATE ... WHERE KEY='Foo') is the first statement of the transaction and should be executed at first in a single database, am I right?

Another question is does the diagram show that Citus will send the statements to worker in an order different from the order in user code?

**Comment by onurctirtir** [comment]
The arrows between Dist TX 1 and Dist TX 2 represent the fact that "they blocked on each other" and this means a distributed deadlock, the diagram is not much about their execution order I believe.

> Another question is does the diagram show that Citus will send the statements to worker in an order different from the order in user code?

No, if two distributed transactions are initiated from the same session, then the corresponding worker statements for them will be executed in the same order on workers.

Please feel free to re-open the issue if you have any more questions.

**Comment by SandeepFranklin** [comment]
Thank you for the kind reply.

I would also like to know how Citus would work in a concurrency scenario, suppose Citus executes two transactions t1 and t2 at the same time, which are generated by the same piece of code of a concurrent program, so they would acquire locks first on A and then on B in the same order.

Let's say that A is on NodeA and B is on NodeB, so both t1 and t2 are distributed transactions across nodes. In this case, is it possible that t1 acquires A's lock first and t2 acquires B's lock first, then resulting in a deadlock?
