### ISSUE TITLE
Two-layer sharding

### ISSUE THREAD

**Issue by sergeyvm** [citusdata/citus#763]
Sometimes single-level sharding is not sufficient. For example, someone has a table with nearly billion rows per a day and a necessity for a fast-search rows by some date' range and an id. For an efficient maintenance of the data it is a good option to choose the "append" sharding scheme. It is also well for a fast search by date' range. But, if a table stored in columnar format (cstore_fdw), search by an id means full-scan of all the shards in date' range. By chosing the "hash" sharding scheme, it is possible to gain a good performance of search by the id, and also by the date' range, since there are millions distinct id values and by orders of magnitude less of rows per an unique id value per a day. But, in such way, it is hard to perform maintance of the table (delete old data), especially if data stored in columnar formart.

P.S. sorry, english isn't my native language.

**Comment by metdos** [comment]
Hi @sergeyvm, thanks for opening the issue.

You can create two-layer sharding in Citus with some manual effort. You can distribute your data on your id by hash distribution. Then, for every shard created in your worker nodes, you can use PostgreSQL partitioning and create different partitions based on date. You may also want to create triggers to redirect inserts in worker nodes similar to example here in PostgreSQL documentation:
https://www.postgresql.org/docs/9.5/static/ddl-partitioning.html

Do you have such a use case? How big is your data?

**Comment by sergeyvm** [comment]
Hi @metdos, thanks for your reply.
It is an interesting idea to use the underlaying PostgreSQL partitioning =)
But, it would be cumbersome in case of fifty hash-shards. Also there would be some performance degradation in case of thousand partitions, since native PostgreSQL partition pruning isn't as efficient as Citus one.

Despite I have no real few PB of data yet, my issue based on real project's R&D process.

**Comment by marcocitus** [comment]
Columnar storage might not be the most suitable solution for dealing with queries that filter by a very specific ID. You'd probably want to consider row-based storage with an index on the ID. If you need the compression, you could consider using arrays, which will get compressed into TOAST tables in PosgreSQL.

Example: https://gist.github.com/djk447/b597cd6c9114d10c309a07bb5916bad5

**Comment by ozgune** [comment]
@sergeyvm -- I have a quick question.

If using Postgres partitioning across dozens of shards was easy, would that help solve your issue?

We heard requirements similar to yours several times before, and we're tracking our understanding in #183 and #573. Do #183 / #573 sound similar to your use-case?

**Comment by sergeyvm** [comment]
Hi, @marcocitus , thanks for your answer.
Although #573 and #183 sheds some light how to solve my puzzle, it doesn't sound as a good idea - create a distributed by hash table and then go to each shard and create table inheritance. Most sadly, it has necessity to process future maintenance of each shard in separate, which is a huge drawback. Instead of run a single query on the master - multiple queries on multiple shards.

**Comment by ozgune** [comment]
@sergeyvm -- I had a quick clarification question.

If this process -create a distributed table on the master and partition that table by time on workers- was automatic, would it address your use-case?

**Comment by vialorn** [comment]
Partially. That about you wrote is just first step. Next and regularly recurring step is add new and drop old partitions on the shards.

**Comment by ozgune** [comment]
@vialorn -- Got it.

I had a quick clarification note. We have customers who already use a similar setup; and we opened #183 to communicate what they are doing and then potentially turn some of their manual work into deployable scripts.

#573 takes a higher level approach. Once we have more feedback in #183, we'd then investigate automating the work involved as part of the product. The new declarative partitioning feature in upcoming Postgres 10 release could make this much easier.

I added your note on requirements (automating table partition creation and adding/dropping partitions) to #573. I'm planning to close this issue with those notes in #573. If that doesn't sound good, could you let me know?

**Comment by ozgune** [comment]
@sergeyvm and @vialorn -- I wanted to provide an update on this issue. We've been working on adding support for automatic feature to Citus.


[Citus 7](https://www.citusdata.com/blog/2017/09/07/citus-7-distributed-transactions-frameworks-and-pg10/) supports declarative partitioning that comes with PostgreSQL 10. This way, you can hash distribute your tables on one dimension, and further partition them on time.

Citus 7.2 makes further improvements to support pg_partman. pg_partman automatically manages Postgres partitions for users (by creating new partitions and dropping old ones). You can read more about it in Citus and pg_partman: [Creating a scalable time series database on Postgres](https://www.citusdata.com/blog/2018/01/24/citus-and-pg-partman-creating-a-scalable-time-series-database-on-PostgreSQL/).

For users who want multi-level sharding, we're tracking the issue in #1346.
