### ISSUE TITLE
Order of return value of load_shard_placement_array() is not deterministic

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#766]
This causes Travis to fail time to time. The workaround is to rerun Travis until to get the expected results.

Example Travis log:

```sql
+test -f regression.diffs
+cat regression.diffs
*** /home/travis/build/citusdata/citus/src/test/regress/expected/multi_distribution_metadata.out	2016-09-02 11:16:18.703099086 +0000
--- /home/travis/build/citusdata/citus/src/test/regress/results/multi_distribution_metadata.out	2016-09-02 11:17:30.840737461 +0000
***************
*** 128,134 ****
  SELECT load_shard_placement_array(540001, false);
      load_shard_placement_array     
  -----------------------------------
!  {localhost:57637,localhost:57638}
  (1 row)
  
  -- only one of which is finalized
--- 128,134 ----
  SELECT load_shard_placement_array(540001, false);
      load_shard_placement_array     
  -----------------------------------
!  {localhost:57638,localhost:57637}
  (1 row)
  
  -- only one of which is finalized
***************
*** 142,148 ****
  SELECT load_shard_placement_array(540001, false);
      load_shard_placement_array     
  -----------------------------------
!  {localhost:57637,localhost:57638}
  (1 row)
  
  -- should see column id of 'name'
--- 142,148 ----
  SELECT load_shard_placement_array(540001, false);
      load_shard_placement_array     
  -----------------------------------
!  {localhost:57638,localhost:57637}
  (1 row)
  
  -- should see column id of 'name'
======================================================================
+exit 2
The command "CFLAGS=-Werror pg_travis_multi_test check-multi check-worker" exited with 2.
```

Example Travis build:
https://travis-ci.org/citusdata/citus/builds/157065140

**Comment by metdos** [comment]
Both load_shard_placement_array() and the called function ShardPlacementList() seem that they haven't changed for months. Maybe something has changed related to PostgreSQL heap scan or something related to Travis.

@jasonmp85, do you have any idea?

**Comment by jasonmp85** [comment]
I just saw this locally, not just in Travis. And I've _never_ seen this, nor have I recently changed my PostgreSQL version.

Are we _sure_ this isn't something we introduced, somehow?

**Comment by anarazel** [comment]
On 2016-09-02 13:22:24 -0700, Jason Petersen wrote:
> I just saw this locally, not just in Travis. And I've _never_ seen this, nor have I recently changed my PostgreSQL version.
> 
> Are we _sure_ this isn't something we introduced, somehow?

It might just be that more free-space in the catalog table, due to some
independent change. As ShardPlacementList() doesn't enforce any
ordering...

**Comment by jasonmp85** [comment]
I slapped a `SortList` with `CompareShardPlacements` as comparator in the test code. There's another issue (#759) that says this comparator is bad (it is), but it seemed worth a shot for the test here. I believe this should go away now.
