### ISSUE TITLE
Remove (toast) oid references in regression tests

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#771]
In 5.2 we'd gotten rid of most pg_toast_<oid> references. Which is good, because they constantly change, and prohibit making tests parallel. We unfortunately just re-added a lot of them.

I think we should work to remove all of them, and make it a policy that no tests referencing oids are to be checked in anymore.
```
$ git grep pg_toast github-open/master 
github-open/master:src/test/regress/expected/multi_complex_expressions.out:DEBUG:  building index "pg_toast_17022_index" on table "pg_toast_17022"
github-open/master:src/test/regress/output/multi_subquery.source:DEBUG:  building index "pg_toast_17247_index" on table "pg_toast_17247"
github-open/master:src/test/regress/output/multi_subquery.source:DEBUG:  building index "pg_toast_17256_index" on table "pg_toast_17256"
```

**Comment by anarazel** [comment]
@metdos You're the author of 5b50f2c33390631b0410b961bdbe75e5c46de106 re-adding a bunch of such references.  @jasonmp85 You just complained to me about this ;)

**Comment by jasonmp85** [comment]
Recently I'm getting in the habit of just re-running Travis until the build passes with the right OIDs… it's pretty annoying, especially when I'm e.g. catching up enterprise with Citus and need to do a lot of builds and merges that should "just pass".
