### ISSUE TITLE
node membership should use a catalog table instead of pg_worker_list.conf

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#786]
We'll:
- Create a new table: `pg_dist_node (nodeid int, nodename text, nodeport int, groupid int)` .
- Upon `ALTER EXTENSION UPGRADE` we'll import data from `pg_worker_list.conf`, then rename the file to `pg_worker_list.conf.no_longer_used`.
- If `pg_worker_list.conf` exists we throw an error, informing users who might auto generate the file that it no longer works.
- create a new function: `master_add_node(nodename, nodeport)` which attempts to connect to the worker and if it is up assigns it a groupid and adds a row to `pg_dist_nodes`. Once nodes have been added they're immediately available for use.
- create a new function: `master_remove_node(nodename, nodeport)`, which throws an error if there exist any shard placements which use the node in question. If there are no shard placements referencing this node it drops the row from `pg_dist_nodes`.

Questions:
- When do we throw the error if `pg_worker_list.conf` exists? We probably can't throw it immediately, since during an upgrade the reboot happens before `ALTER EXTENSION`. So it gets thrown when you try to call one of the `master_...` functions?

Note to self:
- When pulling this code over from the private repo, `node_metadata.c` should either hash on a key like `nodename:nodeport` or just cache the node list.

**Comment by jasonmp85** [comment]
Could we instead erase the file and modify `citus` to error out with a message if it's present?

People might have tools that write the file for them; simply adding a header won't notify those users.

**Comment by anarazel** [comment]
If so we should rename it, instead of just removing it.

**Comment by lithp** [comment]
Renaming the file makes sense to me. I don't want to get rid of the data that's already there but it should be obvious that it's not being used.

**Comment by lithp** [comment]
@jasonmp85 When do you suggest throwing the error if `pg_worker_list.conf` exists? We can't throw it upon boot since the reboot with the new code will happen before `ALTER TABLE`. Maybe we check before any distributed DML?

**Comment by lithp** [comment]
Some operational scenarios to consider:

**Adding a new node**: After setting the node up call `master_add_node` on the master, then migrate data over like you usually would.

**Removing a node**: After moving all shard placements off of the node, call `master_remove_node` on the master.

**Moving a node to a new IP**: `pg_dist_shard_placement` is still denormalized, so you have to atomically update all relevant rows there along with the `pg_dist_node` row.

**Temporarily bringing a node down for maintenance**: Currently you can mark all relevant entries in `pg_dist_shard_placement` as `inactive` while the node is down, that's still possible. If a node is removed from `pg_dist_nodes`, even though we no longer run DML on its shards, we should be careful to mark the placements as `FILE_INACTIVE` should modifications be made to the other placements of those shards.

**Rolling upgrades to pg 9.6 (for instance)**: Assuming you use something like pg_upgrade, do the same as you would to temporarily bring nodes down, but staggered across the cluster.
