### ISSUE TITLE
Support HAVING clause

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#787]
We've had several requests from users recently to add support for the ``HAVING`` clause. Tableau's default PG driver also generates queries with ``HAVING``, and users wouldn't have to change their driver settings.

IIRC, this could be a simple change. We'd basically treat the ``HAVING`` clause like ``ORDER BY``, let the query complete and then perform the final ``HAVING`` on data collected on the master node.

Right now, users need to enable subselect pushdowns and rewrite their queries in a way that feels awkward. They may also run into other issues related to subselect pushdowns.

I'm also adding an example query below.

<pre>
SELECT profile_id
FROM profile_segment
WHERE (segment_id = 'X'
       OR segment_id = 'Y'
       OR segment_id = 'Z')
GROUP BY profile_id
HAVING count(distinct segment_id) >= 2
</pre>

**Comment by ozgune** [comment]
@metdos (or @byucesoy) -- if we wanted to implement this feature, how long do you think it would take?

**Comment by jasonmp85** [comment]
We had a similar issue in `pg_shard`: citusdata/pg_shard#53. It was fixed here: citusdata/pg_shard#55.

**Comment by metdos** [comment]
> @metdos (or @byucesoy) -- If we wanted to implement this feature, how long do you think it would take?

Hey @ozgune, you're right, this looks like a simple change. Less than one week should be enough to merge it.
