### ISSUE TITLE
the query "select (customer_id, review_date) as test from customer_reviews limit 1;" produces the error: column "intermediate_column_85_0" has pseudo-type record. A column in a PostgreSQL table cannot have record as a type, so creating a temporary table fails.

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#79]
the query "select (customer_id, review_date) as test from customer_reviews limit 1;" produces the error: column "intermediate_column_85_0" has pseudo-type record. A column in a PostgreSQL table cannot have record as a type, so creating a temporary table fails.

**Comment by marcocitus** [comment]
We no longer use temporary tables and this query works normally.
