### ISSUE TITLE
Add worker transactions infrastructure with transaction recovery

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#792]
Add functions for sending commands to all workers through 2PC and integrate 2PC transaction recovery into Citus. The former can be achieved through the unified networking API (#704).

**Comment by aamederen** [comment]
What is the status of #704 in the context of this issue? Should we wait until the unified networking API is ready?

**Comment by marcocitus** [comment]
I think we should go ahead and add worker_transactions. We also need it to do rebalancing safely.
