### ISSUE TITLE
Error out when performing unsupported operations on workers

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#793]
In MX, we propagate distributed tables to all workers, but certain operations such as DDL can only be performed on the coordinator. Other operations need to error out.

**Comment by aamederen** [comment]
This requires distinguishing the master from the other nodes. How should we do this? I could think of the following options:

- Add the master into the pg_dist_node table with groupid = 0
- If the current node is not in pg_dist_node, then it means we are the master.

**Comment by marcocitus** [comment]
MX has the pg_dist_local_group table which is set to 0 for the coordinator and to a >0 value for new nodes that join. Adding this table is part of #797.

**Comment by marcocitus** [comment]
A change from MX in 6.1 is that master_modify_multiple_shards also needs to error out on workers, as well as new code paths such as INSERT .. SELECT and reference tables.

**Comment by marcocitus** [comment]
and mark_tables_colocated

**Comment by aamederen** [comment]
- master_create_distributed_table
- create_distributed_table
- create_reference_table
- master_create_worker_shards
- master_move_shard_placement
- master_copy_shard_placement
- DDL commands
- master_modify_multiple_shards
- master_drop_all_shards
- master_apply_delete_command (?)
- master_add_node
- master_remove_node
- TRUNCATE
- INSERT / SELECT
- mark_tables_colocated

**Comment by onderkalaci** [comment]
Also, #967. I'm assigning that issue to you :) We can talk about the issue in person.

**Comment by onderkalaci** [comment]
> as well as new code paths such as INSERT .. SELECT

@marcocitus I've some ideas on why do we want to disable this. But, could you also clarify what are your thoughts on this?

**Comment by marcocitus** [comment]
> @marcocitus I've some ideas on why do we want to disable this. But, could you also clarify what are your thoughts on this?

Due to the likelihood of deadlock we don't allow concurrent multi-shard commands on overlapping sets of shards, which we prevent through shard resource locks on the master.
