### ISSUE TITLE
Add regression tests for queries from workers

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#795]
We have a number of regression tests that we will want to run from the distributed tables on workers as well.

**Comment by aamederen** [comment]
For this task, I can think of 2 approaches

- Copy (almost) all of the regression tests from the citus-mx project to a separate schedule: `multi-mx`
- Create regression tests for all 5.2+ features (by referring to Changelog)
- All new features should also add some (maybe lighter) tests to the `multi-mx` schedule.

or

- Make `multi-mx` a redundant queries schedule (like TPCH) and add MX-related tests to their respective test files.
- All new PRs should test the features from the mx perspective on their own PRs.

@marcocitus, @onderkalaci  What do you think?

**Comment by metdos** [comment]
@aamederen, one note, if we follow the first approach, let's make sure that we run these tests with Travis.

**Comment by marcocitus** [comment]
I'm fine with whatever approach you choose. The main goal is to get good test coverage for execution logistics on workers, e.g. re-testing advanced planning features on the workers does not provide much benefit, but re-testing different types of re-partitioning and broadcast joins is.

**Comment by sumedhpathak** [comment]
👍
