### ISSUE TITLE
We have three standing items related to Citus' PostgreSQL 9.2 integration

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#80]
(Multiple items in one) We currently have a few standing items related to our PostgreSQL 9.2 integration. These issues aren't immediate, but should be cleaned up in the medium term. These include removing all relay file related configuration from guc. and postgresql.c, refactoring psql/copy.c, and changing the sleeping mechanism in task_tracker.c.

**Comment by ozgune** [comment]
A quick update on the three points reported on this issue.

* Remove all relay file related config from guc and postgresql.c: We already did this
* Refactor psql/copy.c: we removed psql and therefore resolved this issue
* Change sleeping mechanism in task_tracker.c: We're already tracking this issue in #296

I'm therefore closing this issue as resolved.
