### ISSUE TITLE
Add a column to pg_dist_partition that activates metadata propagation on a table

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#800]
We need a way to distinguish MX tables from ordinary distributed tables. Add a new column to pg_dist_partition and the necessary infrastructure for reading it in metadata_cache.c.

**Comment by onderkalaci** [comment]
We're also going to add another column to pg_dist_partition (i.e,`colocationid`).
 I'm just noting here that if we check-in that PR first, we need to rebase the MX commit.
