### ISSUE TITLE
Remove copy_to_distributed_table

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#809]
The copy_to_distributed_table script still exists, but has been superseded by COPY. Should we remove it?

**Comment by metdos** [comment]
I think the idea was to keep it until next big release as a backup. So far, COPY seems good and we're moving to 6.0. Therefore, I think we should remove it :)

**Comment by ozgune** [comment]
Quick question. Do we reference ``copy_to_distributed_table`` in our documentation?

**Comment by lfittl** [comment]
@ozgune From looking at the `citus_docs` repo, we've had this in v5.0, but its gone from both v5.1, v5.2 and latest.
