### ISSUE TITLE
Postmaster crash-restarts lead to xact hooks being established multiple times

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#813]
Because router (and some other parts) use shmem callbacks, which get executed after every crash-restart, every crash-restart adds another RouterTransactionCallback to the chain. That makes every commit trying to commit remote transactions repeatedly. That in turn leads to repeated log entries like
```
WARNING:  there is no transaction in progress
```

I don't quite know why we ended up using  a shared memory hook for this. I think we should simply remove the usage of said hook, and register those callbacks like all the others we register in _PG_init().

@jasonmp85 Do you remember how we ended up doing this?

**Comment by jasonmp85** [comment]
Welp, now I'm glad I didn't close the window for 5.2.2 yet…

Yeah, I think we discussed whether that hook would be a suitable "runs one time" type thing and I thought you said basically yes, so I leaned on it as a "register this once" type semantic.

Didn't know about this behavior under crashes. I, as a part of the DDL transaction changes, believe it was changed to use the same hook (for consistency). I suppose that should be fixed, too. Will look at this tomorrow (it's less pressing with #812 merged).
