### ISSUE TITLE
Problem with double-quoted table names - Table names can have spaces, dots, … and they can be case sensitive when we put them inside double-quotes. In stage.c, in ExtendTablename function, we don’t support these kind of table names, and staging gives syntax error.

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#82]
Problem with double-quoted table names - Table names can have spaces, dots, … and they can be case sensitive when we put them inside double-quotes. In stage.c, in ExtendTablename function, we don’t support these kind of table names, and staging gives syntax error.

**Comment by byucesoy** [comment]
#588 will fix similar problems to this one, but we do not apply same fix to this one because \stage will be deprecated soon. COPY can be used instead.

**Comment by anarazel** [comment]
\stage does not exist anymore.
