### ISSUE TITLE
check-multi-task-tracker-extra fails

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#839]
After [this commit](https://github.com/citusdata/citus/commit/37631cd132d8d7890d1caae77d3a6ec9737397a6) removed the alternate hash pruning test output, check-multi-task-tracker-extra started failing.

It seems that we needed that `multi_hash_pruning_0.out` file or we may need to rethink the debug messages.

**Comment by sumedhpathak** [comment]
Closing this as dupe of #856
