### ISSUE TITLE
Map / isolate certain distribution keys to their own shard/shard placement

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#844]
# Request

Citus users today create a distributed table by picking their distribution column and method. Citus then automatically maps the distributed column's values to shards/shard placements.

We heard from multiple customers that they would like to extend on this distribution logic. In particular, they'd like to map specific values to their own shards. For example, if you're creating a `customers` table, you may want to extend on the default logic to map `customer_id = 10` to its own shard.

Motivations for wanting to have this special logic could include:
- We have a large (or important) customer whose data warrants dedicated resources. We'd like to make sure `customer_id = 10` gets its premium share.
- We have a noisy customer whose requests are hurting other customers who get assigned to their shard. We'd like to make sure `customer_id = 10` receives fewer resources isolated on smaller instances.
- If we break anything for this particular customer, we don't want it affecting other customers. Two examples are: we're using `customer_id = 10` for internal development or testing. Or, we're using `customer_id` for pre-production testing -- we first release our changes for this customer and if all looks good, for all customers.

One way to implement this feature is by overriding our hash function and making sure that users can manually set the mapping from a value to a hash token. There may be other ways.

I'm opening this issue to track our progress on this feature. This issue could also be related to the conversation around colocation apis (#695).

# Proposal
- [x] Create isolate_tenant_to_new_shard()
    - [x] Signature will be
isolate_tenant_to_new_shard('target_table', 'tenant_id')
    - [x] It will error out if target_table is colocated with other tables and advise to run it with CASCADE option
    isolate_tenant_to_new_shard('target_table', 'tenant_id', 'CASCADE')
    - [x] It will create 3 new shards and divide hash space into three: a. hash of the isolated tenant, b. lower space and c. upper space. It will return the shard id of the isolated tenant. Then, the user can move the new shard to wherever he wants with master_move_shard_placement(). 
    - [ ] It will increase the shard count of the colocation group by 2 (we decided to drop this).
    - [x] It will allow SELECTs during this operation, but it will block modifications.
    - [x] Only valid for hash-distributed tables, and error out otherwise.
    - [x] Make sure that we handle the corner case that the hash value of the tenant_id would be just on the border of the original shard. For such cases, we should divide shard into 2 instead of 3.
    - [x] (Optional) For replication count > 1, we will error out if there is an inactive shard in the colocated shards for the given tenant id.
<br />

- [ ] Add excluded_node_list option to rebalance_table_shards() and replicate_table_shards(). This is required if the user wants to keep a tenant isolated on a specific node during a rebalance or replication operation.

- [ ] (Optional) Create a simple wrapper of master_move_shard_placement() for the case of the replication count = 1 to skip providing source node name and node port:
move_shard(shardid, nodename, nodeport)

- [ ] (Optional) Create a simpler wrapper function for demo purposes which calls split and move functions in order:
move_tenant_to_node('table_name', 'tenant_id', nodename, nodeport)
instead of 
isolate_tenant_to_new_shard() and master_move_shard_placement().

- [ ] (Optional) Create a merge function to undo effects of tenant isolation. This function would take a list of shards and merge them if their hash spaces are continuous together.

Other notes:
We will not handle hash collision.

**Comment by anarazel** [comment]
> We heard from multiple customers that they would like to extend on
> this distribution logic. In particular, they'd like to map specific
> values to their own shards. For example, if you're creating a
> ``customers`` table, you may want to extend on the default logic to
> map ``customer_id = 10`` to its own shard.

Is the primary issue here that multiple keys are hashed to the same
hash, or just that several customers end up in the same bucket?

If it's the bucketing, it's quite possible to solve this by splitting
the existing bucket assigned to a shard into three. The "upper" portion
of the hash-space, the individual customer's hash (just one wide), and
the lower portion of the space.


> One way to implement this feature is by overriding our hash function
> and making sure that users can manually set the mapping from a value
> to a hash token.

I don't like this approach a lot. Decoupling from the postgres hash
functions (i.e. the defaults hash op for a datatype) seems quite likely
to cause trouble later.

**Comment by ozgune** [comment]
I wanted to document two alternatives on the user api front. As we talk about these APIs, let's also talk about their timelines on the engineering side.

Let's say that we have a multi-tenant application that has a few tables. In v6.0, we'd create these tables in the following way:

<pre>
CREATE TABLE company (company_id text, ...);
SELECT create_distributed_table('company', 'company_id');

CREATE TABLE leads (company_id text, lead_id bigint, ...);
SELECT create_distributed_table('leads', 'company_id');

CREATE TABLE conversions(company_id text, conversion_id bigint, ...);
SELECT create_distributed_table('conversions', 'company_id');

CREATE TABLE nation(nation_id integer, ...);
SELECT create_reference_table('nation');
</pre>

Let's then say that the user wants to isolate a particular "company_id" for one of the three reasons outlined above. We could then enable this in one of two ways -- are there others?

(The following proposals are a WIP and I'll update them shortly.)

<h3>Proposal 1</h3>

In this option, the user can call a user-defined function for isolation either before going into production or when the cluster is running.

<pre>
SELECT isolate_distributed_table_tenant('company', 'Verizon');
</pre>

This call would then isolate the tenant with the identifier ``'Verizon'`` into its own shard. The following questions are open questions:

1. When the user calls this function, we should also split the related shards for ``leads`` and ``conversions`` and move their shard to another machine. Is this intuitive to the user?
2. After calling this function, what happens if the user calls ``SELECT  isolate_distributed_table_tenant ('leads', 'Verizon');``
3. Do we split the existing shard related to ``Verizon`` into 2 or 3? Ideally, we'd have fewer shards.
4. Do we only create a separate shard? Or do we go ahead and transfer those "shards" into a separate unloaded machine? It's hard to judge the user's intent when calling this function.
    * If we're concerned about performance, then they may want the shard to go into its own machine. In this case, what if there isn't a machine that doesn't have any shards in the cluster?
    * If the user's concerned about isolation for testing / development purposes, then it may be enough for the shard to live with other shards on a machine.
5. Let's say that we created three new shards for tables ``company``, ``leads``, and ``conversions``. Let's say that we then created another colocated table ``accounts``. How are we going to make sure that this new table's has a separate shard for ``Verizon``? Is our colocation logic as implemented in #695 good enough?
6. (minor) What happens if we have hash collision between ``Verizon`` and another key. Do we move those two keys into the new shard(s)?

On the first question, another alternative that makes the notion of colocation more explicit could be the following:

<pre>
SELECT isolate_colocated_tables_tenant('Verizon');
</pre>

This slight variation makes it obvious that we're isolating the ``Verizon`` tenant across all colocated tables. However, it may also introduce confusion around which of the existing tables are colocated.

<h3>Proposal 2</h3>

(to update in 1-2 days)

**Comment by metdos** [comment]
We had a nice long conversation about this topic. I'm listing items we have discussed with decisions and open issues.

1- (Addresses Proposal 1.4) We decided to have two separate functions to implement this feature. Differently from Proposal-3, and similar to Proposal-1 and Proposal-2 above, these functions can be called anytime.

- First split shard on the same machine for the given tenant id
```sql
isolate_tenant_to_new_shard('table_name', 'tenant_id')
```
Another alternative for naming;
```sql
split_shard_for_tenant('table_name', 'tenant_id')
```

- Then move created new shard to another node (such as a new node for performance reasons)

We already have master_move_shard_placement(), but we also discussed to have a simple wrapper for the case of the replication count = 1 to skip providing source node name and node port:
```sql
move_shard(shardid, nodename, nodeport)
```

@samay-sharma also suggested having a simpler wrapper which calls these two functions. @marcocitus has some concerns about if it is possible to do this in a single transaction. The verdict is to implement this wrapper function if it does not require too much effort.

2- (Addresses Proposal 1.1) We decided to split colocated shards for a tenant altogether. Actually, this is a must to maintain colocation. To make this explicit, we decided to add ``CASCADE`` option to the API. Basically, if the table has colocated tables, it will require the user to pass ``CASCADE`` option (Exact syntax (string, boolean, enum) remains an open question).
```sql
isolate_tenant_to_new_shard('table_name', 'tenant_id', CASCADE)
```

3- We will only support hash distributed tables.

4- For replication count > 1, we will implement this if it does not require too much effort. One question for replication_count > 1 is what to do about inactive shards. The current verdict is to error out if there is an inactive shard in the colocated shards for the given tenant id.

5- (Discussion of Proposal 1.5) Short answer is yes, we will correctly colocate a new table with the existing tables even if they have isolated tenant ids. However, we would need to decide how this will interact with the pg_dist_colocation table. If we increase shard count of the colocation group, then the user would need to use colocate_with option while creating a distributed table to have colocation right.

**Comment by onderkalaci** [comment]
Two notes / open questions:

1 - 

> . To make this explicit, we decided to add CASCADE option to the API. Basically, if the table has colocated tables, it will require the user to pass CASCADE option (Exact syntax (string, boolean, enum) remains an open question).

I was expecting this to be the default behaviour instead of explicitly providing `CASCADE` option. Wouldn't users want to split colocated shards all together? 

Say you have `users` and `events` tables, both partitioned on `user_id`. Do we want only one of the table's shard splitted? I think, without being able to run  split operation within a transaction, this would cause some problems. For instance, router plannable queries start not working because some of the shards are already splitted and moved some not.

2 - We should probably wouldn't want to block `SELECTs` during the shard split + shard move operations. It'd even be great if we can allow modifications as well (which seems quite hard).

**Comment by metdos** [comment]
> 1 -
> 
> . To make this explicit, we decided to add CASCADE option to the API. Basically, if the table has colocated tables, it will require the user to pass CASCADE option (Exact syntax (string, boolean, enum) remains an open question).
> I was expecting this to be the default behaviour instead of explicitly providing CASCADE option. Wouldn't users want to split colocated shards all together?
> 
> Say you have users and events tables, both partitioned on user_id. Do we want only one of the table's shard splitted? I think, without being able to run split operation within a transaction, this would cause some problems. For instance, router plannable queries start not working because some of the shards are already splitted and moved some not.

I think the idea was to resemble the behavior of PostgreSQL. If there are colocated tables, and the user didn't provide the CASCADE option, we will error out and advise to run the function with CASCADE option. This allows the user to make this decision explicitly.

**Comment by onderkalaci** [comment]
> (We will not allow splitting shards for just one of the colocated tables).

Okay, that makes sense :)

**Comment by metdos** [comment]
@ozgune, @samay-sharma, @saicitus
I updated the issue with the proposal. Could you take a look and let me know if something does not fit?

**Comment by marcocitus** [comment]
Just some implementation notes.

To avoid failures and inconsistency, we'll need to commit the changes to the shards before the changes to the metadata. Otherwise, queries could start to come in before the new shard placements are visible / have been committed on the worker.

One design could be to create 2 new shards and migrate data from the original shard to the two new shards. However, this design is likely to lead to issues because we cannot simultaneously commit the new metadata on the master and the data migration on the worker. Either the data migration is committed before the new metadata becomes visible on the master, meaning part of the data temporarily appears to be gone as queries don't include new shards. Or the data migration is committed after the new metadata becomes visible on the master, meaning queries might fail as the target shard placement appears to not exist or unexpected results are included in queries (e.g. data from the isolated tenant ends up in the wrong shard during INSERT .. SELECT).

A more robust design is to create 3 new shards (e.g. through 3 `CREATE TABLE .. AS SELECT` statements), commit them, and drop the original shard after the master commits (using 2PC).  This guarantees that the shard placements are already visible on the worker when new metadata becomes visible on the master. While this approach creates extra work, this is partly offset by the fact that it avoids excessive deletion and vacuuming.

Tenant isolation should also lock shards across other workers and sync metadata for MX.

**Comment by metdos** [comment]
> (e.g. through 3 CREATE TABLE .. AS SELECT statements)

Do you mean something like;

CREATE TABLE .. AS SELECT * FROM orginal_shard WHERE 
    hash(distribution_column) < hash(tenant_id) AND 
    hash(distribution_column) >= orginal_shard_min_value;

> drop the original shard after the master commits (using 2PC).

This means after the master commits flipping shards in metadata, and using 2PC for MX, right?

**Comment by marcocitus** [comment]
> Do you mean something like this;
>
> CREATE TABLE .. AS SELECT ...

Yes.

> This means after the master commits flipping shards in metadata, and using 2PC for MX, right?

More or less. It should become reasonably straight-forward to send a command that gets committed in a 2PC using the new connection API.

**Comment by ozgune** [comment]
@metdos -- I'm reading the issue description and had a quick question.

We say in the description that we want to "add excluded_node_list option to rebalance_table_shards() and replicate_table_shards()." Do we need to use the higher shard rebalancing functions or can we just use the lower level shard copy/move functions to move the split shard to a new machine?

**Comment by metdos** [comment]
> @metdos -- I'm reading the issue description and had a quick question.
> 
> We say in the description that we want to "add excluded_node_list option to rebalance_table_shards() and replicate_table_shards()." Do we need to use the higher shard rebalancing functions or can we just use the lower level shard copy/move functions to move the split shard to a new machine?

I updated the related part.

"This is required if the user wants to keep a tenant isolated on a specific node during a rebalance or replication operation."

Is it clear now? We don't need this to isolate the tenant, but to keep it isolated during a rebalance or replication operation.

**Comment by ozgune** [comment]
@metdos -- got it, thanks for the clarification.

@craigkerstiens recently had a question about splitting shards; and I wanted to make a note of it here. We talked about resizing existing shards (splitting a large shard into two) as an interesting feature. That way, if customers observe data growth at a rate faster than they anticipated, they can later dynamically split their shards into two. How much of an overlap is there between that feature and the tenant isolation one?

The shard split feature is out of scope for #844 -- I just wanted to ask the question so we start thinking about it.

**Comment by metdos** [comment]
> @craigkerstiens recently had a question about splitting shards; and I wanted to make a note of it here. We talked about resizing existing shards (splitting a large shard into two) as an interesting feature. That way, if customers observe data growth at a rate faster than they anticipated, they can later dynamically split their shards into two. How much of an overlap is there between that feature and the tenant isolation one?

@ozgune, they hugely overlap. Doing some minor work should be enough to support this. We can do this for the cluster, or on the individual shard level (just picking the largest shards).

Doing this for the cluster, such as from 16 to 32 shards requires a bit more thinking around doing it serially or parallelly.
i. parallel -> faster but IO can be a bottleneck
ii. serial -> takes longer to finish (similar to shard rebalancer)

**Comment by marcocitus** [comment]
> Doing this for the cluster, such as from 16 to 32 shards requires a bit more thinking around doing it serially or parallelly.

When I explain the shard rebalancer to customers they generally appreciate that it doesn't hose the cluster, which happens in some other databases when rebalancing. I think doing it as a serial sequence of autonomous subtransactions is better than parallel in this case.

**Comment by ozgune** [comment]
@metdos, I wanted to follow up on an internal email. Could you give an example of our final API? (an example where the user creates a distributed table and calls this function)

If you have a few alternative proposals in mind, could you also list them in your example?

**Comment by metdos** [comment]
Merged both community and enterprise PRs, and sent an email about docs. Closing this issue.
