### ISSUE TITLE
Move default shard count to a GUC

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#845]
This came up in #695. Task is to simply have a default shard count on a GUC as we do for default replication factor.

**Comment by onderkalaci** [comment]
@ozgune 
I expect that only `create_distributed_table` obeys this GUC not the `master_create_worker_shards()`. Is that what you have in your mind as well?

**Comment by metdos** [comment]
Related to #802

**Comment by ozgune** [comment]
@onderkalaci -- yes, I was thinking that we'd using this config setting only in ``create_distributed_table``.
