### ISSUE TITLE
Remove pg_worker_list.conf related Code and GUC

### ISSUE THREAD

**Issue by aamederen** [citusdata/citus#848]
With #786 is closed by #798, we no longer use pg_worker_list.conf. However, for upgrade purposes, we left some portions of the code about parsing pg_worker_list.conf file:
- `citus.worker_list_file` GUC
- `master_initialize_node_metadata` UDF (called automatically after update to 6.0)

These should be removed from the code after we decide not to support upgrades from Citus 5.

**Comment by sumedhpathak** [comment]
@lithp this wasn't planned for 6.1. Any reason to add this item for the current cycle?

**Comment by lithp** [comment]
@sumedhpathak I didn't want this to get lost, it's maintenance that should be done eventually and I figured if it wasn't added to a milestone we would lose track of it.

**Comment by ozgune** [comment]
@lithp -- I added this item to our v6.2 product planning spreadsheet. We'll make sure not to lose track of it.
