### ISSUE TITLE
When uploading regular files, non-qualified filenames work. For foreign files, they fail. We need to make sure that \stage works consistently for regular and foreign tables, and between full and non-qualified file paths.

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#85]
When uploading regular files, non-qualified filenames work. For foreign files, they fail. We need to make sure that \stage works consistently for regular and foreign tables, and between full and non-qualified file paths.

**Comment by metdos** [comment]
Works with COPY.
