### ISSUE TITLE
check-multi-task-tracker-extra tests don't pass

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#856]
At the moment the tests don't seem to work, to a large degree, I think, because plans that are normally router plannable aren't due to the default setting of task-tracker in this test.

It's pretty odd that this is broken right now, without anybody of us noticing.

@jasonmp85 I think we really need to require make check to entirely pass, not just subsets. This isn't the first time stuff broke.

**Comment by anarazel** [comment]
I bet this is caused by 37631cd132d8d7890d1caae77d3a6ec9737397a6 - @jasonmp85

**Comment by metdos** [comment]
> It's pretty odd that this is broken right now, without anybody of us noticing.

Actually, in Istanbul office, we have noticed that :) #839


> @jasonmp85 I think we really need to require make check to entirely pass, not just subsets. This isn't the first time stuff broke

+1
