### ISSUE TITLE
Warnings show up in schema-only pg_dump due to dependency loops

### ISSUE THREAD

**Issue by lfittl** [citusdata/citus#866]
Splitting this out from #348 per a discussion with @ozgune and @anarazel.

When running a schema-only pg_dump, as some migration frameworks do (e.g. `rake db:migrate` with Rails/ActiveRecord), the following warnings appear:

```
  pg_dump: [sorter] WARNING: could not resolve dependency loop among these items:
  pg_dump: [sorter]   TABLE impressions  (ID 240 OID 19654)
  pg_dump: [sorter] WARNING: could not resolve dependency loop among these items:
  pg_dump: [sorter]   TABLE clicks  (ID 241 OID 19661)
```

**These are harmless** since we can still successfully dump the schema on the master, but people have been confused by this a couple of times.

The fix for this seems to be rather involved, and might require some upstream Postgres changes - for now one should just ignore these.

**Comment by anarazel** [comment]
The issue is actually easily solvable.  The issue is that we've a dependency from the sharding expression to the table, to prevent the partition column from being dropped.  You'd get
```
ERROR:  2BP01: cannot drop table test_table2 column test_id because other objects depend on it
DETAIL:  table test_table2 depends on table test_table2 column test_id
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
LOCATION:  reportDependentObjects, dependency.c:985
Time: 5.596 ms
``` 
but we also have another check these days:
```
ERROR:  XX000: cannot execute ALTER TABLE command involving partition column
LOCATION:  ErrorIfUnsupportedAlterTableStmt, multi_utility.c:1700
Time: 4.988 ms
```
so we can just drop the expression dependency.

**Comment by anarazel** [comment]
If we want to keep the dependency, we could alternatively have a dependency from pg_dist_partition to the expression.  That'd allow us to drop the check.
