### ISSUE TITLE
Ubuntu 9.10 comes with libreadline6 in default. We should install libreadline5 in order to install our readline5 package. We can depreciate our support for Ubuntu 9.10 later.

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#87]
Ubuntu 9.10 comes with libreadline6 in default. We should install libreadline5 in order to install our readline5 package. We can depreciate our support for Ubuntu 9.10 later.

**Comment by ozgune** [comment]
@sumedhpathak / @jasonmp85 -- do we provide any packages that have readline5 dependencies?

If not, could we close this issue?

**Comment by jasonmp85** [comment]
Now all our packages are actually built on the OSes they're targeting, using `Docker`. So the dependency issues are largely gone, as we're building against what the OS has available anyhow.

Additionally, we probably don't depende on `readline` anymore; that's probably a holdover from when we were a PostgreSQL fork. We still have a `libedit-dev` dependency in our Debian files, but I think that can be removed now that `csql` is gone.

**Comment by jasonmp85** [comment]
I think this should be closed. Closing.
