### ISSUE TITLE
Upgrading from 5.2 to the master branch is failing

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#875]
I didn't have time to investigate this in detail. But, upgrading from 5.2 to the current master branch is not working smoothly.

```
git checkout tags/v5.2.1
make clean -s
 make -j9 -s
sudo make install

/* a custom script that creates 3 node cluster */
init_dbs.sh 


psql -c "CREATE TABLE asd(a int);"
psql -c "SELECT master_create_distributed_table('asd', 'a', 'hash')"
psql -c "SELECT master_create_worker_shards('asd', 8, 2)"
psql -c "SELECT * FROM asd;"

git checkout master
make clean -s
 make -j9 -s
sudo make install

psql -c "SELECT * FROM asd;"


psql -c "ALTER EXTENSION citus UPDATE;"
ERROR:  could not find function "column_to_column_name" in file "/usr/local/pgsql/lib/citus.so"

/* now that restart all nodes */
restart_workers.sh 

/* still failing */
 psql -c "ALTER EXTENSION citus UPDATE;"
ERROR:  could not find function "cluster_create_distributed_table" in file "/usr/local/pgsql/lib/citus.so"
```

Besides, we've another issue that I've mentioned on #816 . We should fix these two issues before the code-freeze. In general, we should make sure that user can smoothly upgrade to 6.0

@sumedhpathak can you assign someone to work on this?

**Comment by mtuncer** [comment]
it could be due to old build artifacts. Does it still occur when a different clone is used for v5.2.1 and current master ?

**Comment by onderkalaci** [comment]
> it could be due to old build artifacts. Does it still occur when a different clone is used for v5.2.1 and current master ?

I updated the description, added `make clean` before compiling `master` branch. Is that what you're asking for?

**Comment by mtuncer** [comment]
No I meant using different completely different project folders created by "git clone".

**Comment by sumedhpathak** [comment]
Hey @lithp could you take a look at this issue? Thanks!

**Comment by marcocitus** [comment]
I previously had some trouble with the citus-mx 5.2--1--6.0-1 upgrade script still being in my PostgreSQL installation directory and postgres picking those to upgrade instead of the citus ones.

**Comment by onderkalaci** [comment]
@mtuncer 

> No I meant using different completely different project folders created by "git clone".

I cloned a new repo, still the same

**Comment by sumedhpathak** [comment]
For #816, @lithp could you replace the ``Assert(!isNull)`` with something that adds a default value to the column if it is null? That will avoid this scenario.

**Comment by lithp** [comment]
@onderkalaci I couldn't reproduce the issue with missing functions, could you test again on master and make sure it's still there? Maybe try doing the restart before you run `ALTER EXTENSION`.

**Comment by marcocitus** [comment]
This is just an MX development artifact. Just `rm /usr/local/pgsql/share/extension/citus--5.2-1--6.0-1.sql` and reinstall citus.

**Comment by lithp** [comment]
To confirm what marco just said you can run `SELECT * FROM pg_extension_update_paths('citus') WHERE source = '5.2-1' AND target = '6.0-11';` after you've run `make install`.

MX will have an entry which skips from 5.2-1 straight to 6.0-1, but the proper sequence will look like: `5.2-1--5.2-2--5.2-3--5.2-4--6.0-1--6.0-2--6.0-3--6.0-4--6.0-5--6.0-6--6.0-7--6.0-8--6.0-9--6.0-10--6.0-11`.

Doing a fresh clone won't fix the issue because these scripts are put into `--prefix`, you have to delete that directory, then rebuild postgresql and citus. (You could also take the offending files out of `[prefix]/share/postgresql/extension` I suppose)
