### ISSUE TITLE
CopyShardPlacement should use table owner

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#881]
In CopyShardPlacement we currently connect as the extension owner when creating the new shard placement:
https://github.com/citusdata/citus/blob/master/src/backend/distributed/master/master_repair_shards.c#L284

This should be the table owner for each of the co-located tables. Otherwise, the user might not be able to access the placement.

Alternatively, we could continue connecting as the extension owner (being careful that there is no privilege escalation) and reset the owner using `ALTER TABLE`.

**Comment by anarazel** [comment]
Agreed, this is a bug. We should really use the relation owner, not the superuser. ALTER TABLE can run code, so it's not a good idea to use a different user. It also shouldn't be hard to change things.

**Comment by sumedhpathak** [comment]
@marcocitus for my understanding, is this a regression from our previous rebalancer? Did we support multi-user table rebalancing before?

**Comment by marcocitus** [comment]
Iirc we just connected as the current user and checked that it's the table owner. We can still do that, but a new complication is that different tables can have different owners. I think if we needed a quick & dirty fix connecting ad the current user would still be reasonable though. I don't think users have a lot of different table owners.

**Comment by marcocitus** [comment]
We could also consider only allowing one owner per co-location group, which might simplify things. We'd probably want to add a role column to pg_dist_colocation in that case.

**Comment by sumedhpathak** [comment]
@byucesoy I presume this shouldn't be closed by the Create Table FK PR? Was this fix explicitly intended to be in that PR? i.e., Did we test that scenario as part of the FK pushdown change?

**Comment by byucesoy** [comment]
As @marcocitus said, we already changed related part of CopyShardPlacement function for foreign key push down and did not want to add buggy code on purpose.

**Comment by sumedhpathak** [comment]
I see, that's good to know. Do we have separate regression tests for this in the Enterprise repo? Or should we open up an issue to add them?

**Comment by anarazel** [comment]
On 2016-10-20 10:36:34 -0700, Marco Slot wrote:
> Iirc we just connected as the current user and checked that it's the table owner. We can still do that, but a new complication is that different tables can have different owners. I think if we needed a quick & dirty fix connecting ad the current user would still be reasonable though. I don't think users have a lot of different table owners.

Agreed, I think that's a lot better than the current behaviour.
