### ISSUE TITLE
Master-Issue: Duplicated code from PostgreSQL that can be removed:

### ISSUE THREAD

**Issue by anarazel** [citusdata/citus#883]
This issue is supposed to track code duplication between postgres and similar code smells. Once an individual issue is being addressed a separate item for it should be created and then closed with a pull request.

After 9.5 support has been dropped:
- [x] simplify/deduplicate MasterIrreducibleExpressionWalker() using check_functions_in_node() (See #1478)
- [x] copy of readfuncs.c and related code in citus_readfuncs.c/citus_outfuncs.c (See #1470)

**Comment by mtuncer** [comment]
both subtasks are merged
closing the issue
