### ISSUE TITLE
Prepared statements are not invalidated after shard placement changes

### ISSUE THREAD

**Issue by marcocitus** [citusdata/citus#887]
When using a prepared statements, the plan contains shard placement metadata. However, cached plans are not invalidated after pg_dist_shard_placement changes, meaning that writes that use prepared statements might not go to the right shard placements after a shard repair/move/copy.

**Comment by robin900** [comment]
This seems a duplicate, or an extension, of #127.

**Comment by marcocitus** [comment]
> This seems a duplicate, or an extension, of #127.

Yep, I think you're right. #127 should be higher on our list.
