### ISSUE TITLE
segment fault while query SELECT

### ISSUE THREAD

**Issue by meagon** [citusdata/citus#889]
```
postgres=# \d
DEBUG:  StartTransactionCommand
DEBUG:  StartTransaction
DEBUG:  name: unnamed; blockState:       DEFAULT; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children: 
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: DEBUG:  forked new backend, pid=4923 socket=9
DEBUG:  reaping dead processes
DEBUG:  server process (PID 4922) was terminated by signal 11: Segmentation fault
DETAIL:  Failed process was running: SELECT n.nspname as "Schema",
	  c.relname as "Name",
	  CASE c.relkind WHEN 'r' THEN 'table' WHEN 'v' THEN 'view' WHEN 'm' THEN 'materialized view' WHEN 'i' THEN 'index' WHEN 'S' THEN 'sequence' WHEN 's' THEN 'special' WHEN 'f' THEN 'foreign table' END as "Type",
	  pg_catalog.pg_get_userbyid(c.relowner) as "Owner"
	FROM pg_catalog.pg_class c
	     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
	WHERE c.relkind IN ('r','v','m','S','f','')
	      AND n.nspname <> 'pg_catalog'
	      AND n.nspname <> 'information_schema'
	      AND n.nspname !~ '^pg_toast'
	  AND pg_catalog.pg_table_is_visible(c.oid)
	ORDER BY 1,2;
LOG:  server process (PID 4922) was terminated by signal 11: Segmentation fault

```

the pid 4922 is the citus trace process

**Comment by metdos** [comment]
@meagon, that's interesting. We use \d all the time but have never seen a segmentation fault. 

Which version of Citus do you use?

**Comment by meagon** [comment]
@metdos  the master version right now, and postgresql 9.6

**Comment by metdos** [comment]
@meagon, thank you for reporting this and your time. I'm trying to replicate the problem. Can I ask for more information?

i. How did you install PostgreSQL? From source or from a binary. If you installed from the source, did you use any ./configure  parameters?

ii. What steps did you follow?
- Did you add citus to shared_preload_libraries?
- Did you create the citus extension?
- Other steps before you run \d? Such as table creation, calling Citus udfs etc.

**Comment by meagon** [comment]
@metdos  i got the postgresql-9.6.tar.bz2 source with  ``` configure --prefix=/opt/pg96 --disable-rpath ```

and install citus got the master repo code, with postgresql 9.6 's  ```pg_config ``` in system variable PATH,
```configure && make  && make install```

**Comment by metdos** [comment]
@meagon, I still could not replicate the problem. Which OS are you using?

Any other information which would be helpful?

**Comment by metdos** [comment]
@meagon, also was this a fresh installation or upgrade from previous versions?

Thanks.

**Comment by meagon** [comment]
i tried compile again，and did not reproduce the problem，maybe bad environment affect it？
sorry to interrubute you @metdos

**Comment by metdos** [comment]
@meagon, no worries. Thank you for your interest!
