### ISSUE TITLE
DDL changes and INSERT INTO SELECT within the same transaction deadlock

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#898]
This issue relates to the upcoming `INSERT INTO SELECT` changes (pr: #859) The following sequence of commands results in a deadlock with the upcoming changes.

<pre>
BEGIN;
ALTER TABLE b ...;
INSERT INTO a SELECT * FROM b;
</pre>

This is because the first command uses different connections from second command and holds exclusive locks on shard placements. (note: distributed deadlocks currently require master restarts or kill -9)

@marcocitus / @jasonmp85 - how hard is it to detect this scenario and error out?

**Comment by marcocitus** [comment]
We could probably disallow multi-shard modifications from DDL in transactions. I kind of lumped them together as part of the parallelisation changes, but it might make sense to separate them. On the other hand, creating a foreign key has the same problem (might block on a DDL command on the referenced table).

A possible fix is to always use the same connection for co-located shards. I wrote a simple prototype, but it needs a caching layer to avoid a huge performance penalty.
https://github.com/citusdata/citus/commit/9004852a1fb57cda5611d36e27c0df9d52111f57

**Comment by anarazel** [comment]
I think for now erroring out is fine. I just chatted with Onder, and I personally would prefer we merge #859 without fixing this, and then go on to fix this directly afterwards.
