### ISSUE TITLE
Problem with file-names which have single quotes - We cannot stage a file which has single-quotes to a foreign table, while copy from these files work.

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#90]
Problem with file-names which have single quotes - We cannot stage a file which has single-quotes to a foreign table, while copy from these files work.

**Comment by metdos** [comment]
Now, copying from a file with single quote works, but I don't know what is the meaning of this:
"which has single-quotes to a foreign table"

**Comment by marcocitus** [comment]
This is related to now defunct/removed file_fdw logic
