### ISSUE TITLE
Investigate PREPARE workaround to offer better ORM integration

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#904]
We're tracking our prepare support in #306. @metdos nicely documented our current behavior in his comment in https://github.com/citusdata/citus/issues/306#issuecomment-250475341

@anarazel noted that a short term hack/workaround for `PREPARE` could be to return a cost of 0 in the related code path for distributed plans. This way, Postgres wouldn't drop into the `PREPARE` code path; and we'd be able to offer a simpler integration story with different ORM tools.

I'm opening this issue to track investigating a potential workaround. If this works, we'd cover all scenarios except for the PL/PgSQL column in https://github.com/citusdata/citus/issues/306#issuecomment-250475341

**Comment by anarazel** [comment]
I have a prototype of this. Seems to work. There's two difficulties:
- It doesn't work for ```LANGUAGE sql``` type functions (plpgsql etc is fine)
- I've not yet figured out how to avoid a slowdown if prepared statements were used in a previously supported manner. We'd now plan considerably more often.

What do you guys think, are those acceptable tradeoffs? Or do we need to figure something out fixing one or both of them?

**Comment by ozgune** [comment]
@samay-sharma, @lfittl and I just chatted about this. These tradeoffs sound good to us!

We also had a clarification question. When we introduce this workaround, what would ``PREPARE``'s behavior be for local (non-distributed) Postgres tables?

**Comment by sumedhpathak** [comment]
@anarazel How long would it take to open up a PR based on the prototype? Thanks!
