### ISSUE TITLE
Add hint to unsupported DELETE commands to call related UDF

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#905]
Currently, we natively support `DELETE` commands that are only on the distribution column. Deleting old rows across shards, particularly in the context of data expiration, is quite common. We talk more about this use-case in #183.

Right now, when the user runs `DELETE` across multiple shards, we error out. In our docs, we then instruct our users to use `master_modify_multiple_shards()` / `master_apply_delete_command()` depending on the table's distribution method.

As a short term improvement, we should add a HINT to our error messages, and instruct our users to call the related UDF to delete old rows.

**Comment by marcocitus** [comment]
Closed after #1031
