### ISSUE TITLE
Cannot use shard pruning with ANY/ALL (array expression)

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#923]
Found when going through our documentation: http://docs.citusdata.com/en/v5.2/dist_tables/dml.html and running 

`SELECT master_modify_multiple_shards('DELETE FROM github_events WHERE repo_id IN (24509048, 24509049)');`

We get the error:

`
NOTICE:  cannot use shard pruning with ANY/ALL (array expression)
HINT:  Consider rewriting the expression with OR/AND clauses.
`

**Comment by ozgune** [comment]
@lithp / @begriffs -- It's curious that we provided this as an example in our v5.2 documentation. Do we know if this command used to work?

Also, is this issue related to #443 or #779?

**Comment by lithp** [comment]
I would assume it's not related to those tickets but I'll look into it more

**Comment by ozgune** [comment]
@lithp / @begriffs -- I ran through these steps in our documentation and had two questions.

First, when the user runs this command, do we see an error message or notice? When I run this command, I see the following. This signals to me that the command executed, but it didn't run in the most efficient way.

<pre>
postgres=# SELECT master_modify_multiple_shards(
postgres(#   'DELETE FROM github_events WHERE repo_id IN (24509048, 24509049)');
NOTICE:  cannot use shard pruning with ANY/ALL (array expression)
HINT:  Consider rewriting the expression with OR/AND clauses.
 master_modify_multiple_shards 
-------------------------------
                             0
(1 row)
</pre>

Second, I think we have two issues. (a) Can we apply shard pruning for queries that have ``IN (...)`` ? (b) Do we want to provide an example in our docs that generates a ``NOTICE`` / ``HINT`` message? Can we instead have an example that doesn't generate these messages and returns an output greater than 0?

When you opened this issue, did you have (a), (b), or both in mind?
