### ISSUE TITLE
Always pick router executor over task tracker executor

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#930]
Citus currently has three different executors:
1. Router executor: Queries that we can push down to a worker node
2. Real-time executor: Queries that span across worker nodes -- queries that touch usually touch less than ~500 shards and don't require repartitioning
3. Task-tracker executor: Queries that span across worker nodes -- queries that touch many shards or require repartitioning

Router executor offers full SQL coverage and it's also the most resource efficient.

We currently allow our users to pick between `real-time` and `task-tracker` executor types through the [citus.task_executor_type](http://docs.citusdata.com/en/v5.2/reference/configuration.html#citus-task-executor-type-enum). If we can plan a query for router execution, we know that it will always perform better than the other executors. We therefore automatically pick it over the `real-time` executor.

We however don't exhibit this behavior when the `task-tracker` is configured and this leads to inconsistent behavior. If we can push down the query to a worker node, we should always switch to the `router` executor.

**Comment by lithp** [comment]
Murat [agrees](https://github.com/citusdata/citus/blob/master/src/backend/distributed/planner/multi_router_planner.c#L2369) this should be changed :smile:
