### ISSUE TITLE
Add user-defined function to temporarily remove a worker node

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#931]
With #798, we are getting rid of `pg_worker_list.conf` and adding a new metadata table: `pg_dist_node`. 

From v6.0 onwards, we will introduce the worker list data in this metadata table, instead of a configuration file.

For adding/removing nodes, we will use two functions that require super-user permissions:

<pre>
master_add_node('nodename', nodeport);
master_remove_node('nodename', nodeport);
</pre>

When the user wants to permanently remove a node from the cluster, they will call `master_remove_node()`. If this node has any healthy shard placements, the function will error out and ask the user to invalidate or remove those shard placements (from the metadata).

We observed another common usage pattern for worker node names in `pg_worker_list.conf`, particularly for tables that have append distribution. In this pattern, if a worker node had a temporary failure, users would comment out that node's name in `pg_worker_list.conf` and send a `SIGHUP` to Citus. This way, Citus wouldn't try to reach that node until it came back up (usually a pg_ctl restart or machine reboot).

To continue to provide this behavior, we should add a sister function to `master_remove_node` to only temporarily remove a node from the membership list.

**Comment by marcocitus** [comment]
The current equivalent would be to delete the row from `pg_dist_node` and add it back later.

**Comment by ozgune** [comment]
I'm adding the v6.1 milestone with the intent to spend about a day on this and see if we can agree on a quick fix.

**Comment by begriffs** [comment]
Requires documentation in https://github.com/citusdata/citus_docs/issues/224

**Comment by mtuncer** [comment]
Here is the usage scenario
- citus cluster has node_1, node_2, node_3, there are existing tables on these nodes.
- user calls ```master_disable_node``` or something similar to ```master_remove_node``` for node_3. 
- node_3 will be removed from ```pg_dist_node``` but it will still serve queries on existing shards.
- no new shard could be created on node_3 since it is not in ```pg_dist_node```
- if user wants to create new shards on this one, node_3 must be added to ```pg_dist_node``` using ```master_add_node```

**Comment by mtuncer** [comment]
Changed this approach and opted for adding ```force``` parameter to ```master_remove_node```. It removed the node from pg_dist_node and propagates changes to other meta-data nodes. It displays a notice saying some queries may fail after this operation.

**Comment by jasonmp85** [comment]
> node_3 will be removed from `pg_dist_node` but it will still serve queries on existing shards

Is that actually true? I thought we usually checked whether a node was in `pg_dist_node` before including its placements in query planning?

**Comment by mtuncer** [comment]
not anymore,  logged an error about this during 6.0 release testing complaining about node still serving drop queries even if it is removed from pg_dist_node. #956.

**Comment by sumedhpathak** [comment]
@mtuncer This change needs documentation updates as well. See tag. Looks like we added a new UDF, and also a new parameter to the existing `master_remove_node` UDF. Both need changes in Docs. Could you add information about these changes to the related Docs issue?

**Comment by mtuncer** [comment]
documentation issue is updated
@sumedhpathak we did not change ```master_remove_node()```s parameters. It was an alternative solution to ```master_disable_node```,  we decided to add a new UDF rather than changing the existing one.

**Comment by metdos** [comment]
@sumedhpathak, given that @mtuncer added information about these changes to the related Docs issue, I think we can close this issue.

**Comment by sumedhpathak** [comment]
👍
