### ISSUE TITLE
Disallow master_apply_delete_command() on hash distributed tables

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#934]
Use of [master_apply_delete_command()](http://docs.citusdata.com/en/v5.2/reference/user_defined_functions.html#master-apply-delete-command) on hash distributed tables does not make sense. We should disallow this and error out.

**Comment by sumedhpathak** [comment]
Current behavior is to error out if a 'where-clause' criteria is specified. So the effect of this is to drop all the shards for hash-partitioned tables. Agreed we should disallow entirely for hash-partitioned tables since we have master_modify_multiple_shards now.

**Comment by metdos** [comment]
Similarly, we should also block the use of master_drop_all_shards() on hash-partitioned tables.

**Comment by marcocitus** [comment]
Well, we actually call master_drop_all_shards on hash-distributed tables from the DROP table trigger.

**Comment by metdos** [comment]
> Well, we actually call master_drop_all_shards on hash-distributed tables from the DROP table trigger.

Hmm, then maybe we can try to find a way to hide it from the user.

**Comment by lithp** [comment]
What if they actually want to drop all shards though? I can imagine wanting to change the shard count, especially while you're still experimenting with Citus.

**Comment by marcocitus** [comment]
> Hmm, then maybe we can try to find a way to hide it from the user.

It's not documented. We have quite a few UDFs which users probably shouldn't call (e.g. worker_drop_distributed_table), but they don't appear in documentation.

**Comment by metdos** [comment]
> What if they actually want to drop all shards though? I can imagine wanting to change the shard count, especially while you're still experimenting with Citus.

We are depreciating the old API. How are you planning to create shards? You can simply drop table and recreate it if you wish to play with different shard counts.
