### ISSUE TITLE
Whether citus is suitable for online transactions

### ISSUE THREAD

**Issue by hareteam** [citusdata/citus#948]
I would like to ask, citus is suitable for online transactions (like EBay, Amazon, etc.), thank you。
For example: In a transaction,write recorders  into more than one table 。

**Comment by ozgune** [comment]
@hareteam -- We'll reply to the question on in the [mailing list shortly](https://groups.google.com/forum/#!topic/citus-users/GJA9G6nOPcQ).

I'll close this issue in favor of the mailing list conversation. If you'd like to have a more interactive conversation, please also feel free to ping us over Slack.
