### ISSUE TITLE
Copy does not roll back

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#959]
aborting a transaction does not rollback ```copy```'ed rows. A warning message would have been nice.

```sql
postgres=# select * from t1;
 a | b 
---+---
(0 rows)

postgres=# begin; copy t1 from '/tmp/t1'; abort;
BEGIN
COPY 1
ROLLBACK
postgres=# select * from t1;
 a | b 
---+---
 1 | 1
(1 row)
```

Note : There is a discussion in transactional behavior for copy [here](https://github.com/citusdata/citus/issues/666)

**Comment by sumedhpathak** [comment]
@marcocitus Is this expected behavior? @mtuncer Could you try to see if 5.2 exhibits the same behavior?

**Comment by marcocitus** [comment]
Yes, this is how copy always worked. It's from before anything supported transaction blocks. We could rework it to use the multi_shard_transaction API now, though this will require a bit more work as of 6.0 because of the colocation changes.

**Comment by marcocitus** [comment]
Note that it does roll back on any error that occurs during the copy.

**Comment by marcocitus** [comment]
Copy uses 1PC/2PC now.
