### ISSUE TITLE
Reference Tables: Transactional behaviour

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#966]
With #879 we're planning to propagate the DML changes to reference tables via 2PC. There are two alternatives to implement this:

(i) Add 2PC capabilities to router executor  
(ii) Use existing multi-shard transaction API which already implements 2PC

**Comparison of both approaches:**

The basic behaviour would be the following: Whichever approach we pick, intermixing the other transaction type would fail the query. For instance, if we go with (i), we wouldn't be able to insert into a reference table then run a multi-shard modification query.

To be more specific, see the below 

* **Add 2PC capabilities to router executor**
```SQL

-- this should work
BEGIN;
INSERT INTO reference_table VALUES (...);
INSERT INTO colocated_distributed_table (...);
SELECT FROM reference_table X colocated_distributed_table -> which hits a worker (i.e. router executable selects)
END;

-- the followings wouldn't work (i.e., error out)
BEGIN;
INSERT INTO reference_table VALUES (...);
INSERT INTO colocated_distributed_table SELECT ... FROM ...;
END;

-- the followings wouldn't work too (i.e., error out)
BEGIN;
INSERT INTO reference_table VALUES (...);
SELECT master_modify_multiple_shards(...);
END;

-- similarly, any kind of multi-shard modifications would error out if 
-- intermixed with DML to reference table
```

* **Use existing multi-shard transaction API**

```SQL

-- the following would work given that all use multi-shard modifications
BEGIN;
INSERT INTO reference_table VALUES (...);
SELECT master_modify_multiple_shards(...);
INSERT INTO colocated_distributed_table SELECT ... FROM ...;
END;

-- the followings wouldn't work (i.e., error out)
BEGIN;
INSERT INTO reference_table VALUES (...);
INSERT INTO colocated_distributed_table VALUES (...);
END;

-- similarly, any kind of single-shard modifications would error out if 
-- intermixed with DML to reference table

```

In terms of implementation complexity, `Add 2PC capabilities to router executor` approach seems harder. However, @lfittl mentioned that it makes more sense to go with this approach considering prospective mx customers and rails integration.

I'll look into the implementation trade-offs and update the issue accordingly.

**Comment by onderkalaci** [comment]
As we discussed with @marcocitus, adding 2PC to router executor requires the following high-level changes:

* Wrap router connections within `TransactionConnection` struct.
* Call `PrepareRemoteTransactions()`
* Add `AbortRemoteTransactions()` / `CommitRemoteTransactions()` to the necessary place
*  Switch to 2PC when a modification is on a reference table.

**Comment by anarazel** [comment]
@onderkalaci 
It should be fairly straightforward to do this after #1020 is merged. You basically just would need to do
1) ```BeginOrContinueCoordinatedTransaction();  /* signal that we want transaction to be used remotely */
2) ```CoordinatedTransactionUse2PC();``` Force 2PC to be used
3) On each of the connections used: ```RemoteTransactionBeginIfNecessary(connectio);```, to signal that a transaction should be started 
4) On each of the connections used: ```MarkRemoteTransactionCritical(connection);```, to signal that each failure should cause a rollback of the entire transaction

Except for 2) and 4) that' show transactional router commands work already after #1020.

**Comment by onderkalaci** [comment]
With the new connection/transaction changes, this issue became obsolete. Reference table modifications go through router executor and obey the new connection/transaction rules. Thus, I'm closing the issue. 

(Just a note the transactional changes for reference tables checked-in #1058 )
