### ISSUE TITLE
Reference tables: Make them explicit

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#969]
Reference tables would have a single shard with replication of (# worker nodes). 

They would have some different characteristics such as replication, DML execution path and foreign key constraints compared to ordinary distributed tables.

This means that we should come up with a representation in the metadata to distinguish reference tables. 

Some thoughts on this: 
(i)  We could use pg_dist_colocation and treat tables with shard_count = 1 as reference tables. This relates to #962.
(ii) We could add another replication model (i.e., `REPLICATION_MODEL_REFERENCE_TABLE`), and explicitly have this in `pg_dist_partition`

**Comment by metdos** [comment]
I think another option was (iii) to use another partition method (such as 'all' or 'reference' instead of 'hash', 'append' etc.). However, this change would require more changes in different code paths.

**Comment by onderkalaci** [comment]
Though it includes more extensive changes, I'm leaning towards having a new `partition method`. (The name is TDB yet)

My reasons for that:
* First of all, it is `actually` a new partition method. 
  * In a very basic sense, we're not partitioning on any columns.
* Using `shard_count == 1` with hash partitioned table feels a lot hacky to me.
  *  Besides, it'd unnecessarily add the requirement of having hash function on a column.
  * Would need to do shard pruning, which we could avoid. 
  * We're planning to act differently than regular hash partitioned tables in some major operations such as `INSERT`. This could end up having `if hash_partitioned && shard_count == 1 && replication==#worker_count` kinds of checks, which are quite ugly.
* Using append/range partitioning is not even on my agenda given that we're trying to move towards hash partitioned world and I don't see it valuable to invest on more to those existing partitioning methods. Any objections/comments here?
* Also, having a new partitioning method could make updating exising reference tables to this new type much more smooth.
* My initial investigation shows that it requires extensive changes in the code, but, the changes would be very small in most cases. Below, I'm listing the items that we need to make sure that they work expceted before closing this issue:

* [ ] INSERT
  * [ ]  Function evaluation -- for all DMLs
   * [ ] Sequence support
   * [ ] Unique key violation -- Does this also apply to UPDATEs for reference tables?
* [ ] UPDATE/DELETE
   * [ ] Unique key violation -- Does this also apply to UPDATEs for reference tables?
* [ ] UPSERT on any column
* [ ] COPY TO/FROM
* [ ] EXPLAIN
	* [ ] EXPLAIN EXECUTE 
* [ ] SELECT -- various more tests
  * [ ] SELECT * FROM ref
  * [ ] SELECT * FROM ref where ..
  * [ ] SELECT * FROM ref X colocated_hash where ..
  * [ ] SELECT * FROM ref X append/range where ..
  * [ ] SELECT * FROM ref X ref on any column
  * [ ] Some router queries involving CTEs/JOINs/Subqueries etc
* [ ] INSERT INTO SELECT ...
   * [ ] Discuss co-locataion aspect of this tables
* [ ] Different schemas
* [ ] Transaction:
   * [ ] Currently only use regular router executor. 
   * [ ] Ensure that BEGIN; INSERT/UPDATE/DELETE ref .. works expected
   * [ ] Ensure that errors out if Multi-shard modifications exists in the same transaction
* [ ] Custom UDFs:
	* [ ] master_append_table_to_shard
	* [ ] master_apply_delete_command
	* [ ] master_create_empty_shard
	* [ ] master_copy_shard_placement
	* [ ] master_modify_multiple_shards
	* [ ] master_drop_all_shards
	* [ ] master_get_table_metadata
	* [ ] master_get_table_ddl_events
	* [ ] master_update_shard_statistics
	* [ ] Write functions and run queries involving those functions
* [ ] DROP TABLE
* [ ] DROP SCHEMA 
	* [ ] Test that it cascades to the reference tables as expected
* [ ] TRUNCATE
* [ ] DDL
	* [ ] CREATE/DROP INDEX - UNIQUE Constraints on any column
	* [ ] ALTER TABLE ADD COLUMN ... (and such)
	* [ ] ALTER TABLE SET SCHEMA [Not sure if this works with Citus?]
* [ ] CREATE TABLE AS SELECT * from ref 
* [ ] Shard rebalancer -- we could consider closing the issue without solving this now:
   * [ ] Make it fail for rebalance - replicate operations
* [ ] Composite Keys
	* [ ] Just a sanity check
	* [ ] Columns without hash functions should also work
* [ ] Prepared Statements
	* [ ] Also test with PL/PGSQL functions w/wout parameters
* [ ] Cursors
* [ ] MX
	* [ ] Make sure that only the coordinator can modifications on reference tables
* [ ] Foreign Keys
	* [ ] Simply do not allow, given that we decided not to include foreign keys for reference tables in 6.1


I'll check the above with @marcocitus to see if it makes sense to him as well. Any other feedback is welcome.

**Comment by onderkalaci** [comment]
Fixed by #1018, closing the issue.
