### ISSUE TITLE
Reference Tables: Adding a new node

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#971]
Reference tables would have a single shard with replication of (# worker nodes).

In an ideal world, when a user adds a new node with `master_add_node()`, the reference tables should  be replicated to the new node.

The simplest approach looks like using the infrastructure we have for `master_copy_shard_placement()`. 

Directly using `master_copy_shard_placement()` would fail on citus-public repo. But, I think it seems relatively easy to use the existing C interface for repairing the shard placement. 

I think the decision is more on whether we'd like to provide a very similar API as we have in citus-enterprise i.e., `ReplicateColocatedShardPlacement ()`. Also, this is semi-related with #962. If we mark all references tables as co-located with each other, we could simply use `ReplicateColocatedShardPlacement()` as it is.

**Comment by marcocitus** [comment]
Nasty question: What if the reference table contains a custom type?

**Comment by onderkalaci** [comment]
Another question from @marcocitus : 
> Will we continuously update the replication factor in pg_dist_colocation for reference tables? What if we have a special case, e.g. replication factor 0, or a reserved colocation group ID?

**Comment by metdos** [comment]
> What if we have a special case, e.g. replication factor 0, or a reserved colocation group ID?

@byucesoy, do you want to lobby for reserved colocation id :)

**Comment by byucesoy** [comment]
:) My main motivation for having reserved colocation id is that it would prevent mixing reference tables and other co-located tables. If we have different distribution type for reference tables, we may not need reserved colocation id for that purpose.

**Comment by onderkalaci** [comment]
We decided to change the behaviour with #1283.
