### ISSUE TITLE
Reference Tables: Removing a new node

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/citus#972]
Currently, when user tries to remove a node from the cluster, and if there exists an active placement on it, the user ends-up with an error:

```SQL
SELECT master_remove_node('localhost', 9700);   
ERROR:  you cannot remove a node which has active shard placements
```

However, if  there exist any reference tables on the cluster, it'll always be on all nodes and be in an active state. Thus, removing a node becomes impossible.

The simplest way would be to error out with a descriptive message saying that manually remove the metadata and drop the target placement.

A relatively simple solution would be to mark the placements of reference tables on the removed node as `INACTIVE` under the covers and so allow the `remove_node` operation. (Or even remove the related rows from `pg_dist_shard_placement`)

The more comprehensive solution would be to drop the placements of all reference tables on the removed node first, and then proceed with the operation. But, I guess some users may not want to the placements being dropped.

We marked this nice-to-have for 6.1. But, I think it is worth implementing the simplest solution at least.

This is semi-related to #931

**Comment by aamederen** [comment]
Actually, when we call `master_remove_node`, I believe in the proper fix, we should error out if and only if that node contains any one and only active placement of a shard i.e. we lose the data of a shard.
