### ISSUE TITLE
CREATE SEQUENCE doesn't propagate to workers

### ISSUE THREAD

**Issue by lithp** [citusdata/citus#977]
This is unfortunate if you want to `CREATE SEQUENCE` and then `ALTER TABLE SET DEFAULT nextval()`.

I had thought there was already a ticket for this but can't find it.

**Comment by ozgune** [comment]
@lithp -- Could you clarify this issue more with specifics?

This issue recently came up in https://gitlab.com/gitlab-com/infrastructure/issues/1206 and we're looking to understand its applicability for that use-case.

**Comment by ozgune** [comment]
@lithp / @metdos -- Do you remember this issue's specifics?

We now have full sequence support in Citus, and I couldn't remember why we had this issue.

**Comment by marcocitus** [comment]
It should only matter in MX. We don't use sequences on workers otherwise.

**Comment by lithp** [comment]
Closing because sequences don't need to be propogated in the non-MX case, and they are propogated in the MX case.

**Comment by marcocitus** [comment]
Sequences generated using serial are propagated in the MX case. Manually created sequences are not, but it seems better to open an MX-specific issue for that, or general object propagation (#1026).
