### ISSUE TITLE
[Citus 6] Sharded data not balance in some workers

### ISSUE THREAD

**Issue by maestrofx** [citusdata/citus#984]
Hi all,
My team has been working on tens of gigs data with the power of Citus 6.
I found weird behaviour in the sharding process.  Say 1 master with 3 workers.
The data sharded was not balanced. Only in spesific sharded table in worker 1. 
Based on Citus documentation,  rebalance_table_shards() is only available in Citus Enterprise.

For later, we consider to use the Citus Enterprise in production, but right now,  we are still in prototyping with that data.

Any people experienced with this problem before?

Thank you.

**Comment by onderkalaci** [comment]
We have the same conversation on [citus-users group](https://groups.google.com/forum/#!topic/citus-users/1bsWiPsVdt0), so closing the issue.
