### ISSUE TITLE
Productize PostgreSQL upgrade steps with Citus

### ISSUE THREAD

**Issue by mtuncer** [citusdata/citus#987]
Upgrading PostgreSQL from 9.5 to 9.6 have few non trivial steps that pg_upgrade does not perform.

One first upgrade to Citus 6.0 on existing PostgreSQL instance, then upgrade postgresql version to 9.6.

The first one is trivial, ```alter extension citus update``` takes care of everything needed. However,  the second part requires more attention on master. 

1. backup citus metadata
1. run pg_upgrade
1. restore citus medatadata
1. some bookkeeping steps for triggers and table dependencies.
  
Upgrading workers is simpler
1. upgrade to Citus 6.0 in PostgreSQL 9.5
1. run pg_upgrade

We have the pre/post upgrade scripts available, it would be nice to have them in the product.

**Comment by mtuncer** [comment]
Realized I have this issue open with different wording at #980

**Comment by marcocitus** [comment]
We should probably have another look at this with PG11 coming up. The [current process](http://citus-docs.readthedocs.io/en/v7.5/admin_guide/upgrading_citus.html) is quite involved and prone to errors (e.g. https://github.com/citusdata/citus/issues/2329 )

**Comment by marcocitus** [comment]
Fixed by https://github.com/citusdata/citus/pull/2877
