### ISSUE TITLE
Tests: Automate Test Cluster Creation

### ISSUE THREAD

**Issue by metdos** [citusdata/citus#989]
We should create an automated system to create test cluster easily.

**Comment by metdos** [comment]
@lithp, could you think about possible solutions and how much time they will require?

We used to use Cloudformation for this, it seems as one of the good options.

**Comment by metdos** [comment]
Related to #890

**Comment by ozgune** [comment]
@metdos / @lithp -- We had an initial conversation and an internal email thread on automating test cluster's creation. Could we write down our decisions in this issue? (Do you have agreement on the points @onderkalaci brought up on this one?)

**Comment by metdos** [comment]
@ozgune, @lithp will send his final document today, and we are planning to discuss it tomorrow in Istanbul office (comments are also welcome on the email thread). I think, @lithp can share our final decisions tomorrow here. @lithp, does this sound good?

**Comment by lithp** [comment]
Yep, nothing to add

**Comment by lithp** [comment]
[Here's a doc](https://docs.google.com/a/citusdata.com/document/d/1BvYH1vpZaHYandKLtWTOJ-Ne4JuDYnZghuVhNSXsj78/edit?usp=sharing) with the proposal plan (only viewable by citusdata.com). Some additional ideas were floated during our meeting but they didn't change the plan at all, only added some things which would be nice to have and refined what the UX might be like.

**Comment by metdos** [comment]
@lithp, could you add individual tasks to the issue description as a checklist as we talked this morning? Maybe we can track them in the new test repo (to be created), but we should list them somewhere.

@onderkalaci will review them today or early next week. We can update them according to his feedback but no need to wait for him for the initial list :)

**Comment by lithp** [comment]
- [ ] Create cloudformation template which only spins up a cluster
- [ ] Decide whether to use bash scripts or puppet / fabric
- [ ] Create happy-path script which only sets up PG and Citus to enable documentation testing (it should accept which version of PG and which branch/commit of Citus to use)
- [ ] Between versions of Citus the steps to setup a cluster change, how do you accommodate that? Likely by adding a setup file to the Citus repo?
- [ ] add the ability to specify which additional programs are installed and create a target for feature testing (which wants JDBC)
- [ ] add the ability to specify which additional extensions are installed and create a target for integration testing (which wants session analytics and shard rebalancer)
- [ ] Add the ability to specify additional files to include and commands to run on the citus cluster (like creating and staging tables). Write a target for TPCH testing.
- [ ] Write the sample queries DML testing should use and a target for it.
- [ ] Add the ability to build pg/citus with custom configure flags (--enable-debug) and write a target for the Valgrind testing
- [ ] add the ability to have multiple simultaneous versions of pg and citus installed in the target, then create an upgrade testing target
- [ ] Write a target for citus enterprise testing
- [ ] Automate Integration Testing: Create a script which runs the session analytics and shard rebalancer regression tests, and an additional regression test to test behavior, then add that script to Travis (which first sets up the integration testing target).

Onder and the rest of the team had some feedback on the order these should be done in, which I haven't yet incorporated into the above list.

**Comment by sumedhpathak** [comment]
@metdos @lithp Is this a high-level issue which captures #990 also?
Are we creating a new repo for this somewhere?

**Comment by metdos** [comment]
> @metdos @lithp Is this a high-level issue which captures #990 also?
> Are we creating a new repo for this somewhere?

No, we already have a high-level issue #890. @lithp, could you move related check boxes to #990?

**Comment by metdos** [comment]
> Are we creating a new repo for this somewhere?

@lithp will add CloudFormation changes to existing repo, and open a new repo for other tools. @lithp, could you correct me if I'm wrong.

**Comment by metdos** [comment]
@lithp, could you also add your notes about why we picked fabric over puppet here?

**Comment by onderkalaci** [comment]
> @lithp, could you also add your notes about why we picked fabric over puppet here?

My initial observation: 
* Puppet is great for installing standard packages and configuring them such as `Install postgres and update configuration file as specified`. More targeting for IT people where writing `puppet manifest` file is acceptable.
* Fabric is also great for installing standard packages and configuring them. However, in this case, the author (which is us), needs to write some very basic scripting to install stuff. The flip side of this is that fabric seems very flexible and easily extendable as our needs evolve over time. In the long run, fabric seems to allow us to add new feature more easily.

@lithp please feel free to share your observations as well so that others also could chime in if necessary.

**Comment by lithp** [comment]
I've created a new repo to hold all the tooling for out testing automation, and opened [a ticket](https://github.com/citusdata/test-automation/issues/1) to track progress.

**Comment by lithp** [comment]
It was more than just puppet, I also looked into chef, ansible, salt, etc.

I think puppet, and especially ansible, are likely more suitable than fabric (which I ended up choosing) for this task. They're designed for configuring systems just so and putting files in the right place and transitioning from one state to another, however they all have complicated configuration syntaxes and if the idea is to make our testing more agile replacing CloudFormation with another complicated format doesn't seem appropriate.

Fabric requires that we write a little more plumbing, but in the end will be easier for people who aren't me to adapt to our future needs.

**Comment by ozgune** [comment]
For documentation purposes, I'm copy/pasting an internal email thread (re: Testing Improvements, any ideas?) on what we'd like to accomplish with testing automation.

---

@onderkalaci's biggest pain point is to repetitively setup different clusters with different variables during the testing and manually operating on the cluster:

* Optional: Ability to pick operating system of the clusters (ubuntu - amazon linux)
* Ability to pick Postgresql version (assert vs non-assert)
* Ability to pick Citus version (Branch is more useful)
* Install Shard rebalancer (branch is more useful) / hll / session analytics / cstore_fdw (branch is more useful)
* Cluster setup 
    * how many workers 
    * what are worker and master instances 
    * Optional: having the ability to have different worker instance types and citus/postgres/OS versions (for some more extreme testing)
* Optional: Having predefined tables and data on the cluster. For instance, a shell script such that it allows creating tables and loading data for tpch/github events/wikipedia edits/ a composite key partition column
    * load_data  --type=citus --partition=hash --shard_count=32 --replication_factor=2 --data_type=github_events --size=10GB --method=copy (or inserts for hash)
    * Enable to create the tables without data
    * Instead of size, be able to define row_count
    * Change partition column for the predefined tables during the setup
    * Allow creating with/without indexes. For instance, for faster data loading I'd prefer not to have indexes. Or, for faster querying I'd prefer to have the indexes. But, this is a minor detail.
    * Allow running concurrent of these scripts
    * Allow the same script to operate on Postgres tables instead of Citus tables as well
    * Any other parameters?
    * A README that explains the parameters :)
* Optional: Having a JDBC client on the master, ready to run queries.
    * What about versions of JDBC? Similarly, there is a "version" config on the JDBC connection string. Is it worth to be able to change them?
* Optional: Ability to run the regression tests of both Citus and postgresql        
* Optional: Allow failing worker nodes
    * citus_fail_worker --host=10.0.0.1 --port=5432 --method = (kill network connection or pg_ctl stop force or kill -9)      
* Optional: Having a script that re-initializes all the databases on the cluster (i.e., run initdb's to have a clean test environment)
* Optional: Enable/disable logging on all nodes or a given node.
    * Optional: Pipe the files to the master if possible such that /tmp/worker_logs/10.0.0.1_log
* Have pg_bench present (I think this is already the case when postgres is installed)
    * Optional: Include some example pg_bench query files
* Optional: Be able to change config values from the command line (allow master as well)
    * citus_change_config --host=10.0.0.1, localhost, 10.0.0.2 --port=5432,5432,5432 --config=sync_commit --value=off
    * I think this is possible through citustools which I've not experimented yet. If so, skip this item at all.
* Optional: A script that could compare the contents of the two replicas of all (or a given) shards.
    * citus_compare_shard_replicas --tablename=wikipedia_edits shards=all
    * Errors out if they are not exactly the same

The above items are useful for both automating the cluster setup and operating on the cluster. I marked many operational items as optional given that it is not in the scope and I'm not sure if they all make sense (and be useful) to the other testers as well. However, from my point of view, they could dramatically decrease the time I spent on the testing. This is valid for both release testing and the testing I do in feature development.

**Comment by lithp** [comment]
This has been completed, check out the massive readme [here](https://github.com/citusdata/test-automation) for more.
