### ISSUE TITLE
Update pg_upgrade to handle copying of (a) pg_dist catalog tables (b) copy over pg_foreign_file/cached/* (c) update pg_dist_shardid_seq to latest value

### ISSUE THREAD

**Issue by Jhanbanan** [citusdata/citus#99]
Update pg_upgrade to handle copying of (a) pg_dist catalog tables (b) copy over pg_foreign_file/cached/\* (c) update pg_dist_shardid_seq to latest value

**Comment by ozgune** [comment]
#980 looks like a duplicate of this issue. I'm therefore closing this issue in favor of that one.
