### ISSUE TITLE
any values support

### ISSUE THREAD

**Issue by Baznu** [citusdata/citus#991]
Is it possible to integrate support of any values to citus?

With Citus 6 I get the following error:

> Error:  cannot perform distributed planning on this query

I could use IN or ANY(ARRAY... ) expression, but that way is much slower. 
Seems like there are similiar experiences/requests in issue: #443 and #779 

It's a postgres related problem, that the queryplanner is kinda slow with IN(<huge list of primitives>) and the best way I found to get around this is ANY VALUES

**Comment by sumedhpathak** [comment]
@Baznu Thanks for reporting. We already have #443 for tracking this issue. A few questions to better understand: What performance differences have you observed? How many values do you have in the clause itself? Thanks.

**Comment by Baznu** [comment]
ANY VALUE query runs 3 seconds, IN / ANY(ARRAY ) runs up to 2 minutes.

We have 8000 - 12000 values in the filter clauses

**Comment by ozgune** [comment]
@Baznu -- if you have an example table schema and query, could you share it with us?

I'm also planning to post the info in this issue into #443. Once we have all the details, I'm planning to close this issue in favor of that one. If that doesn't work, could you let us know?

**Comment by ozgune** [comment]
I copy/pasted the information in this issue to #443 and I'm closing this issue in favor of that one. If you have further details, could you post them in #443?

Also, if you think we should keep both issues open, please feel free to reply with a comment.
