### ISSUE TITLE
Reduce default value for citus.shard_replication_factor to 1

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus#998]
Citus currently sets the default value for [citus.shard_replication_factor](http://docs.citusdata.com/en/v6.0/reference/configuration.html?highlight=replication%20factor#citus-shard-replication-factor-integer) to 2. When this value is set, Citus uses its built-in statement based replication model. This model caused a number of engineering challenges in the Citus 6.0 release, particularly around multi-tenancy features.

* We're planning to drop the default value for ``citus.shard_replication_factor`` to 1 in Citus 6.1.
* We should look to communicate why we're making this change. I'll highlight some of the motivations in below, and our communication needs to be much more thorough.
* Users will still be able to increase the replication factor. We'd probably discourage them from doing so for the multi-tenant use case on-prem.

We have several motivations for reducing the default value. From a use-case standpoint, Citus currently shines in one of two use-cases:

(1) You have a multi-tenant application, and you'd like to scale out your [multi-tenant database](https://www.citusdata.com/blog/2016/10/03/designing-your-saas-database-for-high-scalability/). In these cases, particularly if you're using your multi-tenant database for OLTP purposes, you care deeply about data integrity across multiple tables.

In Citus 6.0, we implemented several important features around multi-tenancy, such as foreign keys. With Citus' statement-based replication model, it's pretty hard to enforce those guarantees while also providing high availability: https://github.com/citusdata/citus/issues/810

(We may also have other issues around locking and deadlocks in certain write patterns (#861) that may require further investigation.)

It's also worth noting that issue #810 only exhibits itself when we use Citus' statement-based replication. Citus Cloud uses streaming replication for HA. Therefore, Citus Cloud users always set ``shard_replication_factor`` to 1 even when they have streaming replication turned on.

(2) You have a real-time application. You'd like to ingest large volumes of data and also run analytical queries that take <1s. Our customers who have this use-case use either hash or append distribution to address this use-case. For this use-case, if the customer's on-prem (not Citus managed cloud), they typically would want the ``shard_replication_factor`` to be 2 or higher.

We looked at these two use cases after our v6.0 release. We then weighed providing a safe/desirable implementation in the multi-tenant use case versus informing our customers who have real-time applications. We also evaluated our on-prem/cloud versus Citus Cloud deployments.

Based on these criteria, we're planning to reduce the default replication factor value to 1 in Citus 6.1. For users who have real-time applications, we need to inform them and ask them to increase their setting to 2 when they upgrade to 6.1.

**Comment by ozgune** [comment]
I'm also adding a checklist of items on the communication and engineering side. For the engineering question, we may want to open up another issue.

* [ ] Survey users who have real-time applications and ask them about their current ``shard_replication_count`` setting
* [ ] Write up a blog post that explains the two different replication models customers use in production. Explain how and why these models evolved
* [ ] Open up an issue in citus_docs that explains two different replication models for Citus
* [ ] Send an email to citus-users and also Citus' Slack channel on our decision to reduce the default value for ``shard_replication_factor``
* [ ] Open up an issue in citus_docs to document our decision to reduce the default value for ``shard_replication_factor``
* [ ] (tbd) Follow up with Citus customers who are upgrading their clusters to v6.1 on this decision

**Comment by marcocitus** [comment]
We also need to decide how a table becomes an MX table, or rather gets repmodel 'streaming'. We added a repmodel column in pg_dist_partition to distinguish between tables which are replicated by the 'coordinator' and tables that are guaranteed to use 'streaming' replication and can thus be synced to workers.

A 'streaming' table has just one restriction compared to a 'coordinator' table: Its replication factor must remain 1.

One option I've discussed with @aamederen and @metdos is to introduce a new GUC along the lines of `default_replication_model` which could either be 'coordinator' or 'streaming'. If it is set to 'streaming', then then  table will be synced to workers, but the replication factor cannot be increased.

Another option is to treat all tables with replication factor 1 as 'streaming' tables and sync them with MX.  This means you can never increase the replication factor later on, which might be ok.

If we take the second approach, an implication of setting `shard_replication_factor` to 1 is that every new hash-distributed table automatically becomes an MX table. 

Note that we don't actually sync the metadata for an MX table unless you explicitly call `sync_metadata_to_node` on workers, per #997, which means there's no immediate cost to marking a table as having repmodel 'streaming' compared to 'coordinator' unless you explicitly sync metadata to workers as well.

**Comment by begriffs** [comment]
Requires documentation in https://github.com/citusdata/citus_docs/issues/219

**Comment by marcocitus** [comment]
We currently use the `citus.shard_replication_factor` setting in some mission-critical parts of the code that might affect users that have existing (or new) tables with a higher replication factor:

For example, the default task assignment algorithm in the physical planner uses this setting to iterate over the placements:
https://github.com/citusdata/citus/blob/master/src/backend/distributed/planner/multi_physical_planner.c#L4955

It seems like that code might cause failures if we lower the setting as we'd skip over secondary placements.

**Comment by marcocitus** [comment]
Trying this out, I don't actually observe failures, but rather starvation of the node that does not have first replicas (no longer greedy).

```
postgres=# SELECT * FROM pg_dist_shard_placement;
 shardid | shardstate | shardlength | nodename  | nodeport | placementid 
---------+------------+-------------+-----------+----------+-------------
  102041 |          1 |           0 | localhost |     9700 |          68
  102042 |          1 |           0 | localhost |     9700 |          69
  102043 |          1 |           0 | localhost |     9700 |          72
  102040 |          1 |           0 | localhost |     9700 |          77
  102041 |          1 |           0 | localhost |     9701 |          78
  102042 |          1 |           0 | localhost |     9701 |          79
  102043 |          1 |           0 | localhost |     9701 |          80
  102040 |          1 |           0 | localhost |     9701 |          81
(8 rows)

postgres=# SET citus.shard_replication_factor TO 2;
SET
postgres=# EXPLAIN SELECT * FROM test;
                                   QUERY PLAN                                   
--------------------------------------------------------------------------------
 Distributed Query into pg_merge_job_0037
   Executor: Real-Time
   Task Count: 4
   Tasks Shown: All
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Seq Scan on test_102040 test  (cost=0.00..32.60 rows=2260 width=8)
   ->  Task
         Node: host=localhost port=9701 dbname=postgres
         ->  Seq Scan on test_102041 test  (cost=0.00..32.60 rows=2260 width=8)
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Seq Scan on test_102042 test  (cost=0.00..32.60 rows=2260 width=8)
   ->  Task
         Node: host=localhost port=9701 dbname=postgres
         ->  Seq Scan on test_102043 test  (cost=0.00..32.60 rows=2260 width=8)
 Master Query
   ->  Seq Scan on pg_merge_job_0037  (cost=0.00..0.00 rows=0 width=0)
(18 rows)

postgres=# SET citus.shard_replication_factor TO 1;
SET
postgres=# EXPLAIN SELECT * FROM test;
                                   QUERY PLAN                                   
--------------------------------------------------------------------------------
 Distributed Query into pg_merge_job_0035
   Executor: Real-Time
   Task Count: 4
   Tasks Shown: All
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Seq Scan on test_102040 test  (cost=0.00..32.60 rows=2260 width=8)
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Seq Scan on test_102041 test  (cost=0.00..32.60 rows=2260 width=8)
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Seq Scan on test_102042 test  (cost=0.00..32.60 rows=2260 width=8)
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Seq Scan on test_102043 test  (cost=0.00..32.60 rows=2260 width=8)
 Master Query
   ->  Seq Scan on pg_merge_job_0035  (cost=0.00..0.00 rows=0 width=0)
(18 rows)
```

**Comment by ozgune** [comment]
@marcocitus -- I have a clarification question.

If the user starts with ``citus.shard_replication_factor`` set to 1, creates their distributed tables, and runs this query, do they still observe this starvation behavior? Or does this become an issue when they have ``citus.shard_replication_factor`` set to 2, create distributed tables, and then reduce the replication factor?

**Comment by marcocitus** [comment]
> If the user starts with citus.shard_replication_factor set to 1, creates their distributed tables, and runs this query, do they still observe this starvation behavior?

No, only when there is an existing table with replication factor > 1.

**Comment by anarazel** [comment]
This was implemented via #1151 - do we want to keep the issue open due to @marcocitus's concerns above? Or should we create a separate issue for the assignment policy stuff?

**Comment by sumedhpathak** [comment]
We haven't evaluated all the items from Ozgun's comment here: https://github.com/citusdata/citus/issues/998#issuecomment-263382678. 

Specifically:
* [ ] Survey users who have real-time applications and ask them about their current shard_replication_count setting
* [ ] Send an email to citus-users and also Citus' Slack channel on our decision to reduce the default value for shard_replication_factor
* [ ] How do existing Citus customers upgrade their clusters? What are upgrade states?
* [ ] (tbd) Follow up with Citus customers who are upgrading their clusters to v6.1 on this decision

@jasonmp85 If I recall, we also discussed documenting various uses of shard_replication_factor in the planner/other parts of the code. Did we document those somewhere?

**Comment by jasonmp85** [comment]
Can this be closed?

**Comment by jasonmp85** [comment]
Ping; can we close this yet?

**Comment by ozgune** [comment]
Yes, we can now close this issue.

**Comment by theromis** [comment]
sorry for asking in old thread, just trying to make citus workers failover, and easiest way to do it was just make `citus.shard_replication_factor = 2` makes cluster stable, otherwise I have to add haproxy and duplicate every worker with follower plus some detections scripts which leads in my opinion to much more problems.

Can I still use this option or it been completely deprecated?

**Comment by gnat** [comment]
Agreed, this feature would go a long way to reducing operational complexity.
